Repository 1Panel-dev/1Panel, pull requests merged in 2023-05, with the labels that each got.

#856 fix: redis 按钮位置调整
  frontend/src/views/database/mysql/index.vue
  frontend/src/views/database/redis/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#854 feat: 增加已安装应用操作的执行时间
  frontend/src/api/modules/app.ts
Labels: dev, lgtm, approved

#855 fix: 时区问题修改
  backend/app/api/v1/cronjob.go
  backend/app/api/v1/monitor.go
  backend/cron/cron.go
  backend/middleware/password_expired.go
  backend/utils/common/common.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#860 fix: 初始化密码时，对密码进行加密操作
  backend/init/migration/migrations/init.go
  backend/init/viper/viper.go
  frontend/src/components/error-message/unsafe.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#861 feat: 创建网站支持 ipv6
  backend/app/service/website.go
  backend/app/service/website_utils.go
  backend/utils/nginx/components/server.go
  cmd/server/nginx_conf/website_default.conf
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#866 fix: 限制描述长度
  backend/app/dto/common_req.go
  backend/app/dto/setting.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#867 fix: 指定 IP 输入增加提示信息
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/host/firewall/port/operate/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#871 feat: 升级 gin 版本到 v1.9.0
  go.mod
  go.sum
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#872 fix: 容器创建端口校验修改
  backend/app/service/container.go
  frontend/src/views/container/container/create/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#873 fix: 修改初始化错误返回
  backend/app/service/auth.go
  backend/constant/errs.go
  backend/i18n/lang/en.yaml
  backend/i18n/lang/zh.yaml
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#874 fix: 删除初始化用户界面及接口
  backend/app/api/v1/auth.go
  backend/app/dto/auth.go
  backend/app/service/auth.go
  backend/router/ro_base.go
  cmd/server/docs/docs.go
  cmd/server/docs/swagger.json
  cmd/server/docs/swagger.yaml
  frontend/src/api/interface/auth.ts
  frontend/src/api/modules/auth.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/login/components/login-form.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#875 fix: 解决反向代理停用无法删除的问题
  backend/app/service/website.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#876 fix: 解决列表查询输入框刷新的问题
  frontend/src/views/app-store/installed/index.vue
  frontend/src/views/container/compose/index.vue
  frontend/src/views/container/container/index.vue
  frontend/src/views/container/image/index.vue
  frontend/src/views/container/network/index.vue
  frontend/src/views/container/repo/index.vue
  frontend/src/views/container/template/index.vue
  frontend/src/views/container/volume/index.vue
  frontend/src/views/cronjob/index.vue
  frontend/src/views/database/mysql/index.vue
  frontend/src/views/host/firewall/ip/index.vue
  frontend/src/views/host/firewall/port/index.vue
  frontend/src/views/host/terminal/host/index.vue
  frontend/src/views/log/login/index.vue
  frontend/src/views/log/operation/index.vue
  frontend/src/views/setting/snapshot/index.vue
  frontend/src/views/website/website/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#877 fix: 修改用户名长度限制
  frontend/src/global/form-rules.ts
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#878 fix: 解决反向代理网站停止不生效的问题
  backend/app/service/website_utils.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#879 fix: 解决解压 mac 压缩文件失败的问题
  backend/utils/files/file_op.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#881 feat: 监控设置改到【主机-监控】菜单内
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/routers/modules/host.ts
  frontend/src/routers/modules/setting.ts
  frontend/src/views/host/monitor/index.vue
  frontend/src/views/host/monitor/monitor/index.vue
  frontend/src/views/host/monitor/setting/index.vue
  frontend/src/views/setting/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#882 增加安全问题联系人
  SECURITY.md
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#883 feat: 搜索子目录增加提示
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/host/file-management/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#884 fix: 证书创建校验修改
  backend/app/service/setting.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#887 fix: 数据库创建重名用户问题修改
  backend/app/service/database_mysql.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#891 chore: remove console.log
  frontend/src/views/app-store/detail/index.vue
Labels: do-not-merge/release-note-label-needed, dev

#892 feat: 网站列表增加网站目录跳转功能
  backend/app/service/website.go
  frontend/src/views/website/website/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#895 fix: mfa 启用时，增加时间同步提示信息
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/setting/safe/mfa/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#896 fix: 解决文件搜索不存在的资源后，点击下面存在的目录也会提示资源不存在的问题
  frontend/src/views/host/file-management/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#899 feat: 网站新增域名，自动放开相应端口
  backend/app/service/app.go
  backend/app/service/website.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#900 feat: 网站域名跳转增加端口
  frontend/src/views/website/website/config/basic/domain/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#901 feat: 非静态网站和运行环境网站隐藏网站目录权限设置
  frontend/src/views/website/website/config/basic/site-folder/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#902 fix: 优化编排删除提示信息
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/zh.ts
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#904 fix: 创建编排时，默认显示编辑模式
  frontend/src/views/container/compose/create/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#905 feat: ssl 设置增加重启提示信息
  backend/utils/ssl/ssl.go
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/setting/safe/ssl/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#908 fix: 解决计划任务部分脚本执行没有输出的问题
  backend/app/api/v1/file.go
  backend/app/service/cronjob_helper.go
  backend/utils/cmd/cmd.go
  frontend/src/views/cronjob/record/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#909 fix: 解决应用列表页面搜索之后点击安装没响应的问题
  frontend/src/views/app-store/apps/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#910 fix: 解决同名反向代理失败导致文件被删除的问题
  backend/app/service/website.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#919 feat: 文件搜索框样式调整
  frontend/src/views/host/file-management/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#921 feat: 解决时区获取不到导致的网站自动停止的问题
  backend/cron/job/ssl.go
  backend/cron/job/website.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#925 feat: 增加 iptables 设置修改提示信息
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/container/setting/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#926 fix: 解决删除 Openresty 之后网站列表页面报错的问题
  backend/app/service/website.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#930 fix: 解决停止一键部署网站失败的问题
  backend/app/service/website_utils.go
  backend/utils/nginx/components/server.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#931 fix: 提示信息国际化修改
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/container/setting/index.vue
  frontend/src/views/setting/safe/ssl/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#952 fix: 修复文件列表总共条数显示问题
  backend/utils/files/fileinfo.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#948 Fix maccms rewrite configuration file error
  cmd/server/nginx_conf/rewrite/maccms.conf
Labels: do-not-merge/release-note-label-needed, lgtm, approved

#951 feat: 升级badger版本到v4
  backend/init/cache/badger_db/badger_db.go
  backend/init/cache/cache.go
  go.mod
  go.sum
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#954 fix: 解决登录情况下，输入任意路由跳转到安全入口的问题
  frontend/src/api/helper/check-status.ts
  frontend/src/api/index.ts
  frontend/src/routers/index.ts
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#956 feat: 应用商店同步改为异步操作
  backend/app/api/v1/app.go
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/app-store/apps/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#960 feat: app.yaml 增加 username 和 password 参数
  backend/init/viper/viper.go
  cmd/server/conf/app.yaml
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#964 Update README.md
  README.md
Labels: do-not-merge/release-note-label-needed

#970 fix: 解决验证码加载失败的问题
  frontend/src/views/login/components/login-form.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#971 fix: 忽略概览页异常数据
  frontend/src/views/home/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#977 fix: 解决本地备份账号更新失败的问题
  backend/app/service/backup.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#980 fix: 解决运行环境版本与已安装应用版本不一致的问题
  frontend/src/views/website/runtime/create/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#981 feat: 限制 PHP 应用升级
  backend/app/service/app_utils.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#982 fix: 优化抽屉中操作对象的名称显示
  frontend/src/views/container/compose/detail/index.vue
  frontend/src/views/container/compose/edit/index.vue
  frontend/src/views/container/container/index.vue
  frontend/src/views/container/container/log/index.vue
  frontend/src/views/container/container/monitor/index.vue
  frontend/src/views/container/container/rename/index.vue
  frontend/src/views/container/container/terminal/index.vue
  frontend/src/views/container/repo/operator/index.vue
  frontend/src/views/container/template/operator/index.vue
  frontend/src/views/cronjob/operate/index.vue
  frontend/src/views/database/mysql/index.vue
  frontend/src/views/database/mysql/password/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#983 fix: ntp 依赖修改
  backend/app/api/v1/setting.go
  backend/utils/ntp/ntp.go
  go.mod
  go.sum
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#984 fix: 容器监控适配部分单核系统
  backend/app/service/container.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#985 feat: 文件操作增加名称显示
  frontend/src/api/interface/file.ts
  frontend/src/views/host/file-management/change-role/index.vue
  frontend/src/views/host/file-management/chown/index.vue
  frontend/src/views/host/file-management/code-editor/index.vue
  frontend/src/views/host/file-management/compress/index.vue
  frontend/src/views/host/file-management/decompress/index.vue
  frontend/src/views/host/file-management/detail/index.vue
  frontend/src/views/host/file-management/index.vue
  frontend/src/views/host/file-management/rename/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#988 fix: 镜像导出增加默认值
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/container/image/index.vue
  frontend/src/views/container/image/save/index.vue
  frontend/src/views/container/image/tag/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#990 fix: 解决密码过期后重定向到登录页的问题
  frontend/src/api/index.ts
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#994 fix: 解决安全入口情况下升级后页面无法打开的问题
  frontend/src/components/system-upgrade/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1004 Update README.md
  README.md
Labels: do-not-merge/release-note-label-needed

#1011 fix: 获取网站日志时，先检查一下日志文件大小，超过10M时直接报错
  backend/app/service/website.go
  backend/constant/errs.go
Labels: do-not-merge/release-note-label-needed, lgtm, approved

#1009 fix: 端口校验正则表达式修改
  frontend/src/utils/util.ts
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1016 fix: 解决网站设置切换到 HTTPS 控制台报错的问题
  frontend/src/views/website/website/config/basic/https/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1019 fix: 解决数据库用户指定多个 ip 无效的问题
  backend/app/service/database_mysql.go
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/database/mysql/create/index.vue
  frontend/src/views/database/mysql/password/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1020 fix: 限制应用失败情况下启动应用
  backend/app/service/website.go
  backend/constant/errs.go
  frontend/src/views/app-store/installed/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1022 fix: 补全 swagger 文档
  backend/app/api/v1/firewall.go
  cmd/server/docs/docs.go
  cmd/server/docs/swagger.json
  cmd/server/docs/swagger.yaml
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1023 fix: 解决网站设置 https 情况下，设置默认网站失败的问题
  backend/app/service/website.go
  backend/utils/nginx/components/server.go
  backend/utils/nginx/components/server_listen.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1026 fix: 增加初始化逻辑
  backend/configs/system.go
  backend/init/hook/hook.go
  backend/init/viper/viper.go
  backend/utils/common/common.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1027 fix: 解决数据库上传备份恢复失败的问题
  backend/app/service/backup.go
  backend/app/service/database_mysql.go
  frontend/src/components/upload/index.vue
  frontend/src/views/database/redis/setting/persistence/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1030 fix: 解决 ssl 启用和端口修改跳转问题
  frontend/src/views/setting/safe/port/index.vue
  frontend/src/views/setting/safe/ssl/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1034 fix: 解决默认网站开启 https 443 端口没有设置 default_server 的问题
  backend/app/service/website_utils.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1037 fix: 解决创建数据库超时问题
  backend/app/service/database_mysql.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1045 fix: 容器配置界面样式调整
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/container/setting/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1047 fix: 右侧抽屉宽度调整
  frontend/src/views/container/image/save/index.vue
  frontend/src/views/container/image/tag/index.vue
  frontend/src/views/container/network/create/index.vue
  frontend/src/views/container/repo/index.vue
  frontend/src/views/container/repo/operator/index.vue
  frontend/src/views/container/volume/create/index.vue
  frontend/src/views/database/mysql/create/index.vue
  frontend/src/views/database/mysql/remote/index.vue
  frontend/src/views/setting/safe/ssl/index.vue
  frontend/src/views/setting/snapshot/import/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1060 feat: 创建应用增加高级设置
  backend/app/dto/request/app.go
  backend/app/service/app.go
  backend/app/service/app_utils.go
  backend/app/service/website.go
  backend/constant/errs.go
  backend/utils/ssl/acme_test.go
  frontend/src/global/form-rules.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/app-store/detail/index.vue
  frontend/src/views/app-store/detail/install/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1062 feat: 编辑应用增加高级设置
  backend/app/dto/request/app.go
  backend/app/dto/response/app.go
  backend/app/service/app.go
  backend/app/service/app_install.go
  backend/constant/app.go
  frontend/src/api/interface/app.ts
  frontend/src/api/modules/app.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/app-store/detail/install/index.vue
  frontend/src/views/app-store/installed/detail/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1064 feat: 创建一键部署网站和运行环境增加高级设置
  backend/app/dto/request/app.go
  backend/app/dto/request/website.go
  backend/app/service/website.go
  frontend/src/views/app-store/installed/detail/index.vue
  frontend/src/views/website/website/create/index.vue
Labels: dev, lgtm, approved

#1067 feat: 升级 distribution 版本到 v2.8.2
  go.mod
  go.sum
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1073 fix: docker 状态判断逻辑修改
  backend/app/dto/docker.go
  backend/app/service/docker.go
  frontend/src/api/interface/container.ts
  frontend/src/api/modules/container.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/container/setting/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm

#1075 feat: 优化应用升级逻辑
  backend/app/dto/request/app.go
  backend/app/dto/response/app.go
  backend/app/service/app.go
  backend/app/service/app_install.go
  backend/app/service/app_utils.go
  backend/constant/app.go
  backend/utils/compose/compose.go
  backend/utils/files/file_op.go
  frontend/src/components/status/index.vue
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/app-store/index.scss
  frontend/src/views/app-store/installed/detail/index.vue
  frontend/src/views/app-store/installed/index.vue
  frontend/src/views/app-store/installed/upgrade/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1077 feat: 容器增加日志切割
  backend/app/dto/docker.go
  backend/app/service/docker.go
  frontend/src/api/interface/container.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/container/container/index.vue
  frontend/src/views/container/setting/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1076 feat: 增加创建本地应用默认文件指令
  cmd/server/app/app_config.go
  cmd/server/app/app_config.yml
  cmd/server/app/app_param.yml
  cmd/server/app/logo.png
  cmd/server/cmd/app.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1079 feat: 创建运行环境逻辑修改
  backend/app/service/app_utils.go
  backend/app/service/runtime.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1080 修复首页推荐应用处在窄窗口时显示异常的问题
  frontend/src/views/home/app/index.vue
Labels: do-not-merge/release-note-label-needed

#1083 fix: 解决反向代理 1Panel 并启用 auth_basic 的时候无法登录的问题
  backend/constant/session.go
  frontend/src/views/app-store/installed/detail/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1084 fix: 解决打开编辑文件页面确认按钮可能看不到的问题
  frontend/src/views/host/file-management/code-editor/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1085 fix: 解决搜索子目录模糊查询失败的问题
  backend/utils/files/fileinfo.go
  frontend/src/views/host/file-management/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1086 fix: 解决伪静态页面光标丢失的问题
  frontend/src/views/website/website/config/basic/rewrite/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1087 fix: 解决首页控制台报错的问题
  frontend/src/views/home/status/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1089 feat: 实现域名绑定与授权 ip 功能
  backend/app/dto/setting.go
  backend/app/service/setting.go
  backend/configs/system.go
  backend/constant/errs.go
  backend/init/hook/hook.go
  backend/init/migration/migrate.go
  backend/init/migration/migrations/init.go
  backend/init/router/router.go
  backend/middleware/bind_domain.go
  backend/middleware/ip_limit.go
  frontend/components.d.ts
  frontend/src/api/index.ts
  frontend/src/api/interface/setting.ts
  frontend/src/components/error-message/err_domain.vue
  frontend/src/components/error-message/err_ip.vue
  frontend/src/enums/http-enum.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/utils/util.ts
  frontend/src/views/login/entrance/index.vue
  frontend/src/views/setting/safe/allowips/index.vue
  frontend/src/views/setting/safe/domain/index.vue
  frontend/src/views/setting/safe/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1098 feat: 1pctl reset 命令改为多级
  cmd/server/cmd/reset.go
  frontend/src/components/error-message/err_domain.vue
  frontend/src/components/error-message/err_ip.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1099 feat: 取消网站 ipv6 的默认设置
  backend/app/service/website_utils.go
  cmd/server/nginx_conf/website_default.conf
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1100 feat: 已安装应用增加打开安装目录功能
  backend/app/api/v1/app.go
  backend/app/dto/response/app.go
  backend/app/service/app.go
  backend/app/service/app_utils.go
  backend/i18n/i18n.go
  backend/i18n/lang/en.yaml
  backend/i18n/lang/zh.yaml
  frontend/src/api/interface/app.ts
  frontend/src/global/business.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/app-store/apps/index.vue
  frontend/src/views/app-store/detail/index.vue
  frontend/src/views/app-store/detail/install/index.vue
  frontend/src/views/app-store/installed/detail/index.vue
  frontend/src/views/app-store/installed/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1102 feat: 时间同步增加时区、同步地址自定义设置
  backend/app/api/v1/setting.go
  backend/app/dto/setting.go
  backend/app/service/setting.go
  backend/init/migration/migrations/init.go
  backend/router/ro_setting.go
  backend/utils/cmd/cmd.go
  backend/utils/ntp/ntp.go
  frontend/src/api/interface/setting.ts
  frontend/src/api/modules/setting.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/setting/panel/index.vue
  frontend/src/views/setting/panel/ntp/index.vue
  frontend/src/views/setting/safe/allowips/index.vue
  frontend/src/views/setting/safe/mfa/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1105 feat: 创建应用增加 compose 文件配置功能
  backend/app/dto/request/app.go
  backend/app/model/app_detail.go
  backend/app/service/app.go
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/app-store/detail/index.vue
  frontend/src/views/app-store/detail/install/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1106 feat: 日志菜单样式调整
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/styles/common.scss
  frontend/src/views/log/index.vue
  frontend/src/views/log/login/index.vue
  frontend/src/views/log/operation/index.vue
  frontend/src/views/log/system/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1107 feat: 应用列表增加已安装提示
  backend/app/dto/response/app.go
  backend/app/service/app.go
  frontend/src/api/interface/app.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/app-store/apps/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1108 feat: 应用商店支持多容器的本地应用
  backend/app/service/app.go
  backend/app/service/app_utils.go
  frontend/components.d.ts
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1111 feat: 增加容器日志清理功能
  backend/app/api/v1/container.go
  backend/app/api/v1/setting.go
  backend/app/service/container.go
  backend/router/ro_container.go
  cmd/server/docs/docs.go
  cmd/server/docs/swagger.json
  cmd/server/docs/swagger.yaml
  frontend/src/api/modules/container.ts
  frontend/src/components/container-log/index.vue
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/container/container/log/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1112 fix: 解决代码合并冲突
  frontend/src/components/backup/index.vue
  frontend/src/views/host/ssh/index.vue
  frontend/src/views/host/ssh/log/log.vue
  frontend/src/views/host/ssh/ssh/index.vue
  frontend/vite.config.ts
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1114 feat: 日志审计增加网站日志
  backend/app/service/website.go
  backend/constant/website.go
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/routers/modules/log.ts
  frontend/src/views/log/index.vue
  frontend/src/views/log/website/index.vue
  frontend/src/views/website/website/config/log/log-fiile/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1116 feat: 计划任务增加网站日志切割
  backend/app/service/cronjob_helper.go
  frontend/components.d.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/cronjob/operate/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1117 feat: 增加容器、镜像、网络、存储卷清理功能
  backend/app/api/v1/container.go
  backend/app/dto/container.go
  backend/app/service/container.go
  backend/router/ro_container.go
  cmd/server/docs/docs.go
  cmd/server/docs/swagger.json
  cmd/server/docs/swagger.yaml
  frontend/src/api/interface/container.ts
  frontend/src/api/modules/container.ts
  frontend/src/components/confirm-dialog/index.vue
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/container/container/index.vue
  frontend/src/views/container/image/index.vue
  frontend/src/views/container/image/prune/index.vue
  frontend/src/views/container/network/index.vue
  frontend/src/views/container/volume/index.vue
  frontend/src/views/setting/expired.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1119 feat: 应用商店兼容移动端
  frontend/src/layout/index copy.vue
  frontend/src/layout/index.vue
  frontend/src/styles/moblie.scss
  frontend/src/views/app-store/apps/index.vue
  frontend/src/views/app-store/installed/index.vue
  frontend/src/views/website/website/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1123 fix: 系统时间同步样式修改
  backend/app/api/v1/setting.go
  backend/app/dto/setting.go
  backend/app/service/setting.go
  backend/init/migration/migrations/init.go
  backend/utils/ntp/ntp.go
  cmd/server/docs/docs.go
  cmd/server/docs/swagger.json
  cmd/server/docs/swagger.yaml
  frontend/src/api/modules/setting.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/setting/panel/index.vue
  frontend/src/views/setting/panel/ntp/index.vue
  frontend/src/views/setting/panel/timezone/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1125 feat: PHP 网站增加禁用函数设置
  backend/app/dto/request/website.go
  backend/app/dto/response/website.go
  backend/app/service/website.go
  frontend/components.d.ts
  frontend/src/api/interface/website.ts
  frontend/src/global/form-rules.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/website/website/config/php/config/index.vue
  frontend/src/views/website/website/config/php/function/index.vue
  frontend/src/views/website/website/config/php/index.vue
  frontend/src/views/website/website/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1126 feat: 兼容移动端
  frontend/src/components/complex-table/index.vue
  frontend/src/components/layout-content/index.vue
  frontend/src/store/index.ts
  frontend/src/styles/moblie.scss
  frontend/src/views/app-store/apps/index.vue
  frontend/src/views/app-store/installed/index.vue
  frontend/src/views/container/container/index.vue
  frontend/src/views/cronjob/index.vue
  frontend/src/views/database/mysql/index.vue
  frontend/src/views/host/monitor/monitor/index.vue
  frontend/src/views/host/ssh/log/log.vue
  frontend/src/views/host/ssh/ssh/index.vue
  frontend/src/views/log/login/index.vue
  frontend/src/views/log/operation/index.vue
  frontend/src/views/setting/backup-account/index.vue
  frontend/src/views/setting/panel/index.vue
  frontend/src/views/setting/safe/index.vue
  frontend/src/views/setting/snapshot/index.vue
  frontend/src/views/website/ssl/index.vue
  frontend/src/views/website/website/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1127 fix: 计划任务脚本执行设置执行路径
  backend/app/service/cronjob_helper.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#829 feat: 使用 goreleaser 构建包
  .github/workflows/build-test.yml
  .github/workflows/release-drafter.yml
  .gitignore
  .goreleaser.yaml
  Dockerfile
  script.sh
Labels: do-not-merge/release-note-label-needed, lgtm, approved

#1128 feat: 计划任务增加时间同步选项
  backend/app/service/cronjob_helper.go
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/cronjob/operate/index.vue
  go.mod
  go.sum
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1129 style: 删除无用代码
  backend/app/service/app_install.go
  frontend/components.d.ts
  frontend/src/views/website/website/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1132 feat: 计划任务增加每隔 n 秒执行
  backend/app/dto/cronjob.go
  backend/app/model/cronjob.go
  backend/app/service/cornjob.go
  backend/init/migration/migrate.go
  backend/init/migration/migrations/init.go
  frontend/src/api/interface/cronjob.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/cronjob/index.vue
  frontend/src/views/cronjob/operate/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1133 feat: PHP 网站增加配置上传限制功能
  backend/app/dto/request/website.go
  backend/app/dto/response/website.go
  backend/app/service/website.go
  frontend/src/api/interface/website.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/website/website/config/php/index.vue
  frontend/src/views/website/website/config/php/upload/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1136 fix: 修正 goreleaser 构建失败
  .gitignore
  frontend/components.d.ts
Labels: do-not-merge/release-note-label-needed

#1139 feat: 调整网站设置页面
  frontend/src/styles/moblie.scss
  frontend/src/views/website/website/config/basic/auth-basic/index.vue
  frontend/src/views/website/website/config/basic/default-doc/index.vue
  frontend/src/views/website/website/config/basic/domain/index.vue
  frontend/src/views/website/website/config/basic/https/index.vue
  frontend/src/views/website/website/config/basic/limit-conn/index.vue
  frontend/src/views/website/website/config/basic/other/index.vue
  frontend/src/views/website/website/config/basic/proxy/index.vue
  frontend/src/views/website/website/config/safety/ccdeny/index.vue
  frontend/src/views/website/website/config/safety/file-block-list/index.vue
  frontend/src/views/website/website/config/safety/simple-list/index.vue
  frontend/src/views/website/website/config/safety/value-list/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1140 fix: 计划任务删除弹窗优化
  backend/app/service/cornjob.go
  frontend/src/views/cronjob/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1141 feat: 修改同步应用列表方式
  backend/app/dto/response/app.go
  backend/app/service/app.go
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/app-store/installed/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1143 feat: 适配 Linux 多架构打包
  backend/log/dup_write_darwin.go
  backend/log/dup_write_linux.go
  backend/log/dup_write_linux_arm64.go
  go.mod
  go.sum
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1142 fix: 修改计划任务报告样式
  backend/utils/cmd/cmd.go
  frontend/src/views/cronjob/record/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1144 feat: 支持更多 linux 架构打包
  .github/workflows/build-test.yml
  .github/workflows/release-drafter.yml
  .goreleaser.yaml
  backend/log/dup_write_windows.go
  go.mod
  go.sum
Labels: do-not-merge/release-note-label-needed, lgtm

#1145 fix: 修正 actions 构建错误
  .github/workflows/build-test.yml
  .github/workflows/release-drafter.yml
Labels: do-not-merge/release-note-label-needed

#1146 feat: 监控增加数据采集间隔设置
  backend/app/dto/setting.go
  backend/app/repo/setting.go
  backend/app/service/monitor.go
  backend/app/service/setting.go
  backend/cron/cron.go
  backend/global/global.go
  backend/init/migration/migrations/init.go
  frontend/src/api/interface/setting.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/host/monitor/setting/days/index.vue
  frontend/src/views/host/monitor/setting/index.vue
  frontend/src/views/host/monitor/setting/interval/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1147 feat: 优化监控界面无数据时显示样式
  backend/app/service/monitor.go
  frontend/src/views/host/monitor/monitor/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1148 perf: 默认构建 armv7
  .goreleaser.yaml
Labels: do-not-merge/release-note-label-needed, lgtm

#1152 build(deps): bump github.com/shirou/gopsutil/v3 from v3.23.1 to v3.23.4
  .goreleaser.yaml
  go.mod
  go.sum
Labels: do-not-merge/release-note-label-needed

#1151 feat: 网站增加防盗链设置
  backend/app/api/v1/website.go
  backend/app/dto/request/nginx.go
  backend/app/dto/response/nginx.go
  backend/app/service/website.go
  backend/router/ro_website.go
  frontend/src/api/interface/website.ts
  frontend/src/api/modules/website.ts
  frontend/src/global/form-rules.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/website/website/config/basic/anti-Leech/index.vue
  frontend/src/views/website/website/config/basic/https/index.vue
  frontend/src/views/website/website/config/basic/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1153 perf: 更新 arm 文件名规则
  .github/workflows/build-test.yml
  .github/workflows/release-drafter.yml
  .goreleaser.yaml
Labels: do-not-merge/release-note-label-needed

#1154 feat: 更新 npm 依赖
  frontend/package-lock.json
  frontend/package.json
Labels: do-not-merge/release-note-label-needed

#1156 feat: 概览界面针对磁盘显示优化
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/home/status/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1167 fix: 解决高级设置CPU和内存限制删除之后安装报错的问题
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/app-store/detail/install/index.vue
Labels: do-not-merge/release-note-label-needed, dev

#1168 feat: 文件列表增加批量上传功能
  backend/app/api/v1/file.go
  backend/i18n/lang/en.yaml
  backend/i18n/lang/zh.yaml
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/host/file-management/upload/index.vue
Labels: do-not-merge/release-note-label-needed, dev

#1173 feat: docker 配置界面样式统一
  backend/app/api/v1/docker.go
  backend/app/dto/docker.go
  backend/app/service/docker.go
  backend/app/service/firewall.go
  backend/router/ro_container.go
  cmd/server/docs/docs.go
  cmd/server/docs/swagger.json
  cmd/server/docs/swagger.yaml
  frontend/src/api/modules/container.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/container/container/create/index.vue
  frontend/src/views/container/setting/index.vue
  frontend/src/views/container/setting/log/index.vue
  frontend/src/views/container/setting/mirror/index.vue
  frontend/src/views/container/setting/registry/index.vue
Labels: do-not-merge/release-note-label-needed, dev

#1177 fix: 面板设置界面多行样式统一
  frontend/src/views/container/setting/index.vue
  frontend/src/views/setting/safe/allowips/index.vue
  frontend/src/views/setting/safe/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1178 fix: 修复概览页数据加载失败的问题
  frontend/src/views/home/index.vue
  frontend/src/views/home/status/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1180 fix: 解决浏览器关闭后重新打开不需要登录验证的问题
  backend/app/service/auth.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1181 fix: 补全缺失的组件引用
  frontend/src/api/modules/auth.ts
  frontend/src/views/container/image/build/index.vue
  frontend/src/views/container/setting/log/index.vue
  frontend/src/views/container/setting/mirror/index.vue
  frontend/src/views/container/setting/registry/index.vue
  frontend/src/views/host/file-management/chown/index.vue
  frontend/src/views/host/file-management/rename/index.vue
  frontend/src/views/host/monitor/setting/days/index.vue
  frontend/src/views/host/monitor/setting/interval/index.vue
  frontend/src/views/host/ssh/ssh/address/index.vue
  frontend/src/views/host/ssh/ssh/port/index.vue
  frontend/src/views/host/ssh/ssh/pubkey/index.vue
  frontend/src/views/host/ssh/ssh/root/index.vue
  frontend/src/views/host/terminal/host/change-group/index.vue
  frontend/src/views/host/terminal/host/operate/index.vue
  frontend/src/views/log/system/index.vue
  frontend/src/views/log/website/index.vue
  frontend/src/views/setting/panel/name/index.vue
  frontend/src/views/setting/panel/ntp/index.vue
  frontend/src/views/setting/panel/timeout/index.vue
  frontend/src/views/setting/panel/timezone/index.vue
  frontend/src/views/setting/panel/username/index.vue
  frontend/src/views/setting/safe/allowips/index.vue
  frontend/src/views/setting/safe/domain/index.vue
  frontend/src/views/setting/safe/entrance/index.vue
  frontend/src/views/setting/safe/mfa/index.vue
  frontend/src/views/setting/safe/port/index.vue
  frontend/src/views/setting/safe/ssl/index.vue
  frontend/src/views/setting/safe/timeout/index.vue
  frontend/src/views/website/runtime/create/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1183 feat: 优化大文件下载
  backend/app/api/v1/file.go
  backend/app/dto/request/file.go
  backend/constant/errs.go
  backend/i18n/lang/en.yaml
  backend/i18n/lang/zh.yaml
  backend/init/router/router.go
  backend/router/ro_file.go
  frontend/src/api/interface/file.ts
  frontend/src/views/host/file-management/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1185 style: 修改日志审计-网站日志样式
  frontend/src/views/app-store/installed/index.vue
  frontend/src/views/log/website/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1187 fix: 镜像仓库校验判断修改
  backend/app/service/image_repo.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1188 feat: 网站增加 IPV6 监听设置
  backend/app/dto/request/website.go
  backend/app/model/website.go
  backend/app/service/website.go
  backend/app/service/website_utils.go
  backend/init/migration/migrate.go
  backend/init/migration/migrations/init.go
  frontend/src/api/interface/website.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/log/website/index.vue
  frontend/src/views/website/website/config/basic/https/index.vue
  frontend/src/views/website/website/config/basic/limit-conn/index.vue
  frontend/src/views/website/website/config/basic/other/index.vue
  frontend/src/views/website/website/create/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1189 fix: 解决 nexus 安装失败的问题
  backend/app/service/app.go
  backend/app/service/app_install.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1190 fix: 解决 halo 用户名设置为大写之后导致安装失败的问题
  backend/app/api/v1/file.go
  frontend/src/global/form-rules.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/zh.ts
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1193 fix: 面板设置输入增加校验及提示信息
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/host/ssh/log/log.vue
  frontend/src/views/setting/panel/ntp/index.vue
  frontend/src/views/setting/safe/allowips/index.vue
Labels: dev, lgtm, approved

#1194 fix: 解决网站的默认文档不能设置为子目录的文件的问题
  frontend/src/global/form-rules.ts
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1195 fix: 解决申请证书 多个域名下显示异常的问题
  frontend/src/views/website/ssl/create/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1196 Update .goreleaser.yaml
  .goreleaser.yaml
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1197 feat: 限制删除运行环境中使用的应用版本
  backend/app/repo/runtime.go
  backend/app/service/app.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1199 fix: 解决备份文件过大导致下载超时问题
  frontend/src/components/backup/index.vue
  frontend/src/utils/util.ts
  frontend/src/views/host/file-management/index.vue
  frontend/src/views/website/website/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1200 fix: 默认时区获取方式修改
  backend/init/migration/migrations/init.go
  backend/utils/common/common.go
  frontend/src/views/container/setting/mirror/index.vue
  frontend/src/views/container/setting/registry/index.vue
  frontend/src/views/setting/panel/timezone/index.vue
  frontend/src/views/setting/safe/allowips/index.vue
  frontend/src/views/setting/safe/domain/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1202 feat: 移动端样式优化
  frontend/src/styles/moblie.scss
  frontend/src/views/website/website/config/basic/https/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved
