Repository 1Panel-dev/1Panel, pull requests merged in 2023-08, with the labels that each got.

#1794 fix: 修改远程数据库依赖
  backend/utils/mysql/client/remote.go
  backend/utils/mysql/helper/dump.go
  backend/utils/mysql/helper/source.go
  frontend/src/views/database/mysql/conn/index.vue
  frontend/src/views/database/mysql/create/index.vue
  frontend/src/views/database/mysql/delete/index.vue
  frontend/src/views/database/mysql/index.vue
  frontend/src/views/database/mysql/password/index.vue
  frontend/src/views/database/mysql/setting/slow-log/index.vue
  go.mod
  go.sum
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1797 fix: 修正容器重启规则翻译错误
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
Labels: do-not-merge/release-note-label-needed

#1800 feat: 增加守护进程管理
  backend/app/api/v1/host_tool.go
  backend/app/api/v1/remote_db.go
  backend/app/dto/request/host_tool.go
  backend/app/dto/response/host_tool.go
  backend/app/service/host_tool.go
  backend/i18n/lang/en.yaml
  backend/i18n/lang/zh-Hant.yaml
  backend/i18n/lang/zh.yaml
  backend/router/ro_host.go
  cmd/server/docs/docs.go
  cmd/server/docs/swagger.json
  cmd/server/docs/swagger.yaml
  frontend/src/api/interface/host-tool.ts
  frontend/src/api/modules/host-tool.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/host/tool/supervisor/create/index.vue
  frontend/src/views/host/tool/supervisor/file/index.vue
  frontend/src/views/host/tool/supervisor/index.vue
  frontend/src/views/host/tool/supervisor/status/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1802 fix: 解决文件压缩无法选择文件夹的问题
  frontend/src/views/host/file-management/compress/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1803 fix: 解决重定向设置重定向到首页但是编辑显示错误的问题
  backend/app/dto/response/nginx.go
  backend/app/service/website.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1805 fix: 快照容器部分修改为仅备份已安装应用数据
  backend/app/service/snapshot.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1806 fix: 解决带数据库应用安装失败的问题
  backend/app/service/app_utils.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1807 style: 修改网站防盗链页面样式
  frontend/src/views/website/website/config/basic/anti-Leech/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1809 fix: 解决安装应用 数据库密码字段包含&$提示错误的问题
  frontend/src/global/form-rules.ts
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1810 fix: 解决打开越权读取文件的问题
  backend/app/api/v1/container.go
  backend/app/api/v1/cronjob.go
  backend/app/api/v1/database_mysql.go
  backend/app/api/v1/file.go
  backend/app/api/v1/logs.go
  backend/app/api/v1/ssh.go
  backend/app/service/container.go
  backend/app/service/container_compose.go
  backend/app/service/cornjob.go
  backend/app/service/database_mysql.go
  backend/app/service/docker.go
  backend/app/service/image.go
  backend/app/service/logs.go
  backend/app/service/snapshot.go
  backend/app/service/ssh.go
  backend/init/migration/migrations/init.go
  backend/router/ro_container.go
  backend/router/ro_cronjob.go
  backend/router/ro_database.go
  backend/router/ro_file.go
  backend/router/ro_host.go
  backend/router/ro_log.go
  backend/utils/mysql/client/local.go
  cmd/server/docs/docs.go
  cmd/server/docs/swagger.json
  cmd/server/docs/swagger.yaml
  frontend/src/api/modules/container.ts
  frontend/src/api/modules/cronjob.ts
  frontend/src/api/modules/database.ts
  frontend/src/api/modules/files.ts
  frontend/src/api/modules/host.ts
  frontend/src/api/modules/log.ts
  frontend/src/components/backup/index.vue
  frontend/src/views/container/compose/create/index.vue
  frontend/src/views/container/compose/index.vue
  frontend/src/views/container/image/build/index.vue
  frontend/src/views/container/image/pull/index.vue
  frontend/src/views/container/image/push/index.vue
  frontend/src/views/cronjob/record/index.vue
  frontend/src/views/database/mysql/setting/index.vue
  frontend/src/views/database/mysql/setting/slow-log/index.vue
  frontend/src/views/database/redis/setting/index.vue
  frontend/src/views/host/ssh/ssh/index.vue
  frontend/src/views/log/system/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1811 feat: Supervisor 适配 Debian 操作系统
  .gitignore
  backend/app/dto/request/host_tool.go
  backend/app/dto/response/host_tool.go
  backend/app/service/host_tool.go
  backend/constant/host_tool.go
  cmd/server/docs/docs.go
  cmd/server/docs/swagger.json
  cmd/server/docs/swagger.yaml
  frontend/src/api/interface/host-tool.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/host/tool/supervisor/index.vue
  frontend/src/views/host/tool/supervisor/status/index.vue
  frontend/src/views/host/tool/supervisor/status/init/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1813 fix: 解决越权下载文件的问题
  backend/app/api/v1/cronjob.go
  backend/app/api/v1/file.go
  backend/app/api/v1/setting.go
  backend/app/service/cornjob.go
  backend/app/service/setting.go
  backend/router/ro_file.go
  backend/router/ro_setting.go
  cmd/server/docs/docs.go
  cmd/server/docs/swagger.json
  cmd/server/docs/swagger.yaml
  frontend/src/api/modules/cronjob.ts
  frontend/src/api/modules/files.ts
  frontend/src/api/modules/setting.ts
  frontend/src/views/cronjob/record/index.vue
  frontend/src/views/setting/safe/ssl/index.vue
Labels: dev, lgtm, approved

#1814 fix: 修复网站配置文件读取漏洞
  backend/app/api/v1/website.go
  backend/app/dto/request/nginx.go
  backend/app/dto/request/website.go
  backend/app/dto/response/nginx.go
  backend/app/dto/response/website.go
  backend/app/service/nginx.go
  backend/app/service/website.go
  backend/router/ro_website.go
  cmd/server/docs/docs.go
  cmd/server/docs/swagger.json
  cmd/server/docs/swagger.yaml
  frontend/src/api/interface/nginx.ts
  frontend/src/api/interface/website.ts
  frontend/src/api/modules/website.ts
  frontend/src/views/website/website/config/safety/ccdeny/index.vue
  frontend/src/views/website/website/config/safety/file-block-list/index.vue
  frontend/src/views/website/website/config/safety/simple-list/index.vue
  frontend/src/views/website/website/config/safety/value-list/index.vue
  frontend/src/views/website/website/nginx/source/index.vue
Labels: dev, lgtm, approved

#1815 fix: 修改数据库密码校验规则
  frontend/src/global/form-rules.ts
  frontend/src/views/database/mysql/conn/index.vue
  frontend/src/views/database/mysql/create/index.vue
  frontend/src/views/database/mysql/password/index.vue
  frontend/src/views/database/redis/password/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1816 fix: 应用恢复后自动同步数据库
  backend/app/service/backup_app.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1817 feat: 数据库从服务器获取增加提示信息
  backend/app/service/backup_app.go
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/database/mysql/index.vue
  frontend/src/views/database/mysql/remote/operate/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1818 feat: Supervisor 增加修改配置功能
  .gitignore
  backend/app/service/host_tool.go
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/host/tool/supervisor/config/basic/index.vue
  frontend/src/views/host/tool/supervisor/config/index.vue
  frontend/src/views/host/tool/supervisor/index.vue
  frontend/src/views/host/tool/supervisor/status/index.vue
  frontend/src/views/host/tool/supervisor/status/init/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1819 feat: 应用安装适配 sftpgo pgadmin4
  backend/app/service/app_utils.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1821 fix: 分页排序样式调整
  frontend/src/views/container/container/index.vue
  frontend/src/views/cronjob/index.vue
  frontend/src/views/database/mysql/index.vue
  frontend/src/views/database/mysql/remote/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1822 fix: 解决 cloudreve 升级数据丢失的问题
  backend/app/service/app_utils.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1823 fix: 解决数据库日志监听未刷新的问题
  frontend/src/components/container-log/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1824 fix: 解决应用升级无法编辑最新配置的问题
  backend/app/service/app_install.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1825 feat: 创建远程数据库支持 localhost 权限
  frontend/src/views/database/mysql/create/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm

#1826 feat: 应用关联 redis 时自动填充密码
  backend/app/dto/app.go
  backend/app/service/app_utils.go
  backend/init/migration/migrate.go
  backend/init/migration/migrations/init.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1827 fix: 解决应用同步可能出现的多个同名应用的问题
  backend/app/service/app.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1828 fix: 解决应用备份失败的问题
  backend/app/service/backup_app.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1830 fix: 解决数据库同步后备份路径错误的问题
  backend/app/service/backup_mysql.go
  backend/app/service/database_mysql.go
  backend/utils/mysql/client/local.go
  frontend/src/lang/modules/en.ts
  frontend/src/views/database/mysql/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1832 feat: 网站反向代理增加协议选择
  backend/utils/files/fileinfo.go
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/styles/common.scss
  frontend/src/views/website/website/config/basic/site-folder/index.vue
  frontend/src/views/website/website/create/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1840 fix: 解决文件上传可以拖入文件夹的问题
  frontend/src/components/upload/index.vue
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/utils/util.ts
  frontend/src/views/host/file-management/upload/index.vue
Labels: dev, lgtm, approved

#1841 fix: 解决重定向切换 404 没有消除名称字段校验结果的问题
  frontend/src/views/website/website/config/basic/redirect/create/index.vue
Labels: dev, lgtm, approved

#1837 fix: 解决创建数据库用户重复的问题
  backend/utils/mysql/client/local.go
  backend/utils/mysql/client/remote.go
Labels: dev, lgtm, approved

#1838 style: 修改初始化 Supervisor 的提示文字
  backend/app/service/host_tool.go
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/host/tool/supervisor/status/index.vue
  frontend/src/views/host/tool/supervisor/status/init/index.vue
Labels: dev, lgtm, approved

#1854 feat:404重定向取消设置是否保留 URL 参数
  frontend/src/views/website/website/config/basic/redirect/create/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1855 fix: 解决网站路径重定向不保留URL参数不生效的问题
  backend/app/service/website.go
  frontend/src/views/website/website/config/basic/redirect/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1857 fix: mysql 数据库连接信息样式调整
  backend/app/repo/databse_mysql.go
  backend/app/service/app_utils.go
  frontend/src/views/database/mysql/conn/index.vue
  frontend/src/views/database/mysql/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1858 fix: 解决 redis 页面命令行执行命令提示未认证的问题
  backend/app/repo/app_install.go
  backend/app/service/app_install.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1861 fix: 解决应用安装有远程同名数据库报错的问题
  backend/app/service/app_utils.go
  frontend/src/components/upload/index.vue
  frontend/src/utils/util.ts
  frontend/src/views/host/file-management/upload/index.vue
  frontend/src/views/website/website/create/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1860 fix: 优化英文状态下，备份恢复按钮换行的问题
  backend/utils/mysql/client/local.go
  backend/utils/mysql/client/remote.go
  frontend/src/components/app-status/index.vue
  frontend/src/components/backup/index.vue
  frontend/src/components/upload/index.vue
  frontend/src/views/database/mysql/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1862 fix: 修改快照版本判断
  backend/app/service/snapshot.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1863 fix: 解决同步快照路径错误的问题
  backend/app/service/backup.go
  backend/utils/cloud_storage/client/onedrive.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1864 fix: 防火墙与进程守护加载样式调整
  backend/utils/firewall/client/firewalld.go
  frontend/src/views/host/firewall/ip/index.vue
  frontend/src/views/host/firewall/port/index.vue
  frontend/src/views/host/tool/supervisor/status/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1865 feat: 守护进程一些字段增加校验
  backend/app/service/host_tool.go
  frontend/src/views/host/tool/supervisor/create/index.vue
  frontend/src/views/host/tool/supervisor/file/index.vue
  frontend/src/views/host/tool/supervisor/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1866 fix: 解决 sftpgo 安装失败的问题
  backend/app/service/app_utils.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1869 fix: 优化远程数据库备份方式
  backend/utils/mysql/helper/dump.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1870 feat: 已安装应用增加 https 端口跳转
  frontend/src/components/port-jump/index.vue
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/app-store/installed/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1871 style: 修改网站提示
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/website/website/config/basic/site-folder/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1872 fix: 国际化问题修改
  frontend/src/api/index.ts
  frontend/src/lang/modules/en.ts
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1875 fix: 解决同步快照名称加载错误的问题
  backend/app/service/backup.go
  backend/utils/cloud_storage/client/cos.go
  backend/utils/cloud_storage/client/kodo.go
  backend/utils/cloud_storage/client/minio.go
  backend/utils/cloud_storage/client/onedrive.go
  backend/utils/cloud_storage/client/oss.go
  backend/utils/cloud_storage/client/s3.go
  backend/utils/cloud_storage/client/sftp.go
  backend/utils/cloud_storage/cloud_storage_client.go
  frontend/src/views/setting/snapshot/import/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1876 feat: 修改 Supervisor 的判断
  backend/app/service/host_tool.go
  backend/utils/cmd/cmd.go
  backend/utils/systemctl/systemctl.go
  frontend/src/views/host/tool/supervisor/config/basic/index.vue
  frontend/src/views/host/tool/supervisor/config/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1874 fix: 解决 Mysql 恢复失败的问题
  backend/app/service/backup_app.go
  frontend/src/global/form-rules.ts
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1881 fix: 修改部分字段校验
  backend/app/dto/database.go
  backend/app/dto/image_repo.go
  backend/app/dto/remote_db.go
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/container/setting/mirror/index.vue
  frontend/src/views/container/setting/registry/index.vue
  frontend/src/views/database/mysql/password/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1882 fix: 解决创建PHP运行环境报错的问题
  backend/app/service/runtime.go
  backend/app/service/runtime_utils.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1883 fix: 解决编排创建日志获取失败的问题
  backend/app/api/v1/container.go
  backend/app/service/container.go
  backend/app/service/image.go
  backend/app/service/setting.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1885 feat: 优化网站反向代理地址填写
  backend/app/service/host_tool.go
  frontend/src/api/interface/website.ts
  frontend/src/views/website/website/config/basic/proxy/create/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1887 fix: 解决关闭高级设置之后没有提示端口放开的问题
  frontend/src/global/business.ts
  frontend/src/views/app-store/detail/install/index.vue
  frontend/src/views/app-store/installed/detail/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1886 fix: 解决计划任务备份远程数据库详情显示错误的问题
  backend/app/service/cornjob.go
  backend/init/migration/migrate.go
  backend/init/migration/migrations/init.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1888 fix: 快照前停止计划任务执行
  backend/app/service/snapshot.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1891 Pr@dev@dan
  frontend/src/components/container-log/index.vue
  frontend/src/styles/moblie.scss
  frontend/src/views/app-store/apps/index.vue
  frontend/src/views/container/compose/index.vue
  frontend/src/views/container/container/index.vue
  frontend/src/views/container/image/index.vue
  frontend/src/views/container/network/index.vue
  frontend/src/views/container/volume/index.vue
  frontend/src/views/database/mysql/setting/status/index.vue
  frontend/src/views/host/monitor/monitor/index.vue
  frontend/src/views/website/website/index.vue
  frontend/src/views/website/website/nginx/performance/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1892 fix: 快照恢复前先清空对应文件夹
  backend/app/service/snapshot.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1893 fix: 备份账号高度调整
  frontend/src/views/setting/backup-account/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1894 fix: 修改数据库名称长度提示信息
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1896 feat: 编辑运行环境增加提示
  frontend/src/api/interface/runtime.ts
  frontend/src/views/website/runtime/create/index.vue
  frontend/src/views/website/runtime/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1897 fix: 计划任务创建样式调整
  frontend/src/lang/modules/en.ts
  frontend/src/views/cronjob/operate/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1899 fix: 限制数据库名称大小写
  frontend/src/global/form-rules.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1901 fix: 解决 ssh 登录日志分页错误
  backend/app/service/ssh.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1902 fix: 解决计划任务编辑错误
  backend/app/service/cornjob.go
  frontend/src/views/cronjob/record/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1903 fix: 解决 PHP 运行环境网站恢复失败的问题
  backend/app/service/backup_website.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1904 feat: 修改应用安装数据库名的默认值
  frontend/src/utils/util.ts
  frontend/src/views/app-store/detail/params/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1906 fix: 数据库获取时，忽略重名数据库
  backend/app/dto/image_repo.go
  backend/app/dto/remote_db.go
  backend/app/service/database_mysql.go
  frontend/src/global/form-rules.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/container/repo/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1909 feat: 远程数据库地址支持域名
  frontend/src/views/database/mysql/remote/operate/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1911 fix: 修改表格分页偶发的数据丢失问题
  frontend/src/components/complex-table/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1917 fix: 容器创建启动命令提示信息修改
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/container/container/operate/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1919 feat: 守护进程增加操作列
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/host/tool/supervisor/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1921 fix: 解决应用升级镜像拉取失败导致应用服务异常的问题
  backend/app/service/app_utils.go
  backend/buserr/errors.go
  backend/i18n/lang/en.yaml
  backend/i18n/lang/zh-Hant.yaml
  backend/i18n/lang/zh.yaml
  backend/utils/docker/compose.go
  backend/utils/docker/docker.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1926 fix: 容器终端断开连接时，保持抽屉打开
  frontend/src/components/terminal/index.vue
  frontend/src/views/container/container/terminal/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1927 fix: 优化容器清理提示信息
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/container/container/index.vue
  frontend/src/views/container/container/prune/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1928 feat: 远程数据库增加连接性测试
  backend/app/api/v1/remote_db.go
  backend/app/service/remote_db.go
  backend/router/ro_database.go
  backend/utils/mysql/client.go
  cmd/server/docs/docs.go
  cmd/server/docs/swagger.json
  cmd/server/docs/swagger.yaml
  frontend/src/api/modules/database.ts
  frontend/src/views/database/mysql/remote/operate/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1934 fix: 备份文件时忽略文件变化
  backend/app/service/cronjob_helper.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1935 feat: 数据库连接信息增加复制按钮以及超长悬浮显示
  frontend/src/views/database/mysql/conn/index.vue
  frontend/src/views/database/mysql/remote/index.vue
  go.mod
  go.sum
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1936 fix: 修改 loading
  frontend/src/views/database/mysql/remote/operate/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1937 fix: 恢复表格封装代码
  frontend/src/components/complex-table/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1938 fix: 解决备份压缩报错问题
  backend/app/service/cronjob_helper.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1939 fix: 解决登录页切换语言提示信息不更换的问题
  frontend/src/views/login/components/login-form.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1943 feat: 优化进程守护状态获取方式
  backend/app/api/v1/host_tool.go
  backend/app/service/host_tool.go
  backend/router/ro_host.go
  cmd/server/docs/docs.go
  cmd/server/docs/swagger.json
  cmd/server/docs/swagger.yaml
  frontend/src/api/modules/host-tool.ts
  frontend/src/lang/modules/en.ts
  frontend/src/views/host/tool/supervisor/file/index.vue
  frontend/src/views/host/tool/supervisor/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1952 fix: 进程守护区分项目名称和进程名称
  frontend/src/views/host/tool/supervisor/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1962 feat: 防火墙支持设置备注信息
  backend/app/api/v1/firewall.go
  backend/app/dto/firewall.go
  backend/app/model/firewall.go
  backend/app/repo/host.go
  backend/app/service/firewall.go
  backend/init/migration/migrate.go
  backend/init/migration/migrations/init.go
  backend/router/ro_host.go
  backend/utils/firewall/client/info.go
  cmd/server/docs/docs.go
  cmd/server/docs/swagger.json
  cmd/server/docs/swagger.yaml
  frontend/src/api/interface/host.ts
  frontend/src/api/modules/host.ts
  frontend/src/views/host/firewall/ip/index.vue
  frontend/src/views/host/firewall/ip/operate/index.vue
  frontend/src/views/host/firewall/port/index.vue
  frontend/src/views/host/firewall/port/operate/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1967 优化移动端样式
  frontend/src/layout/index.vue
  frontend/src/styles/common.scss
  frontend/src/views/app-store/apps/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1975 fix: 修改网站重定向列表样式
  frontend/src/lang/modules/en.ts
  frontend/src/views/website/website/config/basic/redirect/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1973 fix: 解决容器编排创建日志加载慢的问题
  backend/app/service/container.go
  backend/app/service/container_compose.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1974 fix: 解决获取远程数据库失败的问题
  backend/utils/mysql/client/local.go
  backend/utils/mysql/client/remote.go
  frontend/src/routers/modules/database.ts
  frontend/src/views/database/mysql/index.vue
  frontend/src/views/database/mysql/setting/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1977 fix: 解决暂停进程被重新拉起的问题
  backend/app/service/host_tool.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1979 fix: 移动端样式优化
  frontend/src/layout/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1980 fix: 解决网站反代编辑时回显错误的问题
  frontend/src/views/website/website/config/basic/proxy/create/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1983 fix: 解决进程状态一直加载中的问题
  backend/app/api/v1/host_tool.go
  backend/app/service/host_tool.go
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/host/tool/supervisor/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1986 fix: 延长进程状态获取等待时间
  backend/app/service/container_compose.go
  backend/app/service/host_tool.go
  backend/app/service/image.go
  frontend/src/components/container-log/index.vue
  frontend/src/views/website/website/config/basic/proxy/create/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1988 fix: 解决防火墙多端口创建失败的问题
  backend/app/service/firewall.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1991 fix: 移除容器日志中的 ANSI 转义序列
  frontend/src/views/container/container/log/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1996 perf: 防止message重复弹出
  frontend/src/utils/message.ts
Labels: do-not-merge/release-note-label-needed, lgtm

#2011 fix: 解决数据库用户名超长导致用户创建失败的问题
  backend/utils/mysql/client/info.go
  backend/utils/mysql/client/local.go
  backend/utils/mysql/client/remote.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2016 fix: 服务器地址支持设置为空
  frontend/index.html
  frontend/src/views/setting/panel/systemip/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2019 fix: 解决清空容器日志导致的 CPU 占用异常问题
  backend/app/service/container.go
  frontend/src/components/container-log/index.vue
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/container/container/log/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2026 fix: 解决运行环境网站切换PHP版本导致已安装应用消失的问题
  backend/app/service/app_utils.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2028 fix: 解决数据库用户名显示错误的问题
  backend/utils/mysql/client/local.go
  backend/utils/mysql/client/remote.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2030 feat: 增加强制删除 openresty 功能
  backend/app/repo/website.go
  backend/app/repo/website_domain.go
  backend/app/service/app_utils.go
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/app-store/installed/check/index.vue
  frontend/src/views/app-store/installed/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2039 feat: 重构快照功能，取消快照过程 loading
  backend/app/api/v1/snapshot.go
  backend/app/dto/setting.go
  backend/app/model/snapshot.go
  backend/app/repo/runtime.go
  backend/app/repo/snapshot.go
  backend/app/service/database_mysql.go
  backend/app/service/snapshot.go
  backend/app/service/snapshot_create.go
  backend/constant/status.go
  backend/init/hook/hook.go
  backend/init/migration/migrations/init.go
  backend/router/ro_setting.go
  frontend/src/api/interface/setting.ts
  frontend/src/api/modules/setting.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/setting/snapshot/index.vue
  frontend/src/views/setting/snapshot/snap_status/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2040 feat: 计划任务支持备份应用
  backend/app/api/v1/app_install.go
  backend/app/dto/app.go
  backend/app/dto/cronjob.go
  backend/app/model/cronjob.go
  backend/app/service/app_install.go
  backend/app/service/cornjob.go
  backend/app/service/cronjob_helper.go
  backend/init/migration/migrations/init.go
  backend/router/ro_app.go
  cmd/server/docs/docs.go
  cmd/server/docs/swagger.json
  cmd/server/docs/swagger.yaml
  frontend/src/api/interface/app.ts
  frontend/src/api/interface/cronjob.ts
  frontend/src/api/modules/app.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/cronjob/operate/index.vue
  frontend/src/views/cronjob/record/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2042 feat: 应用安装、升级、卸载之前支持执行脚本
  backend/app/service/app.go
  backend/app/service/app_utils.go
  backend/utils/cmd/cmd.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2052 feat: 放开 1panel-network 按钮禁用
  frontend/src/views/container/network/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2057 fix: 解决打开进程守护页面报错的问题
  backend/app/service/host_tool.go
  frontend/src/views/host/tool/supervisor/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2059 feat: Openresty 支持非 80 443 端口安装
  backend/app/dto/response/app.go
  backend/app/service/app.go
  backend/app/service/app_install.go
  backend/app/service/app_utils.go
  backend/app/service/nginx.go
  backend/app/service/website.go
  backend/app/service/website_ssl.go
  backend/app/service/website_utils.go
  backend/i18n/lang/en.yaml
  backend/i18n/lang/zh-Hant.yaml
  backend/i18n/lang/zh.yaml
  backend/utils/cmd/cmd.go
  frontend/src/api/interface/app.ts
  frontend/src/components/app-status/index.vue
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2061 feat: 计划任务支持系统快照
  backend/app/dto/setting.go
  backend/app/model/snapshot.go
  backend/app/service/cornjob.go
  backend/app/service/cronjob_helper.go
  backend/app/service/snapshot.go
  backend/app/service/snapshot_create.go
  backend/app/service/upgrade.go
  backend/init/hook/hook.go
  frontend/src/api/interface/setting.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/cronjob/operate/index.vue
  frontend/src/views/cronjob/record/index.vue
  frontend/src/views/setting/snapshot/index.vue
  frontend/src/views/setting/snapshot/snap_status/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2068 feat: 应用商店增加版本控制
  backend/app/dto/app.go
  backend/app/service/app.go
  backend/i18n/lang/en.yaml
  backend/i18n/lang/zh-Hant.yaml
  backend/i18n/lang/zh.yaml
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2071 feat: 网站支持不同域名使用同一个端口
  backend/app/service/website.go
  backend/i18n/lang/en.yaml
  backend/i18n/lang/zh-Hant.yaml
  backend/i18n/lang/zh.yaml
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2072 feat: 网站日志支持读取 10M 以上文件
  backend/app/dto/request/website.go
  backend/app/dto/response/website.go
  backend/app/service/website.go
  backend/utils/files/utils.go
  frontend/src/api/interface/website.ts
  frontend/src/views/website/website/config/log/log-fiile/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2089 feat: 修改应用商店版本升级判断条件
  backend/app/service/app.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2090 fix: 解决多容器应用升级失败的问题
  backend/app/service/app.go
  backend/app/service/app_utils.go
  backend/app/service/setting.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2091 feat: 应用重建改为响应式
  backend/app/service/app_utils.go
  backend/constant/app.go
  frontend/src/components/status/index.vue
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/app-store/installed/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2095 feat: PHP 运行环境更新增加重建 php 应用功能
  backend/app/dto/request/runtime.go
  backend/app/service/runtime.go
  backend/app/service/runtime_utils.go
  frontend/src/api/interface/runtime.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/website/runtime/create/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2099 fix: 修复压缩包解压时可能的由于父目录不存在导致的解压失败的问题
  backend/utils/files/file_op.go
Labels: do-not-merge/release-note-label-needed, lgtm

#2094 feat: 多数据库接口适配
  backend/app/api/v1/app_install.go
  backend/app/api/v1/backup.go
  backend/app/api/v1/database.go
  backend/app/api/v1/database_mysql.go
  backend/app/api/v1/entry.go
  backend/app/dto/backup.go
  backend/app/dto/database.go
  backend/app/dto/remote_db.go
  backend/app/dto/request/app.go
  backend/app/model/database.go
  backend/app/model/remote_db.go
  backend/app/repo/app_install.go
  backend/app/repo/database.go
  backend/app/repo/remote_db.go
  backend/app/service/app_install.go
  backend/app/service/backup_app.go
  backend/app/service/backup_mysql.go
  backend/app/service/cronjob_helper.go
  backend/app/service/database.go
  backend/app/service/database_mysql.go
  backend/app/service/entry.go
  backend/init/hook/hook.go
  backend/init/migration/migrate.go
  backend/init/migration/migrations/init.go
  backend/router/ro_app.go
  backend/router/ro_database.go
  backend/utils/mysql/client/local.go
  backend/utils/mysql/client/remote.go
  cmd/server/docs/docs.go
  cmd/server/docs/swagger.json
  cmd/server/docs/swagger.yaml
  frontend/src/api/interface/database.ts
  frontend/src/api/modules/app.ts
  frontend/src/api/modules/database.ts
  frontend/src/components/app-status/index.vue
  frontend/src/components/upload/index.vue
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/routers/modules/database.ts
  frontend/src/views/database/mysql/conn/index.vue
  frontend/src/views/database/mysql/create/index.vue
  frontend/src/views/database/mysql/delete/index.vue
  frontend/src/views/database/mysql/index.vue
  frontend/src/views/database/mysql/password/index.vue
  frontend/src/views/database/mysql/remote/index.vue
  frontend/src/views/database/mysql/remote/operate/index.vue
  frontend/src/views/database/mysql/setting/index.vue
  frontend/src/views/database/mysql/setting/slow-log/index.vue
  frontend/src/views/database/mysql/setting/status/index.vue
  frontend/src/views/database/mysql/setting/variables/index.vue
  frontend/src/views/database/redis/index.vue
  frontend/src/views/database/redis/password/index.vue
  frontend/src/views/website/website/create/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2102 Update README.md
  README.md
Labels: do-not-merge/release-note-label-needed, dev

#2103 feat: 修改 user-info 指令的输出
  cmd/server/cmd/user-info.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2104 fix: 解决 Openresty 获取状态异常的问题
  backend/app/service/app_install.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2105 fix: 修改数据库 migration
  backend/init/migration/migrate.go
  backend/init/migration/migrations/init.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2109 feat: 应用安装支持选择多数据库
  backend/app/repo/database.go
  backend/app/service/app.go
  backend/app/service/app_utils.go
  backend/app/service/database.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2112 fix: 1pctl 增加非 root 提示信息
  cmd/server/cmd/app.go
  cmd/server/cmd/reset.go
  cmd/server/cmd/root.go
  cmd/server/cmd/user-info.go
  cmd/server/cmd/version.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2116 feat: 防火墙支持删除系统占用端口
  frontend/src/views/host/firewall/port/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2110 fix: 1pctl 增加回滚功能
  cmd/server/cmd/restore.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2121 feat: 防火墙列表增加状态、策略筛选项
  backend/app/api/v1/firewall.go
  backend/app/dto/firewall.go
  backend/app/model/firewall.go
  backend/app/repo/host.go
  backend/app/service/firewall.go
  backend/init/migration/migrations/init.go
  frontend/src/api/interface/host.ts
  frontend/src/views/database/mysql/index.vue
  frontend/src/views/host/firewall/ip/index.vue
  frontend/src/views/host/firewall/port/index.vue
  frontend/src/views/setting/snapshot/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2129 fix: 解决 deepin 获取 ssh 服务状态失败的问题
  backend/app/service/ssh.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2130 feat: 应用安装支持选择 mariadb 和其他 mysql
  backend/app/model/app_install_resource.go
  backend/app/repo/database.go
  backend/app/service/app.go
  backend/app/service/app_install.go
  backend/app/service/app_utils.go
  backend/init/migration/migrate.go
  backend/init/migration/migrations/init.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2133 fix: 解决同步数据库失败的问题
  backend/app/service/database_mysql.go
  backend/utils/mysql/client.go
  backend/utils/mysql/client/info.go
  backend/utils/mysql/client/local.go
  backend/utils/mysql/client/remote.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2136 fix: 数据库样式调整
  backend/app/api/v1/database.go
  backend/app/dto/database.go
  backend/app/service/database.go
  backend/app/service/database_mysql.go
  cmd/server/docs/docs.go
  cmd/server/docs/swagger.json
  cmd/server/docs/swagger.yaml
  frontend/src/api/interface/database.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/cronjob/operate/index.vue
  frontend/src/views/cronjob/record/index.vue
  frontend/src/views/database/mysql/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2137 fix: 解决侧边栏收起状态下菜单长度不一致的问题
  frontend/src/layout/components/Sidebar/index.scss
Labels: do-not-merge/release-note-label-needed
