Repository 1Panel-dev/1Panel, pull requests merged in 2023-03, with the labels that each got.

#218 fix: 解决打开应用详情页，控制台报错的 BUG
  frontend/src/views/app-store/detail/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved

#219 fix: 敏感字符增加传输加密
  backend/app/api/v1/backup.go
  backend/app/api/v1/database_mysql.go
  backend/app/api/v1/database_redis.go
  backend/app/api/v1/file.go
  backend/app/api/v1/host.go
  backend/app/service/logs.go
  backend/app/service/upgrade.go
  backend/utils/ssh/ssh_test.go
  frontend/src/api/modules/database.ts
  frontend/src/api/modules/host.ts
  frontend/src/api/modules/setting.ts
Labels: do-not-merge/release-note-label-needed, lgtm, approved

#224 fix: 容器部分已知问题修改
  backend/app/dto/container.go
  backend/app/service/container.go
  backend/app/service/container_volume.go
  backend/constant/errs.go
  backend/i18n/lang/en.yaml
  backend/i18n/lang/zh.yaml
  frontend/src/api/interface/container.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/container/compose/detail/index.vue
  frontend/src/views/container/container/index.vue
  frontend/src/views/container/image/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved

#230 feat: 修改 action name
  .github/workflows/add-labels-for-pr.yml
Labels: do-not-merge/release-note-label-needed, dev

#247 fix: 解决 mysql 慢日志设置修改失败的问题
  frontend/package-lock.json
  frontend/src/components/container-log/index.vue
  frontend/src/views/container/container/log/index.vue
  frontend/src/views/database/mysql/setting/slow-log/index.vue
  frontend/src/views/host/terminal/host/operate/index.vue
Labels: lgtm, do-not-merge/release-note-label-needed, dev, approved

#252 fix: 容器删除使用中对象提示信息优化
  backend/app/service/container_network.go
  backend/app/service/container_volume.go
  backend/app/service/image.go
  backend/constant/errs.go
  backend/i18n/lang/en.yaml
  backend/i18n/lang/zh.yaml
  frontend/src/views/log/operation/index.vue
  frontend/src/views/setting/snapshot/index.vue
Labels: lgtm, do-not-merge/release-note-label-needed, dev, approved

#262 fix: 表格可点击列超长样式优化
  frontend/components.d.ts
  frontend/src/components/tooltip/index.vue
  frontend/src/views/container/compose/detail/index.vue
  frontend/src/views/container/compose/index.vue
  frontend/src/views/container/container/index.vue
  frontend/src/views/container/image/index.vue
  frontend/src/views/container/network/index.vue
  frontend/src/views/container/template/index.vue
  frontend/src/views/container/volume/index.vue
  frontend/src/views/cronjob/index.vue
  frontend/src/views/cronjob/record/index.vue
  frontend/src/views/website/website/index.vue
Labels: lgtm, do-not-merge/release-note-label-needed, dev, approved

#270 fix: 国际化换行问题修改
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/setting/panel/password/index.vue
Labels: lgtm, do-not-merge/release-note-label-needed, dev, approved

#272 Update README.md
  README.md
Labels: do-not-merge/release-note-label-needed, dev

#276 feat: 修改 .gitignore 规则
  .gitignore
  cmd/server/web/favicon.png
Labels: lgtm, do-not-merge/release-note-label-needed, dev, approved

#278 Update README.md
  README.md
Labels: do-not-merge/release-note-label-needed

#291 fix: 解决计划任务备份文件失效仍能下载的问题
  backend/app/api/v1/backup.go
  backend/app/api/v1/cronjob.go
  backend/app/api/v1/file.go
  backend/app/repo/cronjob.go
  backend/app/service/cornjob.go
  backend/app/service/cronjob_helper.go
  backend/router/ro_file.go
  cmd/server/docs/docs.go
  cmd/server/docs/swagger.json
  cmd/server/docs/swagger.yaml
  frontend/src/api/modules/container.ts
  frontend/src/api/modules/cronjob.ts
  frontend/src/api/modules/files.ts
  frontend/src/api/modules/setting.ts
  frontend/src/components/backup/index.vue
  frontend/src/views/cronjob/record/index.vue
Labels: lgtm, do-not-merge/release-note-label-needed, dev, approved

#298 ci: add workflow to sync to Gitee repo
  .github/workflows/sync2gitee.yml
Labels: lgtm, do-not-merge/release-note-label-needed

#303 Update README.md
  README.md
Labels: do-not-merge/release-note-label-needed, dev

#306 Fix typo in image.go
  backend/app/service/image.go
Labels: lgtm, do-not-merge/release-note-label-needed, approved

#313 feat: 删除自动创建 pr 的 workflow
  .github/workflows/create-pr-from-push.yml
Labels: do-not-merge/release-note-label-needed

#318 fix: 创建编排改为异步操作
  backend/app/api/v1/container.go
  backend/app/service/container.go
  backend/app/service/container_compose.go
  backend/utils/compose/compose.go
  frontend/src/api/modules/container.ts
  frontend/src/views/container/compose/create/index.vue
  frontend/src/views/container/image/build/index.vue
Labels: lgtm, do-not-merge/release-note-label-needed, dev, approved

#322 feat: 登录增加社区软件许可协议同意选项
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/store/index.ts
  frontend/src/store/interface/index.ts
  frontend/src/views/login/components/login-form.vue
Labels: lgtm, do-not-merge/release-note-label-needed, dev, approved

#333 fix: 解决网站定时任务没有执行的BUG
  backend/constant/website.go
  backend/cron/job/ssl.go
  backend/cron/job/website.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#339 删除 issue 处理相关 workflow
  .github/workflows/issue-close.yml
  .github/workflows/issue-comment.yml
  .github/workflows/issue-open.yml
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#337 feat: 证书列表增加设置自动续签功能
  backend/app/api/v1/file.go
  backend/app/api/v1/website_ssl.go
  backend/app/dto/request/website_ssl.go
  backend/app/service/website_ssl.go
  backend/router/ro_website_ssl.go
  cmd/server/docs/docs.go
  cmd/server/docs/swagger.json
  cmd/server/docs/swagger.yaml
  frontend/src/api/interface/website.ts
  frontend/src/api/modules/website.ts
  frontend/src/views/website/ssl/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#341 fix: 升级逻辑调整
  backend/app/api/v1/upgrade.go
  backend/app/dto/setting.go
  backend/app/service/upgrade.go
  backend/router/ro_setting.go
  cmd/server/docs/docs.go
  cmd/server/docs/swagger.json
  cmd/server/docs/swagger.yaml
  frontend/src/api/interface/setting.ts
  frontend/src/api/modules/setting.ts
  frontend/src/components/system-upgrade/index.vue
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/zh.ts
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#342 fix: 修改镜像构建和编排创建路径限制，增加 config 校验
  backend/app/api/v1/container.go
  backend/app/service/container_compose.go
  backend/app/service/image.go
  backend/router/ro_container.go
  cmd/server/docs/docs.go
  cmd/server/docs/swagger.json
  cmd/server/docs/swagger.yaml
  frontend/src/api/modules/container.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/container/compose/create/index.vue
  frontend/src/views/container/image/build/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#343 fix: 解决数据库密码修改未同步到应用的问题
  backend/app/repo/app_install.go
  backend/app/service/app_install.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#345 fix: 解决快照同步恢复失败的问题
  backend/app/service/snapshot.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#355 fix: 解决文件编辑，快捷提示不显示的 BUG
  frontend/src/layout/layout-content.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#361 fix: 优化导入备份限制
  backend/app/api/v1/file.go
  cmd/server/docs/docs.go
  cmd/server/docs/swagger.json
  cmd/server/docs/swagger.yaml
  frontend/src/components/upload/index.vue
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/host/file-management/upload/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#356 fix: 优化容器菜单页面状态加载样式
  frontend/src/styles/common.scss
  frontend/src/views/container/compose/index.vue
  frontend/src/views/container/container/index.vue
  frontend/src/views/container/image/index.vue
  frontend/src/views/container/network/index.vue
  frontend/src/views/container/repo/index.vue
  frontend/src/views/container/template/index.vue
  frontend/src/views/container/volume/index.vue
  frontend/src/views/database/mysql/index.vue
  frontend/src/views/database/redis/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#363 feat: 应用编辑增加 select 类型处理
  backend/app/dto/app.go
  backend/app/dto/response/app.go
  backend/app/service/app_install.go
  cmd/server/docs/docs.go
  cmd/server/docs/swagger.json
  cmd/server/docs/swagger.yaml
  frontend/src/api/interface/app.ts
  frontend/src/views/app-store/detail/params/index.vue
  frontend/src/views/app-store/installed/detail/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#364 fix: 优化计划任务记录查询返回
  frontend/src/views/cronjob/record/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#369 fix: 解决应用创建没有默认网络创建失败的BUG
  backend/app/service/app.go
  backend/constant/errs.go
  backend/i18n/lang/en.yaml
  backend/i18n/lang/zh.yaml
  backend/init/app/app.go
  backend/utils/docker/docker.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#371 fix: 优化分组显示
  backend/app/service/group.go
  frontend/src/components/group/index.vue
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/home/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#372 feat: 优化网站分组
  backend/app/api/v1/entry.go
  backend/app/api/v1/website_group.go
  backend/app/model/website_group.go
  backend/app/repo/entry.go
  backend/app/repo/group.go
  backend/app/repo/website_group.go
  backend/app/service/entry.go
  backend/app/service/group.go
  backend/app/service/website_group.go
  backend/init/migration/migrate.go
  backend/init/migration/migrations/init.go
  backend/router/ro_group.go
  backend/router/ro_host.go
  frontend/src/api/interface/website.ts
  frontend/src/api/modules/group.ts
  frontend/src/api/modules/host.ts
  frontend/src/api/modules/website.ts
  frontend/src/components/group/index.vue
  frontend/src/views/host/terminal/host/change-group/index.vue
  frontend/src/views/host/terminal/host/index.vue
  frontend/src/views/host/terminal/host/operate/index.vue
  frontend/src/views/website/website/config/basic/other/index.vue
  frontend/src/views/website/website/create/index.vue
  frontend/src/views/website/website/group/index.vue
  frontend/src/views/website/website/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#378 Pr@dev@docs add readme en.md
  README.md
  README_EN.md
Labels: do-not-merge/release-note-label-needed, dev

#377 feat: 网站分组删除校验
  backend/app/service/group.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#380 fix: 修改构建失败判断条件
  backend/app/service/container.go
  backend/app/service/image.go
  frontend/src/api/modules/container.ts
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#383 fix: 解决 mfa 验证回车时触发页面刷新的问题
  backend/app/dto/auth.go
  backend/app/service/auth.go
  frontend/src/api/interface/auth.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/login/components/login-form.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#385 fix: 解决设置默认分组的问题
  backend/app/dto/group.go
  backend/app/repo/group.go
  backend/app/service/group.go
  frontend/src/components/group/index.vue
  frontend/src/views/login/components/login-form.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#390 fix: 修改默认升级版本
  backend/app/service/upgrade.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#412 chore: 简化社区软件协议文案
  frontend/src/lang/modules/zh.ts
Labels: do-not-merge/release-note-label-needed, dev

#425 fix: 登录页面优化适配
  frontend/src/views/login/index.vue
Labels: do-not-merge/release-note-label-needed, dev, approved

#432 fix: 修复了部分容器创建完直接退出的问题
  backend/app/service/container.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#433 fix: 修复了创建容器自动拉取镜像失败的问题
  backend/app/service/container.go
  frontend/src/api/modules/container.ts
  frontend/src/views/container/image/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#436 fix: 修复了 jwt 无法登录的问题
  backend/app/api/v1/auth.go
  backend/init/router/router.go
  backend/middleware/jwt.go
  backend/middleware/session.go
  cmd/server/docs/docs.go
  cmd/server/docs/swagger.json
  cmd/server/docs/swagger.yaml
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#442 fix: 修复了概览页未显示挂载磁盘信息的问题
  backend/app/dto/dashboard.go
  backend/app/service/dashboard.go
  frontend/src/api/interface/dashboard.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/home/index.vue
  frontend/src/views/home/status/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#443 fix: 优化了概览页、监控页选项排序
  backend/app/api/v1/monitor.go
  backend/app/dto/dashboard.go
  backend/app/service/dashboard.go
  cmd/server/docs/docs.go
  cmd/server/docs/swagger.json
  cmd/server/docs/swagger.yaml
  frontend/src/api/interface/dashboard.ts
  frontend/src/views/home/app/index.vue
  frontend/src/views/home/index.vue
  frontend/src/views/home/status/index.vue
Labels: dev, lgtm, approved

#450 fix: 修复登录页面从大屏切换小屏填写信息消失问题
  frontend/src/views/login/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#448 feat: xterm-Support for Ctrl+MouseWheel to scaling fonts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/host/file-management/code-editor/index.vue
  frontend/src/views/host/terminal/terminal/terminal.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved

#458 fix: 概览页磁盘显示过滤规则修改
  backend/app/service/dashboard.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#459 fix: 解决 opencontainers/runc 系统漏洞
  go.mod
  go.sum
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#461 fix: 解决 nexus 安装失败的问题
  backend/app/service/app.go
  backend/app/service/app_utils.go
  backend/utils/files/file_op.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#462 fix: 修复了重启后计划任务执行周期错误的问题
  backend/cron/cron.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#465 style: 修改编辑器行尾符提示
  frontend/src/views/host/file-management/code-editor/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#468 fix: 修复了执行周期更新失败的问题
  backend/app/service/cornjob.go
Labels: do-not-merge/release-note-label-needed, dev
