Repository 1Panel-dev/1Panel, pull requests merged in 2023-04, with the labels that each got.

#506 fix: 修复前端开发时后端接口代理无法正常连接 WebSocket 的问题
  frontend/vite.config.ts
Labels: do-not-merge/release-note-label-needed, lgtm, approved

#512 fix: 监控数据改为批量插入
  backend/cron/job/monitor.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#514 feat: 增加 S3 兼容存储对象文档跳转
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/setting/backup-account/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#515 fix: 防火墙样式调整
  backend/app/service/firewall.go
  frontend/src/routers/modules/host.ts
  frontend/src/views/host/firewall/ip/operate/index.vue
  frontend/src/views/host/firewall/status/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#516 fix: 处理 docker 漏洞
  go.mod
  go.sum
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#517 fix: 调整服务未启动的遮罩样式
  frontend/src/components/app-status/index.vue
  frontend/src/views/database/mysql/index.vue
  frontend/src/views/database/redis/index.vue
  frontend/src/views/host/firewall/ip/index.vue
  frontend/src/views/host/firewall/port/index.vue
  frontend/src/views/host/firewall/status/index.vue
  frontend/src/views/website/website/index.vue
  go.sum
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#518 fix: 解决备份账号创建后，未重制 bucket 选项的问题
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/setting/backup-account/index.vue
  frontend/src/views/setting/backup-account/operate/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#519 feat: 运行环境样式修改
  backend/app/service/app_install.go
  backend/app/service/app_utils.go
  backend/app/service/website.go
  backend/init/migration/migrations/init.go
  frontend/src/components/status/index.vue
  frontend/src/views/app-store/detail/index.vue
  frontend/src/views/website/runtime/create/index.vue
  frontend/src/views/website/runtime/index.vue
  frontend/src/views/website/ssl/index.vue
  frontend/src/views/website/website/create/index.vue
  frontend/src/views/website/website/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#521 feat: 文件增加批量删除功能
  frontend/src/views/host/file-management/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#522 fix: 解决应用一直安装中的 BUG
  backend/app/service/app.go
  backend/app/service/app_utils.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#525 fix: 解决安装应用同步之后变为失败的 BUG
  backend/app/service/app.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#526 feat: 计划任务支持备份所有
  backend/app/service/cronjob_helper.go
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/cronjob/operate/index.vue
  frontend/src/views/cronjob/record/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#527 fix: 解决 go 版本升级导致的代码警告
  backend/app/api/v1/docker.go
  backend/app/api/v1/file.go
  backend/app/service/app.go
  backend/app/service/app_install.go
  backend/app/service/backup_redis.go
  backend/app/service/container.go
  backend/app/service/container_volume.go
  backend/app/service/cronjob_helper.go
  backend/app/service/database_mysql.go
  backend/app/service/database_redis.go
  backend/app/service/docker.go
  backend/app/service/image.go
  backend/app/service/image_repo.go
  backend/app/service/nginx.go
  backend/app/service/snapshot.go
  backend/app/service/upgrade.go
  backend/log/writer.go
  backend/middleware/operation.go
  backend/utils/cloud_storage/client/sftp.go
  backend/utils/firewall/client/ufw.go
  backend/utils/nginx/dumper.go
  backend/utils/ssl/acme_test.go
  frontend/tsconfig.json
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#528 feat: 增加计划任务记录清空按钮
  backend/app/api/v1/cronjob.go
  backend/app/repo/cronjob.go
  backend/app/service/cornjob.go
  backend/router/ro_cronjob.go
  cmd/server/docs/docs.go
  cmd/server/docs/swagger.json
  cmd/server/docs/swagger.yaml
  frontend/src/api/modules/cronjob.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/cronjob/record/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#529 feat: 计划任务记录增加定时刷新
  frontend/src/views/container/compose/create/index.vue
  frontend/src/views/container/container/log/index.vue
  frontend/src/views/container/image/build/index.vue
  frontend/src/views/container/image/pull/index.vue
  frontend/src/views/container/image/push/index.vue
  frontend/src/views/cronjob/record/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#530 fix: 解决 docker 配置修改提示信息错误的问题
  frontend/src/views/container/setting/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#533 fix: 监控界面时间控件居中显示
  frontend/src/views/host/monitor/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#534 fix: 解决升级应用失败的 BUG
  backend/app/model/app_install.go
  backend/app/service/app_install.go
  backend/app/service/app_utils.go
  backend/utils/compose/compose.go
  backend/utils/docker/compose.go
  frontend/src/lang/modules/en.ts
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#535 fix: docker 配置增加 iptables
  backend/app/dto/docker.go
  backend/app/service/docker.go
  frontend/src/api/interface/container.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/container/setting/index.vue
  frontend/src/views/host/firewall/port/index.vue
  frontend/src/views/host/firewall/status/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#536 fix: 完善系统操作日志
  backend/app/api/v1/firewall.go
  backend/app/api/v1/group.go
  backend/app/api/v1/host.go
  cmd/server/docs/docs.go
  cmd/server/docs/swagger.json
  cmd/server/docs/swagger.yaml
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/zh.ts
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#537 feat: 增加同步本地应用功能
  backend/app/api/v1/app.go
  backend/app/model/app.go
  backend/app/model/app_install.go
  backend/app/repo/app.go
  backend/app/service/app.go
  backend/app/service/app_utils.go
  backend/app/service/backup_app.go
  backend/constant/app.go
  backend/constant/dir.go
  backend/init/app/app.go
  backend/init/business/business.go
  backend/init/migration/migrate.go
  backend/init/migration/migrations/init.go
  frontend/components.d.ts
  frontend/src/views/app-store/apps/index.vue
  frontend/src/views/app-store/installed/index.vue
  frontend/src/views/host/file-management/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#538 feat: 前端启动配置可以通过 IP 访问
  frontend/vite.config.ts
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#541 feat: 优化前端页面打开速度
  backend/init/router/router.go
  frontend/.env.development
  frontend/.env.production
  frontend/vite.config.ts
  go.mod
  go.sum
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#542 fix: 解决 echart 前端报错
  frontend/vite.config.ts
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#543 feat: 文件支持输入URL直接访问
  frontend/src/views/host/file-management/hooks/searchable.ts
  frontend/src/views/host/file-management/index.vue
Labels: do-not-merge/release-note-label-needed

#545 feat: 运行环境应用和版本增加联动
  frontend/src/views/website/runtime/create/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#546 feat: 创建应用忽略创建默认 network
  backend/utils/docker/compose.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#548 feat: 计划任务支持自定义日志保留份数
  backend/app/service/cornjob.go
  backend/app/service/cronjob_helper.go
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/cronjob/index.vue
  frontend/src/views/cronjob/operate/index.vue
  frontend/src/views/cronjob/record/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#549 feat: 创建运行环境增加版本校验
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/website/runtime/create/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#550 fix: 解决创建运行环境报错的 BUG
  backend/app/service/app_utils.go
  backend/app/service/runtime.go
  backend/app/service/runtime_utils.go
  backend/utils/docker/compose.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#551 fix: 解决表单修改 iptables 失败的问题
  backend/app/service/docker.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#552 fix: 解决禁 ping 状态切换失败的问题
  frontend/src/views/host/firewall/status/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#553 fix: 容器配置文件为空时，删除配置文件
  backend/app/service/docker.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#554 fix: 解决用户授权失败的问题
  backend/app/service/database_mysql.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#555 feat: 数据库创建支持随机密码
  frontend/src/views/database/mysql/create/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#556 feat: mysql root 密码增加随机和复制按钮
  frontend/src/views/database/mysql/root-password/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#557 fix: 解决禁 ping 状态获取失败的问题
  backend/utils/firewall/client/firewalld.go
  frontend/src/views/host/firewall/status/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#559 fix: 解决已安装应用包含大写字母，启动失败的BUG
  backend/app/service/website.go
  backend/utils/docker/compose.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#560 fix: 防火墙端口校验规则修改
  frontend/src/utils/util.ts
  frontend/src/views/host/firewall/port/operate/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#561 fix: 容器创建中命令输入方式修改
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/container/container/create/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#562 feat: 网站列表增加运行环境字段
  backend/app/dto/response/website.go
  backend/app/service/website.go
  frontend/src/api/interface/website.ts
  frontend/src/views/website/website/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#563 feat: 应用更新端口之后放开相应防火墙端口
  backend/app/service/app_install.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#564 fix: 解决 Swarm 模式下，启用 live-restore 重启失败的问题
  backend/app/dto/docker.go
  backend/app/service/docker.go
  frontend/src/api/interface/container.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/container/setting/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#565 fix: 解决修改分组之后 网站页面过滤条件分组没有刷新的问题
  backend/app/service/app.go
  backend/app/service/app_utils.go
  backend/cron/cron.go
  backend/utils/files/file_op.go
  frontend/src/views/website/website/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#566 fix: 解决本地运行环境网站被删除之后 误删其他应用的BUG
  backend/app/service/website.go
  backend/app/service/website_utils.go
  frontend/src/views/website/website/create/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#567 fix: 解决编辑主机信息时，未输入密码或密钥测试连接失败的问题
  backend/app/api/v1/host.go
  backend/app/service/host.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#568 feat: 本地运行环境限制编辑 PHP 文件
  frontend/src/views/website/website/config/resource/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#569 style: 取消一行同步应用的日志打印
  backend/app/service/app.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#570 feat: 主机增加记住密码，支持带密码私钥连接
  backend/app/api/v1/host.go
  backend/app/api/v1/terminal.go
  backend/app/dto/host.go
  backend/app/model/host.go
  backend/app/service/host.go
  backend/init/migration/migrate.go
  backend/init/migration/migrations/init.go
  backend/utils/ssh/ssh.go
  frontend/src/api/interface/host.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/host/terminal/host/operate/index.vue
  frontend/src/views/host/terminal/terminal/host-create.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#571 style: runtime列表样式修改
  frontend/src/views/website/runtime/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#573 feat: 数据库增加 ServiceName 显示
  backend/app/api/v1/app_install.go
  backend/app/dto/response/app.go
  backend/app/repo/app_install.go
  backend/app/service/app_install.go
  backend/router/ro_app.go
  cmd/server/docs/docs.go
  cmd/server/docs/swagger.json
  cmd/server/docs/swagger.yaml
  frontend/src/api/interface/app.ts
  frontend/src/api/modules/app.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/database/mysql/index.vue
  frontend/src/views/database/mysql/root-password/index.vue
  frontend/src/views/database/redis/index.vue
  frontend/src/views/database/redis/password/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#574 fix: 保存主机信息必须先通过连接测试
  frontend/src/views/host/terminal/host/operate/index.vue
  frontend/src/views/host/terminal/terminal/host-create.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#575 fix: 补全备份列表返回信息
  backend/app/service/backup.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#576 fix: 解决安装应用锁库的问题
  backend/app/repo/app_install.go
  backend/app/service/app.go
  backend/app/service/app_utils.go
  backend/app/service/database_mysql.go
  backend/app/service/website.go
  backend/app/service/website_utils.go
  backend/constant/errs.go
  backend/i18n/lang/en.yaml
  backend/i18n/lang/zh.yaml
  frontend/src/views/website/website/delete/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#577 fix: 防火墙禁 ping 方式修改
  backend/app/service/firewall.go
  backend/utils/firewall/client.go
  backend/utils/firewall/client/firewalld.go
  backend/utils/firewall/client/ufw.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#578 fix: 解决备份所有时，保留份数错误的问题
  backend/app/service/cronjob_helper.go
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/cronjob/record/index.vue
  frontend/src/views/setting/backup-account/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#580 feat: 计划任务删除时增加删除数据提示
  backend/app/api/v1/cronjob.go
  backend/app/dto/cronjob.go
  backend/app/service/cornjob.go
  backend/app/service/cronjob_helper.go
  frontend/src/api/modules/cronjob.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/cronjob/index.vue
  frontend/src/views/cronjob/record/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#581 fix: 解决计划任务下载失败的问题
  backend/app/service/cornjob.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#585 fix: 解决操作日志解析失败的问题
  backend/middleware/operation.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#586 fix: 解决开启防火墙未添加系统端口的问题
  backend/app/service/firewall.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#588 fix: 解决系统不存在 netstat 命令的问题
  backend/app/service/firewall.go
  backend/utils/common/common.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#589 fix: 计划任务列表样式调整
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/cronjob/index.vue
  frontend/src/views/cronjob/record/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#591 feat: 优化网站创建流程
  backend/app/api/v1/website.go
  backend/app/service/website.go
  backend/app/service/website_utils.go
  backend/constant/errs.go
  backend/i18n/lang/en.yaml
  backend/i18n/lang/zh.yaml
  backend/utils/cmd/cmd.go
  frontend/src/views/app-store/installed/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#592 feat: 优化网站、应用删除逻辑
  backend/app/api/v1/app_install.go
  backend/app/api/v1/website.go
  backend/app/service/app_install.go
  backend/app/service/app_utils.go
  backend/app/service/website.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#593 feat: 增加修改 PHP 文件的接口
  backend/app/api/v1/website.go
  backend/app/dto/request/website.go
  backend/app/service/website.go
  backend/router/ro_website.go
  cmd/server/docs/docs.go
  cmd/server/docs/swagger.json
  cmd/server/docs/swagger.yaml
  frontend/src/api/interface/website.ts
  frontend/src/api/modules/website.ts
  frontend/src/views/website/website/config/resource/php-fpm/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#594 fix: 解决 firewalld ip 范围规则不生效的问题
  backend/utils/firewall/client/firewalld.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#595 feat: 文件编辑器增加 python 语言
  frontend/src/global/mimetype.ts
  frontend/src/views/host/file-management/code-editor/index.vue
  frontend/src/views/host/file-management/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#597 fix: 解决计划任务清除所有数据失败的问题
  backend/app/service/cornjob.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#598 fix: 防火墙 ip 规则取消范围输入
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/host/firewall/ip/operate/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#599 fix: 解决删除本地运行环境报错的问题
  backend/app/service/runtime.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#600 fix: 计划任务删除提示样式优化
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/cronjob/record/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#601 fix: 防火墙禁 ping 样式优化
  frontend/src/views/container/compose/create/index.vue
  frontend/src/views/host/firewall/status/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#603 feat: 增加 cmd 执行时间
  backend/app/service/nginx_utils.go
  backend/app/service/website.go
  backend/utils/cmd/cmd.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#605 fix: 解决证书定时任务错误执行的问题
  backend/cron/job/ssl.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#606 fix: 解决概览页接口报错 500 的问题
  backend/app/service/dashboard.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#607 fix: 调整监控数据采集间隔
  backend/cron/cron.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#608 fix: 解决删除网站锁库的问题
  backend/app/service/website.go
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/website/website/create/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#611 feat: PHP 运行环境,限制 Openresty 版本
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/website/runtime/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#612 fix: 前端界面国际化优化
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/container/compose/create/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#613 feat: 解决编辑镜像之后会删除镜像的问题
  backend/app/service/runtime_utils.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#621 feat: 增加自动更新检测
  frontend/src/components/system-upgrade/index.vue
  frontend/src/store/index.ts
  frontend/src/store/interface/index.ts
  frontend/src/views/home/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#625 fix: 防火墙空状态页面样式优化
  frontend/src/components/app-status/index.vue
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/styles/common.scss
  frontend/src/views/host/firewall/ip/index.vue
  frontend/src/views/host/firewall/port/index.vue
  frontend/src/views/host/firewall/status/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#637 feat: 打开防火墙时，自动放开应用以及 80 443 22 端口
  backend/app/service/firewall.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#643 fix: 防火墙禁 ping 增加判断条件，不存在文件则隐藏
  backend/app/service/firewall.go
  backend/constant/status.go
  frontend/src/views/host/firewall/status/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#644 feat: 创建 PHP 运行环境同步修改index目录文件和文件夹权限
  backend/app/service/website_utils.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#647 feat: OpenResty 升级提示转到创建网站处
  frontend/src/views/website/runtime/index.vue
  frontend/src/views/website/website/create/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#655 fix: 修改页脚错误
  frontend/src/components/app-layout/footer/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#664 fix: 解决表单回车导致页面刷新的问题
  frontend/src/components/group/index.vue
  frontend/src/views/app-store/detail/install/index.vue
  frontend/src/views/app-store/installed/detail/index.vue
  frontend/src/views/app-store/installed/upgrade/index.vue
  frontend/src/views/container/container/monitor/index.vue
  frontend/src/views/container/container/rename/index.vue
  frontend/src/views/container/image/delete/index.vue
  frontend/src/views/container/image/load/index.vue
  frontend/src/views/database/mysql/remote/index.vue
  frontend/src/views/database/mysql/root-password/index.vue
  frontend/src/views/database/redis/password/index.vue
  frontend/src/views/host/file-management/move/index.vue
  frontend/src/views/host/terminal/host/change-group/index.vue
  frontend/src/views/website/ssl/acme-account/create/index.vue
  frontend/src/views/website/website/config/basic/default-doc/index.vue
  frontend/src/views/website/website/default/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#665 fix: 页脚特殊符号修改
  frontend/src/components/app-layout/footer/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#667 fix: 命令执行增加超时时间
  backend/app/service/cronjob_helper.go
  backend/app/service/snapshot.go
  backend/app/service/upgrade.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#668 feat: 运行环境支持手动输入 PHP 扩展
  backend/app/service/runtime_utils.go
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/website/runtime/edit/index.vue
  frontend/src/views/website/runtime/param/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#675 feat: 增加配置网站运行目录功能
  backend/app/api/v1/website.go
  backend/app/dto/request/website.go
  backend/app/model/website.go
  backend/app/service/website.go
  backend/app/service/website_utils.go
  backend/init/migration/migrations/init.go
  backend/router/ro_website.go
  cmd/server/docs/docs.go
  cmd/server/docs/swagger.json
  cmd/server/docs/swagger.yaml
  frontend/src/api/interface/website.ts
  frontend/src/api/modules/website.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/website/website/config/basic/site-folder/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#676 fix: 登录页样式修改
  backend/init/router/router.go
  frontend/src/assets/iconfont/iconfont.css
  frontend/src/assets/iconfont/iconfont.js
  frontend/src/assets/iconfont/iconfont.json
  frontend/src/assets/iconfont/iconfont.svg
  frontend/src/assets/iconfont/iconfont.ttf
  frontend/src/assets/iconfont/iconfont.woff
  frontend/src/assets/iconfont/iconfont.woff2
  frontend/src/lang/modules/en.ts
  frontend/src/views/login/components/login-form.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#677 删除无用文件
  frontend/LICENSE
  frontend/README.md
  frontend/STANDARD.md
  frontend/src/lang/index.ts
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#684 feat: 删除提示页面增加换行
  frontend/src/views/app-store/installed/check/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#685 fix: 解决网站过期时间设置为永久之后再次打开过期时间错误的问题
  frontend/src/views/website/website/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#687 feat: mysql 和 redis 增加连接信息提示
  backend/app/dto/response/app.go
  backend/app/service/app_install.go
  frontend/src/api/interface/app.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/database/mysql/root-password/index.vue
  frontend/src/views/database/redis/password/index.vue
  frontend/src/views/website/website/config/basic/site-folder/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#688 style: 修改网站目录提示信息
  frontend/src/views/database/mysql/root-password/index.vue
  frontend/src/views/database/redis/password/index.vue
  frontend/src/views/website/website/config/basic/site-folder/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#691 fix: 延长快照超时时间
  backend/app/service/snapshot.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#693 style: 修改网站目录样式
  frontend/components.d.ts
  frontend/src/views/website/website/config/basic/site-folder/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#694 feat: 网站增加设置目录运行用户和用户组的功能
  backend/app/api/v1/website.go
  backend/app/dto/request/website.go
  backend/app/model/website.go
  backend/app/service/website.go
  backend/init/migration/migrations/init.go
  backend/router/ro_website.go
  frontend/src/api/interface/website.ts
  frontend/src/api/modules/website.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/website/website/config/basic/site-folder/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#695 fix: 解决网站目录重复的问题
  frontend/src/views/website/website/config/basic/limit-conn/index.vue
  frontend/src/views/website/website/config/basic/site-folder/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#710 fix: 解决网站设置用户/组报错的问题
  backend/app/service/website.go
  backend/utils/cmd/cmd.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#733 fix: ufw 防火墙增加 sudo 判断
  backend/app/service/firewall.go
  backend/utils/cmd/cmd.go
  backend/utils/firewall/client/ufw.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#736 fix: ufw 增加中文适配
  backend/utils/firewall/client/ufw.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#738 fix: 防火墙端口添加支持输入网段
  backend/app/service/firewall.go
  backend/utils/cmd/cmd.go
  backend/utils/firewall/client/ufw.go
  frontend/src/views/host/firewall/port/operate/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#740 fix: 验证码错误后清空验证码输入框
  frontend/src/views/login/components/login-form.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#741 feat: 静态网站默认页增加禁止搜索引擎收录
  cmd/server/nginx_conf/index.html
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#721 fix: 为了安全，使面板首页禁止搜索引擎收录
  frontend/index.html
Labels: do-not-merge/release-note-label-needed, lgtm, approved

#742 fix: 解决 ufw 防火墙版本加载失败问题
  backend/utils/firewall/client/ufw.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#746 fix: 解决中文插件下 ufw 防火墙获取端口列表失败的问题
  backend/utils/firewall/client/ufw.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#749 feat: 增加复制路径功能
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/host/file-management/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved

#775 style: 文件列表样式修改
  frontend/src/views/host/file-management/index.vue
  frontend/vite.config.ts
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#779 fix: 解决容器终端断开后未退出进程的问题
  backend/app/api/v1/terminal.go
  backend/utils/terminal/local_cmd.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#780 feat: 增加系统 ssl 设置功能
  backend/app/api/v1/setting.go
  backend/app/dto/setting.go
  backend/app/service/setting.go
  backend/configs/system.go
  backend/init/hook/hook.go
  backend/init/migration/migrate.go
  backend/init/migration/migrations/init.go
  backend/router/ro_setting.go
  backend/server/server.go
  backend/utils/ssl/ssl.go
  frontend/src/api/index.ts
  frontend/src/api/interface/setting.ts
  frontend/src/api/modules/setting.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/setting/safe/index.vue
  frontend/src/views/setting/safe/ssl/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#781 feat: 1pctl user-info 返回增加 protocol 信息
  cmd/server/cmd/user-info.go
  frontend/src/views/setting/safe/ssl/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#782 feat: 网站增加密码访问功能
  backend/app/api/v1/website.go
  backend/app/dto/nginx.go
  backend/app/dto/request/nginx.go
  backend/app/dto/response/nginx.go
  backend/app/service/website.go
  backend/constant/errs.go
  backend/i18n/lang/en.yaml
  backend/i18n/lang/zh.yaml
  backend/router/ro_website.go
  cmd/server/docs/docs.go
  cmd/server/docs/swagger.json
  cmd/server/docs/swagger.yaml
  frontend/src/api/interface/website.ts
  frontend/src/api/modules/website.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/website/website/config/basic/auth-basic/create/index.vue
  frontend/src/views/website/website/config/basic/auth-basic/index.vue
  frontend/src/views/website/website/config/basic/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#784 feat: 1pctl version 增加 mode 参数
  cmd/server/cmd/version.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#786 feat: 容器增加资源使用、端口显示
  backend/app/dto/container.go
  backend/app/service/container.go
  frontend/src/api/interface/container.ts
  frontend/src/api/modules/container.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/container/container/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#788 fix: 证书校验规则修改
  backend/app/service/setting.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#792 feat: 页脚增加论坛、文档入口
  frontend/src/components/app-layout/footer/index.vue
  frontend/src/components/system-upgrade/index.vue
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/zh.ts
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#793 feat: 修改反向代理网站创建逻辑
  backend/app/service/website.go
  backend/app/service/website_utils.go
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/website/website/config/basic/proxy/create/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#795 feat: 存储卷创建支持 nfs
  backend/app/service/container.go
  backend/app/service/docker.go
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/container/volume/create/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#798 fix: 解决文件复制到原路径导致文件内容清空的 BUG
  backend/utils/files/file_op.go
  frontend/src/views/host/file-management/code-editor/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#803 feat: 文件管理增加用户/用户组设置
  backend/app/api/v1/file.go
  backend/app/api/v1/setting.go
  backend/app/dto/request/file.go
  backend/app/service/file.go
  backend/router/ro_file.go
  backend/utils/files/file_op.go
  backend/utils/files/fileinfo.go
  backend/utils/files/utils.go
  cmd/server/docs/docs.go
  cmd/server/docs/swagger.json
  cmd/server/docs/swagger.yaml
  frontend/package-lock.json
  frontend/package.json
  frontend/src/api/interface/file.ts
  frontend/src/api/modules/files.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/host/file-management/chown/index.vue
  frontend/src/views/host/file-management/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#806 fix: compose 验证、提交按钮合并
  backend/app/service/container_compose.go
  backend/app/service/docker.go
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/container/compose/create/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#808 feat: 编排删除增加删除文件勾选
  backend/app/dto/container.go
  backend/app/service/container_compose.go
  frontend/src/api/interface/container.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/container/compose/create/index.vue
  frontend/src/views/container/compose/delete/index.vue
  frontend/src/views/container/compose/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#810 fix: 面板设置样式调整
  backend/middleware/password_expired.go
  frontend/src/views/setting/expired.vue
  frontend/src/views/setting/monitor/index.vue
  frontend/src/views/setting/panel/index.vue
  frontend/src/views/setting/safe/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#811 feat: 文件权限增加修改子文件功能
  backend/app/dto/request/file.go
  backend/app/service/file.go
  backend/utils/cmd/cmd.go
  backend/utils/files/file_op.go
  frontend/src/api/interface/file.ts
  frontend/src/views/host/file-management/change-role/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#812 style: 网站-密码访问 名称 改为 用户名
  frontend/src/views/website/website/config/basic/auth-basic/create/index.vue
  frontend/src/views/website/website/config/basic/auth-basic/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#814 feat: 安全登录界面样式优化
  frontend/components.d.ts
  frontend/src/assets/images/unsafe.svg
  frontend/src/components/error-message/unsafe.vue
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/login/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#813 fix: 解决本地应用升级失败的问题
  backend/app/service/app_utils.go
  frontend/src/views/host/file-management/code-editor/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#816 Update README.md
  README.md
Labels: do-not-merge/release-note-label-needed

#817 Update README.md
  README.md
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#818 feat: 1pctl 支持 mfa、ssl 和安全入口关闭
  cmd/server/cmd/reset.go
  cmd/server/cmd/root.go
  cmd/server/cmd/user-info.go
  cmd/server/cmd/version.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#820 style: 运行环境页面增加提示
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/website/runtime/create/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#819 feat: 文件搜索增加搜索子目录功能
  backend/utils/files/fileinfo.go
  backend/utils/files/utils.go
  frontend/src/views/host/file-management/index.vue
  go.mod
  go.sum
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#821 fix: 安全入口逻辑调整
  backend/app/api/v1/setting.go
  backend/app/dto/setting.go
  backend/app/service/auth.go
  backend/app/service/setting.go
  backend/configs/system.go
  backend/init/migration/migrations/init.go
  backend/init/viper/viper.go
  backend/router/ro_setting.go
  cmd/server/cmd/reset.go
  cmd/server/docs/docs.go
  cmd/server/docs/swagger.json
  cmd/server/docs/swagger.yaml
  frontend/src/api/interface/setting.ts
  frontend/src/api/modules/setting.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/home/index.vue
  frontend/src/views/log/operation/index.vue
  frontend/src/views/setting/panel/index.vue
  frontend/src/views/setting/safe/entrance/index.vue
  frontend/src/views/setting/safe/index.vue
  frontend/src/views/setting/safe/timeout/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#822 feat: 两步验证增加手动输入选项
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/setting/safe/index.vue
  frontend/src/views/setting/safe/mfa/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#823 fix: 面板设置证书改为抽屉实现
  backend/init/router/router.go
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/setting/monitor/index.vue
  frontend/src/views/setting/panel/index.vue
  frontend/src/views/setting/panel/password/index.vue
  frontend/src/views/setting/safe/entrance/index.vue
  frontend/src/views/setting/safe/index.vue
  frontend/src/views/setting/safe/mfa/index.vue
  frontend/src/views/setting/safe/ssl/index.vue
  frontend/src/views/setting/safe/timeout/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#824 fix: 解决回车导致页面刷新的问题
  frontend/src/views/container/compose/create/index.vue
  frontend/src/views/host/terminal/command/index.vue
  frontend/src/views/setting/backup-account/operate/index.vue
  frontend/src/views/setting/monitor/index.vue
  frontend/src/views/setting/safe/entrance/index.vue
  frontend/src/views/setting/safe/mfa/index.vue
  frontend/src/views/setting/safe/timeout/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#825 style: 网站列表增加 WAF 入口
  backend/init/router/router.go
  frontend/package-lock.json
  frontend/src/views/website/website/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#826 feat: 解决文件上传成功后再次点击“确认”会重新上传一遍的问题
  frontend/src/views/host/file-management/upload/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#827 fix: 两步验证样式调整
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/setting/safe/mfa/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#830 fix: 解决容器创建批量端口失败的问题
  backend/app/service/container.go
  backend/constant/errs.go
  backend/i18n/lang/en.yaml
  backend/i18n/lang/zh.yaml
  frontend/src/views/container/container/create/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#842 feat: 验证码输入判断逻辑修改
  backend/app/api/v1/auth.go
  backend/app/dto/auth.go
  cmd/server/docs/docs.go
  cmd/server/docs/swagger.json
  cmd/server/docs/swagger.yaml
  frontend/src/api/interface/auth.ts
  frontend/src/store/index.ts
  frontend/src/store/interface/index.ts
  frontend/src/views/login/components/login-form.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved
