Repository 1Panel-dev/1Panel, pull requests merged in 2023-12, with the labels that each got.

#3126 feat: 证书模块增加一些提示
  backend/app/service/website_ssl.go
  backend/init/migration/migrations/v_1_9.go
  backend/utils/ssl/acme.go
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/website/ssl/acme-account/create/index.vue
  frontend/src/views/website/ssl/create/index.vue
  frontend/src/views/website/ssl/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3136 feat: 数据库用户名自动填充
  frontend/src/views/database/mysql/create/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3135 feat: 实现同时拖拽上传文件和文件夹
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/host/file-management/upload/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3144 feat:增加yii2框架的重写规则
  cmd/server/nginx_conf/rewrite/yii2.conf
  frontend/src/global/mimetype.ts
Labels: do-not-merge/release-note-label-needed

#3161 feat: 增加回收站开关功能
  backend/app/api/v1/recycle_bin.go
  backend/app/dto/setting.go
  backend/app/service/file.go
  backend/init/migration/migrate.go
  backend/init/migration/migrations/v_1_9.go
  backend/router/ro_file.go
  cmd/server/docs/docs.go
  cmd/server/docs/swagger.json
  cmd/server/docs/swagger.yaml
  frontend/src/api/modules/files.ts
  frontend/src/global/mimetype.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/host/file-management/delete/index.vue
  frontend/src/views/host/file-management/recycle-bin/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3163 feat: 1pctl 支持修改面板信息
  cmd/server/cmd/update.go
  cmd/server/cmd/user-info.go
  go.mod
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3162 feat: 应用升级版本列表增加排序
  backend/app/service/app_install.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3164 feat: CloudFlare DNS 证书改为使用 Token
  backend/utils/ssl/client.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3165 feat: 网站创建支持相同域名不同端口
  backend/app/service/website.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3166 feat: 网站支持按状态排序
  frontend/src/views/website/website/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3171 feat: 解决删除文件报错的问题
  backend/app/service/recycle_bin.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3175 feat: Swap 修改增加最大值限制
  backend/app/dto/device.go
  backend/app/service/device.go
  frontend/src/api/interface/toolbox.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/toolbox/device/hosts/index.vue
  frontend/src/views/toolbox/device/swap/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3181 fix: 增加部分表单校验
  backend/app/service/device.go
  backend/app/service/fail2ban.go
  backend/constant/errs.go
  backend/i18n/lang/en.yaml
  backend/i18n/lang/zh-Hant.yaml
  backend/i18n/lang/zh.yaml
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/setting/panel/name/index.vue
  frontend/src/views/setting/panel/username/index.vue
  frontend/src/views/toolbox/fail2ban/max-retry/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3182 feat: 网站 OpenResty 增加重载功能
  backend/app/service/app_install.go
  backend/constant/app.go
  frontend/src/components/app-status/index.vue
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3186 feat: 迁移缓存清理代码
  backend/app/api/v1/device.go
  backend/app/api/v1/setting.go
  backend/app/service/cronjob_helper.go
  backend/app/service/device.go
  backend/app/service/device_clean.go
  backend/app/service/setting.go
  backend/router/ro_setting.go
  backend/router/ro_toolbox.go
  cmd/server/docs/docs.go
  cmd/server/docs/swagger.json
  cmd/server/docs/swagger.yaml
  frontend/src/api/interface/setting.ts
  frontend/src/api/interface/toolbox.ts
  frontend/src/api/modules/setting.ts
  frontend/src/api/modules/toolbox.ts
  frontend/src/views/log/operation/index.vue
  frontend/src/views/toolbox/clean/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3187 fix: 解决复制之前文件被删除报错的问题
  backend/app/service/file.go
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/host/file-management/delete/index.vue
  frontend/src/views/website/runtime/php/param/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3188 feat: 远程下载文件忽略证书
  backend/utils/files/file_op.go
  backend/utils/http/get.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3189 feat: 数据库管理跳转增加 Adminer
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/database/mysql/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3193 fix: 解决容器编辑时删除暴露端口 IP 不生效的问题
  frontend/src/views/container/container/operate/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3200 fix: 解决自签证书填写 IP 不显示的问题
  backend/app/service/website_ca.go
  frontend/src/views/website/ssl/ca/obtain/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3202 fix: Fail2ban 配置文件区分系统
  backend/utils/toolbox/fail2ban.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3203 fix: 面板证书自动续签增加重启提示
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/setting/safe/ssl/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3211 fix: 优化主机测试连接逻辑
  backend/server/server.go
  frontend/src/views/host/terminal/host/operate/index.vue
  frontend/src/views/host/terminal/terminal/host-create.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3212 feat: 容器端口跳转增加 IPv4 IPv6 判断
  frontend/src/components/port-jump/index.vue
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/container/container/index.vue
  frontend/src/views/database/redis/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3213 fix: 部分界面样式调整
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/container/setting/sock-path/index.vue
  frontend/src/views/database/mysql/remote/operate/index.vue
  frontend/src/views/setting/safe/ssl/index.vue
  frontend/src/views/toolbox/clean/index.vue
  frontend/src/views/toolbox/device/dns/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3215 fix: 工具箱管理防止命令注入
  backend/app/dto/fail2ban.go
  backend/app/service/device.go
  backend/app/service/fail2ban.go
  backend/utils/toolbox/fail2ban.go
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/toolbox/device/swap/index.vue
  frontend/src/views/toolbox/fail2ban/index.vue
  frontend/src/views/toolbox/fail2ban/log-path/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3218 fix: 解决删除非面板 SSL 证书报错的问题
  backend/app/service/website_ssl.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3217 fix: 修改部分表单校验方法
  backend/app/service/fail2ban.go
  backend/app/service/logs.go
  backend/app/service/setting.go
  backend/utils/toolbox/fail2ban.go
  frontend/src/global/form-rules.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/setting/safe/timeout/index.vue
  frontend/src/views/toolbox/fail2ban/ban-time/index.vue
  frontend/src/views/toolbox/fail2ban/find-time/index.vue
  frontend/src/views/toolbox/fail2ban/max-retry/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3228 fix: 解决网站 PHP 版本切换报错的问题
  backend/app/service/website.go
  backend/app/service/website_utils.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3232 feat: 远程数据库增加是否开启 CA 验证选项
  backend/utils/mysql/client/info.go
  frontend/src/api/interface/database.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/container/container/operate/index.vue
  frontend/src/views/database/mysql/remote/operate/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3236 fix: 解决列表设置导致的浏览器抖动问题
  backend/app/service/device.go
  frontend/src/views/container/compose/index.vue
  frontend/src/views/container/container/index.vue
  frontend/src/views/container/container/upgrade/index.vue
  frontend/src/views/container/image/index.vue
  frontend/src/views/container/network/index.vue
  frontend/src/views/container/repo/index.vue
  frontend/src/views/container/template/index.vue
  frontend/src/views/container/volume/index.vue
  frontend/src/views/cronjob/index.vue
  frontend/src/views/database/mysql/index.vue
  frontend/src/views/host/firewall/ip/index.vue
  frontend/src/views/host/firewall/port/index.vue
  frontend/src/views/host/ssh/log/log.vue
  frontend/src/views/log/operation/index.vue
  frontend/src/views/setting/snapshot/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3249 fix: 解决容器名规则提示错误
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
Labels: do-not-merge/release-note-label-needed

#3250 refactor: 删除重复代码逻辑
  backend/app/api/v1/app_install.go
Labels: do-not-merge/release-note-label-needed

#3258 fix: 修改防火墙状态判断方式
  backend/app/dto/fail2ban.go
  backend/app/service/fail2ban.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3260 fix: 解决编辑进程守护名称/进程数量报错的问题
  frontend/src/views/app-store/installed/index.vue
  frontend/src/views/toolbox/supervisor/create/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3261 fix: Fail2ban 配置修改后重启服务
  backend/app/dto/fail2ban.go
  backend/app/service/fail2ban.go
  cmd/server/docs/docs.go
  cmd/server/docs/swagger.json
  cmd/server/docs/swagger.yaml
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/container/image/index.vue
  frontend/src/views/setting/backup-account/operate/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3263 feat: 容器列表端口展示优化
  backend/app/service/container.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3265 fix: 固定搜索框宽度
  frontend/src/styles/common.scss
  frontend/src/views/container/compose/index.vue
  frontend/src/views/container/container/index.vue
  frontend/src/views/container/image/index.vue
  frontend/src/views/container/network/index.vue
  frontend/src/views/container/repo/index.vue
  frontend/src/views/container/template/index.vue
  frontend/src/views/container/volume/index.vue
  frontend/src/views/cronjob/index.vue
  frontend/src/views/host/firewall/ip/index.vue
  frontend/src/views/host/firewall/port/index.vue
  frontend/src/views/host/ssh/log/log.vue
  frontend/src/views/log/operation/index.vue
  frontend/src/views/setting/snapshot/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3266 feat: 升级界面增加软件的网站跳转
  frontend/src/views/app-store/installed/upgrade/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3270 fix: 快速跳转样式调整
  backend/app/service/fail2ban.go
  backend/utils/toolbox/fail2ban.go
  frontend/src/components/app-status/index.vue
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/container/setting/ipv6/index.vue
  frontend/src/views/container/setting/sock-path/index.vue
  frontend/src/views/database/mysql/index.vue
  frontend/src/views/host/firewall/ip/index.vue
  frontend/src/views/host/firewall/port/index.vue
  frontend/src/views/toolbox/fail2ban/index.vue
  frontend/src/views/toolbox/supervisor/status/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3273 fix: 1pctl update 增加校验
  cmd/server/cmd/update.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3281 fix: 解决域名非 80 端口时快速跳转地址错误的问题
  frontend/src/views/website/website/config/basic/domain/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3282 fix: 解决应用升级网站链接跳转不生效的问题
  frontend/src/views/app-store/installed/index.vue
  frontend/src/views/toolbox/device/swap/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3284 fix: 解决网站手动导入证书错误的问题
  backend/app/service/website.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3285 fix: 解决网站日志开启关闭失败的问题
  frontend/src/api/interface/website.ts
  frontend/src/views/website/website/config/log/log-fiile/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3286 feat: 优化 PHP 运行环境日志
  backend/app/api/v1/runtime.go
  backend/app/service/runtime.go
  frontend/src/api/modules/runtime.ts
  frontend/src/views/website/runtime/php/create/index.vue
  frontend/src/views/website/runtime/php/index.vue
  frontend/src/views/website/ssl/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3287 fix: 解决容器镜像为空导致升级失败的问题
  backend/app/service/container.go
  backend/app/service/firewall.go
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/container/compose/create/index.vue
  frontend/src/views/container/container/upgrade/index.vue
  frontend/src/views/container/network/create/index.vue
  frontend/src/views/toolbox/fail2ban/ips/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3288 feat: 编排修改增加失败回滚操作
  backend/app/service/container_compose.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3291 fix: 优化计划任务备份所有下载提示
  backend/app/service/firewall.go
  backend/app/service/ssh.go
  cmd/server/cmd/update.go
  frontend/src/api/modules/host.ts
  frontend/src/views/container/compose/create/index.vue
  frontend/src/views/container/network/create/index.vue
  frontend/src/views/cronjob/record/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3295 fix: 解决容器端口加载错误的问题
  backend/app/service/container.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3297 Update SECURITY.md
  SECURITY.md
Labels: do-not-merge/release-note-label-needed

#3298 feat: 升级验证码组件版本到 v1.3.6
  backend/utils/captcha/captcha.go
  go.mod
  go.sum
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3299 feat: 增加 dns 修改提示信息
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/database/mysql/remote/operate/index.vue
  frontend/src/views/toolbox/device/dns/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3301 feat: 删除部分代码
  backend/app/service/website.go
Labels: do-not-merge/release-note-label-needed, dev

#3314 fix: 解决部分软件错误判断升级的问题
  backend/utils/common/common.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3315 feat: 目录选择增加显示隐藏文件夹
  frontend/src/components/file-list/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3318 fix: 解决 ssh 日志解析错误的问题
  backend/app/service/ssh.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3320 fix: 解决创建容器时拉取带认证仓库镜像失败的问题
  backend/app/service/container.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3321 fix: 修改 Supervisor 文档跳转路径
  frontend/src/views/toolbox/supervisor/status/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3322 feat: 支持编辑失败状态下的 Fail2ban 配置
  backend/app/service/fail2ban.go
  frontend/src/views/toolbox/fail2ban/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3324 feat: 远程下载文件增加是否忽略不可信证书选项
  backend/app/dto/request/file.go
  backend/app/service/file.go
  backend/utils/files/file_op.go
  frontend/src/api/interface/file.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/host/file-management/wget/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3328 fix: 增加工具箱获取超时时间
  backend/app/api/v1/device.go
  backend/app/service/device.go
  backend/router/ro_toolbox.go
  cmd/server/docs/docs.go
  cmd/server/docs/swagger.json
  cmd/server/docs/swagger.yaml
  frontend/src/api/modules/toolbox.ts
  frontend/src/views/home/status/index.vue
  frontend/src/views/toolbox/device/dns/index.vue
  frontend/src/views/toolbox/device/hostname/index.vue
  frontend/src/views/toolbox/device/hosts/index.vue
  frontend/src/views/toolbox/device/passwd/index.vue
  frontend/src/views/toolbox/device/swap/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3335 feat: 调整菜单次序
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/routers/modules/cronjob.ts
  frontend/src/routers/modules/host.ts
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3341 feat: 容器升级界面调整
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/container/container/upgrade/index.vue
  frontend/src/views/container/image/pull/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3343 fix: 解决部分文件上传失败的问题
  frontend/src/views/host/file-management/upload/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3344 feat: 不同类型 ACME 账号支持使用同一个邮箱
  backend/app/repo/website_acme_account.go
  backend/app/service/website_acme_account.go
  frontend/src/views/website/website/config/basic/https/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3346 feat: 镜像 Tag 逻辑修改
  backend/app/dto/image.go
  cmd/server/docs/docs.go
  cmd/server/docs/swagger.json
  cmd/server/docs/swagger.yaml
  frontend/src/api/interface/container.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/container/container/upgrade/index.vue
  frontend/src/views/container/image/delete/index.vue
  frontend/src/views/container/image/index.vue
  frontend/src/views/container/image/tag/index.vue
  frontend/src/views/toolbox/device/swap/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3348 feat: 优化 SSH 日志获取
  backend/app/api/v1/ssh.go
  backend/app/dto/ssh.go
  backend/app/service/ssh.go
  backend/router/ro_host.go
  cmd/server/docs/docs.go
  cmd/server/docs/swagger.json
  cmd/server/docs/swagger.yaml
  frontend/src/api/modules/host.ts
  frontend/src/views/host/ssh/log/analysis/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3349 feat: 证书部分增加一些提示
  backend/app/api/v1/website_ca.go
  cmd/server/docs/docs.go
  cmd/server/docs/swagger.json
  cmd/server/docs/swagger.yaml
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/website/ssl/acme-account/create/index.vue
  frontend/src/views/website/ssl/create/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3363 feat: 优化终端搜索样式及回滚条数显示
  frontend/src/components/terminal/index.vue
  frontend/src/views/host/terminal/terminal/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3364 feat: 防火墙增加重启按钮
  backend/app/dto/firewall.go
  cmd/server/docs/docs.go
  cmd/server/docs/swagger.json
  cmd/server/docs/swagger.yaml
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/host/firewall/status/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3365 feat: 工具箱操作增加超时时间
  frontend/src/api/modules/toolbox.ts
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3366 fix: 解决自签证书在导入机构 Root CA 之后仍然显示不安全的问题
  backend/app/service/website_ca.go
  backend/app/service/website_ssl.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3382 feat: 面板别名支持中文及空格
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/setting/panel/name/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3381 feat: SSH 支持同时监听 IPv4 及 IPv6
  backend/app/service/ssh.go
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/container/network/create/index.vue
  frontend/src/views/host/ssh/ssh/address/index.vue
  frontend/src/views/host/ssh/ssh/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3384 fix: 解决本地备份文件被删除导致的备份列表读取错误
  backend/app/service/backup.go
  backend/app/service/backup_app.go
  backend/app/service/backup_mysql.go
  backend/app/service/backup_redis.go
  backend/app/service/backup_website.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3386 fix: 解决暗黑模式下主机地址样式问题
  frontend/src/views/host/terminal/host/operate/index.vue
  frontend/src/views/host/terminal/terminal/host-create.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3389 fix: 优化部分界面滚动条样式
  frontend/src/views/container/compose/create/index.vue
  frontend/src/views/host/ssh/ssh/index.vue
  frontend/src/views/toolbox/device/dns/index.vue
  frontend/src/views/website/website/config/log/log-fiile/index.vue
  frontend/src/views/website/website/config/resource/nginx/index.vue
  frontend/src/views/website/website/config/resource/php-fpm/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3390 feat: 容器名称修改增加来源判断
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/container/container/operate/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3399 feat: 优化文本域换行符校验
  backend/app/service/firewall.go
  backend/utils/firewall/client.go
  backend/utils/firewall/client/firewalld.go
  backend/utils/firewall/client/ufw.go
  backend/utils/toolbox/fail2ban.go
  frontend/src/views/container/image/pull/index.vue
  frontend/src/views/container/image/push/index.vue
  frontend/src/views/container/image/tag/index.vue
  frontend/src/views/container/setting/mirror/index.vue
  frontend/src/views/container/setting/registry/index.vue
  frontend/src/views/setting/safe/allowips/index.vue
  frontend/src/views/toolbox/fail2ban/ips/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3402 fix: 修改 UFW 防火墙重启方式
  backend/utils/firewall/client/ufw.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3410 Update upgrade.go
  backend/app/api/v1/upgrade.go
Labels: do-not-merge/release-note-label-needed

#3407 feat: 增加 xpack 相关代码
  .gitignore
  backend/init/router/router.go
  backend/router/common.go
  backend/router/entry.go
  backend/router/entry_xpack.go
  backend/router/ro_app.go
  backend/router/ro_base.go
  backend/router/ro_container.go
  backend/router/ro_cronjob.go
  backend/router/ro_dashboard.go
  backend/router/ro_database.go
  backend/router/ro_file.go
  backend/router/ro_group.go
  backend/router/ro_host.go
  backend/router/ro_log.go
  backend/router/ro_monitor.go
  backend/router/ro_nginx.go
  backend/router/ro_process.go
  backend/router/ro_router.go
  backend/router/ro_runtime.go
  backend/router/ro_setting.go
  backend/router/ro_terminal.go
  backend/router/ro_toolbox.go
  backend/router/ro_website.go
  backend/router/ro_website_acme_account.go
  backend/router/ro_website_ca.go
  backend/router/ro_website_dns_account.go
  backend/router/ro_website_ssl.go
  frontend/.env
  frontend/.env.development
  frontend/.env.production
  frontend/src/api/index.ts
  frontend/src/routers/router.ts
  frontend/src/typings/global.d.ts
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3422 Fix CopyButton content in SSL apply page
  frontend/src/views/website/ssl/apply/index.vue
Labels: do-not-merge/release-note-label-needed

#3442 feat: 同步用户时，移除创建用户逻辑
  backend/app/api/v1/database_mysql.go
  backend/app/dto/database.go
  backend/app/service/database_mysql.go
  backend/router/ro_database.go
  backend/utils/mysql/client.go
  backend/utils/mysql/client/info.go
  backend/utils/mysql/client/local.go
  backend/utils/mysql/client/remote.go
  cmd/server/docs/docs.go
  cmd/server/docs/swagger.json
  cmd/server/docs/swagger.yaml
  frontend/src/api/interface/database.ts
  frontend/src/api/modules/database.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/database/mysql/bind/index.vue
  frontend/src/views/database/mysql/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3443 fix: 解决 SSL 关闭失败的问题
  backend/app/dto/setting.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3444 feat: 增加 xpack init 方法
  backend/router/common.go
  backend/server/init.go
  backend/server/init_xpack.go
  backend/server/server.go
  go.mod
  go.sum
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3451 fix: 解决网站文件层级过多导致的授权超时问题
  backend/app/service/website.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3452 fix: 解决日志审计网站日志在网站为空的时候报错的问题
  frontend/src/views/log/website/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3454 feat: 拆分备份账号代码
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/utils/util.ts
  frontend/src/views/setting/backup-account/cos/index.vue
  frontend/src/views/setting/backup-account/index.vue
  frontend/src/views/setting/backup-account/kodo/index.vue
  frontend/src/views/setting/backup-account/minio/index.vue
  frontend/src/views/setting/backup-account/onedrive/index.vue
  frontend/src/views/setting/backup-account/operate/index.vue
  frontend/src/views/setting/backup-account/oss/index.vue
  frontend/src/views/setting/backup-account/s3/index.vue
  frontend/src/views/setting/backup-account/sftp/index.vue
  frontend/src/views/setting/backup-account/webdav/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3459 fix: 解决 zip 压缩失败之后压缩文件还存在的问题
  backend/utils/files/zip.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3465 feat: 容器列表增加关联资源展示
  backend/app/dto/container.go
  backend/app/service/container.go
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/container/container/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3469 feat: 容器列表增加过滤应用商店容器功能
  backend/app/dto/container.go
  backend/app/service/container.go
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/container/container/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3447 feat: 数据库面板新增PostgreSQL管理,支持远程/本地数据库,支持与应用关联等 #758 #1978
  backend/app/api/v1/backup.go
  backend/app/api/v1/database.go
  backend/app/api/v1/database_mysql.go
  backend/app/api/v1/database_postgresql.go
  backend/app/api/v1/entry.go
  backend/app/dto/backup.go
  backend/app/dto/database.go
  backend/app/dto/database_postgresql.go
  backend/app/dto/response/app.go
  backend/app/model/database_postgresql.go
  backend/app/repo/app_install.go
  backend/app/repo/databse_postgresql.go
  backend/app/service/app_install.go
  backend/app/service/app_utils.go
  backend/app/service/backup.go
  backend/app/service/backup_app.go
  backend/app/service/backup_postgresql.go
  backend/app/service/database.go
  backend/app/service/database_postgresql.go
  backend/app/service/entry.go
  backend/constant/app.go
  backend/init/migration/migrate.go
  backend/init/migration/migrations/init.go
  backend/router/ro_database.go
  backend/utils/cloud_storage/client/webdav.go
  backend/utils/postgresql/client.go
  backend/utils/postgresql/client/info.go
  backend/utils/postgresql/client/remote.go
  frontend/src/api/interface/app.ts
  frontend/src/api/interface/database.ts
  frontend/src/api/modules/database.ts
  frontend/src/components/app-status/index.vue
  frontend/src/components/router-button/index.vue
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/routers/modules/database.ts
  frontend/src/views/database/index.vue
  frontend/src/views/database/postgresql/check/index.vue
  frontend/src/views/database/postgresql/conn/index.vue
  frontend/src/views/database/postgresql/create/index.vue
  frontend/src/views/database/postgresql/delete/index.vue
  frontend/src/views/database/postgresql/index.vue
  frontend/src/views/database/postgresql/password/index.vue
  frontend/src/views/database/postgresql/remote/delete/index.vue
  frontend/src/views/database/postgresql/remote/index.vue
  frontend/src/views/database/postgresql/remote/operate/index.vue
  frontend/src/views/database/postgresql/setting/index.vue
  frontend/src/views/database/postgresql/setting/status/index.vue
  go.mod
  go.sum
Labels: do-not-merge/release-note-label-needed

#3472 feat: 网站支持中文域名
  backend/app/service/website.go
  backend/app/service/website_utils.go
  backend/utils/common/common.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3474 fix: 更新 PostgreSQL 依赖
  frontend/src/views/database/postgresql/conn/index.vue
  frontend/src/views/database/postgresql/remote/index.vue
  frontend/src/views/database/postgresql/remote/operate/index.vue
  go.mod
  go.sum
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3471 feat: openresty 增加清理反代缓存的功能
  backend/app/api/v1/nginx.go
  backend/app/service/nginx.go
  backend/router/ro_nginx.go
  backend/utils/files/file_op.go
  cmd/server/docs/docs.go
  cmd/server/docs/swagger.json
  cmd/server/docs/swagger.yaml
  frontend/src/api/modules/nginx.ts
  frontend/src/components/app-status/index.vue
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3473 feat: 应用搜索支持描述字段
  backend/app/repo/common.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3479 style: 数据库链接信息适配宽度不合适的情况
  frontend/src/routers/router.ts
  frontend/src/styles/common.scss
  frontend/src/views/database/mysql/conn/index.vue
  go.mod
  go.sum
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3481 fix: 解决网站日志正在写入的情况下切割失败的问题
  backend/app/service/cronjob_helper.go
  backend/i18n/lang/en.yaml
  backend/i18n/lang/zh-Hant.yaml
  backend/i18n/lang/zh.yaml
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3483 fix: 解决网站反向代理在开启 HTTPS 后 HSTS 配置失效的问题
  backend/app/service/website.go
  backend/app/service/website_utils.go
  backend/utils/nginx/components/config.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved
