Repository 1Panel-dev/1Panel, pull requests merged in 2023-10, with the labels that each got.

#2434 feat: 容器支持自定义控制台交互方式
  backend/app/api/v1/container.go
  backend/app/dto/container.go
  backend/app/service/container.go
  backend/router/ro_container.go
  cmd/server/docs/docs.go
  cmd/server/docs/swagger.json
  cmd/server/docs/swagger.yaml
  frontend/src/api/interface/container.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/container/container/operate/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2435 fix: 解决防火墙 ip 规则批量操作失败的问题
  backend/app/service/firewall.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2437 fix: 优化 compose 删除提示信息
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/container/compose/delete/index.vue
Labels: do-not-merge/release-note-label-needed, dev

#2439 feat: 应用安装支持选择远程数据库
  backend/app/dto/response/app.go
  backend/app/service/app_install.go
  backend/app/service/app_utils.go
  backend/app/service/backup_app.go
  frontend/src/api/interface/app.ts
  frontend/src/views/app-store/detail/params/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2440 fix: 日志筛选项格式修改
  backend/app/service/logs.go
  backend/app/service/ssh.go
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/container/image/prune/index.vue
  frontend/src/views/log/operation/index.vue
  frontend/src/views/log/system/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2441 feat: 运行环境支持选择镜像源
  backend/app/service/runtime.go
  backend/app/service/runtime_utils.go
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/website/runtime/node/operate/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2442 style: 修改网站日志按钮样式
  frontend/src/views/log/website/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2444 feat: 网站增加选择 node.js 运行环境
  backend/app/service/backup_runtime.go
  backend/app/service/backup_website.go
  backend/app/service/website.go
  backend/app/service/website_utils.go
  frontend/src/views/website/website/config/index.vue
  frontend/src/views/website/website/config/resource/index.vue
  frontend/src/views/website/website/create/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2445 feat: node.js 运行环境端口禁止输入小数
  frontend/src/views/website/runtime/node/operate/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2446 style: 已安装应用按钮调整
  frontend/src/views/app-store/installed/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2451 feat: 解决创建网站切换类型显示错误的问题
  frontend/src/api/interface/app.ts
  frontend/src/views/website/website/create/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2452 fix: 解决防火墙未显示具体应用占用情况的问题
  backend/app/service/firewall.go
  backend/app/service/setting_clean.go
  backend/utils/firewall/client/info.go
  frontend/src/api/interface/host.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/host/firewall/port/index.vue
  frontend/src/views/setting/panel/clean/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2455 feat: 应用商店分类增加排序
  backend/app/dto/app.go
  backend/app/model/tag.go
  backend/app/repo/tag.go
  backend/app/service/app.go
  backend/init/migration/migrate.go
  backend/init/migration/migrations/v_1_7.go
  frontend/src/api/interface/app.ts
  frontend/src/layout/components/Sidebar/index.scss
  frontend/src/views/app-store/apps/index.vue
  frontend/src/views/app-store/installed/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2456 feat: 反向代理配置默认增加协议转发
  cmd/server/nginx_conf/proxy.conf
  cmd/server/nginx_conf/website_default.conf
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2457 feat: 应用列表顶部增加页码切换
  frontend/src/components/layout-content/index.vue
  frontend/src/views/app-store/apps/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2458 fix: 增加备份临时回滚文件清理项
  backend/app/service/setting_clean.go
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/setting/panel/clean/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2459 fix: 解决 node.js 运行环境网站第一次创建失败的问题
  backend/app/service/runtime.go
  backend/app/service/website_utils.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2460 fix: 优化容器列表端口显示
  backend/app/service/container.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2461 feat: 创建、更新 node.js 环境增加容器名称校验
  backend/app/service/runtime.go
  backend/app/service/runtime_utils.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2462 fix: 解决 node.js 网站备份恢复之后运行环境一直启动中的问题
  backend/app/service/backup_runtime.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2464 fix: 暗色模式下面板设置按钮样式调整
  frontend/src/styles/element-dark.scss
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2466 feat: 启动中的 node.js 运行环境放开编辑、停止等操作
  frontend/src/views/website/runtime/node/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2467 fix: 修改容器名称校验
  frontend/src/views/container/container/operate/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2468 fix: 解决域名暂停或者移除后无法重新创建该域名的问题
  frontend/src/views/website/website/config/basic/other/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2470 fix: 解决相同域名和端口可以重复添加的问题
  backend/app/service/website.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2474 fix: MySQL 性能参数区分版本显示
  frontend/src/views/database/mysql/setting/index.vue
  frontend/src/views/database/mysql/setting/variables/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2476 fix: 解决证书 HTTP 模式下保存了错误数据的问题
  backend/app/service/website_ssl.go
Labels: dev, lgtm, approved

#2475 feat: 修改网站日志的关闭参数
  backend/app/service/website.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2479 feat: 1Panel 重启增加同步应用商店
  backend/app/api/v1/app.go
  backend/app/dto/response/app.go
  backend/app/service/app.go
  backend/init/business/business.go
Labels: dev, lgtm, approved

#2481 fix: 解决远程数据库恢复失败的问题
  backend/utils/mysql/helper/source.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2482 feat: node.js 运行环境增加模块列表
  backend/app/api/v1/runtime.go
  backend/app/dto/request/runtime.go
  backend/app/dto/response/runtime.go
  backend/app/service/app.go
  backend/app/service/runtime.go
  backend/i18n/lang/en.yaml
  backend/i18n/lang/zh-Hant.yaml
  backend/i18n/lang/zh.yaml
  backend/router/ro_runtime.go
  cmd/server/docs/docs.go
  cmd/server/docs/swagger.json
  cmd/server/docs/swagger.yaml
  frontend/src/api/interface/runtime.ts
  frontend/src/api/modules/runtime.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/website/runtime/node/index.vue
  frontend/src/views/website/runtime/node/module/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2484 fix: 解决授权 IP 为空时无法保存的问题
  frontend/src/views/setting/safe/allowips/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2485 fix: 缓存清理样式调整
  frontend/src/views/setting/panel/clean/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2489 fix: 监控采集方式修改
  backend/app/service/monitor.go
  backend/app/service/setting.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2488 feat: node.js 运行环境增加模块管理
  backend/app/api/v1/runtime.go
  backend/app/dto/request/runtime.go
  backend/app/service/runtime.go
  backend/constant/runtime.go
  backend/router/ro_runtime.go
  backend/utils/cmd/cmd.go
  backend/utils/env/env.go
  cmd/server/docs/docs.go
  cmd/server/docs/swagger.json
  cmd/server/docs/swagger.yaml
  frontend/src/api/interface/runtime.ts
  frontend/src/api/modules/runtime.ts
  frontend/src/components/compose-log/index.vue
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/website/runtime/node/index.vue
  frontend/src/views/website/runtime/node/module/index.vue
  frontend/src/views/website/runtime/node/operate/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2490 feat: 后端增加统一参数校验方法
  backend/app/api/v1/helper/helper.go
  backend/app/api/v1/runtime.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2491 fix: 解决 UFW 防火墙添加端口备注时不生效的问题
  backend/app/service/firewall.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2492 fix: 解决强制删除 Openresty 没有同步删除 PHP 应用的问题
  backend/app/service/app.go
  backend/app/service/app_utils.go
  backend/constant/errs.go
  backend/i18n/lang/en.yaml
  backend/i18n/lang/zh-Hant.yaml
  backend/i18n/lang/zh.yaml
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2493 fix: 修改容器名校验规则描述信息
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/container/container/rename/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2497 fix: mfa 标题增加校验规则
  frontend/src/views/setting/safe/mfa/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2498 fix: 解决 node.js 运行环境模块页面打开失败的问题
  backend/app/api/v1/runtime.go
  backend/app/dto/request/runtime.go
  backend/app/service/runtime.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2500 fix: 容器升级增加忽略版本比较勾选
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/container/container/upgrade/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2501 feat: 同步所有应用增加提示信息
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/app-store/installed/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2503 style: 修改网站运行环境下拉列表样式
  frontend/src/views/website/website/create/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2504 fix: 修改默认监控网卡
  backend/init/migration/migrations/v_1_7.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2505 fix: 解决部分应用删除失败的问题
  backend/app/repo/common.go
  backend/app/service/app_install.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2506 chore: 更新 README
  README.md
Labels: do-not-merge/release-note-label-needed, dev

#2507 fix: 解决防火墙范围端口添加时备注不生效的问题
  backend/app/service/firewall.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2508 fix: 修改 UFW IP 规则优先级
  backend/app/service/firewall.go
  backend/utils/firewall/client/ufw.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2512 fix: 修改部分校验规则
  frontend/src/views/container/container/operate/index.vue
  frontend/src/views/container/container/upgrade/index.vue
  frontend/src/views/setting/safe/mfa/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2513 fix: 解决 SSH 日志统计信息勾选失效的问题
  frontend/src/views/host/ssh/log/analysis/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2514 chore: 更新 README
  README.md
Labels: do-not-merge/release-note-label-needed, dev

#2515 fix: 解决 SSH 日志批量操作失败的问题
  frontend/src/views/host/ssh/log/analysis/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2516 fix: 解决新增域名校验错误的问题
  backend/app/service/website.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2518 fix: 依赖升级
  go.mod
  go.sum
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2519 fix: 解决首页应用安装跳转错误的问题
  frontend/src/views/app-store/apps/index.vue
  frontend/src/views/home/app/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2520 fix: 解决日志审计-网站日志不显示的问题
  frontend/src/views/log/website/index.vue
  frontend/src/views/website/website/config/basic/site-folder/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2521 fix: 解决容器编辑存储卷失败导致容器丢失的问题
  backend/app/service/container.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2522 fix: 解决容器编辑失败时未更新容器 ID 的问题
  frontend/src/views/container/container/operate/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2525 fix: 解决反向代理网站在 firefox 浏览器打开失败的问题
  cmd/server/nginx_conf/ssl.conf
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2540 feat: add sonar cloud scan
  .github/workflows/build.yml
  sonar-project.properties
Labels: do-not-merge/release-note-label-needed, dev

#2542 fix: 解决证书详情页其他域名一直为空的问题
  frontend/src/views/website/ssl/detail/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2553 feat: 容器编辑提示增加判断条件
  frontend/src/views/container/container/operate/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2554 fix: 解决容器没有 entrypoint 无法打开编辑页面的问题
  frontend/src/views/container/container/operate/index.vue
Labels: do-not-merge/release-note-label-needed, dev

#2541 feat: 文件列表增加排序功能
  backend/utils/cmd/cmd.go
  backend/utils/files/file_op.go
  backend/utils/files/fileinfo.go
  frontend/package.json
  frontend/src/api/interface/file.ts
  frontend/src/components/complex-table/index.vue
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/host/file-management/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2565 fix: 解决部分情况下 zip 文件压缩解压失败的问题
  backend/utils/cmd/cmd.go
  backend/utils/files/archiver.go
  backend/utils/files/file_op.go
  backend/utils/files/tar.go
  backend/utils/files/zip.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2567 feat: SSH 登陆日志适配 Debian12
  backend/app/service/ssh.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2579 feat: 概览界面增加服务重启以及面板重启功能
  backend/app/api/v1/dashboard.go
  backend/app/service/dashboard.go
  backend/router/ro_dashboard.go
  cmd/server/docs/docs.go
  cmd/server/docs/swagger.json
  cmd/server/docs/swagger.yaml
  frontend/src/api/modules/dashboard.ts
  frontend/src/components/router-button/index.vue
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/styles/common.scss
  frontend/src/views/home/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2582 fix: 解决容器设置 host 网络失败的问题
  backend/app/service/container.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2585 feat: 备份账号创建增加上传测试
  backend/app/service/backup.go
  backend/i18n/lang/en.yaml
  backend/i18n/lang/zh-Hant.yaml
  backend/i18n/lang/zh.yaml
  frontend/src/api/modules/host.ts
  frontend/src/api/modules/setting.ts
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2587 feat: 容器列表增加状态筛选
  backend/app/dto/container.go
  backend/app/service/container.go
  cmd/server/docs/docs.go
  cmd/server/docs/swagger.json
  cmd/server/docs/swagger.yaml
  frontend/src/api/interface/container.ts
  frontend/src/components/status/index.vue
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/container/container/index.vue
  sonar-project.properties
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2591 fix: 同步数据库时，忽略 recycle_bin
  backend/utils/mysql/client/local.go
  backend/utils/mysql/client/remote.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2586 feat: 文件增加回收站功能
  backend/app/api/v1/entry.go
  backend/app/api/v1/recycle_bin.go
  backend/app/dto/request/file.go
  backend/app/dto/request/recycle_bin.go
  backend/app/dto/response/recycle_bin.go
  backend/app/service/file.go
  backend/app/service/recycle_bin.go
  backend/constant/dir.go
  backend/i18n/lang/en.yaml
  backend/i18n/lang/zh-Hant.yaml
  backend/i18n/lang/zh.yaml
  backend/router/ro_file.go
  backend/utils/files/file_op.go
  cmd/server/docs/docs.go
  cmd/server/docs/swagger.json
  cmd/server/docs/swagger.yaml
  frontend/src/api/interface/file.ts
  frontend/src/api/modules/files.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/host/file-management/change-role/index.vue
  frontend/src/views/host/file-management/delete/index.vue
  frontend/src/views/host/file-management/index.vue
  frontend/src/views/host/file-management/recycle-bin/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2605 feat: 优化 mfa 登陆方式
  frontend/src/views/login/components/login-form.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2604 fix: 系统用户名、密码增加空格校验
  frontend/src/global/form-rules.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/setting/expired.vue
  frontend/src/views/setting/panel/password/index.vue
  frontend/src/views/setting/panel/username/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2606 feat: 缓存容器界面刷新频率
  frontend/src/components/table-setting/index.vue
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/container/container/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2595 fix: 计划任务增加日志备份
  backend/app/service/cronjob_helper.go
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/cronjob/operate/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2607 feat: 解决容器编辑内存限额失败的问题
  backend/app/service/container.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2612 feat: 文件增加收藏夹功能
  backend/app/api/v1/entry.go
  backend/app/api/v1/favorite.go
  backend/app/api/v1/helper/helper.go
  backend/app/api/v1/recycle_bin.go
  backend/app/dto/request/favorite.go
  backend/app/dto/response/favorite.go
  backend/app/model/favorite.go
  backend/app/repo/favorite.go
  backend/app/service/entry.go
  backend/app/service/favorite.go
  backend/constant/errs.go
  backend/i18n/lang/en.yaml
  backend/i18n/lang/zh-Hant.yaml
  backend/i18n/lang/zh.yaml
  backend/init/migration/migrate.go
  backend/init/migration/migrations/v_1_8.go
  backend/router/ro_file.go
  backend/utils/files/fileinfo.go
  cmd/server/docs/docs.go
  cmd/server/docs/swagger.json
  cmd/server/docs/swagger.yaml
  frontend/src/api/interface/file.ts
  frontend/src/api/modules/files.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/host/file-management/favorite/index.vue
  frontend/src/views/host/file-management/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2613 fix: 解决 firewalld 防火墙规则 ipv6 下不生效的问题
  backend/utils/firewall/client/firewalld.go
  backend/utils/firewall/client/ufw.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2614 feat: OneDrive 授权码增加格式校验
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/setting/backup-account/operate/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2627 fix: 修复数据库修改端口错误
  backend/app/service/app_install.go
Labels: do-not-merge/release-note-label-needed, lgtm

#2630 fix: ssh日志识别错误
  backend/app/service/ssh.go
Labels: do-not-merge/release-note-label-needed

#2615 feat: 优化systemctl中判断service文件是否存在的函数
  backend/utils/systemctl/systemctl.go
Labels: do-not-merge/release-note-label-needed

#2629 fix: 修改 OneDrive 授权码长度限制
  frontend/src/views/setting/backup-account/operate/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2634 feat: supervisor 优化状态判断
  backend/utils/systemctl/systemctl.go
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2635 feat: 优化计划任务脚本执行错误处理
  backend/constant/errs.go
  backend/i18n/lang/en.yaml
  backend/i18n/lang/zh-Hant.yaml
  backend/i18n/lang/zh.yaml
  backend/utils/cmd/cmd.go
  backend/utils/encrypt/encrypt_test.go
  frontend/src/views/cronjob/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2637 feat: 优化计划任务脚本执行输出
  backend/i18n/lang/en.yaml
  backend/i18n/lang/zh-Hant.yaml
  backend/i18n/lang/zh.yaml
  backend/utils/cmd/cmd.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2638 fix: 解决容器创建默认 Entrypoint 失败的问题
  backend/app/service/container.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2640 fix: 计划任务报告样式调整
  frontend/src/views/cronjob/record/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2641 fix: 解决容器创建默认 Cmd 失败的问题
  backend/app/service/container.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2643 feat: 终端主机地址校验支持 ipv6
  frontend/src/views/database/mysql/remote/operate/index.vue
  frontend/src/views/host/terminal/host/operate/index.vue
  frontend/src/views/host/terminal/terminal/host-create.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2642 feat: 文件收藏夹增加快速跳转
  backend/app/service/file.go
  frontend/src/api/interface/file.ts
  frontend/src/components/compose-log/index.vue
  frontend/src/views/host/file-management/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2659 fix: 同步数据库时, 忽略recycle_bin改为__recycle_bin__
  backend/utils/mysql/client/local.go
  backend/utils/mysql/client/remote.go
Labels: do-not-merge/release-note-label-needed, lgtm

#2660 feat: 文件增加打开终端功能
  frontend/src/components/terminal/index.vue
  frontend/src/routers/modules/host.ts
  frontend/src/views/host/file-management/index.vue
  frontend/src/views/host/terminal/terminal/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2664 fix: 同步数据库时, 忽略recycle_bin和__recycle_bin__
  backend/utils/mysql/client/local.go
  backend/utils/mysql/client/remote.go
Labels: do-not-merge/release-note-label-needed

#2661 feat: 增加上传文件夹功能
  backend/app/api/v1/file.go
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/host/file-management/delete/index.vue
  frontend/src/views/host/file-management/upload/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2663 feat: 面板设置增加监听地址
  backend/app/api/v1/setting.go
  backend/app/dto/setting.go
  backend/app/service/setting.go
  backend/configs/system.go
  backend/init/hook/hook.go
  backend/init/migration/migrate.go
  backend/init/migration/migrations/v_1_8.go
  backend/router/ro_setting.go
  backend/server/server.go
  cmd/server/docs/docs.go
  cmd/server/docs/swagger.json
  cmd/server/docs/swagger.yaml
  frontend/src/api/interface/setting.ts
  frontend/src/api/modules/setting.ts
  frontend/src/global/form-rules.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/setting/safe/bind/index.vue
  frontend/src/views/setting/safe/index.vue
  go.mod
  go.sum
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2672 feat: 1Panel 日志文件取消压缩
  backend/log/writer.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2673 fix: 修改部分错误代码
  backend/utils/mysql/client/remote.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2671 feat: 命令行支持切换监听 IP
  cmd/server/cmd/listen-ip.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2675 fix: 修改计划任务脚本执行状态判断
  backend/utils/cmd/cmd.go
  frontend/src/views/cronjob/record/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2676 fix: 优化终端界面菜单按钮样式
  frontend/src/views/cronjob/index.vue
  frontend/src/views/host/terminal/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2677 feat: Node.js 运行环境增加自定义启动命令
  backend/app/service/runtime.go
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/website/runtime/node/operate/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2678 fix: 解决未设置默认字符集导致数据库导入备份失败的问题
  backend/utils/mysql/client/local.go
  frontend/src/components/upload/index.vue
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/database/mysql/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2680 fix: 解决页面加载先后导致的分页错误问题
  frontend/src/views/app-store/apps/index.vue
  frontend/src/views/app-store/installed/index.vue
  frontend/src/views/container/compose/detail/index.vue
  frontend/src/views/database/mysql/index.vue
  frontend/src/views/website/website/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2690 fix: 统一删除提示信息及样式
  backend/app/api/v1/container.go
  backend/app/dto/container.go
  backend/app/service/container.go
  backend/router/ro_container.go
  cmd/server/docs/docs.go
  cmd/server/docs/swagger.json
  cmd/server/docs/swagger.yaml
  frontend/src/api/interface/container.ts
  frontend/src/api/interface/cronjob.ts
  frontend/src/api/modules/container.ts
  frontend/src/api/modules/cronjob.ts
  frontend/src/components/del-dialog/index.vue
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/container/compose/detail/index.vue
  frontend/src/views/container/container/handle/index.vue
  frontend/src/views/container/container/index.vue
  frontend/src/views/container/container/rename/index.vue
  frontend/src/views/container/image/delete/index.vue
  frontend/src/views/container/image/index.vue
  frontend/src/views/container/network/index.vue
  frontend/src/views/container/repo/index.vue
  frontend/src/views/container/template/index.vue
  frontend/src/views/container/volume/index.vue
  frontend/src/views/cronjob/index.vue
  frontend/src/views/host/firewall/ip/index.vue
  frontend/src/views/host/firewall/port/index.vue
  frontend/src/views/host/terminal/command/index.vue
  frontend/src/views/host/terminal/host/index.vue
  frontend/src/views/setting/snapshot/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2691 feat: Node.js 运行环境增加多端口
  backend/app/dto/request/runtime.go
  backend/app/dto/response/runtime.go
  backend/app/service/runtime.go
  backend/app/service/runtime_utils.go
  frontend/src/api/interface/runtime.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/website/runtime/node/operate/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2699 fix: 解决创建网站报端口被占用的问题
  backend/app/service/website.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2700 fix: 面板设置样式调整
  frontend/src/lang/modules/en.ts
  frontend/src/views/setting/panel/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2701 fix: 解决可以创建同名网站的问题
  backend/app/service/website.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2703 feat: 统一修改部分接口参数校验
  backend/app/api/v1/app.go
  backend/app/api/v1/app_install.go
  backend/app/api/v1/file.go
  backend/app/api/v1/host_tool.go
  backend/app/api/v1/nginx.go
  backend/app/api/v1/process.go
  backend/app/api/v1/website.go
  backend/app/api/v1/website_acme_account.go
  backend/app/api/v1/website_dns_account.go
  backend/app/api/v1/website_ssl.go
  backend/app/service/runtime_utils.go
Labels: dev, lgtm, approved

#2705 Update README.md
  README.md
Labels: do-not-merge/release-note-label-needed, dev

#2704 fix: 简化接口校验代码
  backend/app/api/v1/auth.go
  backend/app/api/v1/backup.go
  backend/app/api/v1/command.go
  backend/app/api/v1/compose_template.go
  backend/app/api/v1/container.go
  backend/app/api/v1/cronjob.go
  backend/app/api/v1/database.go
  backend/app/api/v1/database_mysql.go
  backend/app/api/v1/database_redis.go
  backend/app/api/v1/docker.go
  backend/app/api/v1/firewall.go
  backend/app/api/v1/group.go
  backend/app/api/v1/host.go
  backend/app/api/v1/image.go
  backend/app/api/v1/image_repo.go
  backend/app/api/v1/logs.go
  backend/app/api/v1/monitor.go
  backend/app/api/v1/setting.go
  backend/app/api/v1/snapshot.go
  backend/app/api/v1/ssh.go
  backend/app/api/v1/upgrade.go
  backend/app/dto/auth.go
  backend/app/dto/container.go
  backend/app/dto/cronjob.go
  backend/app/dto/database.go
  backend/app/dto/setting.go
  cmd/server/docs/docs.go
  cmd/server/docs/swagger.json
  cmd/server/docs/swagger.yaml
  frontend/src/views/container/container/operate/index.vue
  frontend/src/views/container/container/rename/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2706 fix: 压缩过程忽略 .sock 套接字
  backend/app/service/cronjob_helper.go
  backend/app/service/snapshot_create.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2707 fix: 解决网站域名可以重复添加的问题
  backend/app/api/v1/app_install.go
  backend/app/api/v1/website.go
  backend/app/api/v1/website_domain.go
  backend/app/dto/request/app.go
  backend/app/dto/request/website.go
  backend/app/service/website.go
  backend/constant/errs.go
  backend/i18n/lang/en.yaml
  backend/i18n/lang/zh-Hant.yaml
  backend/i18n/lang/zh.yaml
  frontend/src/api/interface/app.ts
  frontend/src/views/website/website/create/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2708 fix: 解决网站日志审计切换网站日志显示错误的问题
  backend/app/api/v1/file.go
  backend/app/dto/request/file.go
  backend/app/service/file.go
  frontend/src/views/log/website/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2710 fix: 解决终端连接无法正常打开的问题
  backend/app/dto/backup.go
  backend/app/dto/common_req.go
  frontend/package-lock.json
  frontend/src/components/terminal/index.vue
Labels: dev, lgtm, approved

#2711 fix: 统一删除提示框
  backend/app/service/setting_clean.go
  frontend/src/components/backup/index.vue
  frontend/src/components/upload/index.vue
  frontend/src/views/database/redis/setting/persistence/index.vue
  frontend/src/views/setting/backup-account/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2724 fix: 统一网站等删除样式
  frontend/src/views/host/process/process/index.vue
  frontend/src/views/host/tool/supervisor/file/index.vue
  frontend/src/views/website/runtime/php/index.vue
  frontend/src/views/website/ssl/acme-account/index.vue
  frontend/src/views/website/ssl/dns-account/index.vue
  frontend/src/views/website/ssl/index.vue
  frontend/src/views/website/website/config/basic/auth-basic/index.vue
  frontend/src/views/website/website/config/basic/domain/index.vue
  frontend/src/views/website/website/config/basic/proxy/index.vue
  frontend/src/views/website/website/config/basic/redirect/index.vue
  frontend/src/views/website/website/config/log/log-fiile/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2731 feat: 修改部分接口报错和页面显示问题
  backend/utils/files/fileinfo.go
  frontend/src/components/del-dialog/index.vue
  frontend/src/components/index.ts
  frontend/src/views/host/process/process/index.vue
  frontend/src/views/host/tool/supervisor/file/index.vue
  frontend/src/views/website/runtime/php/index.vue
  frontend/src/views/website/ssl/dns-account/index.vue
  frontend/src/views/website/website/config/basic/domain/index.vue
  frontend/src/views/website/website/config/basic/proxy/index.vue
  frontend/src/views/website/website/config/basic/redirect/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2732 fix: 快速命令增加分组
  backend/app/api/v1/command.go
  backend/app/dto/command.go
  backend/app/model/command.go
  backend/app/service/command.go
  backend/app/service/group.go
  backend/init/migration/migrate.go
  backend/init/migration/migrations/v_1_8.go
  backend/router/ro_host.go
  cmd/server/docs/docs.go
  cmd/server/docs/swagger.json
  cmd/server/docs/swagger.yaml
  frontend/src/api/interface/command.ts
  frontend/src/api/modules/command.ts
  frontend/src/api/modules/host.ts
  frontend/src/components/group/change.vue
  frontend/src/views/host/terminal/command/index.vue
  frontend/src/views/host/terminal/host/index.vue
  frontend/src/views/host/terminal/terminal/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2733 fix: 解决自动升级导致的代码问题
  backend/app/service/container_volume.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2734 chore: Update README.md
  docs/README_EN.md
  docs/README_JP.md
  docs/README_TW.md
Labels: do-not-merge/release-note-label-needed, dev

#2736 fix: 升级 Go 到 1.20.10
  backend/app/service/container_volume.go
  go.mod
  go.sum
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2735 feat: 证书页面增加上传证书功能
  backend/app/api/v1/website_ssl.go
  backend/app/dto/request/website_ssl.go
  backend/app/service/website_ssl.go
  backend/router/ro_website_ssl.go
  cmd/server/docs/docs.go
  cmd/server/docs/swagger.json
  cmd/server/docs/swagger.yaml
  frontend/src/api/interface/website.ts
  frontend/src/api/modules/website.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/website/ssl/detail/index.vue
  frontend/src/views/website/ssl/index.vue
  frontend/src/views/website/ssl/upload/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2737 fix: 解决 PHP 网站切换版本导致 serviceName 变更的问题
  backend/app/service/website.go
  backend/app/service/website_utils.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2739 fix: 解决容器端口解析失败的问题
  backend/app/service/container.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2740 fix: 解决概览页样式不统一的问题
  frontend/src/views/home/status/index.vue
Labels: dev, lgtm, approved

#2741 style: 修改文件列表部分样式
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/host/file-management/index.vue
  frontend/src/views/host/file-management/recycle-bin/delete/index.vue
  frontend/src/views/host/file-management/recycle-bin/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2742 fix: 优化证书申请超时问题
  frontend/src/api/modules/website.ts
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2745 fix: 解决启用 https 时无法访问的问题
  backend/app/api/v1/website_ssl.go
  backend/server/server.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved
