Repository 1Panel-dev/1Panel, pull requests merged in 2023-06, with the labels that each got.

#1210 fix: 优化未启用安全入口跳转逻辑
  backend/app/api/v1/auth.go
  backend/app/service/auth.go
  frontend/src/api/modules/auth.ts
  frontend/src/layout/index.vue
  frontend/src/routers/index.ts
  frontend/src/views/login/entrance/index.vue
  frontend/src/views/login/index.vue
  frontend/src/views/setting/safe/index.vue
  frontend/src/views/setting/safe/port/index.vue
  frontend/src/views/setting/safe/ssl/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1213 fix: 拦截中间件数据改为实时获取
  backend/app/service/setting.go
  backend/configs/system.go
  backend/init/hook/hook.go
  backend/middleware/bind_domain.go
  backend/middleware/ip_limit.go
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/login/entrance/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1214 fix: 解决解压 GBK 格式的 zip 文件中文乱码的问题
  backend/utils/files/file_op.go
  cmd/server/app/logo.png
  go.mod
  go.sum
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1216 feat: 减少 badger 的内存占用
  backend/init/cache/cache.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1217 feat: 删除 AppStoreVersion 参数
  backend/app/service/app_install.go
  backend/i18n/lang/en.yaml
  backend/i18n/lang/zh.yaml
  backend/init/business/business.go
  cmd/server/cmd/version.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1218 fix: 解决编辑已停止计划任务导致任务执行的问题
  backend/app/service/cornjob.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1219 feat: 计划任务报告页增加计划任务名称显示
  frontend/src/views/cronjob/record/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1220 fix: 解决应用升级失败的问题
  backend/app/service/app.go
  backend/app/service/app_utils.go
  backend/i18n/lang/en.yaml
  backend/i18n/lang/zh.yaml
  backend/utils/files/file_op.go
  backend/utils/http/get.go
  frontend/src/lang/modules/zh.ts
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1221 fix: ssh 登录日志归属地获取方式修改
  .gitignore
  backend/app/dto/ssh.go
  backend/app/service/ssh.go
  cmd/server/docs/docs.go
  cmd/server/docs/swagger.json
  cmd/server/docs/swagger.yaml
  frontend/src/api/interface/host.ts
  frontend/src/views/host/ssh/log/log.vue
  frontend/src/views/host/ssh/ssh/address/index.vue
  frontend/src/views/host/ssh/ssh/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1223 fix: ssh 登录日志时区修改
  backend/app/service/ssh.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1225 fix: 解决容器配置失败的问题
  .gitignore
  frontend/src/api/modules/container.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/container/setting/index.vue
  frontend/src/views/container/setting/log/index.vue
  frontend/src/views/container/volume/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1226 fix: 解决本地应用升级失败的问题
  backend/app/service/app.go
  backend/app/service/app_utils.go
  frontend/src/components/status/index.vue
  frontend/src/views/app-store/installed/index.vue
Labels: dev, lgtm, approved

#1227 fix: 解决PHP上传限制清空之后可以上传的问题
  frontend/src/views/website/website/config/php/upload/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1229 fix: 优化监控页空数据显示
  frontend/src/views/host/monitor/monitor/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1230 fix: 解决打开防盗链报错的问题
  backend/app/service/website.go
Labels: dev, lgtm, approved

#1232 fix: 概览页磁盘大小自适应
  frontend/src/views/home/status/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1231 feat: 增加应用商店定时同步
  backend/cron/cron.go
  backend/cron/job/app.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1233 feat: 限制已废弃应用升级和备份
  backend/app/service/app.go
  frontend/src/views/app-store/apps/index.vue
  frontend/src/views/app-store/installed/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1234 feat: 增加一些提示信息
  Makefile
  backend/app/service/app.go
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/app-store/installed/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1237 fix: 解决应用内存限制回显失败的问题
  backend/app/service/app_utils.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1238 feat: 安装应用自动填写名称
  frontend/src/views/app-store/apps/index.vue
  frontend/src/views/app-store/detail/install/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1239 feat: 容器日志切割增加回显
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/container/setting/index.vue
  frontend/src/views/container/setting/log/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1241 fix: 解决同步应用之后旧版本被删除的问题
  backend/app/service/app.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1242 feat: 防盗链响应增加状态码判断
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/website/website/config/basic/anti-Leech/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1248 fix: 解决本地应用升级失败的问题
  Makefile
  backend/app/service/app.go
  backend/app/service/app_utils.go
  frontend/src/views/app-store/installed/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1249 fix: 面板设置提示信息修改
  backend/app/service/setting.go
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/setting/safe/allowips/index.vue
  frontend/src/views/setting/safe/domain/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1251 feat: 修改应用容器名称增加校验
  backend/app/repo/app_install.go
  backend/app/service/app.go
  backend/app/service/app_install.go
  backend/app/service/app_utils.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1252 fix: 恢复密码过期跳转
  frontend/src/api/index.ts
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1256 perf: 浏览器失去焦点停止查询、节省开销
  frontend/src/views/home/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm

#1255 fix: 计划任务排除规则改为换行切割
  backend/app/service/cronjob_helper.go
  backend/init/migration/migrations/init.go
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/cronjob/operate/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1260 fix: 日志拦截解压方式判断修改
  backend/middleware/operation.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1262 fix: 容器详情抽屉高度自适应
  frontend/src/components/codemirror-dialog/index.vue
  frontend/src/views/container/compose/detail/index.vue
  frontend/src/views/container/container/index.vue
  frontend/src/views/container/network/index.vue
  frontend/src/views/container/volume/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1264 fix: 修改 ssh 登录日志排序规则
  backend/app/service/ssh.go
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/host/ssh/log/log.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1266 fix: 操作日志内容修改
  backend/app/api/v1/app_install.go
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/log/operation/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1267 fix: 应用默认配置路径修改
  backend/app/service/app_install.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1268 fix: 解决导入 cloudflare 证书域名显示错误的问题
  backend/app/service/website.go
  cmd/server/nginx_conf/ssl.conf
  frontend/src/views/website/ssl/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1269 fix: 工作目录切换逻辑修改
  backend/app/service/cronjob_helper.go
  backend/utils/cmd/cmd.go
  frontend/src/views/cronjob/record/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1271 fix: 备份适配 redis 版本
  backend/app/service/backup_redis.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1273 feat: 版本更新检查错误信息优化
  backend/app/service/upgrade.go
  backend/constant/errs.go
  backend/i18n/lang/en.yaml
  backend/i18n/lang/zh.yaml
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1274 feat: 修改一些提示信息
  backend/app/service/app_install.go
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/host/firewall/port/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1276 feat: 创建 DNS 账号禁止输入空格
  frontend/src/views/website/ssl/create/index.vue
  frontend/src/views/website/ssl/dns-account/create/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1277 fix: 计划任务执行周期校验修改
  frontend/src/views/cronjob/operate/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1278 fix: 解决网站导入自签证书报错的问题
  backend/app/service/app.go
  backend/app/service/website.go
  frontend/src/views/website/runtime/create/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1279 style: 修改 logo 路径
  backend/init/router/router.go
  frontend/index.html
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1281 feat: 删除域名的时候同步删除 ipv6 的端口监听
  backend/app/service/website_utils.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1282 feat: 计划任务创建增加第三方备份账号跳转
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/cronjob/operate/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1283 fix: 解决 MYSQL 不显示升级的问题
  backend/app/service/app_install.go
  backend/app/service/app_utils.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1285 fix: 修复启动 panic 问题
  backend/app/service/app_install.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1287 fix: 解决计划任务报告未显示执行周期的问题
  frontend/src/views/cronjob/record/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1288 feat: 修改前端打包方式
  Makefile
  frontend/package.json
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1289 feat: 删除无用的文件
  frontend/package-lock.json
  frontend/src/assets/apps/halo.png
  frontend/src/assets/apps/redis.png
  frontend/src/assets/apps/wordpress.png
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1294 fix: 解决 sftp 上传大文件失败的问题
  backend/utils/cloud_storage/client/sftp.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1297 feat: 应用详情适配夜间模式
  backend/app/service/app_utils.go
  frontend/src/components/system-upgrade/index.vue
  frontend/src/views/app-store/detail/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1298 fix: 解决 mysql 日志清空错误的问题
  frontend/src/views/database/mysql/setting/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1301 fix: 解决系统启动时同步应用导致的报错
  backend/init/business/business.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1304 feat: 上传文件到 OSS
  .github/workflows/release-drafter.yml
Labels: do-not-merge/release-note-label-needed, lgtm

#1306 fix: 解决应用备份或升级失败的问题
  backend/app/service/backup_app.go
  backend/app/service/cronjob_helper.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1307 fix: 优化 ssh 登录日志查询速度
  backend/app/service/ssh.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1308 style: 修改安装应用提示语句
  frontend/src/lang/modules/zh.ts
  frontend/src/views/app-store/detail/install/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1313 fix: 终端全屏问题
  frontend/src/layout/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1314 fix: 解决终端意外退出全屏导致菜单无法显示的问题
  frontend/src/views/host/terminal/terminal/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1316 fix: 解决终端全屏及缩放的菜单显示问题
  frontend/src/views/host/terminal/terminal/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1319 feat: 计划任务和容器日志的前端改进
  frontend/src/components/drawer-header/index.vue
  frontend/src/views/container/container/log/index.vue
  frontend/src/views/cronjob/index.vue
Labels: do-not-merge/release-note-label-needed

#1347 feat: 应用导入备份恢复优化
  backend/app/repo/app_install_resource.go
  backend/app/service/backup_app.go
  backend/app/service/database_mysql.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1349 fix: 解决计划任务执行周期错误的问题
  backend/app/dto/cronjob.go
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/cronjob/operate/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1350 fix: 修正 actions 脚本
  .github/workflows/release-drafter.yml
Labels: do-not-merge/release-note-label-needed

#1354 fix: 修复英文语言包缺少"operateConfirm"的问题
  frontend/src/lang/modules/en.ts
Labels: do-not-merge/release-note-label-needed, lgtm

#1356 fix: 修复无法读取ssh成功日志
  backend/app/service/ssh.go
Labels: do-not-merge/release-note-label-needed, lgtm

#1357 feat: 容器存储卷快捷进入挂载点文件目录 #1325
  frontend/src/views/container/volume/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm

#1358 fix: 修复创建数据库时误删数据库用户的bug
  backend/app/service/database_mysql.go
Labels: do-not-merge/release-note-label-needed, lgtm

#1362 feat: 应用导入恢复增加提示信息
  frontend/src/components/upload/index.vue
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/zh.ts
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1365 fix: 应用恢复去掉版本限制
  backend/app/service/backup_app.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1366 fix: 容器存储卷目录按钮样式修改
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/container/volume/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1367 fix: 修改应用导入恢复时数据库连接信息
  backend/app/service/backup_app.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1370 feat: 优化容器日志加载方式，增加显示条数过滤
  backend/app/api/v1/container.go
  backend/app/dto/container.go
  backend/app/service/container.go
  backend/router/ro_container.go
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/container/container/log/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1372 fix: 容器日志接口文档修改
  backend/app/api/v1/container.go
  backend/app/service/container.go
  cmd/server/docs/docs.go
  cmd/server/docs/swagger.json
  cmd/server/docs/swagger.yaml
  frontend/src/api/interface/container.ts
  frontend/src/api/modules/container.ts
  frontend/src/components/container-log/index.vue
  frontend/src/views/container/container/log/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1382 feat: 不使用 cgo
  .github/workflows/build-test.yml
  .github/workflows/release-drafter.yml
  .gitignore
  .goreleaser.yaml
  Dockerfile
  backend/init/db/db.go
  cmd/server/cmd/root.go
  go.mod
  go.sum
Labels: do-not-merge/release-note-label-needed, lgtm, approved

#1385 fix: 解决容器、终端界面 ios 适配的问题
  frontend/src/views/container/container/log/index.vue
  frontend/src/views/host/terminal/terminal/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1386 fix: 构建移除对 cgo 的依赖
  Makefile
  go.mod
  go.sum
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1383 feat: 容器创建编辑增加 cpu 、内存最大限制
  backend/app/api/v1/container.go
  backend/app/dto/container.go
  backend/app/service/container.go
  backend/router/ro_container.go
  cmd/server/docs/docs.go
  cmd/server/docs/swagger.json
  cmd/server/docs/swagger.yaml
  frontend/src/api/interface/container.ts
  frontend/src/api/modules/container.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/container/compose/detail/index.vue
  frontend/src/views/container/container/index.vue
  frontend/src/views/container/container/monitor/index.vue
  frontend/src/views/container/container/operate/index.vue
  frontend/src/views/container/container/rename/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1352 feat: ssh登录日志增加一键屏蔽ip #1309
  frontend/src/views/host/ssh/log/log.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved

#1393 feat: 支持容器镜像升级操作
  backend/app/api/v1/container.go
  backend/app/dto/container.go
  backend/app/dto/image.go
  backend/app/service/container.go
  backend/app/service/snapshot.go
  backend/router/ro_container.go
  cmd/server/docs/docs.go
  cmd/server/docs/swagger.json
  cmd/server/docs/swagger.yaml
  frontend/src/api/modules/container.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/container/container/index.vue
  frontend/src/views/container/container/operate/index.vue
  frontend/src/views/container/container/upgrade/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1394 fix: 修复ssh日志为空时不渲染的问题
  frontend/src/views/host/ssh/log/log.vue
Labels: do-not-merge/release-note-label-needed

#1421 feat: 备份账号增加 Onedrive
  backend/app/dto/backup.go
  backend/app/model/backup.go
  backend/app/service/backup.go
  backend/app/service/cornjob.go
  backend/app/service/cronjob_helper.go
  backend/constant/backup.go
  backend/init/migration/migrate.go
  backend/init/migration/migrations/init.go
  backend/utils/cloud_storage/client/onedrive.go
  backend/utils/cloud_storage/cloud_storage_client.go
  frontend/src/api/interface/backup.ts
  frontend/src/assets/iconfont/iconfont.css
  frontend/src/assets/iconfont/iconfont.js
  frontend/src/assets/iconfont/iconfont.json
  frontend/src/assets/iconfont/iconfont.svg
  frontend/src/assets/iconfont/iconfont.ttf
  frontend/src/assets/iconfont/iconfont.woff
  frontend/src/assets/iconfont/iconfont.woff2
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/setting/backup-account/index.vue
  frontend/src/views/setting/backup-account/operate/index.vue
  go.mod
  go.sum
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1423 fix: 优化监控页图表Y轴数字大小和宽度，防止数字过长溢出 #1422
  frontend/src/views/host/monitor/monitor/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved

#1435 fix: ssh 登录日志排序优化
  backend/app/service/ssh.go
  frontend/src/views/host/ssh/log/log.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1437 fix: 解决容器镜像加速或仓库空行导致 Docker 无法正常启用的问题
  backend/app/service/docker.go
  frontend/src/components/upload/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1438 fix: 修改数据库无法正常访问情况下系统提示信息
  backend/middleware/bind_domain.go
  backend/middleware/ip_limit.go
  backend/middleware/password_expired.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1440 feat: 概览、监控等界面增加单位区分显示
  frontend/src/components/v-charts/components/Line.vue
  frontend/src/utils/util.ts
  frontend/src/views/host/monitor/monitor/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1441 feat: 两步验证增加自定义刷新时间
  backend/app/api/v1/setting.go
  backend/app/dto/auth.go
  backend/app/dto/setting.go
  backend/app/service/auth.go
  backend/init/migration/migrate.go
  backend/init/migration/migrations/init.go
  backend/router/ro_setting.go
  backend/utils/mfa/mfa.go
  frontend/src/api/interface/setting.ts
  frontend/src/api/modules/setting.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/setting/safe/index.vue
  frontend/src/views/setting/safe/mfa/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1444 fix: 解决计划任务备份根目录下文件夹失败的问题
  backend/app/service/cronjob_helper.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1446 fix: 解决 Docker 版本过低导致应用无法操作的问题
  backend/utils/compose/compose.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1447 feat: 应用商店增加分页
  frontend/src/views/app-store/apps/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1456 fix: 增加前端注入校验规则
  backend/app/api/v1/terminal.go
  backend/app/service/image_repo.go
  backend/constant/errs.go
  backend/i18n/lang/en.yaml
  backend/i18n/lang/zh.yaml
  backend/utils/cmd/cmd.go
  backend/utils/terminal/local_cmd.go
  frontend/src/global/form-rules.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/container/repo/operator/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1458 fix: 网站日志切割定时任务执行失败时打印失败原因，方便排查问题
  backend/app/service/cronjob_helper.go
Labels: do-not-merge/release-note-label-needed

#1411 新增tailwindcss做响应式
  frontend/package-lock.json
  frontend/package.json
  frontend/postcss.config.js
  frontend/src/main.ts
  frontend/src/styles/style.css
  frontend/tailwind.config.js
Labels: do-not-merge/release-note-label-needed

#1450 feat: 数据库兼容 mysql 5.6.51 版本
  backend/app/service/database_mysql.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1452 fix: 解决终端点击本地服务器未打开新连接的问题
  frontend/src/views/host/terminal/terminal/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1453 fix: 统一抽屉警告或提示信息样式
  frontend/src/views/app-store/detail/install/index.vue
  frontend/src/views/app-store/installed/detail/index.vue
  frontend/src/views/app-store/installed/index.vue
  frontend/src/views/container/container/upgrade/index.vue
  frontend/src/views/database/mysql/check/index.vue
  frontend/src/views/host/file-management/chown/index.vue
  frontend/src/views/host/ssh/log/log.vue
  frontend/src/views/setting/panel/timezone/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1454 fix: 面板操作日志显示优化
  backend/middleware/operation.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1464 feat: 备份账号 OSS 、COS 支持存储类型选择
  backend/app/service/cornjob.go
  backend/utils/cloud_storage/client/cos.go
  backend/utils/cloud_storage/client/oss.go
  backend/utils/cloud_storage/client/s3.go
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/setting/backup-account/index.vue
  frontend/src/views/setting/backup-account/operate/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1466 feat: 监控增加全局过滤
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/host/monitor/monitor/index.vue
  frontend/src/views/host/monitor/setting/days/index.vue
  frontend/src/views/host/monitor/setting/index.vue
  frontend/src/views/log/operation/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1474 feat: 计划任务脚本执行增加容器中选项
  backend/app/api/v1/container.go
  backend/app/dto/cronjob.go
  backend/app/model/cronjob.go
  backend/app/service/container.go
  backend/app/service/cornjob.go
  backend/app/service/cronjob_helper.go
  backend/init/migration/migrations/init.go
  backend/router/ro_container.go
  frontend/src/api/interface/cronjob.ts
  frontend/src/api/modules/container.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/cronjob/operate/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1476 feat: 增加进程管理
  backend/app/api/v1/entry.go
  backend/app/api/v1/file.go
  backend/app/api/v1/process.go
  backend/app/dto/request/process.go
  backend/app/service/process.go
  backend/init/router/router.go
  backend/router/entry.go
  backend/router/ro_process.go
  backend/utils/ps/ps_test.go
  backend/utils/websocket/client.go
  backend/utils/websocket/client_manager.go
  backend/utils/websocket/process_data.go
  cmd/server/docs/docs.go
  cmd/server/docs/swagger.json
  cmd/server/docs/swagger.yaml
  frontend/src/api/interface/process.ts
  frontend/src/api/modules/process.ts
  frontend/src/components/complex-table/index.vue
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/routers/modules/host.ts
  frontend/src/views/host/process/index.vue
  frontend/src/views/host/process/process/detail/index.vue
  frontend/src/views/host/process/process/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1478 fix: 优化同步快照名称重复错误显示
  backend/app/service/snapshot.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1479 feat: 增加系统 IP 设置，实现容器端口跳转功能
  backend/app/dto/setting.go
  backend/init/migration/migrations/init.go
  frontend/src/api/interface/setting.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/container/container/index.vue
  frontend/src/views/container/container/operate/index.vue
  frontend/src/views/database/mysql/index.vue
  frontend/src/views/database/redis/index.vue
  frontend/src/views/host/file-management/upload/index.vue
  frontend/src/views/setting/panel/index.vue
  frontend/src/views/setting/panel/systemip/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1477 fix: 解决快照压缩数据库文件失败的问题
  backend/app/service/snapshot.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1486 feat: 创建运行环境增加拉取最新版本
  backend/app/service/app.go
  backend/app/service/runtime.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1488 feat: 进程列表增加 loading
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/complex-table/index.vue
  frontend/src/views/host/process/process/detail/index.vue
  frontend/src/views/host/process/process/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1490 feat: 容器、数据库、网站、计划任务增加名称排序
  backend/app/dto/common_req.go
  backend/app/dto/container.go
  backend/app/dto/request/website.go
  backend/app/repo/common.go
  backend/app/repo/cronjob.go
  backend/app/service/container.go
  backend/app/service/cornjob.go
  backend/app/service/database_mysql.go
  backend/app/service/website.go
  backend/constant/status.go
  frontend/src/api/interface/container.ts
  frontend/src/api/interface/index.ts
  frontend/src/api/interface/website.ts
  frontend/src/views/container/container/index.vue
  frontend/src/views/cronjob/index.vue
  frontend/src/views/database/mysql/index.vue
  frontend/src/views/website/website/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1489 fix: 解决防盗链保存两次导致访问网站自动下载文件的问题
  backend/utils/nginx/components/server.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1491 feat: 网站启用 https 增加 http2 配置
  backend/app/service/website_utils.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1484 i18n添加
  backend/i18n/lang/zh-tw.yaml
Labels: do-not-merge/release-note-label-needed

#1498 feat: 增加 SSH 会话管理
  backend/utils/ps/ps_test.go
  backend/utils/websocket/process_data.go
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/routers/modules/host.ts
  frontend/src/views/host/process/process/index.vue
  frontend/src/views/host/ssh/index.vue
  frontend/src/views/host/ssh/session/index.vue
  frontend/src/views/host/ssh/ssh/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1499 fix: 解决修改上传限制导致 PHP 配置文件错误的问题
  backend/app/api/v1/website.go
  backend/app/service/website.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1500 feat: PHP 运行环境增加扩展列表提示
  backend/app/service/runtime_utils.go
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/styles/common.scss
  frontend/src/views/app-store/detail/install/index.vue
  frontend/src/views/app-store/installed/detail/index.vue
  frontend/src/views/container/container/upgrade/index.vue
  frontend/src/views/container/setting/log/index.vue
  frontend/src/views/host/file-management/chown/index.vue
  frontend/src/views/host/terminal/terminal/host-create.vue
  frontend/src/views/setting/panel/timezone/index.vue
  frontend/src/views/setting/safe/mfa/index.vue
  frontend/src/views/website/runtime/create/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved
