Repository 1Panel-dev/1Panel, pull requests merged in 2023-11, with the labels that each got.

#2750 fix: 解决部分机器监听 IPv4 失败的问题
  backend/server/server.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2752 fix: 解决部分情况下文件移动失败的问题
  backend/app/service/file.go
  backend/utils/files/file_op.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2751 fix: 登陆增加参数校验
  backend/app/dto/auth.go
  frontend/src/views/login/components/login-form.vue
Labels: do-not-merge/release-note-label-needed, dev

#2756 fix: 处理代码警告
  backend/app/service/image.go
  backend/utils/common/common.go
  backend/utils/ps/ps_test.go
  backend/utils/ssl/acme_test.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2758 style: 修改文件列表部分样式
  frontend/src/styles/common.scss
  frontend/src/views/host/file-management/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2759 fix: 解决依赖升级导致无法启动的问题
  go.mod
  go.sum
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2760 fix: 修改 SSH 端口时自动放开防火墙
  backend/app/api/v1/ssh.go
  backend/app/dto/ssh.go
  backend/app/service/ssh.go
  cmd/server/docs/docs.go
  cmd/server/docs/swagger.json
  cmd/server/docs/swagger.yaml
  frontend/src/api/interface/host.ts
  frontend/src/api/modules/host.ts
  frontend/src/views/host/ssh/ssh/address/index.vue
  frontend/src/views/host/ssh/ssh/index.vue
  frontend/src/views/host/ssh/ssh/port/index.vue
  frontend/src/views/host/ssh/ssh/root/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2763 feat: 文件复制、粘贴操作支持修改名称
  backend/app/api/v1/file.go
  backend/app/dto/request/file.go
  backend/app/dto/response/file.go
  backend/app/service/file.go
  backend/utils/files/file_op.go
  cmd/server/docs/docs.go
  cmd/server/docs/swagger.json
  cmd/server/docs/swagger.yaml
  frontend/src/components/upload/index.vue
  frontend/src/styles/common.scss
  frontend/src/utils/util.ts
  frontend/src/views/host/file-management/delete/index.vue
  frontend/src/views/host/file-management/index.vue
  frontend/src/views/host/file-management/move/index.vue
  frontend/src/views/host/file-management/recycle-bin/delete/index.vue
  frontend/src/views/host/file-management/recycle-bin/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2764 feat: PHP 运行环境增加日志
  backend/app/api/v1/file.go
  backend/app/dto/request/file.go
  backend/app/dto/response/file.go
  backend/router/ro_file.go
  cmd/server/docs/docs.go
  cmd/server/docs/swagger.json
  cmd/server/docs/swagger.yaml
  frontend/src/api/interface/file.ts
  frontend/src/api/modules/files.ts
  frontend/src/views/website/runtime/php/index.vue
  frontend/src/views/website/runtime/php/log/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2765 fix: 调整面板设置样式
  backend/server/server.go
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/cronjob/record/index.vue
  frontend/src/views/setting/safe/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2772 feat: 腾讯 COS 支持大文件分片上传
  backend/utils/cloud_storage/client/cos.go
  backend/utils/ssl/acme_test.go
  frontend/src/views/cronjob/record/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2773 feat: 处理 1Panel 重启导致运行环境状态异常的问题
  backend/app/service/runtime.go
  backend/constant/common.go
  backend/init/business/business.go
  backend/utils/ssl/acme_test.go
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/website/runtime/php/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2775 feat: 服务启动时自动同步系统时间
  backend/cron/cron.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2779 fix: 解决主机标题显示不一致的问题
  backend/app/service/dashboard.go
  frontend/src/views/host/terminal/host/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2774 feat: 域名支持批量添加
  backend/app/dto/request/website.go
  backend/app/service/website.go
  backend/app/service/website_utils.go
  backend/i18n/lang/en.yaml
  backend/i18n/lang/zh-Hant.yaml
  backend/i18n/lang/zh.yaml
  backend/utils/common/common.go
  frontend/src/api/interface/website.ts
  frontend/src/views/website/website/config/basic/domain/create/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2778 feat: 新增批量修改文件权限功能
  backend/app/api/v1/file.go
  backend/app/dto/request/file.go
  backend/app/service/file.go
  backend/router/ro_file.go
  backend/utils/files/file_op.go
  frontend/src/api/interface/file.ts
  frontend/src/api/modules/files.ts
  frontend/src/components/file-role/index.vue
  frontend/src/views/host/file-management/batch-role/index.vue
  frontend/src/views/host/file-management/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2780 fix: 修复黑色主题部分样式
  frontend/src/views/host/file-management/index.vue
Labels: dev, lgtm, approved

#2789 fix: 解决 firewalld 防火墙规则 ipv6 下不生效的问题
  backend/utils/firewall/client/firewalld.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2786 fix: 解决计划任务备份日志报错的问题
  backend/app/service/cronjob_helper.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2790 fix: 解决文件名和图标堆叠显示问题
  frontend/src/views/host/file-management/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2791 feat: 优化防火墙错误返回
  backend/app/service/firewall.go
  backend/utils/firewall/client/firewalld.go
  backend/utils/firewall/client/ufw.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2792 feat: host 模式应用增加提示
  backend/app/dto/request/app.go
  backend/app/dto/response/app.go
  backend/app/service/app.go
  backend/app/service/app_install.go
  backend/app/service/app_utils.go
  frontend/src/api/interface/app.ts
  frontend/src/global/business.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/app-store/detail/install/index.vue
  frontend/src/views/app-store/installed/detail/index.vue
  frontend/src/views/website/website/create/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2795 feat: 优化应用商店同步
  backend/app/api/v1/app.go
  backend/app/dto/response/app.go
  backend/app/dto/setting.go
  backend/app/service/app.go
  backend/app/service/app_utils.go
  backend/app/service/website_utils.go
  backend/constant/app.go
  backend/i18n/lang/en.yaml
  backend/i18n/lang/zh-Hant.yaml
  backend/i18n/lang/zh.yaml
  backend/init/business/business.go
  backend/init/migration/migrate.go
  backend/init/migration/migrations/v_1_8.go
  backend/utils/files/file_op.go
  backend/utils/files/fileinfo.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2796 feat: 网站 WAF 增加 user-agent 过滤
  backend/app/dto/request/file.go
  backend/app/dto/request/nginx.go
  backend/app/dto/request/website.go
  backend/app/dto/request/website_ssl.go
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/website/website/config/safety/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2797 fix: 解决收藏夹和回收站切换每页数量不生效的问题
  backend/app/api/v1/favorite.go
  frontend/src/views/host/file-management/favorite/index.vue
  frontend/src/views/host/file-management/recycle-bin/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2798 fix: 解决计划任务备份日志的一些问题
  backend/app/service/cornjob.go
  backend/app/service/cronjob_helper.go
  frontend/src/components/del-dialog/index.vue
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/cronjob/index.vue
  frontend/src/views/cronjob/operate/index.vue
  frontend/src/views/cronjob/record/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2799 fix: 解决批量修改文件权限错误的问题
  frontend/src/components/file-role/index.vue
  frontend/src/global/form-rules.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/host/file-management/batch-role/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2801 feat: 服务升级重启等操作时取消前端定时请求
  frontend/src/components/system-upgrade/index.vue
  frontend/src/store/index.ts
  frontend/src/store/interface/index.ts
  frontend/src/views/home/index.vue
  frontend/src/views/login/components/login-form.vue
  frontend/src/views/login/entrance/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2804 fix: 解决排序之后获取文件夹大小导致排序失效的问题
  frontend/src/views/app-store/detail/install/index.vue
  frontend/src/views/host/file-management/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2805 fix: 文件复制粘贴，选择覆盖已存在文件，限制修改文件名
  frontend/src/views/host/file-management/move/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2806 fix: 解决文件拖拽上传空文件夹失败的问题
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/host/file-management/upload/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2807 feat: 创建网站-其他域名增加端口校验
  backend/app/service/website_utils.go
  backend/i18n/lang/en.yaml
  backend/i18n/lang/zh-Hant.yaml
  backend/i18n/lang/zh.yaml
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2808 feat: Node.js 运行环境外部映射端口增加校验
  backend/app/service/runtime.go
  frontend/src/views/website/runtime/node/operate/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2809 fix: 解决 zip 压缩在某些情况下失败的问题
  backend/utils/files/file_op.go
  backend/utils/files/zip.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2816 fix: 解决 UFW 防火墙规则为空时插入规则失败的问题
  backend/utils/firewall/client/ufw.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2819 fix: 解决移动文件夹，所选路径下有同名文件夹时会在同名文件夹下再创建一个文件夹的问题
  backend/utils/files/file_op.go
  frontend/src/views/host/file-management/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2821 fix: 解决反代域名失败的问题
  frontend/src/utils/util.ts
  frontend/src/views/website/website/config/basic/proxy/create/index.vue
  frontend/src/views/website/website/config/safety/value-list/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2823 fix: 解决 UFW 防火墙启用失败的问题
  backend/app/service/firewall.go
  frontend/src/views/cronjob/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2827 fix: 解决 PHP 版本切换可以选择 Node.js 的问题
  frontend/src/views/website/website/config/php/version/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2828 fix: 解决日志审计-网站日志的错误日志不显示的问题
  frontend/src/views/log/website/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2829 fix: 解决日志审计-网站切换网站日志显示错误的问题
  frontend/src/views/log/website/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2830 feat: 优化文件复制-粘贴逻辑
  frontend/src/views/host/file-management/move/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2831 feat: 修改应用升级流程
  backend/app/service/app_utils.go
  backend/app/service/website_utils.go
  backend/i18n/lang/en.yaml
  backend/i18n/lang/zh-Hant.yaml
  backend/i18n/lang/zh.yaml
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2832 fix: 主机连接、数据库连接适配 IPv6
  backend/utils/mysql/client.go
  backend/utils/ssh/ssh.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2839 fix: 解决主机默认分组失败的问题
  backend/app/dto/ssh.go
  backend/app/repo/group.go
  backend/app/service/host.go
  cmd/server/docs/docs.go
  cmd/server/docs/swagger.json
  cmd/server/docs/swagger.yaml
  frontend/src/api/interface/host.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/host/ssh/ssh/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2840 fix: 缓存容器刷新状态
  frontend/src/components/table-setting/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2841 feat: 回收站选择为空的时候禁用删除按钮
  backend/utils/files/archiver.go
  frontend/src/views/host/file-management/recycle-bin/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2842 feat: 前后端域名校验保持一致
  backend/utils/common/common.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2843 fix: 解决上传文件夹失败的问题
  frontend/src/views/host/file-management/upload/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2845 fix: 解决反代保存失败的问题
  backend/app/dto/request/website.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2848 fix: 修改文件删除样式
  frontend/src/views/host/file-management/delete/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2847 fix: 处理容器日志导致的僵尸进程
  backend/app/api/v1/container.go
  backend/app/service/container.go
  backend/app/service/container_compose.go
  frontend/src/components/compose-log/index.vue
  frontend/src/components/container-log/index.vue
  frontend/src/views/container/container/log/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2849 fix: 解决系统别名导致无法修改开机自启的问题
  backend/app/service/ssh.go
  frontend/src/components/compose-log/index.vue
  frontend/src/components/container-log/index.vue
  frontend/src/views/container/container/log/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2850 fix: 解决网站域名重复端口不能提交的问题
  backend/app/service/website_utils.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2851 fix: 修改 ssh 开启自启状态判断
  backend/app/service/ssh.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2852 fix: 解决选择单个文件复制再选多个文件之后显示异常的问题
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/host/file-management/index.vue
  frontend/src/views/host/file-management/move/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2859 feat:增加控制台静态资源/assets/浏览器缓存
  backend/init/router/router.go
Labels: do-not-merge/release-note-label-needed, lgtm, approved

#2863 fix:解决备份还原到新建应用失败的问题 #2854
  backend/app/service/backup_app.go
Labels: do-not-merge/release-note-label-needed

#2864 fix: 解决网站保存设置报错的问题
  backend/app/dto/request/nginx.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2869 feat: 增加证书续签的超时时间
  frontend/src/api/modules/website.ts
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2873 fix: 解决网站反向代理缓存时间选择年报错的问题
  frontend/src/global/mimetype.ts
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2878 feat: 取消检测文件是否存在接口的日志打印
  backend/app/api/v1/file.go
  cmd/server/docs/docs.go
  cmd/server/docs/swagger.json
  cmd/server/docs/swagger.yaml
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2879 fix: 解决本地应用备份恢复报错的问题
  backend/app/model/app_install.go
  backend/app/service/backup_app.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2883 fix: 解决文件复制粘贴路径中带空格导致失败的问题
  backend/utils/files/file_op.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2885 fix: 解决网站设置默认站点失败的问题
  backend/app/dto/request/website.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2886 feat: 增加文件压缩解压的超时时间
  frontend/src/api/modules/files.ts
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2892 perf: 容器操作弹窗的 successMsg 参数
  frontend/src/views/container/container/index.vue
Labels: do-not-merge/release-note-label-needed

#2891 fix: 解决网站密码访问启动报错的问题
  backend/app/dto/request/nginx.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2897 perf: 弹窗操作的 successMsg 参数
  frontend/src/views/container/compose/detail/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved

#2911 perf: home page style
  frontend/src/components/router-button/index.vue
  frontend/src/styles/common.scss
Labels: do-not-merge/release-note-label-needed

#2919 fix: 解决 Openresty 性能调整保存报错的问题
  backend/app/dto/request/nginx.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2920 fix: logr 依赖回退版本
  go.mod
  go.sum
Labels: do-not-merge/release-note-label-needed, dev

#2925 fix: 解决文件上传多选可能导致的文件列表丢失的问题
  frontend/src/components/index.ts
  frontend/src/components/tooltip/index.vue
  frontend/src/views/host/file-management/delete/index.vue
  frontend/src/views/host/file-management/upload/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2926 feat: 概览页重启按钮优化
  backend/app/service/dashboard.go
  frontend/src/components/confirm-dialog/index.vue
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/home/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2933 fix: 解决部分文件不能上传的问题
  frontend/src/views/host/file-management/upload/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2931 fix: 优化镜像清理弹框内容显示
  frontend/src/api/interface/container.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/container/image/prune/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2936 Update README.md
  README.md
Labels: do-not-merge/release-note-label-needed

#2937 Update README.md
  README.md
Labels: do-not-merge/release-note-label-needed, dev

#2943 feat: 优化应用升级逻辑
  backend/app/service/app_utils.go
  backend/constant/errs.go
  backend/utils/docker/compose.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2951 feat: 证书增加 ZeroSSL BuyPass Google 申请
  backend/app/dto/request/website_ssl.go
  backend/app/model/website_acme_account.go
  backend/app/service/website_acme_account.go
  backend/app/service/website_ssl.go
  backend/constant/errs.go
  backend/i18n/lang/en.yaml
  backend/i18n/lang/zh-Hant.yaml
  backend/i18n/lang/zh.yaml
  backend/init/migration/migrate.go
  backend/init/migration/migrations/v_1_9.go
  backend/utils/ssl/acme.go
  backend/utils/ssl/acme_test.go
  backend/utils/ssl/client.go
  frontend/src/api/modules/website.ts
  frontend/src/global/mimetype.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/website/ssl/acme-account/create/index.vue
  frontend/src/views/website/ssl/acme-account/index.vue
  frontend/src/views/website/ssl/index.vue
  go.mod
  go.sum
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2956 fix: FileRole 初始化
  frontend/src/views/host/file-management/batch-role/index.vue
  frontend/src/views/host/file-management/change-role/index.vue
  frontend/src/views/host/file-management/create/index.vue
Labels: do-not-merge/release-note-label-needed

#2959 feat: 导入证书支持 IP 证书
  backend/app/service/website_ssl.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2974 fix: 删除 key
  backend/utils/ssl/acme_test.go
Labels: do-not-merge/release-note-label-needed

#2965 feat: 增加申请 ECC 类型证书
  backend/app/dto/request/website_ssl.go
  backend/app/model/website_acme_account.go
  backend/app/service/website_acme_account.go
  backend/app/service/website_ssl.go
  backend/init/migration/migrations/v_1_9.go
  backend/utils/ssl/acme.go
  backend/utils/ssl/client.go
  frontend/src/global/mimetype.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/website/ssl/acme-account/create/index.vue
  frontend/src/views/website/ssl/acme-account/index.vue
  frontend/src/views/website/ssl/create/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2966 feat: 工具箱增加 Fail2Ban 管理
  backend/app/api/v1/entry.go
  backend/app/api/v1/fail2ban.go
  backend/app/dto/common_req.go
  backend/app/dto/fail2ban.go
  backend/app/service/fail2ban.go
  backend/init/router/router.go
  backend/router/entry.go
  backend/router/ro_toolbox.go
  backend/utils/toolbox/fail2ban.go
  backend/utils/toolbox/fail2ban_test.go
  cmd/server/docs/docs.go
  cmd/server/docs/swagger.json
  cmd/server/docs/swagger.yaml
  frontend/src/api/interface/index.ts
  frontend/src/api/interface/toolbox.ts
  frontend/src/api/modules/toolbox.ts
  frontend/src/components/system-upgrade/index.vue
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/routers/modules/host.ts
  frontend/src/routers/modules/log.ts
  frontend/src/routers/modules/setting.ts
  frontend/src/routers/modules/toolbox.ts
  frontend/src/utils/util.ts
  frontend/src/views/container/setting/index.vue
  frontend/src/views/host/firewall/ip/index.vue
  frontend/src/views/host/firewall/port/index.vue
  frontend/src/views/host/firewall/status/index.vue
  frontend/src/views/host/ssh/ssh/index.vue
  frontend/src/views/setting/about/index.vue
  frontend/src/views/setting/backup-account/operate/index.vue
  frontend/src/views/toolbox/fail2ban/ban-action/index.vue
  frontend/src/views/toolbox/fail2ban/ban-time/index.vue
  frontend/src/views/toolbox/fail2ban/find-time/index.vue
  frontend/src/views/toolbox/fail2ban/index.vue
  frontend/src/views/toolbox/fail2ban/ips/index.vue
  frontend/src/views/toolbox/fail2ban/max-retry/index.vue
  frontend/src/views/toolbox/index.vue
  frontend/src/views/toolbox/supervisor/config/basic/index.vue
  frontend/src/views/toolbox/supervisor/config/index.vue
  frontend/src/views/toolbox/supervisor/config/log/index.vue
  frontend/src/views/toolbox/supervisor/config/source/index.vue
  frontend/src/views/toolbox/supervisor/create/index.vue
  frontend/src/views/toolbox/supervisor/file/index.vue
  frontend/src/views/toolbox/supervisor/index.vue
  frontend/src/views/toolbox/supervisor/status/index.vue
  frontend/src/views/toolbox/supervisor/status/init/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2973 fix: 解决网站某些设置会报服务器内部错误的问题
  backend/app/service/nginx_utils.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2975 feat: 概览页增加 Swap 分区监控
  backend/app/dto/dashboard.go
  backend/app/service/dashboard.go
  cmd/server/docs/docs.go
  cmd/server/docs/swagger.json
  cmd/server/docs/swagger.yaml
  frontend/src/api/interface/dashboard.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/home/index.vue
  frontend/src/views/home/status/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2980 fix: 本地数据库备份命令增加 --default-character-set 参数 与备份还原的编码保持一致
  backend/utils/mysql/client/local.go
Labels: do-not-merge/release-note-label-needed, lgtm

#2983 feat: 应用商店请求增加超时时间
  backend/utils/http/get.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2982 feat: 证书增加多个 DNS 服务商
  backend/app/service/website_ssl.go
  backend/utils/ssl/acme.go
  backend/utils/ssl/acme_test.go
  backend/utils/ssl/client.go
  frontend/src/views/website/ssl/dns-account/create/index.vue
  go.mod
  go.sum
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2987 Update vite.config.ts
  frontend/vite.config.ts
Labels: do-not-merge/release-note-label-needed

#2991 feat: 优化证书申请流程
  backend/app/api/v1/website_ssl.go
  backend/app/dto/request/website_ssl.go
  backend/app/model/website_ssl.go
  backend/app/service/website_ssl.go
  backend/constant/status.go
  backend/constant/website.go
  backend/i18n/lang/en.yaml
  backend/i18n/lang/zh-Hant.yaml
  backend/i18n/lang/zh.yaml
  backend/init/migration/migrate.go
  backend/init/migration/migrations/v_1_9.go
  backend/router/ro_website_ssl.go
  cmd/server/docs/docs.go
  cmd/server/docs/swagger.json
  cmd/server/docs/swagger.yaml
  frontend/src/api/interface/website.ts
  frontend/src/api/modules/website.ts
  frontend/src/components/status/index.vue
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/website/ssl/apply/index.vue
  frontend/src/views/website/ssl/create/index.vue
  frontend/src/views/website/ssl/detail/index.vue
  frontend/src/views/website/ssl/index.vue
  go.mod
  go.sum
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3001 feat: 增加主机工具箱管理
  backend/app/api/v1/device.go
  backend/app/api/v1/entry.go
  backend/app/api/v1/setting.go
  backend/app/dto/common_req.go
  backend/app/dto/device.go
  backend/app/service/device.go
  backend/app/service/setting.go
  backend/router/ro_setting.go
  backend/router/ro_toolbox.go
  backend/utils/toolbox/fail2ban_test.go
  cmd/server/docs/docs.go
  cmd/server/docs/swagger.json
  cmd/server/docs/swagger.yaml
  frontend/src/api/interface/toolbox.ts
  frontend/src/api/modules/toolbox.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/routers/modules/toolbox.ts
  frontend/src/views/setting/panel/index.vue
  frontend/src/views/toolbox/device/dns/index.vue
  frontend/src/views/toolbox/device/hostname/index.vue
  frontend/src/views/toolbox/device/hosts/index.vue
  frontend/src/views/toolbox/device/index.vue
  frontend/src/views/toolbox/device/local-time/index.vue
  frontend/src/views/toolbox/device/passwd/index.vue
  frontend/src/views/toolbox/device/time-zone/index.vue
  frontend/src/views/toolbox/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3004 Update sonar-project.properties
  sonar-project.properties
Labels: do-not-merge/release-note-label-needed, dev

#3002 feat: 证书增加申请日志
  backend/app/dto/response/website_ssl.go
  backend/app/service/website_ssl.go
  backend/constant/dir.go
  backend/cron/job/ssl.go
  backend/i18n/lang/en.yaml
  backend/i18n/lang/zh-Hant.yaml
  backend/i18n/lang/zh.yaml
  backend/init/app/app.go
  backend/init/business/business.go
  frontend/src/api/interface/website.ts
  frontend/src/api/modules/website.ts
  frontend/src/components/log/index.vue
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/website/runtime/php/index.vue
  frontend/src/views/website/ssl/index.vue
Labels: do-not-merge/release-note-label-needed, dev

#3003 feat: 修改可编辑表格样式
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/container/container/operate/index.vue
  frontend/src/views/host/ssh/log/analysis/index.vue
  frontend/src/views/host/ssh/log/log.vue
  frontend/src/views/toolbox/device/hosts/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3016 feat: 容器适配 IPv6
  backend/app/api/v1/docker.go
  backend/app/dto/container.go
  backend/app/dto/docker.go
  backend/app/service/container_network.go
  backend/app/service/docker.go
  backend/router/ro_container.go
  cmd/server/docs/docs.go
  cmd/server/docs/swagger.json
  cmd/server/docs/swagger.yaml
  frontend/src/api/interface/container.ts
  frontend/src/api/modules/container.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/utils/util.ts
  frontend/src/views/container/network/create/index.vue
  frontend/src/views/container/setting/index.vue
  frontend/src/views/container/setting/ipv6/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3021 feat: 容器创建支持特权模式
  backend/app/dto/container.go
  backend/app/service/container.go
  frontend/src/api/interface/container.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/container/container/operate/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3024 fix: 禁 Ping 兼容 ipv6
  backend/app/service/firewall.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3029 fix: 解决镜像仓库编辑失败的问题
  backend/app/service/image_repo.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3035 feat: 统一部分日志页面
  backend/app/api/v1/file.go
  backend/app/dto/request/file.go
  backend/app/model/website_ssl.go
  backend/app/service/container.go
  backend/app/service/file.go
  backend/app/service/logs.go
  backend/constant/common.go
  backend/utils/files/utils.go
  backend/utils/ssl/client.go
  cmd/server/docs/docs.go
  cmd/server/docs/swagger.json
  cmd/server/docs/swagger.yaml
  frontend/src/api/interface/file.ts
  frontend/src/components/log-dialog/index.vue
  frontend/src/components/log-file/index.vue
  frontend/src/components/log/index.vue
  frontend/src/views/container/compose/create/index.vue
  frontend/src/views/container/image/build/index.vue
  frontend/src/views/container/image/pull/index.vue
  frontend/src/views/container/image/push/index.vue
  frontend/src/views/log/system/index.vue
  frontend/src/views/log/website/index.vue
  frontend/src/views/website/runtime/php/index.vue
  frontend/src/views/website/ssl/index.vue
  frontend/src/views/website/website/config/log/log-fiile/index.vue
  frontend/vite.config.ts
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3056 fix: 修复网站404重定向次数过多 (#3054)
  backend/app/service/website.go
Labels: do-not-merge/release-note-label-needed

#3070 feat: 增加证书推送到本地目录功能
  backend/app/dto/request/website_ssl.go
  backend/app/model/website_ssl.go
  backend/app/repo/website_ssl.go
  backend/app/service/website_ca.go
  backend/app/service/website_ssl.go
  backend/app/service/website_utils.go
  backend/i18n/lang/en.yaml
  backend/i18n/lang/zh-Hant.yaml
  backend/i18n/lang/zh.yaml
  backend/init/migration/migrations/v_1_9.go
  cmd/server/docs/docs.go
  cmd/server/docs/swagger.json
  cmd/server/docs/swagger.yaml
  frontend/src/api/interface/website.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/website/ssl/ca/obtain/index.vue
  frontend/src/views/website/ssl/create/index.vue
  frontend/src/views/website/ssl/detail/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3071 fix: Fail2ban 名称修改
  backend/app/api/v1/fail2ban.go
  backend/utils/toolbox/fail2ban.go
  cmd/server/docs/docs.go
  cmd/server/docs/swagger.json
  cmd/server/docs/swagger.yaml
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/routers/modules/toolbox.ts
  frontend/src/views/toolbox/fail2ban/index.vue
  frontend/src/views/toolbox/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3072 fix: 类名重命名
  frontend/src/views/login/entrance/index.vue
  frontend/src/views/login/index.vue
Labels: do-not-merge/release-note-label-needed

#3076 feat: 增加批量删除证书功能
  backend/app/api/v1/website_ssl.go
  backend/app/dto/request/website_ssl.go
  backend/app/service/website_ca.go
  backend/app/service/website_ssl.go
  backend/i18n/lang/en.yaml
  backend/i18n/lang/zh-Hant.yaml
  backend/i18n/lang/zh.yaml
  cmd/server/docs/docs.go
  cmd/server/docs/swagger.json
  cmd/server/docs/swagger.yaml
  frontend/src/components/del-dialog/index.vue
  frontend/src/views/website/ssl/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3074 fix: 概览页磁盘信息获取增加超时时间
  backend/app/service/dashboard.go
  frontend/src/views/home/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3079 feat: 自签证书增加续签功能
  backend/app/api/v1/website_ca.go
  backend/app/api/v1/website_ssl.go
  backend/app/dto/request/website_ssl.go
  backend/app/model/website_ssl.go
  backend/app/repo/website_ssl.go
  backend/app/service/website.go
  backend/app/service/website_ca.go
  backend/app/service/website_ssl.go
  backend/app/service/website_utils.go
  backend/cron/job/ssl.go
  backend/i18n/lang/en.yaml
  backend/i18n/lang/zh-Hant.yaml
  backend/i18n/lang/zh.yaml
  backend/init/migration/migrations/v_1_9.go
  backend/router/ro_website_ca.go
  backend/router/ro_website_ssl.go
  cmd/server/docs/docs.go
  cmd/server/docs/swagger.json
  cmd/server/docs/swagger.yaml
  frontend/src/api/interface/website.ts
  frontend/src/api/modules/website.ts
  frontend/src/components/log-dialog/index.vue
  frontend/src/components/log-file/index.vue
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/website/ssl/apply/index.vue
  frontend/src/views/website/ssl/ca/obtain/index.vue
  frontend/src/views/website/ssl/index.vue
  frontend/src/views/website/ssl/obtain/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3085 feat: Docker 服务支持自定义 .sock 路径
  backend/app/dto/setting.go
  backend/init/migration/migrate.go
  backend/init/migration/migrations/v_1_9.go
  backend/server/server.go
  backend/utils/docker/docker.go
  cmd/server/docs/docs.go
  cmd/server/docs/swagger.json
  cmd/server/docs/swagger.yaml
  frontend/src/api/interface/setting.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/container/setting/index.vue
  frontend/src/views/container/setting/sock-path/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3087 feat: 手动创建证书增加更新功能
  backend/app/dto/request/website_ssl.go
  backend/app/model/website_ssl.go
  backend/app/service/website_ssl.go
  backend/init/migration/migrations/v_1_9.go
  frontend/src/api/interface/website.ts
  frontend/src/views/website/ssl/detail/index.vue
  frontend/src/views/website/ssl/index.vue
  frontend/src/views/website/ssl/upload/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3091 feat: Mysql 远程数据库支持 SSL
  backend/app/api/v1/database.go
  backend/app/dto/database.go
  backend/app/model/database.go
  backend/app/service/database.go
  backend/app/service/database_mysql.go
  backend/init/migration/migrate.go
  backend/init/migration/migrations/v_1_9.go
  backend/utils/mysql/client.go
  backend/utils/mysql/client/info.go
  backend/utils/mysql/client/remote.go
  frontend/src/api/interface/database.ts
  frontend/src/api/modules/database.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/database/mysql/remote/operate/index.vue
  frontend/src/views/home/status/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3092 feat: 证书增加备注
  backend/app/dto/request/website_ssl.go
  backend/app/service/website_ssl.go
  frontend/src/api/interface/website.ts
  frontend/src/views/website/ssl/create/index.vue
  frontend/src/views/website/ssl/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3096 fix: 概览页磁盘显示优化
  backend/app/service/dashboard.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3100 fix: 概览页磁盘信息获取增加锁
  backend/app/service/dashboard.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3097 feat: 机构增加详情查看页
  backend/app/dto/request/website_ssl.go
  backend/app/dto/response/website_ssl.go
  backend/app/service/website_ca.go
  backend/router/ro_website_ca.go
  cmd/server/docs/docs.go
  cmd/server/docs/swagger.json
  cmd/server/docs/swagger.yaml
  frontend/src/api/interface/website.ts
  frontend/src/api/modules/website.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/website/ssl/ca/create/index.vue
  frontend/src/views/website/ssl/ca/detail/index.vue
  frontend/src/views/website/ssl/ca/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3105 feat: 申请证书支持直接从网站选取域名
  backend/app/repo/website.go
  backend/app/service/website_ssl.go
  backend/i18n/lang/en.yaml
  backend/i18n/lang/zh-Hant.yaml
  backend/i18n/lang/zh.yaml
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/website/ssl/ca/obtain/index.vue
  frontend/src/views/website/ssl/create/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3106 feat: 优化 zip 文件压缩/解压
  backend/utils/files/file_op.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3102 fix: 解决证书面板过期问题
  backend/app/api/v1/website_ca.go
  backend/app/service/setting.go
  backend/app/service/website_ca.go
  backend/cron/job/ssl.go
  backend/init/migration/migrate.go
  backend/init/migration/migrations/v_1_9.go
  backend/utils/ssl/ssl.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3107 feat: 面板主题色增加跟随浏览器
  frontend/src/hooks/use-theme.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/layout/index.vue
  frontend/src/views/setting/panel/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3113 feat: 自签证书和手动上传证书增加备注
  backend/app/dto/request/website_ssl.go
  backend/app/service/website_ca.go
  backend/app/service/website_ssl.go
  backend/init/migration/migrations/v_1_9.go
  frontend/src/api/interface/website.ts
  frontend/src/views/website/ssl/ca/detail/index.vue
  frontend/src/views/website/ssl/ca/obtain/index.vue
  frontend/src/views/website/ssl/index.vue
  frontend/src/views/website/ssl/upload/index.vue
  frontend/src/views/website/website/config/basic/https/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3115 fix: 解决添加 User-Agent 过滤失败的问题
  backend/app/dto/request/website.go
  frontend/src/views/website/ssl/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3114 feat: 镜像删除增加存在性判断
  backend/app/dto/container.go
  backend/app/service/image.go
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/container/image/delete/index.vue
  frontend/src/views/container/image/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved
