Repository 1Panel-dev/1Panel, pull requests merged in 2023-09, with the labels that each got.

#2139 feat: 远程数据库支持添加 mariadb
  backend/app/dto/database.go
  backend/app/repo/database.go
  backend/app/service/app_install.go
  backend/app/service/database.go
  backend/utils/mysql/client/local.go
  backend/utils/mysql/client/remote.go
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/database/mysql/index.vue
  frontend/src/views/database/mysql/remote/index.vue
  frontend/src/views/database/mysql/remote/operate/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2141 fix: 面板设置样式调整
  frontend/src/components/system-upgrade/index.vue
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/styles/common.scss
  frontend/src/views/database/mysql/create/index.vue
  frontend/src/views/database/mysql/index.vue
  frontend/src/views/database/mysql/remote/index.vue
  frontend/src/views/database/mysql/remote/operate/index.vue
  frontend/src/views/setting/panel/index.vue
  frontend/src/views/setting/safe/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2142 fix: 解决概览页流量突增问题
  frontend/src/views/home/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2146 feat: 数据库密码加密存储
  backend/app/repo/database.go
  backend/app/repo/databse_mysql.go
  backend/app/service/database.go
  backend/app/service/database_mysql.go
  backend/init/hook/hook.go
  backend/init/migration/migrate.go
  backend/init/migration/migrations/init.go
  backend/utils/encrypt/encrypt.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2162 fix: 统一状态栏样式
  frontend/src/views/container/setting/index.vue
  frontend/src/views/cronjob/record/index.vue
  frontend/src/views/host/ssh/ssh/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2165 fix: 解决页面像素不对齐的问题
  frontend/src/components/svg-icon/svg-icon.vue
  frontend/src/components/system-upgrade/index.vue
  frontend/src/layout/components/AppFooter.vue
  frontend/src/layout/components/Sidebar/components/Collapse.vue
  frontend/src/layout/components/Sidebar/components/Logo.vue
  frontend/src/layout/components/Sidebar/components/SubItem.vue
  frontend/src/layout/components/Sidebar/index.scss
  frontend/src/layout/components/Sidebar/index.vue
  frontend/src/layout/index.vue
Labels: do-not-merge/release-note-label-needed

#2163 fix: 调整按钮样式
  frontend/src/styles/element.scss
  frontend/src/views/setting/panel/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2166 fix: 修改远程数据库列表查询规则
  backend/app/repo/database.go
  backend/init/migration/migrations/init.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2169 🎨 容器列表添加网络地址列
  backend/app/dto/container.go
  backend/app/service/container.go
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/container/container/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm

#2170 fix: 解决防火墙筛选问题
  backend/app/service/firewall.go
  backend/utils/common/common.go
  frontend/src/views/host/firewall/ip/index.vue
  frontend/src/views/host/firewall/port/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2168 feat: 优化应用安装流程
  frontend/src/components/app-status/index.vue
  frontend/src/views/app-store/apps/index.vue
  frontend/src/views/app-store/detail/index.vue
  frontend/src/views/app-store/detail/install/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2171 fix: 修改 migration，解决升级失败的问题
  backend/init/migration/migrations/init.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2172 feat: 解决安装应用失败的问题
  backend/app/service/app.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2174 fix: 解决合并导致的代码格式问题
  frontend/src/api/interface/container.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/container/container/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2177 fix: 解决数据库切换时，状态标签显示不正常的问题
  backend/app/service/app_install.go
  frontend/src/views/database/mysql/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2178 feat: 解决快速安装应用跳转失败问题
  frontend/src/components/app-status/index.vue
  frontend/src/routers/modules/app-store.ts
  frontend/src/views/app-store/apps/index.vue
  frontend/src/views/app-store/detail/index.vue
  frontend/src/views/app-store/detail/install/index.vue
  frontend/src/views/app-store/detail/params/index.vue
  frontend/src/views/database/mysql/index.vue
  frontend/src/views/database/redis/index.vue
  frontend/src/views/home/app/index.vue
  frontend/src/views/host/file-management/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2179 fix: 容器列表样式调整
  backend/app/service/container.go
  frontend/src/views/container/container/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2184 style: 修改文件和应用商店样式
  frontend/src/api/interface/app.ts
  frontend/src/views/app-store/apps/index.vue
  frontend/src/views/host/file-management/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2186 fix: 解决守护进程停止之后状态读取异常的问题
  backend/app/api/v1/host_tool.go
  backend/app/service/host_tool.go
  backend/router/ro_host.go
  frontend/src/api/modules/host-tool.ts
  frontend/src/views/host/tool/supervisor/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2188 fix: 容器列表端口显示优化
  backend/app/service/container.go
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/container/container/index.vue
  frontend/src/views/database/mysql/index.vue
  frontend/src/views/database/mysql/remote/index.vue
  frontend/src/views/host/firewall/ip/operate/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2189 feat: MySQL 数据库选择项增加跳转
  frontend/src/views/database/mysql/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2191 feat: 容器日志行数增加所有选项
  backend/app/service/container.go
  frontend/src/components/container-log/index.vue
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/container/container/log/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2190 feat：网站目录支持三级 增加网站目录权限校验
  backend/app/api/v1/website.go
  backend/app/dto/request/website.go
  backend/app/dto/response/website.go
  backend/app/service/website.go
  backend/app/service/website_utils.go
  backend/i18n/lang/en.yaml
  backend/i18n/lang/zh-Hant.yaml
  backend/i18n/lang/zh.yaml
  backend/router/ro_website.go
  cmd/server/docs/docs.go
  cmd/server/docs/swagger.json
  cmd/server/docs/swagger.yaml
  frontend/src/api/interface/website.ts
  frontend/src/api/modules/website.ts
  frontend/src/views/website/website/config/basic/site-folder/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2196 fix: 解决路由按钮边框显示异常的问题
  frontend/src/App.vue
  frontend/src/api/helper/axios-cancel.ts
  frontend/src/components/router-button/index.vue
  frontend/src/main.ts
  frontend/src/routers/cache-router.ts
  frontend/src/typings/global.d.ts
Labels: do-not-merge/release-note-label-needed

#2195 fix: 修改数据库重复校验判断
  backend/app/service/database.go
  backend/constant/errs.go
  backend/i18n/lang/en.yaml
  backend/i18n/lang/zh-Hant.yaml
  backend/i18n/lang/zh.yaml
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2197 fix: 解决文件名带空格导致的设置权限失败的问题
  backend/app/service/website_utils.go
  backend/utils/files/file_op.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2202 style: 修改部分弹窗 提示文字样式
  frontend/src/components/error-prompt/index.vue
  frontend/src/components/index.ts
  frontend/src/styles/common.scss
  frontend/src/views/app-store/detail/index.vue
  frontend/src/views/app-store/installed/check/index.vue
  frontend/src/views/host/file-management/delete/index.vue
  frontend/src/views/host/file-management/index.vue
  frontend/src/views/host/tool/supervisor/status/init/index.vue
  frontend/src/views/website/website/delete/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2207 feat: 数据库设置或远程服务器跳转返回时跳转到原路由
  backend/app/dto/database.go
  backend/app/service/database.go
  frontend/src/store/index.ts
  frontend/src/store/interface/index.ts
  frontend/src/views/database/mysql/index.vue
  frontend/src/views/database/mysql/remote/operate/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2208 fix: 解决获取默认配置失败的问题
  backend/app/api/v1/app_install.go
  backend/app/repo/app_install.go
  backend/app/service/app_install.go
  backend/constant/app.go
  backend/router/ro_app.go
  cmd/server/docs/docs.go
  cmd/server/docs/swagger.json
  cmd/server/docs/swagger.yaml
  frontend/src/api/modules/app.ts
  frontend/src/views/database/mysql/setting/index.vue
  frontend/src/views/database/redis/setting/index.vue
  frontend/src/views/website/website/nginx/source/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2212 feat: 安装数据库应用增加与远程数据库名称校验
  backend/app/service/app.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2214 feat: 解决数据库同步时存在特殊字符导致失败的问题
  backend/utils/common/common.go
  backend/utils/mysql/client/info.go
  backend/utils/mysql/client/remote.go
  go.mod
  go.sum
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2218 fix: 数据库删除检查样式调整
  frontend/src/views/container/container/handle/index.vue
  frontend/src/views/database/mysql/check/index.vue
  frontend/src/views/database/mysql/setting/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2219 fix: 解决删除 mariadb 的时候没有删除数据库表信息的问题
  backend/app/service/app_utils.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2220 fix: 修改数据库创建权限校验规则
  backend/utils/mysql/client/local.go
  backend/utils/mysql/client/remote.go
  frontend/src/views/database/mysql/create/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2222 fix: 解决数据库创建重命名用户的问题
  backend/utils/mysql/client/remote.go
  frontend/src/views/database/mysql/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2226 fix: 修改数据库配置文件不存在提示信息
  backend/app/repo/database.go
  backend/utils/mysql/client/local.go
  backend/utils/mysql/client/remote.go
  frontend/src/api/modules/setting.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/database/mysql/setting/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2227 fix: 快照增加文件大小显示
  backend/app/dto/setting.go
  backend/app/model/snapshot.go
  backend/app/service/snapshot.go
  backend/app/service/snapshot_create.go
  backend/init/migration/migrations/init.go
  backend/utils/common/common.go
  frontend/src/api/interface/setting.ts
  frontend/src/views/setting/snapshot/snap_status/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2232 fix: 修改 mongodb 和 postgresql 的数据库用户名获取
  backend/app/repo/app_install.go
  backend/init/migration/migrations/init.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2235 fix: 数据库选择项样式优化
  frontend/src/views/cronjob/operate/index.vue
  frontend/src/views/database/mysql/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2252 fix: 解决不同 mysql 应用无法同名的问题
  backend/app/service/database_mysql.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2255 fix: 数据库、计划任务下拉框样式调整
  backend/app/dto/database.go
  backend/app/service/database_mysql.go
  cmd/server/docs/docs.go
  cmd/server/docs/swagger.json
  cmd/server/docs/swagger.yaml
  frontend/src/api/interface/database.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/container/container/operate/index.vue
  frontend/src/views/cronjob/operate/index.vue
  frontend/src/views/database/mysql/index.vue
  frontend/src/views/database/mysql/setting/index.vue
  frontend/src/views/setting/snapshot/snap_status/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2256 fix: 解决防火墙搜索报错的问题
  frontend/src/api/modules/host.ts
  frontend/src/views/host/firewall/ip/index.vue
  frontend/src/views/host/firewall/port/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2257 feat: 支持自定义概览页安全入口提示是否显示
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/store/index.ts
  frontend/src/store/interface/index.ts
  frontend/src/views/home/index.vue
  frontend/src/views/setting/safe/entrance/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2259 fix: 解决数据库切换导致的错乱样式问题
  backend/init/migration/migrations/init.go
  frontend/src/views/database/mysql/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2264 fix: 解决应用安装选择 mariadb 安装失败的问题
  backend/app/repo/app.go
  backend/app/service/app.go
  backend/app/service/app_install.go
  backend/app/service/app_utils.go
  backend/init/migration/migrations/init.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2261 feat: 优化防火墙响应速度
  backend/app/service/firewall.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2262 fix: 容器列表页显示端口映射对应 ip
  backend/app/service/container.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2267 fix: 解决应用停止之后不能启动的问题
  backend/app/service/app_install.go
  backend/utils/docker/docker.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2268 fix: 修改防火墙操作超时时间
  backend/app/service/website.go
  frontend/src/api/modules/app.ts
  frontend/src/api/modules/container.ts
  frontend/src/api/modules/cronjob.ts
  frontend/src/api/modules/database.ts
  frontend/src/api/modules/files.ts
  frontend/src/api/modules/host-tool.ts
  frontend/src/api/modules/host.ts
  frontend/src/api/modules/setting.ts
  frontend/src/api/modules/website.ts
  frontend/src/enums/http-enum.ts
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2270 fix: 解决快照上传失败的问题
  backend/app/service/snapshot_create.go
  frontend/src/views/setting/snapshot/import/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2272 feat: 取消 HTTP 模式下申请证书的 Openresty 端口校验
  backend/app/service/website_ssl.go
  backend/i18n/lang/en.yaml
  backend/i18n/lang/zh-Hant.yaml
  backend/i18n/lang/zh.yaml
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2274 feat: 升级时暂停计划任务
  backend/app/service/upgrade.go
  backend/init/migration/migrations/init.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2276 style: 修改 openresty 非 80 443 端口提示
  frontend/src/components/app-status/index.vue
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2277 fix: 解决容器切换端口选项时，仍然进行端口校验的问题
  backend/app/service/backup_app.go
  frontend/src/views/container/container/operate/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2278 fix: 解决计划任务备份所有应用失败的问题
  backend/app/api/v1/database_mysql.go
  backend/app/dto/database.go
  backend/app/service/cornjob.go
  backend/app/service/cronjob_helper.go
  backend/app/service/database_mysql.go
  cmd/server/docs/docs.go
  cmd/server/docs/swagger.json
  cmd/server/docs/swagger.yaml
  frontend/src/api/interface/cronjob.ts
  frontend/src/api/interface/database.ts
  frontend/src/api/modules/database.ts
  frontend/src/views/cronjob/record/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2279 fix: 解决 mariadb 删除没有同步删除数据库表的问题
  backend/app/service/app_utils.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2280 fix: 解决 mariadb 删除没有同步删除数据库表的问题
  backend/app/service/app_utils.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2281 fix: 解决 MySQL 8.x 切换数据库访问权限导致创建数据库失败的问题
  backend/utils/mysql/client/local.go
  backend/utils/mysql/client/remote.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2284 fix: 修改计划任务下载判断
  backend/utils/common/common.go
  frontend/src/views/cronjob/record/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2283 fix: 解决 MySQL 8.x 切换数据库访问权限导致创建数据库失败的问题
  backend/utils/mysql/client/local.go
  backend/utils/mysql/client/remote.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2286 fix: 解决同步计划任务中快照失败的问题
  backend/app/service/snapshot.go
  backend/app/service/snapshot_create.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2287 fix: 解决快照恢复时应用重建无法拉起的问题
  backend/app/service/snapshot.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2292 fix: 解决防火墙偶发的修改备注信息失败的问题
  backend/app/service/firewall.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2295 fix: 解决限制安装的应用程序在首页还能继续安装的问题
  frontend/src/views/home/app/index.vue
Labels: dev, lgtm, approved

#2305 style: 容器界面提示文字和操作保持一致
  frontend/src/views/container/container/handle/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2307 fix: 修复导航样式冲突
  frontend/src/styles/element-dark.scss
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2306 fix: 解决数据冲突导致的升级失败问题
  backend/app/api/v1/database_mysql.go
  backend/app/dto/database.go
  backend/app/model/database.go
  backend/app/model/database_mysql.go
  backend/app/repo/databse_mysql.go
  backend/app/service/app_utils.go
  backend/app/service/backup_app.go
  backend/app/service/backup_mysql.go
  backend/app/service/cronjob_helper.go
  backend/app/service/database.go
  backend/app/service/database_mysql.go
  backend/init/migration/migrate.go
  backend/init/migration/migrations/init.go
  backend/utils/mysql/client/info.go
  backend/utils/mysql/client/local.go
  backend/utils/mysql/client/remote.go
  cmd/server/docs/docs.go
  cmd/server/docs/swagger.json
  cmd/server/docs/swagger.yaml
  frontend/src/api/interface/database.ts
  frontend/src/api/modules/database.ts
  frontend/src/components/backup/index.vue
  frontend/src/components/upload/index.vue
  frontend/src/routers/modules/database.ts
  frontend/src/views/database/mysql/conn/index.vue
  frontend/src/views/database/mysql/create/index.vue
  frontend/src/views/database/mysql/delete/index.vue
  frontend/src/views/database/mysql/index.vue
  frontend/src/views/database/mysql/password/index.vue
  frontend/src/views/database/mysql/setting/index.vue
  frontend/src/views/database/mysql/setting/slow-log/index.vue
  frontend/src/views/database/mysql/setting/status/index.vue
  frontend/src/views/database/mysql/setting/variables/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2308 fix: 解决数据库性能调整导致服务重启的问题
  backend/app/service/snapshot_create.go
  backend/utils/common/common.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2311 feat: 修改应用安装删除数据库逻辑
  backend/app/repo/databse_mysql.go
  backend/app/service/app.go
  backend/app/service/app_install.go
  backend/app/service/app_utils.go
  backend/constant/errs.go
  backend/i18n/lang/en.yaml
  backend/i18n/lang/zh-Hant.yaml
  backend/i18n/lang/zh.yaml
  backend/init/migration/migrate.go
  backend/init/migration/migrations/init.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2313 fix: 修复日志文件下载不全的问题
  backend/app/dto/response/website.go
  backend/app/service/website.go
  frontend/src/api/interface/website.ts
  frontend/src/views/website/website/config/log/log-fiile/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2314 fix: 修改数据库删除逻辑
  backend/app/dto/database.go
  backend/app/repo/databse_mysql.go
  backend/app/service/app_utils.go
  backend/app/service/backup_app.go
  backend/app/service/database_mysql.go
  cmd/server/docs/docs.go
  cmd/server/docs/swagger.json
  cmd/server/docs/swagger.yaml
  frontend/src/api/interface/database.ts
  frontend/src/views/database/mysql/delete/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2315 fix: 修改数据库备份逻辑
  backend/app/service/backup_mysql.go
  backend/app/service/cronjob_helper.go
  backend/init/migration/migrate.go
  backend/init/migration/migrations/init.go
  backend/utils/mysql/client/info.go
  frontend/src/components/backup/index.vue
  frontend/src/components/upload/index.vue
  frontend/src/views/database/mysql/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2316 fix: 数据库部分逻辑调整
  backend/app/api/v1/database_mysql.go
  backend/app/dto/database.go
  backend/app/model/database.go
  backend/app/model/database_mysql.go
  backend/app/repo/databse_mysql.go
  backend/app/service/app_utils.go
  backend/app/service/backup_app.go
  backend/app/service/backup_mysql.go
  backend/app/service/cronjob_helper.go
  backend/app/service/database.go
  backend/app/service/database_mysql.go
  backend/constant/errs.go
  backend/i18n/lang/en.yaml
  backend/i18n/lang/zh-Hant.yaml
  backend/i18n/lang/zh.yaml
  backend/init/migration/migrate.go
  backend/init/migration/migrations/init.go
  backend/utils/mysql/client/info.go
  backend/utils/mysql/client/local.go
  backend/utils/mysql/client/remote.go
  cmd/server/docs/docs.go
  cmd/server/docs/swagger.json
  cmd/server/docs/swagger.yaml
  frontend/src/api/interface/database.ts
  frontend/src/api/modules/database.ts
  frontend/src/components/app-status/index.vue
  frontend/src/components/backup/index.vue
  frontend/src/components/upload/index.vue
  frontend/src/views/database/mysql/conn/index.vue
  frontend/src/views/database/mysql/create/index.vue
  frontend/src/views/database/mysql/delete/index.vue
  frontend/src/views/database/mysql/index.vue
  frontend/src/views/database/mysql/password/index.vue
  frontend/src/views/database/mysql/setting/index.vue
  frontend/src/views/database/mysql/setting/slow-log/index.vue
  frontend/src/views/database/mysql/setting/status/index.vue
  frontend/src/views/database/mysql/setting/variables/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2320 fix: 修改数据库设置跳转路由
  backend/app/service/app.go
  backend/app/service/database_mysql.go
  frontend/src/routers/modules/database.ts
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2322 fix: 优化版本排序
  backend/app/service/app_install.go
  backend/utils/common/common.go
  frontend/src/components/app-status/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2323 fix: 解决恢复应用导致数据库备份文件丢失的问题
  backend/app/service/backup_app.go
  backend/app/service/database_mysql.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2324 fix: 修改容器操作提示信息
  frontend/src/views/container/container/handle/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2328 redis 增加详细的远程连接信息，并添加复制按钮
  frontend/src/api/interface/app.ts
  frontend/src/views/database/redis/password/index.vue
Labels: do-not-merge/release-note-label-needed

#2334 fix: 修改登录接口文档
  backend/app/api/v1/auth.go
  cmd/server/docs/docs.go
  cmd/server/docs/swagger.json
  cmd/server/docs/swagger.yaml
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2335 fix: MySQL 设置页样式统一
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/database/mysql/setting/index.vue
  frontend/src/views/database/redis/password/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2337 feat: 缓存页面分页条数
  frontend/src/components/backup/index.vue
  frontend/src/components/complex-table/index.vue
  frontend/src/components/upload/index.vue
  frontend/src/views/app-store/apps/index.vue
  frontend/src/views/app-store/installed/index.vue
  frontend/src/views/container/compose/detail/index.vue
  frontend/src/views/container/compose/index.vue
  frontend/src/views/container/container/index.vue
  frontend/src/views/container/image/index.vue
  frontend/src/views/container/network/index.vue
  frontend/src/views/container/repo/index.vue
  frontend/src/views/container/template/index.vue
  frontend/src/views/container/volume/index.vue
  frontend/src/views/cronjob/index.vue
  frontend/src/views/cronjob/record/index.vue
  frontend/src/views/database/mysql/index.vue
  frontend/src/views/database/mysql/remote/index.vue
  frontend/src/views/database/redis/setting/persistence/index.vue
  frontend/src/views/host/file-management/index.vue
  frontend/src/views/host/firewall/ip/index.vue
  frontend/src/views/host/firewall/port/index.vue
  frontend/src/views/host/ssh/log/log.vue
  frontend/src/views/host/terminal/command/index.vue
  frontend/src/views/host/terminal/host/index.vue
  frontend/src/views/log/login/index.vue
  frontend/src/views/log/operation/index.vue
  frontend/src/views/setting/snapshot/index.vue
  frontend/src/views/website/runtime/index.vue
  frontend/src/views/website/ssl/acme-account/index.vue
  frontend/src/views/website/ssl/dns-account/index.vue
  frontend/src/views/website/ssl/index.vue
  frontend/src/views/website/website/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2339 fix: 面板设置增加默认监控网卡选择
  backend/app/dto/setting.go
  backend/init/migration/migrate.go
  backend/init/migration/migrations/v_1_7.go
  frontend/src/api/interface/setting.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/store/index.ts
  frontend/src/store/interface/index.ts
  frontend/src/views/home/index.vue
  frontend/src/views/host/monitor/monitor/index.vue
  frontend/src/views/setting/panel/default-network/index.vue
  frontend/src/views/setting/panel/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2341 fix: 解决网站设置 PHP 源文之后没有立即生效的问题
  backend/app/service/website.go
  frontend/src/views/website/website/config/resource/nginx/index.vue
  frontend/src/views/website/website/config/resource/php-fpm/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2346 fix: 解决 Supervisor 停止之后一直同步状态的问题
  frontend/src/views/host/tool/supervisor/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2348 fix: 解决部分容器创建失败的问题
  frontend/src/views/container/container/operate/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2349 fix: 优化部分日志打印
  backend/app/service/snapshot.go
  backend/app/service/upgrade.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2350 fix: 解决网站打开页面错误的问题
  frontend/src/components/complex-table/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2357 Create FUNDING.yml
  .github/FUNDING.yml
Labels: do-not-merge/release-note-label-needed, dev

#2352 feat: 系统授权 ip 支持 ip 段
  backend/middleware/ip_limit.go
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/setting/safe/allowips/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2347 feat: ssh 登录日志增加概览显示
  backend/app/api/v1/ssh.go
  backend/app/dto/ssh.go
  backend/app/service/firewall.go
  backend/app/service/ssh.go
  backend/constant/errs.go
  backend/i18n/lang/en.yaml
  backend/i18n/lang/zh-Hant.yaml
  backend/i18n/lang/zh.yaml
  backend/router/ro_host.go
  backend/utils/firewall/client.go
  cmd/server/docs/docs.go
  cmd/server/docs/swagger.json
  cmd/server/docs/swagger.yaml
  frontend/src/api/interface/host.ts
  frontend/src/api/modules/host.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/host/ssh/log/analysis/index.vue
  frontend/src/views/host/ssh/log/log.vue
  frontend/src/views/setting/panel/default-network/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2361 feat: 面板系统日志增加日期选择，支持追踪读取
  backend/app/api/v1/logs.go
  backend/app/service/logs.go
  backend/app/service/ssh.go
  backend/router/ro_log.go
  cmd/server/docs/docs.go
  cmd/server/docs/swagger.json
  cmd/server/docs/swagger.yaml
  frontend/src/api/modules/log.ts
  frontend/src/styles/common.scss
  frontend/src/views/log/login/index.vue
  frontend/src/views/log/operation/index.vue
  frontend/src/views/log/system/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2364 feat: 容器镜像列表增加是否使用标签
  backend/app/dto/image.go
  backend/app/service/image.go
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/container/image/index.vue
  frontend/src/views/container/image/prune/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2370 feat: 容器镜像增加详情展示
  backend/app/service/container.go
  frontend/src/views/container/container/index.vue
  frontend/src/views/container/image/index.vue
  frontend/src/views/container/image/prune/index.vue
  frontend/src/views/container/network/index.vue
  frontend/src/views/container/volume/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2371 feat: 容器列表资源使用率增加详情显示
  backend/app/dto/container.go
  backend/app/service/container.go
  frontend/src/api/interface/container.ts
  frontend/src/assets/iconfont/iconfont.css
  frontend/src/assets/iconfont/iconfont.js
  frontend/src/assets/iconfont/iconfont.json
  frontend/src/assets/iconfont/iconfont.svg
  frontend/src/assets/iconfont/iconfont.ttf
  frontend/src/assets/iconfont/iconfont.woff
  frontend/src/assets/iconfont/iconfont.woff2
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/container/container/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2369 feat: 防火墙范围端口规则显示占用详情
  backend/app/service/firewall.go
  backend/utils/firewall/client/info.go
  frontend/src/styles/common.scss
  frontend/src/views/host/firewall/port/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2380 Update .gitignore
  .gitignore
Labels: do-not-merge/release-note-label-needed, dev

#2381 Delete .DS_Store
  .DS_Store
Labels: do-not-merge/release-note-label-needed

#2378 feat: 容器创建替换可输入选择框
  frontend/src/api/interface/container.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/container/container/operate/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2390 feat: 运行环境增加 Node.js 管理
  backend/app/api/v1/runtime.go
  backend/app/dto/request/runtime.go
  backend/app/dto/response/runtime.go
  backend/app/model/runtime.go
  backend/app/service/app.go
  backend/app/service/runtime.go
  backend/app/service/runtime_utils.go
  backend/constant/errs.go
  backend/constant/runtime.go
  backend/i18n/lang/en.yaml
  backend/i18n/lang/zh-Hant.yaml
  backend/i18n/lang/zh.yaml
  backend/init/migration/migrate.go
  backend/init/migration/migrations/v_1_7.go
  backend/router/ro_runtime.go
  cmd/server/docs/docs.go
  cmd/server/docs/swagger.json
  cmd/server/docs/swagger.yaml
  frontend/src/api/interface/runtime.ts
  frontend/src/api/modules/runtime.ts
  frontend/src/components/file-list/index.vue
  frontend/src/components/status/index.vue
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/routers/modules/website.ts
  frontend/src/views/app-store/apps/index.vue
  frontend/src/views/website/runtime/delete/index.vue
  frontend/src/views/website/runtime/index.vue
  frontend/src/views/website/runtime/node/create/index.vue
  frontend/src/views/website/runtime/node/index.vue
  frontend/src/views/website/runtime/node/operate/index.vue
  frontend/src/views/website/runtime/php/create/index.vue
  frontend/src/views/website/runtime/php/edit/index.vue
  frontend/src/views/website/runtime/php/index.vue
  frontend/src/views/website/runtime/php/param/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2394 feat: Node.js 环境增加启动、停止、重启操作
  backend/app/api/v1/app.go
  backend/app/api/v1/runtime.go
  backend/app/dto/request/app.go
  backend/app/dto/request/runtime.go
  backend/app/service/app.go
  backend/app/service/runtime.go
  backend/app/service/runtime_utils.go
  backend/constant/runtime.go
  backend/i18n/lang/en.yaml
  backend/i18n/lang/zh-Hant.yaml
  backend/i18n/lang/zh.yaml
  backend/router/ro_runtime.go
  backend/utils/docker/docker.go
  cmd/server/docs/docs.go
  cmd/server/docs/swagger.json
  cmd/server/docs/swagger.yaml
  frontend/src/api/interface/runtime.ts
  frontend/src/api/modules/runtime.ts
  frontend/src/components/status/index.vue
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/app-store/apps/index.vue
  frontend/src/views/app-store/detail/index.vue
  frontend/src/views/website/runtime/node/create/index.vue
  frontend/src/views/website/runtime/node/index.vue
  frontend/src/views/website/runtime/node/operate/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2403 feat: 已安装应用增加日志页面
  backend/app/api/v1/container.go
  backend/app/service/container.go
  backend/app/service/container_compose.go
  backend/app/service/runtime_utils.go
  backend/router/ro_container.go
  cmd/server/docs/docs.go
  cmd/server/docs/swagger.json
  cmd/server/docs/swagger.yaml
  frontend/.env
  frontend/src/components/compose-log/index.vue
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/app-store/installed/index.vue
  frontend/src/views/website/runtime/node/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2407 feat: Node.js 运行环境增加端口校验
  backend/app/api/v1/container.go
  backend/app/dto/request/runtime.go
  backend/app/dto/response/runtime.go
  backend/app/model/runtime.go
  backend/app/repo/runtime.go
  backend/app/service/app_utils.go
  backend/app/service/runtime.go
  backend/app/service/runtime_utils.go
  backend/i18n/lang/en.yaml
  backend/i18n/lang/zh-Hant.yaml
  backend/i18n/lang/zh.yaml
  backend/init/migration/migrations/v_1_7.go
  frontend/src/api/interface/runtime.ts
  frontend/src/views/app-store/installed/index.vue
  frontend/src/views/website/runtime/node/index.vue
  frontend/src/views/website/runtime/node/operate/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2410 feat: 网站主域名支持域名：端口
  backend/app/service/website.go
  frontend/src/global/form-rules.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/website/website/create/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2402 feat: 增加系统临时文件清理功能
  backend/app/api/v1/setting.go
  backend/app/dto/setting.go
  backend/app/repo/cronjob.go
  backend/app/service/setting.go
  backend/app/service/setting_clean.go
  backend/init/migration/migrations/v_1_7.go
  backend/router/ro_setting.go
  cmd/server/docs/docs.go
  cmd/server/docs/swagger.json
  cmd/server/docs/swagger.yaml
  frontend/src/api/interface/setting.ts
  frontend/src/api/modules/setting.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/setting/panel/clean/index.vue
  frontend/src/views/setting/panel/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2411 feat: 两步验证支持设置标题，区分系统
  backend/app/api/v1/setting.go
  backend/app/dto/auth.go
  backend/router/ro_setting.go
  backend/utils/mfa/mfa.go
  cmd/server/docs/docs.go
  cmd/server/docs/swagger.json
  cmd/server/docs/swagger.yaml
  frontend/src/api/interface/setting.ts
  frontend/src/api/modules/setting.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/setting/safe/mfa/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2413 feat: Demo 环境白名单增加部分放行接口
  backend/middleware/demo_handle.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#2415 feat: 缓存清理增加上传下载检查项
  backend/app/service/setting_clean.go
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/setting/panel/clean/index.vue
  frontend/src/views/setting/panel/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved
