Repository 1Panel-dev/1Panel, pull requests merged in 2023-07, with the labels that each got.

#1497 feat: 增加繁体中文适配
  backend/i18n/i18n.go
  backend/i18n/lang/zh-Hant.yaml
  frontend/src/api/index.ts
  frontend/src/lang/index.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/layout/components/Sidebar/index.vue
  frontend/src/store/interface/index.ts
  frontend/src/views/app-store/apps/index.vue
  frontend/src/views/app-store/detail/index.vue
  frontend/src/views/app-store/detail/params/index.vue
  frontend/src/views/app-store/installed/detail/index.vue
  frontend/src/views/home/app/index.vue
  frontend/src/views/log/operation/index.vue
  frontend/src/views/setting/panel/index.vue
  frontend/src/views/website/runtime/edit/index.vue
  frontend/src/views/website/runtime/param/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1509 feat: sftp 去掉重复的备份文件夹
  backend/utils/cloud_storage/client/onedrive.go
  frontend/src/views/setting/backup-account/index.vue
  frontend/src/views/setting/backup-account/operate/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1510 fix: 解决本地应用删除版本文件夹，页面版本没有删除的问题
  backend/app/service/app.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1511 feat: 证书申请延长超时时间
  frontend/src/api/modules/website.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1513 fix: OneDrive 增加操作描述信息
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/setting/backup-account/operate/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1515 feat: 增加应用忽略升级功能
  backend/app/api/v1/app_install.go
  backend/app/dto/request/app.go
  backend/app/model/app_detail.go
  backend/app/service/app_install.go
  backend/app/service/app_utils.go
  backend/init/migration/migrate.go
  backend/init/migration/migrations/init.go
  backend/router/ro_app.go
  cmd/server/docs/docs.go
  cmd/server/docs/swagger.json
  cmd/server/docs/swagger.yaml
  frontend/src/api/modules/app.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/app-store/installed/index.vue
  frontend/src/views/app-store/installed/upgrade/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1516 feat: 主机密码加密存储
  backend/app/api/v1/host.go
  backend/app/service/host.go
  backend/init/migration/migrate.go
  backend/init/migration/migrations/init.go
  backend/router/ro_host.go
  backend/server/server.go
  backend/utils/encrypt/encrypt.go
  cmd/server/docs/docs.go
  cmd/server/docs/swagger.json
  cmd/server/docs/swagger.yaml
  frontend/src/api/modules/host.ts
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1517 feat: 应用安装增加镜像拉取
  backend/app/service/app_utils.go
  backend/constant/app.go
  backend/i18n/lang/en.yaml
  backend/i18n/lang/zh-Hant.yaml
  backend/i18n/lang/zh.yaml
  backend/utils/docker/compose.go
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/app-store/detail/params/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1519 fix: 计划任务、容器创建样式移动端适配
  frontend/src/styles/common.scss
  frontend/src/styles/moblie.scss
  frontend/src/views/container/container/operate/index.vue
  frontend/src/views/cronjob/operate/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1520 feat: 应用增加跳转功能
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/utils/util.ts
  frontend/src/views/app-store/installed/index.vue
  frontend/src/views/container/container/index.vue
  frontend/src/views/database/mysql/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1525 fix: 解决 SSH 会话在多个连接下显示错误的问题
  backend/app/service/app_utils.go
  backend/utils/websocket/process_data.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1526 fix: 解决进程搜索为空一直转圈的问题
  backend/app/api/v1/file.go
  frontend/src/views/host/process/process/index.vue
  frontend/src/views/host/ssh/session/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1528 fix: 解决网站删除密码访问后，无法关闭密码访问的问题
  backend/app/service/website.go
  frontend/src/layout/components/Sidebar/components/Collapse.vue
  frontend/src/styles/element-dark.scss
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1530 feat: 网站选择证书可以通过 acme 账号过滤
  backend/app/api/v1/website_ssl.go
  backend/app/dto/request/website_ssl.go
  backend/app/service/website_ssl.go
  frontend/src/api/interface/website.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/website/website/config/basic/https/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1529 fix: 备份账号 OneDrive 绑定逻辑修改
  backend/app/api/v1/backup.go
  backend/app/service/backup.go
  backend/configs/system.go
  backend/constant/backup.go
  backend/init/hook/hook.go
  backend/init/migration/migrations/init.go
  backend/router/ro_setting.go
  backend/utils/cloud_storage/client/onedrive.go
  cmd/server/docs/docs.go
  cmd/server/docs/swagger.json
  cmd/server/docs/swagger.yaml
  frontend/src/api/modules/setting.ts
  frontend/src/views/setting/backup-account/operate/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1531 fix: 容器镜像升级样式调整
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/container/container/upgrade/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1532 feat: 优化文件选择逻辑
  frontend/src/components/file-list/index.vue
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/app-store/apps/index.vue
  frontend/src/views/host/ssh/index.vue
  frontend/src/views/host/ssh/session/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1533 fix: 容器端口跳转样式调整
  backend/app/service/container.go
  frontend/src/components/port-jump/index.vue
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/utils/util.ts
  frontend/src/views/app-store/installed/index.vue
  frontend/src/views/container/container/index.vue
  frontend/src/views/container/container/operate/index.vue
  frontend/src/views/cronjob/operate/index.vue
  frontend/src/views/database/mysql/index.vue
  frontend/src/views/database/redis/index.vue
  frontend/src/views/host/firewall/ip/operate/index.vue
  frontend/src/views/host/firewall/port/operate/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1535 feat: 应用创建增加 cpu 和内存最大值提示
  backend/app/service/website_ssl.go
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/app-store/detail/install/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1540 fix: 主机密码回显解密
  backend/app/api/v1/host.go
  backend/app/service/host.go
  backend/init/migration/migrations/init.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1541 fix: 修改 Mysql 数据库长度限制
  frontend/src/global/form-rules.ts
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1542 fix: 随机密码按钮样式统一修改
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/database/mysql/create/index.vue
  frontend/src/views/database/mysql/root-password/index.vue
  frontend/src/views/database/redis/password/index.vue
  frontend/src/views/host/ssh/ssh/pubkey/index.vue
  frontend/src/views/setting/safe/entrance/index.vue
  frontend/src/views/website/website/config/basic/auth-basic/create/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1544 fix: 解决数据库文件不存在时启用失败的问题
  backend/init/hook/hook.go
  backend/init/migration/migrations/init.go
  backend/server/server.go
  cmd/server/cmd/user-info.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1543 feat: 证书手动导入增加选择本地文件
  backend/app/dto/request/website.go
  backend/app/service/website.go
  backend/i18n/lang/en.yaml
  backend/i18n/lang/zh-Hant.yaml
  backend/i18n/lang/zh.yaml
  frontend/src/api/interface/app.ts
  frontend/src/components/file-list/index.vue
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/website/website/config/basic/https/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1546 fix: 解决容器编辑无法编辑名称的问题
  backend/app/dto/container.go
  backend/app/service/container.go
  frontend/src/api/interface/container.ts
  frontend/src/views/container/container/operate/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1549 feat: 内存限制提示保留2位小数
  frontend/src/views/app-store/detail/install/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1550 fix: 修改重名容器校验规则
  backend/app/service/container.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1551 fix: 容器 CPU 限制上限改为机器逻辑核心数
  backend/app/service/container.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1558 fix: 解决重复创建编排导致来源显示错误的问题
  backend/app/repo/compose_template.go
  backend/app/service/container_compose.go
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/container/compose/create/index.vue
  frontend/src/views/container/compose/detail/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1559 fix: 忽略监控采集的异常数据
  backend/app/service/monitor.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1560 fix: 解决备份账号修改备份路径失败的问题
  backend/app/dto/backup.go
  backend/app/dto/setting.go
  backend/app/service/backup.go
  frontend/src/views/setting/backup-account/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1562 fix: 计划任务报告仅在移动端显示滚动条
  frontend/src/views/container/compose/create/index.vue
  frontend/src/views/container/image/load/index.vue
  frontend/src/views/container/image/save/index.vue
  frontend/src/views/cronjob/operate/index.vue
  frontend/src/views/cronjob/record/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1563 fix: 消息弹框样式调整
  frontend/src/utils/message.ts
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1564 feat: 应用同步优化
  backend/app/service/app_install.go
  backend/app/service/app_utils.go
  backend/i18n/lang/en.yaml
  backend/i18n/lang/zh-Hant.yaml
  backend/i18n/lang/zh.yaml
  backend/utils/compose/compose.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1565 feat: 优化容器界面加载速度
  backend/app/api/v1/app_install.go
  backend/app/api/v1/backup.go
  backend/app/api/v1/compose_template.go
  backend/app/api/v1/container.go
  backend/app/api/v1/database_mysql.go
  backend/app/api/v1/file.go
  backend/app/api/v1/host.go
  backend/app/api/v1/image.go
  backend/app/api/v1/image_repo.go
  backend/app/api/v1/nginx.go
  backend/app/api/v1/website.go
  backend/app/api/v1/website_ssl.go
  backend/app/dto/container.go
  backend/app/service/container.go
  backend/router/ro_container.go
  cmd/server/docs/docs.go
  cmd/server/docs/swagger.json
  cmd/server/docs/swagger.yaml
  frontend/src/api/interface/container.ts
  frontend/src/api/modules/container.ts
  frontend/src/views/container/container/index.vue
  frontend/src/views/home/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1566 feat: 增加忽略应用列表和取消忽略功能
  backend/app/api/v1/app.go
  backend/app/dto/request/app.go
  backend/app/dto/response/app.go
  backend/app/repo/app_detail.go
  backend/app/service/app.go
  backend/app/service/app_install.go
  backend/router/ro_app.go
  cmd/server/docs/docs.go
  cmd/server/docs/swagger.json
  cmd/server/docs/swagger.yaml
  frontend/src/api/interface/app.ts
  frontend/src/api/modules/app.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/app-store/installed/ignore/index.vue
  frontend/src/views/app-store/installed/index.vue
  go.mod
  go.sum
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1571 fix: 增加终端连接断开提示信息
  frontend/src/components/terminal/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1572 fix: 解决终端字体大小变化时内容显示不全的问题
  frontend/src/components/terminal/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1573 feat: 修改参数
  backend/app/service/app_install.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1575 fix: 系统正则兼容 ipv6
  frontend/src/components/port-jump/index.vue
  frontend/src/global/form-rules.ts
  frontend/src/utils/util.ts
  frontend/src/views/container/container/operate/index.vue
  frontend/src/views/host/firewall/ip/operate/index.vue
  frontend/src/views/host/firewall/port/operate/index.vue
  frontend/src/views/host/ssh/ssh/address/index.vue
  frontend/src/views/setting/panel/systemip/index.vue
  frontend/src/views/setting/safe/allowips/index.vue
  frontend/src/views/website/website/config/safety/simple-list/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1576 fix: 解决计划任务执行周期显示错误的问题
  frontend/src/views/cronjob/index.vue
  frontend/src/views/cronjob/record/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1580 fix: 解决容器 label 或者 env 为空导致无法编辑的问题
  frontend/src/api/modules/container.ts
  frontend/src/views/container/container/operate/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1581 feat: 应用创建增加端口的检测范围
  backend/app/service/app.go
  backend/app/service/app_utils.go
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/app-store/apps/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1582 feat: 容器创建编辑支持自定义网络
  backend/app/api/v1/container.go
  backend/app/dto/container.go
  backend/app/service/container.go
  backend/app/service/container_network.go
  backend/router/ro_container.go
  cmd/server/docs/docs.go
  cmd/server/docs/swagger.json
  cmd/server/docs/swagger.yaml
  frontend/src/api/interface/container.ts
  frontend/src/api/modules/container.ts
  frontend/src/views/container/container/operate/index.vue
  frontend/src/views/container/volume/create/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1590 fix: 解决容器参数修改失败的问题
  backend/app/dto/container.go
  backend/app/service/container.go
  frontend/package-lock.json
  frontend/package.json
  frontend/src/global/form-rules.ts
  frontend/src/views/container/container/operate/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1591 feat: 修改端口检测规则
  backend/app/service/app.go
  backend/app/service/app_utils.go
  frontend/src/views/host/process/network/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1594 fix: 空数据国际化调整
  frontend/src/components/codemirror-dialog/index.vue
  frontend/src/components/container-log/index.vue
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/container/container/log/index.vue
  frontend/src/views/container/template/detail/index.vue
  frontend/src/views/database/mysql/setting/index.vue
  frontend/src/views/database/redis/setting/index.vue
  frontend/src/views/log/system/index.vue
  frontend/src/views/website/website/config/resource/nginx/index.vue
  frontend/src/views/website/website/config/resource/php-fpm/index.vue
  frontend/src/views/website/website/nginx/source/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1596 feat: 优化应用商店页面打开速度
  backend/app/service/app.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1592 feat: 日志审计-网站日志增加下载和追踪功能
  frontend/src/components/container-log/index.vue
  frontend/src/styles/common.scss
  frontend/src/utils/util.ts
  frontend/src/views/container/container/log/index.vue
  frontend/src/views/database/mysql/setting/slow-log/index.vue
  frontend/src/views/log/website/index.vue
  frontend/src/views/website/website/config/log/log-fiile/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1595 feat: 优化进程管理的页面打开速度
  backend/utils/websocket/process_data.go
  frontend/src/views/host/process/process/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1597 feat: 容器创建编辑增加拉取最新镜像选项
  backend/app/dto/container.go
  backend/app/service/container.go
  backend/app/service/container_network.go
  backend/app/service/container_volume.go
  frontend/src/api/interface/container.ts
  frontend/src/api/modules/container.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/container/container/index.vue
  frontend/src/views/container/container/operate/index.vue
  frontend/src/views/container/container/upgrade/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1602 fix: 强制拉取镜像样式调整
  frontend/src/global/form-rules.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/container/container/index.vue
  frontend/src/views/container/container/operate/index.vue
  frontend/src/views/container/container/upgrade/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1603 fix: 解决备份账号列表下载失败的问题
  backend/app/service/backup.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1604 fix: 解决网站备份路径问题
  backend/app/service/cronjob_helper.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1605 fix: 修改 mfa 最大刷新时间限制
  frontend/src/views/setting/safe/mfa/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm

#1606 fix: 暗色样式调整
  frontend/src/styles/element-dark.scss
  frontend/src/views/host/terminal/terminal/index.vue
  frontend/src/views/setting/safe/mfa/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1607 feat: 文件上传优化
  backend/app/api/v1/file.go
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/host/file-management/upload/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1609 feat: 修改用户名校验提示
  backend/app/service/website.go
  backend/i18n/lang/en.yaml
  backend/i18n/lang/zh-Hant.yaml
  backend/i18n/lang/zh.yaml
  frontend/src/global/form-rules.ts
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1608 fix: 解决计划任务保存份数错误的问题
  backend/app/service/cronjob_helper.go
  backend/utils/cloud_storage/client/onedrive.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1611 fix: 释放 echarts 资源
  frontend/src/components/v-charts/components/Line.vue
  frontend/src/views/home/index.vue
  frontend/src/views/home/status/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1615 fix: 解决容器编辑时端口冲突的问题
  backend/app/service/container.go
  backend/app/service/monitor.go
  frontend/src/components/container-log/index.vue
  frontend/src/components/port-jump/index.vue
  frontend/src/views/container/container/log/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1616 fix: 计划任务详情页删除时刷新选中值
  backend/app/service/cronjob_helper.go
  frontend/src/views/cronjob/record/index.vue
Labels: dev, lgtm, approved

#1618 feat: 限制 mysql 5.6.51 版本的升级
  backend/app/service/app_utils.go
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/host/file-management/decompress/index.vue
  frontend/src/views/website/website/config/safety/simple-list/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1619 fix: 增加备份超时时间
  backend/app/service/cronjob_helper.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1620 fix: 容器列表样式调整
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/container/container/index.vue
  frontend/src/views/container/container/operate/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1622 fix: 异常监控数据增加日志打印
  backend/app/service/monitor.go
  backend/app/service/snapshot.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1624 fix: 解决部分升级失败的问题
  backend/init/migration/migrations/init.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1627 feat: 取消 openresty 安装时的端口开放提示
  frontend/src/views/app-store/detail/install/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1629 fix: 解决网站设置 HTTPS 证书显示错误的问题
  frontend/src/views/website/website/config/basic/https/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1639 fix: 修改部分国际化问题
  backend/i18n/lang/en.yaml
  backend/i18n/lang/zh-Hant.yaml
  backend/i18n/lang/zh.yaml
  frontend/src/views/container/container/index.vue
  frontend/src/views/home/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1640 fix: 解决概览页多磁盘刷新问题
  frontend/src/views/home/index.vue
  frontend/src/views/home/status/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1638 fix: 解决面板设置无法选择 https 证书的问题
  backend/app/dto/request/website_ssl.go
  backend/app/service/website_ssl.go
  cmd/server/docs/docs.go
  cmd/server/docs/swagger.json
  cmd/server/docs/swagger.yaml
  frontend/src/api/interface/website.ts
  frontend/src/views/website/website/config/basic/https/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1645 fix: 解决部分容器编辑无法正常打开的问题
  frontend/src/views/container/container/operate/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1644 fix: 解决某些情况下应用状态异常的问题
  backend/app/service/app_install.go
  backend/app/service/app_utils.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1649 fix: 网站上传备份逻辑调整
  backend/app/service/backup_website.go
  backend/constant/errs.go
  backend/i18n/lang/en.yaml
  backend/i18n/lang/zh-Hant.yaml
  backend/i18n/lang/zh.yaml
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1651 fix: 优化监控页面echart资源释放
  frontend/src/views/host/monitor/monitor/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved

#1653 fix: 修复当网站主域名与网站目录不一致时，定时任务切割网站日志失败
  backend/app/service/cronjob_helper.go
Labels: do-not-merge/release-note-label-needed

#1663 fix: 优化暗色背景下禁用按钮样式
  frontend/src/styles/element-dark.scss
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1658 feat: 基本名称名称长度限制增加到 128
  frontend/src/global/form-rules.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1659 feat: 修复当网站主域名与网站目录不一致时，定时任务切割网站日志失败的问题
  backend/app/service/cronjob_helper.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1664 fix: 解决监控数据异常导致溢出的问题
  backend/app/service/monitor.go
Labels: do-not-merge/release-note-label-needed, dev

#1666 fix: 解决网站停止之后再启动运行目录错误的问题
  backend/app/service/website_utils.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1667 style: 文件列表增加操作列宽度
  frontend/src/views/host/file-management/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1668 Pr@dev@dan
  frontend/src/styles/element-dark.scss
  frontend/src/views/host/monitor/monitor/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1670 fix: 修改部分国际化内容
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/views/app-store/installed/index.vue
  frontend/src/views/website/website/config/basic/anti-Leech/index.vue
  frontend/src/views/website/website/config/basic/other/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1669 fix: 修改部分国际化内容
  frontend/src/lang/modules/en.ts
  frontend/src/views/container/repo/index.vue
  frontend/src/views/cronjob/index.vue
  frontend/src/views/host/ssh/ssh/index.vue
  frontend/src/views/host/ssh/ssh/port/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1671 fix: 解决概览页左右高度不一致的问题
  frontend/src/views/home/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1673 fix: 优化echart线状图表
  frontend/src/components/v-charts/components/Line.vue
  frontend/src/styles/common.scss
  frontend/src/views/host/monitor/monitor/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1675 fix: 解决主机密钥无法正常连接终端的问题
  backend/app/api/v1/host.go
  backend/app/service/host.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1689 fix: 优化首页对齐问题
  frontend/src/views/home/app/index.vue
  frontend/src/views/home/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1690 fix: 解决部分接口命令注入问题
  backend/app/service/container.go
  backend/app/service/container_compose.go
  backend/app/service/database_mysql.go
  backend/app/service/firewall.go
  backend/app/service/image_repo.go
  backend/app/service/ssh.go
  backend/constant/errs.go
  backend/i18n/lang/en.yaml
  backend/i18n/lang/zh-Hant.yaml
  backend/i18n/lang/zh.yaml
  backend/utils/firewall/client/firewalld.go
  backend/utils/firewall/client/ufw.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1691 fix: 本地连接失败时，打开添加主机抽屉
  frontend/src/views/host/terminal/terminal/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1695 fix: 解决容器创建端口选择 ipv6 校验问题
  frontend/src/views/container/container/operate/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1696 fix: 国际化内容补全
  frontend/src/lang/modules/tw.ts
  frontend/src/views/host/terminal/terminal/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1705 feat: php 网站禁用函数支持输入下划线
  frontend/src/global/form-rules.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1707 feat: 网站已安装页面增加分页
  backend/app/service/app_install.go
  frontend/src/views/app-store/apps/index.vue
  frontend/src/views/app-store/index.scss
  frontend/src/views/app-store/installed/index.vue
Labels: dev, lgtm, approved

#1708 fix: 修复首页高度对齐问题
  frontend/src/views/home/app/index.vue
  frontend/src/views/home/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1709 fix: 优化首页样式
  frontend/src/views/home/app/index.vue
  frontend/src/views/home/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1710 fix: 快速命令增加提示信息
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/host/terminal/command/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1721 Pr@dev@dan
  frontend/src/components/v-charts/components/Line.vue
  frontend/src/components/v-charts/components/Pie.vue
  frontend/src/components/v-charts/index.vue
  frontend/src/styles/common.scss
  frontend/src/views/home/status/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1731 feat: 网站增加重定向功能
  backend/app/api/v1/website.go
  backend/app/dto/request/nginx.go
  backend/app/dto/request/website.go
  backend/app/dto/response/nginx.go
  backend/app/service/website.go
  backend/router/ro_website.go
  cmd/server/docs/docs.go
  cmd/server/docs/swagger.json
  cmd/server/docs/swagger.yaml
  frontend/src/api/interface/website.ts
  frontend/src/api/modules/website.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/website/website/config/basic/index.vue
  frontend/src/views/website/website/config/basic/redirect/create/index.vue
  frontend/src/views/website/website/config/basic/redirect/file/index.vue
  frontend/src/views/website/website/config/basic/redirect/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1732 feat: 优化网站 IPV6 设置
  backend/app/service/website.go
  backend/app/service/website_utils.go
  backend/utils/nginx/components/server.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1745 feat: 增加远程数据库提示信息
  backend/utils/mysql/client.go
  backend/utils/mysql/client/info.go
  backend/utils/mysql/client/local.go
  backend/utils/mysql/client/remote.go
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/database/mysql/create/index.vue
  frontend/src/views/database/mysql/index.vue
  frontend/src/views/database/mysql/remote/index.vue
  frontend/src/views/database/mysql/remote/operate/index.vue
  go.mod
  go.sum
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1750 feat: 升级应用增加备份选项
  backend/app/dto/request/app.go
  backend/app/service/app_install.go
  backend/app/service/app_utils.go
  backend/i18n/lang/en.yaml
  backend/i18n/lang/zh-Hant.yaml
  backend/i18n/lang/zh.yaml
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/app-store/installed/upgrade/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1752 feat: 登录页增加语言选项
  backend/app/api/v1/auth.go
  backend/app/dto/auth.go
  backend/app/service/auth.go
  backend/router/ro_base.go
  cmd/server/docs/docs.go
  cmd/server/docs/swagger.json
  cmd/server/docs/swagger.yaml
  frontend/src/api/modules/auth.ts
  frontend/src/views/login/components/login-form.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1753 feat: 文件列表记录最后一次位置
  frontend/src/store/index.ts
  frontend/src/store/interface/index.ts
  frontend/src/views/host/file-management/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1772 fix DatabaseMysql 新增的 From字段 不允许为空 但未设置默认值 导致已存在数据库的1panel升级时无法正常启动
  backend/app/model/database_mysql.go
Labels: do-not-merge/release-note-label-needed

#1770 fix: 解决容器端口冲突导致创建失败的问题
  backend/app/service/container.go
  frontend/src/views/container/container/index.vue
  frontend/src/views/container/container/operate/index.vue
  frontend/src/views/container/image/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1774 feat: 实现远程数据备份恢复功能
  backend/app/dto/database.go
  backend/app/repo/remote_db.go
  backend/app/service/backup_app.go
  backend/app/service/backup_mysql.go
  backend/app/service/cronjob_helper.go
  backend/app/service/database_mysql.go
  backend/utils/mysql/client.go
  backend/utils/mysql/client/info.go
  backend/utils/mysql/client/local.go
  backend/utils/mysql/client/remote.go
  frontend/src/api/interface/database.ts
  frontend/src/views/cronjob/operate/index.vue
  frontend/src/views/database/mysql/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1775 feat: 数据库实现远程服务器获取功能
  backend/app/api/v1/database_mysql.go
  backend/app/api/v1/remote_db.go
  backend/app/model/database_mysql.go
  backend/app/service/database_mysql.go
  backend/app/service/remote_db.go
  backend/router/ro_database.go
  backend/utils/mysql/client.go
  backend/utils/mysql/client/info.go
  backend/utils/mysql/client/local.go
  backend/utils/mysql/client/remote.go
  frontend/src/api/modules/database.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/cronjob/operate/index.vue
  frontend/src/views/database/mysql/conn/index.vue
  frontend/src/views/database/mysql/index.vue
  frontend/src/views/database/mysql/password/index.vue
  frontend/src/views/database/mysql/remote/operate/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1776 fix: 兼容安装目录设置为根目录的情况
  backend/app/service/app_utils.go
  backend/app/service/backup_app.go
  backend/app/service/backup_mysql.go
  backend/app/service/backup_redis.go
  backend/app/service/backup_website.go
  backend/app/service/cronjob_helper.go
  backend/app/service/database_mysql.go
  backend/app/service/database_redis.go
  backend/app/service/setting.go
  backend/app/service/snapshot.go
  backend/app/service/website.go
  backend/init/viper/viper.go
  backend/server/server.go
  backend/utils/ssl/ssl.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm

#1780 perf: 移除不必要的 ssh session 连接
  backend/app/api/v1/terminal.go
Labels: do-not-merge/release-note-label-needed, lgtm, approved

#1777 fix: 创建抽屉隐藏名称显示
  frontend/src/components/drawer-header/index.vue
  frontend/src/views/container/container/operate/index.vue
  frontend/src/views/container/template/operator/index.vue
  frontend/src/views/cronjob/operate/index.vue
  frontend/src/views/database/mysql/remote/operate/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1778 fix: 面板设置支持设置服务器域名
  frontend/src/components/port-jump/index.vue
  frontend/src/global/form-rules.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/utils/util.ts
  frontend/src/views/container/volume/create/index.vue
  frontend/src/views/host/ssh/ssh/address/index.vue
  frontend/src/views/setting/panel/systemip/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1783 fix: 解决手动挂载的挂载卷在编辑时不显示的问题
  backend/app/service/container.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1785 fix: 解决 ssh 登录日志年份获取失败的问题
  backend/app/service/ssh.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1786 feat: 增加进程守护管理
  Makefile
  backend/app/api/v1/entry.go
  backend/app/api/v1/host_tool.go
  backend/app/dto/request/host_tool.go
  backend/app/dto/response/host_tool.go
  backend/app/service/host_tool.go
  backend/constant/host_tool.go
  backend/i18n/lang/en.yaml
  backend/i18n/lang/zh-Hant.yaml
  backend/i18n/lang/zh.yaml
  backend/router/ro_host.go
  backend/utils/ini_conf/ini.go
  backend/utils/systemctl/systemctl.go
  cmd/server/docs/docs.go
  cmd/server/docs/swagger.json
  cmd/server/docs/swagger.yaml
  frontend/src/api/interface/host-tool.ts
  frontend/src/api/modules/host-tool.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/routers/modules/host.ts
  frontend/src/views/host/tool/index.vue
  frontend/src/views/host/tool/supervisor/config/index.vue
  frontend/src/views/host/tool/supervisor/config/log/index.vue
  frontend/src/views/host/tool/supervisor/config/source/index.vue
  frontend/src/views/host/tool/supervisor/create/index.vue
  frontend/src/views/host/tool/supervisor/index.vue
  frontend/src/views/host/tool/supervisor/status/index.vue
  frontend/src/views/host/tool/supervisor/status/init/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#1795 fix: 修改监控默认采集间隔和保存时间
  backend/app/service/monitor.go
  backend/init/migration/migrations/init.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved
