Repository 1Panel-dev/1Panel, pull requests merged in 2024-06, with the labels that each got.

#5255 feat: 网站 access_log 使用主配置文件参数
  backend/app/service/website.go
  backend/app/service/website_utils.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5257 fix: 修改远程数据库排序问题
  backend/app/dto/database.go
  backend/app/service/database.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5259 pref: 优化登录页确认框样式
  backend/app/service/ftp.go
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/login/components/login-form.vue
  frontend/src/views/setting/panel/index.vue
Labels: do-not-merge/release-note-label-needed, dev

#5260 fix: 解决应用安装升级状态错误的问题
  backend/app/dto/response/app.go
  backend/app/service/app.go
  backend/app/service/app_install.go
  backend/app/service/app_utils.go
  frontend/src/api/interface/app.ts
  frontend/src/api/modules/app.ts
  frontend/src/views/app-store/installed/delete/index.vue
  frontend/src/views/app-store/installed/detail/index.vue
  frontend/src/views/app-store/installed/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5261 fix: 解决部分情况下升级版本不显示的问题
  backend/app/model/app.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5267 fix: 修改面板设置证书时间显示不一致的问题
  backend/app/dto/database.go
  backend/app/service/setting.go
  backend/app/service/website.go
  backend/utils/redis/redis.go
  backend/utils/toolbox/pure-ftpd.go
  frontend/src/routers/modules/host.ts
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5271 fix: 容器垃圾清理不展示细节下拉清除
  backend/app/service/device_clean.go
  frontend/src/assets/iconfont/iconfont.css
  frontend/src/assets/iconfont/iconfont.js
  frontend/src/assets/iconfont/iconfont.json
  frontend/src/assets/iconfont/iconfont.svg
  frontend/src/assets/iconfont/iconfont.ttf
  frontend/src/assets/iconfont/iconfont.woff
  frontend/src/assets/iconfont/iconfont.woff2
  frontend/src/views/toolbox/clean/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5258 feat: 压缩和解压缩 tar.gz 文件时支持设置压缩密码
  backend/app/dto/backup.go
  backend/app/dto/cronjob.go
  backend/app/dto/request/file.go
  backend/app/dto/setting.go
  backend/app/model/cronjob.go
  backend/app/service/app.go
  backend/app/service/app_utils.go
  backend/app/service/backup_app.go
  backend/app/service/backup_mysql.go
  backend/app/service/backup_postgresql.go
  backend/app/service/backup_redis.go
  backend/app/service/backup_runtime.go
  backend/app/service/backup_website.go
  backend/app/service/cornjob.go
  backend/app/service/cronjob_backup.go
  backend/app/service/cronjob_helper.go
  backend/app/service/file.go
  backend/app/service/snapshot.go
  backend/app/service/snapshot_create.go
  backend/app/service/snapshot_recover.go
  backend/app/service/upgrade.go
  backend/app/service/website_ssl.go
  backend/init/migration/migrate.go
  backend/init/migration/migrations/v_1_10.go
  backend/utils/files/archiver.go
  backend/utils/files/file_op.go
  backend/utils/files/tar.go
  backend/utils/files/tar_gz.go
  backend/utils/files/zip.go
  frontend/src/api/interface/backup.ts
  frontend/src/api/interface/cronjob.ts
  frontend/src/api/interface/file.ts
  frontend/src/api/interface/setting.ts
  frontend/src/components/backup/index.vue
  frontend/src/components/upload/index.vue
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/cronjob/operate/index.vue
  frontend/src/views/host/file-management/compress/index.vue
  frontend/src/views/host/file-management/decompress/index.vue
  frontend/src/views/setting/snapshot/index.vue
  frontend/src/views/setting/snapshot/status/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5274 feat: 应用升级支持对比 docker-compose 文件
  backend/app/api/v1/app_install.go
  backend/app/dto/app.go
  backend/app/dto/request/app.go
  backend/app/dto/response/app.go
  backend/app/service/app_install.go
  backend/app/service/app_utils.go
  backend/router/ro_app.go
  frontend/src/api/interface/app.ts
  frontend/src/api/modules/app.ts
  frontend/src/assets/images/theworld.png
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/main.ts
  frontend/src/views/app-store/installed/index.vue
  frontend/src/views/app-store/installed/upgrade/diff/index.vue
  frontend/src/views/app-store/installed/upgrade/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5277 fix: 解决表格超出隐藏显示不正确的问题
  frontend/src/views/container/compose/detail/index.vue
  frontend/src/views/container/compose/index.vue
  frontend/src/views/container/container/index.vue
  frontend/src/views/container/image/index.vue
  frontend/src/views/container/network/index.vue
  frontend/src/views/container/template/index.vue
  frontend/src/views/container/volume/index.vue
  frontend/src/views/cronjob/index.vue
  frontend/src/views/toolbox/ftp/index.vue
  frontend/src/views/toolbox/supervisor/index.vue
  frontend/src/views/website/runtime/node/index.vue
  frontend/src/views/website/runtime/php/index.vue
  frontend/src/views/website/website/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5281 style: 统一修改名称样式
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/routers/modules/container.ts
  frontend/src/views/container/compose/index.vue
  frontend/src/views/container/container/index.vue
  frontend/src/views/container/image/index.vue
  frontend/src/views/container/network/index.vue
  frontend/src/views/container/template/index.vue
  frontend/src/views/container/volume/index.vue
  frontend/src/views/cronjob/index.vue
  frontend/src/views/website/runtime/node/index.vue
  frontend/src/views/website/runtime/php/index.vue
  frontend/src/views/website/website/config/basic/https/index.vue
  frontend/src/views/website/website/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5282 fix: 解决自签证书关闭页面之后没有刷新的问题
  frontend/src/views/website/ssl/ca/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5283 fix: 优化 FTP 列表分页样式
  backend/app/service/ftp.go
  frontend/src/components/complex-table/index.vue
  frontend/src/views/toolbox/ftp/index.vue
  frontend/src/views/toolbox/ftp/log/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5285 fix: 解决登录页跳转空白的问题
  backend/app/api/v1/auth.go
  backend/middleware/bind_domain.go
  backend/middleware/helper.go
  backend/middleware/ip_limit.go
  backend/middleware/password_expired.go
  frontend/src/api/index.ts
  frontend/src/components/error-message/error_code.vue
  frontend/src/views/login/entrance/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5287 fix: 解决主题色切换报错的问题
  frontend/src/api/index.ts
  frontend/src/views/setting/panel/index.vue
  frontend/src/views/setting/panel/proxy/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5295 fix: 解决某些情况下安装应用错误没有正确显示的问题
  backend/app/service/app.go
  backend/app/service/app_install.go
  backend/app/service/app_utils.go
  backend/app/service/website.go
  backend/constant/app.go
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5296 fix: 解决不带密码压缩文件失败的问题
  backend/app/service/cronjob_helper.go
  backend/app/service/snapshot.go
  backend/app/service/snapshot_create.go
  backend/app/service/snapshot_recover.go
  backend/utils/files/tar_gz.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm

#5297 feat: 升级增加 docker-compose 文件对比功能
  frontend/src/assets/iconfont/iconfont.css
  frontend/src/assets/iconfont/iconfont.js
  frontend/src/assets/iconfont/iconfont.json
  frontend/src/assets/iconfont/iconfont.svg
  frontend/src/assets/iconfont/iconfont.ttf
  frontend/src/assets/iconfont/iconfont.woff
  frontend/src/assets/iconfont/iconfont.woff2
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/app-store/installed/upgrade/diff/index.vue
  frontend/src/views/app-store/installed/upgrade/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5298 fix: 解决开启代理时同步应用失败的问题
  backend/app/service/app.go
  backend/utils/files/file_op.go
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/toolbox/ftp/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5300 fix: 解决代理选项为空的问题
  frontend/src/api/modules/setting.ts
  frontend/src/views/setting/panel/proxy/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5301 fix: 修复编辑证书，秘钥算法没有回显的问题
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/website/ssl/create/index.vue
  frontend/src/views/website/website/config/basic/index.vue
  frontend/src/views/website/website/config/basic/site-folder/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5302 fix: 面板代理地址自动增加 http 或者 https
  frontend/src/views/setting/panel/proxy/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5303 fix: 修正 goreleaser v2 参数
  .github/workflows/build-test.yml
  .github/workflows/release-drafter.yml
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5304 feat: 限制 PHP 运行环境制作镜像中被删除
  frontend/src/views/website/runtime/php/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5309 fix: 解决删除网站没删除备份文件的问题
  backend/app/service/backup.go
  backend/app/service/website.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm

#5306 fix: 解决 HTTP 类型代理失败的问题
  backend/app/service/app.go
  backend/app/service/app_utils.go
  backend/app/service/snapshot.go
  backend/app/service/upgrade.go
  backend/init/migration/migrations/init.go
  backend/utils/http/request.go
  frontend/src/views/setting/panel/proxy/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5305 fix: 备份恢复弹框中增加输入压缩密码输入框
  frontend/src/components/backup/index.vue
  frontend/src/components/upload/index.vue
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/app-store/installed/backup/index.vue
  frontend/src/views/app-store/installed/recover/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5315 fix: 调整 Redis 空状态样式
  backend/utils/http/request.go
  frontend/src/views/database/redis/index.vue
  frontend/src/views/setting/panel/proxy/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5319 fix: 解决应用安装失败的问题
  backend/app/service/app.go
  backend/utils/http/get.go
  backend/utils/http/request.go
  backend/utils/xpack/xpack.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5320 fix: 文件返回前进功能优化
  frontend/src/views/host/file-management/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5322 fix: 解决压缩备份恢复失败的问题
  backend/app/service/backup_website.go
  backend/app/service/cronjob_helper.go
  backend/app/service/snapshot.go
  backend/utils/postgresql/client/local.go
  frontend/src/views/setting/snapshot/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5323 fix: 修改登录页弹框判断
  frontend/src/views/login/components/login-form.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5324 fix: 增加系统请求超时时间
  backend/app/service/app.go
  backend/app/service/app_install.go
  backend/app/service/app_utils.go
  backend/app/service/runtime_utils.go
  backend/app/service/upgrade.go
  backend/constant/common.go
  backend/utils/files/file_op.go
  backend/utils/http/request.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5325 pref: 加密备份代码优化
  backend/app/service/cronjob_helper.go
  backend/app/service/snapshot.go
  backend/app/service/snapshot_create.go
  backend/utils/files/tar_gz.go
  frontend/src/views/setting/snapshot/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5326 fix: 快照恢复弹框增加压缩密码输入框
  frontend/src/views/setting/snapshot/recover/index.vue
  frontend/src/views/setting/snapshot/status/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5327 fix: 解决应用已安装时间显示错误的问题
  backend/app/dto/response/app.go
  backend/app/service/app_utils.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5331 fix: 解决限制应用安装之后安装按钮还能点的问题
  backend/app/dto/response/app.go
  backend/app/service/app.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5332 fix: 解决 PostgreSQL 页面切换的样式问题
  backend/app/service/database_mysql.go
  backend/app/service/database_postgresql.go
  frontend/src/views/database/mysql/index.vue
  frontend/src/views/database/postgresql/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5335 fix: 解决自签证书开启自动续签报错的问题
  backend/app/dto/request/website_ssl.go
  backend/app/service/website_ssl.go
Labels: dev

#5337 style: 黑金主题样式优化
  frontend/src/components/system-upgrade/index.vue
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/styles/element-dark.scss
  frontend/src/views/host/file-management/index.vue
  frontend/src/views/setting/about/index.vue
  frontend/src/views/setting/backup-account/index.vue
  frontend/src/views/website/ssl/acme-account/create/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5345 fix: 修改部分黑金样式
  frontend/src/components/system-upgrade/index.vue
  frontend/src/views/setting/about/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5347 fix: 解决获取 SSL 信息错误的问题
  backend/app/service/setting.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5351 fix: 解决登录跳概览页时样式错误的问题
  frontend/src/layout/index.vue
  frontend/src/utils/xpack.ts
  frontend/src/views/login/components/login-form.vue
  frontend/src/views/login/entrance/index.vue
  frontend/src/views/login/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5352 fix: 修复应用升级文件对比显示问题
  frontend/src/views/app-store/installed/upgrade/diff/index.vue
  frontend/src/views/setting/about/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5354 添加Flarum的PHP扩展模板
  backend/init/migration/migrations/v_1_9.go
Labels: do-not-merge/release-note-label-needed

#5355 pref: 优化暗黑主题样式
  frontend/src/styles/element-dark.scss
  frontend/src/utils/xpack.ts
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5360 style: 黑金主题样式优化
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/app-store/installed/index.vue
  frontend/src/views/website/runtime/php/create/index.vue
  frontend/src/views/website/runtime/php/extensions/operate/index.vue
  frontend/src/views/website/website/config/basic/anti-Leech/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5402 fix: 解决深色模式下版本显示问题
  frontend/src/styles/element-dark.scss
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5383 fix: 修正未认证设置表单初始值
  frontend/src/views/setting/safe/index.vue
Labels: do-not-merge/release-note-label-needed

#5409 fix: 解决 gorm 的 sql 注入问题
  backend/app/api/v1/cronjob.go
  backend/app/dto/command.go
  backend/app/dto/common_req.go
  backend/app/dto/container.go
  backend/app/dto/cronjob.go
  backend/app/dto/database.go
  backend/app/dto/database_postgresql.go
  backend/app/dto/request/website.go
  backend/app/service/cornjob.go
  cmd/server/docs/docs.go
  cmd/server/docs/swagger.json
  cmd/server/docs/swagger.yaml
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5412 fix: 解决计划任务执行周期错误的问题
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/cronjob/helper.ts
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5413 fix: 解决升级页面 链接点击不跳转的问题
  backend/app/dto/response/app.go
  backend/app/service/app_utils.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5425 fix: 解决部分情况下打开文件中文乱码的问题
  backend/app/service/file.go
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5436 fix: 解决浏览器切换时部分设置未同步的问题
  frontend/src/utils/xpack.ts
  frontend/src/views/login/components/login-form.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5440 perf: 优化前端打包速度
  frontend/package.json
  frontend/src/components/terminal/index.vue
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/routers/router.ts
  frontend/src/typings/plugins.d.ts
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5442 fix: 修改终端全屏按钮样式
  frontend/src/utils/xpack.ts
  frontend/src/views/host/terminal/terminal/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5443 feat: 优化非80端口网站开启 https 端口配置
  backend/app/service/website_utils.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5445 fix: 解决应用安装 services 为空报系统错误的问题
  backend/app/service/app.go
  backend/app/service/app_utils.go
  backend/app/service/website_utils.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5446 feat: demo 环境适配网站监控
  backend/middleware/demo_handle.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5448 feat: 网站列表按照名称排序
  backend/app/service/website.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5449 fix: 解决界面设置主题色不统一的问题
  frontend/src/assets/images/favicon-gold.png
  frontend/src/assets/images/favicon.svg
  frontend/src/utils/xpack.ts
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5447 feat: 容器操作增加制作容器镜像功能
  backend/app/api/v1/container.go
  backend/app/dto/container.go
  backend/app/service/container.go
  backend/router/ro_container.go
  frontend/src/api/interface/container.ts
  frontend/src/api/modules/container.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/container/container/commit/index.vue
  frontend/src/views/container/container/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5458 feat: 续签证书不重置私钥
  backend/app/service/website_ssl.go
  frontend/src/views/website/ssl/create/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5460 feat: 更新 SSL 证书的加密算法
  cmd/server/nginx_conf/ssl.conf
  frontend/src/views/website/website/config/basic/https/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5439 feat: 端口转发功能
  backend/app/api/v1/firewall.go
  backend/app/dto/firewall.go
  backend/app/model/firewall.go
  backend/app/service/firewall.go
  backend/init/app/app.go
  backend/init/migration/migrate.go
  backend/init/migration/migrations/v_1_10.go
  backend/router/ro_host.go
  backend/utils/firewall/client.go
  backend/utils/firewall/client/firewalld.go
  backend/utils/firewall/client/info.go
  backend/utils/firewall/client/iptables.go
  backend/utils/firewall/client/ufw.go
  frontend/src/api/interface/host.ts
  frontend/src/api/modules/host.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/routers/modules/host.ts
  frontend/src/utils/util.ts
  frontend/src/views/host/firewall/forward/index.vue
  frontend/src/views/host/firewall/forward/operate/index.vue
  frontend/src/views/host/firewall/index.vue
Labels: do-not-merge/release-note-label-needed

#5482 feat: 进程守护日志支持全屏
  frontend/src/views/toolbox/supervisor/file/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5483 fix: 解决升级导致的计划任务未执行问题
  backend/app/service/cornjob.go
  backend/cron/cron.go
  frontend/src/components/system-upgrade/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5485 feat: 优化日志读取
  backend/app/dto/request/file.go
  backend/app/dto/response/file.go
  backend/app/service/file.go
  backend/app/service/website.go
  backend/utils/files/utils.go
  frontend/package.json
  frontend/src/components/log-file/index.vue
  frontend/src/main.ts
  frontend/src/views/website/website/config/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5486 feat: 文件编辑器支持网页全屏
  frontend/src/views/host/file-management/code-editor/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5488 feat: 网站列表增加证书过期时间显示
  backend/app/dto/response/website.go
  backend/app/service/website.go
  backend/app/service/website_utils.go
  frontend/src/api/interface/website.ts
  frontend/src/api/modules/website.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/website/website/config/basic/https/index.vue
  frontend/src/views/website/website/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5489 pref: 快照增加恢复前资源检查
  backend/app/dto/dashboard.go
  backend/app/dto/setting.go
  backend/app/service/dashboard.go
  backend/app/service/snapshot.go
  backend/app/service/snapshot_recover.go
  cmd/server/docs/docs.go
  cmd/server/docs/swagger.json
  cmd/server/docs/swagger.yaml
  frontend/src/api/interface/dashboard.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/database/redis/setting/persistence/index.vue
  frontend/src/views/setting/snapshot/index.vue
  frontend/src/views/setting/snapshot/recover/index.vue
  frontend/src/views/setting/snapshot/status/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5491 feat: 增加修改网站默认页面功能
  backend/app/api/v1/website.go
  backend/app/dto/request/website.go
  backend/app/dto/response/website.go
  backend/app/service/website.go
  backend/app/service/website_utils.go
  backend/router/ro_website.go
  cmd/server/nginx_conf/404.html
  cmd/server/nginx_conf/domain404.html
  cmd/server/nginx_conf/nginx_conf.go
  cmd/server/nginx_conf/stop.html
  frontend/package.json
  frontend/src/api/interface/website.ts
  frontend/src/api/modules/website.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/website/website/html/index.vue
  frontend/src/views/website/website/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5490 fix: 端口转发功能在ufw下重启面板导致Docker自带规则被清除
  backend/utils/firewall/client/iptables.go
  backend/utils/firewall/client/ufw.go
Labels: do-not-merge/release-note-label-needed

#5497 feat: 回收站文件支持批量还原
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/host/file-management/recycle-bin/index.vue
  frontend/src/views/host/file-management/recycle-bin/reduce/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5498 feat: 创建静态、PHP 网站默认增加 404 页面
  backend/app/service/website.go
  backend/app/service/website_utils.go
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/website/website/html/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5500 style: 优化申请证书 acme 账户显示
  frontend/src/utils/util.ts
  frontend/src/views/website/ssl/create/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5501 feat: 证书推送自动创建文件夹
  backend/app/service/website_ssl.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5502 docs: 修改 readme 中 UI 展示图片为可跳转到介绍
  README.md
Labels: do-not-merge/release-note-label-needed

#5503 chore: Update README.md
  README.md
Labels: do-not-merge/release-note-label-needed

#5504 feat: 优化网站 WAF 配置文件生成
  backend/app/service/website_utils.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5508 feat: 优化文件上传逻辑，减少临时空间占用
  backend/app/api/v1/file.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5509 feat: 优化文件解压，保留文件更新时间
  backend/utils/files/file_op.go
  frontend/src/components/log-file/index.vue
  frontend/src/views/website/runtime/php/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5517 feat: 申请证书成功之后支持执行脚本
  backend/app/dto/request/website_ssl.go
  backend/app/model/website_ssl.go
  backend/app/service/website_ca.go
  backend/app/service/website_ssl.go
  backend/i18n/lang/zh.yaml
  backend/init/migration/migrate.go
  backend/init/migration/migrations/v_1_10.go
  backend/utils/cmd/cmd.go
  frontend/src/api/interface/website.ts
  frontend/src/components/log-file/index.vue
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/website/ssl/ca/obtain/index.vue
  frontend/src/views/website/ssl/create/index.vue
  frontend/src/views/website/ssl/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5525 feat: 优化应用升级逻辑，避免镜像拉取成功之前容器被删除
  backend/app/service/app_utils.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5548 Update README.md
  README.md
Labels: do-not-merge/release-note-label-needed, dev

#5546 feat: 增加病毒扫描工具
  backend/app/api/v1/clam.go
  backend/app/api/v1/entry.go
  backend/app/dto/clam.go
  backend/app/model/clam.go
  backend/app/repo/clam.go
  backend/app/service/clam.go
  backend/app/service/cronjob.go
  backend/app/service/entry.go
  backend/init/migration/migrate.go
  backend/init/migration/migrations/v_1_10.go
  backend/router/ro_toolbox.go
  cmd/server/docs/docs.go
  cmd/server/docs/swagger.json
  cmd/server/docs/swagger.yaml
  frontend/src/api/interface/toolbox.ts
  frontend/src/api/modules/toolbox.ts
  frontend/src/components/error-message/error_code.vue
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/routers/modules/toolbox.ts
  frontend/src/views/database/mysql/setting/index.vue
  frontend/src/views/toolbox/clam/index.vue
  frontend/src/views/toolbox/clam/operate/index.vue
  frontend/src/views/toolbox/clam/record/index.vue
  frontend/src/views/toolbox/clam/setting/index.vue
  frontend/src/views/toolbox/clam/status/index.vue
  frontend/src/views/toolbox/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5547 fix: 解决面板主题跟随系统失效的问题
  frontend/src/utils/xpack.ts
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5551 chore: Update README.md
  README.md
Labels: do-not-merge/release-note-label-needed, dev

#5552 fix: 一些被忽略的句柄关闭问题
  backend/app/api/v1/website_ssl.go
  backend/app/service/docker.go
  backend/app/service/image_repo.go
  backend/app/service/ssh.go
  backend/init/db/db.go
  backend/utils/nginx/parser/parser.go
  backend/utils/toolbox/fail2ban.go
Labels: do-not-merge/release-note-label-needed

#5553 pref: 优化容器编排创建、镜像拉取等前端逻辑
  frontend/src/views/container/compose/create/index.vue
  frontend/src/views/container/image/build/index.vue
  frontend/src/views/container/image/pull/index.vue
  frontend/src/views/container/image/push/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5556 pref: 优化容器编排编辑逻辑
  backend/app/service/container_compose.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5555 fix: 增加系统主题变化监听事件
  frontend/src/hooks/use-theme.ts
  frontend/src/layout/index.vue
  frontend/src/store/modules/global.ts
  frontend/src/utils/xpack.ts
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5561 feat: 优化应用升级逻辑，拉取镜像失败无需回滚
  backend/app/service/app_utils.go
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/app-store/installed/upgrade/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5563 feat: 升级 lego 依赖
  go.mod
  go.sum
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5564 feat: 防火墙允许操作 ipv6
  backend/utils/firewall/client/firewalld.go
  backend/utils/firewall/client/ufw.go
  go.sum
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5557 feat: 容器日志下载优化
  backend/app/api/v1/container.go
  backend/app/dto/container.go
  backend/app/service/container.go
  backend/router/ro_container.go
  frontend/src/api/interface/container.ts
  frontend/src/api/modules/container.ts
  frontend/src/components/compose-log/index.vue
  frontend/src/views/container/container/log/index.vue
Labels: do-not-merge/release-note-label-needed, dev

#5571 fix: 镜像拉取同步系统认证信息
  backend/app/service/container.go
  backend/app/service/image.go
  backend/utils/postgresql/client/remote.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5575 fit: 文件属性显示大小值调整
  backend/utils/files/fileinfo.go
  frontend/src/views/host/file-management/detail/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5576 feat: 增加 java 运行环境
  backend/app/service/backup_website.go
  backend/app/service/runtime.go
  backend/app/service/runtime_utils.go
  backend/app/service/website.go
  backend/app/service/website_utils.go
  backend/constant/runtime.go
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/routers/modules/website.ts
  frontend/src/views/app-store/apps/index.vue
  frontend/src/views/website/runtime/index.vue
  frontend/src/views/website/runtime/java/index.vue
  frontend/src/views/website/runtime/java/operate/index.vue
  frontend/src/views/website/website/create/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm

#5572 feat: 文件管理增加使用 VS Code 打开
  frontend/src/components/vscode-open/index.vue
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/host/file-management/index.vue
Labels: do-not-merge/release-note-label-needed

#5578 fix: 解决备份密码特殊字符问题
  backend/app/service/cronjob_helper.go
  backend/app/service/snapshot.go
  backend/app/service/snapshot_create.go
  backend/utils/files/tar_gz.go
Labels: do-not-merge/release-note-label-needed

#5581 feat: 升级 golang.org/x/image
  go.mod
  go.sum
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5580 fix: 解决加密压缩文件解压失败的问题
  backend/app/service/file.go
  frontend/src/views/host/file-management/decompress/index.vue
  go.sum
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5583 fit: 文件显示大小值问题修复
  backend/utils/files/fileinfo.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5589 Update README.md
  README.md
Labels: do-not-merge/release-note-label-needed, dev

#5588 fit:replace ctx err equal check as error.is
  backend/utils/mysql/client.go
  backend/utils/mysql/client/local.go
  backend/utils/mysql/client/remote.go
  backend/utils/postgresql/client/local.go
  backend/utils/postgresql/client/remote.go
Labels: do-not-merge/release-note-label-needed

#5598 fit: 修复概览数据库数量显示错误问题
  backend/app/service/dashboard.go
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/home/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5601 style:fit some code style
  backend/app/dto/database.go
  backend/app/service/app_install.go
  backend/app/service/backup.go
  backend/app/service/backup_app.go
  backend/app/service/backup_mysql.go
  backend/app/service/backup_postgresql.go
  backend/app/service/backup_redis.go
  backend/app/service/backup_runtime.go
  backend/app/service/backup_website.go
  backend/app/service/clam.go
  backend/app/service/container.go
  backend/app/service/container_compose.go
  backend/app/service/cronjob.go
  backend/app/service/cronjob_backup.go
  backend/app/service/cronjob_helper.go
  backend/app/service/dashboard.go
  backend/app/service/database.go
  backend/app/service/database_mysql.go
  backend/app/service/device.go
  backend/app/service/device_clean.go
  backend/app/service/file.go
  backend/app/service/image.go
  backend/app/service/setting.go
  backend/app/service/snapshot.go
  backend/app/service/ssh.go
  backend/app/service/upgrade.go
  backend/constant/common.go
  backend/constant/website.go
  backend/cron/cron.go
  backend/init/migration/migrations/init.go
  backend/init/migration/migrations/v_1_9.go
  backend/middleware/password_expired.go
  backend/utils/cloud_storage/client/onedrive.go
  backend/utils/files/zip.go
  backend/utils/mysql/helper/dump.go
  backend/utils/mysql/helper/source.go
  backend/utils/toolbox/pure-ftpd.go
Labels: do-not-merge/release-note-label-needed

#5594 feat: 文件管理编辑文件增加左侧目录树
  backend/app/dto/response/file.go
  backend/app/service/file.go
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/host/file-management/code-editor/index.vue
  frontend/src/views/host/file-management/delete/index.vue
  frontend/src/views/host/file-management/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5602 feat: 文本编辑器支持更多语言
  frontend/src/global/mimetype.ts
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5603 chore: Update README.md
  README.md
Labels: do-not-merge/release-note-label-needed, dev

#5604 fix: 补全依赖
  backend/app/service/dashboard.go
  backend/app/service/device_clean.go
  backend/utils/files/zip.go
  backend/utils/mysql/helper/dump.go
  backend/utils/mysql/helper/source.go
Labels: do-not-merge/release-note-label-needed

#5605 fix: 解决 MariaDB 数据库同步失败的问题
  backend/app/service/database_mysql.go
  backend/app/service/database_postgresql.go
  backend/utils/mysql/client/local.go
  backend/utils/mysql/client/remote.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5606 移除前端打包时生成的gzip文件
  frontend/.env.development
  frontend/.env.production
Labels: do-not-merge/release-note-label-needed

#5608 chore: Update README.md
  README.md
Labels: do-not-merge/release-note-label-needed

#5609 Update v_1_9.go
  backend/init/migration/migrations/v_1_9.go
Labels: do-not-merge/release-note-label-needed
