Repository 1Panel-dev/1Panel, pull requests merged in 2024-12, with the labels that each got.

#7232 WIP: Refine English translation
  backend/i18n/lang/en.yaml
  frontend/src/components/app-status/index.vue
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/app-store/detail/install/index.vue
  frontend/src/views/website/website/create/index.vue
Labels: do-not-merge/release-note-label-needed, do-not-merge/work-in-progress

#7238 feat: merge from dev
  agent/app/dto/app.go
  agent/app/dto/dashboard.go
  agent/app/dto/request/website.go
  agent/app/dto/request/website_ssl.go
  agent/app/service/app.go
  agent/app/service/app_utils.go
  agent/app/service/dashboard.go
  agent/app/service/runtime.go
  agent/app/service/runtime_utils.go
  agent/app/service/website.go
  agent/app/service/website_ca.go
  agent/app/service/website_ssl.go
  agent/cmd/server/nginx_conf/proxy.conf
  agent/constant/runtime.go
  agent/cron/job/ssl.go
  agent/i18n/lang/en.yaml
  agent/i18n/lang/zh-Hant.yaml
  agent/i18n/lang/zh.yaml
  agent/middleware/demo_handle.go
  agent/server/server.go
  agent/utils/nginx/components/config.go
  agent/utils/xpack/xpack.go
  core/constant/common.go
  core/server/server.go
  docs/README_EN.md
  frontend/src/api/interface/dashboard.ts
  frontend/src/api/interface/website.ts
  frontend/src/components/compose-log/index.vue
  frontend/src/components/log-dialog/index.vue
  frontend/src/components/log-file/index.vue
  frontend/src/components/task-log/index.vue
  frontend/src/global/mimetype.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/routers/modules/website.ts
  frontend/src/views/app-store/apps/index.vue
  frontend/src/views/app-store/installed/upgrade/diff/index.vue
  frontend/src/views/home/app/index.vue
  frontend/src/views/home/index.vue
  frontend/src/views/home/status/index.vue
  frontend/src/views/login/components/login-form.vue
  frontend/src/views/website/runtime/dotnet/index.vue
  frontend/src/views/website/runtime/dotnet/operate/index.vue
  frontend/src/views/website/runtime/go/operate/index.vue
  frontend/src/views/website/runtime/index.vue
  frontend/src/views/website/runtime/java/operate/index.vue
  frontend/src/views/website/runtime/python/operate/index.vue
  frontend/src/views/website/website/config/basic/index.vue
  frontend/src/views/website/website/config/basic/php/index.vue
  frontend/src/views/website/website/config/basic/proxy/create/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, dev-v2

#7243 chore: fix typo for CloudDNS
  frontend/src/global/mimetype.ts
Labels: do-not-merge/release-note-label-needed

#7248 chore: Update README_EN.md
  docs/README_EN.md
Labels: do-not-merge/release-note-label-needed, dev

#7249 chore: Update README_EN.md
  docs/README_EN.md
Labels: do-not-merge/release-note-label-needed

#7250 chore: Update README.md
  README.md
Labels: do-not-merge/release-note-label-needed

#7252 feat: Internationalize Certain Files
  backend/init/migration/migrations/init.go
  backend/init/migration/migrations/v_1_8.go
  backend/init/migration/migrations/v_1_9.go
  backend/init/router/router.go
  cmd/server/res/html/200.html
  cmd/server/res/html/200_en.html
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#7247 Refine English translation
  backend/i18n/lang/en.yaml
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/container/container/operate/index.vue
  frontend/src/views/container/container/upgrade/index.vue
  frontend/src/views/container/repo/operator/index.vue
  frontend/src/views/container/setting/index.vue
  frontend/src/views/cronjob/index.vue
  frontend/src/views/host/process/network/index.vue
  frontend/src/views/host/process/process/detail/index.vue
  frontend/src/views/host/process/process/index.vue
  frontend/src/views/host/ssh/ssh/address/index.vue
  frontend/src/views/host/ssh/ssh/index.vue
  frontend/src/views/host/ssh/ssh/port/index.vue
  frontend/src/views/host/terminal/terminal/index.vue
  frontend/src/views/setting/backup-account/cos/index.vue
  frontend/src/views/setting/backup-account/kodo/index.vue
  frontend/src/views/setting/backup-account/minio/index.vue
  frontend/src/views/setting/backup-account/oss/index.vue
  frontend/src/views/setting/backup-account/s3/index.vue
  frontend/src/views/setting/license/index.vue
  frontend/src/views/toolbox/supervisor/file/index.vue
  frontend/src/views/website/runtime/dotnet/operate/index.vue
  frontend/src/views/website/runtime/go/operate/index.vue
  frontend/src/views/website/runtime/java/operate/index.vue
  frontend/src/views/website/runtime/node/operate/index.vue
  frontend/src/views/website/runtime/python/operate/index.vue
  frontend/src/views/website/ssl/ca/index.vue
  frontend/src/views/website/ssl/dns-account/create/index.vue
  frontend/src/views/website/website/config/basic/domain/index.vue
  frontend/src/views/website/website/config/basic/proxy/index.vue
  frontend/src/views/website/website/config/basic/redirect/index.vue
  frontend/src/views/website/website/config/log/log-fiile/index.vue
Labels: release-note-none

#7260 feat: Add System Version Restrictions for Applications
  backend/app/dto/app.go
  backend/app/service/app.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#7261 feat: Add pt-BR support for i18n
  backend/i18n/i18n.go
  cmd/server/cmd/root.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#7263 feat(cmd): Add internationalization for the output of the 1pctl version
  backend/i18n/lang/en.yaml
  backend/i18n/lang/fa.yaml
  backend/i18n/lang/pt.yaml
  backend/i18n/lang/zh-Hant.yaml
  backend/i18n/lang/zh.yaml
  cmd/server/cmd/version.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#7262 Fix: Postgres fails to connect when using special characters
  backend/utils/postgresql/client.go
  backend/utils/postgresql/client/remote.go
Labels: do-not-merge/release-note-label-needed

#7266 feat: Add .NET Runtime Environment for Websites
  frontend/src/views/website/website/create/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#7269 Fix: Postgres fails to connect when using special characters
  backend/utils/postgresql/client.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm

#7277 fix: Modify the default open source license in Swagger
  cmd/server/main.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#7279 chore: fix phantom dependency issue
  frontend/package.json
  frontend/src/views/host/file-management/index.vue
  frontend/src/views/host/ssh/log/log.vue
  frontend/src/views/log/login/index.vue
  frontend/src/views/log/operation/index.vue
  frontend/src/views/toolbox/supervisor/index.vue
Labels: do-not-merge/release-note-label-needed

#7281 chore: Modify the issues-translate-action token
  .github/workflows/issue-translator.yml
Labels: do-not-merge/release-note-label-needed, dev, approved

#7283 chore: refile English translation
  frontend/src/lang/modules/en.ts
Labels: do-not-merge/release-note-label-needed

#7295 fix: Dealing with API interface issues
  backend/middleware/session.go
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/setting/panel/api-interface/index.vue
  frontend/src/views/setting/panel/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#7298 pref: Improve Swagger authentication
  backend/app/api/v1/app.go
  backend/app/api/v1/app_install.go
  backend/app/api/v1/auth.go
  backend/app/api/v1/backup.go
  backend/app/api/v1/clam.go
  backend/app/api/v1/command.go
  backend/app/api/v1/compose_template.go
  backend/app/api/v1/container.go
  backend/app/api/v1/cronjob.go
  backend/app/api/v1/dashboard.go
  backend/app/api/v1/database.go
  backend/app/api/v1/database_common.go
  backend/app/api/v1/database_mysql.go
  backend/app/api/v1/database_postgresql.go
  backend/app/api/v1/database_redis.go
  backend/app/api/v1/device.go
  backend/app/api/v1/docker.go
  backend/app/api/v1/fail2ban.go
  backend/app/api/v1/favorite.go
  backend/app/api/v1/file.go
  backend/app/api/v1/firewall.go
  backend/app/api/v1/ftp.go
  backend/app/api/v1/group.go
  backend/app/api/v1/host.go
  backend/app/api/v1/host_tool.go
  backend/app/api/v1/image.go
  backend/app/api/v1/image_repo.go
  backend/app/api/v1/logs.go
  backend/app/api/v1/monitor.go
  backend/app/api/v1/nginx.go
  backend/app/api/v1/php_extensions.go
  backend/app/api/v1/process.go
  backend/app/api/v1/recycle_bin.go
  backend/app/api/v1/runtime.go
  backend/app/api/v1/setting.go
  backend/app/api/v1/snapshot.go
  backend/app/api/v1/ssh.go
  backend/app/api/v1/upgrade.go
  backend/app/api/v1/website.go
  backend/app/api/v1/website_acme_account.go
  backend/app/api/v1/website_ca.go
  backend/app/api/v1/website_dns_account.go
  backend/app/api/v1/website_domain.go
  backend/app/api/v1/website_ssl.go
  backend/init/router/router.go
  cmd/server/docs/docs.go
  cmd/server/docs/swagger.json
  cmd/server/docs/swagger.yaml
  cmd/server/main.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#7303 feat: Fix Issue with DNS Account Deletion After Certificate Update Ap…
  backend/app/service/website_ssl.go
  backend/utils/geo/geo.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#7305 style: Adjusted some English layouts
  frontend/src/components/system-upgrade/index.vue
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/cronjob/index.vue
  frontend/src/views/cronjob/operate/index.vue
  frontend/src/views/toolbox/clam/index.vue
  frontend/src/views/toolbox/clam/operate/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#7306 feat: Add Return Pages for Unauthorized Domains and IPs
  backend/app/api/v1/helper/helper.go
  backend/init/router/router.go
  backend/middleware/bind_domain.go
  backend/middleware/ip_limit.go
  cmd/server/res/html/200_err_domain.html
  cmd/server/res/html/200_err_ip_limit.html
  frontend/src/components/error-message/err_domain.vue
  frontend/src/components/error-message/err_ip.vue
  frontend/src/components/error-message/unsafe.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#7296 feat: Add support for multiple host license
  agent/app/api/v2/health.go
  agent/app/service/backup.go
  agent/configs/system.go
  agent/constant/errs.go
  agent/i18n/lang/en.yaml
  agent/i18n/lang/zh-Hant.yaml
  agent/i18n/lang/zh.yaml
  agent/init/hook/hook.go
  agent/server/server.go
  agent/utils/xpack/xpack.go
  core/app/repo/common.go
  core/app/service/app_launcher.go
  core/app/service/auth.go
  core/app/service/backup.go
  core/app/service/command.go
  core/app/service/entry.go
  core/app/service/group.go
  core/app/service/host.go
  core/app/service/logs.go
  core/app/service/setting.go
  core/app/service/task.go
  core/app/service/upgrade.go
  core/buserr/errors.go
  core/constant/errs.go
  core/constant/status.go
  core/i18n/lang/en.yaml
  core/i18n/lang/zh-Hant.yaml
  core/i18n/lang/zh.yaml
  core/init/db/db.go
  core/init/hook/hook.go
  core/middleware/bind_domain.go
  core/middleware/helper.go
  core/middleware/ip_limit.go
  core/middleware/loading.go
  core/middleware/password_expired.go
  core/middleware/proxy.go
  core/middleware/session.go
  core/utils/common/common.go
  core/utils/common/sqlite.go
  core/utils/http/new.go
  core/utils/jwt/jwt.go
  core/utils/xpack/xpack.go
  frontend/src/api/interface/setting.ts
  frontend/src/api/modules/setting.ts
  frontend/src/components/system-upgrade/index.vue
  frontend/src/global/use-theme.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/layout/components/Sidebar/index.vue
  frontend/src/layout/index.vue
  frontend/src/store/interface/index.ts
  frontend/src/store/modules/global.ts
  frontend/src/utils/xpack.ts
  frontend/src/views/setting/license/bind/index.vue
  frontend/src/views/setting/license/delete/index.vue
  frontend/src/views/setting/license/index.vue
  frontend/src/views/setting/panel/index.vue
  frontend/src/views/setting/panel/proxy/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#7299 fix: 解决控制台报错问题
  frontend/src/views/container/compose/create/index.vue
  frontend/src/views/container/compose/edit/index.vue
Labels: do-not-merge/release-note-label-needed

#7308 style: Optimize input to disable background color
  frontend/src/styles/element.scss
  frontend/src/views/container/setting/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#7309 style: Improve password action buttons styling in database connection info
  frontend/src/views/database/mysql/conn/index.vue
  frontend/src/views/database/postgresql/conn/index.vue
  frontend/src/views/database/redis/conn/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#7311 feat: Remove Unused Components
  frontend/src/views/login/entrance/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#7313 feat: Fix Missing CPU and Memory Limit Warnings When Editing Installe…
  frontend/src/views/app-store/installed/detail/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#7315 feat(init): add support for international language pack initialization
  backend/app/service/snapshot_create.go
  backend/app/service/snapshot_recover.go
  backend/app/service/upgrade.go
  backend/init/hook/hook.go
  cmd/server/cmd/restore.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#7317 Include the GeoIP.mmdb file when building the installation package
  .goreleaser.yaml
Labels: do-not-merge/release-note-label-needed, dev

#7318 Refine pluralization of some English words
  frontend/package.json
  frontend/src/components/group/index.vue
  frontend/src/components/table-setting/index.vue
  frontend/src/components/v-charts/components/Line.vue
  frontend/src/lang/index.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/layout/components/Sidebar/components/SubItem.vue
  frontend/src/utils/util.ts
  frontend/src/views/app-store/apps/index.vue
  frontend/src/views/app-store/installed/index.vue
  frontend/src/views/container/compose/index.vue
  frontend/src/views/container/container/index.vue
  frontend/src/views/container/image/index.vue
  frontend/src/views/container/index.vue
  frontend/src/views/container/network/index.vue
  frontend/src/views/container/repo/index.vue
  frontend/src/views/container/repo/operator/index.vue
  frontend/src/views/container/setting/index.vue
  frontend/src/views/container/template/index.vue
  frontend/src/views/container/template/operator/index.vue
  frontend/src/views/container/volume/index.vue
  frontend/src/views/cronjob/index.vue
  frontend/src/views/database/mysql/index.vue
  frontend/src/views/database/postgresql/index.vue
  frontend/src/views/database/redis/index.vue
  frontend/src/views/home/index.vue
  frontend/src/views/home/status/index.vue
  frontend/src/views/host/file-management/batch-role/index.vue
  frontend/src/views/host/file-management/change-role/index.vue
  frontend/src/views/host/file-management/create/index.vue
  frontend/src/views/host/file-management/index.vue
  frontend/src/views/host/file-management/upload/index.vue
  frontend/src/views/host/firewall/forward/index.vue
  frontend/src/views/host/firewall/index.vue
  frontend/src/views/host/firewall/ip/index.vue
  frontend/src/views/host/firewall/port/index.vue
  frontend/src/views/host/monitor/index.vue
  frontend/src/views/host/monitor/monitor/index.vue
  frontend/src/views/host/monitor/setting/index.vue
  frontend/src/views/host/process/index.vue
  frontend/src/views/host/process/network/index.vue
  frontend/src/views/host/process/process/index.vue
  frontend/src/views/host/ssh/index.vue
  frontend/src/views/host/ssh/log/log.vue
  frontend/src/views/host/ssh/session/index.vue
  frontend/src/views/host/ssh/ssh/index.vue
  frontend/src/views/host/terminal/command/index.vue
  frontend/src/views/host/terminal/host/index.vue
  frontend/src/views/host/terminal/index.vue
  frontend/src/views/setting/backup-account/index.vue
  frontend/src/views/setting/backup-account/s3/index.vue
  frontend/src/views/setting/index.vue
  frontend/src/views/setting/snapshot/index.vue
  frontend/src/views/website/ssl/ca/index.vue
  frontend/src/views/website/ssl/index.vue
  frontend/src/views/website/website/config/index.vue
  frontend/src/views/website/website/index.vue
Labels: release-note-none

#7321 fix: i18n file enhancement
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#7322 style: Optimize the layout of app operation buttons
  frontend/src/views/app-store/installed/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#7324 fix(database-pg): Fixed the issue of PostgreSQL not being able to back up.
  backend/utils/postgresql/client/remote.go
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#7326 feat: Add YAML format to CodeMirror
  frontend/package.json
  frontend/src/views/app-store/detail/install/index.vue
  frontend/src/views/app-store/installed/detail/index.vue
  frontend/src/views/container/compose/create/index.vue
  frontend/src/views/container/compose/edit/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#7327 fix: typo in makefile
  Makefile
Labels: do-not-merge/release-note-label-needed

#7333 feat(init): Add support for geo ip pack initialization
  backend/app/service/upgrade.go
  backend/init/hook/hook.go
  backend/init/lang/lang.go
  backend/server/server.go
  cmd/server/cmd/restore.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#7332 feat: Some adjustments to internationalization
  frontend/src/layout/components/Sidebar/index.vue
  frontend/src/routers/index.ts
  frontend/src/views/setting/panel/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#7334 feat: Fix 500 Error After Setting Authorized IP
  backend/middleware/ip_limit.go
  frontend/src/views/app-store/installed/detail/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#7336 refactor(init): run docker network creation and firewall setup in a goroutine
  backend/init/app/app.go
Labels: do-not-merge/release-note-label-needed

#7337 fix: correct typos in typescript interface names
  backend/server/server.go
  frontend/src/views/app-store/detail/install/index.vue
  frontend/src/views/app-store/installed/check/index.vue
  frontend/src/views/website/runtime/dotnet/operate/index.vue
  frontend/src/views/website/runtime/go/operate/index.vue
  frontend/src/views/website/runtime/java/operate/index.vue
  frontend/src/views/website/runtime/node/module/index.vue
  frontend/src/views/website/runtime/node/operate/index.vue
  frontend/src/views/website/runtime/php/check/index.vue
  frontend/src/views/website/runtime/php/create/index.vue
  frontend/src/views/website/runtime/python/operate/index.vue
  frontend/src/views/website/website/check/index.vue
Labels: do-not-merge/release-note-label-needed

#7338 fix: fixed the issue of abnormal log request
  frontend/src/components/log-file/index.vue
Labels: do-not-merge/release-note-label-needed

#7341 pref: Optimize the button style for database connection information
  frontend/src/components/copy-button/index.vue
  frontend/src/views/database/mysql/conn/index.vue
  frontend/src/views/database/postgresql/conn/index.vue
  frontend/src/views/database/redis/conn/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#7342 pref: Optimize the button style for database connection information
  backend/init/lang/lang.go
  frontend/src/views/database/mysql/conn/index.vue
  frontend/src/views/database/postgresql/conn/index.vue
  frontend/src/views/database/redis/conn/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#7345 feat: Fix the initialization errors of GeoIP
  backend/app/service/upgrade.go
  backend/init/lang/lang.go
  cmd/server/cmd/restore.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#7346 feat: Optimize English description and layout
  frontend/src/lang/modules/en.ts
  frontend/src/views/toolbox/device/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#7349 feat: Language pack content adjustment
  frontend/src/lang/modules/en.ts
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#7348 fix: Fixed the bug of displaying prompt information for first-time login
  frontend/src/views/login/components/login-form.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#7350 feat: Adjust the empty status prompt layout
  frontend/src/components/app-status/index.vue
  frontend/src/views/database/mysql/index.vue
  frontend/src/views/database/postgresql/index.vue
  frontend/src/views/database/redis/index.vue
  frontend/src/views/host/firewall/forward/index.vue
  frontend/src/views/host/firewall/ip/index.vue
  frontend/src/views/host/firewall/port/index.vue
  frontend/src/views/toolbox/clam/status/index.vue
  frontend/src/views/toolbox/fail2ban/index.vue
  frontend/src/views/toolbox/ftp/index.vue
  frontend/src/views/toolbox/supervisor/status/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#7351 style: Code Style Format
  frontend/src/views/host/firewall/ip/index.vue
  frontend/src/views/toolbox/supervisor/status/index.vue
  frontend/src/views/website/website/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#7352 style: Optimize layout style
  frontend/src/components/license-import/index.vue
  frontend/src/components/system-upgrade/index.vue
  frontend/src/styles/common.scss
  frontend/src/styles/element-dark.scss
  frontend/src/views/database/mysql/index.vue
  frontend/src/views/database/postgresql/index.vue
  frontend/src/views/database/redis/index.vue
  frontend/src/views/setting/license/index.vue
  frontend/src/views/website/runtime/dotnet/index.vue
  frontend/src/views/website/runtime/go/index.vue
  frontend/src/views/website/runtime/java/index.vue
  frontend/src/views/website/runtime/node/index.vue
  frontend/src/views/website/runtime/python/index.vue
  frontend/src/views/website/ssl/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#7353 Refine English translation
  frontend/src/components/app-status/index.vue
  frontend/src/components/table-setting/index.vue
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/routers/modules/host.ts
  frontend/src/views/database/mysql/index.vue
  frontend/src/views/database/postgresql/index.vue
  frontend/src/views/database/postgresql/remote/index.vue
  frontend/src/views/database/redis/index.vue
  frontend/src/views/database/redis/remote/index.vue
  frontend/src/views/home/index.vue
  frontend/src/views/home/status/index.vue
  frontend/src/views/host/terminal/command/index.vue
  frontend/src/views/toolbox/clam/index.vue
  frontend/src/views/toolbox/clam/record/index.vue
  frontend/src/views/toolbox/clam/status/index.vue
  frontend/src/views/toolbox/ftp/index.vue
  frontend/src/views/toolbox/supervisor/index.vue
  frontend/src/views/toolbox/supervisor/status/index.vue
  frontend/src/views/website/website/config/basic/proxy/file/index.vue
  frontend/src/views/website/website/config/basic/proxy/index.vue
  frontend/src/views/website/website/config/basic/redirect/file/index.vue
  frontend/src/views/website/website/config/basic/redirect/index.vue
Labels: do-not-merge/release-note-label-needed

#7354 style: Optimize layout style
  frontend/src/lang/modules/en.ts
  frontend/src/styles/element-dark.scss
  frontend/src/styles/element.scss
  frontend/src/views/container/setting/index.vue
  frontend/src/views/host/file-management/index.vue
Labels: do-not-merge/release-note-label-needed, dev, approved

#7356 pref(system): Optimize and upgrade related internationalization translations.
  frontend/src/components/system-upgrade/index.vue
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/setting/license/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#7357 feat: CornJob shell script syntax highlighting
  frontend/src/views/cronjob/operate/index.vue
Labels: do-not-merge/release-note-label-needed

#7358 Replace whitelist and blacklist with allowlist and blocklist
  frontend/src/lang/modules/en.ts
Labels: release-note-none

#7359 style: Optimize layout style
  frontend/src/components/system-upgrade/index.vue
  frontend/src/lang/modules/en.ts
  frontend/src/store/modules/global.ts
  frontend/src/styles/moblie.scss
  frontend/src/views/app-store/index.scss
  frontend/src/views/app-store/installed/index.vue
  frontend/src/views/setting/about/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#7360 fix: FIx the issue of container editing not opening successfully
  frontend/src/lang/modules/en.ts
  frontend/src/views/container/container/index.vue
  frontend/src/views/container/container/operate/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#7368 style: Optimize international style layout
  frontend/src/styles/common.scss
  frontend/src/views/toolbox/clean/index.vue
  frontend/src/views/toolbox/device/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#7369 feat: Fix Translation Issue in Input Field Placeholder on First Login
  frontend/src/lang/index.ts
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#7374 feat: Fix Application Store Style Issue Under Poor Network Conditions
  backend/app/service/app.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#7375 fix: Fixed an issue where the language pack initialization download f…
  backend/init/lang/lang.go
  backend/utils/http/get.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#7372 feat: Optimize international document addresses
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/layout/components/AppFooter.vue
  frontend/src/styles/common.scss
  frontend/src/styles/element-dark.scss
  frontend/src/styles/element.scss
  frontend/src/views/container/setting/index.vue
  frontend/src/views/container/setting/ipv6/index.vue
  frontend/src/views/host/firewall/forward/index.vue
  frontend/src/views/host/firewall/ip/index.vue
  frontend/src/views/host/firewall/port/index.vue
  frontend/src/views/setting/backup-account/index.vue
  frontend/src/views/setting/backup-account/onedrive/index.vue
  frontend/src/views/setting/backup-account/webdav/index.vue
  frontend/src/views/setting/panel/api-interface/index.vue
  frontend/src/views/toolbox/clam/index.vue
  frontend/src/views/toolbox/clam/status/index.vue
  frontend/src/views/toolbox/fail2ban/index.vue
  frontend/src/views/toolbox/ftp/index.vue
  frontend/src/views/toolbox/supervisor/status/index.vue
  frontend/src/views/website/runtime/php/create/index.vue
  frontend/src/views/website/runtime/php/extensions/operate/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#7376 fix: Fix the issue of incorrect display of prompts on the English language login page
  frontend/src/views/login/components/login-form.vue
  frontend/src/views/toolbox/clam/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#7378 feat: Optimize style and description
  cmd/server/docs/docs.go
  cmd/server/docs/swagger.json
  cmd/server/docs/swagger.yaml
  cmd/server/main.go
  frontend/src/lang/modules/en.ts
  frontend/src/styles/element-dark.scss
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#7381 feat: Modify document address
  frontend/src/views/setting/backup-account/onedrive/index.vue
  frontend/src/views/setting/backup-account/webdav/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#7382 fix: Fix the issue of compose name validation errors
  frontend/src/global/form-rules.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/container/compose/create/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#7385 style: change some column width
  frontend/src/lang/modules/en.ts
  frontend/src/views/container/compose/index.vue
  frontend/src/views/container/container/index.vue
  frontend/src/views/database/mysql/index.vue
  frontend/src/views/database/postgresql/index.vue
  frontend/src/views/host/process/process/index.vue
  frontend/src/views/toolbox/supervisor/index.vue
  frontend/src/views/website/ssl/ca/index.vue
  frontend/src/views/website/ssl/index.vue
  frontend/src/views/website/website/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#7387 style: change some label
  frontend/src/lang/modules/en.ts
  frontend/src/views/container/repo/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#7392 style: change some label
  frontend/src/lang/modules/en.ts
  frontend/src/views/app-store/installed/index.vue
  frontend/src/views/host/ssh/log/log.vue
  frontend/src/views/log/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#7393 feat: Optimize style and description
  frontend/src/views/login/components/login-form.vue
  frontend/src/views/setting/panel/index.vue
  frontend/src/views/toolbox/clean/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#7389 feat: move cmd dir to core
  .gitignore
  backend/router/entry_xpack.go
  backend/server/init_xpack.go
  core/cmd/server/cmd/listen-ip.go
  core/cmd/server/cmd/reset.go
  core/cmd/server/cmd/restore.go
  core/cmd/server/cmd/root.go
  core/cmd/server/cmd/update.go
  core/cmd/server/cmd/user-info.go
  core/cmd/server/cmd/version.go
  core/cmd/server/conf/app.yaml
  core/cmd/server/conf/conf.go
  core/cmd/server/docs/docs.go
  core/cmd/server/docs/swagger.go
  core/cmd/server/docs/swagger.json
  core/cmd/server/docs/swagger_test.go
  core/cmd/server/docs/x-log.json
  core/cmd/server/main.go
  core/cmd/server/web/favicon.png
  core/cmd/server/web/web.go
  core/go.mod
  core/go.sum
  core/init/router/router.go
  core/init/viper/viper.go
  core/middleware/operation.go
  frontend/src/views/website/website/create/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#7395 fix: Improve cache cleaning for internationalization
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/toolbox/clean/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#7396 style: Increase the height of the script input box
  frontend/src/views/cronjob/operate/index.vue
  frontend/src/views/toolbox/clean/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#7397 chore: Update README_EN.md
  docs/README_EN.md
Labels: do-not-merge/release-note-label-needed

#7398 style: Increase the height of the script input box
  frontend/src/views/cronjob/operate/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#7399 Refine English translation and UI style
  frontend/src/lang/modules/en.ts
  frontend/src/views/home/index.vue
  frontend/src/views/host/firewall/port/index.vue
Labels: lgtm, release-note-none

#7400 fix: fix typos
  frontend/src/lang/modules/en.ts
Labels: do-not-merge/release-note-label-needed

#7412 chore: Update README.md
  README.md
Labels: do-not-merge/release-note-label-needed

#7416 docs: Update README.md
  README.md
Labels: do-not-merge/release-note-label-needed, dev

#7401 fix: fix typos
  frontend/src/lang/modules/en.ts
Labels: do-not-merge/release-note-label-needed

#7402 fix: datas should be dataList
  frontend/src/components/v-charts/components/Line.vue
Labels: do-not-merge/release-note-label-needed

#7403 fix: fix typos
  frontend/src/lang/modules/en.ts
Labels: do-not-merge/release-note-label-needed

#7405 fix: typos
  backend/utils/toolbox/pure-ftpd.go
Labels: do-not-merge/release-note-label-needed

#7407 fix: fix typos
  frontend/src/lang/modules/en.ts
Labels: do-not-merge/release-note-label-needed

#7411 Update fa.yaml
  backend/i18n/lang/fa.yaml
Labels: do-not-merge/release-note-label-needed

#7417 feat: Optimize mobile style
  frontend/src/views/container/setting/index.vue
  frontend/src/views/cronjob/record/index.vue
  frontend/src/views/database/mysql/index.vue
  frontend/src/views/database/postgresql/index.vue
  frontend/src/views/database/redis/index.vue
  frontend/src/views/host/firewall/status/index.vue
  frontend/src/views/host/ssh/ssh/index.vue
  frontend/src/views/toolbox/clam/status/index.vue
  frontend/src/views/toolbox/fail2ban/index.vue
  frontend/src/views/toolbox/ftp/index.vue
  frontend/src/views/toolbox/supervisor/status/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#7414 style: Optimize style
  frontend/src/styles/element-dark.scss
  frontend/src/styles/element.scss
  frontend/src/views/container/image/pull/index.vue
  frontend/src/views/setting/snapshot/status/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#7420 feat: Remove Unnecessary Code Segments
  agent/i18n/lang/en.yaml
  agent/i18n/lang/zh-Hant.yaml
  agent/i18n/lang/zh.yaml
  agent/init/migration/migrations/init.go
  frontend/src/components/app-status/index.vue
  frontend/src/components/drawer-pro/index.vue
  frontend/src/components/layout-content/index.vue
  frontend/src/components/log-dialog/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#7422 style: Container style
  frontend/src/views/container/container/index.vue
Labels: do-not-merge/release-note-label-needed

#7424 docs: Update README.md
  README.md
  docs/README.ja.md
  docs/README.zh-Hant.md
Labels: do-not-merge/release-note-label-needed

#7425 docs: Add README.pt-br.md
  README.md
  docs/README.pt-br.md
Labels: do-not-merge/release-note-label-needed

#7423 style(website): Update Nginx Status Page Styling
  agent/app/dto/response/nginx.go
  agent/app/service/nginx.go
  frontend/src/api/interface/nginx.ts
  frontend/src/components/app-status/index.vue
  frontend/src/components/back-button/index.vue
  frontend/src/components/layout-content/index.vue
  frontend/src/views/website/website/nginx/status/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#7427 docs: add Korean README documentation
  README.md
  docs/README.ja.md
  docs/README.ko.md
  docs/README.pt-br.md
  docs/README.zh-Hans.md
  docs/README.zh-Hant.md
Labels: release-note-none

#7426 feat: uniform application service status return
  agent/app/dto/docker.go
  agent/app/dto/firewall.go
  agent/app/dto/ssh.go
  agent/app/service/docker.go
  agent/app/service/fail2ban.go
  agent/app/service/firewall.go
  agent/app/service/ssh.go
  agent/utils/firewall/client.go
  agent/utils/firewall/client/firewalld.go
  agent/utils/firewall/client/iptables.go
  agent/utils/firewall/client/ufw.go
  frontend/src/views/container/compose/index.vue
  frontend/src/views/container/container/index.vue
  frontend/src/views/container/docker-status/index.vue
  frontend/src/views/container/image/index.vue
  frontend/src/views/container/network/index.vue
  frontend/src/views/container/repo/index.vue
  frontend/src/views/container/template/index.vue
  frontend/src/views/container/volume/index.vue
  frontend/src/views/host/firewall/forward/index.vue
  frontend/src/views/host/firewall/ip/index.vue
  frontend/src/views/host/firewall/port/index.vue
  frontend/src/views/host/firewall/status/index.vue
  frontend/src/views/host/ssh/ssh/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#7428 feat(component): Replace Drawer Component
  frontend/src/components/drawer-header/index.vue
  frontend/src/components/layout-content/index.vue
  frontend/src/components/log-dialog/index.vue
  frontend/src/components/system-upgrade/upgrade/index.vue
  frontend/src/config/config.ts
  frontend/src/config/pinia-persist.ts
  frontend/src/directives/index.ts
  frontend/src/directives/modules/copy.ts
  frontend/src/env.d.ts
  frontend/src/main.ts
  frontend/src/utils/is/index.ts
  frontend/src/utils/theme/tool.ts
  frontend/src/views/host/file-management/detail/index.vue
  frontend/src/views/toolbox/clam/operate/index.vue
  frontend/src/views/toolbox/clam/setting/index.vue
  frontend/src/views/website/runtime/dotnet/operate/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#7429 Fix invalid postion of before content in home page
  frontend/src/components/card-with-header/index.vue
Labels: release-note-none

#7433 refactor: Demo server, prohibit operation
  frontend/src/api/index.ts
  frontend/src/views/setting/panel/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#7434 docs: Update README.md
  README.md
Labels: do-not-merge/release-note-label-needed, dev

#7435 feat(container): Align Container Memory Usage Display with Docker Stats
  agent/app/service/container.go
  frontend/src/components/back-button/index.vue
  frontend/src/components/group/index.vue
Labels: do-not-merge/release-note-label-needed, dev-v2

#7439 feat: merge code from dev
  Makefile
  agent/app/dto/dashboard.go
  agent/app/service/dashboard.go
  agent/app/service/firewall.go
  agent/init/app/app.go
  agent/init/router/router.go
  agent/utils/common/sqlite.go
  agent/utils/postgresql/client.go
  agent/utils/postgresql/client/remote.go
  core/cmd/server/cmd/root.go
  core/cmd/server/cmd/version.go
  core/go.mod
  core/init/router/proxy.go
  core/init/router/router.go
  core/middleware/operation.go
  core/router/app_launcher.go
  core/router/command.go
  core/router/ro_backup.go
  core/router/ro_group.go
  core/router/ro_host.go
  core/router/ro_log.go
  core/router/ro_setting.go
  core/utils/mfa/mfa.go
  frontend/src/api/interface/dashboard.ts
  frontend/src/components/error-message/error_code.vue
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/app-store/index.vue
  frontend/src/views/home/index.vue
  frontend/src/views/host/file-management/batch-role/index.vue
  frontend/src/views/host/file-management/create/index.vue
  frontend/src/views/host/file-management/index.vue
  frontend/src/views/host/file-management/recycle-bin/index.vue
  frontend/src/views/host/file-management/upload/index.vue
  frontend/src/views/log/website/index.vue
  frontend/src/views/login/components/login-form.vue
  frontend/src/views/website/runtime/go/index.vue
  frontend/vite.config.ts
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#7441 docs: Create README.id.md
  docs/README.id.md
Labels: do-not-merge/release-note-label-needed

#7442 chore: Update README.md
  README.md
Labels: do-not-merge/release-note-label-needed

#7445 chore: Add Indonesian language
  docs/README.id.md
  docs/README.ja.md
  docs/README.ko.md
  docs/README.pt-br.md
  docs/README.zh-Hans.md
  docs/README.zh-Hant.md
Labels: do-not-merge/release-note-label-needed, dev

#7455 go: upgraded golang.org/x/net v0.30.0 => v0.33.0
  go.mod
  go.sum
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#7456 go: upgraded golang.org/x/crypto v0.28.0 => v0.31.0
  go.mod
  go.sum
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#7458 fix(system): Fix Cloudflare Proxy Access Issue with 1Panel When Secur…
  backend/init/router/router.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#7462 style: Modify some styles to improve the appearance of the version button
  frontend/src/components/system-upgrade/index.vue
Labels: do-not-merge/release-note-label-needed

#7459 feat: Optimize Location Information Display in System Login Logs
  backend/app/api/v1/auth.go
  backend/app/api/v1/logs.go
  backend/app/service/logs.go
  backend/utils/geo/geo.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#7461 Create README.es.md
  docs/README.es.md
Labels: do-not-merge/release-note-label-needed

#7463 添加阿拉伯语的README文件
  docs/README.ar.md
Labels: do-not-merge/release-note-label-needed

#7465 style: Optimize OpenResty Warnings Displayed During Zooming
  frontend/src/components/app-status/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#7464 style: Modify some styles to improve the appearance of the version bu…
  frontend/src/components/system-upgrade/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm

#7466 Update README.es.md
  docs/README.es.md
Labels: do-not-merge/release-note-label-needed

#7467 修改README文件的各语言间隔样式
  docs/README.ar.md
Labels: do-not-merge/release-note-label-needed

#7468 fix:修正葡萄牙语国际化翻译
  backend/i18n/lang/pt.yaml
Labels: do-not-merge/release-note-label-needed

#7469 feat: Add README.fr.md
  docs/README.fr.md
Labels: do-not-merge/release-note-label-needed, dev

#7470 修改了RTL格式，使正文第一句话右对齐
  docs/README.ar.md
Labels: do-not-merge/release-note-label-needed

#7471 Update zh-Hant.yaml
  backend/i18n/lang/zh-Hant.yaml
Labels: do-not-merge/release-note-label-needed

#7473 style: Optimize style code
  frontend/src/views/setting/backup-account/index.vue
Labels: do-not-merge/release-note-label-needed

#7475 fix: Typo in hostname save function and button click
  frontend/src/views/toolbox/device/hostname/index.vue
Labels: do-not-merge/release-note-label-needed

#7472 feat: Open international professional features
  frontend/src/components/system-upgrade/index.vue
  frontend/src/layout/components/Sidebar/index.vue
  frontend/src/routers/index.ts
  frontend/src/styles/element.scss
  frontend/src/views/home/index.vue
  frontend/src/views/setting/about/index.vue
  frontend/src/views/setting/index.vue
  frontend/src/views/setting/panel/index.vue
  frontend/src/views/toolbox/clam/operate/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#7476 fix spelling error
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/container/container/terminal/index.vue
Labels: do-not-merge/release-note-label-needed

#7478 fix: fix typos
  backend/app/api/v1/firewall.go
Labels: do-not-merge/release-note-label-needed

#7477 Update README.es.md
  docs/README.es.md
Labels: do-not-merge/release-note-label-needed

#7482 feat: Add README.de.md
  docs/README.de.md
Labels: do-not-merge/release-note-label-needed

#7480 Add File README.tr.md
  docs/README.tr.md
Labels: do-not-merge/release-note-label-needed

#7483 Update zh-Hant.yaml
  backend/i18n/lang/zh-Hant.yaml
Labels: do-not-merge/release-note-label-needed

#7484 feat: Remove Redundant Code
  frontend/src/directives/index.ts
  frontend/src/directives/modules/copy.ts
  frontend/src/directives/modules/debounce.ts
  frontend/src/directives/modules/draggable.ts
  frontend/src/directives/modules/drawer-drag.ts
  frontend/src/directives/modules/longpress.ts
  frontend/src/directives/modules/throttle.ts
  frontend/src/directives/modules/water-marker.ts
  frontend/src/main.ts
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#7481 Add ImportMeta type definition
  frontend/vite-env.d.ts
Labels: do-not-merge/release-note-label-needed

#7485 fix: update zh-hant spell
  backend/i18n/lang/zh-Hant.yaml
Labels: do-not-merge/release-note-label-needed

#7486 Update README.tr.md
  docs/README.tr.md
Labels: do-not-merge/release-note-label-needed

#7479 perf: Optimize FTP sync function for better performance and readability
  backend/app/service/ftp.go
Labels: do-not-merge/release-note-label-needed

#7487 Update tw.ts
  frontend/src/lang/modules/tw.ts
Labels: do-not-merge/release-note-label-needed

#7488 feat(common): Standardize Permissions for Creating Folders and Files
  agent/app/api/v2/file.go
  agent/app/service/app_install.go
  agent/app/service/app_utils.go
  agent/app/service/backup_app.go
  agent/app/service/backup_runtime.go
  agent/app/service/container.go
  agent/app/service/container_compose.go
  agent/app/service/cronjob.go
  agent/app/service/cronjob_helper.go
  agent/app/service/database_mysql.go
  agent/app/service/database_redis.go
  agent/app/service/file.go
  agent/app/service/firewall.go
  agent/app/service/host_tool.go
  agent/app/service/image.go
  agent/app/service/nginx.go
  agent/app/service/nginx_utils.go
  agent/app/service/recycle_bin.go
  agent/app/service/runtime.go
  agent/app/service/runtime_utils.go
  agent/app/service/ssh.go
  agent/app/service/website.go
  agent/app/service/website_ca.go
  agent/app/service/website_ssl.go
  agent/app/service/website_utils.go
  agent/app/task/task.go
  agent/constant/common.go
  agent/init/app/app.go
  agent/log/config.go
  agent/log/writer.go
  agent/server/server.go
  agent/utils/cloud_storage/client/webdav.go
  agent/utils/cmd/cmd.go
  agent/utils/common/common.go
  agent/utils/files/file_op.go
  agent/utils/mysql/client/local.go
  agent/utils/mysql/client/remote.go
  agent/utils/nginx/dumper.go
  agent/utils/postgresql/client/local.go
  core/app/service/backup.go
  core/app/task/task.go
  core/constant/common.go
  core/log/config.go
  core/log/writer.go
  core/middleware/session.go
  core/utils/cloud_storage/client/webdav.go
  core/utils/files/files.go
  frontend/.gitignore
Labels: do-not-merge/release-note-label-needed, dev-v2

#7489 Update zh-Hant.yaml
  backend/i18n/lang/zh-Hant.yaml
Labels: do-not-merge/release-note-label-needed

#7491 fix: 修正英文国际化翻译
  backend/i18n/lang/en.yaml
Labels: do-not-merge/release-note-label-needed

#7492 feat: Update 數據庫 => 資料庫
  backend/i18n/lang/zh-Hant.yaml
  frontend/src/lang/modules/tw.ts
Labels: do-not-merge/release-note-label-needed, dev

#7493 fix: 修正英文国际化翻译
  backend/i18n/lang/en.yaml
Labels: do-not-merge/release-note-label-needed

#7494 fix: 修正英文国际化翻译
  backend/i18n/lang/en.yaml
Labels: do-not-merge/release-note-label-needed

#7496 feat: Login to access Swagger documentation
  backend/init/router/router.go
Labels: do-not-merge/release-note-label-needed, dev

#7515 fix: Update zh-Hant translation
  backend/i18n/lang/zh-Hant.yaml
  frontend/src/lang/modules/tw.ts
Labels: do-not-merge/release-note-label-needed

#7516 fix: Remove `proxy_cache ` from the global config to prevent it from being enabled for sites that don't need caching.
  cmd/server/nginx_conf/cache.conf
Labels: do-not-merge/release-note-label-needed

#7532 feat(system-security): Optimized unauthenticated settings to enhance …
  core/app/service/auth.go
  core/cmd/server/res/error_msg.go
  core/cmd/server/res/html/200.html
  core/cmd/server/res/html/200_err_domain.html
  core/cmd/server/res/html/200_err_ip_limit.html
  core/cmd/server/res/html/400.html
  core/cmd/server/res/html/401.html
  core/cmd/server/res/html/403.html
  core/cmd/server/res/html/404.html
  core/cmd/server/res/html/408.html
  core/cmd/server/res/html/416.html
  core/cmd/server/res/html/500.html
  core/constant/common.go
  core/init/router/router.go
  frontend/src/api/index.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/routers/router.ts
  frontend/src/views/login/entrance/index.vue
  frontend/src/views/setting/safe/response/index.vue
Labels: do-not-merge/release-note-label-needed, dev-v2

#7529 feat: Add non-professional version node management page
  frontend/src/assets/iconfont/iconfont.css
  frontend/src/assets/iconfont/iconfont.js
  frontend/src/assets/iconfont/iconfont.json
  frontend/src/assets/iconfont/iconfont.ttf
  frontend/src/assets/iconfont/iconfont.woff
  frontend/src/assets/iconfont/iconfont.woff2
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/setting/license/index.vue
Labels: do-not-merge/release-note-label-needed, dev-v2

#7533 feat(system-security): Add API for Synchronizing System Certificates
  agent/app/service/app.go
  agent/app/service/app_utils.go
  agent/app/service/website_ssl.go
  agent/i18n/i18n.go
  agent/init/business/business.go
  agent/utils/http/core.go
  core/app/api/v2/setting.go
  core/app/service/setting.go
  core/router/ro_setting.go
  core/server/server.go
  frontend/src/routers/router.ts
  frontend/src/views/login/entrance/index.vue
Labels: do-not-merge/release-note-label-needed, dev-v2

#7536 feat: Synchronously update the firewall when modifying connection inf…
  core/app/service/setting.go
  core/configs/system.go
  core/constant/errs.go
  core/constant/status.go
  core/i18n/lang/en.yaml
  core/i18n/lang/zh-Hant.yaml
  core/i18n/lang/zh.yaml
  core/init/hook/hook.go
  core/utils/cmd/cmd.go
  core/utils/firewall/firewall.go
  core/utils/xpack/xpack.go
Labels: do-not-merge/release-note-label-needed, dev-v2

#7537 feat(system-security): Optimize Route Matching for Secure Entry
  agent/app/service/app.go
  agent/app/service/runtime.go
  agent/utils/common/common.go
  core/constant/common.go
  core/init/viper/viper.go
  frontend/src/routers/router.ts
  frontend/src/views/login/entrance/index.vue
  frontend/src/views/login/index.vue
Labels: do-not-merge/release-note-label-needed, dev-v2

#7544 docs: add discord badge in readme
  README.md
  docs/README.ar.md
  docs/README.de.md
  docs/README.es.md
  docs/README.fr.md
  docs/README.id.md
  docs/README.ja.md
  docs/README.ko.md
  docs/README.pt-br.md
  docs/README.tr.md
  docs/README.zh-Hant.md
Labels: do-not-merge/release-note-label-needed
