Repository 1Panel-dev/1Panel, pull requests merged in 2024-11, with the labels that each got.

#6918 feat: 概览-状态,磁盘数量多过时默认收起
  frontend/src/views/home/status/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved

#6925 fix: 优化容器创建提示信息
  frontend/src/views/container/container/operate/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#6943 style: 组件样式调整
  frontend/src/components/app-status/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#6944 feat: 优化缓存二级路由方式
  frontend/src/components/complex-table/index.vue
  frontend/src/components/layout-content/index.vue
  frontend/src/routers/index.ts
  frontend/src/routers/modules/website.ts
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#6963 Update OWNERS
  OWNERS
Labels: do-not-merge/release-note-label-needed, dev

#6962 fix: 解决面板证书信息获取失败的问题
  backend/app/service/setting.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#6967 fix: 优化防火墙端口转发错误信息
  backend/app/service/firewall.go
  backend/constant/errs.go
  backend/i18n/lang/en.yaml
  backend/i18n/lang/zh-Hant.yaml
  backend/i18n/lang/zh.yaml
  backend/utils/firewall/client.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#6961 feat: 增加阿里云盘备份账号
  agent/constant/backup.go
  agent/go.mod
  agent/go.sum
  agent/utils/cloud_storage/client/ali.go
  agent/utils/cloud_storage/cloud_storage_client.go
  core/app/model/backup.go
  core/app/service/backup.go
  core/constant/common.go
  core/init/migration/migrate.go
  core/init/migration/migrations/init.go
  core/utils/cloud_storage/client/ali.go
  core/utils/cloud_storage/client/onedrive.go
  core/utils/cloud_storage/client/oss.go
  core/utils/cloud_storage/client/s3.go
  core/utils/cloud_storage/client/sftp.go
  core/utils/cloud_storage/client/webdav.go
  core/utils/cloud_storage/cloud_storage_client.go
  frontend/src/api/interface/backup.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/cronjob/backup/index.vue
  frontend/src/views/setting/backup-account/operate/index.vue
  frontend/src/views/setting/snapshot/index.vue
  go.mod
  go.sum
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#6964 feat: 增加自定义主题颜色，调整默认暗色主题配色
  frontend/src/assets/images/menu-bg.svg
  frontend/src/components/app-status/index.vue
  frontend/src/components/license-import/index.vue
  frontend/src/components/router-button/index.vue
  frontend/src/components/system-upgrade/index.vue
  frontend/src/components/v-charts/components/Pie.vue
  frontend/src/hooks/use-theme.ts
  frontend/src/layout/components/AppFooter.vue
  frontend/src/layout/components/Sidebar/components/Collapse.vue
  frontend/src/layout/components/Sidebar/components/Logo.vue
  frontend/src/layout/components/Sidebar/index.vue
  frontend/src/layout/index.vue
  frontend/src/store/interface/index.ts
  frontend/src/store/modules/global.ts
  frontend/src/styles/common.scss
  frontend/src/styles/element-dark.scss
  frontend/src/styles/element.scss
  frontend/src/utils/theme.ts
  frontend/src/utils/theme/tool.ts
  frontend/src/utils/xpack.ts
  frontend/src/views/home/app/index.vue
  frontend/src/views/host/terminal/terminal/index.vue
  frontend/src/views/login/components/login-form.vue
  frontend/src/views/setting/license/index.vue
  frontend/src/views/setting/panel/index.vue
  frontend/src/views/setting/panel/theme-color/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#6979 docs: Update README.md
  README.md
Labels: do-not-merge/release-note-label-needed

#6983 feat: 修改应用安装超时时间
  backend/app/service/app_utils.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#6986 feat: 面板代理服务器提供 docker 代理
  backend/app/service/docker.go
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/utils/util.ts
  frontend/src/views/setting/panel/index.vue
  frontend/src/views/setting/panel/proxy/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm

#7002 perf: 优化主题色及样式
  frontend/src/components/log-file/index.vue
  frontend/src/components/terminal/index.vue
  frontend/src/styles/element-dark.scss
  frontend/src/styles/element.scss
  frontend/src/utils/xpack.ts
  frontend/src/views/app-store/apps/index.vue
  frontend/src/views/database/mysql/index.vue
  frontend/src/views/database/postgresql/index.vue
  frontend/src/views/database/redis/index.vue
  frontend/src/views/home/index.vue
  frontend/src/views/host/terminal/command/index.vue
  frontend/src/views/host/terminal/terminal/index.vue
  frontend/src/views/log/operation/index.vue
  frontend/src/views/login/components/login-form.vue
  frontend/src/views/setting/panel/index.vue
  frontend/src/views/setting/panel/theme-color/index.vue
  frontend/src/views/website/runtime/php/create/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm

#7009 perf: 优化主题色及样式
  frontend/src/components/app-status/index.vue
  frontend/src/styles/element-dark.scss
  frontend/src/views/app-store/apps/index.vue
  frontend/src/views/login/components/login-form.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#7015 perf: 优化主题色及样式
  frontend/src/components/app-status/index.vue
  frontend/src/components/router-button/index.vue
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/styles/element-dark.scss
  frontend/src/views/app-store/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#7016 perf: 优化 docker 代理
  frontend/src/styles/element-dark.scss
  frontend/src/styles/reset.scss
  frontend/src/views/setting/panel/proxy/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#7019 fix: 修改面板证书显示域名信息
  backend/app/service/setting.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#7026 style: 面板样式优化
  frontend/src/components/system-upgrade/index.vue
  frontend/src/layout/components/Sidebar/components/Collapse.vue
  frontend/src/views/database/mysql/check/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#7027 fix: 优化登陆页面特征信息
  backend/app/api/v1/auth.go
  backend/middleware/bind_domain.go
  backend/middleware/helper.go
  backend/middleware/ip_limit.go
  frontend/src/api/index.ts
  frontend/src/components/error-message/error_code.vue
  frontend/src/views/login/entrance/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#7023 fix: 优化概览页磁盘显示
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/layout/components/AppFooter.vue
  frontend/src/views/home/index.vue
  frontend/src/views/home/status/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#7028 fix: 关闭代理同时更新 Docker 代理
  backend/app/service/docker.go
  frontend/src/views/setting/panel/proxy/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#7029 feat: 面板目录禁止删除
  backend/app/service/file.go
  backend/constant/errs.go
  backend/i18n/lang/en.yaml
  backend/i18n/lang/zh-Hant.yaml
  backend/i18n/lang/zh.yaml
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/host/file-management/delete/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#7031 fix: 删除目录校验是否为禁止删除的目录
  backend/app/service/file.go
  frontend/src/views/host/file-management/delete/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#7035 fix: 删除目录校验
  backend/app/service/file.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#7036 feat: 主题色保存/恢复增加确认提示
  frontend/src/views/setting/panel/theme-color/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#7045 fix: 导入恢复限制文件数量
  frontend/src/components/upload/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#7047 fix: 编辑计划任务和病毒扫描告警问题处理
  backend/app/service/clam.go
  backend/app/service/cronjob.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm

#7048 fix: 客户端缓存导致界面设置 Logo 不能正常显示
  frontend/src/hooks/use-logo.ts
  frontend/src/layout/components/Sidebar/components/Logo.vue
  frontend/src/utils/xpack.ts
  frontend/src/views/setting/about/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#7057 feat：WAF、网站监控增加日志定时清理
  agent/app/dto/response/file.go
  agent/app/service/file.go
  agent/utils/files/file_op.go
  frontend/src/styles/common.scss
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#7058 fix: 编辑计划任务和病毒扫描告警问题处理
  backend/app/service/clam.go
  backend/app/service/cronjob.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm

#7061 chore: Update README.md
  README.md
Labels: do-not-merge/release-note-label-needed

#7063 chore: Update README_EN.md
  docs/README_EN.md
Labels: do-not-merge/release-note-label-needed

#7006 feat: 增加火山引擎DNS
  backend/utils/ssl/client.go
  frontend/src/global/mimetype.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/website/ssl/dns-account/create/index.vue
  go.mod
  go.sum
Labels: do-not-merge/release-note-label-needed

#7075 fix: 修复许可证失效主题切换错误问题
  frontend/src/components/license-import/index.vue
  frontend/src/views/setting/panel/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#7076 feat：WAF 拦截日志支持导出
  agent/i18n/i18n.go
  agent/i18n/lang/en.yaml
  agent/i18n/lang/zh-Hant.yaml
  agent/i18n/lang/zh.yaml
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#7077 fix: 获取告警短信使用量
  frontend/src/api/interface/setting.ts
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#7081 feat: 增加DNS服务商CloudDNS
  backend/utils/ssl/client.go
  frontend/src/global/mimetype.ts
  frontend/src/views/website/ssl/dns-account/create/index.vue
Labels: do-not-merge/release-note-label-needed

#7087 feat: Echarts 组件适配主题颜色
  frontend/src/components/v-charts/components/Line.vue
  frontend/src/styles/element-dark.scss
  frontend/src/views/login/components/login-form.vue
Labels: do-not-merge/release-note-label-needed, dev

#7090 fix: 完善 license 同步失联逻辑
  backend/constant/status.go
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/utils/xpack.ts
  frontend/src/views/setting/license/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#7100 fix: 解决编辑端口规则不能保存的问题
  backend/app/service/firewall.go
Labels: do-not-merge/release-note-label-needed, lgtm, approved

#7106 fix: 统一 xpack 失联接口返回内容
  backend/constant/errs.go
  backend/i18n/lang/en.yaml
  backend/i18n/lang/zh-Hant.yaml
  backend/i18n/lang/zh.yaml
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#7109 build(deps): bump golang from 1.22 to 1.23
  .github/workflows/release-drafter.yml
  .goreleaser.yaml
Labels: do-not-merge/release-note-label-needed, dev

#7110 build(deps): bump goreleaser from v2 to v2.4.5
  .github/workflows/release-drafter.yml
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#7111 fix: 解决数据库切换版本不正确的问题
  backend/constant/errs.go
  frontend/src/components/app-status/index.vue
  frontend/src/views/database/mysql/index.vue
  frontend/src/views/database/postgresql/index.vue
  frontend/src/views/database/redis/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#7112 fix: 修改未激活状态下信息内容
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/setting/license/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#7113 style: 主题样式优化
  frontend/src/styles/element-dark.scss
  frontend/src/views/setting/license/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#7114 perf: remove go cache
  .github/workflows/release-drafter.yml
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#7120 feat: 完成 v2 构建 Makefile
  Makefile
  agent/go.mod
  agent/go.sum
  cmd/server/cmd/root.go
  core/middleware/proxy.go
  frontend/.env.production
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#7122 build(deps): bump goreleaser from v2.4.5 to latest
  .github/workflows/release-drafter.yml
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#7126 feat: optimize the SSH connection method for the host
  core/app/api/v2/host.go
  core/app/service/host.go
  core/constant/status.go
  core/utils/ssh/ssh.go
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#7142 feat(system-security): Optimized unauthenticated settings to enhance system security
  backend/app/api/v1/auth.go
  backend/app/service/auth.go
  backend/constant/common.go
  backend/init/router/router.go
  backend/router/ro_base.go
  cmd/server/res/error_msg.go
  cmd/server/res/html/200.html
  cmd/server/res/html/200_en.html
  cmd/server/res/html/400.html
  cmd/server/res/html/401.html
  cmd/server/res/html/403.html
  cmd/server/res/html/404.html
  cmd/server/res/html/408.html
  cmd/server/res/html/416.html
  cmd/server/res/html/500.html
  frontend/src/api/modules/auth.ts
  frontend/src/routers/modules/toolbox.ts
  frontend/src/views/login/entrance/index.vue
  frontend/src/views/login/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm

#7141 fix: Fixed the fault in determining the firewall port forwarding version
  backend/app/service/firewall.go
  backend/constant/errs.go
  backend/i18n/lang/en.yaml
  backend/i18n/lang/zh-Hant.yaml
  backend/i18n/lang/zh.yaml
  backend/utils/firewall/client/iptables.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#7143 feat(system-security): Added 444 and 500 responses for unauthenticate setting
  backend/constant/common.go
  backend/init/router/router.go
  cmd/server/res/html/500.html
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/setting/safe/response/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#7146 feat: Add API interface authentication function
  backend/app/api/v1/setting.go
  backend/app/dto/setting.go
  backend/app/service/setting.go
  backend/configs/system.go
  backend/constant/errs.go
  backend/i18n/lang/en.yaml
  backend/i18n/lang/zh-Hant.yaml
  backend/i18n/lang/zh.yaml
  backend/init/hook/hook.go
  backend/init/migration/migrate.go
  backend/init/migration/migrations/v_1_10.go
  backend/middleware/session.go
  backend/router/ro_setting.go
  cmd/server/docs/docs.go
  cmd/server/docs/swagger.json
  cmd/server/docs/swagger.yaml
  cmd/server/main.go
  frontend/src/api/interface/setting.ts
  frontend/src/api/modules/setting.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/styles/element-dark.scss
  frontend/src/styles/element.scss
  frontend/src/views/container/image/pull/index.vue
  frontend/src/views/host/terminal/terminal/index.vue
  frontend/src/views/log/operation/index.vue
  frontend/src/views/setting/panel/api-interface/index.vue
  frontend/src/views/setting/panel/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm

#7150 fix: Fixed the fault in determining the firewall port forwarding version
  backend/utils/firewall/client/firewalld.go
  backend/utils/firewall/client/iptables.go
  backend/utils/firewall/client/ufw.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#7152 feat(system-security): Support Hot Reloading of System Certificates
  backend/app/service/website_ca.go
  backend/app/service/website_ssl.go
  backend/app/service/website_utils.go
  backend/constant/common.go
  backend/cron/job/ssl.go
  backend/i18n/lang/en.yaml
  backend/i18n/lang/zh-Hant.yaml
  backend/i18n/lang/zh.yaml
  backend/server/server.go
  frontend/src/api/interface/setting.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/routers/modules/setting.ts
  frontend/src/views/setting/safe/index.vue
  frontend/src/views/setting/safe/ssl/index.vue
  go.mod
  go.sum
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#7155 feat(runtime): Add .NET runtime
  backend/app/service/app_utils.go
  backend/app/service/runtime.go
  backend/app/service/runtime_utils.go
  backend/app/service/website.go
  backend/app/service/website_utils.go
  backend/constant/common.go
  backend/constant/runtime.go
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/routers/modules/website.ts
  frontend/src/views/app-store/apps/index.vue
  frontend/src/views/app-store/detail/index.vue
  frontend/src/views/home/app/index.vue
  frontend/src/views/website/runtime/donet/index.vue
  frontend/src/views/website/runtime/donet/operate/index.vue
  frontend/src/views/website/runtime/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#7172 feat(runtime): correct typo in variable name
  backend/app/service/runtime.go
  backend/app/service/runtime_utils.go
  backend/app/service/website.go
  backend/app/service/website_utils.go
  backend/constant/common.go
  backend/constant/runtime.go
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/routers/modules/website.ts
  frontend/src/views/app-store/apps/index.vue
  frontend/src/views/app-store/detail/index.vue
  frontend/src/views/home/app/index.vue
  frontend/src/views/website/runtime/dotnet/index.vue
  frontend/src/views/website/runtime/dotnet/operate/index.vue
  frontend/src/views/website/runtime/index.vue
Labels: do-not-merge/release-note-label-needed, dev

#7169 fix: 解决更新端口不更新防火墙规则的问题
  cmd/server/cmd/update.go
Labels: do-not-merge/release-note-label-needed, lgtm

#7173 feat(website): Optimize website error_log configuration
  backend/app/service/website.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#7178 feat(system-upgrade): Added support for multi-host upgrade and rollback
  .gitignore
  Makefile
  agent/app/service/snapshot_create.go
  agent/app/service/snapshot_recover.go
  agent/app/service/snapshot_rollback.go
  agent/init/hook/hook.go
  agent/init/migration/migrate.go
  agent/init/migration/migrations/init.go
  agent/init/viper/viper.go
  cmd/server/cmd/restore.go
  core/app/dto/task.go
  core/app/model/task.go
  core/app/model/upgrade_log.go
  core/app/repo/common.go
  core/app/repo/task.go
  core/app/repo/upgrade_log.go
  core/app/service/entry.go
  core/app/service/task.go
  core/app/service/upgrade.go
  core/app/task/task.go
  core/constant/status.go
  core/global/global.go
  core/i18n/i18n.go
  core/i18n/lang/en.yaml
  core/i18n/lang/zh-Hant.yaml
  core/i18n/lang/zh.yaml
  core/init/db/db.go
  core/init/hook/hook.go
  core/init/migration/migrate.go
  core/init/migration/migrations/init.go
  core/utils/files/files.go
  core/utils/ssh/ssh.go
  frontend/src/api/modules/setting.ts
Labels: do-not-merge/release-note-label-needed, dev-v2

#7185 feat(session): Refactor session storage implementation
  agent/app/api/v2/runtime.go
  agent/app/repo/app.go
  agent/app/repo/website.go
  agent/app/repo/website_acme_account.go
  agent/app/service/snapshot_create.go
  agent/cmd/server/nginx_conf/php_extensions.json
  core/app/service/auth.go
  core/init/cache/cache.go
  core/init/router/router.go
  core/init/session/psession/psession.go
  core/init/session/session.go
  core/middleware/session.go
  go.mod
  go.sum
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#7186 feat(file): Optimize file download progress tracking
  agent/app/api/v2/file.go
  agent/cron/cron.go
  agent/cron/job/cache.go
  agent/global/global.go
  agent/go.mod
  agent/go.sum
  agent/init/cache/badger_db/badger_db.go
  agent/init/cache/cache.go
  agent/init/cache/db/db.go
  agent/server/server.go
  agent/utils/files/file_op.go
  agent/utils/websocket/process_data.go
  core/global/global.go
  core/init/cache/badger_db/badger_db.go
  core/init/cache/cache.go
  core/init/router/router.go
  core/server/server.go
  go.mod
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#7196 feat(alert): Add alert settings
  frontend/src/assets/iconfont/iconfont.css
  frontend/src/assets/iconfont/iconfont.js
  frontend/src/assets/iconfont/iconfont.json
  frontend/src/assets/iconfont/iconfont.svg
  frontend/src/assets/iconfont/iconfont.ttf
  frontend/src/assets/iconfont/iconfont.woff
  frontend/src/assets/iconfont/iconfont.woff2
  frontend/src/assets/images/1panel-login.png
  frontend/src/components/router-button/index.vue
  frontend/src/global/form-rules.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/styles/element-dark.scss
  frontend/src/styles/element.scss
  frontend/src/views/host/terminal/terminal/index.vue
  frontend/src/views/setting/panel/api-interface/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#7191 feat(website): Handle uppercase domain names
  agent/app/service/website_utils.go
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#7192 feat(cmd): Add support for internationalization of 1Panel commands
  backend/global/global.go
  backend/i18n/i18n.go
  backend/i18n/lang/en.yaml
  backend/i18n/lang/fa.yaml
  backend/i18n/lang/zh-Hant.yaml
  backend/i18n/lang/zh.yaml
  cmd/server/cmd/app.go
  cmd/server/cmd/listen-ip.go
  cmd/server/cmd/reset.go
  cmd/server/cmd/restore.go
  cmd/server/cmd/root.go
  cmd/server/cmd/update.go
  cmd/server/cmd/user-info.go
  cmd/server/cmd/version.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#7203 fix(website): Fix Issue with Switching PHP Runtime Environment
  backend/app/service/website.go
  frontend/src/views/website/website/config/php/config/index.vue
  frontend/src/views/website/website/config/php/function/index.vue
  frontend/src/views/website/website/config/php/index.vue
  frontend/src/views/website/website/config/php/upload/index.vue
  frontend/src/views/website/website/config/php/version/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#7205 feat: Adapt to internationalization
  backend/app/api/v1/auth.go
  backend/configs/system.go
  backend/init/migration/migrations/init.go
  backend/init/viper/viper.go
  backend/router/ro_base.go
  cmd/server/conf/app.yaml
  frontend/src/api/modules/auth.ts
  frontend/src/components/system-upgrade/index.vue
  frontend/src/lang/modules/en.ts
  frontend/src/layout/components/Sidebar/index.vue
  frontend/src/store/interface/index.ts
  frontend/src/store/modules/global.ts
  frontend/src/views/cronjob/operate/index.vue
  frontend/src/views/home/index.vue
  frontend/src/views/login/components/login-form.vue
  frontend/src/views/setting/about/index.vue
  frontend/src/views/setting/index.vue
  frontend/src/views/setting/panel/index.vue
  frontend/src/views/toolbox/clam/operate/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#7210 Update README_EN.md
  docs/README_EN.md
Labels: do-not-merge/release-note-label-needed, dev

#7216 feat: merge from dev
  agent/app/api/v2/file.go
  agent/app/dto/backup.go
  agent/app/dto/response/file.go
  agent/app/repo/backup.go
  agent/app/service/app.go
  agent/app/service/app_install.go
  agent/app/service/app_utils.go
  agent/app/service/backup.go
  agent/app/service/backup_app.go
  agent/app/service/container.go
  agent/app/service/file.go
  agent/app/service/website.go
  agent/cmd/server/nginx_conf/proxy.conf
  agent/i18n/lang/en.yaml
  agent/i18n/lang/zh-Hant.yaml
  agent/i18n/lang/zh.yaml
  agent/utils/ssl/client.go
  frontend/src/components/log-file/index.vue
  frontend/src/components/router-button/index.vue
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/styles/common.scss
  frontend/src/styles/element-dark.scss
  frontend/src/styles/element.scss
  frontend/src/views/app-store/detail/install/index.vue
  frontend/src/views/app-store/installed/detail/index.vue
  frontend/src/views/app-store/installed/upgrade/index.vue
  frontend/src/views/host/file-management/detail/index.vue
  frontend/src/views/login/components/login-form.vue
  frontend/src/views/website/website/delete/index.vue
Labels: do-not-merge/release-note-label-needed, dev-v2

#7217 pref: Adjust node editing logic
  core/app/api/v2/upgrade.go
  core/app/repo/app_launcher.go
  core/app/repo/backup.go
  core/app/repo/command.go
  core/app/repo/common.go
  core/app/repo/group.go
  core/app/repo/host.go
  core/app/repo/logs.go
  core/app/repo/setting.go
  core/app/repo/task.go
  core/app/repo/upgrade_log.go
  core/app/service/command.go
  core/app/service/entry.go
  core/app/service/group.go
  core/app/service/host.go
  core/app/service/logs.go
  core/app/service/task.go
  core/app/service/upgrade.go
  core/global/global.go
  core/init/migration/migrations/init.go
  frontend/src/components/system-upgrade/index.vue
  frontend/src/components/system-upgrade/upgrade/index.vue
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/terminal/host/operate/index.vue
  frontend/src/views/terminal/terminal/host-create.vue
Labels: do-not-merge/release-note-label-needed, dev-v2

#7213 feat(website): Translate Chinese Parts of Website Default Files
  cmd/server/app/app_config.yml
  cmd/server/nginx_conf/index.html
  cmd/server/nginx_conf/index.php
  cmd/server/nginx_conf/stop.html
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#7214 pref: Remove Swagger description information
  backend/app/api/v1/app.go
  backend/app/api/v1/app_install.go
  backend/app/api/v1/auth.go
  backend/app/api/v1/backup.go
  backend/app/api/v1/clam.go
  backend/app/api/v1/command.go
  backend/app/api/v1/compose_template.go
  backend/app/api/v1/container.go
  backend/app/api/v1/cronjob.go
  backend/app/api/v1/dashboard.go
  backend/app/api/v1/database.go
  backend/app/api/v1/database_common.go
  backend/app/api/v1/database_mysql.go
  backend/app/api/v1/database_postgresql.go
  backend/app/api/v1/database_redis.go
  backend/app/api/v1/device.go
  backend/app/api/v1/docker.go
  backend/app/api/v1/fail2ban.go
  backend/app/api/v1/favorite.go
  backend/app/api/v1/file.go
  backend/app/api/v1/firewall.go
  backend/app/api/v1/ftp.go
  backend/app/api/v1/group.go
  backend/app/api/v1/host.go
  backend/app/api/v1/host_tool.go
  backend/app/api/v1/image.go
  backend/app/api/v1/image_repo.go
  backend/app/api/v1/logs.go
  backend/app/api/v1/monitor.go
  backend/app/api/v1/nginx.go
  backend/app/api/v1/php_extensions.go
  backend/app/api/v1/process.go
  backend/app/api/v1/recycle_bin.go
  backend/app/api/v1/runtime.go
  backend/app/api/v1/setting.go
  backend/app/api/v1/snapshot.go
  backend/app/api/v1/ssh.go
  backend/app/api/v1/upgrade.go
  backend/app/api/v1/website.go
  backend/app/api/v1/website_acme_account.go
  backend/app/api/v1/website_ca.go
  backend/app/api/v1/website_dns_account.go
  backend/app/api/v1/website_domain.go
  backend/app/api/v1/website_ssl.go
  cmd/server/docs/docs.go
  cmd/server/docs/swagger.json
  cmd/server/docs/swagger.yaml
  cmd/server/main.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved
