Repository 1Panel-dev/1Panel, pull requests merged in 2024-08, with the labels that each got.

#5993 style: 应用商店样式调整
  frontend/src/api/interface/app.ts
  frontend/src/views/app-store/apps/index.vue
  frontend/src/views/app-store/detail/index.vue
Labels: do-not-merge/release-note-label-needed, dev-v2

#5996 feat: 应用安装增加日志展示
  agent/app/dto/request/app.go
  agent/app/dto/request/file.go
  agent/app/repo/task.go
  agent/app/service/app.go
  agent/app/service/file.go
  agent/app/service/website.go
  agent/app/task/task.go
  agent/init/migration/migrations/init.go
  frontend/src/api/interface/app.ts
  frontend/src/components/task-log/index.vue
  frontend/src/views/app-store/detail/install/index.vue
  frontend/src/views/app-store/installed/index.vue
Labels: do-not-merge/release-note-label-needed, dev-v2

#6011 feat: 应用升级增加日志
  agent/app/dto/request/app.go
  agent/app/dto/request/file.go
  agent/app/model/task.go
  agent/app/repo/task.go
  agent/app/service/app.go
  agent/app/service/app_install.go
  agent/app/service/app_utils.go
  agent/app/service/file.go
  agent/app/service/runtime.go
  agent/app/service/website.go
  agent/app/task/task.go
  agent/i18n/lang/zh.yaml
  agent/init/migration/migrations/init.go
  frontend/src/components/task-log/index.vue
  frontend/src/views/app-store/detail/install/index.vue
  frontend/src/views/app-store/installed/index.vue
  frontend/src/views/app-store/installed/upgrade/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#6013 feat: 完成节点添加及删除功能
  agent/init/db/db.go
  agent/init/hook/hook.go
  agent/init/migration/migrations/init.go
  agent/init/router/router.go
  agent/server/server.go
  core/constant/errs.go
  core/constant/status.go
  core/i18n/lang/en.yaml
  core/i18n/lang/zh-Hant.yaml
  core/i18n/lang/zh.yaml
  core/middleware/proxy.go
  core/utils/common/common.go
  frontend/src/layout/components/Sidebar/index.vue
  go.mod
  go.sum
Labels: do-not-merge/release-note-label-needed, dev-v2

#6033 feat: 修改部分监控接口
  agent/app/api/v1/entry.go
  agent/app/api/v1/monitor.go
  agent/app/dto/host.go
  agent/app/repo/common.go
  agent/app/repo/monitor.go
  agent/app/service/entry.go
  agent/app/service/monitor.go
  agent/app/service/setting.go
  agent/init/migration/migrations/init.go
  agent/middleware/certificate.go
  agent/router/ro_host.go
  agent/server/server.go
  core/app/api/v1/setting.go
  core/router/ro_setting.go
  frontend/src/api/interface/host.ts
  frontend/src/api/modules/host.ts
  frontend/src/api/modules/setting.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/layout/components/Sidebar/index.vue
  frontend/src/utils/xpack.ts
  frontend/src/views/host/monitor/monitor/index.vue
  frontend/src/views/host/monitor/setting/days/index.vue
  frontend/src/views/host/monitor/setting/default-network/index.vue
  frontend/src/views/host/monitor/setting/index.vue
  frontend/src/views/host/monitor/setting/interval/index.vue
  frontend/src/views/login/components/login-form.vue
  frontend/src/views/setting/panel/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#6036 fix: 解决 PHP 运行环境网站删除之后没有删除应用的问题
  backend/app/dto/response/website.go
  backend/app/service/website.go
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/app-store/detail/install/index.vue
  frontend/src/views/app-store/installed/upgrade/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#6040 feat: 卸载应用支持删除镜像
  .gitignore
  agent/app/dto/request/app.go
  agent/app/service/app_install.go
  agent/app/service/app_utils.go
  agent/app/service/website.go
  frontend/src/api/interface/app.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/app-store/installed/delete/index.vue
Labels: do-not-merge/release-note-label-needed, dev-v2

#6042 feat: 优化接口文档生成
  agent/cmd/server/docs/docs.go
  agent/cmd/server/docs/swagger.go
  agent/cmd/server/docs/swagger.json
  agent/cmd/server/docs/swagger.yaml
  agent/cmd/server/main.go
  agent/go.mod
  agent/go.sum
  cmd/server/docs/docs.go
  cmd/server/docs/swagger.go
  cmd/server/docs/swagger.json
  cmd/server/docs/swagger.yaml
  cmd/server/docs/swagger_test.go
  cmd/server/docs/x-log.json
  cmd/server/main.go
  core/app/api/v1/auth.go
  core/app/api/v1/logs.go
  core/app/api/v1/setting.go
  core/app/api/v1/upgrade.go
  core/init/router/router.go
  core/middleware/demo_handle.go
  core/middleware/operation.go
  core/middleware/proxy.go
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#6043 feat: 卸载应用增加任务日志
  agent/app/dto/app.go
  agent/app/dto/request/app.go
  agent/app/service/app_install.go
  agent/app/service/app_utils.go
  agent/app/task/task.go
  agent/i18n/lang/en.yaml
  agent/i18n/lang/zh-Hant.yaml
  agent/i18n/lang/zh.yaml
  frontend/src/api/interface/app.ts
  frontend/src/components/task-log/index.vue
  frontend/src/views/app-store/installed/delete/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#6044 feat: 创建反代网站支持直接选择应用
  agent/app/repo/app_install.go
  agent/app/service/app_install.go
  frontend/src/api/interface/app.ts
  frontend/src/views/website/website/create/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#6053 feat: 创建网站支持直接选择 SSL 证书并启用 HTTPS
  agent/app/dto/request/website.go
  agent/app/service/website.go
  agent/app/task/task.go
  agent/i18n/lang/en.yaml
  agent/i18n/lang/zh-Hant.yaml
  agent/i18n/lang/zh.yaml
  frontend/src/api/interface/website.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/website/website/config/basic/https/index.vue
  frontend/src/views/website/website/create/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#6056 feat: 网站支持设置 HTTPS 端口
  agent/app/dto/request/website.go
  agent/app/dto/response/website.go
  agent/app/model/website.go
  agent/app/service/website.go
  agent/app/service/website_utils.go
  agent/init/migration/migrations/init.go
  frontend/src/api/interface/website.ts
  frontend/src/views/website/website/config/basic/https/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#6058 chore:新建文件夹支持添加空格,登录页鼠标悬浮样式
  frontend/src/views/host/file-management/create/index.vue
  frontend/src/views/host/file-management/upload/index.vue
  frontend/src/views/login/components/login-form.vue
Labels: do-not-merge/release-note-label-needed

#6069 feat: 优化网站域名添加
  agent/app/dto/request/website.go
  agent/app/dto/response/website.go
  agent/app/model/website.go
  agent/app/model/website_domain.go
  agent/app/service/website.go
  agent/app/service/website_utils.go
  agent/init/migration/migrate.go
  agent/init/migration/migrations/init.go
  frontend/src/api/interface/website.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/website/website/config/basic/domain/create/index.vue
  frontend/src/views/website/website/config/basic/https/index.vue
  frontend/src/views/website/website/create/index.vue
  frontend/src/views/website/website/domain-create/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#6070 fix: 搜索框加长(#6063) 回收站时间排序(#5957) hvoer状态撑高界面(#5929)
  frontend/src/views/host/file-management/index.vue
  frontend/src/views/host/file-management/recycle-bin/index.vue
  frontend/src/views/website/runtime/go/index.vue
Labels: do-not-merge/release-note-label-needed

#6078 feat: 网站密码认证支持子目录
  agent/app/api/v2/website.go
  agent/app/dto/nginx.go
  agent/app/dto/request/nginx.go
  agent/app/dto/response/nginx.go
  agent/app/service/website.go
  agent/cmd/server/nginx_conf/nginx_conf.go
  agent/cmd/server/nginx_conf/path_auth.conf
  agent/router/ro_website.go
  frontend/src/api/interface/website.ts
  frontend/src/api/modules/website.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/website/website/config/basic/auth-basic/create/index.vue
  frontend/src/views/website/website/config/basic/auth-basic/index.vue
  frontend/src/views/website/website/config/basic/proxy/create/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#6077 chore:点击复制版本号(#5894)
  frontend/src/components/system-upgrade/index.vue
Labels: do-not-merge/release-note-label-needed

#6086 feat: 网站域名增加快速跳转
  frontend/src/views/website/website/index.vue
Labels: do-not-merge/release-note-label-needed, dev-v2

#6090 feat: 网站列可编辑显示
  frontend/src/views/website/website/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#6084 feat:更新应用列表上移 #6035
  frontend/src/views/app-store/index.vue
Labels: do-not-merge/release-note-label-needed

#6098 feat: 网站子目录绑定域名
  agent/app/api/v2/website.go
  agent/app/dto/request/website.go
  agent/app/dto/response/website.go
  agent/app/model/website.go
  agent/app/repo/website.go
  agent/app/service/website.go
  agent/app/service/website_utils.go
  agent/constant/website.go
  agent/i18n/lang/en.yaml
  agent/i18n/lang/zh-Hant.yaml
  agent/i18n/lang/zh.yaml
  agent/init/migration/migrations/init.go
  agent/router/ro_website.go
  core/configs/system.go
  frontend/src/api/interface/website.ts
  frontend/src/api/modules/website.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/cronjob/operate/index.vue
  frontend/src/views/website/website/config/basic/site-folder/index.vue
  frontend/src/views/website/website/create/index.vue
  frontend/src/views/website/website/delete/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#6103 feat: 优化网站日志在每行数据量大情况下的读取
  backend/utils/files/utils.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#6104 style: 优化文件属性页面显示
  frontend/src/views/host/file-management/detail/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#6105 style: 去掉应用列表中的更新应用列表按钮
  frontend/src/views/app-store/apps/index.vue
Labels: do-not-merge/release-note-label-needed

#6112 feat: 优化应用安装和删除逻辑
  agent/app/repo/app_install.go
  agent/app/service/app_install.go
  agent/app/service/app_utils.go
  agent/constant/app.go
  agent/utils/docker/compose.go
  agent/utils/files/utils.go
  frontend/src/components/status/index.vue
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/app-store/installed/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, dev-v2

#6116 feat: 应用升级备份保留 3 份
  backend/app/dto/backup.go
  backend/app/repo/backup.go
  backend/app/service/app_utils.go
  backend/app/service/backup.go
  backend/app/service/backup_app.go
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#6108 feat: 修改备份账号同步方式
  agent/app/api/v2/backup.go
  agent/app/dto/backup.go
  agent/app/dto/setting.go
  agent/app/model/backup.go
  agent/app/model/cronjob.go
  agent/app/model/snapshot.go
  agent/app/repo/backup.go
  agent/app/repo/cronjob.go
  agent/app/service/app.go
  agent/app/service/app_utils.go
  agent/app/service/backup.go
  agent/app/service/backup_app.go
  agent/app/service/backup_mysql.go
  agent/app/service/backup_postgresql.go
  agent/app/service/backup_redis.go
  agent/app/service/backup_website.go
  agent/app/service/cronjob.go
  agent/app/service/cronjob_backup.go
  agent/app/service/cronjob_helper.go
  agent/app/service/database.go
  agent/app/service/database_mysql.go
  agent/app/service/database_postgresql.go
  agent/app/service/snapshot.go
  agent/app/service/snapshot_create.go
  agent/app/service/snapshot_recover.go
  agent/configs/system.go
  agent/go.mod
  agent/go.sum
  agent/init/hook/hook.go
  agent/init/migration/migrate.go
  agent/init/migration/migrations/init.go
  agent/router/ro_setting.go
  agent/utils/http/master.go
  agent/utils/jwt/jwt.go
  core/app/api/v2/backup.go
  core/app/dto/common.go
  core/app/repo/common.go
  core/app/service/auth.go
  core/app/service/backup.go
  core/configs/system.go
  core/init/hook/hook.go
  core/init/migration/migrations/init.go
  core/init/router/router.go
  core/router/ro_agent.go
  core/utils/jwt/jwt.go
  frontend/src/layout/components/Sidebar/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, dev-v2

#6120 feat: 修改备份账号同步方式
  agent/app/api/v2/backup.go
  agent/app/api/v2/health.go
  agent/app/dto/backup.go
  agent/app/dto/cronjob.go
  agent/app/dto/setting.go
  agent/app/model/backup.go
  agent/app/model/cronjob.go
  agent/app/model/snapshot.go
  agent/app/service/app_utils.go
  agent/app/service/backup.go
  agent/app/service/cronjob.go
  agent/app/service/cronjob_backup.go
  agent/configs/system.go
  agent/global/global.go
  agent/init/db/db.go
  agent/init/hook/hook.go
  agent/init/migration/migrate.go
  agent/init/migration/migrations/init.go
  agent/init/router/router.go
  agent/middleware/certificate.go
  agent/server/server.go
  agent/utils/encrypt/encrypt.go
  agent/utils/http/master.go
  core/app/api/v2/backup.go
  core/app/dto/backup.go
  core/app/dto/setting.go
  core/app/service/backup.go
  core/app/service/setting.go
  core/configs/system.go
  core/constant/errs.go
  core/i18n/lang/zh.yaml
  core/init/hook/hook.go
  core/init/migration/migrate.go
  core/init/migration/migrations/init.go
  core/init/router/router.go
  core/middleware/jwt.go
  core/router/ro_agent.go
  core/router/ro_backup.go
  core/utils/xpack/xpack.go
  frontend/src/api/interface/backup.ts
  frontend/src/api/interface/cronjob.ts
  frontend/src/api/interface/setting.ts
  frontend/src/api/modules/setting.ts
  frontend/src/api/modules/website.ts
  frontend/src/components/backup/index.vue
  frontend/src/components/upload/index.vue
  frontend/src/views/cronjob/backup/index.vue
  frontend/src/views/cronjob/operate/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#6123 fix: 移除 gorm 类型参数
  agent/app/dto/response/website.go
  agent/app/model/app.go
  agent/app/model/app_detail.go
  agent/app/model/app_install.go
  agent/app/model/app_install_resource.go
  agent/app/model/app_tag.go
  agent/app/model/clam.go
  agent/app/model/command.go
  agent/app/model/compose_template.go
  agent/app/model/database.go
  agent/app/model/database_mysql.go
  agent/app/model/database_postgresql.go
  agent/app/model/favorite.go
  agent/app/model/firewall.go
  agent/app/model/ftp.go
  agent/app/model/group.go
  agent/app/model/host.go
  agent/app/model/image_repo.go
  agent/app/model/monitor.go
  agent/app/model/php_extensions.go
  agent/app/model/runtime.go
  agent/app/model/setting.go
  agent/app/model/tag.go
  agent/app/model/website_dns_account.go
  agent/app/model/website_domain.go
  cmd/server/cmd/root.go
  core/app/model/backup.go
  core/app/model/logs.go
  core/app/model/setting.go
Labels: do-not-merge/release-note-label-needed, dev-v2

#6125 fix: 解决 PHP 运行环境版本过期之后下载安装包失败的问题
  backend/app/service/app.go
  backend/utils/http/request.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#6127 style: 部分页面增加自适应
  agent/app/repo/app_install.go
  agent/app/service/app.go
  agent/app/service/website.go
  agent/utils/http/request.go
  frontend/src/api/modules/website.ts
  frontend/src/components/layout-content/index.vue
  frontend/src/components/log-file/index.vue
  frontend/src/components/main-div/index.vue
  frontend/src/views/container/compose/create/index.vue
  frontend/src/views/container/image/build/index.vue
  frontend/src/views/container/image/pull/index.vue
  frontend/src/views/container/image/push/index.vue
  frontend/src/views/cronjob/operate/index.vue
  frontend/src/views/log/system/index.vue
  frontend/src/views/website/website/config/log/log-fiile/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#6136 fix: 解决部分应用参数数据库显示错误的问题
  backend/app/service/app_install.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#6139 feat: 完善节点管理功能
  agent/app/api/v2/dashboard.go
  agent/app/api/v2/helper/helper.go
  agent/app/dto/dashboard.go
  agent/app/service/backup.go
  agent/app/service/dashboard.go
  agent/constant/errs.go
  agent/constant/session.go
  agent/i18n/lang/en.yaml
  agent/i18n/lang/zh-Hant.yaml
  agent/i18n/lang/zh.yaml
  agent/router/ro_dashboard.go
  core/app/service/backup.go
  frontend/src/api/index.ts
  frontend/src/components/table-setting/index.vue
  frontend/src/utils/util.ts
  frontend/src/views/home/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#6142 fix: 解决计划任务备份内容允许为空的校验问题
  .gitignore
  frontend/src/views/cronjob/operate/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#6145 fix: 修改镜像拉取校验规则
  frontend/src/global/form-rules.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#6147 fix:mysql升级到8.4后查询会出错，容器的command回显使用 text area
  backend/app/service/database_mysql.go
  frontend/src/views/container/container/operate/index.vue
Labels: do-not-merge/release-note-label-needed

#6149 fix: mysql 绑定用户增加输入校验
  backend/app/service/database_mysql.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#6153 feat: 负载均衡增加源文编辑
  agent/app/api/v2/website.go
  agent/app/dto/nginx.go
  agent/app/dto/request/website.go
  agent/app/service/website.go
  agent/router/ro_website.go
  agent/utils/nginx/components/upstream.go
  frontend/src/api/interface/website.ts
  frontend/src/api/modules/website.ts
  frontend/src/views/website/website/config/basic/load-balance/file/index.vue
  frontend/src/views/website/website/config/basic/load-balance/index.vue
  frontend/src/views/website/website/config/basic/load-balance/operate/index.vue
Labels: do-not-merge/release-note-label-needed, dev-v2

#6172 perf: 优化运行环境日志卡顿情况
  backend/app/dto/response/file.go
  backend/app/service/file.go
  frontend/src/components/log-file/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#6173 fix: 解决 redis 没有密码情况下安装应用没有关联的问题
  backend/app/service/app_utils.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#6175 fix: 统一时区获取方法
  backend/app/api/v1/cronjob.go
  backend/app/api/v1/monitor.go
  backend/app/repo/backup.go
  backend/app/service/clam.go
  backend/app/service/container_volume.go
  backend/app/service/ssh.go
  backend/cron/cron.go
  backend/cron/job/ssl.go
  backend/cron/job/website.go
  backend/middleware/password_expired.go
  backend/utils/common/common.go
  frontend/src/views/toolbox/device/time-zone/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#6183 style: 处理代码警告
  .gitignore
  backend/app/service/app.go
  backend/app/service/file.go
  backend/app/service/image.go
  backend/app/service/snapshot.go
  backend/app/service/snapshot_recover.go
  backend/app/service/website.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#6185 fix: 解决路由菜单文字丢失的问题
  frontend/package.json
  frontend/src/components/router-button/index.vue
  frontend/src/styles/common.scss
  frontend/src/styles/element-dark.scss
  frontend/src/styles/element.scss
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#6187 fix: 修改版本号复制方式
  backend/app/service/clam.go
  frontend/src/components/system-upgrade/index.vue
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/cronjob/index.vue
  frontend/src/views/setting/safe/index.vue
  frontend/src/views/toolbox/clam/status/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#6188 feat: 优化已安装应用的参数显示
  frontend/package.json
  frontend/src/views/app-store/installed/detail/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#6189 feat: 修改非 PHP 运行环境网站的删除提示
  backend/app/dto/response/website.go
  backend/app/service/website.go
  frontend/src/api/interface/website.ts
  frontend/src/components/log-file/index.vue
  frontend/src/views/log/system/index.vue
  frontend/src/views/website/website/delete/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#6190 feat: 修复代码警告
  frontend/src/views/login/components/login-form.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#6184 feat: 告警通知
  backend/app/repo/website_ssl.go
  backend/constant/alert.go
  backend/constant/errs.go
  backend/i18n/lang/en.yaml
  backend/i18n/lang/zh-Hant.yaml
  backend/i18n/lang/zh.yaml
  backend/init/migration/migrate.go
  backend/init/migration/migrations/v_1_10.go
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
Labels: do-not-merge/release-note-label-needed, dev

#6192 fix: 解决删除 PHP 运行环境之后，删除其他网站提示错误的问题
  frontend/src/views/website/website/delete/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#6193 feat: 优化应用启动
  agent/app/dto/response/website.go
  agent/app/service/app_install.go
  agent/app/service/website.go
  frontend/src/api/interface/website.ts
  frontend/src/views/website/website/delete/index.vue
  frontend/src/views/website/website/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#6196 fix: 压缩增加 *.socket 排除规则
  backend/app/service/cronjob_helper.go
  backend/app/service/snapshot_create.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#6195 fix: 切换子节点请求方式
  Makefile
  agent/app/api/v2/backup.go
  agent/app/api/v2/health.go
  agent/app/service/backup.go
  agent/configs/system.go
  agent/constant/session.go
  agent/init/hook/hook.go
  agent/init/migration/migrations/init.go
  agent/router/ro_setting.go
  agent/utils/http/master.go
  agent/utils/xpack/xpack.go
  core/app/api/v2/backup.go
  core/init/router/router.go
  core/router/ro_agent.go
  core/utils/encrypt/encrypt.go
  core/utils/xpack/xpack.go
  frontend/src/api/modules/setting.ts
  frontend/src/components/backup/index.vue
  frontend/src/components/upload/index.vue
  frontend/src/views/app-store/installed/backup/index.vue
  frontend/src/views/app-store/installed/recover/index.vue
  frontend/src/views/cronjob/backup/index.vue
  frontend/src/views/cronjob/operate/index.vue
  frontend/src/views/database/redis/setting/persistence/index.vue
  frontend/src/views/setting/snapshot/import/index.vue
  frontend/src/views/setting/snapshot/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#6200 fix: 优化 repo 部分公共方法
  agent/app/api/v2/helper/helper.go
  agent/app/repo/app.go
  agent/app/repo/backup.go
  agent/app/repo/common.go
  agent/app/repo/database.go
  agent/app/repo/database_mysql.go
  agent/app/repo/database_postgresql.go
  agent/app/repo/runtime.go
  agent/app/repo/task.go
  agent/app/repo/website.go
  agent/app/service/app.go
  agent/app/service/app_install.go
  agent/app/service/app_utils.go
  agent/app/service/backup.go
  agent/app/service/backup_app.go
  agent/app/service/clam.go
  agent/app/service/compose_template.go
  agent/app/service/container.go
  agent/app/service/cronjob.go
  agent/app/service/cronjob_helper.go
  agent/app/service/database.go
  agent/app/service/database_mysql.go
  agent/app/service/database_postgresql.go
  agent/app/service/file.go
  agent/app/service/image_repo.go
  agent/app/service/runtime.go
  agent/app/service/snapshot.go
  agent/app/service/task.go
  agent/app/service/website.go
  agent/constant/errs.go
  agent/i18n/lang/en.yaml
  agent/i18n/lang/zh-Hant.yaml
  agent/i18n/lang/zh.yaml
  core/app/repo/command.go
  core/app/repo/common.go
  core/app/repo/host.go
  core/app/repo/logs.go
  core/app/repo/setting.go
  core/app/service/command.go
  core/app/service/host.go
  core/app/service/setting.go
  frontend/src/components/group/index.vue
  frontend/src/views/cronjob/operate/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#6204 feat: 应用详情增加架构信息
  agent/app/dto/app.go
  agent/app/dto/request/app.go
  agent/app/dto/response/app.go
  agent/app/model/app.go
  agent/app/repo/app.go
  agent/app/service/app.go
  agent/app/service/app_utils.go
  agent/init/migration/migrate.go
  agent/init/migration/migrations/init.go
  frontend/src/api/interface/app.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/app-store/apps/index.vue
  frontend/src/views/app-store/detail/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#6208 feat: 增加终端自定义配置
  core/app/api/v2/setting.go
  core/app/dto/setting.go
  core/app/service/setting.go
  core/init/migration/migrate.go
  core/init/migration/migrations/init.go
  core/router/ro_setting.go
  frontend/src/api/interface/setting.ts
  frontend/src/api/modules/setting.ts
  frontend/src/components/terminal/index.vue
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/store/index.ts
  frontend/src/store/interface/index.ts
  frontend/src/store/modules/terminal.ts
  frontend/src/views/setting/backup-account/index.vue
  frontend/src/views/setting/backup-account/operate/index.vue
  frontend/src/views/terminal/index.vue
  frontend/src/views/terminal/setting/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#6210 style: 优化 switch 组件 small 尺寸样式
  frontend/src/styles/reset.scss
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#6211 feat: 告警通知功能完善
  frontend/src/assets/iconfont/iconfont.css
  frontend/src/assets/iconfont/iconfont.js
  frontend/src/assets/iconfont/iconfont.json
  frontend/src/assets/iconfont/iconfont.svg
  frontend/src/assets/iconfont/iconfont.ttf
  frontend/src/assets/iconfont/iconfont.woff
  frontend/src/assets/iconfont/iconfont.woff2
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#6216 fix: 优化防火墙启动时自动添加端口功能
  backend/app/service/firewall.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#6219 fix: 优化部分频繁打印的日志操作
  backend/app/service/cronjob_helper.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#6217 feat: 增加同步本地应用接口
  agent/app/api/v2/app.go
  agent/app/service/app.go
  agent/i18n/lang/en.yaml
  agent/i18n/lang/zh-Hant.yaml
  agent/i18n/lang/zh.yaml
  agent/router/ro_app.go
  frontend/src/api/modules/app.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/app-store/apps/index.vue
Labels: do-not-merge/release-note-label-needed, dev-v2

#6221 feat: 优化数据库备份页面样式
  frontend/src/components/backup/index.vue
  frontend/src/views/app-store/installed/backup/index.vue
  frontend/src/views/app-store/installed/recover/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#6220 feat: 创建运行环境网站，校验 PHP 镜像是否存在
  backend/app/service/website.go
  backend/i18n/lang/en.yaml
  backend/i18n/lang/zh-Hant.yaml
  backend/i18n/lang/zh.yaml
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#6224 feat: 应用增加内存需求展示
  agent/app/dto/app.go
  agent/app/dto/response/app.go
  agent/app/model/app.go
  agent/app/service/app_utils.go
  agent/app/task/task.go
  agent/cmd/server/conf/app.yaml
  agent/i18n/lang/en.yaml
  agent/i18n/lang/zh-Hant.yaml
  agent/i18n/lang/zh.yaml
  agent/init/migration/migrations/init.go
  frontend/src/api/interface/app.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/app-store/detail/index.vue
  frontend/src/views/app-store/detail/install/index.vue
  frontend/src/views/website/website/create/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#6225 fix: 解决容器配置修改后未重启的问题
  backend/app/service/docker.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#6227 pref: 完善告警通知
  backend/utils/common/common.go
  backend/utils/websocket/process_data.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#6228 fix: 解决备份导入失败的问题
  frontend/src/components/upload/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#6235 feat:显示当前ip,系统网络代理地址
  backend/app/dto/dashboard.go
  backend/app/service/dashboard.go
  frontend/src/api/interface/dashboard.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/home/index.vue
Labels: do-not-merge/release-note-label-needed

#6246 feat: 应用支持启用 GPU
  agent/app/api/v2/app.go
  agent/app/dto/app.go
  agent/app/dto/request/app.go
  agent/app/dto/response/app.go
  agent/app/model/app.go
  agent/app/service/app.go
  agent/app/service/app_utils.go
  agent/init/migration/migrations/init.go
  frontend/src/api/interface/app.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/app-store/detail/install/index.vue
Labels: do-not-merge/release-note-label-needed, dev-v2

#6248 feat: 应用增加 Web 访问地址
  agent/app/api/v2/app_install.go
  agent/app/dto/request/app.go
  agent/app/dto/response/app.go
  agent/app/model/app_install.go
  agent/app/service/app_install.go
  agent/app/service/app_utils.go
  agent/init/migration/migrate.go
  agent/init/migration/migrations/init.go
  agent/router/ro_app.go
  frontend/src/api/interface/app.ts
  frontend/src/api/modules/app.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/app-store/installed/detail/index.vue
  frontend/src/views/app-store/installed/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#6250 feat: 应用商店设置增加默认访问地址
  agent/app/api/v2/app.go
  agent/app/dto/request/app.go
  agent/app/dto/response/app.go
  agent/app/service/app.go
  agent/app/service/setting.go
  agent/router/ro_app.go
  frontend/src/api/interface/app.ts
  frontend/src/api/modules/app.ts
  frontend/src/global/form-rules.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/routers/modules/app-store.ts
  frontend/src/views/app-store/index.vue
  frontend/src/views/app-store/installed/detail/index.vue
  frontend/src/views/app-store/installed/index.vue
  frontend/src/views/app-store/setting/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, dev-v2

#6263 pref: 完善告警通知任务
  backend/utils/common/common.go
Labels: do-not-merge/release-note-label-needed, dev

#6251 feat:显示当前ip,系统网络代理地址
  backend/app/dto/dashboard.go
  backend/app/service/dashboard.go
  frontend/src/api/interface/dashboard.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/home/index.vue
Labels: do-not-merge/release-note-label-needed

#6264 feat: 应用增加面板版本限制
  agent/app/dto/app.go
  agent/app/service/app.go
  agent/app/service/app_utils.go
  agent/i18n/lang/en.yaml
  agent/i18n/lang/zh-Hant.yaml
  agent/i18n/lang/zh.yaml
Labels: do-not-merge/release-note-label-needed, lgtm, dev-v2

#6272 fix: 解决备份套接字忽略不完的问题
  backend/app/api/v1/snapshot.go
  backend/app/dto/setting.go
  backend/app/service/cronjob_helper.go
  backend/app/service/snapshot.go
  backend/app/service/snapshot_create.go
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/home/index.vue
  frontend/src/views/setting/snapshot/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#6273 fix: 解决快照套接字忽略失败的问题
  backend/app/service/snapshot_create.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#6275 fix: 修改 PostgreSQL 容器内部端口
  frontend/src/views/database/postgresql/conn/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#6277 feat: OpenResty 安装支持指定网站目录
  agent/app/model/app_install.go
  agent/app/service/app.go
  agent/app/service/app_utils.go
  agent/i18n/lang/en.yaml
  agent/i18n/lang/zh-Hant.yaml
  agent/i18n/lang/zh.yaml
  agent/init/migration/migrations/init.go
  agent/utils/docker/compose.go
  frontend/src/components/container-log/index.vue
  frontend/src/views/app-store/installed/delete/index.vue
  frontend/src/views/app-store/installed/upgrade/index.vue
  frontend/src/views/website/website/config/basic/proxy/create/index.vue
  frontend/src/views/website/website/nginx/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#6297 feat: OpenResty 卸载不删除网站
  agent/app/service/app_install.go
  agent/app/service/app_utils.go
  agent/app/service/file.go
  agent/app/service/nginx_utils.go
  agent/app/service/website.go
  agent/app/service/website_utils.go
  frontend/src/components/app-status/index.vue
  frontend/src/views/website/website/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#6300 feat: 删除证书自动吊销证书
  agent/app/service/website_ssl.go
  agent/utils/ssl/client.go
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2
