Repository 1Panel-dev/1Panel, pull requests merged in 2024-04, with the labels that each got.

#4373 fix: 处理时序攻击漏洞
  backend/app/service/auth.go
  backend/i18n/lang/en.yaml
  backend/i18n/lang/zh-Hant.yaml
  backend/i18n/lang/zh.yaml
  frontend/src/components/config-card/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4375 pref: 修改描述信息
  .gitignore
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4376 pref: 优化 Xpack 错误信息
  backend/constant/errs.go
  backend/i18n/lang/en.yaml
  backend/i18n/lang/zh-Hant.yaml
  backend/i18n/lang/zh.yaml
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4377 feat: 修改 WAF 专业版提示
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4380 feat: 删除部分 .gitignore
  .gitignore
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4382 pref: 优化界面设置提示信息
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4389 fix: 解决容器挂载卷回显失败的问题
  backend/app/dto/container.go
  backend/app/service/container.go
  frontend/src/api/interface/container.ts
  frontend/src/components/log-file/index.vue
  frontend/src/views/container/compose/create/index.vue
  frontend/src/views/container/container/operate/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4391 pref: 专业版界面增加图标显示
  frontend/src/assets/iconfont/iconfont.css
  frontend/src/assets/iconfont/iconfont.js
  frontend/src/assets/iconfont/iconfont.json
  frontend/src/assets/iconfont/iconfont.svg
  frontend/src/assets/iconfont/iconfont.ttf
  frontend/src/assets/iconfont/iconfont.woff
  frontend/src/assets/iconfont/iconfont.woff2
  frontend/src/components/license-import/index.vue
  frontend/src/components/system-upgrade/index.vue
  frontend/src/views/setting/license/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4392 feat: 专业版菜单隐藏控制功能实现
  backend/app/dto/setting.go
  backend/init/migration/migrate.go
  backend/init/migration/migrations/v_1_10.go
  frontend/src/api/interface/setting.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/layout/components/Sidebar/index.vue
  frontend/src/routers/router.ts
  frontend/src/views/setting/panel/hidemenu/index.vue
  frontend/src/views/setting/panel/index.vue
Labels: do-not-merge/release-note-label-needed, dev

#4393 提升文件上传体验
  backend/app/api/v1/file.go
Labels: do-not-merge/release-note-label-needed

#4396 feat: 优化文件上传体验
  frontend/src/views/host/file-management/upload/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4398 feat: 计划任务容器中执行增加 Command 选项
  backend/app/dto/cronjob.go
  backend/app/model/cronjob.go
  backend/app/service/cornjob.go
  backend/app/service/cronjob_helper.go
  backend/init/migration/migrate.go
  backend/init/migration/migrations/v_1_10.go
  frontend/src/api/interface/cronjob.ts
  frontend/src/views/container/container/terminal/index.vue
  frontend/src/views/cronjob/operate/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4399 fix: 专业版菜单隐藏显示逻辑修改
  backend/init/migration/migrations/v_1_10.go
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/layout/components/Sidebar/index.vue
  frontend/src/views/setting/panel/hidemenu/index.vue
  frontend/src/views/setting/panel/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm

#4400 fix: 解决没有 xpack 打包报错的问题
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4403 chore：更新 README
  README.md
Labels: do-not-merge/release-note-label-needed

#4402 fix: 修改升级等过程中复制方式
  backend/app/service/cronjob_backup.go
  backend/app/service/snapshot.go
  backend/app/service/snapshot_create.go
  backend/app/service/snapshot_recover.go
  backend/app/service/upgrade.go
  backend/utils/cloud_storage/client/local.go
  backend/utils/common/common.go
  cmd/server/cmd/restore.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4414 fix: 修改 xpack 依赖
  frontend/src/layout/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4415 feat: 删除网站适配防篡改
  .gitignore
  backend/app/service/app_utils.go
  backend/app/service/website.go
  backend/app/service/website_utils.go
  backend/utils/xpack/xpack.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4417 feat: 增加概览页跳转方式
  frontend/src/components/system-upgrade/index.vue
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/layout/components/Sidebar/components/Logo.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4418 fix: 解决文件保存失败一直处于加载中的问题
  frontend/src/views/host/file-management/code-editor/index.vue
Labels: do-not-merge/release-note-label-needed, dev

#4419 fix: 解决升级失败的问题
  backend/utils/common/common.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4420 fix: 解决替换根目录失败的问题
  backend/app/service/upgrade.go
Labels: do-not-merge/release-note-label-needed, dev

#4424 feat: 监控数据使用独立数据库
  backend/app/api/v1/monitor.go
  backend/app/repo/setting.go
  backend/global/global.go
  backend/init/db/db.go
  backend/init/migration/migrate.go
  backend/init/migration/migrations/v_1_10.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4426 pref: 优化 OSS 连接检测错误信息
  backend/i18n/lang/en.yaml
  backend/i18n/lang/zh-Hant.yaml
  backend/i18n/lang/zh.yaml
  frontend/src/views/host/monitor/setting/days/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4427 fix: 修改监控相关接口
  backend/app/api/v1/monitor.go
  backend/app/api/v1/setting.go
  backend/router/common.go
  backend/router/ro_host.go
  backend/router/ro_monitor.go
  backend/router/ro_setting.go
  cmd/server/docs/docs.go
  cmd/server/docs/swagger.json
  cmd/server/docs/swagger.yaml
  frontend/src/api/interface/host.ts
  frontend/src/api/interface/monitor.ts
  frontend/src/api/modules/host.ts
  frontend/src/api/modules/monitor.ts
  frontend/src/api/modules/setting.ts
  frontend/src/routers/modules/setting.ts
  frontend/src/views/home/index.vue
  frontend/src/views/host/monitor/monitor/index.vue
  frontend/src/views/host/monitor/setting/days/index.vue
  frontend/src/views/host/monitor/setting/index.vue
  frontend/src/views/setting/panel/default-network/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4428 feat: 增加一些翻译
  backend/i18n/lang/en.yaml
  backend/i18n/lang/zh-Hant.yaml
  backend/i18n/lang/zh.yaml
  frontend/src/components/index.ts
  frontend/src/components/msg-info/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4430 chore: remove repetitive word
  frontend/src/lang/modules/en.ts
Labels: do-not-merge/release-note-label-needed

#4429 fix: 切换菜单设置接口
  backend/app/api/v1/monitor.go
  frontend/src/views/setting/panel/hidemenu/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4439 fix: 解决读取 block 文件报错的问题
  backend/utils/files/fileinfo.go
  backend/utils/files/utils.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4440 feat: 优化文件创建
  backend/app/dto/request/file.go
  backend/app/service/file.go
  backend/utils/files/file_op.go
  frontend/src/api/interface/file.ts
  frontend/src/views/host/file-management/create/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4441 feat: 文件上传权限优化
  backend/app/api/v1/file.go
  backend/utils/files/utils.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4442 feat: 进程守护名称支持-_等字符
  frontend/src/views/toolbox/supervisor/create/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4445 feat: 文本编辑器记住上次设置
  frontend/src/views/host/file-management/code-editor/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4446 feat: 网站名称支持带端口
  backend/app/service/website.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4448 feat: 增加文件修改权限的超时时间
  backend/utils/files/file_op.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4444 feat: 未认证设置状态下系统跳转页面功能实现
  backend/app/api/v1/auth.go
  backend/app/dto/setting.go
  backend/app/service/auth.go
  backend/init/migration/migrate.go
  backend/init/migration/migrations/v_1_10.go
  backend/router/ro_base.go
  frontend/src/api/interface/setting.ts
  frontend/src/api/modules/auth.ts
  frontend/src/assets/images/error.svg
  frontend/src/components/error-message/error_code.vue
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/login/entrance/index.vue
  frontend/src/views/login/index.vue
  frontend/src/views/setting/safe/index.vue
  frontend/src/views/setting/safe/response/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4456 fix: close resource
  backend/utils/cloud_storage/client/minio.go
Labels: do-not-merge/release-note-label-needed

#4454 fix: 监控数据迁移增加数据长度判断
  backend/init/migration/migrations/v_1_10.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4464 fix: 解决僵尸进程的问题
  backend/app/api/v1/terminal.go
  backend/app/service/container.go
  frontend/src/views/container/container/log/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4468 feat: 增加 GPU 监控
  backend/app/dto/dashboard.go
  backend/app/service/dashboard.go
  backend/init/migration/migrate.go
  backend/init/migration/migrations/v_1_10.go
  backend/utils/xpack/xpack.go
  cmd/server/docs/docs.go
  cmd/server/docs/swagger.json
  cmd/server/docs/swagger.yaml
  frontend/src/api/interface/dashboard.ts
  frontend/src/assets/iconfont/iconfont.css
  frontend/src/assets/iconfont/iconfont.js
  frontend/src/assets/iconfont/iconfont.json
  frontend/src/assets/iconfont/iconfont.svg
  frontend/src/assets/iconfont/iconfont.ttf
  frontend/src/assets/iconfont/iconfont.woff
  frontend/src/assets/iconfont/iconfont.woff2
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/home/index.vue
  frontend/src/views/home/status/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4469 style(waf): 修改网站图标位置
  frontend/src/components/config-card/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4470 fix: 解决登录页跳转错误的问题
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/home/status/index.vue
  frontend/src/views/login/entrance/index.vue
  frontend/src/views/setting/safe/index.vue
  frontend/src/views/setting/safe/response/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4474 fix: 解决登录页跳转错误的问题
  backend/app/api/v1/setting.go
  cmd/server/docs/docs.go
  cmd/server/docs/swagger.json
  cmd/server/docs/swagger.yaml
  frontend/src/views/login/entrance/index.vue
  go.mod
  go.sum
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4476 fix: 解决安装应用时 deploy 字段被覆盖的问题
  backend/app/service/app_utils.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4477 fix: 修改高级功能菜单 LOGO
  frontend/src/assets/iconfont/iconfont.css
  frontend/src/assets/iconfont/iconfont.js
  frontend/src/assets/iconfont/iconfont.json
  frontend/src/assets/iconfont/iconfont.svg
  frontend/src/assets/iconfont/iconfont.ttf
  frontend/src/assets/iconfont/iconfont.woff
  frontend/src/assets/iconfont/iconfont.woff2
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4478 fix: 创建文件增加非法字符校验
  backend/app/service/file.go
  backend/i18n/lang/en.yaml
  backend/i18n/lang/zh-Hant.yaml
  backend/i18n/lang/zh.yaml
  backend/utils/files/utils.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4480 fix: 解决特殊字符下文件放入回收站失败的问题
  backend/utils/files/file_op.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4483 fix: 修改系统版本比较方法
  backend/app/service/upgrade.go
  backend/utils/common/common.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4484 fix: 解决文件搜索目录包含回收站目录能进入的问题
  frontend/src/views/host/file-management/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4485 feat: 修改中国地区名称
  frontend/src/assets/json/china.json
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4487 fix: 修改登录页跳转问题
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/routers/index.ts
  frontend/src/views/login/index.vue
  frontend/src/views/setting/license/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4490 fix: 解决概览页 CPU 核心过多导致的显示问题
  backend/init/router/router.go
  backend/router/ro_base.go
  frontend/src/api/modules/auth.ts
  frontend/src/views/home/images/de.jpg
  frontend/src/views/home/images/halo.jpg
  frontend/src/views/home/images/js.jpg
  frontend/src/views/home/images/ko.jpg
  frontend/src/views/home/images/kubepi.jpg
  frontend/src/views/home/images/ms.jpg
  frontend/src/views/home/status/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4503 fix typos
  backend/app/api/v1/website.go
  backend/app/dto/database.go
  backend/app/service/website.go
  cmd/server/docs/docs.go
  cmd/server/docs/swagger.json
  cmd/server/docs/swagger.yaml
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/host/file-management/create/index.vue
Labels: do-not-merge/release-note-label-needed

#4489 feat: 容器创建支持指定 IP 地址
  backend/app/dto/container.go
  backend/app/service/container.go
  frontend/src/api/interface/container.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/container/container/operate/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4512 fix: 解决安装应用时候，原始 docker-compose.yml 的 deploy 字段下内容会被自动覆写的问题
  backend/app/service/app_utils.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4513 feat: 修改 supervisor 名称限制
  frontend/src/global/form-rules.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/toolbox/supervisor/create/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4518 typos: Modify wrong words
  frontend/src/components/v-charts/components/Line.vue
  frontend/src/components/v-charts/index.vue
  frontend/src/views/container/container/monitor/index.vue
  frontend/src/views/home/index.vue
  frontend/src/views/host/monitor/monitor/index.vue
Labels: do-not-merge/release-note-label-needed

#4515 fix：解决新建文件夹部分权限无法创建的问题
  backend/utils/files/file_op.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4517 feat: 解决登录页授权 IP 跳转失败的问题
  frontend/src/layout/index.vue
  frontend/src/routers/index.ts
  frontend/src/views/login/entrance/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4510 feat: 增加菜单标签页功能 (#3267)
  backend/app/dto/setting.go
  backend/init/migration/migrate.go
  backend/init/migration/migrations/v_1_10.go
  frontend/src/api/interface/setting.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/layout/components/AppMain.vue
  frontend/src/layout/components/Sidebar/index.vue
  frontend/src/layout/components/Tabs/components/TabItem.vue
  frontend/src/layout/components/Tabs/index.vue
  frontend/src/layout/components/index.ts
  frontend/src/layout/index.vue
  frontend/src/store/index.ts
  frontend/src/store/interface/index.ts
  frontend/src/store/modules/global.ts
  frontend/src/store/modules/tabs.ts
  frontend/src/views/log/operation/index.vue
  frontend/src/views/login/components/login-form.vue
  frontend/src/views/setting/panel/index.vue
Labels: do-not-merge/release-note-label-needed

#4519 fix: 修复容器未指定 IP 编辑显示报错问题
  backend/app/service/container.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4521 chore: 添加拼写检查Action
  .github/workflows/tyops-check.yml
Labels: do-not-merge/release-note-label-needed

#4520 feat: 登陆时加载许可证状态
  frontend/src/layout/index.vue
  frontend/src/utils/xpack.ts
  frontend/src/views/login/components/login-form.vue
  frontend/src/views/login/entrance/index.vue
  frontend/src/views/login/index.vue
Labels: do-not-merge/release-note-label-needed, dev

#4522 feat: 增加许可证解绑功能
  frontend/src/api/modules/setting.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/setting/license/index.vue
Labels: dev

#4530 feat: 修改服务初始化操作逻辑
  backend/configs/system.go
  backend/init/hook/hook.go
  backend/init/viper/viper.go
  cmd/server/cmd/root.go
  cmd/server/cmd/user-info.go
  frontend/src/routers/index.ts
Labels: do-not-merge/release-note-label-needed, dev, lgtm

#4532 style: 修改 openresty 的端口提示
  frontend/src/components/app-status/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm

#4534 pref: 调整部分界面的高度问题
  backend/app/service/container.go
  frontend/src/components/container-log/index.vue
  frontend/src/views/container/setting/index.vue
  frontend/src/views/database/mysql/setting/index.vue
  frontend/src/views/database/mysql/setting/slow-log/index.vue
  frontend/src/views/database/postgresql/setting/index.vue
  frontend/src/views/database/redis/index.vue
  frontend/src/views/database/redis/setting/index.vue
  frontend/src/views/host/terminal/terminal/index.vue
Labels: do-not-merge/release-note-label-needed, dev

#4535 style: 修改文件编辑器配置样式
  frontend/src/views/host/file-management/code-editor/index.vue
Labels: do-not-merge/release-note-label-needed, dev

#4549 fix: 解决容器日志缺失的问题
  backend/app/service/container.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4550 Update README.md
  README.md
Labels: do-not-merge/release-note-label-needed

#4561 docs: add projects to other readme
  docs/README_EN.md
  docs/README_JP.md
  docs/README_TW.md
Labels: do-not-merge/release-note-label-needed

#4560 fix: 解决本地备份账号路径获取错误的问题
  backend/app/service/cronjob_helper.go
  backend/utils/common/common.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4563 fix: 解决文件上传权限错误的问题
  backend/app/api/v1/file.go
  backend/utils/files/file_op.go
  backend/utils/files/utils.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4564 chore: fix some typos
  backend/app/api/v1/app.go
  cmd/server/docs/docs.go
  cmd/server/docs/swagger.json
  cmd/server/docs/swagger.yaml
Labels: do-not-merge/release-note-label-needed

#4569 fix: 解决监控数据迁移失败的问题
  backend/init/migration/migrations/v_1_10.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4577 fix: 解决创建 PHP 网站首页无法访问的 BUG
  backend/app/service/file.go
  backend/utils/files/file_op.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4588 fix: 解决容器日志文件被删除但是进程未结束的问题
  backend/app/service/container.go
  frontend/src/components/compose-log/index.vue
  frontend/src/components/container-log/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4591 fix: 解决伪静态开启报错的问题
  backend/app/service/website.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4593 fix: 修改许可证状态获取接口
  frontend/src/api/interface/setting.ts
  frontend/src/api/modules/setting.ts
  frontend/src/layout/index.vue
  frontend/src/views/login/components/login-form.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4594 fix: 修改安全入口长度校验
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/setting/safe/entrance/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4599 fix: 增加特殊字符命令过滤
  backend/utils/cmd/cmd.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4638 feat: 升级回滚增加相关数据库文件
  backend/app/service/upgrade.go
  cmd/server/cmd/restore.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4650 fix: SSH 连接列表显示优化
  frontend/src/views/host/terminal/terminal/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4648 feat: 增加应用备份跳转目录
  frontend/src/components/backup/index.vue
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4665 feat: 数据库支持 Mariadb 11.x
  backend/app/service/database_mysql.go
  backend/utils/mysql/client.go
  backend/utils/mysql/client/info.go
  backend/utils/mysql/client/local.go
  backend/utils/mysql/client/remote.go
  frontend/src/views/database/mysql/remote/operate/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm

#4656 fix: 解决概览页折线图选择失败的问题
  frontend/src/components/v-charts/components/Line.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4660 fix: 解决容器内进程异常结束的问题
  backend/app/api/v1/terminal.go
  backend/utils/terminal/local_cmd.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4661 fix: 解决低版本 OpenResty 创建网站报错的问题
  backend/app/service/website_utils.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4662 feat: 升级 golang.org/x/net 依赖
  go.mod
  go.sum
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4669 fix: 创建网站可以使用相同域名问题修复
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/website/website/create/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4677 fix: 解决应用升级失败没有回滚的问题
  backend/app/api/v1/backup.go
  backend/app/api/v1/file.go
  backend/app/service/app_utils.go
  backend/app/service/backup.go
  backend/app/service/backup_app.go
  backend/i18n/i18n.go
  backend/i18n/lang/en.yaml
  backend/i18n/lang/zh-Hant.yaml
  backend/i18n/lang/zh.yaml
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4678 feat: 伪静态增加提示
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/website/website/config/basic/rewrite/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4681 style: 优化中国地图显示
  frontend/src/assets/json/china.json
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4685 feat: 增加内测模式
  backend/app/dto/setting.go
  backend/app/service/upgrade.go
  backend/init/migration/migrate.go
  backend/init/migration/migrations/v_1_10.go
  backend/utils/common/common.go
  cmd/server/docs/docs.go
  cmd/server/docs/swagger.json
  cmd/server/docs/swagger.yaml
  frontend/src/api/interface/setting.ts
  frontend/src/components/system-upgrade/index.vue
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/home/index.vue
  frontend/src/views/setting/panel/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4692 fix: 解决计划任务本地保存份数错误的问题
  backend/app/service/cronjob_helper.go
  backend/utils/cloud_storage/client/local.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4700 pref: 释放容器 client 连接
  backend/app/api/v1/file.go
  backend/app/service/app.go
  backend/app/service/app_install.go
  backend/app/service/app_utils.go
  backend/app/service/container.go
  backend/app/service/container_compose.go
  backend/app/service/container_network.go
  backend/app/service/container_volume.go
  backend/app/service/docker.go
  backend/app/service/image.go
  backend/app/service/nginx.go
  backend/app/service/runtime.go
  backend/app/service/runtime_utils.go
  backend/utils/cloud_storage/client/onedrive.go
  backend/utils/cloud_storage/client/sftp.go
  backend/utils/docker/docker.go
  backend/utils/http/get.go
  backend/utils/postgresql/client/remote.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4704 fix: 修复 WAF 地图英文模式下的显示错误
  frontend/src/assets/json/china.json
Labels: do-not-merge/release-note-label-needed, dev

#4707 fix: Docker 配置自动过滤空行
  backend/app/api/v1/docker.go
  cmd/server/docs/docs.go
  cmd/server/docs/swagger.json
  cmd/server/docs/swagger.yaml
  frontend/src/utils/util.ts
  frontend/src/views/container/setting/mirror/index.vue
  frontend/src/views/container/setting/registry/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4711 perf: 优化错误日志超长下的显示
  frontend/src/lang/modules/en.ts
  frontend/src/views/app-store/installed/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4723 feat: 文件管理页面增加回退功能
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/host/file-management/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm

#4725 style: 修改面板设置描述信息
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/setting/panel/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm

#4726 style: 优化网站列表描述信息显示
  backend/utils/files/file_op.go
  backend/utils/files/utils.go
  backend/utils/http/get.go
  frontend/src/views/website/website/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4732 feat: 失败状态应用允许恢复
  frontend/src/components/backup/index.vue
  frontend/src/lang/modules/tw.ts
  frontend/src/views/app-store/installed/index.vue
Labels: do-not-merge/release-note-label-needed, dev

#4737 fix: 解决第二次上传同名文件不显示的问题
  frontend/src/views/host/file-management/upload/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm

#4776 fix: 解决应用商店同步图标丢失的问题
  backend/app/service/app.go
  backend/cron/cron.go
  backend/middleware/demo_handle.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4777 fix: 解决反向代理匹配规则为空之后无法删除的问题
  backend/app/dto/request/website.go
  frontend/src/views/website/website/config/basic/proxy/create/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4790 fix: 删除 PHP 和 Node.js 运行环境的提示信息优化
  backend/app/api/v1/runtime.go
  backend/app/service/runtime.go
  backend/router/ro_runtime.go
  frontend/src/api/modules/runtime.ts
  frontend/src/views/website/runtime/node/index.vue
  frontend/src/views/website/runtime/php/check/index.vue
  frontend/src/views/website/runtime/php/index.vue
Labels: dev, lgtm

#4803 pref: 优化计划任务错误显示
  frontend/src/components/system-upgrade/index.vue
  frontend/src/views/cronjob/record/index.vue
Labels: do-not-merge/release-note-label-needed, dev

#4810 feat: 计划任务应用、网站备份增加排除规则
  backend/app/service/backup_app.go
  backend/app/service/backup_runtime.go
  backend/app/service/backup_website.go
  backend/app/service/cronjob_backup.go
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/cronjob/operate/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm
