Repository 1Panel-dev/1Panel, pull requests merged in 2024-05, with the labels that each got.

#4838 chore: Update README.md
  README.md
Labels: do-not-merge/release-note-label-needed

#4866 fix: 解决计算文件夹大小线程没有回收的问题
  backend/app/service/file.go
  backend/utils/files/file_op.go
  backend/utils/files/utils.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4869 feat: 限制创建网站使用 default 代号
  backend/app/service/website.go
  backend/i18n/lang/en.yaml
  backend/i18n/lang/zh-Hant.yaml
  backend/i18n/lang/zh.yaml
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4870 fix: 运行时运行目录选择器支持手动输入
  frontend/src/views/website/website/config/basic/site-folder/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4874 feat: 网站默认配置增加支持 CDN 真实 IP
  cmd/server/nginx_conf/website_default.conf
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4877 feat: 增加许可证错误信息显示
  frontend/src/api/interface/setting.ts
  frontend/src/views/setting/license/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4894 fix: 解决进程守护启动命令带空格导致报错的问题
  frontend/src/global/mimetype.ts
  frontend/src/views/toolbox/supervisor/create/index.vue
Labels: dev

#4901 feat: 证书增加编辑功能
  backend/app/dto/request/website_ssl.go
  backend/app/model/website_ssl.go
  backend/app/repo/website_ssl.go
  backend/app/service/website_ca.go
  backend/app/service/website_ssl.go
  backend/utils/ssl/client.go
  frontend/src/api/interface/website.ts
  frontend/src/views/website/ssl/create/index.vue
  frontend/src/views/website/ssl/index.vue
Labels: dev

#4903 feat: 证书申请增加配置，提高申请成功率
  backend/app/dto/request/website_ssl.go
  backend/app/model/website_ssl.go
  backend/app/service/website_ssl.go
  backend/init/migration/migrate.go
  backend/init/migration/migrations/v_1_10.go
  backend/utils/common/common.go
  backend/utils/ssl/client.go
  frontend/src/api/interface/website.ts
  frontend/src/global/form-rules.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/website/ssl/apply/index.vue
  frontend/src/views/website/ssl/create/index.vue
  frontend/src/views/website/ssl/dns-account/create/index.vue
  frontend/src/views/website/ssl/obtain/index.vue
Labels: dev

#4910 feat: 修改 supervisor 名称校验规则
  frontend/src/global/form-rules.ts
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4913 style: 解决英文状态下删除文件提示字符超出的问题
  frontend/src/views/host/file-management/delete/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4914 fix: 解决获取版本升级信息失败的问题
  backend/app/service/upgrade.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4915 fix: 解决中文域名创建 PHP 类型网站失败的问题
  backend/app/service/website.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4916 feat: 切割网站日志计划任务增加默认周期
  frontend/src/views/cronjob/helper.ts
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4917 style: 调整反向代理的源文页面大小
  frontend/src/views/website/website/config/basic/proxy/file/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4921 fix: 解决编排目录跳转失败的问题
  backend/init/hook/hook.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4922 fix: 解决容器执行 exit 退出后服务 panic 的问题
  backend/utils/terminal/ws_local_session.go
  backend/utils/terminal/ws_session.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4924 fix: 解决网站备份恢复导致网站列表丢失的问题
  backend/app/service/backup_website.go
  frontend/src/views/website/runtime/php/edit/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4925 fix: 解决升级信息获取失败的问题
  backend/app/service/upgrade.go
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4926 fix: 解决自签证书火狐浏览器报错的问题
  backend/app/service/website_ca.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4934 style: 调整证书编辑页面样式
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/website/ssl/create/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4936 style: 去掉多余的字符
  backend/i18n/lang/en.yaml
  backend/i18n/lang/zh-Hant.yaml
  backend/i18n/lang/zh.yaml
  frontend/src/global/form-rules.ts
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4938 fix: 修改版本升级显示信息
  frontend/src/components/system-upgrade/index.vue
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4939 fix: 解决关闭菜单选项时刷新跳转到概览页的问题
  frontend/src/layout/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4941 fix: 解决数据库备份错误的问题
  backend/utils/mysql/client/local.go
  backend/utils/mysql/client/remote.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4942 feat: WAF 增加 cdn 配置文件
  backend/app/service/website_utils.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4944 fix: 解决容器镜像推送失败的问题
  backend/app/service/image.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4954 fix: 解决安装包下载路径错误的问题
  backend/app/service/upgrade.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4978 feat: 运行环境及容器菜单增加清理构建缓存功能
  backend/app/dto/container.go
  backend/app/service/container.go
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/container/image/index.vue
  frontend/src/views/website/runtime/node/index.vue
  frontend/src/views/website/runtime/php/index.vue
Labels: do-not-merge/release-note-label-needed, dev

#4987 fix: 解决应用名称存在大写导致无法升级的问题
  backend/app/service/app_utils.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4994 feat: 存储卷清理增加清除所有标签
  backend/app/service/container.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4997 fix: 解决进程守护命令不能输入空格的问题
  backend/app/service/host_tool.go
  frontend/src/views/toolbox/supervisor/create/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4991 fix: 解决编辑证书时，其他域名格式不正确问题
  frontend/src/views/website/ssl/create/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved

#4998 feat: 优化网站域名跳转
  frontend/src/views/website/website/config/basic/domain/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4999 fix: 解决上传证书状态异常的问题
  backend/app/service/website_ssl.go
  frontend/src/views/website/ssl/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4989 feat: 首页监控中上下行流量数据单位自动格式化 (#4207)
  frontend/src/views/home/index.vue
Labels: do-not-merge/release-note-label-needed

#5014 feat: Redis 支持远程数据库
  backend/app/api/v1/database_redis.go
  backend/app/api/v1/terminal.go
  backend/app/service/database.go
  backend/app/service/database_redis.go
  backend/router/ro_database.go
  backend/utils/redis/redis.go
  cmd/server/docs/docs.go
  cmd/server/docs/swagger.json
  cmd/server/docs/swagger.yaml
  frontend/src/api/modules/database.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/routers/modules/database.ts
  frontend/src/store/interface/index.ts
  frontend/src/store/modules/global.ts
  frontend/src/views/database/redis/check/index.vue
  frontend/src/views/database/redis/index.vue
  frontend/src/views/database/redis/remote/delete/index.vue
  frontend/src/views/database/redis/remote/index.vue
  frontend/src/views/database/redis/remote/operate/index.vue
  go.mod
  go.sum
Labels: do-not-merge/release-note-label-needed, dev

#5016 添加WordPress的PHP扩展模板
  backend/init/migration/migrations/v_1_9.go
Labels: do-not-merge/release-note-label-needed

#5020 fix: 修改数据库状态异常样式
  frontend/src/views/database/mysql/index.vue
  frontend/src/views/database/postgresql/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5025 feat: 优化网站目录跳转
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/website/website/config/basic/site-folder/index.vue
  frontend/src/views/website/website/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5024 feat: 工具箱的缓存清理添加容器垃圾清理功能
  backend/app/dto/setting.go
  backend/app/service/container.go
  backend/app/service/device_clean.go
  frontend/src/api/interface/toolbox.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/toolbox/clean/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5038 feat: 增加网站监控页面
  backend/app/dto/setting.go
  backend/init/migration/migrate.go
  backend/init/migration/migrations/v_1_10.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5039 feat: 工具箱支持 FTP
  backend/app/api/v1/backup.go
  backend/app/api/v1/entry.go
  backend/app/api/v1/ftp.go
  backend/app/dto/ftp.go
  backend/app/model/ftp.go
  backend/app/repo/ftp.go
  backend/app/service/entry.go
  backend/app/service/ftp.go
  backend/init/migration/migrate.go
  backend/init/migration/migrations/v_1_10.go
  backend/router/ro_toolbox.go
  backend/utils/toolbox/pure-ftpd.go
  cmd/server/docs/docs.go
  cmd/server/docs/swagger.json
  cmd/server/docs/swagger.yaml
  frontend/src/api/interface/toolbox.ts
  frontend/src/api/modules/toolbox.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/routers/modules/toolbox.ts
  frontend/src/views/toolbox/ftp/index.vue
  frontend/src/views/toolbox/ftp/operate/index.vue
  frontend/src/views/toolbox/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5053 feat: 增加网站监控的说明
  backend/app/service/website_utils.go
  frontend/src/assets/iconfont/iconfont.css
  frontend/src/assets/iconfont/iconfont.js
  frontend/src/assets/iconfont/iconfont.json
  frontend/src/assets/iconfont/iconfont.svg
  frontend/src/assets/iconfont/iconfont.ttf
  frontend/src/assets/iconfont/iconfont.woff
  frontend/src/assets/iconfont/iconfont.woff2
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5065 feat: FTP 增加状态及日志
  backend/app/api/v1/ftp.go
  backend/app/dto/ftp.go
  backend/app/service/ftp.go
  backend/router/ro_toolbox.go
  backend/utils/toolbox/fail2ban.go
  backend/utils/toolbox/pure-ftpd.go
  cmd/server/docs/docs.go
  cmd/server/docs/swagger.json
  cmd/server/docs/swagger.yaml
  frontend/src/api/interface/toolbox.ts
  frontend/src/api/modules/toolbox.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/utils/util.ts
  frontend/src/views/toolbox/ftp/index.vue
  frontend/src/views/toolbox/ftp/log/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5080 fix: 解决部分应用图标不显示的问题
  backend/app/service/app.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5076 feat: 网站创建增加 FTP 选项
  backend/app/api/v1/ftp.go
  backend/app/api/v1/website.go
  backend/app/dto/request/website.go
  backend/app/model/website.go
  backend/app/service/ftp.go
  backend/app/service/website.go
  backend/init/migration/migrations/v_1_10.go
  backend/utils/toolbox/pure-ftpd.go
  cmd/server/docs/docs.go
  cmd/server/docs/swagger.json
  cmd/server/docs/swagger.yaml
  frontend/src/api/interface/website.ts
  frontend/src/api/modules/website.ts
  frontend/src/global/form-rules.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/database/mysql/index.vue
  frontend/src/views/database/mysql/remote/index.vue
  frontend/src/views/database/postgresql/index.vue
  frontend/src/views/database/postgresql/remote/index.vue
  frontend/src/views/database/redis/remote/index.vue
  frontend/src/views/toolbox/ftp/index.vue
  frontend/src/views/toolbox/ftp/log/index.vue
  frontend/src/views/toolbox/ftp/operate/index.vue
  frontend/src/views/website/website/create/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5081 fix: 解决部分 ssh 登录日志解析失败的问题
  backend/app/service/ssh.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5088 feat: 进程守护增加运行目录跳转
  frontend/src/views/toolbox/supervisor/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5092 fix: 解决网站排序错误的问题
  frontend/src/views/website/website/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5093 feat: 文件列表行内权限支持修改用户和用户组
  frontend/src/views/host/file-management/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5096 fix: 解决在线文本编辑器打开 GBK 编码文件乱码问题
  backend/app/service/container.go
  backend/app/service/file.go
  backend/utils/docker/docker.go
  backend/utils/mysql/client/remote.go
  backend/utils/postgresql/client/remote.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5097 feat: 文件夹名称增加完整路径展示
  frontend/src/views/host/file-management/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5098 feat: 增加一些 icon
  frontend/src/assets/images/2345explorer.png
  frontend/src/assets/images/360se.png
  frontend/src/assets/images/android.png
  frontend/src/assets/images/chrome.png
  frontend/src/assets/images/edge.png
  frontend/src/assets/images/firefox.png
  frontend/src/assets/images/ie.png
  frontend/src/assets/images/ios.png
  frontend/src/assets/images/linux.png
  frontend/src/assets/images/mac.png
  frontend/src/assets/images/machine.png
  frontend/src/assets/images/mobile.png
  frontend/src/assets/images/opera.png
  frontend/src/assets/images/pc.png
  frontend/src/assets/images/safari.png
  frontend/src/assets/images/tencent.png
  frontend/src/assets/images/ucweb.png
  frontend/src/assets/images/unknown.png
  frontend/src/assets/images/wechat.png
  frontend/src/assets/images/windows.png
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5015 refactor: refactor theme and logo switching functionality
  frontend/package.json
  frontend/src/assets/images/1panel-logo-dark.png
  frontend/src/assets/images/1panel-logo-light.png
  frontend/src/assets/images/1panel-logo.svg
  frontend/src/assets/images/1panel-menu-dark.png
  frontend/src/assets/images/1panel-menu-light.png
  frontend/src/assets/images/1panel-menu-logo.svg
  frontend/src/components/license-import/index.vue
  frontend/src/components/system-upgrade/index.vue
  frontend/src/components/v-charts/components/Line.vue
  frontend/src/components/v-charts/components/Pie.vue
  frontend/src/hooks/use-logo.ts
  frontend/src/hooks/use-theme.ts
  frontend/src/layout/components/Sidebar/components/Logo.vue
  frontend/src/layout/index.vue
  frontend/src/main.ts
  frontend/src/store/modules/global.ts
  frontend/src/styles/element-dark.scss
  frontend/src/styles/element.scss
  frontend/src/styles/var.scss
  frontend/src/utils/xpack.ts
  frontend/src/views/app-store/detail/index.vue
  frontend/src/views/login/entrance/index.vue
  frontend/src/views/login/index.vue
  frontend/src/views/setting/about/index.vue
  frontend/src/views/setting/panel/index.vue
  frontend/vite-env.d.ts
  frontend/vite.config.ts
Labels: release-note-none

#5105 pref: 1pctl 引用路径使用源文件代替软链地址
  backend/init/viper/viper.go
  cmd/server/cmd/restore.go
  cmd/server/cmd/root.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5110 fix: 修复几处日志文件未释放问题
  backend/app/service/runtime_utils.go
  backend/utils/mysql/client/local.go
  backend/utils/mysql/client/remote.go
  backend/utils/postgresql/client/local.go
Labels: do-not-merge/release-note-label-needed

#5109 fix: 修复分块上传文件资源未释放问题
  backend/app/api/v1/file.go
Labels: do-not-merge/release-note-label-needed

#5119 fix: 解决计划任务执行周期解析错误的问题
  frontend/src/views/cronjob/helper.ts
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5120 fix: 解决升级过程中备份错误问题
  backend/utils/mysql/client/local.go
  backend/utils/mysql/client/remote.go
  backend/utils/postgresql/client/local.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5123 feat: 提升分段上传文件的体验
  backend/app/api/v1/file.go
Labels: do-not-merge/release-note-label-needed

#5143 feat: 增加华为 Icon
  frontend/src/assets/images/harmonyos.png
  frontend/src/assets/images/huaweibrowser.png
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
Labels: do-not-merge/release-note-label-needed, dev

#5159 feat: 修改安全入口页特征样式
  backend/app/api/v1/auth.go
  backend/app/api/v1/helper/helper.go
  backend/app/service/auth.go
  backend/constant/errs.go
  backend/init/router/router.go
  backend/middleware/bind_domain.go
  backend/middleware/helper.go
  backend/middleware/ip_limit.go
  backend/middleware/password_expired.go
  frontend/src/api/index.ts
  frontend/src/api/modules/auth.ts
  frontend/src/components/error-message/error_code.vue
  frontend/src/enums/http-enum.ts
  frontend/src/store/interface/index.ts
  frontend/src/store/modules/global.ts
  frontend/src/views/login/entrance/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5164 fix: 登录页跳转增加 404
  backend/app/api/v1/auth.go
  backend/app/service/auth.go
  backend/constant/errs.go
  frontend/src/api/index.ts
  frontend/src/enums/http-enum.ts
  frontend/src/views/login/entrance/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5179 fix: 解决清空伪静态配置报错的问题
  backend/app/dto/request/nginx.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5190 fix: 解决概览页磁盘显示不全的问题
  backend/app/service/dashboard.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5189 feat: 增加服务器代理设置
  backend/app/api/v1/setting.go
  backend/app/dto/setting.go
  backend/app/service/app.go
  backend/app/service/app_utils.go
  backend/app/service/device_clean.go
  backend/app/service/runtime_utils.go
  backend/app/service/setting.go
  backend/app/service/upgrade.go
  backend/init/migration/migrate.go
  backend/init/migration/migrations/v_1_10.go
  backend/router/ro_setting.go
  backend/server/server.go
  backend/utils/http/get.go
  backend/utils/http/request.go
  backend/utils/xpack/xpack.go
  cmd/server/docs/docs.go
  cmd/server/docs/swagger.json
  cmd/server/docs/swagger.yaml
  frontend/src/api/interface/setting.ts
  frontend/src/api/modules/setting.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/setting/panel/index.vue
  frontend/src/views/setting/panel/proxy/index.vue
  frontend/src/views/toolbox/ftp/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5194 fix: the issue where the auto theme is invalid due to an incorrect class setting
  frontend/src/hooks/use-theme.ts
Labels: release-note-none

#5196 fix: 概览页磁盘显示过滤 /snap
  backend/app/service/dashboard.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5197 style: 固定登录页样式
  frontend/src/views/login/components/login-form.vue
  frontend/src/views/login/entrance/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5198 fix: 解决使用本地 PHP 环境停止启动网站之后配置错误的问题
  backend/app/service/website_utils.go
  backend/utils/files/utils.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5201 fix: 解决黑金模式下概览页异常闪动的问题
  frontend/src/api/index.ts
  frontend/src/components/license-import/index.vue
  frontend/src/hooks/use-theme.ts
  frontend/src/layout/index.vue
  frontend/src/store/interface/index.ts
  frontend/src/store/modules/global.ts
  frontend/src/views/setting/license/index.vue
  frontend/src/views/setting/panel/index.vue
  frontend/src/views/website/ssl/create/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5202 perf: 优化应用查询接口的执行速度
  backend/app/dto/request/app.go
  backend/app/service/app_install.go
  backend/app/service/app_utils.go
  backend/utils/docker/docker.go
  frontend/src/api/interface/app.ts
  frontend/src/assets/images/spider.png
  frontend/src/views/app-store/installed/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5203 fix: 解决打开非文本文件报错的问题
  backend/app/service/file.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5205 fix: 解决应用安装切换版本校验条件没变的问题
  frontend/src/views/app-store/detail/params/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5206 fix: 修复 Redis 数据库快速命令部分问题
  backend/app/api/v1/command.go
  backend/app/repo/command.go
  backend/app/service/command.go
  backend/app/service/database.go
  backend/router/ro_host.go
  cmd/server/docs/docs.go
  cmd/server/docs/swagger.json
  cmd/server/docs/swagger.yaml
  frontend/src/api/modules/host.ts
  frontend/src/global/form-rules.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/container/image/pull/index.vue
  frontend/src/views/database/redis/command/index.vue
  frontend/src/views/database/redis/index.vue
  frontend/src/views/database/redis/remote/operate/index.vue
  frontend/src/views/toolbox/ftp/index.vue
  frontend/src/views/toolbox/ftp/log/index.vue
  frontend/src/views/toolbox/ftp/operate/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5215 fix: 处理数据库遮罩问题
  backend/app/dto/response/app.go
  backend/app/repo/app_install.go
  backend/app/service/app_install.go
  backend/app/service/database.go
  backend/app/service/database_mysql.go
  backend/app/service/database_postgresql.go
  backend/app/service/database_redis.go
  frontend/src/api/interface/app.ts
  frontend/src/components/app-status/index.vue
  frontend/src/views/database/mysql/conn/index.vue
  frontend/src/views/database/mysql/index.vue
  frontend/src/views/database/postgresql/conn/index.vue
  frontend/src/views/database/postgresql/index.vue
  frontend/src/views/database/redis/conn/index.vue
  frontend/src/views/database/redis/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm

#5216 feat: 升级 lego 版本
  backend/utils/ssl/client.go
  go.mod
  go.sum
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5218 fix: 解决主题颜色切换失败的问题
  frontend/src/hooks/use-theme.ts
  frontend/src/utils/xpack.ts
  frontend/src/views/setting/panel/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5221 fix: 解决远程数据库备份失败的问题
  backend/app/service/container.go
  backend/app/service/docker.go
  backend/app/service/ftp.go
  backend/utils/mysql/client/remote.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5222 fix: 远程数据库增加名称校验
  frontend/src/views/database/mysql/remote/operate/index.vue
  frontend/src/views/database/postgresql/remote/operate/index.vue
  frontend/src/views/database/redis/command/index.vue
  frontend/src/views/database/redis/remote/operate/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5224 fix: 解决 FTP 状态同步失败的问题
  backend/app/service/ftp.go
  backend/utils/toolbox/pure-ftpd.go
  frontend/src/views/toolbox/ftp/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5225 feat: Node.js 增加 pnpm 支持
  backend/app/service/app_install.go
  backend/utils/docker/compose.go
  backend/utils/postgresql/client.go
  frontend/src/views/website/runtime/node/operate/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5226 feat: 增加定时清理缓存
  backend/cron/cron.go
  backend/cron/job/cache.go
  backend/global/global.go
  backend/init/cache/cache.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5227 feat: 删除无用依赖
  frontend/src/views/website/runtime/node/operate/index.vue
  go.mod
  go.sum
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5230 fix: 解决计划任务时区显示不一致的问题
  backend/app/dto/cronjob.go
  backend/app/service/cornjob.go
  cmd/server/docs/docs.go
  cmd/server/docs/swagger.json
  cmd/server/docs/swagger.yaml
  frontend/src/api/interface/cronjob.ts
  frontend/src/views/cronjob/record/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5229 fix: 优化 Redis 数据库样式
  frontend/src/views/database/mysql/index.vue
  frontend/src/views/database/postgresql/index.vue
  frontend/src/views/database/redis/index.vue
  frontend/src/views/setting/snapshot/index.vue
  frontend/src/views/toolbox/ftp/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5235 fix: demo 环境禁用终端工具
  backend/app/api/v1/terminal.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5237 fix: 快照删除增加备份文件删除选项
  backend/app/api/v1/snapshot.go
  backend/app/dto/setting.go
  backend/app/service/snapshot.go
  cmd/server/docs/docs.go
  cmd/server/docs/swagger.json
  cmd/server/docs/swagger.yaml
  frontend/src/api/modules/setting.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/setting/snapshot/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5238 feat: 修改 xpack 加载顺序
  backend/server/server.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5239 fix: Redis 数据库连接信息移除密码限制
  backend/app/dto/database.go
  backend/app/service/command.go
  frontend/src/views/database/redis/command/index.vue
  frontend/src/views/database/redis/conn/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5241 perf: 优化应用同步查询接口
  backend/app/service/app_utils.go
  backend/utils/docker/docker.go
  frontend/src/views/app-store/installed/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5242 fix: 服务器代理修改默认值
  frontend/src/views/database/mysql/index.vue
  frontend/src/views/database/redis/index.vue
  frontend/src/views/database/redis/setting/index.vue
  frontend/src/views/setting/panel/proxy/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5243 style: 增加 Chrome OS 图标
  frontend/src/assets/images/cros.png
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved
