Repository 1Panel-dev/1Panel, pull requests merged in 2024-07, with the labels that each got.

#5629 feat: 文件管理支持预览常见文件格式
  frontend/package.json
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/utils/util.ts
  frontend/src/views/host/file-management/index.vue
  frontend/src/views/host/file-management/preview/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5631 fix: 字体样式调整
  frontend/src/views/app-store/apps/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5632 feat: 增加 Go 运行环境
  backend/app/service/backup_website.go
  backend/app/service/runtime.go
  backend/app/service/runtime_utils.go
  backend/app/service/website.go
  backend/app/service/website_utils.go
  backend/constant/runtime.go
  frontend/src/routers/modules/website.ts
  frontend/src/views/website/runtime/go/index.vue
  frontend/src/views/website/runtime/go/operate/index.vue
  frontend/src/views/website/runtime/index.vue
  frontend/src/views/website/website/create/index.vue
  frontend/src/views/website/website/html/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm

#5637 feat: 删除部分无用代码
  frontend/package.json
  frontend/src/App.vue
  frontend/src/api/interface/toolbox.ts
  frontend/src/components/license-import/index.vue
  frontend/src/config/service-loading.ts
  frontend/src/directives/index.ts
  frontend/src/directives/modules/debounce.ts
  frontend/src/directives/modules/draggable.ts
  frontend/src/directives/modules/drawer-drag.ts
  frontend/src/directives/modules/longpress.ts
  frontend/src/directives/modules/throttle.ts
  frontend/src/directives/modules/water-marker.ts
  frontend/src/enums/http-enum.ts
  frontend/src/global/use-theme.ts
  frontend/src/hooks/interface/index.ts
  frontend/src/hooks/use-delete-data.ts
  frontend/src/hooks/use-logo.ts
  frontend/src/shims-vue.d.ts
  frontend/src/utils/xpack.ts
  frontend/src/views/setting/panel/index.vue
  frontend/vite.config.ts
Labels: do-not-merge/release-note-label-needed, dev-v2

#5638 fix: docker 镜像加速地址支持添加带端口
  frontend/src/views/container/setting/mirror/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm

#5635 feat: ClamAV 增加病毒文件处理策略
  backend/app/api/v1/clam.go
  backend/app/dto/clam.go
  backend/app/model/clam.go
  backend/app/service/clam.go
  backend/init/migration/migrations/v_1_10.go
  backend/utils/terminal/ws_local_session.go
  backend/utils/terminal/ws_session.go
  cmd/server/docs/docs.go
  cmd/server/docs/swagger.json
  cmd/server/docs/swagger.yaml
  frontend/src/api/interface/toolbox.ts
  frontend/src/api/modules/toolbox.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/toolbox/clam/index.vue
  frontend/src/views/toolbox/clam/operate/index.vue
  frontend/src/views/toolbox/clam/record/index.vue
  frontend/src/views/toolbox/clam/setting/index.vue
  frontend/src/views/toolbox/clam/status/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5636 feat: 文件管理文本编辑后退出前保存提示
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/host/file-management/code-editor/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5644 fix: 升级的时候忽略升级置灰
  frontend/src/views/app-store/installed/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5646 chore: Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: do-not-merge/release-note-label-needed, dev

#5647 feat: 文件列表组件新增创建文件夹功能
  backend/i18n/lang/en.yaml
  backend/i18n/lang/zh-Hant.yaml
  backend/i18n/lang/zh.yaml
  frontend/src/components/file-list/index.vue
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5652 chore: use unseq list
  CONTRIBUTING.md
Labels: do-not-merge/release-note-label-needed

#5655 fix: 解决文件上传拖拽栏上传多文件失败问题
  frontend/src/views/host/file-management/upload/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5656 chore: 编辑器统一代码风格和 prettier 风格保持一致
  frontend/.editorconfig
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5657 feat: 屏蔽选择网站运行目录中，辅助开发包目录
  frontend/src/views/website/website/config/basic/site-folder/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5659 fix: 修改 OneDrive token 刷新
  backend/app/service/backup.go
  backend/init/migration/migrations/v_1_9.go
  backend/utils/cloud_storage/client/onedrive.go
  frontend/src/lang/modules/zh.ts
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5662 feat: 优化英文翻译
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/container/container/index.vue
  frontend/src/views/container/image/index.vue
  frontend/src/views/cronjob/index.vue
  frontend/src/views/database/mysql/index.vue
  frontend/src/views/database/postgresql/index.vue
  frontend/src/views/host/file-management/index.vue
  frontend/src/views/host/firewall/forward/index.vue
  frontend/src/views/host/firewall/port/index.vue
  frontend/src/views/host/terminal/command/index.vue
  frontend/src/views/website/runtime/node/index.vue
  frontend/src/views/website/ssl/acme-account/create/index.vue
  frontend/src/views/website/ssl/acme-account/index.vue
  frontend/src/views/website/ssl/ca/create/index.vue
  frontend/src/views/website/ssl/ca/index.vue
  frontend/src/views/website/ssl/dns-account/create/index.vue
  frontend/src/views/website/ssl/dns-account/index.vue
  frontend/src/views/website/ssl/index.vue
  frontend/src/views/website/website/config/basic/auth-basic/create/index.vue
  frontend/src/views/website/website/config/basic/auth-basic/index.vue
  frontend/src/views/website/website/config/basic/https/index.vue
  frontend/src/views/website/website/config/basic/proxy/create/index.vue
  frontend/src/views/website/website/config/basic/proxy/index.vue
  frontend/src/views/website/website/config/basic/redirect/create/index.vue
  frontend/src/views/website/website/config/basic/redirect/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5664 feat: 容器仓库配置地址，增加有效性校
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/container/repo/operator/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5666 feat: 文本编辑器支持更多语言 vue 补充
  frontend/src/global/mimetype.ts
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5675 fix: 优化病毒扫描报告界面
  backend/app/api/v1/clam.go
  backend/app/dto/clam.go
  backend/app/service/clam.go
  backend/router/ro_toolbox.go
  cmd/server/docs/docs.go
  cmd/server/docs/swagger.json
  cmd/server/docs/swagger.yaml
  frontend/src/api/interface/toolbox.ts
  frontend/src/api/modules/toolbox.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/cronjob/record/index.vue
  frontend/src/views/toolbox/clam/index.vue
  frontend/src/views/toolbox/clam/record/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5676 feat: 机构证书增加下载功能
  backend/app/api/v1/website_ca.go
  backend/app/service/website_ca.go
  backend/router/ro_website_ca.go
  frontend/src/api/modules/website.ts
  frontend/src/lang/modules/en.ts
  frontend/src/views/cronjob/index.vue
  frontend/src/views/host/firewall/forward/index.vue
  frontend/src/views/host/firewall/port/index.vue
  frontend/src/views/website/ssl/ca/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5677 fix: 解决防火墙筛选失效的问题
  backend/app/service/firewall.go
  backend/utils/firewall/client/firewalld.go
  backend/utils/firewall/client/ufw.go
  frontend/src/views/host/firewall/forward/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5678 fix: 解决概览页磁盘挂载点路径带空格无法正常显示的问题
  backend/app/service/dashboard.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5680 feat: 文件列表组件新增创建文件夹以及文件功能
  frontend/src/components/file-list/index.vue
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5684 fix: 解决 Firewalld 防火墙列表显示不全的问题
  backend/utils/firewall/client/firewalld.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5689 feat: 文件编辑器侧边栏指上和选中文件样式调整
  frontend/src/styles/common.scss
  frontend/src/views/host/file-management/code-editor/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5692 feat: 暂时删除 SSL 证书 OCSP 校验
  cmd/server/nginx_conf/ssl.conf
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5693 pref: 优化 ClamAV 提示信息
  backend/app/service/clam.go
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/setting/backup-account/index.vue
  frontend/src/views/toolbox/clam/index.vue
  frontend/src/views/toolbox/clam/record/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5695 fix: 解决社区版刷新时网站标题显示问题
  frontend/src/utils/xpack.ts
Labels: do-not-merge/release-note-label-needed, dev

#5696 feat: 查看文件详情解除二进制文件限制
  backend/app/dto/request/file.go
  backend/app/service/file.go
  backend/utils/files/fileinfo.go
  frontend/src/api/interface/file.ts
  frontend/src/views/host/file-management/detail/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5709 fix: 解决病毒扫描病毒策略更新失败的问题
  backend/app/service/clam.go
  frontend/src/api/modules/toolbox.ts
  frontend/src/views/host/firewall/forward/operate/index.vue
  frontend/src/views/toolbox/clam/index.vue
Labels: dev

#5710 feat: 病毒扫描增加病毒库刷新状态
  backend/app/api/v1/clam.go
  backend/app/dto/clam.go
  backend/app/service/clam.go
  cmd/server/docs/docs.go
  cmd/server/docs/swagger.json
  cmd/server/docs/swagger.yaml
  frontend/src/api/interface/toolbox.ts
  frontend/src/api/modules/toolbox.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/toolbox/clam/setting/index.vue
  frontend/src/views/toolbox/clam/status/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5711 fix: 修改端口转发校验规则
  backend/app/service/firewall.go
  frontend/src/views/host/firewall/forward/operate/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5712 fix: 端口转发增加 ipv4 限制
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/host/firewall/forward/operate/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5713 fix: 调整病毒扫描设置界面样式
  frontend/src/api/modules/toolbox.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/toolbox/clam/index.vue
  frontend/src/views/toolbox/clam/setting/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5721 fix: 解决 Go 运行环境无法保存的问题
  backend/app/service/runtime.go
  frontend/src/views/website/runtime/go/index.vue
  frontend/src/views/website/runtime/java/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5724 fix: 解决 UFW 防火墙列表解析错误的问题
  backend/utils/firewall/client/ufw.go
  frontend/src/views/toolbox/clam/setting/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5727 feat: 统一日志组件
  frontend/src/components/container-log/index.vue
  frontend/src/components/log-pro/index.vue
  frontend/src/views/container/container/log/index.vue
  frontend/src/views/database/mysql/setting/index.vue
  frontend/src/views/database/mysql/setting/slow-log/index.vue
  frontend/src/views/host/ssh/ssh/index.vue
  frontend/src/views/toolbox/clam/record/index.vue
  frontend/src/views/toolbox/clam/setting/index.vue
  frontend/src/views/toolbox/supervisor/config/log/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#5730 fix: 判断文件是否为二进制文件，忽略文本类型文件
  backend/utils/files/fileinfo.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5731 pref: 优化代理提示信息
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5732 fix: 监听编辑器内容变化事件调整
  frontend/src/views/host/file-management/code-editor/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5733 fix: 解决运行环境显示容器名称错误的问题
  frontend/src/views/website/runtime/go/operate/index.vue
  frontend/src/views/website/runtime/java/index.vue
  frontend/src/views/website/runtime/java/operate/index.vue
  frontend/src/views/website/runtime/node/operate/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5739 fix: 解决快照恢复失败的问题
  backend/app/dto/container.go
  backend/app/service/snapshot_recover.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5743 chore: Update README.md
  README.md
Labels: do-not-merge/release-note-label-needed, dev

#5744 fix: VS Code 打开文件可以再次编辑配置
  frontend/src/components/vscode-open/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5748 refactor: 文本编辑器全屏按钮样式处理
  frontend/src/views/host/file-management/code-editor/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5745 feat: 七牛云备份账号支持设置超时时间
  backend/utils/cloud_storage/client/kodo.go
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/setting/backup-account/kodo/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5749 feat: 网站配置 HTTPS 证书时增加组织显示
  frontend/src/views/website/website/config/basic/https/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5751 fix: 解决 ftp 创建用户失败的问题
  backend/utils/toolbox/pure-ftpd.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5753 fix: 解决网站运行目录显示错误的问题
  backend/app/service/website.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5754 fix: 前端优化
  frontend/src/views/app-store/installed/index.vue
  frontend/src/views/container/repo/operator/index.vue
  frontend/src/views/toolbox/supervisor/file/index.vue
  frontend/src/views/website/website/config/basic/site-folder/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5755 fix: 前端优化
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/setting/backup-account/kodo/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5756 fix: 解决安装 mailserver 失败的问题
  backend/app/service/app.go
  backend/app/service/app_utils.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5757 feat: 删除无用代码
  backend/app/service/website.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5760 feat: 文本编辑器全屏高度处理
  frontend/src/views/host/file-management/code-editor/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5761 fix: 字符校验修正
  frontend/src/global/form-rules.ts
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5764 feat: 增加 Go 运行环境跳转
  frontend/src/views/app-store/apps/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5775 Add port to vscodeUrl in SSH remote connection
  frontend/src/components/vscode-open/index.vue
Labels: do-not-merge/release-note-label-needed

#5776 fix: 关闭抽屉同时销毁全部子元素
  frontend/src/views/host/file-management/wget/index.vue
  frontend/src/views/toolbox/supervisor/create/index.vue
  frontend/src/views/website/runtime/go/operate/index.vue
  frontend/src/views/website/runtime/java/operate/index.vue
  frontend/src/views/website/runtime/node/operate/index.vue
  frontend/src/views/website/ssl/ca/obtain/index.vue
  frontend/src/views/website/ssl/create/index.vue
  frontend/src/views/website/ssl/upload/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5781 feat: 文本编辑器新增右侧缩略图开关
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/styles/common.scss
  frontend/src/views/host/file-management/code-editor/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5784 feat: 增加 clamdscan 服务检测
  backend/app/service/clam.go
  backend/i18n/lang/en.yaml
  backend/i18n/lang/zh-Hant.yaml
  backend/i18n/lang/zh.yaml
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5792 fix: 修复变量名拼错
  backend/app/service/file.go
  backend/constant/errs.go
  backend/i18n/lang/en.yaml
  backend/i18n/lang/zh-Hant.yaml
  backend/i18n/lang/zh.yaml
Labels: do-not-merge/release-note-label-needed

#5817 feat: 病毒扫描增加状态判断
  backend/app/service/clam.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5824 pref: 优化远程数据库删除提示信息
  backend/utils/common/common.go
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/database/mysql/remote/delete/index.vue
  frontend/src/views/database/postgresql/remote/delete/index.vue
  frontend/src/views/database/redis/remote/delete/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5833 feat: 网站过期时间增加排序
  backend/app/dto/request/website.go
  backend/app/repo/website.go
  frontend/src/views/website/website/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5836 fix: 文本管理计算文件夹大小请求超时
  frontend/src/api/modules/files.ts
  frontend/src/views/host/file-management/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5838 fix: 关闭 pdf 预览
  frontend/package.json
  frontend/src/views/host/file-management/index.vue
  frontend/src/views/host/file-management/preview/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5844 fix: 查看文件/文件夹属性详情
  backend/utils/files/fileinfo.go
  frontend/src/views/host/file-management/detail/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5846 fix: 解决网站按过期时间排序之后导致的日期控件错误问题
  frontend/src/views/website/website/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5850 pref: 优化远程数据库解绑提示信息
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/database/mysql/remote/delete/index.vue
  frontend/src/views/database/mysql/remote/index.vue
  frontend/src/views/database/postgresql/remote/delete/index.vue
  frontend/src/views/database/postgresql/remote/index.vue
  frontend/src/views/database/redis/remote/delete/index.vue
  frontend/src/views/database/redis/remote/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5851 fix: 多个文件同时计算大小，计算状态独自显示
  frontend/src/views/host/file-management/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5849 feat: 计划任务备份应用/网站/数据库支持多选
  backend/app/service/cronjob_backup.go
  frontend/src/api/interface/cronjob.ts
  frontend/src/views/cronjob/operate/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5856 fix: 解决病毒定时扫描校验国际化的问题
  frontend/src/views/toolbox/clam/operate/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5868 feat: 上传文件使用父目录用户和用户组
  backend/app/api/v1/file.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5869 fix: 解决从网站上传的证书状态显示异常的问题
  backend/app/service/website.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5906 fix: 解决潜在的 SQL 注入漏洞
  backend/middleware/operation.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5908 fix: 解决安装 gitea 跳转到 postgres 报错的问题
  backend/app/service/app.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5909 fix: 解决应用商店 Go 和 Java 安装跳转错误的问题
  frontend/src/views/app-store/detail/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5910 pref: 移除部分废弃代码
  backend/utils/mysql/helper/dump.go
  backend/utils/mysql/helper/source.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5914 feat: 回滚代码
  backend/middleware/operation.go
Labels: do-not-merge/release-note-label-needed

#5917 fix: 解决系统日志解析错误的问题
  backend/app/api/v1/app.go
  backend/middleware/operation.go
  cmd/server/docs/docs.go
  cmd/server/docs/swagger.json
  cmd/server/docs/swagger.yaml
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5933 chore: Update README.md
  README.md
Labels: do-not-merge/release-note-label-needed

#5934 chore: Update README.md
  README.md
Labels: do-not-merge/release-note-label-needed, dev

#5942 feat: 2FA支持前一个验证码
  backend/utils/mfa/mfa.go
Labels: do-not-merge/release-note-label-needed

#5950 feat: 优化泛域名申请证书手动解析值
  backend/utils/ssl/client.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#5951 feat: 修改反向代理默认 Connection 请求头
  cmd/server/nginx_conf/proxy.conf
  cmd/server/nginx_conf/website_default.conf
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved
