Repository 1Panel-dev/1Panel, pull requests merged in 2024-02, with the labels that each got.

#3771 fix: 解决切换运行环境之后 PHP 高级设置还存在的问题
  frontend/src/views/website/website/create/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3773 pref: 优化同步快照返回信息
  backend/app/api/v1/backup.go
  backend/app/service/backup.go
  cmd/server/docs/docs.go
  cmd/server/docs/swagger.json
  cmd/server/docs/swagger.yaml
  frontend/src/views/setting/snapshot/import/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3772 style: 修改计划任务报告页面样式
  frontend/src/views/cronjob/record/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3775 pref: 优化容器列表选项列选项
  frontend/src/views/container/container/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3776 fix: 解决 Redis RDB 规则设置报错的问题
  backend/app/service/database_redis.go
  frontend/src/views/database/redis/setting/persistence/index.vue
Labels: do-not-merge/release-note-label-needed, dev

#3777 fix: 解决计划任务记录删除时文件被误删问题
  backend/app/dto/cronjob.go
  backend/app/service/cornjob.go
  cmd/server/docs/docs.go
  cmd/server/docs/swagger.json
  cmd/server/docs/swagger.yaml
  frontend/src/components/upload/index.vue
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/cronjob/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3778 feat: 计划任务备份增加随机后缀
  backend/app/service/backup_app.go
  backend/app/service/backup_mysql.go
  backend/app/service/backup_postgresql.go
  backend/app/service/backup_redis.go
  backend/app/service/backup_website.go
  backend/app/service/cronjob_backup.go
Labels: do-not-merge/release-note-label-needed, dev

#3782 fix: 解决本地备份账号无法切换到根目录的问题
  backend/app/service/backup.go
Labels: do-not-merge/release-note-label-needed, dev

#3785 fix: 解决网站日志切割备份路径错误的问题
  backend/app/api/v1/terminal.go
  backend/app/service/backup.go
Labels: do-not-merge/release-note-label-needed, dev

#3787 fix: 全局备份目录变量给定初始值
  backend/init/hook/hook.go
Labels: do-not-merge/release-note-label-needed, dev

#3797 fix: 修改同步快照过程中的名称校验
  backend/app/service/snapshot.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3805 fix: 解决移动设备下，容器名称丢失的问题
  frontend/src/views/container/container/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3808 style: 修改应用详情页面样式
  frontend/src/views/app-store/detail/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3809 style: 应用忽略升级样式修改
  frontend/src/views/app-store/installed/upgrade/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3816 feat: 限制版本为 latest 应用升级
  backend/app/service/app_utils.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3817 feat: 面板开启 https 时，cookie 开启 secure 属性
  backend/app/service/auth.go
  backend/app/service/setting.go
Labels: do-not-merge/release-note-label-needed, dev, approved

#3821 fix: 修改计划任务执行周期校验
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/cronjob/helper.ts
  frontend/src/views/cronjob/operate/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3829 fix: 解决删除备份文件路径错误的问题
  backend/app/service/backup.go
Labels: dev

#3831 fix: 解决版本升级时，过滤备份失败的备份文件
  backend/app/service/backup.go
  backend/init/migration/migrations/v_1_9.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3832 feat: 适配多容器应用
  backend/app/service/app.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3834 feat: SFTP Client 增加可连接性校验
  backend/init/migration/migrations/v_1_9.go
  backend/utils/cloud_storage/client/sftp.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3836 feat: WebDAV 支持连接 Alist
  backend/init/migration/migrate.go
  backend/init/migration/migrations/v_1_9.go
  backend/utils/cloud_storage/client/webdav.go
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/setting/backup-account/index.vue
  frontend/src/views/setting/backup-account/sftp/index.vue
  frontend/src/views/setting/backup-account/webdav/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3844 feat: Nginx 配置支持 Lua 模块
  backend/app/service/nginx_utils.go
  backend/app/service/website.go
  backend/app/service/website_utils.go
  backend/utils/nginx/components/block.go
  backend/utils/nginx/components/http.go
  backend/utils/nginx/components/location.go
  backend/utils/nginx/components/lua_block.go
  backend/utils/nginx/components/server.go
  backend/utils/nginx/components/statement.go
  backend/utils/nginx/components/upstream.go
  backend/utils/nginx/dumper.go
  backend/utils/nginx/nginx.go
  backend/utils/nginx/parser/flag/flag.go
  backend/utils/nginx/parser/lexer.go
  backend/utils/nginx/parser/parser.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3845 style: 系统快照恢复样式调整
  backend/init/migration/migrations/v_1_9.go
  frontend/src/views/setting/snapshot/status/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3847 feat: 升级 Go 版本到 1.21
  backend/app/service/container.go
  backend/utils/docker/compose.go
  go.mod
  go.sum
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3856 fix: 修改容器镜像仓库正则表达式
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/container/setting/mirror/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3857 fix: 解决容器监控单位不正确的问题
  frontend/src/components/v-charts/components/Line.vue
  frontend/src/utils/util.ts
  frontend/src/views/container/container/monitor/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3865 fix: 解决拖拽上传文件夹文件上传不全的问题
  backend/utils/docker/docker.go
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/host/file-management/upload/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3866 feat: 优化应用状态同步
  backend/app/service/app_install.go
  backend/app/service/app_utils.go
  backend/app/service/website.go
  backend/constant/app.go
  backend/utils/docker/docker.go
  frontend/src/views/app-store/installed/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3867 feat: 限制文件最大上传个数
  frontend/src/views/host/file-management/upload/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3887 fix: fix typo for i18n-en
  frontend/src/lang/modules/en.ts
Labels: do-not-merge/release-note-label-needed

#3897 Fix typos
  backend/app/repo/database_mysql.go
  backend/app/repo/database_postgresql.go
  backend/app/service/docker.go
  backend/app/service/snapshot_create.go
  backend/app/service/upgrade.go
  backend/init/business/business.go
  backend/init/db/db.go
  backend/init/log/log.go
  backend/utils/firewall/client/ufw.go
  backend/utils/mysql/helper/dump.go
  frontend/src/api/index.ts
  frontend/src/api/interface/container.ts
  frontend/src/api/modules/container.ts
  frontend/src/components/log-file/index.vue
  frontend/src/components/status/index.vue
  frontend/src/components/system-upgrade/index.vue
  frontend/src/enums/files.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/layout/index.vue
  frontend/src/utils/util.ts
  frontend/src/views/app-store/installed/ignore/index.vue
  frontend/src/views/app-store/installed/index.vue
  frontend/src/views/container/compose/index.vue
  frontend/src/views/container/container/index.vue
  frontend/src/views/container/image/build/index.vue
  frontend/src/views/container/image/load/index.vue
  frontend/src/views/container/image/push/index.vue
  frontend/src/views/container/image/save/index.vue
  frontend/src/views/container/image/tag/index.vue
  frontend/src/views/container/setting/index.vue
  frontend/src/views/database/redis/setting/status/index.vue
  frontend/src/views/host/file-management/compress/index.vue
  frontend/src/views/host/file-management/download/index.vue
  frontend/src/views/host/file-management/index.vue
  frontend/src/views/host/file-management/process/index.vue
  frontend/src/views/host/file-management/upload/index.vue
  frontend/src/views/host/process/network/index.vue
  frontend/src/views/setting/backup-account/onedrive/index.vue
  frontend/src/views/website/website/config/basic/index.vue
  frontend/src/views/website/website/config/safety/value-list/index.vue
  frontend/src/views/website/website/create/index.vue
Labels: do-not-merge/release-note-label-needed

#3907 feat: 升级依赖
  backend/app/service/app_install.go
  backend/app/service/app_utils.go
  backend/global/global.go
  backend/i18n/i18n.go
  backend/i18n/lang/en.yaml
  backend/i18n/lang/zh-Hant.yaml
  backend/i18n/lang/zh.yaml
  backend/init/router/router.go
  backend/server/server.go
  backend/utils/docker/compose.go
  frontend/src/views/app-store/installed/index.vue
  go.mod
  go.sum
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3911 Update README.md
  README.md
Labels: do-not-merge/release-note-label-needed

#3912 Update README.md
  README.md
Labels: do-not-merge/release-note-label-needed

#3918 pref: 优化应用安装表单选择器组件支持多选
  backend/app/service/app_install.go
  backend/app/service/app_utils.go
  frontend/src/views/app-store/detail/params/index.vue
  frontend/src/views/app-store/installed/detail/index.vue
Labels: do-not-merge/release-note-label-needed

#3922 fix: 解决备份账号异常导致备份记录无法删除的问题
  backend/app/service/backup.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3925 style: 修改备份账号提示信息
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/cronjob/index.vue
  frontend/src/views/cronjob/operate/index.vue
  frontend/src/views/setting/snapshot/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3926 fix: 快照时排除备份目录下的快照文件
  backend/app/service/snapshot_create.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3928 feat: 样式优化
  frontend/src/components/app-status/index.vue
  frontend/src/components/status/index.vue
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/styles/common.scss
  frontend/src/views/app-store/detail/params/index.vue
  frontend/src/views/app-store/installed/detail/index.vue
  frontend/src/views/app-store/installed/index.vue
  frontend/src/views/container/compose/index.vue
  frontend/src/views/container/setting/index.vue
  frontend/src/views/cronjob/index.vue
  frontend/src/views/cronjob/operate/index.vue
  frontend/src/views/home/index.vue
  frontend/src/views/host/file-management/index.vue
  frontend/src/views/host/firewall/port/index.vue
  frontend/src/views/setting/about/index.vue
  frontend/src/views/setting/backup-account/index.vue
  frontend/src/views/setting/snapshot/index.vue
  frontend/src/views/website/runtime/node/index.vue
  frontend/src/views/website/runtime/php/index.vue
Labels: do-not-merge/release-note-label-needed, dev

#3930 fix: 解决代码冲突
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/cronjob/index.vue
  frontend/src/views/cronjob/operate/index.vue
  frontend/src/views/setting/snapshot/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3938 pref: 计划任务数据库备份增加实例标签
  frontend/src/views/cronjob/operate/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3939 fix: 修改 Mysql 远程数据库添加校验
  backend/utils/mysql/client/info.go
  frontend/src/views/database/mysql/remote/operate/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3941 fix: Cookie 启用 httponly
  backend/app/service/auth.go
  backend/app/service/setting.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3942 fix: 解决远程数据库添加验证失败的问题
  backend/utils/mysql/client.go
  backend/utils/mysql/client/info.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3946 fix: 忽略 WebDAV 获取端口信息错误日志
  backend/utils/cloud_storage/client/helper.go
  backend/utils/cloud_storage/client/sftp.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3948 fix: 移除项目未使用代码
  backend/app/api/v1/database_postgresql.go
  backend/init/cache/badger_db/badger_db.go
  backend/utils/common/common.go
  backend/utils/docker/compose.go
  backend/utils/docker/docker.go
  backend/utils/encrypt/encrypt.go
  backend/utils/files/file_op.go
  backend/utils/ini_conf/ini.go
  backend/utils/mysql/client/info.go
  backend/utils/mysql/helper/dump.go
  backend/utils/mysql/helper/source.go
  backend/utils/nginx/components/config.go
  backend/utils/nginx/nginx.go
  backend/utils/nginx/nginx_test.go
  backend/utils/nginx/parser/flag/flag.go
  backend/utils/ssl/client.go
  backend/utils/websocket/process_data.go
  cmd/server/docs/docs.go
  cmd/server/docs/swagger.json
  cmd/server/docs/swagger.yaml
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3949 fix: 解决 Pr 导致的代码冲突
  frontend/src/views/app-store/detail/params/index.vue
  frontend/src/views/app-store/installed/detail/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3953 feat: 修改应用重建逻辑
  backend/app/service/app_utils.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3961 perf: 应用商店的应用介绍样式
  frontend/src/views/app-store/apps/index.vue
Labels: do-not-merge/release-note-label-needed

#3965 fix: 解决清空文件后保存失败的问题
  backend/app/dto/request/file.go
  frontend/src/views/host/file-management/code-editor/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3967 fix: 解决应用重建失败的问题
  backend/app/service/app_utils.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3980 fix: 解决容器镜像清理的显示问题
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/container/image/prune/index.vue
  frontend/src/views/setting/backup-account/index.vue
  frontend/src/views/setting/backup-account/local/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3983 fix: 解决拖动上传文件夹错误的问题
  frontend/src/views/host/file-management/upload/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3984 fix: 解决删除 openresty 之后没有同步删除 php 运行容器的问题
  backend/app/service/app_utils.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3987 fix: 解决快照恢复过程中生成回滚文件不完整的问题
  backend/app/service/snapshot.go
  backend/app/service/snapshot_create.go
Labels: do-not-merge/release-note-label-needed, dev

#3989 fix: 调整快照回滚逻辑
  backend/app/service/snapshot.go
  frontend/src/views/container/image/prune/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3991 fix: 解决应用同步异常的问题
  .gitignore
  backend/app/service/app_install.go
  backend/utils/docker/docker.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3992 feat: 面板帮助文档跳转到具体目录
  frontend/src/views/setting/backup-account/onedrive/index.vue
  frontend/src/views/setting/backup-account/webdav/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3993 fix: 修改快照 json 文件生成逻辑
  backend/app/service/snapshot.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3996 fix: 解决重复访问容器内部时，终端显示宽度异常的问题
  frontend/src/views/container/container/terminal/index.vue
Labels: do-not-merge/release-note-label-needed

#4008 feat: 增加 waf 模块
  .gitignore
  plugins/openresty/waf/conf/global.json
  plugins/openresty/waf/conf/waf.conf
  plugins/openresty/waf/config.lua
  plugins/openresty/waf/db.lua
  plugins/openresty/waf/html/5s.html
  plugins/openresty/waf/html/5s.js
  plugins/openresty/waf/html/ip.html
  plugins/openresty/waf/html/redirect.html
  plugins/openresty/waf/html/slide.html
  plugins/openresty/waf/html/slide.js
  plugins/openresty/waf/init.lua
  plugins/openresty/waf/lib/action.lua
  plugins/openresty/waf/lib/cc.lua
  plugins/openresty/waf/lib/file.lua
  plugins/openresty/waf/lib/geoip.lua
  plugins/openresty/waf/lib/lib.lua
  plugins/openresty/waf/lib/logger.lua
  plugins/openresty/waf/lib/logger_factory.lua
  plugins/openresty/waf/lib/redis_util.lua
  plugins/openresty/waf/lib/resty/cookie.lua
  plugins/openresty/waf/lib/resty/libinjection.lua
  plugins/openresty/waf/lib/resty/maxminddb.lua
  plugins/openresty/waf/lib/stringutf8.lua
  plugins/openresty/waf/lib/utils.lua
  plugins/openresty/waf/log_and_traffic.lua
  plugins/openresty/waf/rules/acl.json
  plugins/openresty/waf/rules/args.json
  plugins/openresty/waf/rules/ccurl.json
  plugins/openresty/waf/rules/cookie.json
  plugins/openresty/waf/rules/defaultUaBlack.json
  plugins/openresty/waf/rules/header.json
  plugins/openresty/waf/rules/ipBlack.json
  plugins/openresty/waf/rules/ipBlackList
  plugins/openresty/waf/rules/ipWhite.json
  plugins/openresty/waf/rules/methodWhite.json
  plugins/openresty/waf/rules/post.json
  plugins/openresty/waf/rules/uaBlack.json
  plugins/openresty/waf/rules/uaWhite.json
  plugins/openresty/waf/rules/urlBlack.json
  plugins/openresty/waf/rules/urlWhite.json
  plugins/openresty/waf/test.lua
  plugins/openresty/waf/waf.json
  plugins/openresty/waf/waf.lua
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4009 feat: 增加 x-Pack 菜单
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  go.mod
  go.sum
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4014 fix: 解决登陆页刷新跳转的问题
  frontend/src/routers/index.ts
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4003 fix: 初始化版本号变量为字符串类型，默认为空字符串
  frontend/src/components/system-upgrade/index.vue
Labels: do-not-merge/release-note-label-needed

#4023 fix: 解决容器资源使用率获取错误的问题
  backend/app/service/container.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved
