Repository 1Panel-dev/1Panel, pull requests merged in 2024-01, with the labels that each got.

#3499 feat: 完善 PostgreSQL 功能
  backend/app/api/v1/database_postgresql.go
  backend/app/dto/database_postgresql.go
  backend/app/service/app_utils.go
  backend/app/service/backup_postgresql.go
  backend/app/service/database.go
  backend/app/service/database_postgresql.go
  backend/router/ro_database.go
  backend/utils/mysql/client/local.go
  backend/utils/postgresql/client.go
  backend/utils/postgresql/client/info.go
  backend/utils/postgresql/client/local.go
  backend/utils/postgresql/client/remote.go
  cmd/server/docs/docs.go
  cmd/server/docs/swagger.json
  cmd/server/docs/swagger.yaml
  frontend/src/api/interface/database.ts
  frontend/src/api/modules/database.ts
  frontend/src/views/database/postgresql/index.vue
  frontend/src/views/database/postgresql/setting/index.vue
  frontend/src/views/database/postgresql/setting/status/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3500 fix: 修改快照备份失败的问题
  backend/app/service/snapshot.go
  backend/app/service/snapshot_create.go
  backend/app/service/upgrade.go
  frontend/src/views/setting/snapshot/snap_status/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3501 fix: 解决工具箱 Hosts 解析失败的问题
  backend/app/service/device.go
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/toolbox/device/hosts/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3502 feat: PHP 运行环境增加扩展模版
  backend/app/api/v1/entry.go
  backend/app/api/v1/php_extensions.go
  backend/app/dto/request/php_extensions.go
  backend/app/dto/response/php_extensions.go
  backend/app/model/php_extensions.go
  backend/app/repo/php_extensions.go
  backend/app/service/entry.go
  backend/app/service/php_extensions.go
  backend/init/migration/migrate.go
  backend/init/migration/migrations/v_1_9.go
  backend/router/ro_runtime.go
  cmd/server/docs/docs.go
  cmd/server/docs/swagger.json
  cmd/server/docs/swagger.yaml
  frontend/src/api/interface/runtime.ts
  frontend/src/api/modules/runtime.ts
  frontend/src/global/form-rules.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/website/runtime/php/create/index.vue
  frontend/src/views/website/runtime/php/extensions/index.vue
  frontend/src/views/website/runtime/php/extensions/operate/index.vue
  frontend/src/views/website/runtime/php/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3503 feat: 适配 Fail2ban 0.10.2 版本
  backend/utils/toolbox/fail2ban.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3504 feat: 应用安装支持选择 postgres
  backend/app/repo/app.go
  backend/app/repo/common.go
  backend/app/service/app.go
  backend/app/service/app_install.go
  backend/app/service/app_utils.go
  backend/constant/app.go
  frontend/src/components/app-status/index.vue
  frontend/src/views/website/website/create/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3519 feat: 暂时删除 xpack 相关代码
  backend/router/entry_xpack.go
  backend/server/init_xpack.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3520 feat: 计划任务增加 pg 备份
  backend/app/api/v1/database.go
  backend/app/dto/cronjob.go
  backend/app/dto/database.go
  backend/app/model/cronjob.go
  backend/app/service/app_install.go
  backend/app/service/cornjob.go
  backend/app/service/cronjob_helper.go
  backend/app/service/database.go
  backend/app/service/database_postgresql.go
  backend/init/migration/migrate.go
  backend/init/migration/migrations/init.go
  backend/init/migration/migrations/v_1_9.go
  backend/router/ro_database.go
  backend/utils/postgresql/client.go
  backend/utils/postgresql/client/local.go
  backend/utils/postgresql/client/remote.go
  cmd/server/docs/docs.go
  cmd/server/docs/swagger.json
  cmd/server/docs/swagger.yaml
  frontend/src/api/interface/cronjob.ts
  frontend/src/api/interface/database.ts
  frontend/src/api/modules/database.ts
  frontend/src/views/cronjob/operate/index.vue
  frontend/src/views/cronjob/record/index.vue
  frontend/src/views/database/postgresql/conn/index.vue
  frontend/src/views/database/postgresql/delete/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3527 fix: 解决容器未能正常运行情况下的页面显示异常问题
  frontend/src/components/app-status/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3528 feat: 优化 PostgreSQL 远程数据库备份恢复逻辑
  backend/utils/postgresql/client/remote.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3530 fix: 调整 PostgreSQL 用户绑定样式
  backend/utils/postgresql/client.go
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/database/postgresql/bind/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3537 feat: PostgreSQL 增加权限设置
  backend/app/api/v1/database_postgresql.go
  backend/app/dto/database_postgresql.go
  backend/app/model/database_postgresql.go
  backend/app/service/backup_app.go
  backend/app/service/database_postgresql.go
  backend/init/migration/migrate.go
  backend/init/migration/migrations/v_1_9.go
  backend/router/ro_database.go
  backend/utils/postgresql/client.go
  backend/utils/postgresql/client/info.go
  backend/utils/postgresql/client/local.go
  backend/utils/postgresql/client/remote.go
  cmd/server/docs/docs.go
  cmd/server/docs/swagger.json
  cmd/server/docs/swagger.yaml
  frontend/src/api/interface/database.ts
  frontend/src/api/modules/database.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/database/postgresql/bind/index.vue
  frontend/src/views/database/postgresql/create/index.vue
  frontend/src/views/database/postgresql/index.vue
  frontend/src/views/database/postgresql/privileges/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3538 feat: 优化 PostgreSQL 远程数据库备份逻辑
  backend/constant/errs.go
  backend/i18n/lang/en.yaml
  backend/i18n/lang/zh-Hant.yaml
  backend/i18n/lang/zh.yaml
  backend/utils/postgresql/client/remote.go
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/database/postgresql/index.vue
  frontend/src/views/database/postgresql/password/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3540 feat: 解决部分情况下申请证书超时的问题
  backend/app/dto/request/website_ssl.go
  backend/app/service/website_ssl.go
  backend/utils/ssl/client.go
  cmd/server/docs/docs.go
  cmd/server/docs/swagger.json
  cmd/server/docs/swagger.yaml
  frontend/src/api/interface/website.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/website/ssl/apply/index.vue
  frontend/src/views/website/ssl/create/index.vue
  frontend/src/views/website/ssl/obtain/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3541 fix: 解决 PHP 模版添加失败的问题
  backend/app/service/php_extensions.go
  frontend/src/global/form-rules.ts
  frontend/src/views/website/runtime/php/extensions/operate/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3542 fix: 解决卸载 PostgreSQL 后未删除数据的问题
  backend/app/api/v1/database_mysql.go
  backend/app/service/app_utils.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3543 添加安全检查，确保转换后的值在int类型的范围内
  backend/app/service/recycle_bin.go
Labels: do-not-merge/release-note-label-needed, lgtm

#3544 fix: 补充代码依赖
  backend/app/service/recycle_bin.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3546 fix: 解决 PostgreSQL 数据恢复失败的问题
  backend/app/service/backup_app.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3547 fix: 优化右侧抽屉内容过多导致显示不完整的问题
  frontend/src/components/drawer-header/index.vue
  frontend/src/global/form-rules.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/container/container/operate/index.vue
  frontend/src/views/container/container/terminal/index.vue
  frontend/src/views/database/mysql/bind/index.vue
  frontend/src/views/database/postgresql/bind/index.vue
  frontend/src/views/database/postgresql/remote/delete/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3554 style: 修改部分校验的提示文字
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3556 fix: 解决计划任务编辑报错的问题
  frontend/src/global/form-rules.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/cronjob/operate/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3559 style: 修改 pgsql 页面密码字段样式
  frontend/src/views/database/postgresql/conn/index.vue
  frontend/src/views/database/redis/password/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3560 fix: 解决 PostgreSQL 上传恢复报错的问题
  frontend/src/components/upload/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3558 fix: 解决镜像清理显示不全的问题
  backend/app/api/v1/image.go
  backend/app/service/image.go
  backend/router/ro_container.go
  cmd/server/docs/docs.go
  cmd/server/docs/swagger.json
  cmd/server/docs/swagger.yaml
  frontend/src/api/modules/container.ts
  frontend/src/views/container/image/index.vue
  frontend/src/views/container/image/prune/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3562 fix: 解决网站日志清理日志按钮无法点击的问题
  frontend/src/views/website/website/config/log/log-fiile/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3563 fix: 优化容器监控请求频率
  frontend/src/views/container/container/monitor/index.vue
Labels: do-not-merge/release-note-label-needed, dev

#3570 fix: 解决文件列表跳转每页条数限制不生效的问题
  frontend/src/views/host/file-management/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3572 fix: 解决计划任务备份网站失败的问题
  backend/app/dto/response/website.go
  backend/app/service/cronjob_helper.go
  backend/app/service/website.go
  backend/init/migration/migrate.go
  backend/init/migration/migrations/v_1_9.go
  frontend/src/views/cronjob/operate/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3573 fix: 解决网站日志切割失败的问题
  backend/app/service/cronjob_helper.go
  backend/app/service/database.go
Labels: do-not-merge/release-note-label-needed, dev

#3578 fix: 优化 Redis 状态显示
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/database/redis/setting/status/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3587 fix: 解决 WebDav 备份账号校验错误的问题
  frontend/src/views/setting/backup-account/webdav/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3610 fix: 解决 zip 压缩前后大小不变的问题
  backend/utils/files/file_op.go
Labels: do-not-merge/release-note-label-needed, dev

#3613 fix: 解决切换 PHP 版本扩展模版没办法继续选择的问题
  frontend/src/views/website/runtime/php/create/index.vue
Labels: do-not-merge/release-note-label-needed, dev

#3614 fix: 删除 hosts 错误提示信息
  frontend/src/views/toolbox/device/hosts/index.vue
Labels: do-not-merge/release-note-label-needed, dev

#3615 fix: 移除备份账号保存份数最大限制
  frontend/src/views/cronjob/operate/index.vue
Labels: do-not-merge/release-note-label-needed, dev

#3616 style: 容器列表页面适配手机端
  frontend/src/views/container/container/index.vue
Labels: do-not-merge/release-note-label-needed, dev

#3617 fix: WebDav 端口去掉必填校验
  backend/utils/cloud_storage/client/webdav.go
  frontend/src/views/setting/backup-account/webdav/index.vue
Labels: do-not-merge/release-note-label-needed, dev

#3619 fix: 解决类型断言错误的问题
  backend/utils/cloud_storage/client/helper.go
Labels: do-not-merge/release-note-label-needed, dev

#3621 fix: 解决部分 Onedrive 备份账号添加失败的问题
  backend/utils/cloud_storage/client/onedrive.go
Labels: do-not-merge/release-note-label-needed, dev

#3622 fix: 解决容器未启动时无法编辑计划任务的问题
  frontend/src/views/cronjob/operate/index.vue
Labels: do-not-merge/release-note-label-needed, dev

#3629 fix: 解决Redis配置修改报错的问题 (#3627)
  frontend/src/views/database/redis/setting/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm

#3634 faet: 设置默认主题为 `auto`
  backend/init/migration/migrations/init.go
  frontend/src/store/index.ts
Labels: do-not-merge/release-note-label-needed

#3632 fix: 解决网站删除目录错误的问题
  backend/app/service/website_utils.go
Labels: do-not-merge/release-note-label-needed, dev

#3638 fix: 解决计划任务快照失败的问题
  backend/app/service/snapshot.go
Labels: do-not-merge/release-note-label-needed, dev

#3645 fix: 解决网站日志清空页面没有刷新的问题
  frontend/src/components/log-file/index.vue
  frontend/src/views/website/website/config/log/log-fiile/index.vue
Labels: do-not-merge/release-note-label-needed, dev

#3647 fix: 反向代理的文本替换不兼容 " 符号的问题
  backend/utils/nginx/parser/lexer.go
Labels: do-not-merge/release-note-label-needed, dev

#3648 style: CloudFlare DNS 账号增加提示
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/website/ssl/dns-account/create/index.vue
Labels: do-not-merge/release-note-label-needed, dev

#3637 feat: OneDrive 增加 Token 刷新机制
  backend/app/api/v1/backup.go
  backend/app/service/backup.go
  backend/app/service/monitor.go
  backend/cron/cron.go
  backend/global/global.go
  backend/init/migration/migrate.go
  backend/init/migration/migrations/v_1_9.go
  backend/router/ro_setting.go
  backend/utils/cloud_storage/client/onedrive.go
  backend/utils/cloud_storage/client/s3.go
  backend/utils/cloud_storage/client/sftp.go
  frontend/src/api/modules/setting.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/setting/backup-account/index.vue
Labels: do-not-merge/release-note-label-needed, dev

#3652 feat: 文件编辑器增加 lua xml 语言支持
  frontend/src/global/mimetype.ts
Labels: do-not-merge/release-note-label-needed, dev

#3658 fix: 解决删除带特殊符号文件报错的问题 (#3657)
  backend/utils/files/file_op.go
Labels: do-not-merge/release-note-label-needed

#3673 feat:证书 DNS 账号增加腾讯云类型
  backend/utils/ssl/client.go
  frontend/src/global/mimetype.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/website/ssl/detail/index.vue
  frontend/src/views/website/ssl/dns-account/create/index.vue
  go.mod
  go.sum
Labels: do-not-merge/release-note-label-needed, dev

#3676 feat: 计划任务支持多周期执行
  backend/app/dto/cronjob.go
  backend/app/model/cronjob.go
  backend/app/service/cornjob.go
  backend/cron/cron.go
  backend/init/migration/migrate.go
  backend/init/migration/migrations/v_1_9.go
  cmd/server/docs/docs.go
  cmd/server/docs/swagger.json
  cmd/server/docs/swagger.yaml
  frontend/src/api/interface/cronjob.ts
  frontend/src/views/cronjob/helper.ts
  frontend/src/views/cronjob/index.vue
  frontend/src/views/cronjob/operate/index.vue
Labels: do-not-merge/release-note-label-needed, dev

#3681 feat: 优化应用升级逻辑 支持 docker-compose.yml 文件的 image 值中包含参数
  backend/app/service/app_utils.go
  backend/utils/docker/compose.go
Labels: do-not-merge/release-note-label-needed, dev

#3684 feat: 容器列表增加选择列功能
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/container/container/index.vue
Labels: do-not-merge/release-note-label-needed, dev

#3689 feat: 计划任务支持备份到多个备份账号
  backend/app/api/v1/backup.go
  backend/app/dto/backup.go
  backend/app/dto/cronjob.go
  backend/app/dto/setting.go
  backend/app/model/backup.go
  backend/app/model/cronjob.go
  backend/app/repo/backup.go
  backend/app/repo/cronjob.go
  backend/app/service/backup.go
  backend/app/service/backup_app.go
  backend/app/service/backup_mysql.go
  backend/app/service/backup_postgresql.go
  backend/app/service/backup_redis.go
  backend/app/service/backup_website.go
  backend/app/service/cornjob.go
  backend/app/service/cronjob_backup.go
  backend/app/service/cronjob_helper.go
  backend/app/service/snapshot.go
  backend/app/service/snapshot_create.go
  backend/constant/backup.go
  backend/init/migration/migrate.go
  backend/init/migration/migrations/v_1_9.go
  backend/router/ro_setting.go
  backend/utils/cloud_storage/client/local.go
  backend/utils/cloud_storage/client/sftp.go
  backend/utils/cloud_storage/cloud_storage_client.go
  backend/utils/cmd/cmd.go
  cmd/server/docs/docs.go
  cmd/server/docs/swagger.json
  cmd/server/docs/swagger.yaml
  frontend/src/api/interface/backup.ts
  frontend/src/api/interface/cronjob.ts
  frontend/src/api/modules/setting.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/cronjob/backup/index.vue
  frontend/src/views/cronjob/helper.ts
  frontend/src/views/cronjob/index.vue
  frontend/src/views/cronjob/operate/index.vue
  frontend/src/views/cronjob/record/index.vue
  frontend/src/views/setting/backup-account/onedrive/index.vue
Labels: do-not-merge/release-note-label-needed, dev

#3691 fix: 调整计划任务备份账号字段名
  backend/app/dto/cronjob.go
  backend/app/model/cronjob.go
  backend/app/repo/cronjob.go
  backend/app/service/backup.go
  backend/app/service/backup_website.go
  backend/app/service/cornjob.go
  backend/app/service/cronjob_backup.go
  backend/app/service/cronjob_helper.go
  backend/app/service/snapshot.go
  backend/app/service/snapshot_create.go
  backend/init/migration/migrations/v_1_9.go
  cmd/server/docs/docs.go
  cmd/server/docs/swagger.json
  cmd/server/docs/swagger.yaml
  frontend/src/api/interface/cronjob.ts
  frontend/src/views/cronjob/index.vue
  frontend/src/views/cronjob/operate/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3695 feat: 增加计划任务服务器时间同步提示信息
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/cronjob/operate/index.vue
Labels: do-not-merge/release-note-label-needed, dev

#3694 fix: 统一多行文本输入样式
  frontend/src/views/container/container/operate/index.vue
  frontend/src/views/container/image/build/index.vue
  frontend/src/views/container/network/create/index.vue
  frontend/src/views/container/setting/index.vue
  frontend/src/views/container/setting/mirror/index.vue
  frontend/src/views/container/setting/registry/index.vue
  frontend/src/views/container/volume/create/index.vue
  frontend/src/views/cronjob/operate/index.vue
  frontend/src/views/database/mysql/bind/index.vue
  frontend/src/views/database/mysql/create/index.vue
  frontend/src/views/database/mysql/password/index.vue
  frontend/src/views/host/firewall/ip/operate/index.vue
  frontend/src/views/host/ssh/ssh/pubkey/index.vue
  frontend/src/views/setting/backup-account/onedrive/index.vue
  frontend/src/views/setting/safe/allowips/index.vue
  frontend/src/views/setting/safe/index.vue
  frontend/src/views/setting/safe/ssl/index.vue
  frontend/src/views/toolbox/device/dns/index.vue
  frontend/src/views/toolbox/fail2ban/ips/index.vue
  frontend/src/views/website/runtime/php/extensions/operate/index.vue
  frontend/src/views/website/ssl/ca/detail/index.vue
  frontend/src/views/website/ssl/ca/obtain/index.vue
  frontend/src/views/website/ssl/create/index.vue
  frontend/src/views/website/ssl/detail/index.vue
  frontend/src/views/website/website/config/basic/anti-Leech/index.vue
  frontend/src/views/website/website/config/basic/default-doc/index.vue
  frontend/src/views/website/website/config/basic/domain/create/index.vue
  frontend/src/views/website/website/config/basic/https/index.vue
  frontend/src/views/website/website/config/safety/file-block-list/index.vue
  frontend/src/views/website/website/config/safety/simple-list/index.vue
  frontend/src/views/website/website/create/index.vue
Labels: do-not-merge/release-note-label-needed, dev

#3693 feat: 快照支持本地目录及多选备份账号
  backend/app/dto/setting.go
  backend/app/model/snapshot.go
  backend/init/migration/migrate.go
  backend/init/migration/migrations/v_1_9.go
  frontend/src/api/interface/setting.ts
  frontend/src/views/setting/snapshot/index.vue
Labels: do-not-merge/release-note-label-needed, dev

#3696 fix: 调整快照页面备份路径样式
  backend/app/dto/setting.go
  backend/app/service/cronjob_backup.go
  backend/init/migration/migrations/v_1_9.go
  frontend/src/views/cronjob/index.vue
  frontend/src/views/setting/snapshot/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm

#3700 fix: WebDav 支持 https
  backend/utils/cloud_storage/client/sftp.go
  backend/utils/cloud_storage/client/webdav.go
  frontend/src/views/cronjob/backup/index.vue
Labels: dev

#3702 fix: 解决登陆状态下跳转安全入口的问题
  frontend/src/routers/index.ts
Labels: dev

#3701 feat: PostgreSQL 远程数据库增加用户绑定提示信息
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/database/postgresql/remote/operate/index.vue
Labels: dev

#3703 fix: 解决接口文档描述不一致的问题
  backend/app/api/v1/backup.go
  backend/app/api/v1/cronjob.go
  backend/app/api/v1/file.go
  backend/app/api/v1/nginx.go
  cmd/server/docs/docs.go
  cmd/server/docs/swagger.json
  cmd/server/docs/swagger.yaml
Labels: dev

#3704 fix: 解决 Fail2ban 禁用方式切换失败的问题
  backend/app/service/fail2ban.go
  backend/utils/firewall/client/firewalld.go
Labels: dev

#3707 feat: 主机快速命令增加排序
  backend/app/dto/command.go
  backend/app/service/command.go
  frontend/src/api/interface/command.ts
  frontend/src/api/modules/host.ts
  frontend/src/views/host/terminal/command/index.vue
Labels: dev

#3710 fix: 计划任务名称禁用空格
  frontend/src/views/cronjob/operate/index.vue
Labels: do-not-merge/release-note-label-needed, dev

#3711 feat: 增加备份恢复确认框
  frontend/src/components/backup/index.vue
  frontend/src/components/upload/index.vue
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
Labels: do-not-merge/release-note-label-needed, dev

#3712 feat: 页脚增加项目跳转地址
  frontend/src/components/system-upgrade/index.vue
Labels: do-not-merge/release-note-label-needed, dev

#3714 fix: 界面表格样式调整
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/styles/common.scss
  frontend/src/views/container/container/index.vue
  frontend/src/views/cronjob/index.vue
  frontend/src/views/cronjob/operate/index.vue
Labels: do-not-merge/release-note-label-needed, dev

#3716 fix: 解决日志中出现非UTF-8编码字符导致日志错误 (#3715)
  backend/app/service/container.go
Labels: do-not-merge/release-note-label-needed

#3717 fix: 解决备份列表异常时，备份列表无法打开的问题
  backend/app/service/backup.go
  backend/app/service/cronjob_helper.go
  frontend/src/api/modules/setting.ts
  frontend/src/components/backup/index.vue
  frontend/src/views/app-store/installed/index.vue
  frontend/src/views/cronjob/backup/index.vue
Labels: do-not-merge/release-note-label-needed, dev

#3718 fix: 计划任务列表样式调整
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/cronjob/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3733 fix: 优化缓存清理界面样式
  backend/app/service/snapshot.go
  frontend/src/api/interface/setting.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/setting/snapshot/index.vue
  frontend/src/views/toolbox/clean/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3734 fix: 解决 Node.js 运行环境网站停止失败的问题
  backend/app/service/website_utils.go
Labels: do-not-merge/release-note-label-needed, dev

#3735 fix: 数据库连接信息更改为容器名
  backend/app/dto/response/app.go
  backend/app/service/app_install.go
  frontend/src/api/interface/app.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/styles/common.scss
  frontend/src/views/database/mysql/conn/index.vue
  frontend/src/views/database/postgresql/conn/index.vue
  frontend/src/views/database/redis/password/index.vue
Labels: do-not-merge/release-note-label-needed, dev

#3740 perf: 优化计划任务备份列表打开速度
  backend/app/service/backup.go
Labels: do-not-merge/release-note-label-needed, dev

#3741 fix: 解决服务重启后计划任务状态错误的问题
  backend/init/hook/hook.go
Labels: do-not-merge/release-note-label-needed, dev

#3742 fix: 解决计划任务备份上传路径错误的问题
  backend/app/service/cronjob_helper.go
Labels: do-not-merge/release-note-label-needed, dev

#3743 fix: 解决计划任务备份下载路径错误的问题
  backend/app/service/cronjob_backup.go
  frontend/src/views/cronjob/operate/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3748 style: 快照状态界面样式调整
  frontend/src/api/interface/setting.ts
  frontend/src/views/setting/backup-account/onedrive/index.vue
  frontend/src/views/setting/snapshot/import/index.vue
  frontend/src/views/setting/snapshot/index.vue
  frontend/src/views/setting/snapshot/snap_status/index.vue
  frontend/src/views/setting/snapshot/status/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3744 fix: 解决计划任务升级导致数据异常问题
  backend/init/migration/migrations/v_1_9.go
  backend/utils/cloud_storage/client/sftp.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3749 fix: 解决扩展模版过长无法保存的问题
  frontend/src/global/form-rules.ts
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3746 feat: 安装升级应用增加强制拉取镜像选项
  backend/app/dto/request/app.go
  backend/app/service/app.go
  backend/app/service/app_install.go
  backend/app/service/app_utils.go
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/app-store/detail/install/index.vue
  frontend/src/views/app-store/installed/upgrade/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm

#3750 fix: 解决快照恢复失败的问题
  backend/app/service/snapshot.go
  backend/app/service/snapshot_create.go
  backend/init/hook/hook.go
  backend/utils/cloud_storage/client/local.go
  backend/utils/cloud_storage/client/onedrive.go
  frontend/src/views/setting/snapshot/status/index.vue
Labels: dev

#3751 style: 修改同步服务器时间计划任务提示信息
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/toolbox/fail2ban/ips/index.vue
Labels: dev

#3755 fix: 解决数据升级失败的问题
  backend/init/migration/migrations/v_1_9.go
Labels: do-not-merge/release-note-label-needed, dev

#3759 fix: 解决镜像清理列表显示不全的问题
  frontend/src/views/container/image/prune/index.vue
Labels: do-not-merge/release-note-label-needed, dev

#3763 feat: 备份账号适配世纪互联版本 OneDrive
  backend/utils/cloud_storage/client/cos.go
  backend/utils/cloud_storage/client/helper.go
  backend/utils/cloud_storage/client/kodo.go
  backend/utils/cloud_storage/client/local.go
  backend/utils/cloud_storage/client/minio.go
  backend/utils/cloud_storage/client/onedrive.go
  backend/utils/cloud_storage/client/oss.go
  backend/utils/cloud_storage/client/s3.go
  backend/utils/cloud_storage/client/sftp.go
  backend/utils/cloud_storage/client/webdav.go
Labels: dev

#3764 fix: 暂时移除网站备份规则功能
  backend/app/service/backup_website.go
  backend/app/service/cronjob_backup.go
  frontend/src/views/cronjob/operate/index.vue
Labels: dev

#3766 fix: 解决升级导致计划任务数据丢失的问题
  backend/init/migration/migrations/v_1_9.go
Labels: dev

#3769 fix: 解决应用恢复导致计划任务执行失败的问题
  backend/app/repo/cronjob.go
  backend/app/service/backup_app.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3768 fix: 解决文件下载路径包含 + 下载失败的问题
  backend/app/api/v1/file.go
  cmd/server/docs/docs.go
  cmd/server/docs/swagger.json
  cmd/server/docs/swagger.yaml
  frontend/src/utils/util.ts
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#3770 pref: 优化计划任务备份列表排序
  backend/app/service/backup.go
Labels: do-not-merge/release-note-label-needed, dev
