Repository 1Panel-dev/1Panel, pull requests merged in 2024-10, with the labels that each got.

#6647 fix: 修改上传恢复提示信息
  frontend/src/components/upload/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#6650 feat: 统一抽屉样式
  agent/app/service/backup_website.go
  agent/app/service/container.go
  agent/app/service/website_ca.go
  agent/app/service/website_utils.go
  frontend/src/components/compose-log/index.vue
  frontend/src/views/app-store/detail/index.vue
  frontend/src/views/app-store/installed/index.vue
  frontend/src/views/container/container/log/index.vue
  frontend/src/views/website/ssl/ca/detail/index.vue
  frontend/src/views/website/website/config/basic/proxy/create/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, dev-v2

#6651 feat: 支持离线版许可证
  frontend/src/api/interface/setting.ts
  frontend/src/views/setting/license/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#6652 feat: 运行环境支持增加环境变量
  agent/app/dto/request/runtime.go
  agent/app/dto/response/runtime.go
  agent/app/service/app_install.go
  agent/app/service/runtime.go
  agent/app/service/runtime_utils.go
  agent/utils/docker/compose.go
  frontend/src/api/interface/runtime.ts
  frontend/src/components/compose-log/index.vue
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/website/runtime/environment/index.vue
  frontend/src/views/website/runtime/go/operate/index.vue
  frontend/src/views/website/runtime/java/operate/index.vue
  frontend/src/views/website/runtime/node/operate/index.vue
  frontend/src/views/website/runtime/port/index.vue
  frontend/src/views/website/ssl/ca/detail/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#6653 feat: 快照列表改为异步获取大小
  agent/app/api/v2/snapshot.go
  agent/app/dto/snapshot.go
  agent/app/service/backup.go
  agent/app/service/snapshot.go
  agent/router/ro_setting.go
  frontend/src/api/interface/setting.ts
  frontend/src/api/modules/setting.ts
  frontend/src/views/setting/snapshot/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#6656 chore:删除error_code组件的body标签
  frontend/src/components/error-message/error_code.vue
Labels: do-not-merge/release-note-label-needed

#6659 feat: 反代回源 SNI 支持设置 proxy_ssl_name
  backend/app/dto/request/website.go
  backend/app/service/website.go
  cmd/server/nginx_conf/proxy.conf
  frontend/src/api/interface/website.ts
  frontend/src/views/website/website/config/basic/proxy/create/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#6661 feat: 反向代理文本替换增加 sub_filter_types 参数
  backend/utils/nginx/components/location.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#6663 feat: 伪静态支持保存为模版
  agent/app/api/v2/website.go
  agent/app/dto/request/nginx.go
  agent/app/service/backup_website.go
  agent/app/service/website.go
  agent/app/service/website_utils.go
  agent/router/ro_website.go
  frontend/src/api/interface/website.ts
  frontend/src/api/modules/website.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/website/website/config/basic/rewrite/custom/index.vue
  frontend/src/views/website/website/config/basic/rewrite/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#6667 feat: 容器列表缓存是否显示应用商店容器
  frontend/src/views/container/container/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#6670 feat: 快照列表改为异步获取大小
  backend/app/api/v1/snapshot.go
  backend/app/dto/setting.go
  backend/app/service/snapshot.go
  backend/router/ro_setting.go
  frontend/src/api/interface/setting.ts
  frontend/src/api/modules/setting.ts
  frontend/src/views/setting/snapshot/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#6672 fix: 概览页磁盘显示排除 overlay 类型
  backend/app/service/dashboard.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#6680 feat: 表格增加手动刷新按钮
  frontend/src/components/index.ts
  frontend/src/components/table-refresh/index.vue
  frontend/src/components/table-setting/index.vue
  frontend/src/views/container/compose/index.vue
  frontend/src/views/container/container/index.vue
  frontend/src/views/container/image/index.vue
  frontend/src/views/container/network/index.vue
  frontend/src/views/container/repo/index.vue
  frontend/src/views/container/template/index.vue
  frontend/src/views/container/volume/index.vue
  frontend/src/views/cronjob/index.vue
  frontend/src/views/host/firewall/forward/index.vue
  frontend/src/views/host/firewall/ip/index.vue
  frontend/src/views/host/firewall/port/index.vue
  frontend/src/views/host/ssh/log/log.vue
  frontend/src/views/log/login/index.vue
  frontend/src/views/log/operation/index.vue
  frontend/src/views/log/task/index.vue
  frontend/src/views/setting/backup-account/index.vue
  frontend/src/views/setting/snapshot/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#6677 feat: sftp 备份账号支持密钥添加
  agent/utils/cloud_storage/client/sftp.go
  core/app/service/backup.go
  core/utils/cloud_storage/client/sftp.go
  frontend/src/views/setting/backup-account/operate/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#6679 feat: 运行环境增加 Python
  agent/app/service/runtime.go
  agent/app/service/runtime_utils.go
  agent/constant/runtime.go
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/routers/modules/website.ts
  frontend/src/views/app-store/apps/index.vue
  frontend/src/views/website/runtime/index.vue
  frontend/src/views/website/runtime/python/index.vue
  frontend/src/views/website/runtime/python/operate/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#6681 feat: 增加 Python 运行环境
  backend/app/service/runtime.go
  backend/app/service/runtime_utils.go
  backend/app/service/website.go
  backend/app/service/website_utils.go
  backend/constant/runtime.go
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/routers/modules/website.ts
  frontend/src/views/app-store/apps/index.vue
  frontend/src/views/app-store/detail/index.vue
  frontend/src/views/website/runtime/index.vue
  frontend/src/views/website/runtime/python/index.vue
  frontend/src/views/website/runtime/python/operate/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm

#6685 feat: 计划任务支持自定义表达式，预览最近五次执行时间
  agent/app/api/v2/cronjob.go
  agent/app/dto/cronjob.go
  agent/app/model/cronjob.go
  agent/app/service/cronjob.go
  agent/init/migration/migrations/init.go
  agent/router/ro_cronjob.go
  frontend/src/api/interface/cronjob.ts
  frontend/src/api/modules/cronjob.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/cronjob/helper.ts
  frontend/src/views/cronjob/index.vue
  frontend/src/views/cronjob/operate/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#6687 feat: 增加华为云申请证书
  frontend/src/global/mimetype.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/website/ssl/dns-account/create/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#6688 feat:firewalld和ufw同时存在时,不进行操作
  backend/utils/firewall/client.go
Labels: do-not-merge/release-note-label-needed

#6698 fix: 修复“修改文件权限时，文件所属用户和用户组不显示”问题
  frontend/src/views/host/file-management/batch-role/index.vue
Labels: do-not-merge/release-note-label-needed

#6696 fix: 容器重启前增加校验操作
  backend/app/service/docker.go
  backend/app/service/image_repo.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm

#6697 feat: 应用商店支持使用自定义的应用包
  agent/app/dto/response/app.go
  agent/app/repo/app.go
  agent/app/repo/app_detail.go
  agent/app/repo/app_tag.go
  agent/app/repo/tag.go
  agent/app/service/app.go
  agent/app/service/app_utils.go
  agent/i18n/lang/en.yaml
  agent/i18n/lang/zh-Hant.yaml
  agent/i18n/lang/zh.yaml
  agent/utils/xpack/xpack.go
  frontend/src/api/modules/app.ts
  frontend/src/views/app-store/apps/index.vue
  frontend/src/views/app-store/setting/default-domain/index.vue
  frontend/src/views/app-store/setting/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, dev-v2

#6706 style: 修改按钮组边框宽度不一致的问题
  frontend/src/components/layout-content/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#6710 pref: 优化网站日志读取
  frontend/src/components/log-file/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#6712 style: 优化登录页软件许可协议提示语样式
  frontend/src/views/login/components/login-form.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#6711 style: 解决 Alert 提示组件标题存在链接时文字错位问题
  frontend/src/styles/reset.scss
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#6709 feat: 增加病毒扫描和计划任务告警
  backend/app/dto/alert.go
  backend/app/dto/clam.go
  backend/app/dto/cronjob.go
  backend/app/service/clam.go
  backend/app/service/cronjob.go
  backend/app/service/cronjob_helper.go
  backend/utils/xpack/xpack.go
  frontend/src/api/interface/cronjob.ts
  frontend/src/api/interface/toolbox.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/cronjob/operate/index.vue
  frontend/src/views/toolbox/clam/index.vue
  frontend/src/views/toolbox/clam/operate/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#6721 feat: 计划任务脚本支持选择用户及解释器
  agent/app/api/v2/device.go
  agent/app/dto/cronjob.go
  agent/app/model/cronjob.go
  agent/app/service/cronjob.go
  agent/app/service/cronjob_helper.go
  agent/app/service/device.go
  agent/app/task/task.go
  agent/i18n/lang/en.yaml
  agent/i18n/lang/zh-Hant.yaml
  agent/i18n/lang/zh.yaml
  agent/init/migration/migrate.go
  agent/init/migration/migrations/init.go
  agent/router/ro_toolbox.go
  agent/utils/cmd/cmd.go
  frontend/src/api/interface/cronjob.ts
  frontend/src/api/modules/toolbox.ts
  frontend/src/components/codemirror-pro/index.vue
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/cronjob/operate/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#6722 feat: 计划任务列表增加上次执行状态
  agent/app/dto/cronjob.go
  agent/app/service/cronjob.go
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/utils/shortcuts.ts
  frontend/src/views/cronjob/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#6720 feat: 文件夹选择控件，默认选中当前目录
  frontend/src/components/file-list/index.vue
  frontend/src/views/cronjob/operate/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#6733 style: 优化应用升级文件对比样式
  frontend/src/views/app-store/installed/upgrade/diff/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#6732 feat: 计划任务增加文件备份
  agent/app/dto/cronjob.go
  agent/app/model/cronjob.go
  agent/app/service/cronjob_backup.go
  agent/app/service/cronjob_helper.go
  agent/init/migration/migrations/init.go
  agent/utils/files/tar_gz.go
  frontend/src/api/interface/cronjob.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/cronjob/operate/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#6736 feat: 容器列表支持搜索镜像
  agent/app/service/container.go
Labels: do-not-merge/release-note-label-needed, lgtm, dev-v2

#6740 style: 优化一些样式
  frontend/src/views/website/runtime/go/operate/index.vue
  frontend/src/views/website/runtime/java/operate/index.vue
  frontend/src/views/website/runtime/python/operate/index.vue
  frontend/src/views/website/ssl/dns-account/create/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#6741 feat: 支持直接从命令创建容器，表单样式优化
  agent/app/api/v2/container.go
  agent/app/dto/container.go
  agent/app/service/container.go
  agent/router/ro_container.go
  frontend/src/api/modules/container.ts
  frontend/src/components/codemirror-pro/index.vue
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/container/container/command/index.vue
  frontend/src/views/container/container/operate/index.vue
  frontend/src/views/container/image/tag/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#6744 feat: PHP 镜像 build 增加超时时间
  backend/app/service/runtime_utils.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#6748 feat: 容器镜像支持多选删除
  agent/app/api/v2/image.go
  agent/app/service/container.go
  agent/app/service/image.go
  frontend/src/api/modules/container.ts
  frontend/src/views/container/image/prune/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#6749 feat: 计划任务失败告警支持全类型告警
  backend/app/service/cronjob_helper.go
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/cronjob/operate/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#6751 feat: 病毒扫描定时扫描和短信告警合并提示许可证绑定
  frontend/src/views/toolbox/clam/operate/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#6752 fix: Switch 组件 small 尺寸样式修复
  frontend/src/styles/reset.scss
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#6753 feat: 容器列表增加安装目录跳转
  agent/app/dto/container.go
  agent/app/service/container.go
  frontend/src/views/container/container/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#6756 feat: 概览页磁盘支持跳转挂载路径
  frontend/src/views/home/status/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#6750 fix: 容器部分操作动态修改执行命令
  backend/app/service/docker.go
  backend/app/service/firewall.go
  backend/app/service/image_repo.go
  backend/app/service/snapshot_recover.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#6757 feat: 优化数据库切换效果
  frontend/src/components/app-status/index.vue
  frontend/src/views/database/mysql/index.vue
  frontend/src/views/database/postgresql/index.vue
  frontend/src/views/database/redis/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#6759 feat: postgresql 远程数据库支持 17.x 版本
  frontend/src/views/database/postgresql/remote/index.vue
  frontend/src/views/database/postgresql/remote/operate/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#6765 fix: 解决移动端主机文件批量删除错误
  frontend/src/views/host/file-management/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#6772 feat: 增加容器创建表单内容
  agent/app/dto/container.go
  agent/app/service/container.go
  frontend/src/api/interface/container.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/container/container/operate/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#6773 fix: 解决容器编排跳转路径错误的问题
  frontend/src/views/container/compose/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#6774 style: 日志样式调整
  frontend/src/components/log-file/index.vue
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#6784 fix: 解决证书自动续签日志报错的问题
  backend/app/dto/request/website_ssl.go
  backend/app/service/website_ssl.go
  backend/cron/job/ssl.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#6785 fix: 解决创建运行环境报名称存在的问题
  backend/app/service/runtime.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#6790 fix: 解析病毒扫描内容格式处理
  backend/app/service/clam.go
  frontend/src/views/toolbox/clam/operate/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#6792 feat: SSL 配置增加重启选项
  backend/app/dto/setting.go
  backend/app/service/setting.go
  backend/app/service/website_utils.go
  backend/cron/job/ssl.go
  backend/init/migration/migrate.go
  backend/init/migration/migrations/v_1_10.go
  frontend/src/api/interface/setting.ts
  frontend/src/components/log-dialog/index.vue
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/setting/safe/index.vue
  frontend/src/views/setting/safe/ssl/index.vue
  frontend/src/views/toolbox/supervisor/file/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#6793 fix: otel dependencies
  go.mod
  go.sum
Labels: do-not-merge/release-note-label-needed

#6797 feat: 优化防篡改拒绝操作提示信息
  frontend/src/api/index.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#6798 feat: 修改容器操作超时时间
  frontend/src/api/modules/container.ts
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#6800 fix: 解决 Mysql 特定版本忽略升级失效的问题
  backend/app/service/app_utils.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#6799 fix: 文件夹选择控件，选择文件时不默认选择当前目录
  frontend/src/components/file-list/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#6801 fix: 解决 Python 运行环境编辑报错的问题
  backend/app/service/runtime.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#6805 fix: 解决 Docker 重启失败的问题
  backend/app/service/docker.go
  backend/utils/cmd/cmd.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#6806 fix: 完善短信告警国际化
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#6807 feat: 创建运行环境网站增加默认网络创建
  backend/app/service/website.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#6816 fix: 解决快照列表排序的问题
  backend/app/dto/setting.go
  backend/app/service/cronjob_backup.go
  frontend/src/api/interface/setting.ts
  frontend/src/views/setting/snapshot/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#6815 feat: 创建运行环境网站增加 Python 选项
  frontend/src/routers/modules/website.ts
  frontend/src/views/website/website/create/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#6817 feat: 面板重启导致计划任务失败时进行短信告警
  backend/init/hook/hook.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#6820 feat: 启动运行环境增加默认网络检测
  backend/app/service/runtime.go
  backend/app/service/website.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#6822 style: 容器样式调整
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/container/container/operate/index.vue
  frontend/src/views/container/network/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#6824 fix: 解决低版本 dockerd 命令不兼容的问题
  backend/app/service/docker.go
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#6825 fix: 解决计划任务告警误报的问题
  backend/init/hook/hook.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#6836 fix: 补全进程守护 watch 引用
  frontend/src/views/toolbox/supervisor/file/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm

#6845 fix: 解决容器镜像仓库编辑失败的问题
  backend/app/service/image_repo.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#6862 fix: 解决容器编排路径为空时无法删除的问题
  backend/app/dto/container.go
  backend/app/service/container_compose.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#6870 feat: 完成操作日志功能
  agent/app/api/v2/runtime.go
  agent/app/api/v2/snapshot.go
  agent/app/api/v2/website.go
  agent/app/service/cronjob_helper.go
  cmd/server/docs/docs.go
  cmd/server/docs/swagger.json
  cmd/server/docs/swagger_test.go
  cmd/server/docs/x-log.json
  core/app/api/v2/host.go
  core/middleware/operation.go
  frontend/src/api/modules/log.ts
  frontend/src/api/modules/setting.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/cronjob/operate/index.vue
  frontend/src/views/log/operation/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#6882 feat: 统一后端错误处理
  agent/app/api/v2/app.go
  agent/app/api/v2/app_install.go
  agent/app/api/v2/backup.go
  agent/app/api/v2/clam.go
  agent/app/api/v2/compose_template.go
  agent/app/api/v2/container.go
  agent/app/api/v2/cronjob.go
  agent/app/api/v2/dashboard.go
  agent/app/api/v2/database.go
  agent/app/api/v2/database_common.go
  agent/app/api/v2/database_mysql.go
  agent/app/api/v2/database_postgresql.go
  agent/app/api/v2/database_redis.go
  agent/app/api/v2/device.go
  agent/app/api/v2/docker.go
  agent/app/api/v2/fail2ban.go
  agent/app/api/v2/favorite.go
  agent/app/api/v2/file.go
  agent/app/api/v2/firewall.go
  agent/app/api/v2/ftp.go
  agent/app/api/v2/health.go
  agent/app/api/v2/helper/helper.go
  agent/app/api/v2/host_tool.go
  agent/app/api/v2/image.go
  agent/app/api/v2/image_repo.go
  agent/app/api/v2/logs.go
  agent/app/api/v2/monitor.go
  agent/app/api/v2/nginx.go
  agent/app/api/v2/php_extensions.go
  agent/app/api/v2/process.go
  agent/app/api/v2/recycle_bin.go
  agent/app/api/v2/runtime.go
  agent/app/api/v2/setting.go
  agent/app/api/v2/snapshot.go
  agent/app/api/v2/ssh.go
  agent/app/api/v2/task.go
  agent/app/api/v2/website.go
  agent/app/api/v2/website_acme_account.go
  agent/app/api/v2/website_ca.go
  agent/app/api/v2/website_dns_account.go
  agent/app/api/v2/website_domain.go
  agent/app/api/v2/website_ssl.go
  agent/app/service/runtime.go
  agent/app/service/runtime_utils.go
  agent/app/service/website.go
  agent/app/service/website_utils.go
  core/app/api/v2/auth.go
  core/app/api/v2/backup.go
  core/app/api/v2/command.go
  core/app/api/v2/group.go
  core/app/api/v2/helper/helper.go
  core/app/api/v2/host.go
  core/app/api/v2/logs.go
  core/app/api/v2/setting.go
  core/app/api/v2/upgrade.go
  frontend/src/components/layout-content/index.vue
  frontend/src/global/mimetype.ts
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#6892 feat: 概览页支持调整应用显示
  agent/app/api/v2/dashboard.go
  agent/app/dto/common_req.go
  agent/app/dto/dashboard.go
  agent/app/service/dashboard.go
  agent/router/ro_dashboard.go
  agent/utils/common/common.go
  core/app/api/v2/app_launcher.go
  core/app/api/v2/entry.go
  core/app/model/app_launcher.go
  core/app/repo/app_launcher.go
  core/app/repo/common.go
  core/app/repo/setting.go
  core/app/service/app_launcher.go
  core/app/service/auth.go
  core/app/service/backup.go
  core/app/service/entry.go
  core/app/service/setting.go
  core/app/service/upgrade.go
  core/init/hook/hook.go
  core/init/migration/migrate.go
  core/init/migration/migrations/init.go
  core/middleware/bind_domain.go
  core/middleware/helper.go
  core/middleware/ip_limit.go
  core/middleware/loading.go
  core/middleware/password_expired.go
  core/middleware/session.go
  core/router/app_launcher.go
  core/router/common.go
  core/utils/jwt/jwt.go
  frontend/src/api/interface/dashboard.ts
  frontend/src/api/modules/dashboard.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/home/app/index.vue
  frontend/src/views/home/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#6894 fix: 解决全屏切换直接关闭后菜单不显示的问题
  frontend/src/layout/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#6893 fix: 解决远程数据库无法切换的问题
  frontend/src/views/database/mysql/index.vue
  frontend/src/views/database/postgresql/index.vue
  frontend/src/views/database/redis/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#6899 fix: 解决操作日志打印错误的问题
  backend/app/api/v1/dashboard.go
  backend/app/api/v1/runtime.go
  cmd/server/docs/docs.go
  cmd/server/docs/swagger.json
  cmd/server/docs/swagger.yaml
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#6897 feat: 缓存上次访问的路由菜单
  frontend/src/routers/index.ts
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#6905 fix: 解决清空网站日志时的闪烁问题
  frontend/src/views/log/website/index.vue
Labels: do-not-merge/release-note-label-needed

#6910 feat: 增加更新恶意IP组、蜘蛛IP池、IP地址库功能
  agent/cmd/server/conf/app.yaml
  agent/configs/system.go
  core/configs/system.go
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#6911 feat: 备份账号增加又拍云
  agent/app/service/backup.go
  agent/constant/backup.go
  agent/go.mod
  agent/go.sum
  agent/utils/cloud_storage/client/up.go
  agent/utils/cloud_storage/cloud_storage_client.go
  core/app/service/backup.go
  core/constant/common.go
  core/utils/cloud_storage/client/up.go
  core/utils/cloud_storage/cloud_storage_client.go
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/setting/backup-account/operate/index.vue
  go.mod
  go.sum
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2
