Repository 1Panel-dev/1Panel, pull requests merged in 2024-03, with the labels that each got.

#4016 feat: 增加防篡改功能
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/utils/shortcuts.ts
  frontend/src/views/cronjob/helper.ts
  frontend/src/views/cronjob/record/index.vue
  frontend/src/views/host/monitor/monitor/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4031 fix: 修改快照恢复逻辑
  backend/app/service/snapshot.go
  backend/app/service/snapshot_recover.go
  frontend/src/views/database/mysql/remote/delete/index.vue
  frontend/src/views/setting/snapshot/status/index.vue
Labels: do-not-merge/release-note-label-needed, dev

#4024 feat(waf): 修改攻击日志格式
  frontend/src/assets/json/name.json
  frontend/src/assets/json/world.json
  plugins/openresty/waf/conf/global.json
  plugins/openresty/waf/config.lua
  plugins/openresty/waf/db.lua
  plugins/openresty/waf/lib/action.lua
  plugins/openresty/waf/lib/lib.lua
  plugins/openresty/waf/lib/resty/uuid.lua
  plugins/openresty/waf/lib/utils.lua
  plugins/openresty/waf/log_and_traffic.lua
  plugins/openresty/waf/waf.lua
  plugins/openresty/waf/worker.lua
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4048 feat(waf)：增加请求日志统计
  plugins/openresty/waf/conf/waf.conf
  plugins/openresty/waf/db.lua
  plugins/openresty/waf/lib/action.lua
  plugins/openresty/waf/lib/utils.lua
  plugins/openresty/waf/log_and_traffic.lua
  plugins/openresty/waf/waf.lua
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4055 fix: 解决单位转换导致的内存限制问题
  backend/app/dto/container.go
  backend/app/service/container.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4058 feat: 同步本地应用增加 data.yml 正确性验证
  backend/app/service/app_utils.go
  backend/constant/errs.go
  backend/i18n/lang/en.yaml
  backend/i18n/lang/zh-Hant.yaml
  backend/i18n/lang/zh.yaml
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4059 pref: 优化 MySQL 备份恢复方式
  backend/app/service/backup_app.go
  backend/app/service/backup_mysql.go
  backend/app/service/cronjob_backup.go
  backend/utils/mysql/client/info.go
  backend/utils/mysql/client/remote.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4061 style: 修改主机记住密码显示标题
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4064 fix: 限制快照跨架构恢复
  backend/app/api/v1/dashboard.go
  backend/app/dto/dashboard.go
  backend/app/service/dashboard.go
  backend/app/service/snapshot.go
  cmd/server/docs/docs.go
  cmd/server/docs/swagger.json
  cmd/server/docs/swagger.yaml
  frontend/src/api/interface/dashboard.ts
  frontend/src/api/modules/dashboard.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/setting/snapshot/status/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4067 fix: 快照重试时忽略已成功步骤
  backend/app/service/snapshot.go
  backend/utils/cloud_storage/client/onedrive.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4068 fix: 快照前清空服务器地址
  backend/app/service/snapshot.go
  backend/app/service/snapshot_create.go
  backend/router/ro_dashboard.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4070 fix: 解决命令执行超时未生效的问题
  backend/app/service/dashboard.go
  backend/app/service/snapshot_recover.go
  backend/utils/cmd/cmd.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4071 feat: 本地应用同步增加校验
  backend/app/service/app_utils.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4080 fix: 优化计划任务脚本执行输出
  backend/app/api/v1/cronjob.go
  backend/app/service/cornjob.go
  backend/app/service/cronjob_helper.go
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/cronjob/record/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4082 fix: 解决网站日志查看报错的问题
  backend/utils/files/utils.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4086 fix: 快照重试后更新列表状态
  backend/app/service/snapshot.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4090 Issue 跳转 GitHub discussions
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/question.yml
Labels: do-not-merge/release-note-label-needed

#4102 fix: 修改升级过程中的架构判断
  backend/app/service/upgrade.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4092 feat: 升级 element-plus 到 2.6.0
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/file-list/index.vue
  frontend/src/components/router-button/index.vue
  frontend/src/components/status/index.vue
  frontend/src/components/system-upgrade/index.vue
  frontend/src/styles/common.scss
  frontend/src/views/app-store/apps/index.vue
  frontend/src/views/container/compose/create/index.vue
  frontend/src/views/container/container/index.vue
  frontend/src/views/container/container/operate/index.vue
  frontend/src/views/container/image/build/index.vue
  frontend/src/views/container/image/prune/index.vue
  frontend/src/views/container/repo/operator/index.vue
  frontend/src/views/container/setting/index.vue
  frontend/src/views/container/volume/create/index.vue
  frontend/src/views/cronjob/operate/index.vue
  frontend/src/views/database/mysql/index.vue
  frontend/src/views/database/mysql/remote/operate/index.vue
  frontend/src/views/database/postgresql/index.vue
  frontend/src/views/database/postgresql/remote/operate/index.vue
  frontend/src/views/database/redis/setting/persistence/index.vue
  frontend/src/views/home/index.vue
  frontend/src/views/host/file-management/create/index.vue
  frontend/src/views/host/file-management/move/index.vue
  frontend/src/views/host/firewall/ip/index.vue
  frontend/src/views/host/firewall/ip/operate/index.vue
  frontend/src/views/host/firewall/port/index.vue
  frontend/src/views/host/firewall/port/operate/index.vue
  frontend/src/views/host/process/process/index.vue
  frontend/src/views/host/ssh/log/log.vue
  frontend/src/views/host/ssh/ssh/index.vue
  frontend/src/views/host/terminal/command/index.vue
  frontend/src/views/host/terminal/host/index.vue
  frontend/src/views/host/terminal/host/operate/index.vue
  frontend/src/views/host/terminal/index.vue
  frontend/src/views/host/terminal/terminal/host-create.vue
  frontend/src/views/log/operation/index.vue
  frontend/src/views/log/system/index.vue
  frontend/src/views/log/website/index.vue
  frontend/src/views/setting/backup-account/onedrive/index.vue
  frontend/src/views/setting/panel/index.vue
  frontend/src/views/setting/safe/bind/index.vue
  frontend/src/views/setting/safe/ssl/index.vue
  frontend/src/views/toolbox/device/dns/index.vue
  frontend/src/views/toolbox/device/hosts/index.vue
  frontend/src/views/toolbox/fail2ban/index.vue
  frontend/src/views/website/runtime/node/operate/index.vue
  frontend/src/views/website/runtime/php/create/index.vue
  frontend/src/views/website/ssl/ca/detail/index.vue
  frontend/src/views/website/ssl/create/index.vue
  frontend/src/views/website/ssl/detail/index.vue
  frontend/src/views/website/ssl/obtain/index.vue
  frontend/src/views/website/website/create/index.vue
  frontend/src/views/website/website/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4093 fix: 解决编辑ssh端口同步到终端本地服务器问题 (#4043)
  backend/app/service/ssh.go
Labels: do-not-merge/release-note-label-needed, lgtm

#4109 feat: 增加一个外部访问地址校验规则
  frontend/src/global/form-rules.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/app-store/detail/params/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4121 feat: 升级 github.com/go-jose/go-jose/v3 版本到 v3.0.3
  backend/app/service/website_dns_account.go
  go.mod
  go.sum
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4126 feat: 升级 github.com/go-jose/go-jose/v3 版本到 v3.0.3
  go.mod
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4131 fix: 解决命令注入waf被绕过的问题
  backend/utils/cmd/cmd.go
Labels: do-not-merge/release-note-label-needed

#4128 feat: 增加界面设置功能
  frontend/src/hooks/use-logo.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/store/index.ts
  frontend/src/store/interface/index.ts
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4156 fix: 解决安装应用过程中出现的状态异常问题
  backend/app/service/app_install.go
  backend/constant/app.go
  backend/i18n/lang/en.yaml
  backend/i18n/lang/zh-Hant.yaml
  backend/i18n/lang/zh.yaml
  backend/utils/files/file_op.go
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/status/index.vue
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/styles/common.scss
  frontend/src/styles/element.scss
  frontend/src/views/container/container/index.vue
  frontend/src/views/cronjob/record/index.vue
  frontend/src/views/host/file-management/code-editor/index.vue
  frontend/src/views/log/login/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4162 chore: add pnpm-lock.yaml to .gitignore
  frontend/.gitignore
Labels: do-not-merge/release-note-label-needed

#4154 feat: 快照支持设置排除目录
  backend/app/dto/setting.go
  backend/app/service/snapshot_create.go
  backend/init/migration/migrate.go
  backend/init/migration/migrations/v_1_10.go
  frontend/src/api/interface/setting.ts
  frontend/src/components/file-list/index.vue
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/setting/snapshot/ignore-rule/index.vue
  frontend/src/views/setting/snapshot/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4166 feat(waf): 优化规则
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  plugins/openresty/waf/conf/global.json
  plugins/openresty/waf/config.lua
  plugins/openresty/waf/db.lua
  plugins/openresty/waf/init.lua
  plugins/openresty/waf/lib/action.lua
  plugins/openresty/waf/lib/lib.lua
  plugins/openresty/waf/lib/utils.lua
  plugins/openresty/waf/log_and_traffic.lua
  plugins/openresty/waf/rules/args.json
  plugins/openresty/waf/rules/cookie.json
  plugins/openresty/waf/rules/defaultUaBlack.json
  plugins/openresty/waf/rules/defaultUrlBlack.json
  plugins/openresty/waf/rules/header.json
  plugins/openresty/waf/rules/ipBlack.json
  plugins/openresty/waf/rules/ipBlackList
  plugins/openresty/waf/rules/methodWhite.json
  plugins/openresty/waf/rules/post.json
  plugins/openresty/waf/rules/uaBlack.json
  plugins/openresty/waf/rules/uaWhite.json
  plugins/openresty/waf/rules/urlBlack.json
  plugins/openresty/waf/rules/urlWhite.json
  plugins/openresty/waf/waf.lua
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4168 fix: 修复应用商店详情页面部分图标比例错误
  frontend/src/views/app-store/detail/index.vue
Labels: do-not-merge/release-note-label-needed

#4177 fix: 解决计划任务报告刷新异常的问题
  frontend/src/views/cronjob/record/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4176 fix: 升级依赖 google.golang.org/protobuf
  go.mod
  go.sum
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4182 Update README.md
  README.md
Labels: do-not-merge/release-note-label-needed

#4180 fix: 移除未使用依赖
  backend/init/db/db.go
  go.mod
  go.sum
Labels: do-not-merge/release-note-label-needed, dev

#4183 feat: 增加应用商店显示的过滤数量
  frontend/package-lock.json
  frontend/package.json
  frontend/src/assets/json/iso.json
  frontend/src/assets/json/world-name.json
  frontend/src/global/mimetype.ts
  frontend/src/styles/common.scss
  frontend/src/views/app-store/apps/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4185 feat: 同步数据库时标记已删除数据库
  backend/app/dto/database.go
  backend/app/dto/database_postgresql.go
  backend/app/model/database_mysql.go
  backend/app/model/database_postgresql.go
  backend/app/service/database_mysql.go
  backend/app/service/database_postgresql.go
  backend/init/migration/migrate.go
  backend/init/migration/migrations/v_1_10.go
  cmd/server/docs/docs.go
  cmd/server/docs/swagger.json
  cmd/server/docs/swagger.yaml
  frontend/src/api/interface/database.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/database/mysql/index.vue
  frontend/src/views/database/postgresql/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4187 fix: 解决计划任务列表备份账号显示问题
  frontend/src/views/cronjob/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4190 fix: 升级依赖 jackc/pgx/v5
  go.mod
  go.sum
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4193 fix: 移除计划任务报告中的 ANSI 转义
  frontend/src/views/container/container/log/index.vue
  frontend/src/views/cronjob/record/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4197 fix: 解决 Node 运行环境状态异常问题
  backend/app/api/v1/runtime.go
  backend/app/service/runtime.go
  backend/app/service/runtime_utils.go
  backend/router/ro_runtime.go
  frontend/src/api/modules/runtime.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/website/runtime/node/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4198 feat: 网站搜索增加网站关联域名匹配
  backend/app/repo/website.go
  backend/app/repo/website_domain.go
  backend/app/service/website.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4201 feat: 守护进程增加加载状态
  frontend/src/views/toolbox/supervisor/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4195 fix: 解决未登录情况下的页面跳转问题
  frontend/package-lock.json
  frontend/src/routers/index.ts
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4202 feat: 修改网站导入证书的描述
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4203 fix: 解决回收站文件放置错误问题
  backend/app/service/recycle_bin.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4204 feat: 增加 xpack Makefile
  Makefile
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4205 fix: 解决快照恢复时校验 daemon.json 路径失败的问题
  backend/app/service/snapshot_recover.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4210 feat(waf): 优化请求次数记录方式
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  plugins/openresty/waf/conf/global.json
  plugins/openresty/waf/config.lua
  plugins/openresty/waf/db.lua
  plugins/openresty/waf/lib/action.lua
  plugins/openresty/waf/lib/lib.lua
  plugins/openresty/waf/log_and_traffic.lua
  plugins/openresty/waf/rules/acl.json
  plugins/openresty/waf/rules/fileExt.json
  plugins/openresty/waf/rules/geoRestrict.json
  plugins/openresty/waf/waf.lua
  plugins/openresty/waf/worker.lua
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4221 style: 修改重启面板及服务器按钮位置
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/home/index.vue
  frontend/src/views/setting/snapshot/index.vue
  frontend/src/views/toolbox/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4224 feat(waf): 增加内部接口请求安全性
  plugins/openresty/waf/conf/siteConfig.json
  plugins/openresty/waf/config.lua
  plugins/openresty/waf/lib/action.lua
  plugins/openresty/waf/lib/file.lua
  plugins/openresty/waf/lib/lib.lua
  plugins/openresty/waf/lib/utils.lua
  plugins/openresty/waf/log_and_traffic.lua
  plugins/openresty/waf/rules/defaultUrlBlack.json
  plugins/openresty/waf/waf.lua
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4225 fix: 还原 Makefile 内容
  Makefile
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4226 feat(waf): 优化配置更新接口
  plugins/openresty/waf/conf/token
  plugins/openresty/waf/config.lua
  plugins/openresty/waf/lib/action.lua
  plugins/openresty/waf/lib/file.lua
  plugins/openresty/waf/log_and_traffic.lua
  plugins/openresty/waf/waf.lua
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4227 增加PHP模板
  backend/init/migration/migrations/v_1_9.go
Labels: do-not-merge/release-note-label-needed

#4229 feat: 修改应用已安装和可升级页面的标签选择
  frontend/src/views/app-store/installed/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4231 fix: 解决网站配置文件更新之后参数丢失的问题
  backend/utils/nginx/parser/parser.go
  frontend/src/views/app-store/installed/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4235 fix: 解决应用安装快速跳转失败的问题
  frontend/src/layout/components/AppMain.vue
  frontend/src/views/app-store/detail/params/index.vue
  frontend/src/views/website/website/create/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4236 fix: 解决应用安装快速跳转失败的问题
  frontend/src/layout/components/AppMain.vue
  frontend/src/views/app-store/detail/params/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4239 feat: 镜像拉取日志 Unicode 转义
  frontend/src/components/log-file/index.vue
  frontend/src/views/container/container/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4243 fix: 解决文件选择框关闭再打开依然选中的问题
  frontend/src/components/file-list/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4247 fix: 解决 i18n 导致页面错误的问题
  frontend/.gitignore
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/config-card/index.vue
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/utils/util.ts
  frontend/src/views/app-store/apps/index.vue
  frontend/src/views/app-store/detail/index.vue
  frontend/src/views/app-store/installed/detail/index.vue
  frontend/src/views/app-store/installed/index.vue
  frontend/src/views/home/app/index.vue
  frontend/src/views/website/runtime/php/edit/index.vue
  frontend/src/views/website/runtime/php/param/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4250 feat: 升级依赖 fit2cloud-ui-plus
  frontend/package.json
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4259 解决部分操作系统上 platformVersion 为空导致的显示问题
  frontend/src/views/home/index.vue
Labels: do-not-merge/release-note-label-needed

#4268 fix: 解决命令注入waf被绕过的问题
  backend/utils/cmd/cmd.go
Labels: do-not-merge/release-note-label-needed

#4273 ci: 替换过时的组件
  .github/workflows/add-labels-for-pr.yml
Labels: do-not-merge/release-note-label-needed

#4277 feat(waf): 增加 IP 组功能
  frontend/src/components/config-card/index.vue
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/styles/common.scss
  plugins/openresty/waf/conf/global.json
  plugins/openresty/waf/conf/waf.conf
  plugins/openresty/waf/config.lua
  plugins/openresty/waf/lib/action.lua
  plugins/openresty/waf/lib/cc.lua
  plugins/openresty/waf/lib/file.lua
  plugins/openresty/waf/lib/lib.lua
  plugins/openresty/waf/lib/resty/ipmatcher.lua
  plugins/openresty/waf/log_and_traffic.lua
  plugins/openresty/waf/rules/acl.json
  plugins/openresty/waf/rules/ipBlack.json
  plugins/openresty/waf/rules/ipWhite.json
  plugins/openresty/waf/rules/ip_group/test
  plugins/openresty/waf/waf.lua
  plugins/openresty/waf/worker.lua
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4288 feat(waf): 优化配置文件读取方式
  plugins/openresty/waf/config.lua
  plugins/openresty/waf/init.lua
  plugins/openresty/waf/lib/lib.lua
  plugins/openresty/waf/lib/resty/mlcache.lua
  plugins/openresty/waf/lib/resty/mlcache/ipc.lua
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4295 feat: 增加 License 导入界面
  backend/buserr/errors.go
  backend/constant/errs.go
  backend/i18n/lang/en.yaml
  backend/i18n/lang/zh-Hant.yaml
  backend/i18n/lang/zh.yaml
  frontend/src/api/index.ts
  frontend/src/api/interface/setting.ts
  frontend/src/api/modules/setting.ts
  frontend/src/components/system-upgrade/index.vue
  frontend/src/enums/http-enum.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/layout/index.vue
  frontend/src/routers/modules/setting.ts
  frontend/src/store/index.ts
  frontend/src/store/interface/index.ts
  frontend/src/views/home/index.vue
  frontend/src/views/setting/index.vue
  frontend/src/views/setting/license/index.vue
  frontend/src/views/setting/license/upload/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4297 feat: 完善 License 导入错误显示
  backend/constant/errs.go
  backend/i18n/lang/en.yaml
  backend/i18n/lang/zh-Hant.yaml
  backend/i18n/lang/zh.yaml
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4301 feat: 优化网站目录显示
  frontend/src/components/app-status/index.vue
  frontend/src/views/home/index.vue
  frontend/src/views/website/website/config/basic/site-folder/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4305 feat: 调整 License 导入样式
  frontend/src/components/system-upgrade/index.vue
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/home/index.vue
  frontend/src/views/home/license/index.vue
  frontend/src/views/setting/license/index.vue
  frontend/src/views/setting/license/upload/index.vue
Labels: do-not-merge/release-note-label-needed, dev

#4311 feat: 删除 plugins 目录
  plugins/openresty/waf/conf/global.json
  plugins/openresty/waf/conf/siteConfig.json
  plugins/openresty/waf/conf/token
  plugins/openresty/waf/conf/waf.conf
  plugins/openresty/waf/config.lua
  plugins/openresty/waf/db.lua
  plugins/openresty/waf/html/5s.html
  plugins/openresty/waf/html/5s.js
  plugins/openresty/waf/html/ip.html
  plugins/openresty/waf/html/redirect.html
  plugins/openresty/waf/html/slide.html
  plugins/openresty/waf/html/slide.js
  plugins/openresty/waf/init.lua
  plugins/openresty/waf/lib/action.lua
  plugins/openresty/waf/lib/cc.lua
  plugins/openresty/waf/lib/file.lua
  plugins/openresty/waf/lib/geoip.lua
  plugins/openresty/waf/lib/lib.lua
  plugins/openresty/waf/lib/logger.lua
  plugins/openresty/waf/lib/logger_factory.lua
  plugins/openresty/waf/lib/redis_util.lua
  plugins/openresty/waf/lib/resty/cookie.lua
  plugins/openresty/waf/lib/resty/ipmatcher.lua
  plugins/openresty/waf/lib/resty/libinjection.lua
  plugins/openresty/waf/lib/resty/maxminddb.lua
  plugins/openresty/waf/lib/resty/mlcache.lua
  plugins/openresty/waf/lib/resty/mlcache/ipc.lua
  plugins/openresty/waf/lib/resty/uuid.lua
  plugins/openresty/waf/lib/stringutf8.lua
  plugins/openresty/waf/lib/utils.lua
  plugins/openresty/waf/log_and_traffic.lua
  plugins/openresty/waf/rules/acl.json
  plugins/openresty/waf/rules/args.json
  plugins/openresty/waf/rules/ccurl.json
  plugins/openresty/waf/rules/cookie.json
  plugins/openresty/waf/rules/defaultUaBlack.json
  plugins/openresty/waf/rules/defaultUrlBlack.json
  plugins/openresty/waf/rules/fileExt.json
  plugins/openresty/waf/rules/geoRestrict.json
  plugins/openresty/waf/rules/header.json
  plugins/openresty/waf/rules/ipBlack.json
  plugins/openresty/waf/rules/ipWhite.json
  plugins/openresty/waf/rules/ip_group/test
  plugins/openresty/waf/rules/methodWhite.json
  plugins/openresty/waf/rules/post.json
  plugins/openresty/waf/rules/uaBlack.json
  plugins/openresty/waf/rules/uaWhite.json
  plugins/openresty/waf/rules/urlBlack.json
  plugins/openresty/waf/rules/urlWhite.json
  plugins/openresty/waf/test.lua
  plugins/openresty/waf/waf.json
  plugins/openresty/waf/waf.lua
  plugins/openresty/waf/worker.lua
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4315 chore: 去掉某些字体
  frontend/src/styles/common.scss
Labels: do-not-merge/release-note-label-needed

#4316 feat: 完善界面设置功能
  frontend/index.html
  frontend/src/assets/images/favicon.png
  frontend/src/hooks/use-logo.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/layout/components/Sidebar/components/Logo.vue
  frontend/src/layout/index.vue
  frontend/src/views/login/entrance/index.vue
  frontend/src/views/login/index.vue
  frontend/src/views/setting/about/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4317 fix: 修改 Xpack 路由路径
  frontend/src/routers/router.ts
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4322 feat: 删除 xpack 的翻译
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4323 style: 调整 Xpack 界面样式与菜单位置
  frontend/src/components/license-import/index.vue
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/routers/modules/setting.ts
  frontend/src/views/home/index.vue
  frontend/src/views/setting/license/index.vue
  frontend/src/views/setting/license/upload/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4325 chore: 增加 JetBrains Toolbox 图标
  .gitignore
  .idea/icon.png
Labels: do-not-merge/release-note-label-needed

#4327 feat: 删除旧版本 WAF 配置
  backend/app/api/v1/website.go
  backend/app/service/website.go
  backend/router/ro_website.go
  cmd/server/docs/docs.go
  cmd/server/docs/swagger.json
  cmd/server/docs/swagger.yaml
  cmd/server/nginx_conf/website_default.conf
  frontend/src/api/interface/website.ts
  frontend/src/api/modules/website.ts
  frontend/src/views/website/website/config/index.vue
  frontend/src/views/website/website/config/safety/ccdeny/index.vue
  frontend/src/views/website/website/config/safety/file-block-list/index.vue
  frontend/src/views/website/website/config/safety/index.vue
  frontend/src/views/website/website/config/safety/simple-list/index.vue
  frontend/src/views/website/website/config/safety/value-list/index.vue
  frontend/src/views/website/website/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4331 fix: 解决前端打包报错问题
  frontend/vite.config.ts
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4332 fix: 解决界面设置无法上传大图片的问题
  backend/init/router/router.go
  frontend/src/hooks/use-logo.ts
  frontend/src/layout/components/Sidebar/components/Logo.vue
  frontend/src/layout/index.vue
  frontend/src/views/setting/about/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4333 feat: 创建网站增加 waf 关联
  backend/app/dto/request/website.go
  backend/app/dto/response/website.go
  backend/app/service/website.go
  backend/app/service/website_utils.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4339 feat: 调整 waf 配置文件生成顺序
  backend/app/service/website.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4354 fix: 解决 WAF 首次安装创建网站没有生效的问题
  backend/app/service/website.go
  backend/app/service/website_utils.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4355 feat: 同步数据库中界面设置数据
  frontend/src/api/index.ts
  frontend/src/layout/components/MobileHeader.vue
  frontend/src/layout/components/Sidebar/components/Collapse.vue
  frontend/src/layout/components/Sidebar/index.vue
  frontend/src/layout/hooks/useResize.ts
  frontend/src/layout/index.vue
  frontend/src/store/index.ts
  frontend/src/store/interface/index.ts
  frontend/src/store/modules/auth.ts
  frontend/src/store/modules/global.ts
  frontend/src/store/modules/menu.ts
  frontend/src/views/login/components/login-form.vue
  frontend/src/views/setting/license/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#4357 style: 调整 Logo 样式
  frontend/src/components/license-import/index.vue
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/layout/components/Sidebar/components/Logo.vue
  frontend/src/layout/index.vue
  frontend/src/views/login/components/login-form.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved
