Repository 1Panel-dev/1Panel, pull requests merged in 2024-09, with the labels that each got.

#6313 fix:修复文件路径bug
  frontend/src/views/host/file-management/index.vue
Labels: do-not-merge/release-note-label-needed

#6337 fix: 修复域名删除导致网站访问被 WAF 拦截的问题
  backend/app/service/website.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#6338 feat: PHP 多网站使用一个 PHP 容器
  agent/app/dto/app.go
  agent/app/model/app.go
  agent/app/repo/app.go
  agent/app/service/app.go
  agent/app/service/app_utils.go
  agent/app/service/container.go
  agent/app/service/container_compose.go
  agent/app/service/runtime.go
  agent/app/service/runtime_utils.go
  agent/app/service/snapshot_recover.go
  agent/app/service/website.go
  agent/app/service/website_utils.go
  agent/constant/runtime.go
  agent/i18n/lang/en.yaml
  agent/i18n/lang/zh-Hant.yaml
  agent/i18n/lang/zh.yaml
  agent/init/business/business.go
  agent/init/migration/migrate.go
  agent/init/migration/migrations/init.go
  agent/server/server.go
  agent/utils/compose/compose.go
  agent/utils/files/file_op.go
  frontend/src/api/interface/app.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/app-store/detail/params/index.vue
  frontend/src/views/website/runtime/php/create/index.vue
  frontend/src/views/website/runtime/php/index.vue
  frontend/src/views/website/runtime/php/param/index.vue
  frontend/src/views/website/website/create/index.vue
  frontend/src/views/website/website/delete/index.vue
  frontend/src/views/website/website/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#6348 style:优化container在不同设备界面下的布局
  frontend/src/views/container/container/index.vue
Labels: do-not-merge/release-note-label-needed

#6352 feat: PHP 运行环境增加扩展管理
  agent/app/api/v2/runtime.go
  agent/app/dto/request/runtime.go
  agent/app/dto/response/runtime.go
  agent/app/model/runtime.go
  agent/app/service/runtime.go
  agent/cmd/server/nginx_conf/nginx_conf.go
  agent/cmd/server/nginx_conf/php_extensions.json
  agent/i18n/lang/en.yaml
  agent/i18n/lang/zh-Hant.yaml
  agent/i18n/lang/zh.yaml
  agent/init/migration/migrations/init.go
  agent/router/ro_runtime.go
  agent/utils/cmd/cmd.go
  frontend/src/api/interface/runtime.ts
  frontend/src/api/modules/runtime.ts
  frontend/src/components/task-log/index.vue
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/website/runtime/php/edit/index.vue
  frontend/src/views/website/runtime/php/extension-management/index.vue
  frontend/src/views/website/runtime/php/extension-template/index.vue
  frontend/src/views/website/runtime/php/extension-template/operate/index.vue
  frontend/src/views/website/runtime/php/index.vue
  frontend/src/views/website/runtime/php/param/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#6364 fix: 解决部分情况下缓存目录导致启动失败的问题
  backend/init/cache/cache.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#6370 fix: 解决停止状态容器端口获取不正确的问题
  backend/app/service/container.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#6360 fix:移动端网站页面和数据库页面样式
  frontend/src/components/app-status/index.vue
  frontend/src/views/database/mysql/index.vue
Labels: do-not-merge/release-note-label-needed

#6374 fix: 解决 FreshClam 操作失败的问题
  frontend/src/views/toolbox/clam/status/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#6376 fix: 解决备份恢复弹窗打开后无法关闭的问题
  frontend/src/components/backup/index.vue
  frontend/src/components/upload/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#6377 feat: PHP 运行环境增加操作
  agent/app/api/v2/runtime.go
  agent/app/dto/request/runtime.go
  agent/app/dto/response/runtime.go
  agent/app/service/runtime.go
  agent/app/service/runtime_utils.go
  agent/cmd/server/nginx_conf/php_extensions.json
  agent/router/ro_runtime.go
  frontend/src/api/interface/runtime.ts
  frontend/src/api/modules/runtime.ts
  frontend/src/components/log-dialog/index.vue
  frontend/src/components/log-file/index.vue
  frontend/src/components/task-log/index.vue
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/website/runtime/php/create/index.vue
  frontend/src/views/website/runtime/php/extension-management/index.vue
  frontend/src/views/website/runtime/php/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#6380 fix: 概览页获取 CPU 精度问题
  backend/app/service/dashboard.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#6379 refactor: 调整主机监控任务时间为整分钟执行
  backend/app/service/monitor.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#6382 fix: 解决部分情况下缓存目录导致启动失败的问题
  backend/init/cache/cache.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#6381 fix: 备份账号 bucket 支持手动输入
  frontend/src/api/interface/backup.ts
  frontend/src/views/setting/backup-account/cos/index.vue
  frontend/src/views/setting/backup-account/kodo/index.vue
  frontend/src/views/setting/backup-account/minio/index.vue
  frontend/src/views/setting/backup-account/oss/index.vue
  frontend/src/views/setting/backup-account/s3/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#6384 feat: PHP 运行环境增加配置修改
  agent/app/api/v2/runtime.go
  agent/app/api/v2/website.go
  agent/app/dto/request/runtime.go
  agent/app/dto/request/website.go
  agent/app/service/runtime.go
  agent/app/service/website.go
  agent/router/ro_runtime.go
  agent/router/ro_website.go
  frontend/src/api/interface/runtime.ts
  frontend/src/api/interface/website.ts
  frontend/src/api/modules/runtime.ts
  frontend/src/api/modules/website.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/routers/modules/website.ts
  frontend/src/views/website/runtime/php/config/config/index.vue
  frontend/src/views/website/runtime/php/config/function/index.vue
  frontend/src/views/website/runtime/php/config/index.vue
  frontend/src/views/website/runtime/php/config/php-fpm/index.vue
  frontend/src/views/website/runtime/php/config/upload/index.vue
  frontend/src/views/website/runtime/php/index.vue
  frontend/src/views/website/website/config/php/index.vue
  frontend/src/views/website/website/config/php/version/index.vue
  frontend/src/views/website/website/config/resource/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#6386 style:移动端文件页面样式和防火墙页面样式
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/database/mysql/index.vue
  frontend/src/views/host/file-management/index.vue
  frontend/src/views/host/firewall/status/index.vue
  frontend/src/views/website/ssl/index.vue
Labels: do-not-merge/release-note-label-needed

#6387 style:更新所有移动端container路径下样式
  frontend/src/views/container/compose/index.vue
  frontend/src/views/container/image/index.vue
  frontend/src/views/container/index.vue
  frontend/src/views/container/network/index.vue
  frontend/src/views/container/repo/index.vue
  frontend/src/views/container/setting/index.vue
  frontend/src/views/container/template/index.vue
  frontend/src/views/container/volume/index.vue
Labels: do-not-merge/release-note-label-needed

#6393 perf: 优化文件管理器终端命令
  frontend/src/views/host/terminal/terminal/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#6400 fix: 解决软连接被识别为文件问题
  backend/utils/files/fileinfo.go
  frontend/src/api/interface/file.ts
  frontend/src/views/host/file-management/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#6401 feat: 优化 PHP 运行环境扩展安装
  agent/app/service/runtime.go
  agent/app/service/runtime_utils.go
  agent/app/task/task.go
  agent/cmd/server/nginx_conf/php_extensions.json
  agent/i18n/lang/en.yaml
  agent/i18n/lang/zh-Hant.yaml
  agent/i18n/lang/zh.yaml
  frontend/src/views/website/runtime/php/extension-management/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#6404 fix: 创建CA机构生成的应为证书而非证书签名请求
  backend/app/service/website_ca.go
  frontend/src/views/website/ssl/ca/detail/index.vue
Labels: do-not-merge/release-note-label-needed

#6415 feat: 防火墙操作支持 ipv6 网段
  frontend/src/utils/util.ts
  frontend/src/views/host/firewall/forward/operate/index.vue
  frontend/src/views/host/firewall/ip/operate/index.vue
  frontend/src/views/host/firewall/port/operate/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#6417 fix: 解决容器端口的显示问题
  backend/app/service/container.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#6420 feat: PHP 增加性能调整配置
  agent/app/api/v2/runtime.go
  agent/app/dto/request/runtime.go
  agent/app/model/runtime.go
  agent/app/service/runtime.go
  agent/router/ro_runtime.go
  frontend/src/api/interface/runtime.ts
  frontend/src/api/modules/runtime.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/website/runtime/php/config/config/index.vue
  frontend/src/views/website/runtime/php/config/index.vue
  frontend/src/views/website/runtime/php/config/performance/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#6423 fix: 解决文件编辑器行号问题
  frontend/package.json
  frontend/src/views/host/file-management/code-editor/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#6424 fix: 解决服务器重启按钮被遮住的样式问题
  frontend/src/styles/common.scss
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#6425 fix: 限制二进制文件解压的类型
  frontend/src/views/host/file-management/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#6428 fix: 主机文件的路径栏路径 Bug 解决
  backend/app/service/file.go
  frontend/src/views/host/file-management/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#6431 perf: 优化工具栏样式
  frontend/src/components/layout-content/index.vue
  frontend/src/styles/common.scss
  frontend/src/views/app-store/index.scss
  frontend/src/views/container/container/index.vue
  frontend/src/views/container/image/index.vue
  frontend/src/views/container/network/index.vue
  frontend/src/views/container/template/index.vue
  frontend/src/views/container/volume/index.vue
  frontend/src/views/cronjob/index.vue
  frontend/src/views/database/mysql/index.vue
  frontend/src/views/database/mysql/remote/index.vue
  frontend/src/views/database/postgresql/index.vue
  frontend/src/views/database/postgresql/remote/index.vue
  frontend/src/views/host/firewall/forward/index.vue
  frontend/src/views/host/firewall/ip/index.vue
  frontend/src/views/host/firewall/port/index.vue
  frontend/src/views/host/process/network/index.vue
  frontend/src/views/host/process/process/index.vue
  frontend/src/views/host/ssh/log/log.vue
  frontend/src/views/host/ssh/session/index.vue
  frontend/src/views/log/operation/index.vue
  frontend/src/views/log/website/index.vue
  frontend/src/views/setting/snapshot/index.vue
  frontend/src/views/website/runtime/go/index.vue
  frontend/src/views/website/runtime/java/index.vue
  frontend/src/views/website/runtime/node/index.vue
  frontend/src/views/website/runtime/php/index.vue
  frontend/src/views/website/ssl/index.vue
  frontend/src/views/website/website/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#6432 fix: 主机文件打开软链接优化
  backend/utils/files/fileinfo.go
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#6433 fix: 处理代码格式问题
  frontend/src/views/database/mysql/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#6435 feat: 增加 Intel Arc 显卡 适配
  backend/app/dto/dashboard.go
  backend/app/service/dashboard.go
  backend/utils/xpack/xpack.go
  frontend/src/api/interface/dashboard.ts
  frontend/src/views/home/index.vue
  frontend/src/views/home/status/index.vue
Labels: do-not-merge/release-note-label-needed, dev

#6437 fix: 主机文件解压文件 mimetype 类型增加
  frontend/src/utils/util.ts
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#6440 fix: 修改移动端样式
  backend/app/service/dashboard.go
  frontend/src/styles/common.scss
  frontend/src/views/container/compose/index.vue
  frontend/src/views/container/index.vue
  frontend/src/views/container/repo/index.vue
  frontend/src/views/database/mysql/remote/index.vue
  frontend/src/views/database/postgresql/remote/index.vue
  frontend/src/views/database/redis/index.vue
  frontend/src/views/database/redis/remote/index.vue
  frontend/src/views/host/terminal/command/index.vue
  frontend/src/views/host/terminal/host/index.vue
  frontend/src/views/log/login/index.vue
  frontend/src/views/toolbox/ftp/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#6441 style:优化日志审计页面样式
  frontend/src/styles/common.scss
  frontend/src/views/host/file-management/index.vue
  frontend/src/views/log/operation/index.vue
  frontend/src/views/log/system/index.vue
  frontend/src/views/log/website/index.vue
Labels: do-not-merge/release-note-label-needed

#6443 style:优化设置移动端界面
  frontend/src/views/setting/backup-account/index.vue
  frontend/src/views/setting/panel/index.vue
  frontend/src/views/setting/safe/index.vue
Labels: do-not-merge/release-note-label-needed

#6445 fix: 移除重复样式
  frontend/src/styles/common.scss
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#6446 feat: 日志页面增加加载状态
  frontend/src/components/log-file/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#6448 style: 优化移动端样式
  frontend/src/components/app-status/index.vue
  frontend/src/views/container/setting/index.vue
  frontend/src/views/cronjob/record/index.vue
  frontend/src/views/database/mysql/index.vue
  frontend/src/views/database/postgresql/index.vue
  frontend/src/views/database/redis/index.vue
  frontend/src/views/host/firewall/status/index.vue
  frontend/src/views/host/ssh/ssh/index.vue
  frontend/src/views/log/system/index.vue
  frontend/src/views/toolbox/clam/status/index.vue
  frontend/src/views/toolbox/fail2ban/index.vue
  frontend/src/views/toolbox/ftp/index.vue
  frontend/src/views/toolbox/supervisor/status/index.vue
  frontend/src/views/website/website/status/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#6450 feat: 优化概览页内存单位
  frontend/src/views/home/status/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#6452 feat: 增加静态网站和 PHP 运行环境网站互相切换功能
  agent/app/dto/request/website.go
  agent/app/dto/response/website.go
  agent/app/service/website.go
  agent/router/ro_website.go
  frontend/src/api/interface/website.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/website/website/config/basic/index.vue
  frontend/src/views/website/website/config/basic/other/index.vue
  frontend/src/views/website/website/config/basic/php/index.vue
  frontend/src/views/website/website/config/index.vue
  frontend/src/views/website/website/config/resource/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#6451 fix: 解决主机文件压缩解压特殊字符问题
  backend/utils/files/file_op.go
  backend/utils/files/tar.go
  backend/utils/files/tar_gz.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#6463 feat: 删除多余代码
  frontend/src/views/home/index.vue
Labels: do-not-merge/release-note-label-needed, dev

#6447 fix: 删除容器后 compose 记录保存以便后续处理
  backend/app/dto/container.go
  backend/app/model/compose_template.go
  backend/app/repo/compose_template.go
  backend/app/service/container.go
  backend/app/service/container_compose.go
  backend/init/migration/migrate.go
  backend/init/migration/migrations/v_1_10.go
  frontend/src/views/container/compose/detail/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#6473 feat: 网站增加反代缓存配置
  agent/app/api/v2/website.go
  agent/app/dto/request/nginx.go
  agent/app/dto/response/nginx.go
  agent/app/service/website.go
  agent/app/service/website_utils.go
  agent/router/ro_website.go
  agent/utils/nginx/components/location.go
  frontend/src/api/interface/website.ts
  frontend/src/api/modules/website.ts
  frontend/src/global/mimetype.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/website/website/config/basic/proxy/cache/index.vue
  frontend/src/views/website/website/config/basic/proxy/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#6407 feat(ssl证书): 实现华为云dns
  backend/utils/ssl/client.go
  backend/utils/ssl/huaweicloud/huaweicloud.go
  backend/utils/ssl/huaweicloud/huaweicloud.toml
  backend/utils/ssl/huaweicloud/huaweicloud_test.go
  go.mod
  go.sum
Labels: do-not-merge/release-note-label-needed

#6491 style:优化概览界面的布局
  frontend/src/components/error-message/error_code.vue
  frontend/src/components/router-button/index.vue
  frontend/src/views/home/index.vue
Labels: do-not-merge/release-note-label-needed

#6497 feat: 优化 nginx 编辑器代码高亮
  frontend/src/components/codemirror-pro/index.vue
  frontend/src/components/codemirror-pro/nginx.ts
  frontend/src/views/website/website/config/basic/auth-basic/create/index.vue
  frontend/src/views/website/website/config/basic/redirect/create/index.vue
Labels: do-not-merge/release-note-label-needed, dev-v2

#6498 feat: demo 环境增加首页状态接口过滤
  backend/middleware/demo_handle.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#6501 feat: 网站支持启动 http3
  agent/app/dto/request/website.go
  agent/app/dto/response/website.go
  agent/app/service/website.go
  agent/app/service/website_utils.go
  agent/utils/nginx/components/server.go
  frontend/src/api/interface/website.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/website/website/config/basic/https/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#6510 fix: 调整Logo长宽比，防止显示被拉伸
  cmd/server/web/favicon.png
  frontend/public/favicon.png
  frontend/src/assets/images/favicon.png
Labels: do-not-merge/release-note-label-needed

#6503 fix: 创建和编辑 compose 文件支持设置环境变量
  backend/app/dto/container.go
  backend/app/service/container_compose.go
  frontend/src/api/interface/container.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/container/compose/create/index.vue
  frontend/src/views/container/compose/edit/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#6533 fix: 解决图片/视频预览时，重命名文件名导致浏览器缓存文件内容问题
  frontend/src/views/host/file-management/preview/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#6538 feat: openresty 异常状态下支持修改配置文件
  agent/app/service/nginx.go
  agent/app/service/runtime_utils.go
  agent/app/service/website.go
  agent/utils/compose/compose.go
  frontend/src/components/app-status/index.vue
  frontend/src/routers/modules/website.ts
  frontend/src/views/website/website/nginx/index.vue
  frontend/src/views/website/website/nginx/source/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#6534 feat: 容器编排显示容器状态，编排模板样式优化
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/container/compose/index.vue
  frontend/src/views/container/template/detail/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#6543 feat: OpenResty 支持新增扩展
  agent/app/api/v2/nginx.go
  agent/app/dto/request/nginx.go
  agent/app/dto/response/nginx.go
  agent/app/service/nginx.go
  agent/app/task/task.go
  agent/i18n/lang/en.yaml
  agent/i18n/lang/zh-Hant.yaml
  agent/i18n/lang/zh.yaml
  agent/router/ro_nginx.go
  frontend/src/api/interface/nginx.ts
  frontend/src/api/modules/nginx.ts
  frontend/src/components/task-log/index.vue
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/log/task/index.vue
  frontend/src/views/website/website/index.vue
  frontend/src/views/website/website/nginx/index.vue
  frontend/src/views/website/website/nginx/module/index.vue
  frontend/src/views/website/website/nginx/module/operate/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#6553 fix: 解决服务包含 .socket 时起停失败的问题
  backend/app/service/docker.go
  backend/app/service/ssh.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#6551 fix: 编排模板列表日期格式化
  frontend/src/views/container/template/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#6555 fix: 添加国际化及样式修改
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/container/compose/delete/index.vue
  frontend/src/views/container/compose/index.vue
  frontend/src/views/host/file-management/index.vue
  frontend/src/views/website/runtime/go/index.vue
  frontend/src/views/website/runtime/java/index.vue
  frontend/src/views/website/runtime/node/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#6556 feat: OpenResty 增加默认扩展
  agent/app/dto/nginx.go
  agent/app/dto/request/nginx.go
  agent/app/dto/response/nginx.go
  agent/app/service/nginx.go
  frontend/src/api/interface/nginx.ts
  frontend/src/api/modules/nginx.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/website/website/nginx/module/build/index.vue
  frontend/src/views/website/website/nginx/module/index.vue
  frontend/src/views/website/website/nginx/module/operate/index.vue
Labels: do-not-merge/release-note-label-needed, dev-v2

#6564 flx: 修复会默认出现水平滚动条的问题
  frontend/src/components/router-button/index.vue
Labels: do-not-merge/release-note-label-needed

#6566 feat: 容器编排及模板列表支持排序
  frontend/src/views/container/compose/index.vue
  frontend/src/views/container/template/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm

#6559 feat: 容器日志下载只支持全量下载
  frontend/src/views/container/container/log/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#6565 feat: 容器编排列表增加编排目录并支持跳转
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/container/compose/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#6580 feat: PHP 运行环境增加进程守护管理
  agent/app/api/v2/runtime.go
  agent/app/dto/request/host_tool.go
  agent/app/dto/request/runtime.go
  agent/app/service/host_tool.go
  agent/app/service/runtime.go
  agent/app/service/website.go
  agent/router/ro_runtime.go
  frontend/src/api/interface/runtime.ts
  frontend/src/api/modules/runtime.ts
  frontend/src/components/drawer-pro/index.vue
  frontend/src/views/website/runtime/php/index.vue
  frontend/src/views/website/runtime/php/supervisor/create/index.vue
  frontend/src/views/website/runtime/php/supervisor/file/index.vue
  frontend/src/views/website/runtime/php/supervisor/index.vue
  frontend/src/views/website/website/config/basic/index.vue
  frontend/src/views/website/website/nginx/module/build/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#6583 feat: 优化快照功能
  agent/app/api/v2/snapshot.go
  agent/app/dto/setting.go
  agent/app/dto/snapshot.go
  agent/app/model/snapshot.go
  agent/app/repo/snapshot.go
  agent/app/repo/task.go
  agent/app/service/container_compose.go
  agent/app/service/container_network.go
  agent/app/service/cronjob_backup.go
  agent/app/service/cronjob_helper.go
  agent/app/service/snapshot.go
  agent/app/service/snapshot_create.go
  agent/app/service/snapshot_recover.go
  agent/app/service/snapshot_rollback.go
  agent/app/task/task.go
  agent/i18n/lang/en.yaml
  agent/i18n/lang/zh-Hant.yaml
  agent/i18n/lang/zh.yaml
  agent/init/hook/hook.go
  agent/init/migration/migrate.go
  agent/init/migration/migrations/init.go
  agent/router/ro_setting.go
  agent/utils/files/file_op.go
  agent/utils/files/tar_gz.go
  frontend/package.json
  frontend/src/api/interface/setting.ts
  frontend/src/api/modules/backup.ts
  frontend/src/api/modules/setting.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/log/task/index.vue
  frontend/src/views/setting/snapshot/create/index.vue
  frontend/src/views/setting/snapshot/ignore-rule/index.vue
  frontend/src/views/setting/snapshot/import/index.vue
  frontend/src/views/setting/snapshot/index.vue
  frontend/src/views/setting/snapshot/recover/index.vue
  frontend/src/views/setting/snapshot/snap_status/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#6592 feat: 网站增加切换数据库功能
  agent/app/api/v2/website.go
  agent/app/dto/request/website.go
  agent/app/dto/response/website.go
  agent/app/service/website.go
  agent/router/ro_website.go
  agent/utils/docker/compose.go
  frontend/src/api/interface/website.ts
  frontend/src/api/modules/website.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/website/website/config/basic/anti-Leech/index.vue
  frontend/src/views/website/website/config/basic/index.vue
  frontend/src/views/website/website/config/basic/limit-conn/index.vue
  frontend/src/views/website/website/config/basic/other/index.vue
  frontend/src/views/website/website/config/basic/php/index.vue
  frontend/src/views/website/website/config/basic/resource/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#6594 feat: 增加容器状态统计及状态快速切换
  agent/app/api/v2/container.go
  agent/app/dto/container.go
  agent/app/service/container.go
  agent/router/ro_container.go
  frontend/src/api/interface/container.ts
  frontend/src/api/modules/container.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/routers/modules/container.ts
  frontend/src/views/container/container/index.vue
  frontend/src/views/container/container/operate/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#6593 feat: 优化日志加载
  frontend/src/components/log-file/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#6598 feat: 镜像拉取、推送、构建改为任务方式实现
  agent/app/api/v2/container.go
  agent/app/api/v2/image.go
  agent/app/dto/container.go
  agent/app/dto/image.go
  agent/app/service/container.go
  agent/app/service/container_compose.go
  agent/app/service/device_clean.go
  agent/app/service/file.go
  agent/app/service/image.go
  agent/app/task/task.go
  agent/i18n/lang/en.yaml
  agent/i18n/lang/zh-Hant.yaml
  agent/i18n/lang/zh.yaml
  frontend/src/api/interface/container.ts
  frontend/src/views/container/compose/create/index.vue
  frontend/src/views/container/image/build/index.vue
  frontend/src/views/container/image/pull/index.vue
  frontend/src/views/container/image/push/index.vue
Labels: do-not-merge/release-note-label-needed, dev-v2

#6599 feat: 容器列表缓存是否显示应用商店容器
  frontend/src/views/container/container/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#6603 feat: 网站备份/恢复增加任务日志
  agent/app/dto/backup.go
  agent/app/repo/backup.go
  agent/app/service/backup_app.go
  agent/app/service/backup_website.go
  agent/app/service/cronjob_backup.go
  agent/app/service/website.go
  agent/app/service/website_utils.go
  agent/app/task/task.go
  agent/cmd/server/nginx_conf/php_extensions.json
  agent/i18n/lang/en.yaml
  agent/i18n/lang/zh-Hant.yaml
  agent/i18n/lang/zh.yaml
  frontend/src/api/interface/backup.ts
  frontend/src/api/interface/website.ts
  frontend/src/components/backup/index.vue
  frontend/src/views/website/website/config/basic/index.vue
  frontend/src/views/website/website/config/basic/resource/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#6600 fix: 重构容器编排环境变量设置逻辑
  backend/app/dto/container.go
  backend/app/service/container_compose.go
  frontend/src/api/interface/container.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/container/compose/create/index.vue
  frontend/src/views/container/compose/edit/index.vue
  frontend/src/views/container/compose/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#6605 feat: Compose 环境变量编辑增加是否 1Panel 创建校验
  frontend/src/views/container/compose/edit/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#6610 feat: 调整编排删除逻辑
  backend/app/dto/container.go
  backend/app/service/container_compose.go
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/container/compose/delete/index.vue
  frontend/src/views/container/compose/detail/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#6611 feat: 新增 BookStack 的 PHP 扩展模板
  backend/init/migration/migrations/v_1_9.go
Labels: do-not-merge/release-note-label-needed

#6613 feat: 移除编排删除后跳转
  backend/app/service/container_compose.go
  frontend/src/views/container/compose/detail/index.vue
  frontend/src/views/container/compose/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#6614 feat: 增加容器概览页面
  agent/app/dto/container.go
  agent/app/service/container.go
  frontend/src/api/interface/container.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/routers/modules/container.ts
  frontend/src/views/container/dashboard/index.vue
  frontend/src/views/container/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#6616 style: 修改许可证即将过期样式
  frontend/src/api/interface/setting.ts
  frontend/src/store/interface/index.ts
  frontend/src/store/modules/global.ts
  frontend/src/utils/xpack.ts
  frontend/src/views/setting/license/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#6618 feat: 备份运行环境/静态网站时支持同步备份数据库
  agent/app/service/backup_app.go
  agent/app/service/backup_website.go
  agent/i18n/lang/en.yaml
  agent/i18n/lang/zh-Hant.yaml
  agent/i18n/lang/zh.yaml
  frontend/src/components/backup/index.vue
Labels: do-not-merge/release-note-label-needed, dev-v2

#6619 feat: 备份恢复应用增加任务日志
  agent/app/service/backup_app.go
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#6627 feat: 自签证书支持 ipv6
  backend/app/service/website_ca.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved
