Repository 1Panel-dev/1Panel, pull requests merged in 2025-02, with the labels that each got.

#7800 feat: Updated partial translations
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/utils/util.ts
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#7801 feat: fix anti-leech is not work on proxy website
  backend/app/service/website.go
  frontend/src/utils/util.ts
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#7791 fix(firewall): 删除复杂转发规则报错
  backend/utils/firewall/client/iptables.go
Labels: do-not-merge/release-note-label-needed

#7802 feat: Updated partial translations
  agent/app/service/app.go
  agent/app/service/runtime.go
  agent/app/service/website.go
  agent/go.mod
  agent/go.sum
  agent/utils/ssl/client.go
  frontend/src/components/group/index.vue
  frontend/src/global/mimetype.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/app-store/apps/index.vue
  frontend/src/views/host/file-management/index.vue
  frontend/src/views/website/runtime/dotnet/index.vue
  frontend/src/views/website/runtime/go/index.vue
  frontend/src/views/website/runtime/java/index.vue
  frontend/src/views/website/runtime/node/index.vue
  frontend/src/views/website/runtime/node/module/index.vue
  frontend/src/views/website/runtime/php/create/index.vue
  frontend/src/views/website/runtime/php/index.vue
  frontend/src/views/website/runtime/python/index.vue
  frontend/src/views/website/ssl/dns-account/create/index.vue
  frontend/src/views/website/website/config/basic/other/index.vue
  frontend/src/views/website/website/create/index.vue
  frontend/src/views/website/website/index.vue
Labels: do-not-merge/release-note-label-needed, dev-v2

#7803 fix: fix some internationalization formats
  backend/i18n/lang/zh.yaml
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#7805 feat: Running environment website adapts to multiple ports
  agent/app/service/website.go
  agent/app/service/website_utils.go
  frontend/src/api/interface/runtime.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/utils/util.ts
  frontend/src/views/website/website/create/index.vue
  frontend/src/views/website/website/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, dev-v2

#7811 style: Optimize the styles of dashboard, container, and other pages
  frontend/src/assets/iconfont/iconfont.css
  frontend/src/assets/iconfont/iconfont.js
  frontend/src/assets/iconfont/iconfont.json
  frontend/src/assets/iconfont/iconfont.svg
  frontend/src/assets/iconfont/iconfont.ttf
  frontend/src/assets/iconfont/iconfont.woff
  frontend/src/assets/iconfont/iconfont.woff2
  frontend/src/components/card-with-header/index.vue
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/routers/modules/terminal.ts
  frontend/src/routers/modules/toolbox.ts
  frontend/src/views/container/compose/detail/index.vue
  frontend/src/views/container/container/command/index.vue
  frontend/src/views/container/container/index.vue
  frontend/src/views/container/container/operate/index.vue
  frontend/src/views/container/dashboard/index.vue
  frontend/src/views/home/app/index.vue
  frontend/src/views/host/file-management/index.vue
  frontend/src/views/toolbox/supervisor/file/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#7815 feat: Update Login Page
  core/app/api/v2/auth.go
  core/app/api/v2/helper/helper.go
  core/app/repo/setting.go
  core/app/service/auth.go
  core/utils/captcha/captcha.go
  frontend/src/components/drawer-pro/index.vue
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/app-store/installed/index.vue
  frontend/src/views/home/app/index.vue
  frontend/src/views/login/components/login-form.vue
  frontend/src/views/login/index.vue
  frontend/src/views/setting/safe/mfa/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#7818 feat: The appstore has added support for the Korean language
  backend/app/dto/app.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#7822 fix: Remove some comments.
  frontend/.editorconfig
  frontend/.env
  frontend/.env.development
  frontend/.env.production
  frontend/.eslintrc.js
  frontend/.prettierrc.js
  frontend/.stylelintrc.js
  frontend/package.json
  frontend/tsconfig.json
  frontend/vite-env.d.ts
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#7824 feat: Modify some translations.
  core/i18n/lang/en.yaml
  core/i18n/lang/fa.yaml
  core/i18n/lang/ja.yaml
  core/i18n/lang/ko.yaml
  core/i18n/lang/ms.yml
  core/i18n/lang/pt-BR.yaml
  core/i18n/lang/pt.yaml
  core/i18n/lang/ru.yaml
  core/i18n/lang/zh-Hant.yaml
  core/i18n/lang/zh.yaml
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/host/process/process/detail/index.vue
  frontend/src/views/website/website/check/index.vue
  frontend/src/views/website/website/config/basic/php/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#7825 feat(system): Password encryption for login API.
  core/app/service/auth.go
  core/app/service/setting.go
  core/init/hook/hook.go
  core/init/router/router.go
  core/middleware/password_rsa.go
  core/utils/encrypt/encrypt.go
  frontend/package.json
  frontend/src/utils/util.ts
  frontend/src/views/login/components/login-form.vue
  frontend/src/views/login/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#7823 feat: Add function backups by default for MySQL and MariaDB databases.
  backend/utils/mysql/client/local.go
  backend/utils/mysql/client/remote.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm

#7827 fix: fix the issue of abnormal display of backup account size
  agent/app/service/backup_record.go
  agent/app/service/snapshot_create.go
  core/utils/cloud_storage/client/local.go
  core/utils/cloud_storage/cloud_storage_client.go
  frontend/src/views/cronjob/operate/index.vue
  frontend/src/views/host/file-management/index.vue
  frontend/src/views/host/file-management/upload/index.vue
  frontend/src/views/host/process/process/detail/index.vue
  frontend/src/views/setting/snapshot/create/index.vue
  frontend/src/views/toolbox/ftp/log/index.vue
Labels: do-not-merge/release-note-label-needed, dev-v2

#7828 feat(system): Optimize the logic of the login page
  core/app/api/v2/app_launcher.go
  core/app/api/v2/auth.go
  core/app/api/v2/backup.go
  core/app/dto/auth.go
  core/app/service/auth.go
  core/app/service/setting.go
  core/cmd/server/docs/docs.go
  core/cmd/server/docs/swagger.json
  core/cmd/server/docs/swagger_test.go
  core/cmd/server/docs/x-log.json
  core/router/ro_base.go
  frontend/src/api/interface/auth.ts
  frontend/src/api/modules/auth.ts
  frontend/src/layout/components/Sidebar/index.vue
  frontend/src/views/login/components/login-form.vue
  frontend/src/views/login/index.vue
Labels: do-not-merge/release-note-label-needed, dev-v2

#7830 feat: Update zh-Hant translation
  backend/i18n/lang/zh-Hant.yaml
  frontend/src/lang/modules/tw.ts
Labels: do-not-merge/release-note-label-needed

#7834 fix: Fixed the issue where application labels were not displayed afte…
  backend/app/service/app.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm

#7838 feat: support adding license modification feature
  frontend/src/api/modules/setting.ts
  frontend/src/components/group/index.vue
  frontend/src/components/license-import/index.vue
  frontend/src/views/setting/license/bind/index.vue
  frontend/src/views/setting/license/delete/index.vue
  frontend/src/views/setting/license/index.vue
Labels: do-not-merge/release-note-label-needed, dev-v2

#7840 feat(website): Manually request certificates using a custom nameserver.
  agent/app/service/website_ssl.go
  agent/utils/ssl/client.go
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/styles/common.scss
  frontend/src/views/app-store/index.scss
  frontend/src/views/app-store/installed/index.vue
  frontend/src/views/website/website/config/basic/redirect/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, dev-v2

#7852 feat(system): Modify the login page style
  core/cmd/server/conf/app.yaml
  frontend/src/assets/images/1panel-login-bg.jpg
  frontend/src/assets/images/1panel-login-bg.png
  frontend/src/assets/images/1panel-login.jpg
  frontend/src/assets/images/1panel-login.png
  frontend/src/views/login/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#7854 fix: Fix the security entry verification error issue.
  backend/app/api/v1/setting.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#7855 feat: Improve the name of the professional version
  frontend/src/api/interface/setting.ts
  frontend/src/components/system-upgrade/index.vue
  frontend/src/components/system-upgrade/upgrade/index.vue
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/setting/about/index.vue
  frontend/src/views/setting/license/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#7857 feat(docker): The default network of 1panel-network supports IPv6.
  agent/utils/docker/docker.go
  frontend/src/utils/util.ts
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#7858 style: Optimize app store style and layout
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/views/app-store/index.scss
  frontend/src/views/app-store/installed/index.vue
Labels: do-not-merge/release-note-label-needed, dev

#7865 feat: Adding GPU acceleration configuration to some applications
  backend/app/dto/app.go
  backend/app/dto/request/app.go
  backend/app/dto/response/app.go
  backend/app/model/app.go
  backend/app/service/app.go
  backend/app/service/app_utils.go
  backend/init/migration/migrations/v_1_10.go
  frontend/src/api/interface/app.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/app-store/detail/install/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#7868 fix(iptables): 复杂环境下转发删除端口错误
  backend/utils/firewall/client/iptables.go
Labels: do-not-merge/release-note-label-needed

#7871 feat: Copy and move files with the same name file processing
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/host/file-management/index.vue
  frontend/src/views/host/file-management/move/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#7872 fix: Fix the problem of duplicate content display in the model list
  backend/app/service/ai_tool.go
  backend/app/service/website_utils.go
  frontend/src/views/ai-tools/model/index.vue
  frontend/src/views/container/repo/operator/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#7887 fix: Change the AI routing interface
  backend/app/api/v1/ai.go
  backend/app/dto/ai.go
  backend/app/service/ai.go
  backend/constant/common.go
  backend/router/ro_ai.go
  cmd/server/docs/docs.go
  cmd/server/docs/swagger.json
  cmd/server/docs/swagger.yaml
  frontend/src/api/interface/ai.ts
  frontend/src/api/modules/ai-tool.ts
  frontend/src/api/modules/ai.ts
  frontend/src/routers/modules/ai.ts
  frontend/src/views/ai/gpu/index.vue
  frontend/src/views/ai/model/add/index.vue
  frontend/src/views/ai/model/conn/index.vue
  frontend/src/views/ai/model/domain/index.vue
  frontend/src/views/ai/model/index.vue
  go.mod
Labels: do-not-merge/release-note-label-needed, dev

#7894 feat: Modified the logic for AI Tool
  backend/app/dto/ai.go
  backend/app/service/ai.go
  backend/utils/common/common.go
  frontend/src/api/interface/ai.ts
  frontend/src/views/ai/model/domain/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#7895 fix: Adjust the synchronization method for the Ollama model
  backend/app/api/v1/ai.go
  backend/app/dto/ai.go
  backend/app/dto/common_req.go
  backend/app/model/ai.go
  backend/app/repo/ai.go
  backend/app/service/ai.go
  backend/app/service/entry.go
  backend/app/service/file.go
  backend/constant/status.go
  backend/init/migration/migrate.go
  backend/init/migration/migrations/v_1_10.go
  backend/router/ro_ai.go
  cmd/server/docs/docs.go
  cmd/server/docs/swagger.json
  cmd/server/docs/swagger.yaml
  frontend/src/api/interface/ai.ts
  frontend/src/api/modules/ai.ts
  frontend/src/components/log-file/index.vue
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/ai/model/del/index.vue
  frontend/src/views/ai/model/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#7896 fix: Fixed the issue where local application descriptions were not di…
  backend/app/dto/app.go
  backend/app/service/app_utils.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#7897 feat: Added display of ollama proxy address
  backend/app/dto/ai.go
  backend/app/service/ai.go
  frontend/src/api/interface/ai.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/ai/model/conn/index.vue
  frontend/src/views/ai/model/domain/index.vue
  frontend/src/views/ai/model/index.vue
Labels: do-not-merge/release-note-label-needed, dev

#7898 feat: Added underscore support for website default documents
  frontend/src/global/form-rules.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
Labels: do-not-merge/release-note-label-needed, dev

#7899 fix: Optimized ollama model status display
  backend/app/service/ai.go
  backend/constant/status.go
  backend/init/hook/hook.go
  frontend/src/components/log-file/index.vue
  frontend/src/views/ai/model/add/index.vue
  frontend/src/views/ai/model/del/index.vue
  frontend/src/views/ai/model/index.vue
Labels: dev

#7900 feat: Added partial prompt messages
  backend/app/dto/response/app.go
  backend/app/service/app_install.go
  backend/app/service/app_utils.go
  frontend/src/api/interface/app.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/ai/model/domain/index.vue
  frontend/src/views/ai/model/index.vue
  frontend/src/views/app-store/installed/detail/index.vue
  frontend/src/views/app-store/installed/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#7901 feat: Adjusted the position of the quick jump button.
  frontend/src/views/ai/model/domain/index.vue
Labels: do-not-merge/release-note-label-needed, dev

#7905 feat: Updated partial translations.
  agent/app/service/nginx.go
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/utils/util.ts
  frontend/src/views/app-store/detail/install/index.vue
  frontend/src/views/app-store/setting/index.vue
  frontend/src/views/host/process/network/index.vue
  frontend/src/views/website/website/config/basic/resource/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#7907 feat: Support for terminal operation with the Ollama model
  backend/app/api/v1/ai.go
  backend/app/api/v1/terminal.go
  backend/app/service/ai.go
  backend/router/ro_ai.go
  cmd/server/docs/docs.go
  cmd/server/docs/swagger.json
  cmd/server/docs/swagger.yaml
  frontend/src/api/modules/ai.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/ai/model/index.vue
  frontend/src/views/ai/model/terminal/index.vue
  frontend/src/views/container/container/terminal/index.vue
Labels: dev

#7908 feat: Optimize encryption method
  agent/app/service/dashboard.go
  agent/utils/encrypt/encrypt.go
  agent/utils/files/file_op.go
  frontend/src/assets/iconfont/iconfont.css
  frontend/src/assets/iconfont/iconfont.js
  frontend/src/assets/iconfont/iconfont.json
  frontend/src/assets/iconfont/iconfont.svg
  frontend/src/assets/iconfont/iconfont.ttf
  frontend/src/assets/iconfont/iconfont.woff
  frontend/src/assets/iconfont/iconfont.woff2
  frontend/src/components/license-import/index.vue
  frontend/src/routers/modules/terminal.ts
  frontend/src/views/setting/license/index.vue
Labels: do-not-merge/release-note-label-needed, dev-v2

#7910 fix: Fixed the issue of failing to update reverse proxy files
  agent/app/service/website.go
  frontend/src/components/log-file/index.vue
  frontend/src/views/website/website/create/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#7913 feat: AI tool Added quick jump functionality
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/ai/model/domain/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#7914 fix: Fix the issue of abnormal display of recommended applications on…
  agent/app/api/v2/dashboard.go
  agent/app/service/cronjob.go
  agent/router/ro_dashboard.go
  core/app/service/app_launcher.go
  frontend/src/components/dialog-pro/index.vue
  frontend/src/views/home/app/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#7915 fix: Fix the loading method of slow logs in MySQL and MariaDB
  backend/app/service/database_common.go
  backend/app/service/file.go
  frontend/src/views/database/mysql/setting/slow-log/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#7916 fix: Fixed the issue with incorrect routing for quick jump during app…
  agent/app/service/file.go
  frontend/src/routers/index.ts
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#7918 feat: Improve international language
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#7920 fix: Optimize status display.
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/ai/model/index.vue
Labels: do-not-merge/release-note-label-needed, dev

#7926 fix: Resolve the issue of local application label loss
  backend/cron/job/app.go
Labels: dev

#7927 feat: API timestamp verification
  backend/middleware/session.go
Labels: dev

#7924 fix: Fix the issue of obtaining errors in global configuration.
  core/init/viper/viper.go
Labels: dev-v2

#7932 style: Fix the issue of inconsistent menu spacing.
  frontend/src/layout/components/Sidebar/index.scss
Labels: dev

#7935 fix: Modify help information about Ollama pull
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
Labels: dev

#7941 feat: Add the display of details for backup accounts.
  agent/app/dto/snapshot.go
  agent/cron/cron.go
  core/app/dto/setting.go
  frontend/src/api/interface/setting.ts
  frontend/src/api/modules/setting.ts
  frontend/src/components/codemirror-pro/index.vue
  frontend/src/components/detail-show/index.vue
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/cronjob/operate/index.vue
  frontend/src/views/setting/backup-account/index.vue
Labels: dev-v2

#7945 fix: Fix the issue of loading errors for editing container port data
  backend/app/service/backup_mysql.go
  backend/app/service/backup_postgresql.go
  backend/app/service/container.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#7946 style: Adjust the width display of the model list
  frontend/src/views/ai/model/add/index.vue
  frontend/src/views/ai/model/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#7950 fix: Fix the issue of inconsistent deletion status for the ollama model
  frontend/src/views/ai/model/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#7953 fix: Fixed the issue of no echo after binding the SSL to the AI.
  frontend/src/views/ai/model/domain/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#7966 feat: Update zh-Hant translation
  backend/i18n/lang/zh-Hant.yaml
  frontend/src/lang/modules/tw.ts
Labels: do-not-merge/release-note-label-needed

#7958 feat: Support freemyip.com DNS provider
  backend/utils/ssl/client.go
  frontend/src/global/mimetype.ts
  frontend/src/views/website/ssl/dns-account/create/index.vue
  go.mod
  go.sum
Labels: do-not-merge/release-note-label-needed

#7955 feat: Added progress display for image pulling
  agent/app/service/app_utils.go
  agent/app/service/website.go
  agent/app/service/website_utils.go
  agent/app/task/task.go
  agent/utils/docker/docker.go
  core/constant/common.go
  frontend/src/views/log/task/index.vue
  frontend/src/views/login/components/login-form.vue
  frontend/src/views/login/index.vue
Labels: do-not-merge/release-note-label-needed, dev-v2

#7960 fix(container/log): enable close-on-click-modal and wrap log update in nextTick
  frontend/src/components/compose-log/index.vue
  frontend/src/components/container-log/index.vue
  frontend/src/views/container/container/log/index.vue
Labels: do-not-merge/release-note-label-needed

#7974 fix: Fix the issue with the homepage route refresh
  backend/app/api/v1/setting.go
  backend/init/router/router.go
Labels: do-not-merge/release-note-label-needed, dev

#7976 fix: Modify the logic for adding hosts
  core/app/service/host.go
Labels: dev-v2

#7981 feat: API interface IP whitelist supports IPv6
  backend/middleware/session.go
  frontend/src/utils/util.ts
  frontend/src/views/setting/panel/api-interface/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#7980 fix: Fix issue with .NET environment creation failure
  agent/app/service/container.go
  agent/app/service/runtime_utils.go
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/home/app/index.vue
  frontend/src/views/website/runtime/dotnet/index.vue
  frontend/src/views/website/runtime/dotnet/operate/index.vue
  frontend/src/views/website/runtime/go/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#7982 feat: Merge code of gpu from dev
  agent/app/api/v2/ai.go
  agent/app/api/v2/entry.go
  agent/app/api/v2/terminal.go
  agent/app/dto/ai.go
  agent/app/dto/common_req.go
  agent/app/model/ai.go
  agent/app/repo/ai.go
  agent/app/service/ai.go
  agent/app/service/dashboard.go
  agent/app/service/entry.go
  agent/app/service/website_utils.go
  agent/init/migration/migrate.go
  agent/init/migration/migrations/init.go
  agent/router/ai.go
  agent/router/common.go
  agent/utils/ai_tools/gpu/common/gpu_info.go
  agent/utils/ai_tools/gpu/gpu.go
  agent/utils/ai_tools/gpu/schema_v12/parser.go
  agent/utils/ai_tools/gpu/schema_v12/types.go
  agent/utils/ai_tools/xpu/types.go
  agent/utils/ai_tools/xpu/xpu.go
  agent/utils/ai_tools/xpu/xpu_info.go
  agent/utils/common/common.go
  agent/utils/nginx/components/server.go
  core/constant/common.go
  frontend/src/api/interface/ai.ts
  frontend/src/api/modules/ai.ts
  frontend/src/assets/iconfont/iconfont.css
  frontend/src/assets/iconfont/iconfont.js
  frontend/src/assets/iconfont/iconfont.json
  frontend/src/assets/iconfont/iconfont.svg
  frontend/src/assets/iconfont/iconfont.ttf
  frontend/src/assets/iconfont/iconfont.woff
  frontend/src/assets/iconfont/iconfont.woff2
  frontend/src/components/app-status/index.vue
  frontend/src/components/system-upgrade/upgrade/index.vue
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/routers/modules/ai.ts
  frontend/src/routers/modules/container.ts
  frontend/src/routers/modules/database.ts
  frontend/src/routers/modules/host.ts
  frontend/src/routers/modules/terminal.ts
  frontend/src/routers/modules/toolbox.ts
  frontend/src/views/ai/gpu/index.vue
  frontend/src/views/ai/model/add/index.vue
  frontend/src/views/ai/model/conn/index.vue
  frontend/src/views/ai/model/del/index.vue
  frontend/src/views/ai/model/domain/index.vue
  frontend/src/views/ai/model/index.vue
  frontend/src/views/ai/model/terminal/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#7983 fix: Fix the issue with AI proxy certificate res error
  backend/app/dto/ai.go
  backend/app/service/ai.go
  frontend/src/api/interface/ai.ts
  frontend/src/views/ai/model/domain/index.vue
Labels: dev

#7986 feat: merge ai from dev
  agent/app/dto/ai.go
  agent/app/service/ai.go
  frontend/src/api/interface/ai.ts
  frontend/src/components/app-status/index.vue
  frontend/src/views/ai/model/domain/index.vue
Labels: do-not-merge/release-note-label-needed, dev-v2

#7987 feat: Support gpu of schema v11
  agent/utils/ai_tools/gpu/gpu.go
  agent/utils/ai_tools/gpu/schema/parser.go
  agent/utils/ai_tools/gpu/schema/types.go
  agent/utils/cmd/cmd.go
  frontend/src/views/ai/gpu/index.vue
Labels: do-not-merge/release-note-label-needed, dev-v2

#7988 feat: Support gpu of schema v11
  backend/utils/ai_tools/gpu/gpu.go
  backend/utils/ai_tools/gpu/schema/parser.go
  backend/utils/ai_tools/gpu/schema/types.go
  frontend/src/views/ai/gpu/index.vue
Labels: do-not-merge/release-note-label-needed, dev

#7989 fix: Fix the issue of the container creation not popping up the task box
  agent/app/service/container.go
  frontend/src/api/interface/container.ts
  frontend/src/views/container/container/index.vue
  frontend/src/views/container/container/operate/index.vue
Labels: dev-v2

#7992 feat: Resolve issue with bulk domain generation failure
  frontend/src/views/website/ssl/index.vue
  frontend/src/views/website/website/domain-create/index.vue
Labels: dev-v2

#7995 feat(file): Add download task button to view current ongoing download tasks
  agent/app/api/v2/file.go
  agent/router/ro_file.go
  frontend/src/api/modules/files.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/host/file-management/index.vue
  frontend/src/views/host/file-management/process/index.vue
Labels: dev-v2

#7996 fix: Improve some internationalized content
  frontend/src/assets/iconfont/iconfont.css
  frontend/src/assets/iconfont/iconfont.js
  frontend/src/assets/iconfont/iconfont.json
  frontend/src/assets/iconfont/iconfont.svg
  frontend/src/assets/iconfont/iconfont.ttf
  frontend/src/assets/iconfont/iconfont.woff
  frontend/src/assets/iconfont/iconfont.woff2
  frontend/src/components/task-log/index.vue
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/layout/components/Sidebar/index.scss
  frontend/src/views/cronjob/operate/index.vue
  frontend/src/views/toolbox/clam/operate/index.vue
Labels: dev-v2

#8002 fix: Update swagger docs
  backend/app/api/v1/container.go
  cmd/server/docs/docs.go
  cmd/server/docs/swagger.json
  cmd/server/docs/swagger.yaml
Labels: dev

#8004 feat:Update translations
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/host/file-management/index.vue
Labels: dev-v2

#8008 Fix issue with runtime environment restart failure
  agent/app/service/container_compose.go
  agent/app/service/runtime_utils.go
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
Labels: dev-v2

#8007 fix: Fix the issue of abnormal display on the monitoring page
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/routers/modules/host.ts
  frontend/src/views/home/app/index.vue
  frontend/src/views/host/monitor/monitor/index.vue
  frontend/src/views/terminal/index.vue
Labels: dev-v2

#8011 feat: update default app.yaml
  cmd/server/conf/app.yaml
Labels: do-not-merge/release-note-label-needed, dev

#8010 feat: Change frontend locale code from 'tw' to 'zh-Hant'
  frontend/src/App.vue
  frontend/src/api/index.ts
  frontend/src/lang/index.ts
  frontend/src/lang/modules/zh-Hant.ts
  frontend/src/utils/util.ts
  frontend/src/views/app-store/detail/params/index.vue
  frontend/src/views/app-store/installed/detail/index.vue
  frontend/src/views/log/operation/index.vue
  frontend/src/views/login/components/login-form.vue
  frontend/src/views/setting/panel/index.vue
  frontend/src/views/website/runtime/php/create/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8012 fix: Fix the problem of abnormal theme color switching
  agent/app/repo/monitor.go
  frontend/src/layout/index.vue
  frontend/src/utils/xpack.ts
  frontend/src/views/login/components/login-form.vue
  frontend/src/views/setting/panel/password/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8014 fix(system): Fix issue where accessing with an unbound domain returns an error
  core/app/api/v2/setting.go
  core/init/router/router.go
  core/middleware/ip_limit.go
  core/utils/common/common.go
  frontend/src/assets/json/china/en.json
  frontend/src/assets/json/china/zh.json
  frontend/src/utils/util.ts
Labels: do-not-merge/release-note-label-needed, lgtm, dev-v2

#8016 style: Change wget page style
  frontend/src/views/host/file-management/process/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#8017 feat: Update translations
  agent/i18n/lang/en.yaml
  agent/i18n/lang/fa.yaml
  agent/i18n/lang/ja.yaml
  agent/i18n/lang/ko.yaml
  agent/i18n/lang/ms.yml
  agent/i18n/lang/pt-BR.yaml
  agent/i18n/lang/pt.yaml
  agent/i18n/lang/ru.yaml
  agent/i18n/lang/zh-Hant.yaml
  agent/i18n/lang/zh.yaml
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8024 fix: Fix issue with application recovery failure
  frontend/src/components/upload/index.vue
Labels: do-not-merge/release-note-label-needed, dev-v2

#8025 fix: Adjust the container task log
  agent/app/service/container.go
  frontend/src/views/terminal/host/operate/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, dev-v2

#8026 feat: Standardize runtime environment status handling
  frontend/src/api/modules/files.ts
  frontend/src/utils/runtime.ts
  frontend/src/views/website/runtime/dotnet/index.vue
  frontend/src/views/website/runtime/go/index.vue
  frontend/src/views/website/runtime/java/index.vue
  frontend/src/views/website/runtime/node/index.vue
  frontend/src/views/website/runtime/php/index.vue
  frontend/src/views/website/runtime/python/index.vue
  frontend/src/views/website/website/create/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, dev-v2

#8027 feat: Optimize file selection UI
  frontend/src/assets/iconfont/iconfont.css
  frontend/src/assets/iconfont/iconfont.ttf
  frontend/src/assets/iconfont/iconfont.woff
  frontend/src/assets/iconfont/iconfont.woff2
  frontend/src/components/file-list/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8028 fix: Fix the monitoring data exception
  agent/app/dto/setting.go
  agent/app/repo/monitor.go
  agent/app/service/monitor.go
  agent/app/service/snapshot_create.go
  agent/cron/cron.go
  agent/init/migration/migrate.go
  agent/init/migration/migrations/init.go
  core/app/dto/setting.go
  core/init/migration/migrate.go
  core/init/migration/migrations/init.go
  frontend/src/views/ai/model/conn/index.vue
  frontend/src/views/database/mysql/conn/index.vue
  frontend/src/views/database/postgresql/conn/index.vue
  frontend/src/views/database/redis/conn/index.vue
  frontend/src/views/home/app/index.vue
  frontend/src/views/host/file-management/recycle-bin/index.vue
  frontend/src/views/host/firewall/status/index.vue
  frontend/src/views/host/monitor/setting/index.vue
  frontend/src/views/login/components/login-form.vue
  frontend/src/views/setting/panel/index.vue
  frontend/src/views/setting/safe/bind/index.vue
  frontend/src/views/terminal/setting/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, dev-v2

#8029 feat: Update translations
  agent/i18n/lang/en.yaml
  agent/i18n/lang/ja.yaml
  agent/i18n/lang/ko.yaml
  agent/i18n/lang/ms.yml
  agent/i18n/lang/pt-BR.yaml
  agent/i18n/lang/ru.yaml
  agent/i18n/lang/zh-Hant.yaml
  agent/i18n/lang/zh.yaml
  frontend/src/components/bread-crumbs/bread-crumbs-item.vue
  frontend/src/components/bread-crumbs/index.vue
  frontend/src/components/file-list/index.vue
  frontend/src/components/port-jump/index.vue
  frontend/src/lang/modules/zh.ts
  frontend/src/views/container/setting/index.vue
  frontend/src/views/host/file-management/index.vue
  frontend/src/views/website/runtime/dotnet/index.vue
  frontend/src/views/website/runtime/php/create/index.vue
Labels: do-not-merge/release-note-label-needed, dev-v2

#8030 fix: Fix scheduled task execution exceptions
  agent/app/service/cronjob.go
  agent/app/service/cronjob_helper.go
  core/constant/common.go
  frontend/src/components/complex-table/index.vue
  frontend/src/components/task-list/index.vue
  frontend/src/layout/components/Sidebar/index.vue
  frontend/src/views/cronjob/operate/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8037 fix: Fix ollama model log exception
  agent/app/api/v2/ai.go
  agent/app/dto/ai.go
  agent/app/service/ai.go
  agent/app/service/cronjob_helper.go
  agent/app/service/firewall.go
  agent/app/task/task.go
  agent/constant/status.go
  agent/i18n/lang/zh.yaml
  agent/init/hook/hook.go
  agent/utils/cmd/cmd.go
  core/init/router/router.go
  frontend/src/api/modules/ai.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/zh-Hant.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/ai/model/add/index.vue
  frontend/src/views/ai/model/index.vue
  frontend/src/views/ai/model/terminal/index.vue
  frontend/src/views/container/container/terminal/index.vue
  frontend/src/views/cronjob/operate/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2
