Repository 1Panel-dev/1Panel, pull requests merged in 2025-08, with the labels that each got.

#9782 feat: Optimize SSH key management
  agent/app/api/v2/setting.go
  agent/app/api/v2/ssh.go
  agent/app/dto/ssh.go
  agent/app/model/ssh.go
  agent/app/repo/host.go
  agent/app/service/ssh.go
  agent/init/migration/migrations/init.go
  agent/router/ro_host.go
  frontend/src/api/interface/host.ts
  frontend/src/api/modules/host.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/tr.ts
  frontend/src/lang/modules/zh-Hant.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/host/ssh/ssh/certification/index.vue
  frontend/src/views/host/ssh/ssh/index.vue
  frontend/src/views/host/ssh/ssh/pubkey/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#9785 fix: Fix overview page refresh issue
  frontend/src/layout/components/Sidebar/components/Collapse.vue
  frontend/src/views/home/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#9796 fix: Fix file copy overwrite error
  agent/app/service/file.go
Labels: do-not-merge/release-note-label-needed, dev-v2

#9827 fix: Fixed issue with where runtime website fails to start after beinng stopped
  agent/app/service/app.go
  agent/app/service/website_utils.go
Labels: do-not-merge/release-note-label-needed, lgtm, dev-v2

#9833 fix: Optimize SSH key synchronization
  agent/app/repo/host.go
  agent/app/service/ssh.go
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/tr.ts
  frontend/src/lang/modules/zh-Hant.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/host/ssh/ssh/certification/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#9831 fix: Add autostart configuration for supervisor
  agent/app/dto/request/host_tool.go
  agent/app/dto/response/host_tool.go
  agent/app/service/host_tool.go
  frontend/src/api/interface/host-tool.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/tr.ts
  frontend/src/lang/modules/zh-Hant.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/toolbox/supervisor/create/index.vue
Labels: do-not-merge/release-note-label-needed, approved, dev-v2

#9834 style: file code editor style
  frontend/src/styles/element-dark.scss
  frontend/src/styles/element.scss
  frontend/src/views/host/file-management/code-editor/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#9839 fix: Move inline editorconfig comments
  frontend/.editorconfig
Labels: do-not-merge/release-note-label-needed

#9845 ref: Optimize code
  agent/app/model/alert.go
  agent/utils/version/version.go
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#9848 fix: Fix redis configuration modification issues
  agent/app/dto/database.go
  agent/app/service/app_install.go
  agent/app/service/database_common.go
  agent/app/service/database_redis.go
  frontend/src/api/interface/database.ts
  frontend/src/views/database/postgresql/setting/index.vue
  frontend/src/views/database/redis/setting/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#9852 feat: Delete app while ignoring it during synchronization.
  agent/app/repo/app_ignore_upgrade.go
  agent/app/service/app_utils.go
  frontend/src/components/log/file/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, dev-v2

#9853 fix: Fix the issue where viewing logs during certificate application
  agent/app/service/website_ssl.go
Labels: do-not-merge/release-note-label-needed, dev-v2

#9855 style: Adjust menu tab styling
  frontend/src/layout/components/Tabs/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#9859 fix: Add custom timeout support for remote database
  agent/app/service/database.go
  agent/utils/redis/redis.go
  frontend/src/api/modules/database.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/tr.ts
  frontend/src/lang/modules/zh-Hant.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/database/mysql/index.vue
  frontend/src/views/database/postgresql/remote/index.vue
  frontend/src/views/database/postgresql/remote/operate/index.vue
  frontend/src/views/database/redis/remote/index.vue
  frontend/src/views/database/redis/remote/operate/index.vue
Labels: do-not-merge/release-note-label-needed, dev-v2

#9857 feat: Add master node IP validation when installing a cluster slave node
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/tr.ts
  frontend/src/lang/modules/zh-Hant.ts
  frontend/src/lang/modules/zh.ts
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#9861 fix: Fix menu name display issue
  frontend/src/routers/modules/host.ts
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#9862 fix: Fix menu name display issue
  frontend/src/routers/modules/host.ts
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#9864 fix: Reset data before copying files
  frontend/src/styles/element-dark.scss
  frontend/src/views/host/file-management/move/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#9865 fix: Add non-standard log filtering for SSH
  agent/app/service/ssh.go
Labels: do-not-merge/release-note-label-needed, lgtm, dev-v2

#9868 fix: Add remote database connection timeout record
  agent/app/dto/database.go
  agent/app/model/database.go
  agent/app/service/database.go
  agent/init/migration/migrations/init.go
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/tr.ts
  frontend/src/lang/modules/zh-Hant.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/cronjob/cronjob/record/index.vue
  frontend/src/views/database/mysql/remote/index.vue
  frontend/src/views/database/postgresql/remote/index.vue
  frontend/src/views/database/redis/remote/index.vue
  frontend/src/views/setting/snapshot/status/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#9872 style: Update list styling for cronjob
  frontend/src/views/cronjob/cronjob/index.vue
  frontend/src/views/cronjob/cronjob/operate/index.vue
Labels: dev-v2

#9874 fix: Fix node ip switch exception issue
  frontend/src/api/index.ts
  frontend/src/layout/components/Sidebar/components/Collapse.vue
  frontend/src/utils/node.ts
  frontend/src/views/log/operation/index.vue
  frontend/src/views/login/components/login-form.vue
  frontend/src/views/toolbox/device/time-zone/index.vue
Labels: dev-v2

#9882 fix: Fix menu display exception issue
  frontend/src/routers/modules/website.ts
Labels: dev-v2

#9881 feat: add root config for proxy website
  agent/app/service/website_utils.go
Labels: dev-v2

#9890 feat: Optimize backup filename format for cronjob
  agent/app/service/cronjob_backup.go
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#9901 fix: Enhance OperateProxy location parsing to support custom Nginx configs
  agent/app/service/website.go
Labels: do-not-merge/release-note-label-needed

#9902 fix: Optimize toolbox cache cleaning functionality
  agent/app/api/v2/cronjob.go
  agent/app/dto/cronjob.go
  agent/app/service/cronjob.go
  agent/app/service/device_clean.go
  agent/router/ro_cronjob.go
  frontend/src/api/modules/cronjob.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/tr.ts
  frontend/src/lang/modules/zh-Hant.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/routers/modules/toolbox.ts
  frontend/src/views/toolbox/clean/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#9914 feat: Reverse proxy supports configuring server caching
  agent/app/dto/request/website.go
  agent/app/service/website.go
  agent/utils/nginx/components/location.go
  frontend/src/api/interface/website.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/tr.ts
  frontend/src/lang/modules/zh-Hant.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/website/website/config/basic/proxy/create/index.vue
Labels: do-not-merge/release-note-label-needed, dev-v2

#9905 fix: Add margin to "View comparison" button and fix "Use custom version" button color issue
  frontend/src/views/app-store/installed/upgrade/diff/index.vue
  frontend/src/views/app-store/installed/upgrade/index.vue
Labels: do-not-merge/release-note-label-needed

#9925 feat: support riscv64
  .goreleaser.yaml
  agent/app/service/snapshot.go
  core/app/service/upgrade.go
  core/utils/common/common.go
Labels: do-not-merge/release-note-label-needed

#9944 feat: Restrict special characters in website aliases
  frontend/src/views/website/website/create/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#9947 feat: Optimize node synchronization logic
  core/app/service/backup.go
  core/app/service/script_library.go
  core/app/service/setting.go
  core/i18n/lang/en.yaml
  core/i18n/lang/ja.yaml
  core/i18n/lang/ko.yaml
  core/i18n/lang/ms.yml
  core/i18n/lang/pt-BR.yaml
  core/i18n/lang/ru.yaml
  core/i18n/lang/tr.yaml
  core/i18n/lang/zh-Hant.yaml
  core/i18n/lang/zh.yaml
  core/init/cron/job/backup.go
  frontend/src/views/setting/backup-account/operate/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#9951 fix: Add ctrl+c support in container terminal
  agent/utils/terminal/ws_local_session.go
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#9946 fix: Fixed the issue where IPv6 would turn off after favoriting a website.
  agent/app/dto/response/website.go
  agent/app/service/website.go
  frontend/src/views/website/website/config/basic/other/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#9961 fix: Fix clamdscan timeout issues
  agent/app/service/clam.go
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#9963 feat: Exit file upload with added prompt
  frontend/src/components/drawer-pro/index.vue
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/tr.ts
  frontend/src/lang/modules/zh-Hant.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/host/file-management/upload/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#9964 fix: Fix the issue where SSH sessions keep loading indefinitely
  agent/app/api/v2/monitor.go
  agent/app/service/alert.go
  agent/app/service/alert_helper.go
  agent/app/service/container.go
  agent/app/service/dashboard.go
  agent/app/service/device.go
  agent/app/service/monitor.go
  agent/app/service/process.go
  agent/app/service/recycle_bin.go
  agent/app/service/snapshot.go
  agent/go.mod
  agent/go.sum
  agent/utils/websocket/process_data.go
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#9965 style: Download progress adapted for dark mode
  frontend/src/views/host/file-management/process/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#9973 feat: Add quick jump to website directory button
  agent/app/dto/response/app.go
  agent/app/service/app_install.go
  frontend/src/api/interface/app.ts
  frontend/src/components/app-status/index.vue
  frontend/src/components/table-search/index.vue
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/tr.ts
  frontend/src/lang/modules/zh-Hant.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/app-store/installed/index.vue
  frontend/src/views/website/website/index.vue
  frontend/src/views/website/website/nginx/index.vue
Labels: lgtm, approved, dev-v2

#9974 fix: Fix .tgz file decompression exception issue
  frontend/src/enums/files.ts
  frontend/src/views/host/file-management/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#9977 fix: Modify domain binding and authorization IP priority logic
  core/init/router/router.go
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#9978 fix: Fix the issue of system certificates not auto-renewing.
  agent/app/service/website_utils.go
  agent/utils/req_helper/core.go
Labels: do-not-merge/release-note-label-needed, dev-v2

#9987 fix: Fix terminal connection initialization exception
  agent/app/api/v2/setting.go
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#9996 fix: Optimize license error messaging
  core/i18n/lang/en.yaml
  core/i18n/lang/ja.yaml
  core/i18n/lang/ko.yaml
  core/i18n/lang/ms.yml
  core/i18n/lang/pt-BR.yaml
  core/i18n/lang/ru.yaml
  core/i18n/lang/tr.yaml
  core/i18n/lang/zh-Hant.yaml
  core/i18n/lang/zh.yaml
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#9998 feat: Add file verification for SSH file transfers
  core/utils/ssh/ssh.go
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#10000 fix：Asynchronous log writing has not taken effect
  core/log/writer.go
Labels: do-not-merge/release-note-label-needed

#10011 feat: Support file management page drag and drop upload
  frontend/src/views/host/file-management/index.vue
  frontend/src/views/host/file-management/upload/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#10014 feat: Add empty state prompt for app list
  frontend/src/lang/modules/zh.ts
  frontend/src/views/app-store/apps/app/index.vue
  frontend/src/views/app-store/apps/index.vue
  frontend/src/views/app-store/apps/no-app/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#10034 feat(alert): Support panel login/ssh login/license exception and node exception alerts
  agent/app/dto/alert.go
  agent/app/model/alert.go
  agent/app/service/alert.go
  agent/app/service/alert_helper.go
  agent/app/service/alert_sender.go
  agent/i18n/lang/en.yaml
  agent/i18n/lang/ja.yaml
  agent/i18n/lang/ko.yaml
  agent/i18n/lang/ms.yaml
  agent/i18n/lang/pt-BR.yaml
  agent/i18n/lang/ru.yaml
  agent/i18n/lang/tr.yaml
  agent/i18n/lang/zh-Hant.yaml
  agent/i18n/lang/zh.yaml
  agent/init/migration/migrate.go
  agent/init/migration/migrations/init.go
  agent/utils/alert/alert.go
  agent/utils/alert_push/alert_push.go
  agent/utils/xpack/xpack.go
  frontend/src/api/interface/alert.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/tr.ts
  frontend/src/lang/modules/zh-Hant.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/utils/util.ts
  frontend/src/views/setting/alert/dash/index.vue
  frontend/src/views/setting/alert/dash/task/index.vue
  frontend/src/views/setting/alert/log/index.vue
  frontend/src/views/setting/alert/setting/time-range/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#10047 feat: Optimize App Store Tag Selection
  frontend/src/views/app-store/apps/index.vue
  frontend/src/views/app-store/components/tag.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#10049 feat: File list supports right-click operation
  frontend/src/components/right-context-menu/index.vue
  frontend/src/views/host/file-management/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#10050 fix: fix slow log state toggle exception
  agent/app/service/database_mysql.go
  frontend/src/views/database/mysql/setting/slow-log/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#10052 fix: Fix temporary file leak during snapshot deletion
  agent/app/service/snapshot.go
Labels: do-not-merge/release-note-label-needed, lgtm, dev-v2

#10055 feat: Add default value support for file selection component
  frontend/src/components/file-list/index.vue
  frontend/src/views/host/file-management/hooks/searchable.ts
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#10063 feat: Optimize code
  agent/app/service/alert_helper.go
  frontend/src/components/complex-table/index.vue
  frontend/src/utils/util.ts
  frontend/src/views/host/file-management/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#10072 feat: Support table row selection
  frontend/src/components/complex-table/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#10077 fix: Fix partial WebDAV upload failures
  agent/go.mod
  agent/go.sum
  agent/utils/cloud_storage/client/helper/webdav/auth.go
  agent/utils/cloud_storage/client/helper/webdav/auth_basic.go
  agent/utils/cloud_storage/client/helper/webdav/auth_digest.go
  agent/utils/cloud_storage/client/helper/webdav/auth_passport.go
  agent/utils/cloud_storage/client/helper/webdav/errors.go
  agent/utils/cloud_storage/client/helper/webdav/file.go
  agent/utils/cloud_storage/client/helper/webdav/reques.go
  agent/utils/cloud_storage/client/helper/webdav/utils.go
  agent/utils/cloud_storage/client/helper/webdav/webdav.go
  agent/utils/cloud_storage/client/webdav.go
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#10079 fix: Fixed issue with website proxy proxy_ssl_name display error
  agent/app/service/website.go
Labels: do-not-merge/release-note-label-needed, dev-v2

#10080 feat: Supports inline editing of file names
  frontend/src/views/host/file-management/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#10095 fix: Add service health check to node editing
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/tr.ts
  frontend/src/lang/modules/zh-Hant.ts
  frontend/src/lang/modules/zh.ts
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#10096 fix: Optimize image push logic
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/tr.ts
  frontend/src/lang/modules/zh-Hant.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/container/image/push/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#10101 feat: Add description field matching to application search
  agent/app/repo/app.go
  agent/app/service/app.go
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#10103 fix: Optimize container image operation task logging
  agent/utils/docker/docker.go
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#10107 style: Optimize version update log styling
  frontend/src/components/system-upgrade/releases/index.vue
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/tr.ts
  frontend/src/lang/modules/zh-Hant.ts
  frontend/src/lang/modules/zh.ts
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#10108 feat: improve empty state for app store
  frontend/src/views/app-store/apps/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#10109 feat: Add system information copy button for dashboard
  frontend/src/views/home/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#10111 fix: resolve log loss in certain scenarios
  frontend/src/components/log/file/index.vue
  frontend/src/views/cronjob/cronjob/record/index.vue
  frontend/src/views/website/website/config/basic/php/composer/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#10114 fix: Fix SSH log export exception when logs are empty
  agent/app/api/v2/ssh.go
  agent/app/service/ssh.go
  agent/i18n/lang/en.yaml
  agent/i18n/lang/ja.yaml
  agent/i18n/lang/ko.yaml
  agent/i18n/lang/ms.yaml
  agent/i18n/lang/pt-BR.yaml
  agent/i18n/lang/ru.yaml
  agent/i18n/lang/tr.yaml
  agent/i18n/lang/zh-Hant.yaml
  agent/i18n/lang/zh.yaml
  agent/utils/csv_export/ssh_log.go
  frontend/src/api/modules/host.ts
  frontend/src/views/host/ssh/log/log.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#10128 fix: Optimize application recommendation logic
  agent/app/repo/app.go
  agent/app/service/dashboard.go
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#10130 fix: Optimize decryption implementation
  agent/utils/encrypt/encrypt.go
  core/utils/encrypt/encrypt.go
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#10131 refactor: reverse proxy rules
  frontend/src/views/website/website/config/basic/proxy/create/index.vue
  frontend/src/views/website/website/config/basic/proxy/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#10133 fix: Add gpu monitoring support for some machines
  agent/utils/ai_tools/gpu/gpu.go
  agent/utils/ai_tools/gpu/schema/parser.go
  agent/utils/ai_tools/gpu/schema/types.go
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#10136 fix: incorrect restart strategy display in app editor
  agent/app/service/app.go
  agent/app/service/app_utils.go
  frontend/src/views/app-store/installed/detail/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#10141 optimization: optimization the log file read
  frontend/src/components/log/custom-hightlight/index.vue
  frontend/src/components/log/file/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#10142 style: change appstore tag style
  frontend/src/views/app-store/components/tag.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#10143 feat: confirm before leaving during file upload
  frontend/src/views/host/file-management/upload/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#10146 feat: Add table page size cache
  frontend/src/components/task-list/index.vue
  frontend/src/views/ai/mcp/server/index.vue
  frontend/src/views/container/compose/index.vue
  frontend/src/views/container/container/index.vue
  frontend/src/views/container/image/index.vue
  frontend/src/views/container/network/index.vue
  frontend/src/views/container/repo/index.vue
  frontend/src/views/container/template/index.vue
  frontend/src/views/container/volume/index.vue
  frontend/src/views/cronjob/cronjob/index.vue
  frontend/src/views/cronjob/library/index.vue
  frontend/src/views/database/mysql/remote/index.vue
  frontend/src/views/database/postgresql/remote/index.vue
  frontend/src/views/database/redis/remote/index.vue
  frontend/src/views/database/redis/setting/persistence/index.vue
  frontend/src/views/host/file-management/favorite/index.vue
  frontend/src/views/host/file-management/index.vue
  frontend/src/views/host/file-management/recycle-bin/index.vue
  frontend/src/views/host/firewall/forward/index.vue
  frontend/src/views/host/firewall/ip/index.vue
  frontend/src/views/host/firewall/port/index.vue
  frontend/src/views/host/ssh/log/log.vue
  frontend/src/views/host/ssh/ssh/certification/index.vue
  frontend/src/views/log/login/index.vue
  frontend/src/views/log/operation/index.vue
  frontend/src/views/log/task/index.vue
  frontend/src/views/setting/license/index.vue
  frontend/src/views/setting/snapshot/index.vue
  frontend/src/views/terminal/command/index.vue
  frontend/src/views/terminal/host/index.vue
  frontend/src/views/toolbox/ftp/log/index.vue
  frontend/src/views/website/runtime/dotnet/index.vue
  frontend/src/views/website/runtime/go/index.vue
  frontend/src/views/website/runtime/java/index.vue
  frontend/src/views/website/runtime/node/index.vue
  frontend/src/views/website/runtime/php/index.vue
  frontend/src/views/website/runtime/python/index.vue
  frontend/src/views/website/ssl/acme-account/index.vue
  frontend/src/views/website/ssl/ca/index.vue
  frontend/src/views/website/ssl/dns-account/index.vue
  frontend/src/views/website/ssl/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, dev-v2

#10147 feat: File management supports multi tab management
  frontend/src/components/complex-table/index.vue
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/tr.ts
  frontend/src/lang/modules/zh-Hant.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/host/file-management/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#10151 style: Adjust compose log display height
  agent/app/service/image.go
  frontend/src/components/log/compose/index.vue
  frontend/src/components/system-upgrade/releases/index.vue
  frontend/src/views/container/container/index.vue
  frontend/src/views/container/container/upgrade/index.vue
  frontend/src/views/container/volume/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#10149 feat: Enhance anti-leech configuration with new options and improved UI
  agent/app/service/website.go
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/tr.ts
  frontend/src/lang/modules/zh-Hant.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/website/website/config/basic/anti-Leech/index.vue
Labels: do-not-merge/release-note-label-needed

#10154 refactor: use maps
  agent/app/service/app_utils.go
  agent/app/service/runtime.go
  agent/app/service/runtime_utils.go
  agent/utils/cloud_storage/client/helper/webdav/auth_digest.go
Labels: do-not-merge/release-note-label-needed

#10159 fix: Fix image sorting anomalies
  agent/app/service/image.go
Labels: do-not-merge/release-note-label-needed, dev-v2

#10162 fix: Resolve file renaming and other operational conflicts
  frontend/src/components/complex-table/index.vue
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/tr.ts
  frontend/src/lang/modules/zh-Hant.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/host/file-management/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#10163 fix: Optimize backup logic for cronjob
  agent/app/api/v2/snapshot.go
  agent/app/service/backup.go
  agent/app/service/backup_record.go
  agent/app/service/cronjob_backup.go
  agent/app/service/cronjob_helper.go
  agent/app/service/snapshot.go
  agent/app/service/snapshot_create.go
Labels: do-not-merge/release-note-label-needed, lgtm, dev-v2

#10168 fix: Remove deprecated google drive connection information
  agent/app/service/dashboard.go
  core/app/service/backup.go
  core/constant/common.go
  core/init/migration/migrate.go
  core/init/migration/migrations/init.go
  frontend/src/components/system-upgrade/releases/index.vue
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/tr.ts
  frontend/src/lang/modules/zh-Hant.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/cronjob/cronjob/index.vue
  frontend/src/views/cronjob/cronjob/record/index.vue
  frontend/src/views/setting/backup-account/operate/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#10169 fix: Fix snapshot cronjob execution issues
  agent/app/service/cronjob_helper.go
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#10170 fix: Fix bug in file management with multiple tabs
  frontend/src/components/complex-table/index.vue
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/tr.ts
  frontend/src/lang/modules/zh-Hant.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/styles/element-dark.scss
  frontend/src/styles/element.scss
  frontend/src/views/host/file-management/hooks/searchable.ts
  frontend/src/views/host/file-management/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#10176 fix: Fix some bugs in the alert
  agent/utils/alert/alert.go
  frontend/src/views/setting/alert/dash/index.vue
  frontend/src/views/setting/alert/dash/task/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#10178 perf: optimization file component
  agent/app/service/app_utils.go
  frontend/src/components/log/file/index.vue
Labels: do-not-merge/release-note-label-needed, dev-v2

#10179 fix: Update authorization IP regular expression
  frontend/src/views/cronjob/cronjob/record/index.vue
  frontend/src/views/setting/safe/allowips/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#10180 fix: Fix folder redirection issue
  frontend/src/views/host/file-management/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#10185 fix: Resolving the Issue of Website Directory Not Migrated During OpenResty Reinstallation
  agent/app/service/app.go
  agent/app/service/app_utils.go
  agent/i18n/lang/en.yaml
  agent/i18n/lang/ja.yaml
  agent/i18n/lang/ko.yaml
  agent/i18n/lang/ms.yaml
  agent/i18n/lang/pt-BR.yaml
  agent/i18n/lang/ru.yaml
  agent/i18n/lang/tr.yaml
  agent/i18n/lang/zh-Hant.yaml
  agent/i18n/lang/zh.yaml
Labels: do-not-merge/release-note-label-needed, dev-v2

#10187 fix: Fix page loading flicker issue
  frontend/src/views/app-store/apps/index.vue
  frontend/src/views/app-store/installed/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#10188 fix: fixed issue with push ssl to node failed
  agent/app/dto/request/website_ssl.go
  agent/app/service/website_ssl.go
  frontend/src/api/interface/website.ts
  frontend/src/views/website/ssl/create/index.vue
  frontend/src/views/website/ssl/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#10191 fix: Fix the initialization issue of alert tasks
  agent/init/hook/hook.go
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/tr.ts
  frontend/src/lang/modules/zh-Hant.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/setting/alert/dash/index.vue
  frontend/src/views/setting/alert/dash/task/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#10193 fix: Fixed issue with build frontend failed
  frontend/src/views/app-store/installed/check/index.vue
  frontend/src/views/website/runtime/php/check/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#10194 fix: Fix issues with pasting files not loading and file retrieval path cursor
  frontend/src/views/host/file-management/hooks/searchable.ts
  frontend/src/views/host/file-management/index.vue
  frontend/src/views/host/file-management/move/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2
