Repository 1Panel-dev/1Panel, pull requests merged in 2025-04, with the labels that each got.

#8285 fix: Enable the ping ban function to be compatible with some IPv6 mac…
  agent/app/service/firewall.go
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8288 fix: Fix the exception of refreshing the token of Ali Cloud Disk
  agent/app/api/v2/logs.go
  agent/app/service/backup.go
  agent/app/service/backup_record.go
  agent/app/service/clam.go
  agent/app/service/logs.go
  agent/app/service/ssh.go
  agent/router/ro_log.go
  agent/utils/cloud_storage/client/local.go
  core/app/service/logs.go
  frontend/src/api/modules/log.ts
  frontend/src/views/cronjob/cronjob/index.vue
  frontend/src/views/cronjob/cronjob/operate/index.vue
  frontend/src/views/setting/backup-account/index.vue
  frontend/src/views/setting/snapshot/create/index.vue
  frontend/src/views/setting/snapshot/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8292 dev:修复注释路由前缀
  backend/app/api/v1/host_tool.go
  backend/app/api/v1/ssh.go
Labels: do-not-merge/release-note-label-needed

#8290 fix: Fixed an update failure when the container network is bridge
  backend/app/service/container.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#8291 fix: Modify the panel password verification rule
  frontend/src/views/setting/expired.vue
  frontend/src/views/setting/panel/password/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#8293 fix: Resolve cloudns reference error
  backend/utils/ssl/client.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#8299 feat: Add MCP management
  backend/app/api/v1/entry.go
  backend/app/api/v1/mcp_server.go
  backend/app/dto/mcp.go
  backend/app/dto/request/mcp_server.go
  backend/app/dto/response/mcp_server.go
  backend/app/model/mcp_server.go
  backend/app/repo/mcp_server.go
  backend/app/service/entry.go
  backend/app/service/mcp_server.go
  backend/app/service/website.go
  backend/constant/dir.go
  backend/i18n/lang/en.yaml
  backend/i18n/lang/ja.yaml
  backend/i18n/lang/ko.yaml
  backend/i18n/lang/ms.yml
  backend/i18n/lang/pt-BR.yaml
  backend/i18n/lang/ru.yaml
  backend/i18n/lang/zh-Hant.yaml
  backend/i18n/lang/zh.yaml
  backend/init/app/app.go
  backend/init/migration/migrate.go
  backend/init/migration/migrations/v_1_10.go
  backend/router/common.go
  backend/router/ro_ai.go
  backend/router/ro_mcp.go
  backend/utils/nginx/components/location.go
  cmd/server/mcp/compose.yml
  cmd/server/mcp/mcp.go
  cmd/server/nginx_conf/nginx_conf.go
  cmd/server/nginx_conf/sse.conf
  frontend/src/api/interface/ai.ts
  frontend/src/api/modules/ai.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/routers/modules/ai.ts
  frontend/src/views/ai/mcp/index.vue
  frontend/src/views/ai/mcp/server/bind/index.vue
  frontend/src/views/ai/mcp/server/import/index.vue
  frontend/src/views/ai/mcp/server/index.vue
  frontend/src/views/ai/mcp/server/operate/index.vue
  frontend/src/views/ai/mcp/server/volume/index.vue
  go.mod
  go.sum
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#8296 feat: Support the retention of remote backup files when deleting sche…
  backend/app/dto/cronjob.go
  backend/app/service/cronjob.go
  frontend/src/api/interface/cronjob.ts
  frontend/src/api/modules/cronjob.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/cronjob/index.vue
  frontend/src/views/cronjob/record/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#8298 fix: Regenerates the interface document
  cmd/server/docs/docs.go
  cmd/server/docs/swagger.json
  cmd/server/docs/swagger.yaml
  go.mod
  go.sum
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#8301 fix: Modify the container terminal connection mode
  backend/app/api/v1/terminal.go
  backend/utils/terminal/local_cmd.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#8305 feat: Website SSL DNS Type support WestCN
  backend/utils/ssl/client.go
  frontend/src/global/mimetype.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/website/ssl/dns-account/create/index.vue
  go.mod
  go.sum
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#8303 feat: Agent nodes offline, alert through the main node
  agent/constant/alert.go
  frontend/package.json
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/zh-Hant.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/store/interface/index.ts
  frontend/src/store/modules/global.ts
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8310 feat(app): fix sync custom app failed
  frontend/src/api/interface/app.ts
  frontend/src/views/app-store/apps/index.vue
  frontend/src/views/app-store/detail/index.vue
  frontend/src/views/app-store/installed/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8312 fix: Modify the pure-ftpd encryption method
  agent/utils/toolbox/helper/sha512_crypt.go
  agent/utils/toolbox/pure-ftpd.go
  core/init/migration/helper/script.go
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8315 style: Menu expansion and collapse changed to regular display
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/zh-Hant.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/layout/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8316 feat(system): fix issue with upgrade redirect
  agent/app/service/website.go
  agent/i18n/lang/zh.yaml
  frontend/src/components/log/file/index.vue
  frontend/src/layout/index.vue
  frontend/src/views/login/components/login-form.vue
  frontend/src/views/website/runtime/dotnet/index.vue
  frontend/src/views/website/runtime/go/index.vue
  frontend/src/views/website/runtime/java/index.vue
  frontend/src/views/website/runtime/node/index.vue
  frontend/src/views/website/runtime/php/index.vue
  frontend/src/views/website/runtime/python/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8317 feat: The application installation jumps to the script library
  agent/app/service/firewall.go
  agent/i18n/lang/en.yaml
  agent/i18n/lang/ja.yaml
  agent/i18n/lang/ko.yaml
  agent/i18n/lang/ms.yaml
  agent/i18n/lang/pt-BR.yaml
  agent/i18n/lang/ru.yaml
  agent/i18n/lang/zh-Hant.yaml
  agent/i18n/lang/zh.yaml
  agent/utils/firewall/client.go
  frontend/src/views/host/firewall/forward/index.vue
  frontend/src/views/host/firewall/ip/index.vue
  frontend/src/views/host/firewall/port/index.vue
  frontend/src/views/host/firewall/status/index.vue
  frontend/src/views/toolbox/clam/index.vue
  frontend/src/views/toolbox/fail2ban/index.vue
  frontend/src/views/toolbox/ftp/index.vue
  frontend/src/views/toolbox/supervisor/status/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8325 fix: Fix the problem that the verification code is not displayed when…
  core/i18n/lang/en.yaml
  core/i18n/lang/ja.yaml
  core/i18n/lang/ko.yaml
  core/i18n/lang/ms.yml
  core/i18n/lang/pt-BR.yaml
  core/i18n/lang/ru.yaml
  core/i18n/lang/zh-Hant.yaml
  frontend/src/views/login/components/login-form.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8326 fix: fix issue with install app no label
  frontend/src/store/modules/global.ts
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#8327 feat: update mcp form label
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/routers/modules/ai.ts
  frontend/src/views/ai/mcp/index.vue
  frontend/src/views/ai/mcp/server/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#8329 fix: Fix the problem that some request connections are not released
  agent/utils/cloud_storage/client/ali.go
  agent/utils/cloud_storage/client/google_drive.go
  agent/utils/cloud_storage/client/onedrive.go
  agent/utils/files/file_op.go
  agent/utils/req_helper/core.go
  agent/utils/req_helper/request.go
  agent/utils/ssl/acme.go
  core/utils/cloud_storage/client/ali.go
  core/utils/cloud_storage/client/onedrive.go
  core/utils/req_helper/proxy_local/req_to_local.go
  core/utils/req_helper/requset.go
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8330 fix: Fix the problem that the theme color display is abnormal after t…
  frontend/src/views/login/components/login-form.vue
  frontend/src/views/setting/panel/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8331 feat: add config for mcp server
  backend/app/service/mcp_server.go
  backend/constant/common.go
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/ai/mcp/server/config/index.vue
  frontend/src/views/ai/mcp/server/index.vue
  frontend/src/views/ai/mcp/server/operate/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#8334 fix: Fix the problem that the agent remembers the password invalid
  core/init/migration/migrations/init.go
  frontend/src/views/setting/panel/proxy/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8335 feat: change DNSTypes order
  frontend/src/global/mimetype.ts
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#8337 feat: remove env from mcp config
  frontend/src/views/ai/mcp/server/config/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#8338 style: update style for mcp server
  backend/app/service/mcp_server.go
  backend/app/service/website.go
  frontend/src/api/interface/ai.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/ai/mcp/server/operate/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#8342 fix: Modify database verification rules
  backend/app/service/cronjob.go
  frontend/src/views/database/mysql/bind/index.vue
  frontend/src/views/database/mysql/create/index.vue
  frontend/src/views/database/mysql/password/index.vue
  frontend/src/views/database/postgresql/bind/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#8344 feat: import mcp server support env
  frontend/src/views/ai/mcp/server/import/index.vue
  frontend/src/views/ai/mcp/server/operate/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#8345 fix: Improve the script library script content
  core/init/migration/helper/script.go
  core/init/migration/migrations/init.go
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8346 feat: add warn text for mcp server
  backend/app/service/mcp_server.go
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/ai/mcp/server/bind/index.vue
  frontend/src/views/ai/mcp/server/import/index.vue
  frontend/src/views/ai/mcp/server/index.vue
  frontend/src/views/ai/mcp/server/operate/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#8347 fix: Node switchover information Added the node mode
  frontend/src/layout/components/Sidebar/components/Collapse.vue
  frontend/src/views/login/components/login-form.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8348 feat: Unify the encapsulation of the component for 'service not exist'
  agent/app/api/v2/docker.go
  agent/app/dto/docker.go
  agent/app/service/docker.go
  frontend/src/api/interface/container.ts
  frontend/src/api/modules/container.ts
  frontend/src/components/layout-content/no-such-service.vue
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/zh-Hant.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/container/compose/index.vue
  frontend/src/views/container/container/index.vue
  frontend/src/views/container/dashboard/index.vue
  frontend/src/views/container/docker-status/index.vue
  frontend/src/views/container/image/index.vue
  frontend/src/views/container/network/index.vue
  frontend/src/views/container/repo/index.vue
  frontend/src/views/container/setting/index.vue
  frontend/src/views/container/template/index.vue
  frontend/src/views/container/volume/index.vue
  frontend/src/views/host/firewall/status/index.vue
  frontend/src/views/toolbox/clam/status/index.vue
  frontend/src/views/toolbox/fail2ban/index.vue
  frontend/src/views/toolbox/ftp/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8349 fix: fix bug with mcp-server status error
  backend/app/service/mcp_server.go
  backend/constant/runtime.go
  frontend/src/views/ai/mcp/server/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#8351 fix: Fix the problem of failed MySQL permission modification
  backend/app/service/cronjob_helper.go
  backend/utils/mysql/client/local.go
  backend/utils/mysql/client/remote.go
  frontend/src/views/cronjob/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#8352 change mcp helper
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#8353 fix: Fix the problem that jumping to a directory that does not exist …
  backend/app/api/v1/file.go
  backend/app/dto/request/file.go
  frontend/src/api/modules/files.ts
  frontend/src/components/upload/index.vue
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/host/file-management/move/index.vue
  frontend/src/views/setting/snapshot/import/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#8354 feat: Support user-defined description for backup
  agent/app/api/v2/backup.go
  agent/app/dto/backup.go
  agent/app/model/backup.go
  agent/app/repo/backup.go
  agent/app/service/backup_app.go
  agent/app/service/backup_mysql.go
  agent/app/service/backup_postgresql.go
  agent/app/service/backup_record.go
  agent/app/service/backup_redis.go
  agent/app/service/backup_website.go
  agent/app/service/device_clean.go
  agent/init/migration/migrations/init.go
  agent/router/backup.go
  frontend/src/api/modules/backup.ts
  frontend/src/components/backup/index.vue
  frontend/src/components/complex-table/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8355 feat: update allowPort check
  frontend/src/views/ai/mcp/server/operate/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#8356 fix: fix issue with mcp bind website
  backend/app/repo/group.go
  backend/app/service/mcp_server.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#8359 feat: Sync docker proxy to nodes
  core/constant/common.go
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/zh-Hant.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/setting/panel/index.vue
  frontend/src/views/setting/panel/proxy/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8361 feat(monitor): add websites list display for monitor
  core/init/router/router.go
  frontend/.env
  frontend/.env.development
  frontend/.env.production
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/zh-Hant.ts
  frontend/src/lang/modules/zh.ts
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8374 feat: update mcp proxy_pass
  backend/app/service/mcp_server.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#8371 feat: Support remote synchronization of script library scripts
  agent/utils/common/common.go
  core/app/api/v2/script_library.go
  core/app/model/script_library.go
  core/app/repo/script_library.go
  core/app/service/script_library.go
  core/app/service/upgrade.go
  core/app/task/task.go
  core/global/config.go
  core/go.mod
  core/i18n/lang/en.yaml
  core/i18n/lang/ja.yaml
  core/i18n/lang/ko.yaml
  core/i18n/lang/ms.yml
  core/i18n/lang/pt-BR.yaml
  core/i18n/lang/ru.yaml
  core/i18n/lang/zh-Hant.yaml
  core/i18n/lang/zh.yaml
  core/init/cron/cron.go
  core/init/cron/job/script.go
  core/init/migration/helper/script.go
  core/init/migration/migrate.go
  core/init/migration/migrations/init.go
  core/router/ro_script_library.go
  frontend/src/api/modules/cronjob.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/zh-Hant.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/utils/util.ts
  frontend/src/views/cronjob/library/index.vue
  frontend/src/views/setting/panel/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved

#8378 fix: Fix the mysql root account permission switchover exception
  backend/utils/mysql/client/local.go
  backend/utils/mysql/client/remote.go
  frontend/src/views/database/mysql/password/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#8379 fix(website): fix issue with create website with local php-fpm failed
  agent/app/repo/runtime.go
  agent/app/service/runtime.go
  agent/app/service/website_utils.go
  frontend/src/components/log/compose/index.vue
  frontend/src/components/log/file/index.vue
  frontend/src/utils/runtime.ts
  frontend/src/views/website/runtime/php/index.vue
  frontend/src/views/website/ssl/index.vue
  frontend/src/views/website/website/config/resource/nginx/index.vue
  frontend/src/views/website/website/create/index.vue
  frontend/src/views/website/website/index.vue
  frontend/src/views/website/website/nginx/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8398 feat: customize login page images and backgrounds
  frontend/src/assets/images/1panel-login-bg.jpg
  frontend/src/assets/images/1panel-login.jpg
  frontend/src/global/use-logo.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/zh-Hant.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/store/interface/index.ts
  frontend/src/utils/xpack.ts
  frontend/src/views/login/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8401 feat: Encapsulate command execution methods
  agent/app/api/v2/terminal.go
  agent/app/dto/cronjob.go
  agent/app/model/cronjob.go
  agent/app/service/ai.go
  agent/app/service/app_utils.go
  agent/app/service/backup_redis.go
  agent/app/service/backup_website.go
  agent/app/service/clam.go
  agent/app/service/container.go
  agent/app/service/cronjob_helper.go
  agent/app/service/dashboard.go
  agent/app/service/device.go
  agent/app/service/docker.go
  agent/app/service/firewall.go
  agent/app/service/host_tool.go
  agent/app/service/image_repo.go
  agent/app/service/nginx.go
  agent/app/service/nginx_utils.go
  agent/app/service/runtime.go
  agent/app/service/runtime_utils.go
  agent/app/service/snapshot.go
  agent/app/service/snapshot_create.go
  agent/app/service/snapshot_recover.go
  agent/app/service/ssh.go
  agent/app/service/website.go
  agent/app/service/website_ca.go
  agent/app/service/website_ssl.go
  agent/app/service/website_utils.go
  agent/init/migration/migrations/init.go
  agent/utils/ai_tools/gpu/gpu.go
  agent/utils/ai_tools/xpu/xpu.go
  agent/utils/cmd/cmd.go
  agent/utils/cmd/cmdx.go
  agent/utils/common/common.go
  agent/utils/compose/compose.go
  agent/utils/files/file_op.go
  agent/utils/files/tar.go
  agent/utils/files/tar_gz.go
  agent/utils/files/zip.go
  agent/utils/firewall/client/firewalld.go
  agent/utils/firewall/client/iptables.go
  agent/utils/firewall/client/ufw.go
  agent/utils/ntp/ntp.go
  agent/utils/toolbox/fail2ban.go
  agent/utils/toolbox/pure-ftpd.go
  agent/utils/xpack/xpack.go
  core/app/service/logs.go
  core/app/service/setting.go
  core/app/service/upgrade.go
  core/cmd/server/cmd/restore.go
  core/cmd/server/cmd/root.go
  core/cmd/server/cmd/update.go
  core/init/hook/hook.go
  core/init/lang/lang.go
  core/init/viper/viper.go
  core/utils/cmd/cmd.go
  core/utils/cmd/cmdx.go
  core/utils/common/common.go
  core/utils/files/files.go
  core/utils/firewall/firewall.go
Labels: do-not-merge/release-note-label-needed, dev-v2

#8403 feat: Modify the way of creating cronjob
  agent/app/api/v2/cronjob.go
  agent/app/dto/cronjob.go
  agent/app/service/cronjob.go
  agent/router/ro_cronjob.go
  agent/utils/cmd/cmdx.go
  core/utils/cmd/cmdx.go
  frontend/src/api/interface/cronjob.ts
  frontend/src/api/modules/cronjob.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/zh-Hant.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/routers/index.ts
  frontend/src/routers/modules/cronjob.ts
  frontend/src/utils/util.ts
  frontend/src/views/cronjob/cronjob/index.vue
  frontend/src/views/cronjob/cronjob/operate/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8407 feat: Add Node File Exchange
  agent/app/service/file.go
  agent/init/dir/dir.go
  agent/utils/files/fileinfo.go
  core/app/task/task.go
  core/i18n/lang/zh.yaml
  core/init/migration/helper/menu.go
  core/init/migration/migrations/init.go
  core/init/router/proxy.go
  core/utils/cmd/cmd.go
  core/utils/ssh/ssh.go
  frontend/src/api/interface/file.ts
  frontend/src/api/modules/files.ts
  frontend/src/api/modules/setting.ts
  frontend/src/components/log/container/index.vue
  frontend/src/components/log/task/index.vue
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/zh-Hant.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/host/file-management/delete/index.vue
  frontend/src/views/host/file-management/process/index.vue
  frontend/src/views/host/process/network/index.vue
  frontend/src/views/host/process/process/index.vue
  frontend/src/views/host/ssh/session/index.vue
Labels: do-not-merge/release-note-label-needed, dev-v2

#8408 style: Adjust the global interval style
  frontend/src/components/app-status/index.vue
  frontend/src/components/layout-content/index.vue
  frontend/src/layout/components/Sidebar/components/Logo.vue
  frontend/src/layout/components/Sidebar/index.scss
  frontend/src/layout/index.vue
  frontend/src/styles/common.scss
  frontend/src/views/ai/gpu/index.vue
  frontend/src/views/container/container/index.vue
  frontend/src/views/container/dashboard/index.vue
  frontend/src/views/container/setting/index.vue
  frontend/src/views/cronjob/cronjob/record/index.vue
  frontend/src/views/database/mysql/index.vue
  frontend/src/views/database/postgresql/index.vue
  frontend/src/views/database/redis/index.vue
  frontend/src/views/home/app/index.vue
  frontend/src/views/home/index.vue
  frontend/src/views/host/firewall/status/index.vue
  frontend/src/views/host/monitor/monitor/index.vue
  frontend/src/views/host/ssh/ssh/index.vue
  frontend/src/views/terminal/terminal/index.vue
  frontend/src/views/toolbox/clam/status/index.vue
  frontend/src/views/toolbox/fail2ban/index.vue
  frontend/src/views/toolbox/ftp/index.vue
  frontend/src/views/toolbox/supervisor/status/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8409 feat: Change the local connection mode of the terminal
  agent/app/api/v2/terminal.go
  agent/router/ro_host.go
  agent/utils/terminal/local_cmd.go
  core/app/service/host.go
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/zh-Hant.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/terminal/host/index.vue
  frontend/src/views/terminal/host/operate/index.vue
  frontend/src/views/terminal/terminal/host-create.vue
  frontend/src/views/terminal/terminal/index.vue
Labels: do-not-merge/release-note-label-needed, dev-v2

#8410 feat: Certificate list supports search by name and hides specified co…
  agent/app/dto/request/website_ssl.go
  agent/app/repo/website_ssl.go
  agent/app/service/app.go
  agent/app/service/website_ssl.go
  agent/i18n/lang/zh.yaml
  frontend/src/views/website/ssl/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8369 feat: basic support riscv64
  .goreleaser.yaml
  backend/app/service/snapshot.go
  backend/app/service/upgrade.go
Labels: do-not-merge/release-note-label-needed

#8380 feat(systemctl): 实现服务管理器初始化和命令执行
  Makefile
  backend/app/service/clam.go
  backend/app/service/device.go
  backend/app/service/device_clean.go
  backend/app/service/docker.go
  backend/app/service/host_tool.go
  backend/app/service/setting.go
  backend/app/service/snapshot_create.go
  backend/app/service/snapshot_recover.go
  backend/app/service/ssh.go
  backend/app/service/upgrade.go
  backend/utils/common/common.go
  backend/utils/systemctl/configloade.go
  backend/utils/systemctl/handle.go
  backend/utils/systemctl/managers.go
  backend/utils/systemctl/systemctl.go
  backend/utils/toolbox/fail2ban.go
  backend/utils/toolbox/pure-ftpd.go
  cmd/server/cmd/restore.go
Labels: do-not-merge/release-note-label-needed

#8412 feat: update golang.org/x/net version
  frontend/.gitignore
  go.mod
  go.sum
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#8413 feat: Supervisor supports automatic restart configuration.
  agent/app/dto/request/host_tool.go
  agent/app/dto/response/host_tool.go
  agent/app/service/host_tool.go
  agent/i18n/lang/zh.yaml
  frontend/src/api/interface/host-tool.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/zh-Hant.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/toolbox/supervisor/create/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8414 feat: Website list supports filtering by type.
  agent/app/dto/request/website.go
  agent/app/repo/website.go
  agent/app/service/website.go
  frontend/src/global/mimetype.ts
  frontend/src/views/website/website/create/index.vue
  frontend/src/views/website/website/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8415 fix: Modify the terminal connection method
  agent/app/api/v2/setting.go
  agent/app/api/v2/terminal.go
  agent/app/dto/setting.go
  agent/app/dto/ssh.go
  agent/app/service/setting.go
  agent/app/service/ssh.go
  agent/app/task/task.go
  agent/global/config.go
  agent/init/dir/dir.go
  agent/init/migration/migrate.go
  agent/init/migration/migrations/init.go
  agent/router/ro_host.go
  agent/router/ro_setting.go
  agent/utils/ssh/ssh.go
  agent/utils/terminal/ws_session.go
  frontend/src/api/interface/host.ts
  frontend/src/api/modules/terminal.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/zh-Hant.ts
  frontend/src/views/terminal/terminal/host-create.vue
  frontend/src/views/terminal/terminal/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8419 feat: When creating files/folders, use the parent directory's user an…
  agent/app/service/file.go
  agent/app/service/website_utils.go
  core/app/api/v2/backup.go
  core/app/api/v2/command.go
  core/app/api/v2/group.go
  core/app/api/v2/helper/helper.go
  core/app/api/v2/host.go
  core/app/api/v2/logs.go
  core/app/api/v2/script_library.go
  core/app/api/v2/setting.go
  core/app/api/v2/upgrade.go
  core/init/router/proxy.go
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/zh-Hant.ts
  frontend/src/lang/modules/zh.ts
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8422 chore: Update README.md
  README.md
Labels: do-not-merge/release-note-label-needed, dev

#8423 chore: Update README.md
  README.md
Labels: do-not-merge/release-note-label-needed

#8424 chore: Update README.md
  README.md
Labels: do-not-merge/release-note-label-needed

#8426 chore: Update README.md
  README.md
Labels: do-not-merge/release-note-label-needed

#8436 style: Optimize page styles.
  frontend/src/views/app-store/apps/index.vue
  frontend/src/views/app-store/installed/index.vue
  frontend/src/views/host/file-management/index.vue
  frontend/src/views/host/process/network/index.vue
  frontend/src/views/host/process/process/index.vue
  frontend/src/views/host/ssh/ssh/index.vue
  frontend/src/views/website/runtime/dotnet/index.vue
  frontend/src/views/website/runtime/go/index.vue
  frontend/src/views/website/runtime/java/index.vue
  frontend/src/views/website/runtime/node/index.vue
  frontend/src/views/website/runtime/php/index.vue
  frontend/src/views/website/runtime/python/index.vue
  frontend/src/views/website/ssl/index.vue
  frontend/src/views/website/website/config/index.vue
  frontend/src/views/website/website/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8437 feat: Applications support setting a description field.
  agent/app/dto/app.go
  frontend/src/api/interface/app.ts
  frontend/src/utils/util.ts
  frontend/src/views/app-store/detail/params/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8440 feat: Application installation supports limiting port binding to a sp…
  agent/app/dto/request/app.go
  agent/app/service/app_utils.go
  frontend/src/api/interface/app.ts
  frontend/src/global/form-rules.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/zh-Hant.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/app-store/detail/install/index.vue
  frontend/src/views/app-store/installed/detail/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8444 Fix issue with errors when reverse proxy source text includes comments.
  backend/app/service/website.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#8450 fix(app): Fix issue with leading zero parameter loss in applications.
  agent/utils/env/env.go
  frontend/src/components/complex-table/index.vue
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/zh-Hant.ts
  frontend/src/lang/modules/zh.ts
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8457 feat: Improve the license binding logic
  core/i18n/lang/en.yaml
  core/i18n/lang/ja.yaml
  core/i18n/lang/ko.yaml
  core/i18n/lang/ms.yml
  core/i18n/lang/pt-BR.yaml
  core/i18n/lang/ru.yaml
  core/i18n/lang/zh-Hant.yaml
  core/i18n/lang/zh.yaml
  frontend/src/api/interface/setting.ts
  frontend/src/api/modules/setting.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/zh-Hant.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/layout/components/Sidebar/components/Collapse.vue
  frontend/src/views/setting/license/bind/free.vue
  frontend/src/views/setting/license/bind/xpack.vue
  frontend/src/views/setting/license/index.vue
  frontend/src/views/terminal/terminal/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8460 fix(app): Applications support single quotes in env files.
  agent/app/model/website_ssl.go
  agent/app/service/app_utils.go
  agent/app/service/website_acme_account.go
  agent/app/service/website_ssl.go
  agent/init/migration/migrate.go
  agent/init/migration/migrations/init.go
  agent/utils/env/env.go
  agent/utils/ssl/acme.go
  agent/utils/ssl/client.go
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8462 fix(website): Add pinning feature for websites.
  agent/app/dto/request/website.go
  agent/app/dto/response/website.go
  agent/app/model/website.go
  agent/app/service/website.go
  agent/init/migration/migrate.go
  agent/init/migration/migrations/init.go
  frontend/src/api/interface/website.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/zh-Hant.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/website/website/index.vue
Labels: do-not-merge/release-note-label-needed, approved, dev-v2

#8416 WIP: refactor(service): Refactor OpenRC service manager
  backend/app/service/snapshot_create.go
  backend/app/service/snapshot_recover.go
  backend/app/service/ssh.go
  backend/app/service/upgrade.go
  backend/utils/systemctl/managers.go
  backend/utils/toolbox/fail2ban.go
Labels: do-not-merge/release-note-label-needed, do-not-merge/work-in-progress

#8467 fix: Improve the node synchronization logic
  agent/app/api/v2/backup.go
  agent/app/service/backup.go
  agent/router/backup.go
  core/app/service/backup.go
  core/constant/common.go
  core/i18n/lang/en.yaml
  core/i18n/lang/ja.yaml
  core/i18n/lang/ko.yaml
  core/i18n/lang/ms.yml
  core/i18n/lang/pt-BR.yaml
  core/i18n/lang/ru.yaml
  core/i18n/lang/zh-Hant.yaml
  core/i18n/lang/zh.yaml
  core/init/cron/job/backup.go
  core/utils/xpack/xpack.go
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/zh-Hant.ts
  frontend/src/lang/modules/zh.ts
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8471 style: Optimize the node switching style
  frontend/src/components/system-upgrade/index.vue
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/zh-Hant.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/layout/components/Sidebar/components/Collapse.vue
  frontend/src/views/setting/backup-account/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8473 fix: Modify the node synchronization description information
  core/app/service/setting.go
  core/i18n/lang/en.yaml
  core/i18n/lang/ja.yaml
  core/i18n/lang/ko.yaml
  core/i18n/lang/ms.yml
  core/i18n/lang/pt-BR.yaml
  core/i18n/lang/ru.yaml
  core/i18n/lang/zh-Hant.yaml
  core/i18n/lang/zh.yaml
  frontend/src/lang/modules/zh-Hant.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/terminal/terminal/index.vue
Labels: do-not-merge/release-note-label-needed, dev-v2

#8474 fix(editor): reset edit state after not saving content
  frontend/src/views/host/file-management/code-editor/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm

#8476 chore: Update README.md
  README.md
Labels: do-not-merge/release-note-label-needed

#8475 feat(website): Certificate application supports custom ACME addresses.
  agent/app/dto/request/website_ssl.go
  agent/app/model/website_acme_account.go
  agent/app/service/website_acme_account.go
  agent/app/service/website_ssl.go
  agent/init/migration/migrations/init.go
  agent/utils/ssl/acme.go
  frontend/src/global/mimetype.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/zh-Hant.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/website/ssl/acme-account/create/index.vue
Labels: do-not-merge/release-note-label-needed, dev-v2

#8477 feat(app): Add a favorite feature for installed applications
  agent/app/dto/request/app.go
  agent/app/dto/response/app.go
  agent/app/model/app_install.go
  agent/app/service/app_install.go
  agent/app/service/app_utils.go
  agent/constant/app.go
  agent/init/migration/migrate.go
  agent/init/migration/migrations/init.go
  frontend/src/api/interface/app.ts
  frontend/src/views/app-store/installed/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8480 feat: Complete the Docker proxy synchronization function
  core/app/dto/setting.go
  core/app/service/setting.go
  core/constant/common.go
  core/utils/xpack/xpack.go
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/zh-Hant.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/setting/panel/proxy/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8485 feat(ssl): add vercel dns provider
  agent/utils/ssl/acme.go
  agent/utils/ssl/client.go
  frontend/src/global/mimetype.ts
  frontend/src/views/website/ssl/dns-account/create/index.vue
Labels: do-not-merge/release-note-label-needed, dev-v2

#8487 fix: Fix the problem of abnormal system version detection
  frontend/src/components/system-upgrade/index.vue
  frontend/src/views/setting/license/bind/free.vue
  frontend/src/views/setting/license/bind/xpack.vue
  frontend/src/views/setting/snapshot/create/index.vue
  frontend/src/views/setting/snapshot/recover/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8488 feat: Hide the favorites button for installed items.
  frontend/src/views/app-store/installed/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8489 feat: refreshTask when open task log
  core/constant/common.go
  frontend/src/components/task-list/index.vue
  frontend/src/views/log/task/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8490 feat: Remove drawer exit prompt.
  frontend/src/components/drawer-pro/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8491 feat: handle exist env file for app install
  agent/app/service/app_utils.go
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8493 fix: Fix the problem of abnormal terminal connection
  core/init/migration/migrations/init.go
  core/utils/terminal/local_cmd.go
  frontend/src/components/terminal/index.vue
  frontend/src/views/container/container/index.vue
  frontend/src/views/cronjob/library/index.vue
  frontend/src/views/cronjob/library/operate/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8481 fix(cronjob): prevent unnecessary log updates and clean log formatting
  frontend/src/views/cronjob/record/index.vue
Labels: do-not-merge/release-note-label-needed

#8495 fix: Modify the license import method
  frontend/src/components/license-import/index.vue
  frontend/src/components/system-upgrade/index.vue
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/zh-Hant.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/layout/components/Sidebar/components/Collapse.vue
  frontend/src/layout/index.vue
  frontend/src/store/modules/global.ts
  frontend/src/views/setting/license/bind/free.vue
  frontend/src/views/setting/license/bind/xpack.vue
  frontend/src/views/setting/license/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8496 fix: Fix the problem of abnormal script execution
  core/app/api/v2/script_library.go
  frontend/src/views/cronjob/library/operate/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8497 feat: Login page style optimization
  frontend/src/views/login/components/login-form.vue
  frontend/src/views/login/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8499 feat: merge mcp server from dev
  agent/app/api/v2/entry.go
  agent/app/api/v2/mcp_server.go
  agent/app/dto/request/mcp_server.go
  agent/app/dto/request/website.go
  agent/app/dto/response/mcp_server.go
  agent/app/model/mcp_server.go
  agent/app/repo/group.go
  agent/app/repo/mcp_server.go
  agent/app/service/app.go
  agent/app/service/entry.go
  agent/app/service/mcp_server.go
  agent/app/service/website.go
  agent/cmd/server/mcp/compose.yml
  agent/cmd/server/mcp/mcp.go
  agent/cmd/server/nginx_conf/nginx_conf.go
  agent/cmd/server/nginx_conf/sse.conf
  agent/global/config.go
  agent/i18n/lang/en.yaml
  agent/i18n/lang/ja.yaml
  agent/i18n/lang/ko.yaml
  agent/i18n/lang/ms.yaml
  agent/i18n/lang/pt-BR.yaml
  agent/i18n/lang/ru.yaml
  agent/i18n/lang/zh-Hant.yaml
  agent/i18n/lang/zh.yaml
  agent/init/dir/dir.go
  agent/init/migration/migrate.go
  agent/init/migration/migrations/init.go
  agent/router/ro_ai.go
  core/constant/common.go
  core/init/migration/helper/menu.go
  core/init/migration/migrations/init.go
  frontend/src/api/interface/ai.ts
  frontend/src/api/modules/ai.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/zh-Hant.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/routers/modules/ai.ts
  frontend/src/views/ai/mcp/index.vue
  frontend/src/views/ai/mcp/server/bind/index.vue
  frontend/src/views/ai/mcp/server/config/index.vue
  frontend/src/views/ai/mcp/server/import/index.vue
  frontend/src/views/ai/mcp/server/index.vue
  frontend/src/views/ai/mcp/server/operate/index.vue
  frontend/src/views/ai/mcp/server/volume/index.vue
  frontend/src/views/website/website/create/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8501 feat: add spaceship dns provider
  agent/utils/ssl/client.go
  frontend/src/global/mimetype.ts
  frontend/src/views/website/ssl/dns-account/create/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8503 fix: Fix the problem of abnormal menu display and hide switching
  agent/app/api/v2/database_postgresql.go
  agent/app/dto/setting.go
  agent/utils/postgresql/client/remote.go
  core/cmd/server/docs/docs.go
  core/cmd/server/docs/swagger.json
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/zh-Hant.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/setting/panel/hidemenu/index.vue
  frontend/src/views/setting/panel/index.vue
  frontend/src/views/setting/panel/systemip/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8504 feat: merge code from dev
  agent/go.mod
  agent/go.sum
  agent/init/migration/migrations/init.go
  agent/utils/ssl/client.go
  core/app/api/v2/auth.go
  frontend/src/global/mimetype.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/zh-Hant.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/app-store/index.vue
  frontend/src/views/website/ssl/dns-account/create/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8506 fix: Fix the problem of abnormal display of license import
  frontend/src/components/license-import/index.vue
  frontend/src/layout/components/Sidebar/components/Collapse.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8512 fix: Fix the problem of abnormal recovery of the application state
  agent/app/service/snapshot_create.go
  core/app/service/upgrade.go
Labels: do-not-merge/release-note-label-needed, dev-v2

#8510 fix: Fix the problem of abnormal script execution
  core/app/service/upgrade.go
  core/i18n/lang/en.yaml
  core/i18n/lang/ja.yaml
  core/i18n/lang/ko.yaml
  core/i18n/lang/ms.yml
  core/i18n/lang/pt-BR.yaml
  core/i18n/lang/ru.yaml
  core/i18n/lang/zh-Hant.yaml
  core/i18n/lang/zh.yaml
  core/utils/terminal/local_cmd.go
  core/utils/terminal/ws_session.go
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/zh-Hant.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/layout/components/Sidebar/components/Collapse.vue
  frontend/src/routers/modules/ai.ts
  frontend/src/views/cronjob/library/index.vue
  frontend/src/views/cronjob/library/operate/index.vue
  frontend/src/views/setting/snapshot/create/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8514 fix: Fix the problem of abnormal container port jumps
  agent/app/service/device_clean.go
  core/i18n/lang/en.yaml
  core/i18n/lang/ja.yaml
  core/i18n/lang/ko.yaml
  core/i18n/lang/ms.yml
  core/i18n/lang/pt-BR.yaml
  core/i18n/lang/ru.yaml
  core/i18n/lang/zh-Hant.yaml
  core/i18n/lang/zh.yaml
  frontend/src/components/port-jump/index.vue
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/zh-Hant.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/setting/panel/index.vue
  frontend/src/views/toolbox/clean/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8516 feat: apply acme account use proxy
  agent/app/service/app.go
  agent/init/business/business.go
  core/app/service/auth.go
  frontend/src/api/interface/setting.ts
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8517 fix: Fix the problem of abnormal operation of the script library
  core/app/api/v2/script_library.go
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8522 fix: Fix the problem of abnormal logs when error reports occur during…
  agent/app/repo/cronjob.go
  agent/app/service/cronjob_helper.go
  core/server/server.go
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8524 feat: add config for appstore
  agent/app/api/v2/setting.go
  agent/app/dto/request/app.go
  agent/app/dto/response/app.go
  agent/app/repo/setting.go
  agent/app/service/app.go
  agent/app/service/setting.go
  agent/i18n/i18n.go
  agent/router/ro_setting.go
  core/i18n/i18n.go
  core/server/server.go
  frontend/src/api/interface/app.ts
  frontend/src/api/modules/app.ts
  frontend/src/api/modules/setting.ts
  frontend/src/components/task-list/index.vue
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/zh-Hant.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/app-store/index.vue
  frontend/src/views/app-store/installed/delete/index.vue
  frontend/src/views/app-store/installed/detail/index.vue
  frontend/src/views/app-store/installed/index.vue
  frontend/src/views/app-store/installed/upgrade/index.vue
  frontend/src/views/app-store/setting/default-domain/index.vue
  frontend/src/views/app-store/setting/index.vue
  frontend/src/views/setting/panel/api-interface/index.vue
  frontend/src/views/website/website/create/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8525 feat: sync appstore use proxy
  agent/app/service/app.go
  agent/utils/files/utils.go
  agent/utils/req_helper/request.go
  agent/utils/xpack/xpack.go
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2
