Repository 1Panel-dev/1Panel, pull requests merged in 2025-07, with the labels that each got.

#9354 fix: Implement chunked upload for google drive file transfers
  agent/utils/cloud_storage/client/google_drive.go
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#9355 fix: Optimize 1pctl restore command output
  core/cmd/server/cmd/restore.go
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#9358 fix: Optimize backup account switching logic
  frontend/src/views/container/container/index.vue
  frontend/src/views/cronjob/cronjob/operate/index.vue
  frontend/src/views/home/index.vue
  frontend/src/views/home/status/index.vue
  frontend/src/views/setting/snapshot/create/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#9361 fix: Resolve the issue of database uninstallation failure
  agent/app/service/app_install.go
  agent/app/service/app_utils.go
Labels: do-not-merge/release-note-label-needed, dev-v2

#9363 fix: Support configurable docker config file snapshotting
  agent/app/dto/snapshot.go
  agent/app/model/snapshot.go
  agent/app/service/snapshot.go
  agent/app/service/snapshot_create.go
  agent/app/service/snapshot_recover.go
  agent/app/service/snapshot_rollback.go
  agent/init/migration/migrations/init.go
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/zh-Hant.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/cronjob/cronjob/record/index.vue
  frontend/src/views/setting/snapshot/create/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#9364 fix: Update backup account documentation links
  frontend/src/views/setting/backup-account/operate/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#9369 fix: Resolve the php runtime start failed
  agent/app/service/runtime_utils.go
  agent/app/service/website_utils.go
  agent/cmd/server/nginx_conf/php-fpm.conf
  agent/init/migration/migrations/init.go
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#9378 style: Fix the problem where dropdown text is too long to display properly.
  frontend/src/views/website/ssl/create/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#9387 fix: Fixed issue with build core failed
  core/constant/common.go
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#9392 style: Add more pagination options to table
  frontend/src/components/complex-table/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#9395 fix: Fix user settings loading failure after reinstallation
  core/init/hook/hook.go
  core/init/migration/migrations/init.go
Labels: do-not-merge/release-note-label-needed, dev-v2

#9399 fix: Fix system load spike during disk mount failures
  agent/app/service/dashboard.go
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#9401 fix: Fix the problem of re-logging during the snapshot recovery process
  agent/app/service/snapshot_create.go
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#9402 fix: Fix snap docker startup failure due to empty configuration
  agent/app/service/docker.go
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#9403 fix: Modify OneDrive default connection settings
  core/init/migration/migrate.go
  core/init/migration/migrations/init.go
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#9429 fix: Fix dashboard refresh exception issue
  frontend/src/views/home/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#9430 feat: add DownloadCallBack for install php runtime
  agent/app/service/runtime_utils.go
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#9432 fix: Fix timezone modification reboot exception
  agent/app/service/device.go
  frontend/src/views/toolbox/device/time-zone/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#9435 Fix: Resolved issue where domain binding failed in MCP due to OpenResty not using 80 port
  agent/app/service/mcp_server.go
  agent/app/service/website_utils.go
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#9437 fix: Add rule validation for FTP account creation
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/zh-Hant.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/utils/util.ts
  frontend/src/views/toolbox/ftp/operate/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#9440 fix: Modify OneDrive default connection settings
  backend/init/migration/migrate.go
  backend/init/migration/migrations/v_1_10.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#9441 Fix: fix issue with element-plus tab style wrong
  frontend/package.json
Labels: do-not-merge/release-note-label-needed, dev-v2

#9455 fix: Fix dashboard refresh exception issue
  backend/init/migration/migrations/v_1_10.go
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/home/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#9462 fix: Change container image building to asynchronous operation
  agent/app/dto/container.go
  agent/app/service/container.go
  agent/app/service/image_repo.go
  agent/app/task/task.go
  agent/i18n/lang/en.yaml
  agent/i18n/lang/ja.yaml
  agent/i18n/lang/ko.yaml
  agent/i18n/lang/ms.yaml
  agent/i18n/lang/pt-BR.yaml
  agent/i18n/lang/ru.yaml
  agent/i18n/lang/tr.yaml
  agent/i18n/lang/zh-Hant.yaml
  agent/i18n/lang/zh.yaml
  frontend/src/api/interface/container.ts
  frontend/src/views/container/container/commit/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#9468 fix: Fix the issue where the demo configuration takes effect
  agent/cmd/server/conf/app.yaml
  agent/init/viper/viper.go
  core/app/api/v2/host.go
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#9474 fix: Fix the issue of calculating size incorrectly during sorting
  frontend/src/views/host/file-management/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#9479 fix: Fix container log download ANSI control code garbled issue
  agent/app/service/container.go
Labels: do-not-merge/release-note-label-needed, lgtm, dev-v2

#9505 feat: Add MySQL master-slave installation feature
  agent/app/api/v2/app_install.go
  agent/app/dto/response/app.go
  agent/app/service/app_install.go
  agent/app/service/app_utils.go
  agent/router/ro_app.go
  core/app/task/task.go
  core/constant/common.go
  core/constant/status.go
  core/init/migration/helper/menu.go
  core/init/migration/migrate.go
  core/init/migration/migrations/init.go
  frontend/package.json
  frontend/src/api/interface/app.ts
  frontend/src/api/modules/app.ts
  frontend/src/api/modules/setting.ts
  frontend/src/components/log/compose/index.vue
  frontend/src/components/log/container/index.vue
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/tr.ts
  frontend/src/lang/modules/zh-Hant.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/utils/app.ts
  frontend/src/views/app-store/apps/index.vue
  frontend/src/views/app-store/detail/index.vue
  frontend/src/views/home/app/index.vue
Labels: do-not-merge/release-note-label-needed, dev-v2

#9507 fix: Modify the header of the application logs page
  frontend/src/components/log/compose/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#9510 feat: Optimize node management logic
  agent/app/repo/app_install.go
  agent/app/service/app_utils.go
  frontend/src/assets/iconfont/iconfont.css
  frontend/src/assets/iconfont/iconfont.js
  frontend/src/assets/iconfont/iconfont.json
  frontend/src/assets/iconfont/iconfont.svg
  frontend/src/assets/iconfont/iconfont.ttf
  frontend/src/assets/iconfont/iconfont.woff
  frontend/src/assets/iconfont/iconfont.woff2
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/tr.ts
  frontend/src/lang/modules/zh-Hant.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/database/mysql/index.vue
Labels: do-not-merge/release-note-label-needed, dev-v2

#9519 fix: Resolve the issue of failed slave installation
  agent/app/dto/response/app.go
  agent/app/service/app_install.go
  core/i18n/lang/en.yaml
  core/i18n/lang/ja.yaml
  core/i18n/lang/ko.yaml
  core/i18n/lang/ms.yml
  core/i18n/lang/pt-BR.yaml
  core/i18n/lang/ru.yaml
  core/i18n/lang/tr.yaml
  core/i18n/lang/zh-Hant.yaml
  core/i18n/lang/zh.yaml
  frontend/src/api/modules/app.ts
  frontend/src/composables/useGlobalStore.ts
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#9530 fix: Fix memory usage display issue on dashboard
  agent/app/dto/dashboard.go
  agent/app/service/dashboard.go
  frontend/src/api/interface/dashboard.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/tr.ts
  frontend/src/lang/modules/zh-Hant.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/home/status/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#9531 feat: Application installation supports existing remote databases
  agent/app/service/app_utils.go
Labels: do-not-merge/release-note-label-needed, dev-v2

#9532 feat: Remove the required field prompt for HSTS in the website HTTPS …
  frontend/src/views/website/website/config/basic/https/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#9535 fix: Fix the issue where some applications incorrectly displayed a redirect button on error
  frontend/src/views/app-store/installed/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#9537 feat: Add customizable snapshot timeout support
  agent/app/dto/snapshot.go
  agent/app/model/snapshot.go
  agent/app/service/snapshot_create.go
  agent/app/service/snapshot_recover.go
  agent/init/migration/migrations/init.go
  frontend/src/api/interface/setting.ts
  frontend/src/views/setting/snapshot/create/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#9548 fix: Fix the problem of abnormal request forwarding
  agent/middleware/certificate.go
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#9552 fix: Fix log printing issues caused by container log tracking switches
  core/init/router/proxy.go
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#9560 style: Optimize node switching transition effects
  frontend/src/layout/components/Sidebar/components/Collapse.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#9562 fix: Fixed issue with install Mailserver failed
  agent/app/service/app_utils.go
  agent/utils/docker/compose.go
  frontend/src/components/status/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#9571 feat: Dealing with compatibility issues with alert history data
  core/init/migration/helper/menu.go
  core/init/migration/migrate.go
  core/init/migration/migrations/init.go
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/tr.ts
  frontend/src/lang/modules/zh-Hant.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/setting/alert/setting/email/index.vue
  frontend/src/views/setting/alert/setting/index.vue
Labels: do-not-merge/release-note-label-needed, dev-v2

#9578 fix: Fix DNS configuration editing issue for containers
  frontend/src/views/container/container/operate/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#9579 fix: Optimize snapshot synchronization options
  frontend/src/views/setting/snapshot/import/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#9581 fix: fix some bugs with app-cluster
  agent/app/service/app_install.go
  agent/app/service/container.go
  agent/go.mod
  agent/go.sum
  agent/utils/docker/docker.go
  core/go.mod
  core/go.sum
  frontend/src/api/modules/container.ts
  frontend/src/components/log/container/index.vue
  frontend/src/views/database/redis/index.vue
  frontend/src/views/database/redis/setting/status/index.vue
Labels: do-not-merge/release-note-label-needed, dev-v2

#9582 feat: Optimize node addition notification messages
  core/constant/status.go
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/tr.ts
  frontend/src/lang/modules/zh-Hant.ts
  frontend/src/lang/modules/zh.ts
Labels: do-not-merge/release-note-label-needed, dev-v2

#9585 fix: Fix data synchronization during backup account modification
  agent/app/service/backup.go
  frontend/src/api/modules/backup.ts
Labels: do-not-merge/release-note-label-needed, dev-v2

#9589 fix: Fix the issue where remote databases cannot be selected during a…
  agent/app/service/app_utils.go
Labels: do-not-merge/release-note-label-needed, lgtm, dev-v2

#9587 fix: Fix overview page load metrics localization issues
  frontend/src/views/home/status/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#9590 fix: Fix container edit task log abnormalities
  agent/app/service/container.go
  frontend/src/views/container/container/operate/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#9591 fix: Improve alert notifications
  agent/app/service/cronjob_helper.go
  frontend/src/views/setting/alert/dash/task/index.vue
  frontend/src/views/setting/alert/setting/email/index.vue
  frontend/src/views/setting/alert/setting/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#9597 fix: Change container creation to asynchronous operation
  agent/app/api/v2/container.go
  agent/app/service/container.go
  agent/app/service/database_redis.go
Labels: do-not-merge/release-note-label-needed, lgtm, dev-v2

#9598 feat: Application installation supports using existing remote databases
  agent/app/dto/app.go
  agent/app/service/app.go
  agent/app/service/app_utils.go
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#9599 fix: Fix node state synchronization issues
  frontend/src/layout/components/Sidebar/components/Collapse.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#9603 fix: Resolve backup to server disk failure for cronjob
  agent/app/service/cronjob_backup.go
  agent/app/service/cronjob_helper.go
Labels: do-not-merge/release-note-label-needed, dev-v2

#9605 fix: Fix some issues with the alert
  agent/app/service/alert_helper.go
  frontend/src/routers/index.ts
  frontend/src/views/setting/alert/dash/task/index.vue
  frontend/src/views/setting/alert/log/index.vue
  frontend/src/views/setting/alert/setting/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#9608 fix: Fix offline alert issue
  agent/app/repo/alert.go
  frontend/src/api/modules/alert.ts
  frontend/src/views/setting/alert/log/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#9611 fix: Fix the issue where application labels are displayed incorrectly…
  agent/app/service/app_utils.go
  agent/i18n/lang/en.yaml
  agent/i18n/lang/ja.yaml
  agent/i18n/lang/ko.yaml
  agent/i18n/lang/ms.yaml
  agent/i18n/lang/pt-BR.yaml
  agent/i18n/lang/ru.yaml
  agent/i18n/lang/tr.yaml
  agent/i18n/lang/zh-Hant.yaml
  agent/i18n/lang/zh.yaml
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#9615 fix: Fix the issue where an error occurs on the runtime environment page when Docker is not installed.
  agent/app/service/runtime.go
Labels: do-not-merge/release-note-label-needed, dev-v2

#9641 fix: Fix node switching style issues
  frontend/src/layout/components/Sidebar/components/Collapse.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#9669 fix: Optimize filename generation for directory backup
  agent/app/service/cronjob.go
  agent/app/service/cronjob_backup.go
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#9670 fix: Fixed Changing the runtime container name may cause it to fail to start
  agent/app/service/runtime.go
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#9672 fix: Fixed issue with create website with openresty defaultHttpsPort
  agent/app/service/website.go
  agent/app/service/website_utils.go
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#9671 feat: Customize login page buttons and link colors
  frontend/src/global/use-logo.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/tr.ts
  frontend/src/lang/modules/zh-Hant.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/store/interface/index.ts
  frontend/src/store/modules/global.ts
  frontend/src/styles/element-dark.scss
  frontend/src/utils/xpack.ts
  frontend/src/views/login/components/login-form.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#9673 fix: Add lightweight object storage compatibility for COS backup acco…
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/tr.ts
  frontend/src/lang/modules/zh-Hant.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/setting/backup-account/operate/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#9698 fix: Resolve certificate validate failure Issues
  agent/middleware/certificate.go
  agent/server/server.go
  agent/utils/xpack/xpack.go
Labels: do-not-merge/release-note-label-needed, dev-v2

#9697 Fix Issue with Podman Unable to Create PHP Runtime Website
  agent/app/service/container.go
  agent/app/service/website.go
Labels: do-not-merge/release-note-label-needed

#9700 fix: Fix port forwarding error issues
  agent/utils/firewall/client/iptables.go
  agent/utils/firewall/client/ufw.go
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#9702 fix: add nil checks for transport.DialContext
  agent/utils/email/smtp_sender.go
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#9704 fix: Optimize task log tracking mechanism
  agent/app/dto/response/file.go
  agent/app/service/file.go
  frontend/src/components/log/file/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, dev-v2

#9710 fix: Add file upload restrictions for cronjob
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/tr.ts
  frontend/src/lang/modules/zh-Hant.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/cronjob/cronjob/import/index.vue
  frontend/src/views/host/ssh/index.vue
Labels: dev-v2

#9713 fix: script-type scheduled task import/export issues
  agent/app/service/cronjob.go
Labels: dev-v2

#9727 fix: Fix import failures for cronjob
  agent/app/dto/cronjob.go
  agent/app/service/cronjob.go
  frontend/src/api/interface/cronjob.ts
  frontend/src/views/cronjob/cronjob/index.vue
  frontend/src/views/cronjob/cronjob/operate/index.vue
  frontend/src/views/cronjob/cronjob/record/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, dev-v2

#9728 fix: Fix execution refresh issues for cronjob
  frontend/src/views/cronjob/cronjob/record/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#9732 fix: Fixed issue with recover postgres-cluster database failed
  agent/utils/postgresql/client/local.go
  frontend/src/components/drawer-pro/index.vue
  frontend/src/views/app-store/installed/upgrade/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, dev-v2

#9703 feat: Add HTTPS fallback prevention configuration in OpenResty
  agent/app/api/v2/nginx.go
  agent/app/dto/request/nginx.go
  agent/app/dto/response/nginx.go
  agent/app/service/nginx.go
  agent/router/ro_nginx.go
  frontend/src/api/interface/nginx.ts
  frontend/src/api/modules/nginx.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/tr.ts
  frontend/src/lang/modules/zh-Hant.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/website/website/nginx/index.vue
  frontend/src/views/website/website/nginx/other/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#9734 fix: Resolve the issue of ignoring MySQL failures
  agent/app/dto/response/app_ignore_upgrade.go
  agent/app/service/app_ingore_upgrade.go
  agent/app/service/app_utils.go
  frontend/src/api/interface/app.ts
  frontend/src/views/app-store/installed/ignore/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#9753 feat: Restrict deletion of certificates that are being applied for.
  agent/app/service/website_ssl.go
  agent/i18n/lang/en.yaml
  agent/i18n/lang/ja.yaml
  agent/i18n/lang/ko.yaml
  agent/i18n/lang/ms.yaml
  agent/i18n/lang/pt-BR.yaml
  agent/i18n/lang/ru.yaml
  agent/i18n/lang/tr.yaml
  agent/i18n/lang/zh-Hant.yaml
  agent/i18n/lang/zh.yaml
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#9755 perf: Optimize website log reading
  agent/app/dto/response/file.go
  agent/app/service/file.go
  agent/utils/files/utils.go
  frontend/src/components/log/file/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#9761 feat: Mcp Server support streamableHttp
  agent/app/dto/request/mcp_server.go
  agent/app/model/mcp_server.go
  agent/app/service/mcp_server.go
  agent/cmd/server/mcp/compose.yml
  agent/init/migration/migrate.go
  agent/init/migration/migrations/init.go
  agent/utils/docker/docker.go
  frontend/src/api/interface/ai.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/tr.ts
  frontend/src/lang/modules/zh-Hant.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/ai/mcp/server/operate/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#9772 fix: Fix the issue where updating the image in the Compose file during upgrade has no effect
  agent/app/service/app_utils.go
Labels: do-not-merge/release-note-label-needed, dev-v2

#9774 fix: Fixed issue where syncing remote apps causes local app tags to be lost
  agent/app/repo/app_tag.go
  agent/app/repo/tag.go
  agent/app/service/app.go
  agent/app/service/app_utils.go
Labels: do-not-merge/release-note-label-needed, dev-v2

#9775 Fix the issue where certificate deletion fails due to network issues
  agent/app/service/website_ssl.go
Labels: do-not-merge/release-note-label-needed, dev-v2

#9779 feat: upgrade github.com/docker/docker version to v28.3.3
  agent/go.mod
  agent/go.sum
Labels: do-not-merge/release-note-label-needed, dev-v2
