Repository 1Panel-dev/1Panel, pull requests merged in 2025-06, with the labels that each got.

#8895 fix: Node creation adds geo ip initialization
  agent/init/lang/lang.go
  agent/server/server.go
Labels: do-not-merge/release-note-label-needed, dev-v2

#8896 fix: Fix the problem of unfiltered types in the backup database of cr…
  agent/app/service/cronjob_backup.go
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8898 fix: Fix the problem of failed creation of child node snapshots
  agent/app/service/snapshot_create.go
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8900 fix: fix issue with clean runtime lop failed
  agent/app/dto/response/app.go
  agent/app/dto/response/runtime.go
  agent/app/service/app_utils.go
  frontend/src/api/interface/runtime.ts
  frontend/src/components/log/compose/index.vue
  frontend/src/components/log/container/index.vue
  frontend/src/views/ai/mcp/server/index.vue
  frontend/src/views/app-store/installed/index.vue
  frontend/src/views/website/runtime/dotnet/index.vue
  frontend/src/views/website/runtime/go/index.vue
  frontend/src/views/website/runtime/java/index.vue
  frontend/src/views/website/runtime/node/index.vue
  frontend/src/views/website/runtime/php/index.vue
  frontend/src/views/website/runtime/python/index.vue
Labels: do-not-merge/release-note-label-needed, dev-v2

#8910 feat: Move current status to first position in MySQL and Redis settings and set as default tab
  frontend/src/views/database/mysql/setting/index.vue
  frontend/src/views/database/redis/setting/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8922 feat: PHP runtime add php config
  agent/app/api/v2/runtime.go
  agent/app/dto/request/runtime.go
  agent/app/model/website_acme_account.go
  agent/app/service/runtime.go
  agent/app/service/runtime_utils.go
  agent/constant/runtime.go
  agent/router/ro_runtime.go
  frontend/src/api/interface/runtime.ts
  frontend/src/api/modules/runtime.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/zh-Hant.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/website/runtime/php/config/container/index.vue
  frontend/src/views/website/runtime/php/config/index.vue
  frontend/src/views/website/runtime/php/create/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8926 fix: Fix some snapshot anomaly issues
  agent/app/service/snapshot.go
  agent/app/service/snapshot_create.go
  frontend/src/views/setting/snapshot/create/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8929 fix: Fix issue with custom rules being lost after restarting OpenResty.
  agent/app/service/app_install.go
  frontend/src/views/website/runtime/php/config/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8939 feat: add domain validate for appinstall webUI
  frontend/src/views/app-store/installed/detail/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8953 feat: add name attrs to login inputs for password managers to recognize
  frontend/src/views/login/components/login-form.vue
Labels: do-not-merge/release-note-label-needed

#8965 fix: Resolve the error in reading container logs
  agent/app/service/container.go
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8966 fix: Resolve the error in file management
  frontend/src/components/file-list/index.vue
  frontend/src/components/system-upgrade/index.vue
  frontend/src/views/app-store/detail/params/index.vue
  frontend/src/views/host/file-management/index.vue
  frontend/src/views/website/website/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8969 style: change import license button style
  frontend/src/components/license-import/index.vue
  frontend/src/views/app-store/installed/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8979 docs: Update the installation script
  README.md
Labels: do-not-merge/release-note-label-needed

#8985 fix: fix issue with change ssl_protocols failed
  agent/app/service/website_utils.go
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/zh-Hant.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/website/website/config/basic/https/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8994 feat: fix issue with build frontend failed
  frontend/src/views/container/image/prune/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#9012 fix: fix issue with clean supervisor log failed
  frontend/src/views/website/runtime/php/supervisor/file/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#9013 update go module
  agent/go.mod
  agent/go.sum
  core/go.mod
  core/go.sum
  core/i18n/lang/en.yaml
  core/i18n/lang/ja.yaml
  core/i18n/lang/ko.yaml
  core/i18n/lang/ms.yml
  core/i18n/lang/pt-BR.yaml
  core/i18n/lang/ru.yaml
  core/i18n/lang/zh-Hant.yaml
  core/i18n/lang/zh.yaml
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#9021 refactor: update docs url
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/zh-Hant.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/styles/common.scss
  frontend/src/views/toolbox/clam/index.vue
  frontend/src/views/toolbox/fail2ban/index.vue
  frontend/src/views/toolbox/ftp/index.vue
  frontend/src/views/toolbox/supervisor/status/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#9031 fix: Fixed the restart panel theme switching issue
  frontend/src/components/v-charts/components/Line.vue
  frontend/src/components/v-charts/components/Pie.vue
  frontend/src/components/v-charts/index.vue
  frontend/src/utils/xpack.ts
Labels: do-not-merge/release-note-label-needed, dev-v2

#9033 perf: remove "TLSv1.1", "TLSv1" for create website
  agent/app/service/website.go
  frontend/src/views/terminal/host/index.vue
  frontend/src/views/website/runtime/php/supervisor/index.vue
  frontend/src/views/website/website/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#9040 fix: Remove proxy settings from Google Drive client
  agent/utils/cloud_storage/client/google_drive.go
  core/utils/cloud_storage/client/google_drive.go
Labels: do-not-merge/release-note-label-needed

#9044 fix: Fix the problem of abnormal reserved copies for cronjob
  agent/app/service/cronjob_helper.go
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#9053 feat: change runtime timezone helper
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/zh-Hant.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/website/runtime/environment/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#9058 feat: add docker status for appstore
  frontend/src/views/app-store/apps/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#9111 fix: Modify the license binding node filtering
  frontend/src/api/modules/setting.ts
  frontend/src/views/setting/license/bind/free.vue
  frontend/src/views/setting/license/bind/xpack.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#9113 fix: fix issue with php install swoole failed
  agent/cmd/server/nginx_conf/php_extensions.json
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#9117 feat: Ensure compatibility with docker-compose commands.
  agent/global/config.go
  agent/i18n/lang/en.yaml
  agent/i18n/lang/ja.yaml
  agent/i18n/lang/ko.yaml
  agent/i18n/lang/ms.yaml
  agent/i18n/lang/pt-BR.yaml
  agent/i18n/lang/ru.yaml
  agent/i18n/lang/zh-Hant.yaml
  agent/i18n/lang/zh.yaml
  agent/init/business/business.go
  agent/utils/common/common.go
  agent/utils/compose/compose.go
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#9119 feat: Add quick installation for PHP extension pcntl
  agent/app/service/runtime.go
  agent/app/service/runtime_utils.go
  agent/cmd/server/nginx_conf/nginx_conf.go
  agent/cmd/server/nginx_conf/php_extensions.json
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#9124 feat: transfer some code
  agent/app/api/v2/host_tool.go
  agent/app/api/v2/ssh.go
  agent/app/service/firewall.go
  agent/app/service/ftp.go
  agent/app/service/image_repo.go
  agent/app/service/snapshot_recover.go
  agent/app/service/website_ca.go
  agent/utils/cloud_storage/client/cos.go
  agent/utils/firewall/client/info.go
  agent/utils/firewall/client/iptables.go
  agent/utils/firewall/client/ufw.go
  core/utils/cloud_storage/client/cos.go
  frontend/src/components/task-list/index.vue
  frontend/src/views/cronjob/cronjob/operate/index.vue
  frontend/src/views/cronjob/library/index.vue
  frontend/src/views/home/index.vue
  frontend/src/views/host/file-management/index.vue
  frontend/src/views/host/ssh/log/log.vue
  frontend/src/views/log/login/index.vue
  frontend/src/views/log/operation/index.vue
  frontend/src/views/log/task/index.vue
  frontend/src/views/toolbox/supervisor/index.vue
  frontend/src/views/website/runtime/php/supervisor/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#9138 feat: Optimize the node to add inspection items
  core/utils/common/common.go
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/zh-Hant.ts
  frontend/src/lang/modules/zh.ts
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#9139 fix: Fix the issue of abnormal login log recording
  core/app/service/auth.go
  frontend/src/views/log/login/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#9143 fix: Fix the problem of failed start of swap in the toolbox
  agent/app/service/device.go
  core/app/service/entry.go
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#9149 fix: Fix the issue of interface image loss caused by clearing cache
  agent/app/service/device_clean.go
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#9158 fix: Upgrade the element version to 2.9.9
  agent/utils/docker/docker.go
  frontend/package.json
  frontend/src/layout/components/Sidebar/components/Collapse.vue
  frontend/src/views/cronjob/cronjob/operate/index.vue
  frontend/src/views/log/operation/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#9162 fix: Increase the timeout period of the swap setting
  frontend/src/api/modules/toolbox.ts
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#9164 fix: Fix image loading issue
  frontend/src/layout/components/Sidebar/components/Logo.vue
  frontend/src/utils/util.ts
  frontend/src/utils/xpack.ts
  frontend/src/views/login/index.vue
  frontend/src/views/setting/about/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#9165 feat: Adopt temporary container adaptation for app store status verification
  agent/app/service/app_install.go
  agent/app/service/app_utils.go
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#9169 fix: Service status acquisition compatible with snap
  agent/utils/systemctl/systemctl.go
Labels: do-not-merge/release-note-label-needed, dev-v2

#9174 fix: Fix the problem of abnormal addition of remote connections to th…
  agent/utils/postgresql/client.go
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#9175 feat: update demo handle
  agent/middleware/demo_handle.go
  core/app/api/v2/auth.go
  core/app/dto/setting.go
  core/middleware/demo_handle.go
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#9181 feat: add agent debug cmd for cpu/mem analysis
  agent/cmd/server/cmd/debug.go
  agent/cmd/server/cmd/root.go
  agent/cmd/server/main.go
  frontend/src/global/mimetype.ts
Labels: do-not-merge/release-note-label-needed, dev-v2

#9180 feat: Add cache to query SMS records
  core/go.mod
  core/go.sum
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#9183 fix: fix issue with http3 config not work in proxy website
  agent/app/service/website.go
  agent/app/service/website_utils.go
Labels: do-not-merge/release-note-label-needed, dev-v2

#9186 feat: add core debug cmd for cpu/mem analysis
  core/cmd/server/cmd/debug.go
Labels: do-not-merge/release-note-label-needed, lgtm, dev-v2

#9185 style: Adjust the style of the cronjob status button
  frontend/src/components/status/index.vue
  frontend/src/views/cronjob/cronjob/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#9188 fix: Optimize the synchronization log information of the script library
  core/app/service/script_library.go
  core/i18n/lang/en.yaml
  core/i18n/lang/ja.yaml
  core/i18n/lang/ko.yaml
  core/i18n/lang/ms.yml
  core/i18n/lang/pt-BR.yaml
  core/i18n/lang/ru.yaml
  core/i18n/lang/zh-Hant.yaml
  core/i18n/lang/zh.yaml
  frontend/src/views/cronjob/library/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#9189 fix: Fix hidden file flipping issue
  frontend/src/views/host/file-management/index.vue
  frontend/src/views/login/components/login-form.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#9198 fix: File content support GBK encoding
  agent/app/service/file.go
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#9217 fix: Fix the apps store docker status error
  frontend/src/views/app-store/apps/index.vue
Labels: do-not-merge/release-note-label-needed

#9239 style: change dnsAccount select option style in create ssl page
  frontend/src/views/website/ssl/create/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#9243 feat: add PbootCMS extensions template for php runtime
  backend/init/migration/migrate.go
  backend/init/migration/migrations/v_1_10.go
Labels: do-not-merge/release-note-label-needed, dev

#9248 fix: Fix page loading issue with no data status
  frontend/src/views/ai/model/index.vue
  frontend/src/views/app-store/apps/index.vue
  frontend/src/views/database/mysql/index.vue
  frontend/src/views/database/postgresql/index.vue
  frontend/src/views/database/redis/index.vue
  frontend/src/views/host/firewall/status/index.vue
  frontend/src/views/setting/snapshot/index.vue
  frontend/src/views/toolbox/clam/status/index.vue
  frontend/src/views/toolbox/fail2ban/index.vue
  frontend/src/views/toolbox/ftp/index.vue
  frontend/src/views/website/website/index.vue
Labels: do-not-merge/release-note-label-needed, dev-v2

#9247 fix: fixed dashboard operating system platform Version
  frontend/src/views/home/index.vue
Labels: do-not-merge/release-note-label-needed

#9251 fix: Fix the problem of ip changes in container upgrades for macvlan …
  backend/app/service/container.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#9252 fix: Add a restart prompt for HTTP-type mirror repositories
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/container/repo/operator/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#9256 fix: Fixed the issue that caused the error (bufio.Scanner: token too long) when viewing container log
  agent/app/service/container.go
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#9261 fix: Fixed issue with tar file failed with exist 1
  agent/app/service/cronjob_helper.go
  agent/utils/cmd/cmdx.go
  agent/utils/files/file_op.go
  core/utils/cmd/cmdx.go
  core/utils/files/files.go
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#9264 Revert "fix: Fix the issue with upgrade failures"
  backend/app/service/upgrade.go
Labels: do-not-merge/release-note-label-needed, dev

#9259 fix: fix issue with subsite dir error
  agent/app/dto/request/website.go
  agent/app/service/website.go
  frontend/src/components/card-with-header/index.vue
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/zh-Hant.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/website/website/config/basic/site-folder/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#9265 perf: Optimize and Edit PHP Runtime Environment Version Switching
  agent/app/service/runtime_utils.go
Labels: do-not-merge/release-note-label-needed, lgtm, dev-v2

#9263 fix: Rollback snapshot code
  agent/app/service/snapshot_create.go
  agent/i18n/lang/en.yaml
  agent/i18n/lang/ja.yaml
  agent/i18n/lang/ko.yaml
  agent/i18n/lang/ms.yaml
  agent/i18n/lang/pt-BR.yaml
  agent/i18n/lang/ru.yaml
  agent/i18n/lang/zh-Hant.yaml
  agent/i18n/lang/zh.yaml
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#9267 feat: Specify the interpretation code based on the file content
  agent/app/service/clam.go
  agent/app/service/cronjob_helper.go
  agent/app/service/file.go
  agent/init/hook/hook.go
  agent/utils/files/utils.go
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#9273 fix: Fixed logging errors for uploaded files
  agent/app/api/v2/file.go
  core/cmd/server/docs/x-log.json
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#9277 fix: Fix snapshot restoration for container configuration errors
  agent/app/service/snapshot_create.go
  agent/app/service/snapshot_recover.go
  agent/app/service/snapshot_rollback.go
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#9278 perf: add some config for website_default.conf
  agent/app/service/website_utils.go
  agent/cmd/server/nginx_conf/nginx_conf.go
  agent/cmd/server/nginx_conf/website_default.conf
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#9279 fix: Optimize snapshot and snapshot recovery mechanism
  agent/app/service/snapshot_create.go
  agent/app/service/snapshot_recover.go
  agent/app/task/task.go
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#9283 fix: Fix missing line breaks in copied logs on the log page
  frontend/src/components/log/container/index.vue
  frontend/src/components/log/file/index.vue
  frontend/src/views/container/container/index.vue
Labels: do-not-merge/release-note-label-needed, dev-v2

#9292 fix: Fix ClamAV service name detection issue
  backend/utils/systemctl/managers.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#9297 fix: Remove code comments
  backend/app/service/host_tool.go
  backend/utils/systemctl/configloade.go
  backend/utils/systemctl/handle.go
  backend/utils/systemctl/managers.go
  backend/utils/systemctl/systemctl.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#9301 fix: Modify the service status judgment logic
  backend/utils/systemctl/managers.go
Labels: do-not-merge/release-note-label-needed, dev

#9302 Revert "fix: Fix missing line breaks in copied logs on the log page (…
  frontend/src/components/log/container/index.vue
  frontend/src/components/log/file/index.vue
  frontend/src/views/container/container/index.vue
Labels: do-not-merge/release-note-label-needed, dev-v2

#9305 fix: Resolve abnormal state after Docker restart
  backend/app/service/docker.go
  backend/utils/systemctl/handle.go
  backend/utils/systemctl/managers.go
  backend/utils/systemctl/systemctl.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#9311 Revert "fix: Fix missing line breaks in copied logs on the log page (…
  frontend/src/components/log/container/index.vue
  frontend/src/components/log/file/index.vue
  frontend/src/views/container/container/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#9319 fix: Fix the issue of multiple selection moving folder errors
  backend/app/dto/request/file.go
  backend/app/dto/response/file.go
  backend/app/service/file.go
  backend/utils/files/file_op.go
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/host/file-management/move/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#9320 feat: Add application exclusion for cronjob snapshots
  agent/app/dto/cronjob.go
  agent/app/model/cronjob.go
  agent/app/service/cronjob.go
  agent/app/service/cronjob_backup.go
  agent/init/migration/migrate.go
  agent/init/migration/migrations/init.go
  frontend/src/api/interface/cronjob.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/zh-Hant.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/cronjob/cronjob/operate/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#9321 perf: optimization php config
  agent/app/service/runtime_utils.go
  agent/cmd/server/nginx_conf/php-fpm.conf
  agent/constant/runtime.go
  agent/init/migration/migrate.go
  agent/init/migration/migrations/init.go
Labels: do-not-merge/release-note-label-needed, approved, dev-v2

#9323 fix: Update compression backup exclusion rules
  agent/app/dto/setting.go
  agent/app/dto/snapshot.go
  agent/app/model/snapshot.go
  agent/app/service/cronjob_backup.go
  agent/app/service/snapshot_create.go
  agent/init/migration/migrate.go
  agent/init/migration/migrations/init.go
  agent/utils/files/file_op.go
  frontend/src/api/interface/cronjob.ts
  frontend/src/components/file-batch/index.vue
  frontend/src/views/cronjob/cronjob/operate/index.vue
  frontend/src/views/setting/snapshot/create/index.vue
  frontend/src/views/setting/snapshot/index.vue
  frontend/src/views/setting/snapshot/status/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#9341 style: Optimize cronjob report page styling
  core/constant/common.go
  frontend/src/views/cronjob/cronjob/record/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#9345 fix: Fix the compilation exception problem caused by dependencies
  agent/go.mod
  agent/go.sum
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#9347 fix: Optimize container image repo restart detection logic
  agent/app/api/v2/image_repo.go
  agent/app/dto/image_repo.go
  agent/app/service/image_repo.go
  frontend/src/api/interface/container.ts
  frontend/src/api/modules/container.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/zh-Hant.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/container/repo/index.vue
  frontend/src/views/container/repo/operator/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#9348 fix: Fix the display error of the sub node website icon
  frontend/src/utils/xpack.ts
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#9349 fix: Disable button when clearing cache and selecting size 0B
  frontend/src/views/toolbox/clean/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2
