Repository 1Panel-dev/1Panel, pull requests merged in 2025-09, with the labels that each got.

#10213 feat: MFA verification code automatically obtains focus
  frontend/src/views/login/components/login-form.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#10209 fix: Optimize container port detection mechanism
  agent/app/service/container.go
  agent/utils/common/common.go
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#10215 feat: Add date to smtp service header
  agent/utils/email/smtp_sender.go
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#10218 feat: Optimize file log reading
  agent/app/dto/file.go
  agent/app/dto/response/file.go
  agent/app/service/file.go
  agent/app/service/website.go
  agent/go.sum
  agent/utils/files/utils.go
  frontend/src/components/log/file/index.vue
Labels: do-not-merge/release-note-label-needed, dev-v2

#10222 fix: Fix typo of "Redis" in language files
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/tr.ts
  frontend/src/lang/modules/zh-Hant.ts
  frontend/src/lang/modules/zh.ts
Labels: do-not-merge/release-note-label-needed

#10228 feat: Login page username automatically obtains focus
  frontend/src/views/login/components/login-form.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#10230 fix: Optimize tamper-protected File deletion warning messages
  frontend/src/api/index.ts
Labels: do-not-merge/release-note-label-needed, dev-v2

#10233 fix: Optimize duplicate execution prevention for cronjob
  agent/app/model/cronjob.go
  agent/app/repo/cronjob.go
  agent/app/service/cronjob_helper.go
  agent/init/hook/hook.go
  agent/init/migration/migrations/init.go
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#10238 feat: Optimize quick navigation for dashboard
  agent/app/api/v2/dashboard.go
  agent/app/dto/dashboard.go
  agent/app/model/app_launcher.go
  agent/app/repo/app_launcher.go
  agent/app/service/dashboard.go
  agent/i18n/lang/en.yaml
  agent/i18n/lang/ja.yaml
  agent/i18n/lang/ko.yaml
  agent/i18n/lang/ms.yaml
  agent/i18n/lang/pt-BR.yaml
  agent/i18n/lang/ru.yaml
  agent/i18n/lang/tr.yaml
  agent/i18n/lang/zh-Hant.yaml
  agent/i18n/lang/zh.yaml
  agent/init/migration/migrate.go
  agent/init/migration/migrations/init.go
  agent/router/ro_dashboard.go
  frontend/src/api/interface/dashboard.ts
  frontend/src/api/modules/dashboard.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/tr.ts
  frontend/src/lang/modules/zh-Hant.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/home/index.vue
  frontend/src/views/home/quick/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#10239 fix: Fix container image upgrade command loss issue
  agent/app/service/container.go
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#10244 fix: Resolve the issue of still receiving update prompts after ignoring the application.
  agent/app/service/app_utils.go
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#10248 style: Optimize version update changelog display
  frontend/src/components/copy-button/index.vue
  frontend/src/components/detail-show/index.vue
  frontend/src/components/system-upgrade/index.vue
  frontend/src/components/system-upgrade/releases/index.vue
  frontend/src/views/ai/mcp/server/index.vue
  frontend/src/views/ai/model/conn/index.vue
  frontend/src/views/app-store/installed/detail/index.vue
  frontend/src/views/database/mysql/conn/index.vue
  frontend/src/views/database/mysql/index.vue
  frontend/src/views/database/mysql/remote/index.vue
  frontend/src/views/database/postgresql/conn/index.vue
  frontend/src/views/database/postgresql/index.vue
  frontend/src/views/database/postgresql/remote/index.vue
  frontend/src/views/database/redis/conn/index.vue
  frontend/src/views/database/redis/remote/index.vue
  frontend/src/views/setting/panel/api-interface/index.vue
  frontend/src/views/setting/safe/mfa/index.vue
  frontend/src/views/toolbox/ftp/index.vue
  frontend/src/views/website/ssl/apply/index.vue
  frontend/src/views/website/ssl/ca/detail/index.vue
  frontend/src/views/website/ssl/detail/index.vue
  frontend/src/views/website/website/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#10252 feat: support closing log dialog with ESC key and outside click
  frontend/src/components/log/task/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#10253 fix: Add Docker restart option to firewall operations
  agent/app/api/v2/firewall.go
  agent/app/dto/firewall.go
  agent/app/service/firewall.go
  frontend/src/api/modules/host.ts
  frontend/src/components/docker-proxy/docker-restart.vue
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/tr.ts
  frontend/src/lang/modules/zh-Hant.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/host/firewall/status/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#10257 fix: Resolve the issue where the page does not display correctly after enabling browser caching.
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/tr.ts
  frontend/src/lang/modules/zh-Hant.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/website/website/config/basic/anti-Leech/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#10261 feat: Mcp Server support uvx
  agent/app/dto/request/mcp_server.go
  agent/app/model/mcp_server.go
  agent/app/service/mcp_server.go
  agent/init/migration/migrate.go
  agent/init/migration/migrations/init.go
  frontend/src/api/interface/ai.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/tr.ts
  frontend/src/lang/modules/zh-Hant.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/ai/mcp/server/operate/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#10268 fix: Optimize the trigger method for table selection
  frontend/src/components/complex-table/index.vue
  frontend/src/views/container/network/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#10280 fix: Fix the issue where the task did not stop after deleting the alert
  agent/app/service/alert.go
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#10281 fix: Fix alert issue
  frontend/src/views/setting/alert/dash/task/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#10282 feat: Add disk management
  agent/app/api/v2/disk.go
  agent/app/api/v2/entry.go
  agent/app/dto/disk.go
  agent/app/dto/request/disk.go
  agent/app/dto/response/disk.go
  agent/app/service/disk.go
  agent/i18n/lang/en.yaml
  agent/i18n/lang/ja.yaml
  agent/i18n/lang/ko.yaml
  agent/i18n/lang/ms.yaml
  agent/i18n/lang/pt-BR.yaml
  agent/i18n/lang/ru.yaml
  agent/i18n/lang/tr.yaml
  agent/i18n/lang/zh-Hant.yaml
  agent/i18n/lang/zh.yaml
  agent/router/ro_host.go
  core/init/migration/migrate.go
  core/init/migration/migrations/init.go
  frontend/src/api/interface/host.ts
  frontend/src/api/modules/host.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/tr.ts
  frontend/src/lang/modules/zh-Hant.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/routers/modules/host.ts
  frontend/src/views/host/disk-management/components/disk-card.vue
  frontend/src/views/host/disk-management/disk/index.vue
  frontend/src/views/host/disk-management/index.vue
  frontend/src/views/host/disk-management/partition/index.vue
Labels: do-not-merge/release-note-label-needed, dev-v2

#10299 fix: Fix the problem of uploaded backup files being deleted after res…
  agent/app/service/backup.go
  agent/app/service/backup_mysql.go
  agent/app/service/backup_postgresql.go
  agent/app/service/container.go
  agent/i18n/lang/en.yaml
  agent/i18n/lang/ja.yaml
  agent/i18n/lang/ko.yaml
  agent/i18n/lang/ms.yaml
  agent/i18n/lang/pt-BR.yaml
  agent/i18n/lang/ru.yaml
  agent/i18n/lang/tr.yaml
  agent/i18n/lang/zh-Hant.yaml
  agent/i18n/lang/zh.yaml
  frontend/src/utils/router.ts
  frontend/src/views/container/volume/index.vue
  frontend/src/views/home/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#10300 fix: Solve the problem of internationalization of operation logs
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/tr.ts
  frontend/src/lang/modules/zh-Hant.ts
  frontend/src/lang/modules/zh.ts
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#10305 fix: Fixed issue with build frontend failed
  frontend/package.json
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#10306 fix: Fixed issue with can not disable cache in antiLeech
  agent/app/dto/request/nginx.go
  frontend/src/views/website/website/config/basic/anti-Leech/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#10308 fix: Optimize backup logic for cronjob
  agent/app/service/cronjob_backup.go
  agent/i18n/lang/en.yaml
  agent/i18n/lang/ja.yaml
  agent/i18n/lang/ko.yaml
  agent/i18n/lang/ms.yaml
  agent/i18n/lang/pt-BR.yaml
  agent/i18n/lang/ru.yaml
  agent/i18n/lang/tr.yaml
  agent/i18n/lang/zh-Hant.yaml
  agent/i18n/lang/zh.yaml
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#10309 feat: Extend Openresty build time
  agent/app/service/nginx.go
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#10311 perf: Optimize the display of HTML-type logs
  frontend/src/components/log/custom-hightlight/index.vue
  frontend/src/components/log/file/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#10315 fix: Fix snapshot interface timeout configuration issue
  frontend/src/api/modules/setting.ts
  frontend/src/views/database/postgresql/conn/index.vue
  frontend/src/views/setting/snapshot/create/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#10316 style: Add fullscreen support for some drawers
  frontend/src/components/drawer-pro/index.vue
  frontend/src/views/ai/model/terminal/index.vue
  frontend/src/views/container/compose/create/index.vue
  frontend/src/views/container/compose/edit/index.vue
  frontend/src/views/container/container/terminal/index.vue
  frontend/src/views/container/image/build/index.vue
  frontend/src/views/container/template/operator/index.vue
  frontend/src/views/cronjob/library/operate/index.vue
  frontend/src/views/cronjob/library/run/index.vue
  frontend/src/views/host/file-management/terminal/index.vue
  frontend/src/views/toolbox/clam/record/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#10318 fix: Fix the issue of terminal key connection exception
  agent/app/service/setting.go
  frontend/src/views/terminal/setting/default_conn/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#10322 fix: Fix alert issue remove some alert logs
  agent/app/service/alert_helper.go
  frontend/src/views/setting/alert/dash/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#10324 feat: Adjust disk management menu order
  frontend/src/api/modules/files.ts
  frontend/src/api/modules/host.ts
  frontend/src/routers/modules/host.ts
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#10325 fix: Fix the issue of terminal key connection exception
  agent/app/service/setting.go
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#10326 feat: Adjust hard drive mounting logic
  agent/app/dto/request/disk.go
  agent/app/service/disk.go
  frontend/src/lang/modules/zh.ts
  frontend/src/views/host/disk-management/partition/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#10330 feat: Add debounce effect to file selection
  frontend/src/components/file-list/index.vue
  frontend/src/utils/util.ts
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#10333 fix: Fix file decompression issue
  agent/utils/files/file_op.go
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#10372 feat: The certificate list supports sorting by expiration date.
  agent/app/dto/request/website_ssl.go
  agent/app/service/website_ssl.go
  frontend/src/views/website/ssl/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#10380 feat: Update zh-Hant translation
  agent/i18n/lang/zh-Hant.yaml
  core/i18n/lang/zh-Hant.yaml
  docs/README.zh-Hant.md
  frontend/src/lang/modules/zh-Hant.ts
Labels: do-not-merge/release-note-label-needed

#10383 ref: Code formatting
  frontend/src/lang/index.ts
  frontend/src/lang/modules/zh-Hant.ts
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#10385 style: change app edit button style
  frontend/package.json
  frontend/src/views/app-store/installed/detail/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#10386 fix: Resolve the issue of application edit parameters becoming mandatory.
  frontend/src/views/app-store/installed/detail/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#10388 feat: Support adding panels
  core/init/migration/migrate.go
  core/init/migration/migrations/init.go
  core/utils/common/common.go
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/tr.ts
  frontend/src/lang/modules/zh-Hant.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/setting/panel/api-interface/index.vue
Labels: do-not-merge/release-note-label-needed, dev-v2

#10393 fix: Fixed issue with sync ssl to node failed
  core/middleware/bind_domain.go
  core/middleware/ip_limit.go
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#10395 feat: Add support for offline version.
  agent/global/config.go
  core/app/api/v2/auth.go
  core/app/dto/setting.go
  core/app/service/upgrade.go
  core/global/config.go
  core/init/viper/viper.go
  frontend/src/components/system-upgrade/index.vue
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/tr.ts
  frontend/src/lang/modules/zh-Hant.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/store/interface/index.ts
  frontend/src/store/modules/global.ts
  frontend/src/views/app-store/apps/index.vue
  frontend/src/views/app-store/detail/form/index.vue
  frontend/src/views/app-store/setting/index.vue
  frontend/src/views/login/components/login-form.vue
  frontend/src/views/setting/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#10400 feat: Improve Español language
  frontend/src/App.vue
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/es-es.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/tr.ts
  frontend/src/lang/modules/zh-Hant.ts
  frontend/src/views/login/components/login-form.vue
  frontend/src/views/setting/panel/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#10403 feat: optimization install php extensions
  agent/app/service/runtime_utils.go
  agent/cmd/server/nginx_conf/php_extensions.json
  frontend/src/views/website/runtime/components/terminal.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#10405 feat: Support quick commands in the file terminal
  frontend/src/views/host/file-management/terminal/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#10407 feat: Support database terminal operations
  agent/app/api/v2/terminal.go
  agent/utils/terminal/local_cmd.go
  frontend/src/components/terminal/database.vue
  frontend/src/views/database/mysql/index.vue
  frontend/src/views/database/postgresql/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#10408 fix: Optimize the style of quick command options
  core/app/dto/command.go
  core/app/service/command.go
  frontend/src/components/app-status/index.vue
  frontend/src/views/host/file-management/terminal/index.vue
  frontend/src/views/terminal/terminal/index.vue
  frontend/src/views/toolbox/supervisor/status/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#10415 feat: support batch operate website
  agent/app/api/v2/website.go
  agent/app/dto/request/website.go
  agent/app/service/website.go
  agent/app/task/task.go
  agent/i18n/lang/en.yaml
  agent/i18n/lang/es-ES.yaml
  agent/i18n/lang/ja.yaml
  agent/i18n/lang/ko.yaml
  agent/i18n/lang/ms.yaml
  agent/i18n/lang/pt-BR.yaml
  agent/i18n/lang/ru.yaml
  agent/i18n/lang/tr.yaml
  agent/i18n/lang/zh-Hant.yaml
  agent/i18n/lang/zh.yaml
  agent/router/ro_website.go
  frontend/src/api/interface/website.ts
  frontend/src/api/modules/website.ts
  frontend/src/components/complex-table/index.vue
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/es-es.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/tr.ts
  frontend/src/lang/modules/zh-Hant.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/website/website/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#10429 feat: add timeout limit function Config for PHP
  agent/app/dto/request/runtime.go
  agent/app/dto/response/website.go
  agent/app/service/runtime.go
  frontend/src/api/interface/runtime.ts
  frontend/src/api/modules/runtime.ts
  frontend/src/views/website/runtime/php/config/index.vue
  frontend/src/views/website/runtime/php/config/timeout/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#10434 feat: Support import and export operations for quick commands
  core/app/api/v2/command.go
  core/app/dto/command.go
  core/app/service/command.go
  core/i18n/lang/en.yaml
  core/i18n/lang/es-ES.yaml
  core/i18n/lang/ja.yaml
  core/i18n/lang/ko.yaml
  core/i18n/lang/ms.yml
  core/i18n/lang/pt-BR.yaml
  core/i18n/lang/ru.yaml
  core/i18n/lang/tr.yaml
  core/i18n/lang/zh-Hant.yaml
  core/i18n/lang/zh.yaml
  core/router/command.go
  core/utils/csv/command.go
  frontend/src/api/index.ts
  frontend/src/api/modules/command.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/es-es.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/tr.ts
  frontend/src/lang/modules/zh-Hant.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/terminal/command/import/index.vue
  frontend/src/views/terminal/command/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#10464 feat: add acme-dns provider for ssl dns
  agent/go.mod
  agent/go.sum
  agent/utils/ssl/dns_provider.go
  frontend/src/global/mimetype.ts
  frontend/src/views/website/ssl/dns-account/create/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#10471 feat: support config environment for supervisor
  agent/app/dto/request/host_tool.go
  agent/app/dto/response/host_tool.go
  agent/app/service/host_tool.go
  frontend/src/api/interface/host-tool.ts
  frontend/src/api/interface/runtime.ts
  frontend/src/views/toolbox/supervisor/create/index.vue
  frontend/src/views/website/runtime/php/supervisor/create/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#10473 feat: Adapt to Offline Mode
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/es-es.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/tr.ts
  frontend/src/lang/modules/zh-Hant.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/website/runtime/php/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#10480 feat: Support authkeys management
  agent/app/api/v2/ssh.go
  agent/app/service/ssh.go
  agent/router/ro_host.go
  frontend/src/api/modules/host.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/es-es.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/tr.ts
  frontend/src/lang/modules/zh-Hant.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/host/ssh/ssh/auth-keys/index.vue
  frontend/src/views/host/ssh/ssh/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#10483 feat: Support customizing the number of upgrade backup copies
  core/app/dto/setting.go
  core/app/service/setting.go
  core/app/service/upgrade.go
  core/init/migration/migrate.go
  core/init/migration/migrations/init.go
  frontend/src/api/interface/setting.ts
  frontend/src/components/system-upgrade/index.vue
  frontend/src/components/system-upgrade/releases/index.vue
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/es-es.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/tr.ts
  frontend/src/lang/modules/zh-Hant.ts
  frontend/src/lang/modules/zh.ts
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#10485 feat: Fix the issue of abnormal node name display in the Community Ed…
  frontend/src/layout/components/Sidebar/components/Collapse.vue
  frontend/src/layout/index.vue
  frontend/src/store/modules/global.ts
  frontend/src/views/cronjob/library/index.vue
  frontend/src/views/log/operation/index.vue
  frontend/src/views/setting/license/bind/xpack.vue
  frontend/src/views/setting/license/index.vue
  frontend/src/views/setting/panel/watermark/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#10487 feat: Support customizing whether scripts are automatically synchronized
  core/app/api/v2/setting.go
  core/app/dto/setting.go
  core/init/cron/cron.go
  core/init/migration/migrate.go
  core/init/migration/migrations/init.go
  core/init/run/run.go
  core/router/ro_setting.go
  frontend/src/api/modules/setting.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/es-es.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/tr.ts
  frontend/src/lang/modules/zh-Hant.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/cronjob/library/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#10496 feat: Cache the last created website type.
  frontend/src/views/website/website/create/index.vue
  frontend/src/views/website/website/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#10493 fix: Fix the issue where cronjob expressions do not support commas
  agent/app/service/cronjob.go
  agent/init/migration/migrate.go
  agent/init/migration/migrations/init.go
  frontend/src/views/cronjob/cronjob/index.vue
  frontend/src/views/cronjob/cronjob/operate/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#10501 feat: Node Runtime support for pm2
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/es-es.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/tr.ts
  frontend/src/lang/modules/zh-Hant.ts
  frontend/src/lang/modules/zh.ts
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#10502 feat: Support checking proxy server connection availability
  core/app/service/setting.go
  core/i18n/lang/en.yaml
  core/i18n/lang/es-ES.yaml
  core/i18n/lang/ja.yaml
  core/i18n/lang/ko.yaml
  core/i18n/lang/ms.yml
  core/i18n/lang/pt-BR.yaml
  core/i18n/lang/ru.yaml
  core/i18n/lang/tr.yaml
  core/i18n/lang/zh-Hant.yaml
  core/i18n/lang/zh.yaml
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#10519 fix: Fix the issue of double quote escaping in cronjob
  agent/app/service/cronjob_helper.go
Labels: do-not-merge/release-note-label-needed, dev-v2

#10522 feat: Certificate Add ID Display
  frontend/src/views/website/ssl/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#10523 feat: Update the local certificate and remember the directory address.
  agent/app/model/website_ssl.go
  agent/app/service/website_ssl.go
  agent/init/migration/migrate.go
  agent/init/migration/migrations/init.go
  frontend/src/api/interface/website.ts
  frontend/src/views/website/ssl/upload/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#10524 feat: Support manual stopping of shell-type tasks
  agent/app/api/v2/cronjob.go
  agent/app/service/cronjob.go
  agent/app/service/cronjob_helper.go
  agent/app/task/task.go
  agent/global/global.go
  agent/i18n/lang/en.yaml
  agent/i18n/lang/es-ES.yaml
  agent/i18n/lang/ko.yaml
  agent/i18n/lang/ms.yaml
  agent/i18n/lang/pt-BR.yaml
  agent/i18n/lang/ru.yaml
  agent/i18n/lang/tr.yaml
  agent/i18n/lang/zh-Hant.yaml
  agent/i18n/lang/zh.yaml
  agent/router/ro_cronjob.go
  agent/utils/cmd/cmdx.go
  frontend/src/api/modules/cronjob.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/es-es.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/tr.ts
  frontend/src/lang/modules/zh-Hant.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/cronjob/cronjob/record/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#10529 style: Adjust the maximum height of network card options
  frontend/src/views/host/monitor/monitor/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#10532 feat: Support batch image pulling
  agent/app/dto/image.go
  agent/app/service/image.go
  frontend/src/api/interface/container.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/es-es.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/tr.ts
  frontend/src/lang/modules/zh-Hant.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/container/image/pull/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#10533 fix: Fix the issue of abnormal 1pctl language display after upgrade
  core/app/service/upgrade.go
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#10541 feat: File management supports file format conversion
  agent/app/api/v2/file.go
  agent/app/dto/request/file.go
  agent/app/dto/response/file.go
  agent/app/service/file.go
  agent/app/task/task.go
  agent/global/config.go
  agent/i18n/lang/en.yaml
  agent/i18n/lang/es-ES.yaml
  agent/i18n/lang/ja.yaml
  agent/i18n/lang/ko.yaml
  agent/i18n/lang/ms.yaml
  agent/i18n/lang/pt-BR.yaml
  agent/i18n/lang/ru.yaml
  agent/i18n/lang/tr.yaml
  agent/i18n/lang/zh-Hant.yaml
  agent/i18n/lang/zh.yaml
  agent/init/dir/dir.go
  agent/router/ro_file.go
  agent/utils/convert/convert.go
  frontend/postcss.config.cjs
  frontend/src/App.vue
  frontend/src/api/interface/file.ts
  frontend/src/api/modules/files.ts
  frontend/src/components/complex-table/index.vue
  frontend/src/components/terminal/index.vue
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/es-es.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/tr.ts
  frontend/src/lang/modules/zh-Hant.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/styles/element.scss
  frontend/src/utils/util.ts
  frontend/src/views/host/file-management/convert/index.vue
  frontend/src/views/host/file-management/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#10551 feat: support config cors in website proxy
  agent/app/dto/request/website.go
  agent/app/service/website.go
  agent/utils/nginx/components/location.go
  frontend/src/api/interface/website.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/es-es.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/tr.ts
  frontend/src/lang/modules/zh-Hant.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/website/website/config/basic/https/index.vue
  frontend/src/views/website/website/config/basic/proxy/create/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2
