Repository 1Panel-dev/1Panel, pull requests merged in 2025-03, with the labels that each got.

#8043 fix: Fix the problem of terminal saving failure
  agent/app/api/v2/dashboard.go
  agent/app/service/dashboard.go
  agent/router/ro_dashboard.go
  core/app/api/v2/host.go
  core/app/service/host.go
  core/constant/common.go
  core/router/ro_host.go
  core/utils/ssh/ssh.go
  frontend/src/api/modules/terminal.ts
  frontend/src/components/v-charts/components/Line.vue
  frontend/src/views/container/compose/detail/index.vue
  frontend/src/views/terminal/terminal/host-create.vue
  frontend/src/views/terminal/terminal/index.vue
  frontend/src/views/toolbox/clam/status/index.vue
  frontend/src/views/toolbox/supervisor/status/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8039 style: optimize code editor file path style
  frontend/src/views/host/file-management/code-editor/index.vue
Labels: do-not-merge/release-note-label-needed

#8045 fix: Fix issue where website auth_basic is not effective
  agent/app/service/website.go
  agent/app/service/website_utils.go
  agent/i18n/lang/en.yaml
  agent/i18n/lang/ja.yaml
  agent/i18n/lang/ko.yaml
  agent/i18n/lang/ms.yml
  agent/i18n/lang/pt-BR.yaml
  agent/i18n/lang/ru.yaml
  agent/i18n/lang/zh-Hant.yaml
  agent/i18n/lang/zh.yaml
  core/cmd/server/cmd/root.go
  frontend/src/global/form-rules.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/website/website/config/basic/auth-basic/create/index.vue
  frontend/src/views/website/website/config/basic/auth-basic/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8046 fix: Fix issue where editing source text during website redirection r…
  agent/app/service/website.go
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8050 fix: Modify the recommended application synchronization mode
  agent/app/api/v2/dashboard.go
  agent/app/dto/dashboard.go
  agent/app/repo/task.go
  agent/app/service/backup_record.go
  agent/app/service/dashboard.go
  agent/app/service/device_clean.go
  core/app/service/app_launcher.go
  frontend/src/components/status/index.vue
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/zh-Hant.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/container/container/operate/index.vue
  frontend/src/views/cronjob/operate/index.vue
  frontend/src/views/setting/backup-account/operate/index.vue
  frontend/src/views/setting/license/index.vue
  frontend/src/views/terminal/setting/index.vue
  frontend/src/views/toolbox/clean/index.vue
  frontend/src/views/website/runtime/java/index.vue
  frontend/src/views/website/runtime/php/check/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, dev-v2

#8054 fix: Standardize logging component
  frontend/src/components/backup/index.vue
  frontend/src/components/log-dialog/index.vue
  frontend/src/components/log/compose/index.vue
  frontend/src/components/log/container-drawer/index.vue
  frontend/src/components/log/container/index.vue
  frontend/src/components/log/custom-hightlight/index.vue
  frontend/src/components/log/drawer/index.vue
  frontend/src/components/log/file/index.vue
  frontend/src/components/log/hightlight-log/index.vue
  frontend/src/components/log/task/index.vue
  frontend/src/components/log/task/log-without-dialog.vue
  frontend/src/components/task-list/index.vue
  frontend/src/components/upload/index.vue
  frontend/src/views/ai/model/index.vue
  frontend/src/views/app-store/apps/index.vue
  frontend/src/views/app-store/detail/install/index.vue
  frontend/src/views/app-store/installed/delete/index.vue
  frontend/src/views/app-store/installed/index.vue
  frontend/src/views/app-store/installed/upgrade/index.vue
  frontend/src/views/container/compose/create/index.vue
  frontend/src/views/container/compose/detail/index.vue
  frontend/src/views/container/container/command/index.vue
  frontend/src/views/container/container/index.vue
  frontend/src/views/container/container/operate/index.vue
  frontend/src/views/container/image/build/index.vue
  frontend/src/views/container/image/pull/index.vue
  frontend/src/views/container/image/push/index.vue
  frontend/src/views/cronjob/record/index.vue
  frontend/src/views/database/mysql/setting/index.vue
  frontend/src/views/database/mysql/setting/slow-log/index.vue
  frontend/src/views/database/postgresql/setting/index.vue
  frontend/src/views/log/system/index.vue
  frontend/src/views/log/task/index.vue
  frontend/src/views/log/website/index.vue
  frontend/src/views/setting/snapshot/create/index.vue
  frontend/src/views/setting/snapshot/index.vue
  frontend/src/views/setting/snapshot/recover/index.vue
  frontend/src/views/terminal/terminal/host-create.vue
  frontend/src/views/toolbox/supervisor/config/log/index.vue
  frontend/src/views/website/runtime/dotnet/index.vue
  frontend/src/views/website/runtime/go/index.vue
  frontend/src/views/website/runtime/java/index.vue
  frontend/src/views/website/runtime/node/index.vue
  frontend/src/views/website/runtime/php/index.vue
  frontend/src/views/website/runtime/python/index.vue
  frontend/src/views/website/ssl/index.vue
  frontend/src/views/website/website/config/log/log-fiile/index.vue
  frontend/src/views/website/website/create/index.vue
  frontend/src/views/website/website/nginx/index.vue
  frontend/src/views/website/website/nginx/module/build/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, dev-v2

#8038 refactor(container): optimize memory calculation and concurrent data handling
  backend/app/service/container.go
Labels: do-not-merge/release-note-label-needed

#8055 fix: Add length limit to comments
  agent/app/dto/request/website.go
  agent/app/repo/website.go
  agent/app/service/website_ssl.go
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/zh-Hant.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/website/ssl/index.vue
  frontend/src/views/website/website/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8056 feat: Adjust license
  backend/app/dto/setting.go
  backend/configs/system.go
  backend/init/hook/hook.go
  backend/init/migration/migrate.go
  backend/init/migration/migrations/v_1_10.go
  backend/init/viper/viper.go
  backend/server/server.go
  frontend/src/api/interface/setting.ts
  frontend/src/store/interface/index.ts
  frontend/src/store/modules/global.ts
  frontend/src/views/login/components/login-form.vue
  frontend/src/views/setting/license/index.vue
  go.mod
  go.sum
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#8057 feat: Modify Swagger route response for unauthenticated access
  backend/init/router/router.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#8059 feat: Restrict abnormal database selection during application install…
  agent/app/dto/response/app.go
  agent/app/service/ai.go
  agent/app/service/app.go
  agent/app/service/app_install.go
  agent/app/service/app_utils.go
  agent/app/service/backup_record.go
  agent/app/service/docker.go
  agent/app/service/snapshot_recover.go
  agent/app/service/website.go
  agent/app/service/website_ssl.go
  agent/constant/app.go
  agent/constant/status.go
  agent/i18n/lang/en.yaml
  agent/i18n/lang/ja.yaml
  agent/i18n/lang/ko.yaml
  agent/i18n/lang/ms.yml
  agent/i18n/lang/pt-BR.yaml
  agent/i18n/lang/ru.yaml
  agent/i18n/lang/zh-Hant.yaml
  agent/i18n/lang/zh.yaml
  agent/init/business/business.go
  frontend/src/api/interface/app.ts
  frontend/src/components/log/task/index.vue
  frontend/src/lang/modules/zh.ts
  frontend/src/styles/common.scss
  frontend/src/views/app-store/detail/params/index.vue
  frontend/src/views/app-store/setting/index.vue
  frontend/src/views/website/runtime/python/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8061 feat(website): Optimize website expiration time setting
  agent/app/service/runtime.go
  agent/app/service/website.go
  agent/constant/common.go
  agent/init/migration/migrate.go
  agent/init/migration/migrations/init.go
  frontend/src/views/website/website/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8062 feat(file): Prevent progress display after file download completion
  agent/app/api/v2/file.go
  frontend/src/views/host/file-management/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8065 fix(file): Fix issue with abnormal display when calculating sizes of …
  frontend/src/views/host/file-management/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, dev-v2

#8064 style(common): Adjust file selection UI
  frontend/src/components/file-list/index.vue
  frontend/src/views/website/runtime/node/module/index.vue
  frontend/src/views/website/runtime/php/extension-management/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, dev-v2

#8067 feat: Support script library management
  agent/init/migration/migrations/init.go
  agent/utils/ssh/ssh.go
  core/app/api/v2/entry.go
  core/app/api/v2/host.go
  core/app/api/v2/script_library.go
  core/app/dto/command.go
  core/app/dto/common.go
  core/app/dto/host.go
  core/app/dto/script_library.go
  core/app/model/script_library.go
  core/app/repo/script_library.go
  core/app/service/entry.go
  core/app/service/group.go
  core/app/service/host.go
  core/app/service/script_library.go
  core/go.mod
  core/go.sum
  core/i18n/lang/en.yaml
  core/i18n/lang/ja.yaml
  core/i18n/lang/ko.yaml
  core/i18n/lang/ms.yml
  core/i18n/lang/pt-BR.yaml
  core/i18n/lang/ru.yaml
  core/i18n/lang/zh-Hant.yaml
  core/i18n/lang/zh.yaml
  core/init/migration/migrate.go
  core/init/migration/migrations/init.go
  core/router/common.go
  core/router/ro_script_library.go
  core/utils/ssh/ssh.go
  core/utils/terminal/local_cmd.go
  core/utils/terminal/ws_session.go
  core/utils/xpack/xpack.go
  frontend/src/api/interface/cronjob.ts
  frontend/src/api/modules/cronjob.ts
  frontend/src/components/group/index.vue
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/zh-Hant.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/routers/modules/cronjob.ts
  frontend/src/views/cronjob/cronjob/backup/index.vue
  frontend/src/views/cronjob/cronjob/helper.ts
  frontend/src/views/cronjob/cronjob/index.vue
  frontend/src/views/cronjob/cronjob/operate/index.vue
  frontend/src/views/cronjob/cronjob/record/index.vue
  frontend/src/views/cronjob/index.vue
  frontend/src/views/cronjob/library/index.vue
  frontend/src/views/cronjob/library/operate/index.vue
  frontend/src/views/cronjob/library/run/index.vue
  frontend/src/views/terminal/command/index.vue
  frontend/src/views/toolbox/clean/index.vue
Labels: do-not-merge/release-note-label-needed, dev-v2

#8068 fix(website): fix issue with backup failed in websites
  agent/app/service/backup_website.go
  agent/app/service/website_utils.go
  frontend/src/views/website/website/index.vue
Labels: do-not-merge/release-note-label-needed, dev-v2

#8070 fix: Modify the information about the upper limit of free nodes
  agent/app/service/cronjob.go
  agent/app/service/snapshot_create.go
  agent/utils/files/file_op.go
  core/i18n/lang/en.yaml
  core/i18n/lang/ja.yaml
  core/i18n/lang/ko.yaml
  core/i18n/lang/ms.yml
  core/i18n/lang/pt-BR.yaml
  core/i18n/lang/ru.yaml
  core/i18n/lang/zh-Hant.yaml
  core/i18n/lang/zh.yaml
  frontend/src/components/upload/index.vue
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/zh-Hant.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/layout/components/Sidebar/index.vue
  frontend/src/views/cronjob/cronjob/operate/index.vue
  frontend/src/views/cronjob/cronjob/record/index.vue
  frontend/src/views/setting/license/bind/index.vue
  frontend/src/views/toolbox/clam/index.vue
  frontend/src/views/toolbox/clam/operate/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8071 fix(runtime): fix issue with install extensions failed in php runtime
  agent/app/service/nginx.go
  agent/app/service/runtime.go
  agent/app/service/runtime_utils.go
  agent/utils/cmd/cmd.go
  frontend/src/views/website/runtime/php/create/index.vue
  frontend/src/views/website/runtime/php/extension-management/index.vue
  frontend/src/views/website/runtime/php/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8076 fix(fail2ban): fix the issue of set fail2ban log path err
  frontend/src/views/toolbox/fail2ban/log-path/index.vue
Labels: do-not-merge/release-note-label-needed

#8079 chore: Update README.md
  README.md
Labels: do-not-merge/release-note-label-needed

#8081 feat(style): Update some prompt messages
  agent/app/service/runtime_utils.go
  frontend/src/components/backup/index.vue
  frontend/src/components/upload/index.vue
  frontend/src/global/form-rules.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/zh-Hant.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/website/ssl/ca/detail/index.vue
Labels: do-not-merge/release-note-label-needed, dev-v2

#8083 fix: Fix the backup account synchronization exception
  agent/app/api/v2/backup.go
  agent/app/repo/common.go
  agent/app/service/backup.go
  agent/app/service/backup_record.go
  agent/app/service/device_clean.go
  agent/log/writer.go
  core/app/service/backup.go
  core/constant/common.go
  frontend/src/views/setting/backup-account/index.vue
  frontend/src/views/setting/backup-account/operate/index.vue
  frontend/src/views/toolbox/clean/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, dev-v2

#8085 fix: Split the system log files
  agent/app/service/file.go
  agent/app/service/logs.go
  core/cmd/server/conf/app.yaml
  frontend/src/components/system-upgrade/index.vue
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/zh-Hant.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/log/system/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, dev-v2

#8086 feat(runtime): Optimize port selection for runtime environments
  agent/utils/qqwry/qqwry.go
  frontend/src/components/task-list/index.vue
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/zh-Hant.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/log/task/index.vue
  frontend/src/views/website/runtime/components/port-jump.vue
  frontend/src/views/website/runtime/dotnet/index.vue
  frontend/src/views/website/runtime/go/index.vue
  frontend/src/views/website/runtime/java/index.vue
  frontend/src/views/website/runtime/node/index.vue
  frontend/src/views/website/runtime/python/index.vue
  frontend/src/views/website/website/create/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8088 fix: Fix the restart panel exception
  agent/app/api/v2/dashboard.go
  agent/app/service/ai.go
  agent/app/service/dashboard.go
  agent/router/ro_dashboard.go
  core/app/service/upgrade.go
  core/constant/common.go
  frontend/src/components/terminal/index.vue
  frontend/src/layout/index.vue
  frontend/src/utils/xpack.ts
  frontend/src/views/setting/snapshot/index.vue
  frontend/src/views/toolbox/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8094 fix: Fix the display exception problem when the database application …
  agent/app/dto/backup.go
  agent/app/service/backup_app.go
  agent/app/service/backup_record.go
  agent/app/service/backup_runtime.go
  agent/app/service/backup_website.go
  agent/app/service/cronjob_backup.go
  frontend/src/components/log/task/index.vue
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/zh-Hant.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/database/mysql/index.vue
  frontend/src/views/database/postgresql/index.vue
  frontend/src/views/database/redis/index.vue
Labels: do-not-merge/release-note-label-needed, dev-v2

#8095 fix(container): Fix the problem that a container cannot create a read…
  backend/app/service/container.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#8096 fix(container): Fix cpu surge when the container terminal executes exit
  backend/app/api/v1/terminal.go
  backend/router/ro_ai.go
  backend/router/ro_container.go
  backend/router/ro_database.go
  backend/utils/ssh/ssh.go
  backend/utils/terminal/local_cmd.go
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/ai/model/terminal/index.vue
  frontend/src/views/container/container/terminal/index.vue
  frontend/src/views/database/redis/index.vue
  go.mod
  go.sum
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#8107 feat: Container editing and upgrade support task log display
  agent/app/dto/container.go
  agent/app/service/container.go
  agent/i18n/lang/en.yaml
  agent/i18n/lang/zh-Hant.yaml
  agent/i18n/lang/zh.yaml
  frontend/src/api/interface/container.ts
  frontend/src/api/modules/container.ts
  frontend/src/views/container/container/index.vue
  frontend/src/views/container/container/operate/index.vue
  frontend/src/views/container/container/upgrade/index.vue
Labels: do-not-merge/release-note-label-needed, dev-v2

#8108 fix: Adjust the 1panel service name
  agent/app/service/device.go
  agent/app/service/device_clean.go
  agent/app/service/image.go
  agent/app/service/snapshot_create.go
  agent/app/service/snapshot_recover.go
  agent/app/service/snapshot_rollback.go
  agent/utils/common/common.go
  core/app/service/setting.go
  core/app/service/upgrade.go
  core/cmd/server/cmd/restore.go
Labels: do-not-merge/release-note-label-needed, lgtm, dev-v2

#8110 Update script.sh
  ci/script.sh
Labels: do-not-merge/release-note-label-needed

#8109 fix: fix issue with enable ai https failed
  agent/app/dto/app.go
  agent/app/repo/group.go
  agent/app/service/ai.go
  agent/app/service/group.go
  agent/app/service/website.go
  agent/app/service/website_ssl.go
  agent/app/service/website_utils.go
  frontend/src/global/form-rules.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/zh-Hant.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/ai/model/add/index.vue
  frontend/src/views/website/ssl/ca/obtain/index.vue
  frontend/src/views/website/ssl/create/index.vue
  frontend/src/views/website/ssl/index.vue
  frontend/src/views/website/website/create/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8111 fix: fix issue with download container log
  agent/app/service/container.go
  frontend/package.json
  frontend/src/components/log/compose/index.vue
  frontend/src/components/log/container/index.vue
  frontend/src/components/log/custom-hightlight/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, dev-v2

#8112 feat: Add validation when applying wildcard domain certificates in HT…
  agent/app/service/website_ssl.go
  agent/i18n/lang/zh.yaml
Labels: do-not-merge/release-note-label-needed, dev-v2

#8113 fix: Fix issue with failure to disable website cache
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/zh-Hant.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/host/file-management/code-editor/index.vue
  frontend/src/views/website/website/config/basic/proxy/cache/index.vue
  frontend/src/views/website/website/config/basic/proxy/index.vue
  frontend/src/views/website/website/status/index.vue
Labels: do-not-merge/release-note-label-needed

#8117 fix：Fix issue with error during OpenResty reinstallation
  agent/app/service/app.go
  agent/app/service/app_utils.go
Labels: do-not-merge/release-note-label-needed, lgtm, dev-v2

#8119 fix：fix issue with enable system ssl failed
  agent/cmd/server/nginx_conf/php_extensions.json
  core/app/service/setting.go
  frontend/src/views/website/runtime/php/extension-management/index.vue
Labels: do-not-merge/release-note-label-needed, dev-v2

#8121 feat: Handle websocket and eventsource requests
  core/init/router/proxy.go
  frontend/src/components/log/container/index.vue
  frontend/src/views/host/file-management/process/index.vue
  frontend/src/views/host/process/network/index.vue
  frontend/src/views/host/process/process/index.vue
  frontend/src/views/host/ssh/session/index.vue
Labels: do-not-merge/release-note-label-needed, dev-v2

#8124 fix: Modify the node initialization logic
  agent/app/api/v2/setting.go
  agent/app/repo/app_launcher.go
  agent/app/service/setting.go
  agent/init/db/db.go
  agent/init/hook/hook.go
  agent/init/migration/migrations/init.go
  agent/init/viper/viper.go
  agent/router/ro_setting.go
  agent/utils/files/file_op.go
  agent/utils/xpack/xpack.go
  core/app/service/app_launcher.go
  core/app/service/backup.go
  core/app/service/group.go
  core/app/service/setting.go
  core/utils/req_helper/proxy_local/req_to_local.go
Labels: do-not-merge/release-note-label-needed, dev-v2

#8123 feat: allow tencent cloud cos dual stack domain
  backend/utils/cloud_storage/client/cos.go
Labels: do-not-merge/release-note-label-needed

#8125 fix: Fix the problem of incorrect calculation of container memory res…
  backend/app/service/container.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#8126 fix(website): fix issue with change website type failed
  agent/app/service/website.go
  agent/app/service/website_utils.go
  agent/constant/common.go
  agent/cron/job/website.go
  frontend/src/views/website/website/index.vue
Labels: do-not-merge/release-note-label-needed, dev-v2

#8127 fix: Fix the problem that services exit unexpectedly when the contain…
  backend/utils/terminal/ws_local_session.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#8132 pref: go mod
  go.mod
  go.sum
Labels: do-not-merge/release-note-label-needed, dev, lgtm

#8134 fix: Modify the license promp
  core/i18n/lang/en.yaml
  core/i18n/lang/ja.yaml
  core/i18n/lang/ko.yaml
  core/i18n/lang/ms.yml
  core/i18n/lang/pt-BR.yaml
  core/i18n/lang/ru.yaml
  core/i18n/lang/zh-Hant.yaml
  core/i18n/lang/zh.yaml
  frontend/src/api/modules/setting.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/zh-Hant.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/setting/license/index.vue
Labels: do-not-merge/release-note-label-needed, dev-v2

#8133 feat(appstore): Optimize custom application repository logic
  agent/app/repo/app_install.go
  agent/app/repo/runtime.go
  agent/app/service/app.go
  agent/app/service/app_install.go
  agent/app/service/app_utils.go
  agent/app/service/backup_website.go
  agent/app/service/cronjob_backup.go
  agent/app/service/dashboard.go
  agent/app/service/file.go
  agent/app/service/firewall.go
  agent/app/service/runtime.go
  agent/app/service/runtime_utils.go
  agent/app/service/snapshot.go
  agent/app/service/snapshot_recover.go
  agent/app/service/website.go
  agent/app/service/website_utils.go
  agent/app/task/task.go
  agent/i18n/lang/zh.yaml
  agent/utils/files/file_op.go
  core/i18n/lang/zh.yaml
  core/utils/req_helper/proxy_local/req_to_local.go
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/zh-Hant.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/app-store/apps/index.vue
  frontend/src/views/app-store/installed/check/index.vue
  frontend/src/views/app-store/setting/index.vue
Labels: do-not-merge/release-note-label-needed, dev-v2

#8136 Fix typo in rdbHelper1: Change "秒內" to "秒内" #1
  frontend/src/lang/modules/zh.ts
Labels: do-not-merge/release-note-label-needed

#8135 fix: Fix the problem that the cache clears deleted log files by mistake
  agent/app/repo/task.go
  agent/app/service/backup.go
  agent/app/service/device_clean.go
  agent/app/service/snapshot_recover.go
  core/app/service/backup.go
  core/log/writer.go
  frontend/src/views/ai/model/index.vue
  frontend/src/views/setting/backup-account/operate/index.vue
  frontend/src/views/toolbox/clean/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8138 fix(appstore): Fix issue where uninstalling an application fails when…
  agent/app/service/runtime_utils.go
  agent/utils/docker/compose.go
  frontend/src/views/website/runtime/dotnet/index.vue
  frontend/src/views/website/runtime/go/index.vue
  frontend/src/views/website/runtime/java/index.vue
  frontend/src/views/website/runtime/node/index.vue
  frontend/src/views/website/runtime/php/index.vue
  frontend/src/views/website/runtime/python/index.vue
Labels: do-not-merge/release-note-label-needed, dev-v2

#8139 feat(runtime): Add port validation when creating runtime environment
  agent/app/service/runtime.go
Labels: do-not-merge/release-note-label-needed, dev-v2

#8140 feat(container): optimize image pull display
  agent/app/service/container.go
  agent/app/service/image.go
  agent/utils/docker/docker.go
Labels: do-not-merge/release-note-label-needed, dev-v2

#8141 fix: Fix the firewall startup failure
  agent/app/service/container.go
  agent/app/service/firewall.go
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/zh-Hant.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/container/container/operate/index.vue
  frontend/src/views/container/dashboard/index.vue
  frontend/src/views/container/docker-status/index.vue
  frontend/src/views/database/redis/setting/persistence/index.vue
  frontend/src/views/setting/license/delete/index.vue
  frontend/src/views/setting/license/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8144 fix(cronjob): fix issue with run cut website log failed
  agent/app/repo/cronjob.go
  agent/app/service/app.go
  agent/app/task/task.go
  frontend/src/components/log/container/index.vue
  frontend/src/components/table-setting/index.vue
  frontend/src/components/task-list/index.vue
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/zh-Hant.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/cronjob/cronjob/record/index.vue
  frontend/src/views/database/mysql/setting/index.vue
Labels: do-not-merge/release-note-label-needed, dev-v2

#8145 fix(database): Fix missing database logs
  agent/app/service/container.go
  frontend/src/components/log/container/index.vue
  frontend/src/views/database/mysql/setting/index.vue
  frontend/src/views/database/postgresql/setting/index.vue
Labels: do-not-merge/release-note-label-needed, dev-v2

#8146 feat: update golang.org/x/net version to v0.37.0
  go.mod
Labels: do-not-merge/release-note-label-needed, dev

#8147 fix: Merge dev code up to pr-8141
  agent/app/api/v2/container.go
  agent/app/api/v2/terminal.go
  agent/app/dto/firewall.go
  agent/app/service/backup_mysql.go
  agent/app/service/backup_postgresql.go
  agent/app/service/container.go
  agent/app/service/container_compose.go
  agent/app/service/database_common.go
  agent/app/service/database_mysql.go
  agent/app/service/file.go
  agent/app/service/firewall.go
  agent/router/ai.go
  agent/router/ro_container.go
  agent/router/ro_database.go
  agent/utils/mysql/client/local.go
  agent/utils/mysql/client/remote.go
  agent/utils/terminal/local_cmd.go
  agent/utils/terminal/ws_local_session.go
  core/app/api/v2/setting.go
  core/utils/terminal/ws_local_session.go
  frontend/src/api/modules/container.ts
  frontend/src/api/modules/host.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/zh-Hant.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/ai/model/terminal/index.vue
  frontend/src/views/container/compose/delete/index.vue
  frontend/src/views/container/compose/index.vue
  frontend/src/views/container/container/terminal/index.vue
  frontend/src/views/cronjob/library/run/index.vue
  frontend/src/views/database/mysql/remote/index.vue
  frontend/src/views/database/mysql/setting/helper.ts
  frontend/src/views/database/mysql/setting/index.vue
  frontend/src/views/database/mysql/setting/slow-log/index.vue
  frontend/src/views/database/mysql/setting/variables/index.vue
  frontend/src/views/database/postgresql/remote/index.vue
  frontend/src/views/database/postgresql/setting/index.vue
  frontend/src/views/database/redis/index.vue
  frontend/src/views/host/firewall/forward/index.vue
  frontend/src/views/setting/backup-account/index.vue
Labels: do-not-merge/release-note-label-needed, dev-v2

#8148 fix: Fix the recommended application display exception
  agent/app/api/v2/dashboard.go
  agent/app/dto/dashboard.go
  agent/app/service/dashboard.go
  core/app/service/app_launcher.go
Labels: do-not-merge/release-note-label-needed, dev-v2

#8156 style(website): optimize website config page logic
  frontend/src/views/website/website/config/basic/domain/create/index.vue
  frontend/src/views/website/website/config/basic/index.vue
  frontend/src/views/website/website/config/index.vue
  frontend/src/views/website/website/create/index.vue
  frontend/src/views/website/website/domain-create/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8157 fix: Modify the default group value
  agent/app/service/backup.go
  core/init/migration/migrations/init.go
  frontend/src/api/modules/setting.ts
  frontend/src/components/agent-group/index.vue
  frontend/src/components/group/index.vue
  frontend/src/views/cronjob/cronjob/operate/index.vue
  frontend/src/views/login/components/login-form.vue
  frontend/src/views/setting/license/index.vue
  frontend/src/views/terminal/command/index.vue
  frontend/src/views/terminal/host/index.vue
  frontend/src/views/terminal/host/operate/index.vue
  frontend/src/views/terminal/terminal/host-create.vue
  frontend/src/views/website/website/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8158 feat: Unify the response body of the API interface
  agent/app/api/v2/app_install.go
  agent/app/api/v2/php_extensions.go
  core/cmd/server/main.go
  frontend/src/api/modules/app.ts
  frontend/src/api/modules/runtime.ts
  frontend/src/views/website/runtime/php/create/index.vue
  frontend/src/views/website/website/create/index.vue
Labels: do-not-merge/release-note-label-needed, dev-v2

#8159 style(system): fix issue with enable ssl failed
  core/app/service/setting.go
  frontend/src/views/setting/safe/index.vue
  frontend/src/views/setting/safe/ssl/index.vue
Labels: do-not-merge/release-note-label-needed, dev-v2

#8161 fix: Update zh-Hant translation
  frontend/src/lang/modules/tw.ts
Labels: do-not-merge/release-note-label-needed

#8171 fix(website): fix issue with change default website failed
  agent/app/service/nginx_utils.go
  agent/app/service/website.go
  frontend/src/assets/json/china-name.json
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/zh-Hant.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/website/website/config/basic/index.vue
Labels: do-not-merge/release-note-label-needed, dev-v2

#8172 fix: Fix log file generation failure
  agent/app/service/database_mysql.go
  agent/app/service/snapshot_recover.go
  core/app/api/v2/script_library.go
  core/app/dto/logs.go
  core/app/service/upgrade.go
  core/cmd/server/docs/docs.go
  core/cmd/server/docs/swagger.json
  core/cmd/server/docs/swagger_test.go
  core/cmd/server/docs/x-log.json
  frontend/src/components/table-setting/index.vue
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/zh-Hant.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/cronjob/cronjob/record/index.vue
  frontend/src/views/setting/license/index.vue
Labels: do-not-merge/release-note-label-needed, dev-v2

#8175 fix: Fix the problem that the local backup account modification does …
  agent/app/service/backup.go
  agent/app/service/snapshot_create.go
Labels: do-not-merge/release-note-label-needed, dev-v2

#8176 feat(supervisor): fix issue with open supervisor failed
  agent/app/service/host_tool.go
  frontend/src/assets/json/china/en.json
  frontend/src/assets/json/china/zh.json
  frontend/src/assets/json/world-name.json
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/zh-Hant.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/layout/components/Sidebar/index.vue
  frontend/src/views/toolbox/supervisor/index.vue
  frontend/src/views/toolbox/supervisor/status/index.vue
Labels: do-not-merge/release-note-label-needed, dev-v2

#8183 feat: update buildx and containerd version
  go.mod
  go.sum
Labels: do-not-merge/release-note-label-needed, dev

#8177 feat: Check for duplicate files before uploading/copying/moving
  agent/app/api/v2/file.go
  agent/app/dto/request/file.go
  agent/app/dto/response/file.go
  agent/app/service/file.go
  agent/router/ro_file.go
  core/app/dto/auth.go
  frontend/src/api/interface/file.ts
  frontend/src/api/modules/files.ts
  frontend/src/components/drawer-pro/index.vue
  frontend/src/components/exist-file/index.vue
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/zh-Hant.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/layout/components/Sidebar/index.vue
  frontend/src/views/app-store/index.scss
  frontend/src/views/app-store/installed/index.vue
  frontend/src/views/host/file-management/index.vue
  frontend/src/views/host/file-management/move/index.vue
  frontend/src/views/host/file-management/upload/index.vue
  frontend/src/views/setting/panel/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, dev-v2

#8178 fix: Fix some issues
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/views/website/website/create/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm

#8182 feat: API interface IP whitelist supports IPv6
  agent/app/api/v2/container.go
  core/middleware/session.go
  core/utils/common/common.go
  frontend/src/utils/util.ts
  frontend/src/views/setting/panel/api-interface/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, dev-v2

#8184 fix(appstore): Handle redirection in app store
  agent/utils/ssl/client.go
  frontend/src/components/backup/index.vue
  frontend/src/components/port-jump/index.vue
  frontend/src/global/mimetype.ts
  frontend/src/layout/components/Sidebar/index.vue
  frontend/src/routers/index.ts
  frontend/src/utils/util.ts
  frontend/src/views/app-store/apps/index.vue
  frontend/src/views/app-store/installed/index.vue
  frontend/src/views/app-store/setting/default-domain/index.vue
  frontend/src/views/home/index.vue
  frontend/src/views/setting/panel/proxy/index.vue
  frontend/src/views/website/ssl/dns-account/create/index.vue
Labels: do-not-merge/release-note-label-needed, dev-v2

#8186 feat(ssl): update lego version
  agent/go.mod
  agent/go.sum
Labels: do-not-merge/release-note-label-needed, dev-v2

#8189 fix: Fix the problem that the terminal exit fails
  backend/app/api/v1/terminal.go
  backend/utils/terminal/local_cmd.go
  frontend/src/components/terminal/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#8190 feat: Add the default script information of the script library system
  core/app/service/script_library.go
  core/constant/status.go
  core/init/migration/helper/script.go
  core/init/migration/migrations/init.go
  frontend/src/components/codemirror-pro/drawer.vue
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/zh-Hant.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/ai/model/index.vue
  frontend/src/views/container/compose/detail/index.vue
  frontend/src/views/container/container/index.vue
  frontend/src/views/container/image/index.vue
  frontend/src/views/container/network/index.vue
  frontend/src/views/container/volume/index.vue
  frontend/src/views/cronjob/library/index.vue
  frontend/src/views/cronjob/library/operate/index.vue
  frontend/src/views/home/app/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8195 fix: Fix the problem that some Settings on the panel are abnormal
  core/app/api/v2/setting.go
  core/app/service/command.go
  core/app/service/host.go
  core/init/router/router.go
  frontend/src/components/file-list/index.vue
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/zh-Hant.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/app-store/installed/upgrade/index.vue
  frontend/src/views/database/postgresql/conn/index.vue
  frontend/src/views/login/components/login-form.vue
  frontend/src/views/setting/about/index.vue
  frontend/src/views/setting/expired.vue
  frontend/src/views/setting/panel/api-interface/index.vue
  frontend/src/views/setting/panel/index.vue
  frontend/src/views/terminal/command/index.vue
  frontend/src/views/terminal/command/operate/index.vue
  frontend/src/views/terminal/host/index.vue
  frontend/src/views/terminal/host/operate/index.vue
  frontend/src/views/terminal/terminal/host-create.vue
  frontend/src/views/terminal/terminal/index.vue
  frontend/src/views/website/runtime/php/config/function/index.vue
  frontend/src/views/website/website/config/basic/anti-Leech/index.vue
  frontend/src/views/website/website/config/basic/real-ip/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8197 fix: Node update Added detection information
  core/app/service/upgrade.go
  core/i18n/lang/en.yaml
  core/i18n/lang/ja.yaml
  core/i18n/lang/ko.yaml
  core/i18n/lang/ms.yml
  core/i18n/lang/pt-BR.yaml
  core/i18n/lang/ru.yaml
  core/i18n/lang/zh-Hant.yaml
  core/i18n/lang/zh.yaml
  frontend/src/global/use-theme.ts
  frontend/src/views/toolbox/clam/status/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8200 fix: Modify the loading mode of container construction and push log
  agent/app/service/image.go
  agent/utils/docker/docker.go
  frontend/src/components/status/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, dev-v2

#8206 fix: Adjust menu and node switching styles
  frontend/src/assets/iconfont/iconfont.css
  frontend/src/assets/iconfont/iconfont.js
  frontend/src/assets/iconfont/iconfont.json
  frontend/src/assets/iconfont/iconfont.svg
  frontend/src/assets/iconfont/iconfont.ttf
  frontend/src/assets/iconfont/iconfont.woff
  frontend/src/assets/iconfont/iconfont.woff2
  frontend/src/components/table-setting/index.vue
  frontend/src/components/task-list/index.vue
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/zh-Hant.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/layout/components/Sidebar/components/Collapse.vue
  frontend/src/layout/components/Sidebar/index.vue
  frontend/src/layout/index.vue
  frontend/src/views/container/container/index.vue
  frontend/src/views/setting/panel/index.vue
Labels: do-not-merge/release-note-label-needed, dev-v2

#8212 fix: Operation logs Add node information
  core/app/api/v2/command.go
  core/app/dto/logs.go
  core/app/model/logs.go
  core/app/repo/common.go
  core/app/service/command.go
  core/app/service/logs.go
  core/i18n/i18n.go
  core/init/migration/migrate.go
  core/init/migration/migrations/init.go
  core/middleware/operation.go
  frontend/src/components/log/custom-hightlight/index.vue
  frontend/src/components/system-upgrade/index.vue
  frontend/src/layout/index.vue
  frontend/src/views/cronjob/cronjob/index.vue
  frontend/src/views/cronjob/cronjob/record/index.vue
  frontend/src/views/cronjob/library/index.vue
  frontend/src/views/cronjob/library/operate/index.vue
  frontend/src/views/database/postgresql/setting/index.vue
  frontend/src/views/database/redis/remote/index.vue
  frontend/src/views/database/redis/setting/index.vue
  frontend/src/views/log/operation/index.vue
  frontend/src/views/log/system/index.vue
  frontend/src/views/login/components/login-form.vue
  frontend/src/views/setting/panel/index.vue
  frontend/src/views/terminal/terminal/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8213 fix: Modify session verification on the interface
  core/init/router/router.go
  frontend/src/api/interface/auth.ts
  frontend/src/views/login/components/login-form.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8216 fix: Fix the problem that the snapshot file download path is incorrect
  agent/app/service/backup.go
  agent/app/service/snapshot_recover.go
  agent/init/hook/hook.go
  core/app/service/backup.go
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/zh-Hant.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/container/dashboard/index.vue
  frontend/src/views/container/setting/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8217 fix: Fixed an issue where no default button is set for groups
  frontend/src/components/group/index.vue
  frontend/src/views/cronjob/library/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8223 fix: Fix the abnormal status of the ollama model
  agent/app/service/ai.go
  frontend/src/views/ai/model/del/index.vue
  frontend/src/views/ai/model/terminal/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8224 feat(website): fix issue with create load-balance failed
  agent/app/service/app.go
  agent/app/service/app_utils.go
  agent/app/service/website.go
  agent/app/service/website_utils.go
  agent/server/server.go
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/zh-Hant.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/website/website/config/basic/load-balance/index.vue
  frontend/src/views/website/website/config/basic/load-balance/operate/index.vue
  frontend/src/views/website/website/config/basic/resource/index.vue
  frontend/tsconfig.json
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8228 fix: fix some snapshot problems
  agent/app/service/snapshot.go
  agent/app/service/snapshot_create.go
  agent/app/service/snapshot_recover.go
  agent/utils/common/sqlite.go
  core/app/service/upgrade.go
  core/cmd/server/cmd/restore.go
  frontend/src/components/task-list/index.vue
  frontend/src/layout/components/Sidebar/index.vue
  frontend/src/views/cronjob/library/index.vue
  frontend/src/views/host/firewall/ip/index.vue
  frontend/src/views/host/firewall/port/index.vue
  frontend/src/views/host/ssh/log/log.vue
  frontend/src/views/log/login/index.vue
  frontend/src/views/log/system/index.vue
  frontend/src/views/log/task/index.vue
  frontend/src/views/log/website/index.vue
  frontend/src/views/setting/snapshot/create/index.vue
  frontend/src/views/setting/snapshot/index.vue
  frontend/src/views/terminal/command/index.vue
  frontend/src/views/website/website/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, dev-v2

#8230 feat(runtime): fix issue with install php runtime failed
  agent/app/dto/response/website.go
  agent/app/service/app.go
  agent/app/service/website.go
  agent/utils/common/common.go
  frontend/src/api/interface/website.ts
  frontend/src/views/website/website/config/basic/index.vue
  frontend/src/views/website/website/config/basic/resource/index.vue
  frontend/src/views/website/website/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8234 fix: Fix backup compression failure
  agent/app/service/backup_website.go
  agent/app/service/cronjob_backup.go
  agent/utils/files/file_op.go
  frontend/src/components/backup/index.vue
  frontend/src/components/log/hightlight-log/index.vue
  frontend/src/views/container/setting/sock-path/index.vue
  frontend/src/views/log/operation/index.vue
  frontend/src/views/toolbox/clam/record/index.vue
  frontend/src/views/toolbox/clam/setting/index.vue
  frontend/src/views/toolbox/clam/status/index.vue
  frontend/src/views/toolbox/device/hosts/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8207 feat: add DNS provider ClouDNS
  backend/utils/ssl/client.go
  frontend/src/global/mimetype.ts
  frontend/src/views/website/ssl/dns-account/create/index.vue
Labels: do-not-merge/release-note-label-needed

#8237 fix(file): fix issue with download process not work
  agent/app/api/v2/file.go
  agent/utils/websocket/process_data.go
  frontend/src/views/toolbox/supervisor/file/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8242 fix: Remove the jwt login mode
  agent/app/service/device_clean.go
  core/app/api/v2/auth.go
  core/app/dto/auth.go
  core/app/service/auth.go
  core/app/service/upgrade.go
  core/constant/session.go
  core/go.mod
  core/go.sum
  core/init/migration/helper/script.go
  core/init/router/router.go
  core/middleware/jwt.go
  core/middleware/session.go
  core/router/app_launcher.go
  core/router/command.go
  core/router/ro_backup.go
  core/router/ro_group.go
  core/router/ro_host.go
  core/router/ro_log.go
  core/router/ro_script_library.go
  core/router/ro_setting.go
  core/utils/jwt/jwt.go
  frontend/src/api/modules/toolbox.ts
  frontend/src/components/log/hightlight-log/index.vue
  frontend/src/components/system-upgrade/upgrade/index.vue
  frontend/src/views/terminal/terminal/index.vue
  frontend/src/views/toolbox/clam/record/index.vue
  frontend/src/views/toolbox/clean/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8246 fix(app): fix issue with sync custom-app failed
  agent/app/service/website.go
  agent/utils/files/file_op.go
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8245 fix: Delete the data generated by the current snapshot
  agent/app/api/v2/snapshot.go
  agent/app/service/cronjob_backup.go
  agent/app/service/cronjob_helper.go
  agent/app/service/firewall.go
  agent/app/service/snapshot.go
  agent/app/service/snapshot_create.go
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8247 fix(system): fix issue with change system ssl failed
  agent/i18n/lang/zh.yaml
  core/app/api/v2/auth.go
  core/app/service/setting.go
  core/utils/common/common.go
  frontend/src/components/log/custom-hightlight/index.vue
  frontend/src/views/setting/safe/ssl/index.vue
Labels: do-not-merge/release-note-label-needed, dev-v2

#8248 feat: Added a reminder when the drawer is closed
  frontend/src/components/drawer-pro/index.vue
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/zh-Hant.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/home/status/index.vue
Labels: do-not-merge/release-note-label-needed, dev-v2

#8253 fix: Node switchover is cancelled when the master node unbinds the li…
  frontend/src/components/drawer-pro/index.vue
  frontend/src/lang/modules/zh.ts
  frontend/src/layout/components/Sidebar/components/Collapse.vue
  frontend/src/views/login/components/login-form.vue
  frontend/src/views/setting/safe/index.vue
  frontend/src/views/toolbox/fail2ban/log-path/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8262 fix: Optimize script library scripts and execution methods
  core/app/api/v2/script_library.go
  core/init/migration/helper/script.go
  core/utils/terminal/local_cmd.go
  frontend/src/components/drawer-pro/index.vue
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/zh-Hant.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/cronjob/library/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8263 fix: Fix the failure to back up file names containing Spaces for sche…
  agent/app/service/cronjob_backup.go
  agent/utils/files/file_op.go
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/zh-Hant.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/ai/model/del/index.vue
  frontend/src/views/log/operation/index.vue
Labels: do-not-merge/release-note-label-needed, dev-v2

#8268 fix: Fix the exception of some 1pctl commands
  agent/app/service/backup_record.go
  agent/utils/cloud_storage/client/up.go
  core/app/service/upgrade.go
  core/cmd/server/cmd/listen-ip.go
  core/cmd/server/cmd/reset.go
  core/cmd/server/cmd/restore.go
  core/cmd/server/cmd/update.go
  core/cmd/server/cmd/user-info.go
  core/i18n/lang/en.yaml
  core/i18n/lang/ja.yaml
  core/i18n/lang/ko.yaml
  core/i18n/lang/ms.yml
  core/i18n/lang/pt-BR.yaml
  core/i18n/lang/ru.yaml
  core/i18n/lang/zh-Hant.yaml
  core/i18n/lang/zh.yaml
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/zh-Hant.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/layout/components/Sidebar/components/Collapse.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8269 feat(website): Restrict unhealthy application selection during websit…
  core/app/api/v2/auth.go
  frontend/src/assets/json/iso.json
  frontend/src/views/login/components/login-form.vue
  frontend/src/views/website/website/create/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8270 fix: Cancel synchronization between recommended nodes on dashboard
  agent/app/api/v2/dashboard.go
  agent/app/repo/app_launcher.go
  agent/app/repo/common.go
  agent/app/service/dashboard.go
  agent/app/service/device_clean.go
  agent/router/ro_dashboard.go
  core/app/api/v2/app_launcher.go
  core/app/api/v2/entry.go
  core/app/model/app_launcher.go
  core/app/repo/app_launcher.go
  core/app/service/app_launcher.go
  core/app/service/entry.go
  core/cmd/server/cmd/restore.go
  core/init/migration/migrate.go
  core/init/migration/migrations/init.go
  core/router/app_launcher.go
  core/router/common.go
  frontend/src/api/modules/dashboard.ts
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8272 feat(website): fix issues with create website with ftp failed
  agent/app/service/app_install.go
  agent/app/service/runtime_utils.go
  agent/app/service/website.go
  agent/server/server.go
  agent/utils/nginx/dumper.go
  core/app/service/setting.go
  core/init/router/proxy.go
  core/middleware/api_auth.go
  frontend/src/global/mimetype.ts
  frontend/src/views/website/website/config/basic/auth-basic/index.vue
  frontend/src/views/website/website/config/basic/load-balance/operate/index.vue
Labels: do-not-merge/release-note-label-needed, dev-v2

#8280 fix: Fix the problem that the website directory is not backed up duri…
  agent/app/service/app_install.go
  agent/app/service/snapshot.go
  agent/app/service/snapshot_create.go
  agent/app/service/snapshot_recover.go
  agent/app/service/snapshot_rollback.go
  agent/constant/status.go
  agent/i18n/lang/en.yaml
  agent/i18n/lang/ja.yaml
  agent/i18n/lang/ko.yaml
  agent/i18n/lang/ms.yaml
  agent/i18n/lang/ms.yml
  agent/i18n/lang/pt-BR.yaml
  agent/i18n/lang/ru.yaml
  agent/i18n/lang/zh-Hant.yaml
  agent/i18n/lang/zh.yaml
  agent/init/dir/dir.go
  core/i18n/lang/en.yaml
  core/i18n/lang/ja.yaml
  core/i18n/lang/ko.yaml
  core/i18n/lang/ms.yml
  core/i18n/lang/pt-BR.yaml
  core/i18n/lang/ru.yaml
  core/i18n/lang/zh-Hant.yaml
  core/i18n/lang/zh.yaml
  frontend/src/views/setting/snapshot/create/index.vue
  frontend/src/views/setting/snapshot/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8281 fix: Fix the problem of recovering application and website task logs
  agent/app/service/backup_app.go
  agent/app/service/backup_website.go
  agent/app/service/cronjob_backup.go
  core/i18n/lang/en.yaml
  core/i18n/lang/ja.yaml
  core/i18n/lang/ko.yaml
  core/i18n/lang/ms.yml
  core/i18n/lang/pt-BR.yaml
  core/i18n/lang/ru.yaml
  core/i18n/lang/zh-Hant.yaml
  core/i18n/lang/zh.yaml
Labels: do-not-merge/release-note-label-needed, dev-v2
