Repository 1Panel-dev/1Panel, pull requests merged in 2025-05, with the labels that each got.

#8534 feat: install openresty with default ssl
  agent/app/service/app_utils.go
  agent/app/service/nginx_utils.go
  agent/app/service/website_ca.go
  agent/app/service/website_utils.go
  agent/cmd/server/nginx_conf/root_ssl.conf
  agent/cmd/server/nginx_conf/ssl.conf
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8529 fix: the docker image which no tag but used be pruned
  frontend/src/views/container/image/prune/index.vue
Labels: do-not-merge/release-note-label-needed

#8540 feat: Add the cleaning of the execution script
  agent/app/service/device_clean.go
  frontend/src/views/toolbox/clean/index.vue
Labels: do-not-merge/release-note-label-needed, dev-v2

#8538 fix: Modify the script and upload the file name
  core/app/api/v2/script_library.go
  frontend/src/views/cronjob/library/index.vue
  frontend/src/views/cronjob/library/operate/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8548 feat: Add demo mode handling
  core/middleware/demo_handle.go
  frontend/src/components/group/change.vue
  frontend/src/components/log/file-drawer/index.vue
  frontend/src/layout/index.vue
  frontend/src/views/website/runtime/app/index.vue
  frontend/src/views/website/runtime/components/port-jump.vue
  frontend/src/views/website/runtime/components/runtime-status.vue
  frontend/src/views/website/runtime/dir/index.vue
  frontend/src/views/website/runtime/environment/index.vue
  frontend/src/views/website/runtime/php/index.vue
  frontend/src/views/website/runtime/port/index.vue
  frontend/src/views/website/runtime/volume/index.vue
  frontend/src/views/website/ssl/index.vue
  frontend/src/views/website/website/config/basic/index.vue
  frontend/src/views/website/website/config/basic/load-balance/index.vue
Labels: do-not-merge/release-note-label-needed, dev-v2

#8549 feat: Fix issue where added certificate domains become ineffective.
  agent/app/service/website.go
  agent/app/service/website_utils.go
  agent/i18n/lang/en.yaml
  agent/i18n/lang/ja.yaml
  agent/i18n/lang/ko.yaml
  agent/i18n/lang/ms.yaml
  agent/i18n/lang/pt-BR.yaml
  agent/i18n/lang/ru.yaml
  agent/i18n/lang/zh-Hant.yaml
  agent/i18n/lang/zh.yaml
  frontend/src/views/website/runtime/php/index.vue
  frontend/src/views/website/website/config/basic/https/index.vue
Labels: do-not-merge/release-note-label-needed, dev-v2

#8550 feat: Update agent appstore setting to core
  agent/app/api/v2/app.go
  agent/app/dto/request/app.go
  agent/app/dto/response/app.go
  agent/app/service/app.go
  agent/router/ro_app.go
  core/app/api/v2/setting.go
  core/app/dto/setting.go
  core/app/service/setting.go
  core/init/migration/migrate.go
  core/init/migration/migrations/init.go
  core/router/ro_setting.go
  frontend/src/api/modules/app.ts
  frontend/src/api/modules/setting.ts
  frontend/src/views/app-store/installed/delete/index.vue
  frontend/src/views/app-store/installed/upgrade/index.vue
  frontend/src/views/app-store/setting/index.vue
  frontend/src/views/home/app/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8552 feat: Support the selection of scripts from the script library for cr…
  agent/app/api/v2/cronjob.go
  agent/app/dto/cronjob.go
  agent/app/model/cronjob.go
  agent/app/repo/script.go
  agent/app/service/cronjob.go
  agent/app/service/cronjob_helper.go
  agent/app/service/entry.go
  agent/init/migration/migrations/init.go
  agent/router/ro_cronjob.go
  core/app/dto/script_library.go
  core/app/model/script_library.go
  core/app/service/script_library.go
  core/app/service/setting.go
  core/constant/common.go
  core/i18n/i18n.go
  core/init/migration/migrations/init.go
  frontend/src/api/interface/cronjob.ts
  frontend/src/api/modules/cronjob.ts
  frontend/src/components/layout-col/form.vue
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/zh-Hant.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/container/container/index.vue
  frontend/src/views/cronjob/cronjob/operate/index.vue
  frontend/src/views/cronjob/library/index.vue
  frontend/src/views/cronjob/library/operate/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8553 fix: Fix the problem of abnormal display of database connection infor…
  frontend/src/views/database/mysql/conn/index.vue
  frontend/src/views/database/postgresql/conn/index.vue
  frontend/src/views/database/redis/conn/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8554 fix: fix issue with appstore
  core/app/service/backup.go
  core/app/service/group.go
  core/app/service/setting.go
  core/i18n/i18n.go
  core/init/geo/lang.go
  core/server/server.go
  core/utils/req_helper/proxy_local/req_to_local.go
  frontend/src/views/app-store/installed/ignore/index.vue
Labels: do-not-merge/release-note-label-needed, dev-v2

#8555 fix: Fix the problem of snapshot timeout
  agent/app/service/snapshot_create.go
  agent/app/service/snapshot_recover.go
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8559 fix: Fix the problem of snapshot synchronization failure
  agent/app/service/backup.go
  agent/app/service/backup_record.go
  agent/app/service/snapshot.go
Labels: do-not-merge/release-note-label-needed, dev-v2

#8560 style: Adjust the style of the ssh configuration page
  frontend/src/views/container/setting/index.vue
  frontend/src/views/host/ssh/ssh/index.vue
  frontend/src/views/setting/backup-account/index.vue
  frontend/src/views/setting/backup-account/operate/index.vue
Labels: do-not-merge/release-note-label-needed, dev-v2

#8561 feat: sync i18n setting to agent
  agent/i18n/i18n.go
  agent/server/server.go
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8562 style: Optimize page style
  frontend/src/components/layout-content/index.vue
  frontend/src/layout/components/Tabs/index.vue
  frontend/src/layout/index.vue
  frontend/src/styles/common.scss
  frontend/src/views/host/file-management/index.vue
  frontend/src/views/website/website/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8567 fix: fix some bugs with appstore
  agent/app/dto/app.go
  agent/app/repo/app.go
  agent/app/service/app_utils.go
  agent/app/service/nginx.go
  agent/app/task/task.go
  agent/i18n/lang/en.yaml
  agent/i18n/lang/ja.yaml
  agent/i18n/lang/ko.yaml
  agent/i18n/lang/ms.yaml
  agent/i18n/lang/pt-BR.yaml
  agent/i18n/lang/ru.yaml
  agent/i18n/lang/zh-Hant.yaml
  agent/i18n/lang/zh.yaml
  agent/utils/cmd/cmdx.go
  agent/utils/compose/compose.go
  frontend/src/components/log/container/index.vue
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/zh-Hant.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/website/website/nginx/module/build/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8568 feat: Improve alert
  frontend/src/api/modules/setting.ts
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8569 fix: Modify the planned task script display
  agent/app/api/v2/container.go
  agent/app/repo/setting.go
  agent/app/service/container.go
  agent/app/service/cronjob.go
  agent/init/migration/migrate.go
  agent/init/migration/migrations/init.go
  frontend/src/api/interface/cronjob.ts
  frontend/src/api/modules/cronjob.ts
  frontend/src/views/cronjob/cronjob/operate/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8576 fix: change some translate
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/zh-Hant.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/app-store/installed/index.vue
  frontend/src/views/website/runtime/php/supervisor/create/index.vue
  frontend/src/views/website/ssl/create/index.vue
  frontend/src/views/website/website/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8580 fix: Modify the execution mode of the planned tasks
  agent/app/api/v2/snapshot.go
  agent/app/repo/cronjob.go
  agent/app/service/backup_app.go
  agent/app/service/backup_mysql.go
  agent/app/service/backup_postgresql.go
  agent/app/service/backup_website.go
  agent/app/service/cronjob.go
  agent/app/service/cronjob_backup.go
  agent/app/service/cronjob_helper.go
  agent/app/service/device_clean.go
  agent/app/service/snapshot.go
  agent/app/service/snapshot_create.go
  agent/app/task/task.go
  agent/i18n/lang/en.yaml
  agent/i18n/lang/ja.yaml
  agent/i18n/lang/ko.yaml
  agent/i18n/lang/ms.yaml
  agent/i18n/lang/pt-BR.yaml
  agent/i18n/lang/ru.yaml
  agent/i18n/lang/zh-Hant.yaml
  agent/i18n/lang/zh.yaml
  agent/utils/files/file_op.go
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8581 refactor: Improve optimize code
  frontend/package.json
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/zh-Hant.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/layout/index.vue
  frontend/src/views/host/file-management/index.vue
  frontend/src/views/setting/panel/index.vue
  frontend/vite.config.ts
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8582 fix: Modify the license import logic
  frontend/src/api/modules/setting.ts
  frontend/src/views/setting/license/bind/xpack.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8583 fix: fix somme issue with runtime
  agent/app/service/app_utils.go
  agent/app/service/runtime.go
  agent/app/service/runtime_utils.go
  agent/cmd/server/nginx_conf/php_extensions.json
  agent/cmd/server/nginx_conf/website_default.conf
  agent/init/business/business.go
  frontend/src/global/mimetype.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/zh-Hant.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/styles/common.scss
  frontend/src/views/website/runtime/components/port-jump.vue
  frontend/src/views/website/runtime/dotnet/index.vue
  frontend/src/views/website/runtime/dotnet/operate/index.vue
  frontend/src/views/website/runtime/environment/index.vue
  frontend/src/views/website/runtime/go/index.vue
  frontend/src/views/website/runtime/go/operate/index.vue
  frontend/src/views/website/runtime/java/index.vue
  frontend/src/views/website/runtime/java/operate/index.vue
  frontend/src/views/website/runtime/node/index.vue
  frontend/src/views/website/runtime/node/operate/index.vue
  frontend/src/views/website/runtime/php/create/index.vue
  frontend/src/views/website/runtime/port/index.vue
  frontend/src/views/website/runtime/python/index.vue
  frontend/src/views/website/runtime/python/operate/index.vue
  frontend/src/views/website/runtime/volume/index.vue
  frontend/src/views/website/website/create/index.vue
  frontend/src/views/website/website/domain-create/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8584 feat: The script library synchronizes and adds task logs
  agent/app/repo/script.go
  core/app/api/v2/script_library.go
  core/app/dto/common.go
  core/app/service/script_library.go
  core/init/cron/job/script.go
  frontend/src/api/modules/cronjob.ts
  frontend/src/components/layout-content/no-such-service.vue
  frontend/src/views/cronjob/library/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8585 fix: Fix the problem of adding exceptions to the image repository
  agent/app/service/image_repo.go
Labels: do-not-merge/release-note-label-needed, dev-v2

#8591 fix: Snapshots ignore the original existing snapshot files
  agent/app/service/cronjob_helper.go
  agent/app/service/snapshot.go
  agent/app/service/snapshot_create.go
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8592 style: Optimization of the loading style of the overview page
  frontend/src/views/home/app/index.vue
  frontend/src/views/home/index.vue
  frontend/src/views/home/status/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8594 fix: fix somme issue with website
  frontend/src/views/website/runtime/php/create/index.vue
  frontend/src/views/website/website/config/basic/other/index.vue
  frontend/src/views/website/website/create/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8596 fix: Fix the problem of eliminating file exceptions in the backup dir…
  agent/utils/files/file_op.go
  core/utils/files/files.go
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8598 fix: Modify system version upgrade restrictions
  core/app/service/upgrade.go
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8597 feat: Support downloading scheduled task website log rotation files
  agent/app/dto/cronjob.go
  agent/app/service/cronjob.go
  agent/app/service/cronjob_helper.go
  frontend/src/api/interface/cronjob.ts
  frontend/src/api/modules/cronjob.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/zh-Hant.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/cronjob/cronjob/helper.ts
  frontend/src/views/cronjob/cronjob/index.vue
  frontend/src/views/cronjob/cronjob/record/index.vue
  frontend/src/views/setting/license/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8604 fix: Fix the problem of failed task log acquisition
  frontend/src/api/index.ts
  frontend/src/api/modules/files.ts
  frontend/src/components/log/file/index.vue
  frontend/src/components/log/task/index.vue
  frontend/src/views/cronjob/library/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8605 fix: Adjust the order and name of the menu
  core/init/migration/helper/menu.go
  core/init/migration/migrations/init.go
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8607 feat: Adjust offline alert settings
  frontend/src/components/dialog-pro/index.vue
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/zh-Hant.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/layout/components/Sidebar/components/Collapse.vue
  frontend/src/store/interface/index.ts
  frontend/src/store/modules/global.ts
  frontend/src/utils/xpack.ts
  frontend/src/views/login/components/login-form.vue
Labels: do-not-merge/release-note-label-needed, lgtm, dev-v2

#8610 fix: Fix issue with update website config
  backend/app/service/website.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#8611 fix: fix issue with update website config
  agent/app/service/website.go
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8613 fix: Disable the free license editing button
  frontend/src/views/setting/license/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8614 fix: Simplify the migration information
  agent/init/migration/migrate.go
  agent/init/migration/migrations/init.go
  core/init/migration/migrate.go
  core/init/migration/migrations/init.go
Labels: do-not-merge/release-note-label-needed, lgtm, dev-v2

#8616 style: Adjust the display of license binding information
  frontend/src/views/setting/license/index.vue
Labels: do-not-merge/release-note-label-needed, dev-v2

#8615 feat: add some translate
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/zh-Hant.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/utils/util.ts
  frontend/src/views/website/runtime/php/supervisor/create/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8617 fix: fix issue with blank description
  agent/app/model/app.go
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8618 fix: fix issue with blank php app
  Makefile
  agent/app/service/app.go
Labels: do-not-merge/release-note-label-needed, dev-v2

#8620 style: Adjust the order of the drop-down boxes for backup accounts
  frontend/src/views/setting/backup-account/operate/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8626 fix: Initialize the script library when the service starts
  core/app/service/script_library.go
  core/init/run/run.go
  core/server/server.go
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8627 style: Limit the display length of the node
  frontend/src/layout/components/Sidebar/components/Collapse.vue
  frontend/src/views/toolbox/clean/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8629 style: change some style
  agent/app/service/app_utils.go
  agent/i18n/lang/zh.yaml
  frontend/src/views/website/runtime/environment/index.vue
  frontend/src/views/website/runtime/php/create/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8630 fix: fix issue with install runtime
  agent/app/service/app.go
  agent/app/service/runtime_utils.go
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8631 fix: Fix the problem of abnormal synchronization of the script library
  core/app/service/script_library.go
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8637 fix: fix issue with clear the reverse proxy cache
  agent/app/service/website.go
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8638 fix: Modify the container jump path
  frontend/src/views/container/dashboard/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8639 fix: Delete the unused fields
  core/app/dto/setting.go
  core/init/migration/migrations/init.go
  frontend/src/views/setting/panel/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8640 fix: Fix the abnormal problems that occur when the license is unbound
  frontend/src/api/index.ts
  frontend/src/enums/http-enum.ts
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8650 fix: Fix the problem of failed quick command editing
  core/app/dto/command.go
  core/app/service/command.go
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8651 fix: Remove the redundant log print content
  core/app/service/upgrade.go
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8658 fix: fix issue with set default website error
  agent/app/service/app_utils.go
  agent/app/service/nginx_utils.go
  agent/app/service/website.go
Labels: do-not-merge/release-note-label-needed, lgtm, dev-v2

#8664 feat: remove \n with mcp command
  agent/app/service/mcp_server.go
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/zh-Hant.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/app-store/installed/index.vue
  frontend/src/views/home/app/index.vue
  frontend/src/views/website/runtime/environment/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8676 fix: Fix the problem of abnormal display of snapshot task logs
  agent/app/service/cronjob_helper.go
  frontend/src/views/setting/snapshot/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8680 feat: change docker pull process log
  agent/app/service/app_utils.go
  agent/app/service/nginx_utils.go
  agent/utils/docker/docker.go
  frontend/src/global/mimetype.ts
  frontend/src/views/website/website/create/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, dev-v2

#8685 fix: Fix the problem of abnormal switching of Chinese nodes
  core/init/router/proxy.go
  frontend/src/api/index.ts
  frontend/src/lang/modules/en.ts
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8687 feat: update WebsiteTypes usage
  frontend/src/views/website/website/index.vue
Labels: do-not-merge/release-note-label-needed, dev-v2

#8689 style: Mobile style optimization
  frontend/src/global/mimetype.ts
  frontend/src/layout/components/MobileHeader.vue
  frontend/src/layout/index.vue
  frontend/src/views/home/index.vue
Labels: dev-v2

#8688 fix: fix error translate from website
  frontend/src/global/mimetype.ts
  frontend/src/views/website/website/config/basic/load-balance/index.vue
  frontend/src/views/website/website/config/basic/load-balance/operate/index.vue
Labels: dev-v2

#8691 fix: Cronjob backup supports multiple selections
  agent/app/service/cronjob_backup.go
  frontend/src/api/interface/cronjob.ts
  frontend/src/views/cronjob/cronjob/operate/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8717 fix: fix issue with set default group
  agent/app/repo/group.go
  agent/app/service/group.go
  agent/app/service/website.go
  core/app/dto/task.go
  core/app/service/task.go
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8723 fix: Fix the issue of abnormal display of the professional version of…
  frontend/src/views/home/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8733 fix: Modify the default timeout of the planned task
  frontend/src/views/cronjob/cronjob/operate/index.vue
Labels: do-not-merge/release-note-label-needed, dev-v2

#8734 fix: fix issue with add supervisor config error
  frontend/src/views/website/runtime/php/supervisor/create/index.vue
  frontend/src/views/website/runtime/php/supervisor/index.vue
Labels: dev-v2

#8736 fix: Fix the problem of the exclusion directory failure in cronjob
  agent/app/service/snapshot_create.go
  agent/utils/cmd/cmdx.go
  agent/utils/files/file_op.go
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/zh-Hant.ts
  frontend/src/lang/modules/zh.ts
Labels: dev-v2

#8738 feat: Multi tab editing file
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/zh-Hant.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/styles/common.scss
  frontend/src/views/host/file-management/code-editor/index.vue
  frontend/src/views/host/file-management/index.vue
Labels: dev-v2

#8740 fix: Fix the problem of abnormal default check items in snapshots
  agent/app/service/snapshot.go
Labels: dev-v2

#8747 fix: Fix the issue of abnormal token refreshing on alipan
  agent/app/service/backup.go
  agent/cron/job/backup.go
  agent/utils/cloud_storage/client/ali.go
  core/app/service/backup.go
  core/init/cron/job/backup.go
  core/utils/cloud_storage/client/ali.go
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/zh-Hant.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/setting/backup-account/index.vue
Labels: dev-v2

#8749 fix: code editor
  frontend/src/views/host/file-management/code-editor/index.vue
Labels: lgtm, approved, dev-v2

#8751 feat: code editor tab component
  frontend/src/views/host/file-management/code-editor/tabs/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8753 fix: fix issue with build failed
  frontend/src/views/app-store/apps/index.vue
  frontend/src/views/app-store/components/tag.vue
  frontend/src/views/app-store/installed/index.vue
  frontend/src/views/app-store/setting/index.vue
Labels: do-not-merge/release-note-label-needed, dev-v2

#8752 fix: Fix the problem of failed application backup
  agent/app/service/backup_app.go
  agent/app/service/backup_mysql.go
  agent/app/service/backup_postgresql.go
  agent/app/service/backup_website.go
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8755 feat: Optimize the manual certificate application process
  agent/utils/ssl/client.go
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8758 feat: add terminal for runtimes
  agent/app/service/host_tool.go
  frontend/src/views/website/runtime/components/terminal.vue
  frontend/src/views/website/runtime/dotnet/index.vue
  frontend/src/views/website/runtime/go/index.vue
  frontend/src/views/website/runtime/java/index.vue
  frontend/src/views/website/runtime/node/index.vue
  frontend/src/views/website/runtime/php/index.vue
  frontend/src/views/website/runtime/python/index.vue
Labels: do-not-merge/release-note-label-needed, dev-v2

#8759 fix: Fix the issue of abnormal logs in Cronjob backup directory
  agent/app/service/cronjob_backup.go
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/zh-Hant.ts
  frontend/src/lang/modules/zh.ts
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8762 feat: Multi directory calculation size
  agent/app/api/v2/file.go
  agent/app/dto/response/file.go
  agent/app/service/file.go
  agent/router/ro_file.go
  agent/utils/files/file_op.go
  frontend/src/api/interface/file.ts
  frontend/src/api/modules/files.ts
  frontend/src/components/complex-table/index.vue
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/zh-Hant.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/host/file-management/code-editor/index.vue
  frontend/src/views/host/file-management/code-editor/tabs/index.vue
  frontend/src/views/host/file-management/index.vue
Labels: dev-v2

#8764 style: change runtime terminal style
  agent/cmd/server/nginx_conf/php_extensions.json
  frontend/src/views/website/runtime/components/terminal.vue
  frontend/src/views/website/runtime/php/index.vue
Labels: dev-v2

#8763 style: Modify the node to add prompt information
  core/app/service/host.go
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/zh-Hant.ts
  frontend/src/lang/modules/zh.ts
Labels: dev-v2

#8767 style: Modify the node to add prompt information
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/zh-Hant.ts
  frontend/src/lang/modules/zh.ts
Labels: dev-v2

#8772 feat: Refactor reverse proxy to reuse Transport and enable connection pooling
  core/init/proxy/proxy.go
  core/init/router/proxy.go
  core/server/server.go
Labels: dev-v2

#8773 fix: Improve the task log for adding nodes
  core/i18n/lang/en.yaml
  core/i18n/lang/ja.yaml
  core/i18n/lang/ko.yaml
  core/i18n/lang/ms.yml
  core/i18n/lang/pt-BR.yaml
  core/i18n/lang/ru.yaml
  core/i18n/lang/zh-Hant.yaml
  core/i18n/lang/zh.yaml
Labels: dev-v2

#8774 fix: fix issue with sync app failed with docker stop
  agent/app/service/app_utils.go
  agent/i18n/lang/en.yaml
  agent/i18n/lang/ja.yaml
  agent/i18n/lang/ko.yaml
  agent/i18n/lang/ms.yaml
  agent/i18n/lang/pt-BR.yaml
  agent/i18n/lang/ru.yaml
  agent/i18n/lang/zh-Hant.yaml
  agent/i18n/lang/zh.yaml
  frontend/src/views/app-store/installed/index.vue
Labels: dev-v2

#8775 fix: Fix the problem of abnormal display on the docker state switch
  frontend/src/views/container/setting/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8781 feat: Current directory and file numbers
  frontend/src/components/complex-table/index.vue
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/zh-Hant.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/host/file-management/code-editor/index.vue
  frontend/src/views/host/file-management/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8782 feat: add .user.ini for php website
  agent/app/service/runtime_utils.go
  agent/app/service/website.go
  agent/app/service/website_utils.go
  agent/utils/ssl/acme.go
  agent/utils/ssl/client.go
  agent/utils/ssl/custom_manual_provider.go
  agent/utils/ssl/dns_provider.go
  frontend/src/components/log/task/index.vue
  frontend/src/views/app-store/apps/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8783 fix: Fixed the issue of switching file highlighting
  frontend/src/views/host/file-management/code-editor/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8784 fix: code editor font color
  frontend/src/views/host/file-management/code-editor/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8787 fix: Fix the problem of abnormal deletion of manual backup records
  agent/app/service/backup_record.go
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8790 fix: Fix the issue of abnormal parsing of Chinese nodes
  core/middleware/operation.go
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8791 ref: api auth
  core/init/router/router.go
  core/middleware/session.go
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8792 fix: fix issue with agent cpu usage error
  agent/utils/cmd/cmdx.go
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/zh-Hant.ts
  frontend/src/lang/modules/zh.ts
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8796 feat: change cmd timeout handle for core
  core/utils/cmd/cmdx.go
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8798 fix: fix close docker proxy
  frontend/src/views/setting/panel/proxy/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8799 feat: Refactor manual mode certificate application to increase succes rate
  agent/app/dto/request/website_ssl.go
  agent/app/service/website_ssl.go
  agent/utils/ssl/acme.go
  agent/utils/ssl/client.go
  agent/utils/ssl/custom_manual_provider.go
  agent/utils/ssl/manual_client.go
  frontend/src/api/interface/website.ts
  frontend/src/views/website/ssl/apply/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8800 feat： Add some prompts.
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/zh-Hant.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/app-store/setting/index.vue
  frontend/src/views/setting/panel/proxy/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8804 fix: fix issue with reload monitor page failed
  core/constant/common.go
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8811 fix: Fix the problem of Docker restarting caused by proxy sync
  agent/app/api/v2/docker.go
  agent/app/service/docker.go
  frontend/src/components/docker-proxy/dialog.vue
  frontend/src/components/docker-proxy/index.vue
  frontend/src/components/license-import/index.vue
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/zh-Hant.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/setting/license/bind/xpack.vue
  frontend/src/views/setting/license/index.vue
Labels: do-not-merge/release-note-label-needed, dev-v2

#8812 fix: Alibaba Cloud Disk ignores tls verification
  agent/utils/cloud_storage/client/ali.go
  core/utils/cloud_storage/client/ali.go
Labels: do-not-merge/release-note-label-needed, dev-v2

#8816 chore: Update README.md
  README.md
Labels: do-not-merge/release-note-label-needed

#8828 fix: Fix issue with duplicate nodes appearing after adding a node.
  frontend/src/components/docker-proxy/dialog.vue
Labels: do-not-merge/release-note-label-needed, dev-v2

#8833 fix: compose file edit env
  frontend/src/api/interface/container.ts
  frontend/src/views/container/compose/edit/index.vue
  frontend/src/views/container/compose/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8838 fix: fix issue with add node do not restart docker
  agent/app/service/docker.go
  frontend/src/api/interface/setting.ts
  frontend/src/views/setting/license/bind/xpack.vue
  frontend/src/views/setting/license/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8839 fix: change logic for the system proxy setting
  core/app/service/setting.go
  core/constant/common.go
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8845 fix: add restart-docker option when adding system proxy for the first…
  frontend/src/components/docker-proxy/dialog.vue
  frontend/src/views/setting/license/index.vue
  frontend/src/views/setting/panel/proxy/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8851 feat: Optimize file management style and increase file calculation
  frontend/src/views/host/file-management/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8862 fix: Resolve popup caused by node switching.
  core/init/migration/migrations/init.go
  frontend/src/components/backup/index.vue
  frontend/src/views/website/website/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8876 feat: change default runtime php image name
  frontend/src/views/website/runtime/php/create/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#8881 fix: Remote Redis connection
  agent/app/service/container.go
  agent/app/service/database_redis.go
  frontend/src/views/database/redis/index.vue
  frontend/src/views/database/redis/remote/operate/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2
