Repository 1Panel-dev/1Panel, pull requests merged in 2025-01, with the labels that each got.

#7621 feat(common): Optimize commonRepo Invocation
  agent/app/repo/common.go
  agent/app/repo/entry.go
  agent/app/repo/task.go
  agent/app/service/app.go
  agent/app/service/app_install.go
  agent/app/service/app_utils.go
  agent/app/service/backup.go
  agent/app/service/backup_app.go
  agent/app/service/backup_mysql.go
  agent/app/service/backup_postgresql.go
  agent/app/service/backup_website.go
  agent/app/service/clam.go
  agent/app/service/compose_template.go
  agent/app/service/container.go
  agent/app/service/container_compose.go
  agent/app/service/cronjob.go
  agent/app/service/cronjob_backup.go
  agent/app/service/cronjob_helper.go
  agent/app/service/dashboard.go
  agent/app/service/database.go
  agent/app/service/database_mysql.go
  agent/app/service/database_postgresql.go
  agent/app/service/database_redis.go
  agent/app/service/entry.go
  agent/app/service/favorite.go
  agent/app/service/file.go
  agent/app/service/ftp.go
  agent/app/service/image.go
  agent/app/service/image_repo.go
  agent/app/service/monitor.go
  agent/app/service/php_extensions.go
  agent/app/service/runtime.go
  agent/app/service/runtime_utils.go
  agent/app/service/snapshot.go
  agent/app/service/snapshot_create.go
  agent/app/service/snapshot_recover.go
  agent/app/service/snapshot_rollback.go
  agent/app/service/task.go
  agent/app/service/website.go
  agent/app/service/website_acme_account.go
  agent/app/service/website_ca.go
  agent/app/service/website_dns_account.go
  agent/app/service/website_ssl.go
  agent/app/service/website_utils.go
  agent/app/task/task.go
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#7626 feat: Save the theme color scheme to the client
  frontend/src/views/setting/panel/theme-color/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#7629 feat(appstore): Add MD5 Checksum for Custom Application Store Packages
  agent/app/service/app_install.go
  core/utils/files/files.go
Labels: do-not-merge/release-note-label-needed, dev-v2

#7631 feat: Increase version restrictions for node switching
  agent/configs/system.go
  agent/go.mod
  frontend/src/api/interface/setting.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/layout/components/Sidebar/index.vue
  frontend/src/utils/version.ts
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#7634 feat: Improve and format language files
  backend/app/dto/auth.go
  backend/i18n/i18n.go
  frontend/src/lang/modules/ms.ts
  frontend/src/views/home/index.vue
  frontend/src/views/login/components/login-form.vue
  frontend/src/views/setting/panel/index.vue
  frontend/src/views/toolbox/clam/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#7633 feat(website): Fix Issue with Creating Reverse Proxy Website
  agent/app/repo/app.go
  agent/app/repo/common.go
  agent/app/service/app.go
  agent/app/service/website_utils.go
  frontend/src/components/log-file/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#7636 feat(files): Fix Issue with Recycle Bin Failing to Enable
  agent/app/repo/setting.go
  agent/app/service/setting.go
  frontend/src/views/host/file-management/recycle-bin/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#7637 Update Default PHP Extensions
  backend/init/migration/migrations/v_1_9.go
Labels: do-not-merge/release-note-label-needed

#7437 WIP(Language management): Support Japanese by Google Translate
  backend/app/dto/auth.go
  backend/i18n/i18n.go
  backend/i18n/lang/jp.yaml
  frontend/src/lang/index.ts
  frontend/src/lang/modules/jp.ts
  frontend/src/views/login/components/login-form.vue
Labels: do-not-merge/release-note-label-needed, do-not-merge/work-in-progress

#7624 Traducao pt br
  backend/app/dto/auth.go
  backend/i18n/i18n.go
  backend/i18n/lang/pt-BR.yaml
  frontend/src/lang/index.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/views/login/components/login-form.vue
  frontend/src/views/setting/panel/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm

#7645 feat: Improve and format language files
  backend/app/dto/auth.go
  backend/i18n/i18n.go
  backend/i18n/lang/ja.yaml
  frontend/src/lang/index.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/views/login/components/login-form.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#7649 feat(appstore): Handle Website Directory During Second Installation o…
  agent/app/api/v2/file.go
  agent/app/model/app_install.go
  agent/app/service/app.go
  agent/app/service/app_utils.go
  agent/app/service/file.go
  agent/app/service/website_utils.go
  agent/i18n/lang/en.yaml
  agent/i18n/lang/zh-Hant.yaml
  agent/i18n/lang/zh.yaml
  agent/router/ro_file.go
  frontend/src/api/modules/files.ts
  frontend/src/components/task-list/index.vue
  frontend/src/components/task-log/index.vue
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/app-store/detail/params/index.vue
  frontend/src/views/app-store/installed/delete/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#7650 feat(common): Standardize Event Bus
  agent/cmd/server/nginx_conf/website_default.conf
  frontend/src/components/task-log/index.vue
  frontend/src/global/bus.ts
  frontend/src/layout/components/Sidebar/index.vue
  frontend/src/layout/index.vue
  frontend/src/views/app-store/detail/install/index.vue
  frontend/src/views/app-store/index.vue
  frontend/src/views/app-store/installed/delete/index.vue
  frontend/src/views/app-store/installed/upgrade/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#7654 feat: Panel aliases support common special characters
  frontend/src/views/setting/panel/name/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#7655 feat: Upgrade package version
  frontend/package.json
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#7656 feat: Improve international language proficiency
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/host/file-management/index.vue
  frontend/src/views/login/components/login-form.vue
  frontend/src/views/setting/panel/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#7659 feat(system): Fix Issue Allowing Access via Old Secure Entry After Mo…
  backend/init/router/router.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#7660 feat: Support for asynchronously obtaining the backup file size
  backend/app/api/v1/backup.go
  backend/app/dto/backup.go
  backend/app/service/backup.go
  backend/router/ro_setting.go
  frontend/src/api/interface/backup.ts
  frontend/src/api/modules/setting.ts
  frontend/src/components/backup/index.vue
  frontend/src/views/cronjob/backup/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#7661 fix: Fix the issue of frontend packaging errors
  frontend/vite.config.ts
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#7665 feat: Break long menu items into multiple lines
  frontend/src/layout/components/Sidebar/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#7666 feat: Internationalization language order
  frontend/src/views/login/components/login-form.vue
  frontend/src/views/setting/panel/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#7668 fix: Fix the issue of interface returning internationalization failure
  backend/i18n/i18n.go
  backend/i18n/lang/en.yaml
  backend/i18n/lang/pt-BR.yaml
  backend/i18n/lang/ru.yaml
  backend/i18n/lang/zh-Hant.yaml
  backend/i18n/lang/zh.yaml
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#7669 feat: Dealing with Sass version compatibility issues and removing debugger from build
  frontend/src/layout/components/Sidebar/components/SubItem.vue
  frontend/src/layout/components/Sidebar/index.scss
  frontend/src/layout/components/Sidebar/index.vue
  frontend/src/views/app-store/installed/index.vue
  frontend/vite.config.ts
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#7670 feat: Modify the copyright
  frontend/src/layout/components/AppFooter.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#7671 style: Optimize style and layout
  frontend/src/components/app-status/index.vue
  frontend/src/components/layout-content/index.vue
  frontend/src/components/router-button/index.vue
  frontend/src/views/app-store/apps/index.vue
  frontend/src/views/container/container/index.vue
  frontend/src/views/home/app/index.vue
  frontend/src/views/toolbox/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#7673 fix: Fix the issue of pagination errors in the backup list
  frontend/src/components/backup/index.vue
  frontend/src/components/upload/index.vue
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/cronjob/backup/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#7676 feat(appstore): Handle container restarting status for App
  agent/app/service/app.go
  agent/app/service/app_utils.go
  agent/constant/app.go
  agent/i18n/lang/en.yaml
  agent/i18n/lang/zh-Hant.yaml
  agent/i18n/lang/zh.yaml
  frontend/src/components/log-file/index.vue
  frontend/src/components/task-log/index.vue
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
Labels: do-not-merge/release-note-label-needed, dev-v2

#7680 feat: Change AppDto to AppItem
  backend/app/dto/response/app.go
  backend/app/service/app.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#7681 feat: Menu enables vue-router mode
  frontend/src/components/layout-content/index.vue
  frontend/src/layout/components/Sidebar/index.vue
  frontend/src/layout/index.vue
  frontend/vite.config.ts
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#7682 fix: Fix the issue of database cover exception display.
  frontend/src/components/app-status/index.vue
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/host/ssh/index.vue
  frontend/src/views/host/ssh/ssh/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#7685 feat: Update international address
  frontend/src/components/license-import/index.vue
  frontend/src/components/system-upgrade/index.vue
  frontend/src/views/setting/license/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#7686 feat: Modify international version functions
  frontend/src/views/setting/panel/hidemenu/index.vue
  frontend/src/views/website/runtime/php/create/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#7687 feat: Improve international language
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/setting/panel/proxy/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#7689 style: Optimize some internationalization styles
  frontend/src/App.vue
  frontend/src/lang/modules/ja.ts
  frontend/src/views/container/container/terminal/index.vue
  frontend/src/views/database/mysql/conn/index.vue
  frontend/src/views/home/index.vue
  frontend/src/views/website/website/config/basic/other/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#7690 feat: Save custom theme color scheme
  frontend/src/views/setting/panel/index.vue
  frontend/src/views/setting/panel/theme-color/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#7694 fix: Remove redundant code
  frontend/src/views/home/app/index.vue
Labels: do-not-merge/release-note-label-needed, dev

#7697 feat: Improve international language and style
  frontend/src/components/router-button/index.vue
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/views/database/mysql/conn/index.vue
  frontend/src/views/database/postgresql/conn/index.vue
  frontend/src/views/database/redis/conn/index.vue
  frontend/src/views/home/index.vue
  frontend/src/views/host/file-management/index.vue
  frontend/src/views/setting/panel/index.vue
  frontend/src/views/setting/safe/index.vue
  frontend/src/views/website/website/config/basic/other/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#7699 docs: add introduction of 1Panel Pro in README
  README.md
Labels: do-not-merge/release-note-label-needed

#7700 chore: Update README.md
  README.md
Labels: do-not-merge/release-note-label-needed

#7707 feat(log): Add Highlighting to Logs
  agent/app/service/container.go
  frontend/src/components/container-log/index.vue
  frontend/src/components/hightlight/index.vue
  frontend/src/components/log-file/index.vue
  frontend/src/components/task-log/index.vue
  frontend/src/views/log/system/index.vue
  frontend/src/views/log/website/index.vue
  frontend/src/views/website/website/config/log/log-fiile/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#7706 feat: Update Application Name Restrictions
  frontend/src/global/form-rules.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/app-store/detail/install/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#7708 feat(log): Handle Errors in Event Stream
  agent/app/service/container.go
  frontend/src/components/container-log/index.vue
  frontend/src/components/hightlight/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#7709 fix(website):Fix Reverse Proxy Deletion Failure in Certain Scenarios
  backend/app/api/v1/website.go
  backend/app/dto/request/website.go
  backend/app/service/website.go
  backend/router/ro_website.go
  frontend/src/api/interface/website.ts
  frontend/src/api/modules/website.ts
  frontend/src/views/website/website/config/basic/proxy/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#7710 feat: Update swagger docs
  backend/app/api/v1/backup.go
  cmd/server/docs/docs.go
  cmd/server/docs/swagger.json
  cmd/server/docs/swagger.yaml
  cmd/server/main.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#7714 feat: Add Multi-Language Support for Application Labels
  backend/app/api/v1/app.go
  backend/app/dto/app.go
  backend/app/dto/response/app.go
  backend/app/model/tag.go
  backend/app/service/app.go
  backend/init/migration/migrate.go
  backend/init/migration/migrations/v_1_10.go
  frontend/src/views/app-store/apps/index.vue
  frontend/src/views/app-store/installed/index.vue
Labels: do-not-merge/release-note-label-needed, dev

#7726 feat: Merge code from dev
  agent/app/service/image.go
  agent/constant/errs.go
  agent/i18n/lang/en.yaml
  agent/i18n/lang/zh-Hant.yaml
  agent/i18n/lang/zh.yaml
  agent/utils/firewall/client/firewalld.go
  agent/utils/firewall/client/ufw.go
  agent/utils/postgresql/client/remote.go
  frontend/package.json
  frontend/src/components/app-status/index.vue
  frontend/src/components/backup/index.vue
  frontend/src/components/codemirror-pro/index.vue
  frontend/src/components/copy-button/index.vue
  frontend/src/components/upload/index.vue
  frontend/src/global/form-rules.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/container/compose/create/index.vue
  frontend/src/views/container/container/index.vue
  frontend/src/views/container/container/operate/index.vue
  frontend/src/views/cronjob/backup/index.vue
  frontend/src/views/cronjob/helper.ts
  frontend/src/views/setting/license/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#7728 chore: Update README.md
  README.md
Labels: do-not-merge/release-note-label-needed

#7727 feat: Korean language support
  backend/app/dto/auth.go
  backend/i18n/i18n.go
  backend/i18n/lang/ko.yaml
  frontend/src/App.vue
  frontend/src/lang/index.ts
  frontend/src/lang/modules/en.ts
  frontend/src/lang/modules/ja.ts
  frontend/src/lang/modules/ko.ts
  frontend/src/lang/modules/ms.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/lang/modules/ru.ts
  frontend/src/lang/modules/tw.ts
  frontend/src/lang/modules/zh.ts
  frontend/src/views/login/components/login-form.vue
  frontend/src/views/setting/panel/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#7746 chore: Update README.md
  README.md
Labels: do-not-merge/release-note-label-needed

#7747 Update README.md
  README.md
Labels: do-not-merge/release-note-label-needed

#7754 fix: Fix OpenResty Installation Failure
  agent/app/service/app.go
  agent/go.mod
  agent/go.sum
  core/go.mod
  frontend/package.json
  frontend/src/components/task-log/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, dev-v2

#7757 fix: fix the issue of import cycle
  agent/app/service/app.go
  agent/app/service/app_utils.go
  agent/utils/files/file_op.go
  core/utils/req_helper/requset.go
Labels: do-not-merge/release-note-label-needed, dev-v2

#7758 feat: delete the test upload file of the backup account
  agent/app/dto/cronjob.go
  agent/app/service/backup.go
  core/app/service/backup.go
  core/app/task/task.go
  core/i18n/i18n.go
  core/i18n/lang/en.yaml
  core/i18n/lang/ja.yaml
  core/i18n/lang/ko.yaml
  core/i18n/lang/ms.yml
  core/i18n/lang/pt-BR.yaml
  core/i18n/lang/pt.yaml
  core/i18n/lang/zh-Hant.yaml
  core/i18n/lang/zh.yaml
  core/utils/cloud_storage/client/ali.go
  core/utils/cloud_storage/client/cos.go
  core/utils/cloud_storage/client/google_drive.go
  core/utils/cloud_storage/client/kodo.go
  core/utils/cloud_storage/client/local.go
  core/utils/cloud_storage/client/minio.go
  core/utils/cloud_storage/client/onedrive.go
  core/utils/cloud_storage/client/oss.go
  core/utils/cloud_storage/client/s3.go
  core/utils/cloud_storage/client/sftp.go
  core/utils/cloud_storage/client/up.go
  core/utils/cloud_storage/client/webdav.go
  core/utils/cloud_storage/cloud_storage_client.go
  frontend/package.json
  frontend/src/api/interface/cronjob.ts
  frontend/src/layout/components/Sidebar/index.vue
  frontend/src/views/cronjob/operate/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, dev-v2

#7761 feat: Unify the response body of the API interface
  backend/app/api/v1/app_install.go
  backend/app/api/v1/php_extensions.go
  cmd/server/docs/docs.go
  cmd/server/docs/swagger.json
  cmd/server/docs/swagger.yaml
  frontend/src/api/modules/app.ts
  frontend/src/api/modules/runtime.ts
  frontend/src/views/website/runtime/php/create/index.vue
  frontend/src/views/website/website/create/index.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#7763 fix: remove duplicate code
  agent/app/repo/backup.go
  agent/app/service/clam.go
  agent/app/service/docker.go
  agent/init/migration/migrate.go
  agent/init/migration/migrations/init.go
  core/init/migration/migrations/init.go
  frontend/src/api/interface/container.ts
  frontend/src/components/status/index.vue
  frontend/src/views/container/setting/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#7764 feat: Added password encryption for login functionality
  backend/app/repo/common.go
  backend/app/repo/setting.go
  backend/app/service/app.go
  backend/app/service/auth.go
  backend/app/service/setting.go
  backend/init/business/business.go
  backend/init/router/router.go
  backend/middleware/password_rsa.go
  backend/utils/encrypt/encrypt.go
  frontend/package.json
  frontend/src/global/form-rules.ts
  frontend/src/lang/modules/pt-br.ts
  frontend/src/utils/util.ts
  frontend/src/views/login/components/login-form.vue
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved

#7768 feat: Installed Openresty and added automatic directory creation.
  agent/app/service/app.go
  agent/init/migration/migrations/init.go
  core/constant/common.go
  frontend/package.json
  frontend/src/views/website/runtime/php/create/index.vue
  frontend/src/views/website/website/nginx/status/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, dev-v2

#7769 fix: complete the missing international content
  agent/i18n/lang/zh.yaml
  core/app/api/v2/helper/helper.go
  core/i18n/lang/zh.yaml
  core/utils/req_helper/requset.go
Labels: do-not-merge/release-note-label-needed, lgtm, approved, dev-v2

#7775 feat: Runtime environment supports running without port configuration
  agent/app/dto/request/runtime.go
  agent/app/dto/response/runtime.go
  agent/app/model/runtime.go
  agent/app/repo/common.go
  agent/app/repo/runtime.go
  agent/app/service/runtime.go
  agent/app/service/runtime_utils.go
  agent/cmd/server/conf/app.yaml
  frontend/src/api/interface/runtime.ts
  frontend/src/components/drawer-pro/index.vue
  frontend/src/views/app-store/setting/index.vue
  frontend/src/views/website/runtime/dotnet/index.vue
  frontend/src/views/website/runtime/dotnet/operate/index.vue
  frontend/src/views/website/runtime/environment/index.vue
  frontend/src/views/website/runtime/go/index.vue
  frontend/src/views/website/runtime/go/operate/index.vue
  frontend/src/views/website/runtime/java/index.vue
  frontend/src/views/website/runtime/java/operate/index.vue
  frontend/src/views/website/runtime/node/index.vue
  frontend/src/views/website/runtime/node/operate/index.vue
  frontend/src/views/website/runtime/port/index.vue
  frontend/src/views/website/runtime/python/index.vue
  frontend/src/views/website/runtime/python/operate/index.vue
  frontend/src/views/website/runtime/volume/index.vue
  frontend/src/views/website/website/create/index.vue
  frontend/src/views/website/website/index.vue
Labels: do-not-merge/release-note-label-needed, lgtm, dev-v2

#7777 feat: Application details have been enhanced with tags.
  backend/app/dto/response/app.go
  backend/app/model/app.go
  backend/app/service/app.go
  backend/app/service/app_utils.go
Labels: do-not-merge/release-note-label-needed, dev, lgtm, approved
